In [6]:
zipfile <- "HH_flux.zip"

In [7]:

setwd("/mnt/gsdata/projects/panops/panops-data-registry/data/flux")

In [ ]:
### load the libraries
library(data.table)
library(future)
library(stringr)
library(future.apply)

zipfile <- "HH_flux.zip"   # or "flux_HH.zip" if that’s the real name

wanted_cols <- c(
  "TIMESTAMP_START", "TIMESTAMP_END",
  "TA_F", "TA_F_QC", "VPD_F", "VPD_F_QC", "P_F", "P_F_QC",
  "TS_F_MDS_1", "TS_F_MDS_2", "TS_F_MDS_1_QC", "TS_F_MDS_2_QC",
  "WS_F", "WS_F_QC",
  "SWC_F_MDS_1", "SWC_F_MDS_2", "SWC_F_MDS_1_QC", "SWC_F_MDS_2_QC",
  "H_CORR", "H_RANDUNC", "H_RANDUNC_N", "NEE_VUT_REF_RANDUNC_N",
  "LE_F_MDS", "LE_F_MDS_QC", "LE_CORR", "LE_RANDUNC", "LE_RANDUNC_N",
  "H_F_MDS", "H_F_MDS_QC", "CO2_F_MDS", "CO2_F_MDS_QC",
  "NEE_VUT_REF", "NEE_VUT_REF_QC", "NEE_VUT_50", "NEE_VUT_50_QC",
  "NEE_VUT_REF_RANDUNC",
  "GPP_NT_VUT_REF", "GPP_DT_VUT_REF", "GPP_NT_VUT_50", "GPP_DT_VUT_50",
  "RECO_NT_VUT_REF", "RECO_DT_VUT_REF", "RECO_NT_VUT_50", "RECO_DT_VUT_50",
  "SW_IN_F", "SW_IN_F_QC", "PPFD_IN", "PPFD_DIF", "PPFD_OUT",
  "TA_F_MDS", "TA_F_MDS_QC", "VPD_F_MDS",
  "SW_IN_F_MDS", "SW_IN_F_MDS_QC", "SW_IN_POT",
  "LW_IN_F", "LW_OUT", "SW_OUT", "NETRAD",
  "USTAR", "WS", "G_F_MDS", "G_F_MDS_QC", "RH", "NIGHT", "PA"
)

outdir <- "merged_sites_subset"
dir.create(outdir, showWarnings = FALSE)

data.table::setDTthreads(2)

# list files in zip, no extraction
zip_files <- unzip(zipfile, list = TRUE)
csv_files <- zip_files$Name[
  grepl("\\.csv$", zip_files$Name) &
  !grepl("^__MACOSX/", zip_files$Name)
]

extract_site <- function(x) {
  str_extract(basename(x), "[A-Z]{2}-[A-Za-z0-9]+")
}

site_ids     <- extract_site(csv_files)
unique_sites <- unique(site_ids[!is.na(site_ids)])

length(unique_sites)
head(unique_sites)

# robust streaming reader
safe_fread_cmd <- function(cmd) {
  fread(cmd = cmd, showProgress = FALSE, fill = Inf)
}

read_file_from_zip <- function(fname_in_zip) {
  cmd <- sprintf("unzip -p %s %s | tr -d '\\000'",
                 shQuote(zipfile), shQuote(fname_in_zip))
  dt <- safe_fread_cmd(cmd)
  
  if (nrow(dt) > 0) {
    col1 <- dt[[1]]
    if (is.character(col1)) {
      bad  <- grepl("^Mac OS X", col1, useBytes = TRUE) |
              grepl("com\\.apple\\.quarantine", col1, useBytes = TRUE)
      if (any(bad)) dt <- dt[!bad]
    }
  }
  
  dt
}

[1] 521

[1] "US-Wi0" "ZA-Kru" "US-xWR" "AU-ASM" "CA-Gro" "JP-BBY"

Function to process a single site

This will:
	1.	Find all files for that site.
	2.	Read each file from the zip.
	3.	Keep only wanted_cols that actually exist in that file.
	4.	Row-bind all those pieces.
	5.	Remove duplicate rows for the same timestamp(s).
	6.	Write one <SITE>_merged.csv in merged_sites_subset.

In [10]:
process_one_site <- function(site) {
  tryCatch({
    message("=== Processing site: ", site, " ===")
    
    site_files <- csv_files[site_ids == site]
    if (length(site_files) == 0L) {
      message("   no files found in zip for site ", site)
      return(FALSE)
    }
    
    dt_list <- vector("list", length(site_files))
    
    for (i in seq_along(site_files)) {
      f <- site_files[i]
      message("   reading file: ", f)
      
      dt <- read_file_from_zip(f)
      if (nrow(dt) == 0L) next
      
      keep <- intersect(wanted_cols, names(dt))
      if (length(keep) == 0L) next
      
      dt_list[[i]] <- dt[, ..keep]
    }
    
    dt_list <- Filter(function(x) !is.null(x) && nrow(x) > 0L, dt_list)
    if (length(dt_list) == 0L) {
      message("   no usable data for site ", site)
      return(FALSE)
    }
    
    dt_all <- rbindlist(dt_list, use.names = TRUE, fill = TRUE)
    rm(dt_list); gc()
    
    key_cols <- intersect(c("TIMESTAMP_START", "TIMESTAMP_END"), names(dt_all))
    if (length(key_cols) > 0L) {
      setkeyv(dt_all, key_cols)
      dt_all <- unique(dt_all)
    } else {
      dt_all <- unique(dt_all)
    }
    
    out_path <- file.path(outdir, paste0(site, "_merged.csv"))
    if (file.exists(out_path)) file.remove(out_path)
    
    fwrite(dt_all, out_path)
    
    rm(dt_all); gc()
    TRUE
  }, error = function(e) {
    message("   ERROR for site ", site, ": ", conditionMessage(e))
    FALSE
  })
}

Parallel processing on HPC (without eating 128 cores)

In [ ]:
# polite parallelism
data.table::setDTthreads(2)
n_workers <- 16
plan(multisession, workers = n_workers)

# restartable: skip sites that already have a merged file
existing   <- list.files(outdir, pattern = "_merged\\.csv$", full.names = FALSE)
sites_done <- extract_site(existing)
sites_to_do <- setdiff(unique_sites, sites_done)

length(sites_to_do)

res <- future_lapply(sites_to_do, process_one_site)

table(unlist(res))

[1] 503

Quick check

In [6]:
table(site_ids)

site_ids
AR-Bal AR-CCa AR-CCg AR-SLu AR-TF1 AR-TF2 AR-Vir AT-Neu AU-Ade AU-Adr AU-ASM
     2      2      2      2      2      2      2      2      2      2      2
AU-Boy AU-Cpr AU-Cum AU-DaP AU-DaS AU-Dry AU-Emr AU-Fog AU-Gin AU-GWW AU-How
     2      4      4      2      2      2      2      2      2      2      2
AU-Lit AU-Lon AU-Lox AU-RDF AU-Rgf AU-Rig AU-Rob AU-Stp AU-TTE AU-Tum AU-Wac
     2      2      2      2      2      2      2      4      2      2      2
AU-War AU-Whr AU-Wom AU-Ync BE-Bra BE-Dor BE-Lcr BE-Lon BE-Maa BE-Vie BR-CST
     2      2      2      2      4      4      2      4      4      4      2
BR-Npw BR-Sa1 BR-Sa3 CA-ARB CA-ARF CA-BOU CA-Ca1 CA-Ca2 CA-Cbo CA-CF1 CA-DB2
     2      2      2      2      2      2      2      2      2      2      2
CA-DBB CA-DSM CA-EM1 CA-EM2 CA-ER1 CA-Gro CA-HPC CA-LP1 CA-MA1 CA-MA2 CA-MA3
     2      2      2      2      2      2      2      2      2      2      2
CA-Man CA-Mer CA-Mtk CA-NS1 CA-NS2 CA-NS3 CA-NS4 CA-NS5 CA-NS6 CA-NS7 CA-Oas
     2      2      2      2      2      2      2      2      2      2      2
CA-Obs CA-Qc2 CA-Qfo CA-SCB CA-SCC CA-SF1 CA-SF2 CA-SF3 CA-SMC CA-TP1 CA-TP2
     2      2      2      2      2      2      2      2      2      2      2
CA-TP3 CA-TP4 CA-TPD CD-Ygb CG-Tch CH-Aws CH-Cha CH-Dav CH-Frk CH-Fru CH-Lae
     2      2      2      2      2      2      2      4      2      2      2
CH-Oe1 CH-Oe2 CL-ACF CL-SDF CL-SDP CN-Cha CN-Cng CN-Dan CN-Din CN-Du2 CN-Du3
     2      2      2      2      2      2      2      2      2      2      2
CN-Ha2 CN-HaM CN-Qia CN-Sw2 CR-Fsc CZ-BK1 CZ-BK2 CZ-KrP CZ-Lnz CZ-RAJ CZ-Stn
     2      2      2      2      2      4      2      2      4      2      2
CZ-wet DE-Akm DE-Geb DE-Gri DE-Hai DE-Har DE-Hdn DE-HoH DE-Hte DE-Hzd DE-Kli
     4      2      4      4      2      2      2      4      2      4      4
DE-Lkb DE-Lnf DE-Msr DE-Obe DE-Rns DE-RuC DE-RuR DE-RuS DE-RuW DE-Seh DE-SfN
     2      2      2      2      2      2      2      4      2      2      2
DE-SfS DE-Spw DE-Tha DE-Zrk DK-Eng DK-Fou DK-Gds DK-RCW DK-Skj DK-Sor DK-Vng
     2      2      4      2      2      2      2      2      2      4      4
EE-Pts ES-Abr ES-Agu ES-Amo ES-Cnd ES-LgS ES-LJu ES-LM1 ES-LM2 ES-LMa ES-Ln2
     2      2      2      2      2      2      2      2      2      2      2
ES-Pdu FI-Hyy FI-Jok FI-Ken FI-Let FI-Lom FI-Qvd FI-Sii FI-Sod FI-Var FR-Aur
     2      4      2      4      4      2      2      2      4      2      4
FR-Bil FR-CLt FR-EM2 FR-FBn FR-Fon FR-Gri FR-Hes FR-Lam FR-LBr FR-LGt FR-Lus
     4      2      2      4      4      4      4      2      2      2      2
FR-Mej FR-Pue FR-Tou GF-Guy GH-Ank GL-Dsk GL-NuF GL-ZaF GL-ZaH IE-CaC IE-CaN
     2      4      2      4      2      2      6      4      2      2      2
IE-Cra IE-Gwr IL-Yat IT-BCi IT-BFt IT-BsB IT-Bsn IT-CA1 IT-CA2 IT-CA3 IT-Col
     2      2      2      4      2      2      2      2      2      2      2
IT-Cp2 IT-Cpz IT-Isp IT-La2 IT-Lav IT-Lsn IT-MBo IT-MtM IT-MtP IT-Niv IT-Noe
     4      2      2      2      2      4      4      2      2      4      4
IT-PT1 IT-Ren IT-Ro1 IT-Ro2 IT-SR2 IT-SRo IT-Tor IT-TrF JP-BBY JP-MBF JP-SMF
     2      4      2      2      4      2      4      2      2      2      2
MX-Tes MY-PSO NL-Hor NL-Loo NO-Hur PA-SPn PA-SPs PE-QFR RU-Che RU-Cok RU-Fy2
     2      2      2      4      2      2      2      2      2      2      2
RU-Fy3 RU-Fyo RU-Ha1 RU-Sam RU-SkP RU-Tks RU-Vrk SD-Dem SE-Deg SE-Htm SE-Nor
     2      2      2      2      2      2      2      2      4      4      4
SE-Ros SE-St1 SE-Sto SE-Svb SJ-Adv SJ-Blv SN-Dhr UK-AMo US-A32 US-A37 US-A39
     2      2      2      4      2      2      2      4      2      2      2
US-A74 US-Akn US-ALQ US-AR1 US-AR2 US-ARb US-ARc US-ARM US-ASH US-ASM US-Atq
     2      2      2      2      2      2      2      2      2      2      2
US-Bar US-Bi1 US-Bi2 US-Blo US-BRG US-BZB US-BZF US-BZo US-BZS US-CAK US-CdM
     2      2      2      2      2      2      2      2      2      2      2
US-CF1 US-CF2 US-CF3 US-CF4 US-CGG US-Cms US-Cop US-CRK US-CRT US-CS1 US-CS2
     2      2      2      2      2      2      2      2      2      2      2
US-CS3 US-CS4 US-CS5 US-CS6 US-CS8 US-Cst US-DFC US-DFK US-Dmg US-DPW US-DS1
     2      2      2      2      2      2      2      2      2      2      2
US-DS2 US-DS3 US-EA5 US-EA6 US-EDN US-Elm US-EML US-Esm US-EvM US-Fcr US-Fmf
     2      2      2      2      2      2      2      2      2      2      2
US-Fuf US-Fwf US-GBT US-GLE US-Goo US-Ha1 US-HB1 US-HB2 US-HB3 US-HB4 US-Hn2
     2      2      2      2      2      2      2      2      2      2      2
US-Hn3 US-Ho1 US-Ho2 US-Hsm US-HVs US-HWB US-IB2 US-ICh US-ICs US-ICt US-Ivo
     2      2      2      2      2      2      2      2      2      2      2
US-Jo1 US-Jo2 US-KFS US-KLS US-Kon US-KPL US-KS1 US-KS2 US-KS3 US-LA3 US-Lin
     2      2      2      2      2      2      2      2      2      2      2
US-Los US-LS2 US-LWW US-Me1 US-Me2 US-Me3 US-Me4 US-Me5 US-Me6 US-MMS US-MN1
     2      2      2      2      2      2      2      2      2      2      2
US-MN2 US-MN3 US-Mo1 US-Mo2 US-Mo3 US-MOz US-Mpj US-MtB US-Myb US-NC1 US-NC3
     2      2      2      2      2      2      2      2      2      2      2
US-NC4 US-Ne1 US-Ne2 US-Ne3 US-NGB US-NGC US-NR1 US-Oho US-ONA US-ORv US-OWC
     2      2      2      2      2      2      2      2      2      2      2
US-PAS US-PFa US-PFb US-PFc US-PFd US-PFe US-PFg US-PFh US-PFj US-PFk US-PFL
     2      2      2      2      2      2      2      2      2      2      2
US-PFm US-PFn US-PFp US-PFq US-PFr US-PFt US-Pnp US-Prr US-PSH US-PSL US-RGA
     2      2      2      2      2      2      2      2      2      2      2
US-RGB US-RGF US-RGo US-RGW US-Rls US-Rms US-Ro1 US-Ro2 US-Ro3 US-Ro4 US-Ro5
     2      2      2      2      2      2      2      2      2      2      2
US-Ro6 US-Rpf US-RRC US-Rwe US-Rwf US-Rws US-Sag US-Seg US-Ses US-SHC US-Slt
     2      2      2      2      2      2      2      2      2      2      2
US-Sne US-Snf US-SP1 US-SRC US-SRG US-SRM US-Srr US-SRS US-SSH US-Sta US-StJ
     2      2      2      2      2      2      2      2      2      2      2
US-Syv US-Ton US-Tw1 US-Tw2 US-Tw3 US-Tw4 US-Tw5 US-Twt US-UC1 US-UC2 US-UM3
     2      2      2      2      2      2      2      2      2      2      2
US-UMB US-UMd US-UTB US-UTD US-UTE US-UTJ US-UTP US-UTV US-Var US-Vcm US-Vcp
     4      2      2      2      2      2      2      2      2      2      2
US-WCr US-Whs US-Wi0 US-Wi1 US-Wi2 US-Wi3 US-Wi4 US-Wi5 US-Wi6 US-Wi7 US-Wi8
     2      2      2      2      2      2      2      2      2      2      2
US-Wi9 US-Wjs US-Wkg US-WPT US-xAB US-xAE US-xBA US-xBL US-xBN US-xBR US-xCL
     2      2      2      2      2      2      2      2      2      2      2
US-xCP US-xDC US-xDJ US-xDL US-xDS US-xGR US-xHA US-xHE US-xJE US-xJR US-xKA
     2      2      2      2      2      2      2      2      2      2      2
US-xKZ US-xMB US-xML US-xNG US-xNQ US-xNW US-xRM US-xRN US-xSB US-xSC US-xSE
     2      2      2      2      2      2      2      2      2      2      2
US-xSJ US-xSL US-xSR US-xST US-xTA US-xTL US-xTR US-xUK US-xUN US-xWD US-xWR
     2      2      2      2      2      2      2      2      2      2      2
US-xYE US-YK2 ZA-Kru ZM-Mon
     2      2      2      2

In [7]:
View(unique_sites)
length(unique_sites)

  [1] "US-Wi0" "ZA-Kru" "US-xWR" "AU-ASM" "CA-Gro" "JP-BBY" "US-Srr" "US-Fwf"
  [9] "CN-Cng" "US-Ho2" "US-RGo" "US-CS4" "US-ASM" "CR-Fsc" "GL-ZaF" "UK-AMo"
 [17] "AU-Rob" "FR-Lam" "AU-Wom" "US-SRM" "US-Myb" "NL-Loo" "AU-Rgf" "US-PFh"
 [25] "US-Me2" "US-Ro6" "US-PFb" "CA-NS7" "BR-Sa3" "US-Pnp" "US-Wi9" "US-Me5"
 [33] "US-xCP" "FR-Gri" "RU-Tks" "IT-Lav" "US-PFt" "US-PSL" "US-RGF" "DE-Kli"
 [41] "US-xBA" "US-xUN" "CN-Ha2" "SE-Deg" "SE-Svb" "AU-Lox" "US-PAS" "IT-Noe"
 [49] "ES-Pdu" "DK-RCW" "CA-Ca1" "CH-Fru" "FR-EM2" "US-UTV" "DE-RuS" "RU-Fy3"
 [57] "ES-LM2" "US-Ne1" "US-HB1" "US-DS3" "US-Vcm" "CA-TP4" "US-UMB" "CH-Aws"
 [65] "US-Tw5" "DE-Lkb" "US-HB2" "DE-Geb" "CZ-BK1" "DK-Sor" "CA-NS6" "DE-Hzd"
 [73] "IL-Yat" "GL-ZaH" "US-BRG" "US-IB2" "US-Wi6" "FR-Mej" "AR-TF1" "CA-MA2"
 [81] "US-xDJ" "US-Ne2" "RU-Cok" "US-Ro4" "US-xJR" "AU-Cpr" "PA-SPn" "CA-HPC"
 [89] "GH-Ank" "RU-Ha1" "US-MMS" "US-PFc" "US-xWD" "US-Ho1" "US-Me4" "AU-Dry"
 [97] "US-KFS" "US-RGW" "RU-SkP" "CA-NS1" "US-PFd" "US-Rwe" "US-NC4" "CA-DBB"
[105] "BE-Lon" "BE-Maa" "CA-EM1" "US-NC1" "DE-RuR" "US-Tw2" "DE-Zrk" "IT-BsB"
[113] "CA-SMC" "IT-MBo" "US-ICt" "CZ-KrP" "FR-Fon" "CL-SDP" "US-LA3" "US-Jo2"
[121] "DE-SfS" "AU-Emr" "US-CS6" "US-KS2" "DK-Skj" "US-Wi1" "US-CAK" "CA-MA3"
[129] "DE-Msr" "AU-Fog" "US-MOz" "US-A74" "US-CdM" "FI-Var" "US-MtB" "FR-Hes"
[137] "AU-Rig" "FI-Ken" "US-Bar" "CA-DB2" "CZ-Lnz" "US-DFC" "IE-CaN" "US-Me6"
[145] "FI-Let" "US-UMd" "CN-Din" "AR-Bal" "US-Hn3" "US-UTP" "US-DS1" "FI-Hyy"
[153] "CZ-wet" "US-MN2" "FR-FBn" "CA-Ca2" "US-KPL" "CD-Ygb" "US-DFK" "US-LS2"
[161] "CN-Qia" "FR-Aur" "CL-SDF" "US-xMB" "DE-Seh" "US-Fmf" "AR-SLu" "US-xST"
[169] "US-CF1" "US-xSE" "US-AR2" "AU-Lit" "US-CGG" "US-Mo1" "US-xSB" "ES-LJu"
[177] "IT-La2" "CA-TP1" "US-Twt" "FI-Sii" "IT-SRo" "CA-Mer" "IE-Cra" "IT-SR2"
[185] "CZ-RAJ" "DK-Fou" "US-BZo" "US-PFr" "AR-Vir" "AR-CCa" "DE-Akm" "US-xHE"
[193] "AU-GWW" "US-Esm" "US-CS5" "DE-Hai" "DE-Tha" "US-Wi4" "FI-Qvd" "AU-Wac"
[201] "IT-BCi" "US-PFn" "CA-DSM" "DE-Rns" "US-xJE" "US-Elm" "BE-Bra" "SE-Htm"
[209] "US-Tw3" "DE-Hdn" "CN-Dan" "US-BZF" "US-MN3" "US-Ton" "US-Fuf" "US-RRC"
[217] "US-UM3" "US-Seg" "FR-Bil" "US-Wi3" "AT-Neu" "US-NGC" "ES-LMa" "GF-Guy"
[225] "MY-PSO" "BE-Lcr" "US-UTJ" "CH-Oe1" "US-xDL" "US-xSR" "IE-Gwr" "US-Ro2"
[233] "US-xSC" "US-xRN" "US-GBT" "CA-Obs" "US-Wi5" "CA-SF2" "US-UC2" "FR-LGt"
[241] "US-Cop" "GL-Dsk" "DE-Gri" "IT-PT1" "CA-TPD" "US-Syv" "DE-Hte" "ES-LM1"
[249] "ES-Amo" "AU-Cum" "GL-NuF" "IT-Bsn" "CL-ACF" "CA-Man" "PA-SPs" "US-SRS"
[257] "US-Wjs" "US-RGB" "US-Kon" "US-WCr" "SJ-Blv" "CA-SF1" "US-Sag" "US-Ro3"
[265] "CA-SCC" "CA-ARB" "DE-RuC" "RU-Sam" "US-A39" "IT-Ro1" "US-xBL" "IT-CA3"
[273] "US-PFe" "US-xTR" "US-xCL" "US-Rwf" "CA-Qc2" "CH-Cha" "CG-Tch" "DE-Spw"
[281] "DE-RuW" "US-PFa" "US-Rpf" "US-Vcp" "IT-TrF" "US-SP1" "US-AR1" "US-UTB"
[289] "CZ-Stn" "IT-MtM" "US-OWC" "AU-TTE" "ES-Ln2" "IT-Lsn" "CA-TP2" "CH-Dav"
[297] "CA-TP3" "BE-Vie" "DK-Vng" "CH-Oe2" "US-MN1" "US-ARM" "CN-Du3" "US-BZB"
[305] "CN-Sw2" "US-SRG" "BE-Dor" "RU-Fyo" "IT-Niv" "US-Sta" "IE-CaC" "US-Slt"
[313] "IT-Ren" "US-Wi8" "CA-SF3" "CH-Lae" "CA-EM2" "US-xKA" "ES-LgS" "CA-SCB"
[321] "US-PFm" "US-Tw1" "AU-Adr" "US-PFg" "AU-Boy" "US-xAB" "US-xHA" "US-Me1"
[329] "US-Wi7" "IT-BFt" "US-xTA" "CN-Du2" "AU-RDF" "US-YK2" "CZ-BK2" "US-CRK"
[337] "US-Snf" "FR-CLt" "US-ICh" "ZM-Mon" "US-xBN" "US-Tw4" "CA-LP1" "US-xSL"
[345] "FI-Sod" "US-Mo3" "US-CS8" "AU-Stp" "ES-Agu" "FR-Lus" "IT-Isp" "US-UC1"
[353] "US-ORv" "JP-SMF" "EE-Pts" "US-CF4" "US-Hn2" "RU-Che" "DE-Har" "US-Rms"
[361] "IT-CA1" "US-xNG" "IT-MtP" "US-Ne3" "US-CF3" "US-DS2" "US-Cst" "US-xNQ"
[369] "AU-Ade" "US-Rls" "FR-Pue" "ES-Abr" "US-Var" "AU-DaS" "US-CS3" "CA-ARF"
[377] "US-Dmg" "US-StJ" "IT-Tor" "US-PFL" "FI-Lom" "US-EML" "CA-Qfo" "US-Rws"
[385] "US-CF2" "US-Blo" "US-Goo" "US-PFk" "SE-Nor" "IT-Col" "US-RGA" "IT-Ro2"
[393] "NL-Hor" "US-BZS" "US-Prr" "AR-CCg" "FR-Tou" "US-KS1" "DK-Gds" "US-KS3"
[401] "CA-ER1" "US-Bi1" "US-Ses" "AU-Tum" "CA-Cbo" "US-Wi2" "BR-Sa1" "US-A37"
[409] "US-Jo1" "IT-Cpz" "US-Fcr" "CA-Mtk" "FR-LBr" "US-Lin" "US-EA5" "CA-NS4"
[417] "US-Ro5" "US-PSH" "US-PFp" "PE-QFR" "US-ARc" "CH-Frk" "US-xAE" "US-Wkg"
[425] "US-Me3" "NO-Hur" "ES-Cnd" "SD-Dem" "CN-Cha" "US-Bi2" "DE-Lnf" "IT-Cp2"
[433] "IT-CA2" "BR-CST" "SN-Dhr" "AU-Gin" "AU-Whr" "CA-NS2" "CA-MA1" "US-Hsm"
[441] "SE-Sto" "US-CRT" "US-WPT" "FI-Jok" "US-CS2" "CA-NS5" "DE-SfN" "CA-Oas"
[449] "DE-HoH" "US-NC3" "US-LWW" "US-xSJ" "US-xRM" "US-SHC" "US-Whs" "SE-Ros"
[457] "US-CS1" "AU-War" "US-UTD" "US-xDS" "JP-MBF" "DE-Obe" "AU-Lon" "US-EA6"
[465] "US-xYE" "MX-Tes" "US-Oho" "US-Akn" "US-KLS" "SJ-Adv" "CA-BOU" "SE-St1"
[473] "US-ARb" "US-ASH" "US-EDN" "US-Sne" "RU-Fy2" "US-Los" "US-xKZ" "US-Ha1"
[481] "US-HWB" "RU-Vrk" "US-EvM" "US-SRC" "US-HVs" "US-xBR" "US-DPW" "US-PFj"
[489] "CA-CF1" "US-ICs" "US-PFq" "US-xTL" "US-xUK" "US-Mpj" "US-Cms" "US-SSH"
[497] "US-ALQ" "US-xNW" "US-ONA" "CN-HaM" "US-HB3" "US-UTE" "DK-Eng" "AR-TF2"
[505] "BR-Npw" "US-xDC" "US-xGR" "US-NGB" "US-Ivo" "AU-Ync" "US-A32" "US-Atq"
[513] "US-HB4" "CA-NS3" "AU-How" "US-Ro1" "US-GLE" "AU-DaP" "US-Mo2" "US-NR1"
[521] "US-xML"

[1] 521

Loop through each site and merge all datasets
(522 unique sites are exist)

In [37]:
outdir <- "merged_sites"
dir.create(outdir, showWarnings = FALSE)

data.table::setDTthreads(8)  # be nice to the server

safe_fread_file <- function(path) {
  cmd <- sprintf("tr -d '\\000' < %s", shQuote(path))
  fread(cmd = cmd, showProgress = FALSE, fill = TRUE)
}

for (site in unique_sites) {
  
  message("Processing: ", site)
  
  site_files  <- csv_files[site_ids == site]
  merged_path <- file.path(outdir, paste0(site, "_merged.csv"))
  first_write <- TRUE
  
  for (f in site_files) {
    
    # extract only this file
    unzip(zipfile, files = f, exdir = tempdir(), overwrite = TRUE)
    full_path <- file.path(tempdir(), f)
    
    # read robustly (strip NUL bytes)
    dt <- safe_fread_file(full_path)
    
    # append to merged file
    if (first_write) {
      fwrite(dt, merged_path)
      first_write <- FALSE
    } else {
      fwrite(dt, merged_path, append = TRUE)
    }
    
    file.remove(full_path)
  }
  
  # now de-duplicate
  dt_all <- safe_fread_file(merged_path)
  timestamp_cols <- grep("TIMESTAMP|DATE|time", names(dt_all),
                         ignore.case = TRUE, value = TRUE)

  if (length(timestamp_cols) > 0) {
    dt_all <- unique(dt_all, by = timestamp_cols)
  } else {
    dt_all <- unique(dt_all)
  }
  
  fwrite(dt_all, merged_path)
  rm(dt_all); gc()
}

Processing: US-Wi0

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Previous fread() session was not cleaned up properly. Cleaned up ok at the beginning of this fread() call.”
Processing: ZA-Kru

Processing: US-xWR

Processing: AU-ASM

Processing: CA-Gro

Processing: JP-BBY

Processing: US-Srr

Processing: US-Fwf

Processing: CN-Cng

Processing: FI-Ken

Processing: US-Ho2

Processing: US-RGo

Processing: US-CS4

Processing: US-ASM

Processing: CR-Fsc

Processing: GL-ZaF

Processing: AU-Rob

Processing: FR-Lam

Processing: AU-Wom

Processing: US-SRM

Processing: NL-Loo

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 35090. Expected 166 fields but found 234. Consider fill=234 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<199601010000,199601010030,-9999,-9999,-2.104,-2.104,2,0,-9999,-9999,0,0,2,-9999,-9999,310.265,310.265,2,-9999,-9999,298.898,298.898,2,-9999,-9999,0,0,2,-9999,99.659,99.659,2,-9999,0.133,0.133,2,-9999,1.35,1.35,2,-9999,0.54,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,5.086,3,4.91712,-9999,-9999,-9999,-9999,-9999,-9999,-1.41,0,-1.3618,-9999,-9999,-9999,-9999,-9999,-9999,55,3,1,5.32068,5.32068,3,3,-9999,-9>>”
Processing: US-Myb

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 210387. Expected 219 fields but found 221. Consider fill=221 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<201001010000,201001010030,-9999,-9999,10.183,10.183,2,0,-9999,-9999,0,0,2,-9999,-9999,336.219,336.219,2,-9999,-9999,350.831,350.831,2,-9999,-9999,3.07,3.07,2,-9999,102.898,102.898,2,-9999,0,0,2,-9999,2.134,2.134,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,18.8346,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-38.2873,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,->>”
Processing: GL-ZaH

Processing: AU-Rgf

Processing: US-PFh

Processing: US-Me2

Processing: US-Ro6

Processing: US-MMS

Processing: US-PFb

Processing: CA-NS7

Processing: BR-Sa3

Processing: US-Pnp

Processing: US-Wi9

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 35091. Expected 143 fields but found 145. Consider fill=145 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200401010000,200401010030,-9999,-9999,-13.854,-13.854,2,0,0,0,0,0,0,-9999,-9999,187.016,187.016,2,-9999,-9999,185.192,185.192,2,-9999,-9999,0,0,2,-9999,97.933,97.933,2,-9999,0,0,2,-9999,0.835,0.835,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-0.794333,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-10.1711,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,-1.192,3,-9999,-9999,-9999,-9999,-0.306545,3,-9999,-9999,-9999,-9999,-0.273717,0,0.100166,-1.2555,-1.1496,-0.731167,-0.306545>>”
Processing: US-Me5

Processing: US-xCP

Processing: RU-Tks

Processing: IT-Lav

Processing: US-PFt

Processing: US-PSL

Processing: US-RGF

Processing: FI-Let

Processing: US-xBA

Processing: US-xUN

Processing: CN-Ha2

Processing: CA-NS1

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 87651. Expected 224 fields but found 226. Consider fill=226 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200101010000,200101010030,-9999,-9999,-15.108,-15.108,2,0,-9999,-9999,0,0,2,-9999,-9999,197.288,197.288,2,-9999,-9999,188.946,188.946,2,-9999,-9999,0.991,0.991,2,-9999,98.389,98.389,2,-9999,0,0,2,-9999,2.91,2.91,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-0.5714,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-73.5993,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,5.95906,6.5695,3,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-999>>”
Processing: SE-Deg

Processing: SE-Svb

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 122739. Expected 236 fields but found 242. Consider fill=242 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<201901010000,201901010030,-9999,-9999,-0.829,-0.829,2,0,-9999,-9999,0,0,2,-9999,-9999,291.03,291.03,2,-9999,-9999,282.64,282.64,2,-9999,-9999,1.613,1.613,2,-9999,97.832,97.832,2,-9999,0.006,0.006,2,-9999,1.871,1.871,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,4.172,3,2.32628,-9999,-9999,-9999,-9999,-9999,-9999,-39.9371,3,-22.2099,>>”
Processing: IT-Cp2

Processing: AU-Lox

Processing: US-PAS

Processing: ES-Pdu

Processing: CA-Ca1

Processing: CD-Ygb

Processing: CH-Fru

Processing: US-UTV

Processing: RU-Fy3

Processing: ES-LM2

Processing: US-Ne1

Processing: DE-Har

Processing: FR-Gri

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 70130. Expected 242 fields but found 255. Consider fill=255 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200401010000,200401010030,-9999,-9999,1.311,1.311,2,0,-9999,-9999,0,0,2,-9999,-9999,323.382,323.382,2,-9999,-9999,322.471,322.471,2,-9999,-9999,0.836,0.836,2,-9999,101.012,101.012,2,-9999,0.001,0.001,2,-9999,1.14,1.14,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-1.2>>”
Processing: US-Tw1

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 52611. Expected 223 fields but found 229. Consider fill=229 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<201101010000,201101010030,-9999,-9999,6.361,6.361,2,0,-9999,-9999,0,0,2,-9999,-9999,332.062,332.062,2,-9999,-9999,327.95,327.95,2,-9999,-9999,3.743,3.743,2,-9999,101.812,101.812,2,-9999,0.599,0.599,2,-9999,2.352,2.352,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,15.8272,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-57.5872,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,3.11625,2.49885,3,3,-9999,-99>>”
Processing: US-HB1

Processing: US-DS3

Processing: US-Cop

Processing: US-Vcm

Processing: CA-TP4

Processing: US-UMB

Processing: CH-Aws

Processing: US-Tw5

Processing: DE-Lkb

Processing: US-HB2

Processing: DE-Geb

Processing: DK-Sor

Processing: CA-NS6

Processing: DE-Hzd

Processing: IL-Yat

Processing: IT-Noe

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 35042. Expected 162 fields but found 234. Consider fill=234 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<202201010000,202201010030,5.322,3,15.283,15.283,2,0,0,3,0,0,2,283.827,3,324.25,324.25,2,242.299,3,325.007,325.007,2,3.129,3,6.009,6.009,2,-9999,101.799,101.799,2,-9999,0,0,2,-9999,0.88,0.88,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,405.767,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-14.1076,3,0.196929,3,0.279259,0.189744,0.357128,2.17981,2,31,2.18334,-41.4968,3,-58.3983,-75.2539,-39.9828,23.8899,2,4,35.4168,42,1,1,2.08207,1.5704,3,3,0.7949>>”
Processing: US-BRG

Processing: DK-RCW

Processing: US-IB2

Processing: US-Wi6

Processing: FR-Mej

Processing: AR-TF1

Processing: CA-MA2

Processing: US-xDJ

Processing: US-Ne2

Processing: CA-NS2

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 87651. Expected 224 fields but found 226. Consider fill=226 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200101010000,200101010030,-9999,-9999,-17.114,-17.114,2,0,-9999,-9999,0,0,2,-9999,-9999,194.22,194.22,2,-9999,-9999,177.052,177.052,2,-9999,-9999,1.151,1.151,2,-9999,98.349,98.349,2,-9999,0.001,0.001,2,-9999,3.495,3.495,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-0.354583,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-13.8811,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,3.80005,3.80005,3,3,-9999,-9999,-9999,-9999>>”
Processing: RU-Cok

Processing: BE-Lcr

Processing: US-Ro4

Processing: US-xJR

Processing: AU-Cpr

Processing: PA-SPn

Processing: CA-HPC

Processing: GH-Ank

Processing: RU-Ha1

Processing: US-PFc

Processing: US-xWD

Processing: US-Ho1

Processing: US-Me4

Processing: AU-Dry

Processing: FR-Lqu

Processing: US-KFS

Processing: US-RGW

Processing: RU-SkP

Processing: US-Wi5

Processing: CA-NS4

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 70131. Expected 224 fields but found 228. Consider fill=228 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200101010000,200101010030,-9999,-9999,-16.839,-16.839,2,0,-9999,-9999,0,0,2,-9999,-9999,197.288,197.288,2,-9999,-9999,187.954,187.954,2,-9999,-9999,0.99,0.99,2,-9999,98.389,98.389,2,-9999,0.001,0.001,2,-9999,1.732,1.732,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-0.156333,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-10.641,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,-0.0287778,-0.0287778,3,3,-9999,-9999,-9999,>>”
Processing: US-PFd

Processing: FR-Bil

Processing: US-Rwe

Processing: US-NC4

Processing: DK-Skj

Processing: CA-DBB

Processing: BE-Lon

Processing: FR-EM2

Processing: BE-Maa

Processing: CA-EM1

Processing: US-NC1

Processing: US-Tw2

Processing: DE-Zrk

Processing: US-CRT

Processing: IT-BsB

Processing: CA-SMC

Processing: CZ-BK1

Processing: IT-MBo

Processing: US-ICt

Processing: CZ-KrP

Processing: GL-Dsk

Processing: DE-Gri

Processing: FR-Fon

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 280515. Expected 218 fields but found 263. Consider fill=263 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<201901010000,201901010030,-9999,-9999,8.475,8.475,2,0,-9999,-9999,0,0,2,-9999,-9999,333.105,333.105,2,-9999,-9999,344.865,344.865,2,-9999,-9999,2.251,2.251,2,-9999,100.376,100.376,2,-9999,0.011,0.011,2,-9999,1.317,1.317,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9>>”
Processing: CL-SDP

Processing: US-LA3

Processing: US-Jo2

Processing: DE-SfS

Processing: AU-Emr

Processing: US-CS6

Processing: US-KS2

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 140259. Expected 218 fields but found 222. Consider fill=222 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200301010000,200301010030,18.86,0,20.74,18.86,0,0,0,0,0,0,0,-9999,-9999,414.155,414.155,2,350.213,0,454.247,350.213,0,0.6,0,3.356,0.6,0,101.3,101.329,101.3,0,8.382,1.874,8.382,0,0.935,3.89,0.935,0,78.4,0.158,97.2,-28.73,0,379.79,0,-9999,-9999,-9999,-9999,-9999,-9999,1.10409,1,1.46804,-9999,-9999,3.04359,2,222,-9999,-28.3888,3,-37.7379,-9999,-9999,-9999,-9999,-9999,-9999,55,3,1,3.50183,3.43371,3,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,3.5988,3.43371,3,3,-9999,-9999,-9999,-9999,-9999,-99>>”
Processing: US-Wi1

Processing: US-CAK

Processing: CA-MA3

Processing: DK-Gds

Processing: AU-Fog

Processing: US-MOz

Processing: US-A74

Processing: CZ-wet

Processing: US-CdM

Processing: US-Wi8

Processing: US-MtB

Processing: FR-Hes

Processing: AU-Rig

Processing: US-Bar

Processing: CA-DB2

Processing: CZ-Lnz

Processing: US-DFC

Processing: IE-CaN

Processing: US-Me6

Processing: US-UMd

Processing: CN-Din

Processing: AR-Bal

Processing: US-Hn3

Processing: US-UTP

Processing: FR-Pue

Processing: US-DS1

Processing: US-MN2

Processing: CA-Ca2

Processing: FR-FBn

Processing: US-KPL

Processing: US-DFK

Processing: US-LS2

Processing: US-Me1

Processing: CN-Qia

Processing: US-Oho

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 175347. Expected 223 fields but found 224. Consider fill=224 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200401010000,200401010030,-0.049,1,-2.783,-0.049,1,0,0.59,0,0,0.59,0,-9999,-9999,227.361,227.361,2,269.577,1,212.706,269.577,1,0.943,1,1.034,0.943,1,-9999,99.659,99.659,2,-9999,0,0,2,-9999,1.305,1.305,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,374.045,1,3.816,1.648,0,0,19.84,0,-6.2745,0,9.96838,1,11.6227,2.06978,15.5968,5.67077,2,295,11.5198,-15.1366,1,-17.5947,-23.6831,-3.14289,14.3218,2,122,20.9034,258,1,1,0.31793,0.266868,1,1,0.929892,0.934461,2,2,220,223,0.930257,1.04508,0.31793,0.266868,1,>>”
Processing: FR-Aur

Processing: IT-BFt

Processing: CL-SDF

Processing: BE-Vie

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 175395. Expected 242 fields but found 244. Consider fill=244 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<199601010000,199601010030,-9999,-9999,1.802,1.802,2,0,-9999,-9999,0,0,2,-9999,-9999,325.707,325.707,2,-9999,-9999,328.341,328.341,2,-9999,-9999,0.249,0.249,2,-9999,94.434,94.434,2,-9999,0.032,0.032,2,-9999,1.616,1.616,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-0.068605,3,-0.0442907,-9999,-9999,-9999,-9999,-9999,-9999,-0.07774,3,>>”
Processing: US-xMB

Processing: DE-Seh

Processing: IT-Ren

Processing: US-Fmf

Processing: AR-SLu

Processing: US-xST

Processing: US-CF1

Processing: US-xSE

Processing: US-AR2

Processing: ES-LMa

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 87699. Expected 238 fields but found 240. Consider fill=240 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<202001010000,202001010030,2.021,1,5.241,2.021,1,0,0,0,0,0,0,297.573,1,327.471,297.573,1,236.945,1,339.718,236.945,1,0.229,1,1.535,0.229,1,-9999,99.837,99.837,2,-9999,0,0,2,-9999,0.701,0.701,2,-9999,-9999,-9999,-9999,-9999,431.137,1,5.739,6.124,6.596,7.406,9.475,1,1,1,1,1,22.995,22.103,21.065,43.172,45.312,50.735,1,1,1,1,1,1,-9999,-9999,2.19894,-9999,-9999,-9999,-9999,3.78777,2,338,-9999,2.91027,-9999,-9999,-9999,-9999,9.94314,2,230,-9999,-9999,-9999,1,2.00724,1.95882,1,1,1.2755,1.0679,2,2,7,9,1.>>”
Processing: AU-Lit

Processing: US-CGG

Processing: US-Mo1

Processing: NO-Hur

Processing: US-xSB

Processing: ES-LJu

Processing: IT-La2

Processing: CA-TP1

Processing: US-Twt

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 157779. Expected 183 fields but found 221. Consider fill=221 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200901010000,200901010030,-9999,-9999,3.602,3.602,2,0,-9999,-9999,0,0,2,-9999,-9999,258.345,258.345,2,-9999,-9999,277.918,277.918,2,-9999,-9999,0.603,0.603,2,-9999,102.096,102.096,2,-9999,0,0,2,-9999,3.91,3.91,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,41.137,3,47.9092,-9999,-9999,-9999,-9999,-9999,-9999,-78.3625,3,-91.2066,-9999,-9999,-9999,-9999,-9999,-9999,55,3,1,1.23604,1.23604,3,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1.23604,1.23604,3,3,-9999,-9999,>>”
Processing: US-ORv

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 17523. Expected 148 fields but found 217. Consider fill=217 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<201101010000,201101010030,14.396,0,12.827,14.396,0,0,-9999,-9999,0,0,2,-9999,-9999,322.384,322.384,2,346.388,0,348.932,346.388,0,5.277,0,3.732,5.277,0,-9999,98.961,98.961,2,-9999,0.007,0.007,2,2.872,2.063,2.872,0,240.55,0.394,67.835,-9999,368.97,0,-9999,-9999,-9999,-9999,-5.745,0,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-55.682,0,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,3.36472,3.36472,1,1,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,3.36472,3.36472,1,1,-9999,-9999,-9999,-9999>>”
Processing: IT-SRo

Processing: CA-Mer

Processing: IE-Cra

Processing: IT-SR2

Processing: CZ-RAJ

Processing: DK-Fou

Processing: CH-Dav

Processing: US-BZo

Processing: US-PFr

Processing: AR-Vir

Processing: AR-CCa

Processing: DE-Akm

Processing: US-xHE

Processing: AU-GWW

Processing: FI-Hyy

Processing: US-Esm

Processing: US-CS5

Processing: FI-Sod

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 35090. Expected 169 fields but found 226. Consider fill=226 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200101010000,200101010030,-14.033,0,-18.647,-14.033,0,0,0,0,0,0,0,-9999,-9999,216.855,216.855,2,155.915,0,186.605,155.915,0,0.21,0,0.056,0.21,0,-9999,98.11,98.11,2,-9999,0,0,2,0.91,1.248,0.91,0,-9999,-9999,89.833,-9999,-0.38,381.579,1,-3.68,-3.54,0,0,1.58,2.21,0,0,-1.836,-9999,-0.0993667,1,0.00703702,-9999,-9999,0.869388,2,69,-9999,-12.004,1,0.850157,-9999,-9999,9.29143,2,137,-9999,55,3,1,-0.0934588,-0.101827,1,1,0.545104,0.52264,2,2,63,71,0.545714,0.523266,-0.10619,-0.101827,1,1,0.512146,0.5226>>”
Processing: DE-Hai

Processing: US-Wi4

Processing: FI-Qvd

Processing: AU-Wac

Processing: US-PFn

Processing: CA-DSM

Processing: DE-Rns

Processing: US-xJE

Processing: US-Elm

Processing: CA-NS5

Processing: SE-Htm

Processing: US-Tw3

Processing: DE-Hdn

Processing: CN-Dan

Processing: US-BZF

Processing: US-MN3

Processing: DE-RuS

Warning message in fread(cmd = cmd, showProgress = FALSE, fill = TRUE):

ERROR: Error in fwrite(dt, merged_path): Input/output error: 'merged_sites/US-Ro2_merged.csv'

In [11]:
outdir <- "merged_sites"

In [12]:
existing   <- list.files(outdir, pattern = "_merged\\.csv$", full.names = FALSE)
sites_done <- str_extract(existing, "[A-Z]{2}-[A-Za-z0-9]+")
sites_to_do <- setdiff(unique_sites, sites_done)

sites_done
sites_to_do  # this should include US-Ro2 and the ones after it in the original loop

  [1] "AR-Bal" "AR-CCa" "AR-SLu" "AR-TF1" "AR-Vir" "AT-Neu" "AU-ASM" "AU-Cpr"
  [9] "AU-Dry" "AU-Emr" "AU-Fog" "AU-GWW" "AU-Lit" "AU-Lox" "AU-Rgf" "AU-Rig"
 [17] "AU-Rob" "AU-Wac" "AU-Wom" "BE-Lcr" "BE-Lon" "BE-Maa" "BE-Vie" "BR-Sa3"
 [25] "CA-Ca1" "CA-Ca2" "CA-DB2" "CA-DBB" "CA-DSM" "CA-EM1" "CA-Gro" "CA-HPC"
 [33] "CA-MA2" "CA-MA3" "CA-Mer" "CA-NS1" "CA-NS2" "CA-NS4" "CA-NS5" "CA-NS6"
 [41] "CA-NS7" "CA-Obs" "CA-SMC" "CA-TP1" "CA-TP4" "CA-TPD" "CD-Ygb" "CH-Aws"
 [49] "CH-Dav" "CH-Fru" "CH-Oe1" "CL-SDF" "CL-SDP" "CN-Cng" "CN-Dan" "CN-Din"
 [57] "CN-Ha2" "CN-Qia" "CR-Fsc" "CZ-BK1" "CZ-KrP" "CZ-Lnz" "CZ-RAJ" "CZ-wet"
 [65] "DE-Akm" "DE-Geb" "DE-Gri" "DE-Hai" "DE-Har" "DE-Hdn" "DE-Hzd" "DE-Lkb"
 [73] "DE-Rns" "DE-RuS" "DE-Seh" "DE-SfS" "DE-Zrk" "DK-Fou" "DK-Gds" "DK-RCW"
 [81] "DK-Skj" "DK-Sor" "ES-LJu" "ES-LM2" "ES-LMa" "ES-Pdu" "FI-Hyy" "FI-Ken"
 [89] "FI-Let" "FI-Qvd" "FI-Sod" "FR-Aur" "FR-Bil" "FR-EM2" "FR-FBn" "FR-Fon"
 [97] "FR-Gri" "FR-Hes" "FR-Lam" "FR-Lqu" "FR-Mej" "FR-Pue" "GF-Guy" "GH-Ank"
[105] "GL-Dsk" "GL-ZaF" "GL-ZaH" "IE-CaN" "IE-Cra" "IE-Gwr" "IL-Yat" "IT-BCi"
[113] "IT-BFt" "IT-BsB" "IT-Cp2" "IT-La2" "IT-Lav" "IT-MBo" "IT-Noe" "IT-Ren"
[121] "IT-SR2" "IT-SRo" "JP-BBY" "MY-PSO" "NL-Loo" "NO-Hur" "PA-SPn" "RU-Cok"
[129] "RU-Fy3" "RU-Ha1" "RU-SkP" "RU-Tks" "SE-Deg" "SE-Htm" "SE-Svb" "US-A74"
[137] "US-AR2" "US-ASM" "US-Bar" "US-BRG" "US-BZF" "US-BZo" "US-CAK" "US-CdM"
[145] "US-CF1" "US-CGG" "US-Cop" "US-CRT" "US-CS4" "US-CS5" "US-CS6" "US-DFC"
[153] "US-DFK" "US-DS1" "US-DS3" "US-Elm" "US-Esm" "US-Fmf" "US-Fuf" "US-Fwf"
[161] "US-GBT" "US-HB1" "US-HB2" "US-Hn3" "US-Ho1" "US-Ho2" "US-IB2" "US-ICt"
[169] "US-Jo2" "US-KFS" "US-KPL" "US-KS2" "US-LA3" "US-LS2" "US-Me1" "US-Me2"
[177] "US-Me4" "US-Me5" "US-Me6" "US-MMS" "US-MN2" "US-MN3" "US-Mo1" "US-MOz"
[185] "US-MtB" "US-Myb" "US-NC1" "US-NC4" "US-Ne1" "US-Ne2" "US-NGC" "US-NR1"
[193] "US-Oho" "US-ORv" "US-PAS" "US-PFb" "US-PFc" "US-PFd" "US-PFh" "US-PFn"
[201] "US-PFr" "US-PFt" "US-Pnp" "US-PSL" "US-RGF" "US-RGo" "US-RGW" "US-Ro2"
[209] "US-Ro4" "US-Ro6" "US-RRC" "US-Rwe" "US-Seg" "US-SRM" "US-Srr" "US-Ton"
[217] "US-Tw1" "US-Tw2" "US-Tw3" "US-Tw5" "US-Twt" "US-UM3" "US-UMB" "US-UMd"
[225] "US-UTJ" "US-UTP" "US-UTV" "US-Vcm" "US-Whs" "US-Wi0" "US-Wi1" "US-Wi3"
[233] "US-Wi4" "US-Wi5" "US-Wi6" "US-Wi8" "US-Wi9" "US-xBA" "US-xCP" "US-xDJ"
[241] "US-xDL" "US-xHE" "US-xJE" "US-xJR" "US-xMB" "US-xRN" "US-xSB" "US-xSC"
[249] "US-xSE" "US-xSR" "US-xST" "US-xUN" "US-xWD" "US-xWR" "ZA-Kru"

  [1] "CA-SF2" "US-UC2" "CA-Qfo" "FR-LGt" "US-ARM" "CA-TP3" "IT-PT1" "US-Syv"
  [9] "DE-Hte" "ES-LM1" "ES-Amo" "AU-Cum" "SE-Nor" "GL-NuF" "IT-Bsn" "CL-ACF"
 [17] "CA-Man" "PA-SPs" "US-SRS" "US-Wjs" "US-RGB" "US-Kon" "US-WCr" "SJ-Blv"
 [25] "CA-SF1" "US-Sag" "US-Ro3" "CA-SCC" "CA-ARB" "DE-RuC" "RU-Sam" "US-A39"
 [33] "IT-Ro1" "US-xBL" "US-ARc" "IT-CA3" "US-PFe" "US-xTR" "US-xCL" "US-Rwf"
 [41] "CA-Qc2" "UK-AMo" "CH-Cha" "CG-Tch" "US-Me3" "DE-Spw" "US-PFa" "US-Rpf"
 [49] "US-Vcp" "US-Prr" "US-SP1" "US-AR1" "US-UTB" "DE-RuW" "CZ-Stn" "IT-MtM"
 [57] "US-OWC" "SE-Sto" "AU-TTE" "ES-Ln2" "CA-TP2" "DK-Vng" "CH-Oe2" "DE-RuR"
 [65] "US-GLE" "US-MN1" "CN-Du3" "US-BZB" "CN-Sw2" "US-SRG" "US-Tw4" "RU-Fyo"
 [73] "FI-Var" "IT-Niv" "DE-HoH" "US-Sta" "IE-CaC" "CA-NS3" "US-Slt" "DE-Msr"
 [81] "CA-SF3" "CH-Lae" "CA-EM2" "US-xKA" "ES-LgS" "CA-SCB" "US-PFm" "AU-Adr"
 [89] "US-PFg" "AU-Boy" "US-xAB" "US-xHA" "US-Wi7" "US-xTA" "CN-Du2" "DE-Kli"
 [97] "AU-RDF" "US-YK2" "BE-Bra" "CZ-BK2" "US-CRK" "US-Snf" "US-ICh" "IT-TrF"
[105] "ZM-Mon" "US-xBN" "BE-Dor" "CA-LP1" "US-xSL" "US-Mo3" "US-CS8" "AU-Stp"
[113] "ES-Agu" "IT-Isp" "US-UC1" "JP-SMF" "EE-Pts" "US-CF4" "US-Hn2" "RU-Che"
[121] "US-Rms" "IT-CA1" "US-xNG" "IT-MtP" "US-Ne3" "US-CF3" "US-DS2" "US-Cst"
[129] "US-xNQ" "AU-Ade" "US-Rls" "IT-Tor" "ES-Abr" "US-Var" "FI-Sii" "AU-DaS"
[137] "US-CS3" "CA-ARF" "US-Dmg" "US-StJ" "US-PFL" "FI-Lom" "US-EML" "US-Rws"
[145] "US-CF2" "US-Blo" "US-Goo" "US-Lin" "US-PFk" "IT-Col" "US-RGA" "IT-Ro2"
[153] "NL-Hor" "US-BZS" "AR-CCg" "FR-Tou" "US-KS1" "US-KS3" "CA-ER1" "US-Bi1"
[161] "US-Ses" "AU-Tum" "US-Ha1" "CA-Cbo" "US-Wi2" "BR-Sa1" "US-A37" "US-Jo1"
[169] "IT-Cpz" "US-Fcr" "CA-Mtk" "FR-LBr" "US-EA5" "US-Ro5" "US-PSH" "DE-Tha"
[177] "US-PFp" "PE-QFR" "CH-Frk" "US-xAE" "US-Wkg" "ES-Cnd" "SD-Dem" "CN-Cha"
[185] "US-Bi2" "DE-Lnf" "IT-Lsn" "IT-CA2" "BR-CST" "SN-Dhr" "US-ARb" "AU-Gin"
[193] "AU-Whr" "FR-CLt" "US-WPT" "CA-MA1" "US-Hsm" "FI-Jok" "US-CS2" "DE-SfN"
[201] "CA-Oas" "US-NC3" "US-LWW" "US-xSJ" "US-xRM" "US-SHC" "SE-Ros" "US-CS1"
[209] "AU-War" "US-UTD" "US-xDS" "JP-MBF" "DE-Obe" "AU-Lon" "US-EA6" "US-xYE"
[217] "MX-Tes" "US-Akn" "US-KLS" "SJ-Adv" "CA-BOU" "SE-St1" "US-ASH" "US-EDN"
[225] "US-Sne" "RU-Fy2" "US-Los" "US-xKZ" "US-HWB" "RU-Vrk" "US-EvM" "US-SRC"
[233] "US-HVs" "US-xBR" "US-DPW" "US-PFj" "CA-CF1" "US-ICs" "US-PFq" "US-xTL"
[241] "US-xUK" "US-Mpj" "US-Cms" "US-SSH" "FR-Lus" "US-ALQ" "US-xNW" "US-ONA"
[249] "CN-HaM" "US-HB3" "US-UTE" "DK-Eng" "AR-TF2" "BR-Npw" "US-xDC" "US-xGR"
[257] "US-NGB" "US-Ivo" "AU-Ync" "US-A32" "US-Atq" "US-HB4" "AU-How" "US-Ro1"
[265] "AU-DaP" "US-Mo2" "US-xML"

In [13]:
safe_fread_file <- function(path) {
  cmd <- sprintf("tr -d '\\000' < %s", shQuote(path))
  data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE)
}

data.table::setDTthreads(8)

for (site in sites_to_do) {
  message("=== Processing site: ", site, " ===")
  
  site_files  <- csv_files[site_ids == site]
  merged_path <- file.path(outdir, paste0(site, "_merged.csv"))
  
  # in case US-Ro2_merged.csv exists but is corrupted/partial
  if (file.exists(merged_path)) file.remove(merged_path)
  
  first_write <- TRUE
  
  for (f in site_files) {
    unzip(zipfile, files = f, exdir = tempdir(), overwrite = TRUE)
    full_path <- file.path(tempdir(), f)
    
    dt <- safe_fread_file(full_path)
    
    data.table::fwrite(dt, merged_path,
                       append = !first_write)
    first_write <- FALSE
    
    file.remove(full_path)
  }
  
  dt_all <- safe_fread_file(merged_path)
  ts_cols <- grep("TIMESTAMP|DATE|time", names(dt_all),
                  ignore.case = TRUE, value = TRUE)
  if (length(ts_cols) > 0) {
    dt_all <- unique(dt_all, by = ts_cols)
  } else {
    dt_all <- unique(dt_all)
  }
  data.table::fwrite(dt_all, merged_path)
  rm(dt_all); gc()
}

=== Processing site: CA-SF2 ===

=== Processing site: US-UC2 ===

=== Processing site: CA-Qfo ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 140259. Expected 226 fields but found 228. Consider fill=228 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200301010000,200301010030,-9999,-9999,-7.385,-7.385,2,0,-9999,-9999,0,0,2,-9999,-9999,241.792,241.792,2,-9999,-9999,220.415,220.415,2,-9999,-9999,0.528,0.528,2,-9999,96.124,96.124,2,-9999,0.047,0.047,2,-9999,2.779,2.779,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,0.663125,3,0.964118,-9999,-9999,-9999,-9999,-9999,-9999,-1.885,3,-2.73864,-9999,-9999,-9999,-9999,-9999,-9999,55,3,1,2.42933,0.9465,3,3,-9999,-9999,-999>>”
=== Processing site: FR-LGt ===

=== Processing site: US-ARM ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 175347. Expected 225 fields but found 260. Consider fill=260 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200301010000,200301010030,0.116,2,0.412,0.412,2,0,-9999,-9999,0,0,2,295.024,2,241.052,241.052,2,235.917,2,230.672,230.672,2,2.349,2,1.832,1.832,2,-9999,97.43,97.43,2,-9999,0,0,2,-9999,2.143,2.143,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,383.348,2,4.469,-9999,-9999,3.298,-9999,2.288,-9999,-9999,-9999,-9999,-9999,2,-9999,-9999,2,-9999,2,-9999,-9999,-9999,-9999,-9999,27.139,-9999,29.604,-9999,-9999,-9999,-9999,-9999,-9999,2,-9999,2,-9999,-9999,-9999,-9999,-9999,-9999,-20.4805,2,46.01>>”
=== Processing site: CA-TP3 ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 227907. Expected 222 fields but found 231. Consider fill=231 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200201010000,200201010030,-7.987,0,1.822,-7.987,0,0,0,0,0,0,0,-9999,-9999,314.832,314.832,2,200.715,0,338.243,200.715,0,0.323,0,2.402,0.323,0,-9999,99.003,99.003,2,-9999,0.495,0.495,2,2.125,1.395,2.125,0,277.72,-9999,90.367,-68.681,0,0,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,15.75,15.9,14.55,0,0,0,-0.0272069,3,9.53189,3,11.7328,-9999,-9999,-9999,-9999,-9999,-9999,-37.4666,3,-46.0341,-9999,-9999,-9999,-9999,-9999,-9999,55,3,1,-0.6174,-0.6174,3,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,->>”
=== Processing site: IT-PT1 ===

=== Processing site: US-Syv ===

=== Processing site: DE-Hte ===

=== Processing site: ES-LM1 ===

=== Processing site: ES-Amo ===

=== Processing site: AU-Cum ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 157778. Expected 223 fields but found 225. Consider fill=225 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<201201010000,201201010030,-9999,-9999,16.44,16.44,2,0,-9999,-9999,0,0,2,-9999,-9999,337.998,337.998,2,-9999,-9999,348.826,348.826,2,-9999,-9999,2.908,2.908,2,-9999,100.978,100.978,2,-9999,0,0,2,-9999,0.963,0.963,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1.64286,3,2.50245,-9999,-9999,-9999,-9999,-9999,-9999,-4.28571,3,-6.52548,-9999,-9999,-9999,-9999,-9999,-9999,48,3,1,1.77571,1.77571,3,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1.775>>”
=== Processing site: SE-Nor ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 245475. Expected 237 fields but found 242. Consider fill=242 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<201401010000,201401010030,4.278,0,4.608,4.278,0,0,0,0,0,0,0,319.109,0,318.955,319.109,0,299.609,0,321.782,299.609,0,1.247,0,1.342,1.247,0,100.833,100.741,100.833,0,-9999,0,0,2,3.159,3.462,3.159,0,150.684,0.680754,84.9644,-14.6054,0,0,0,0,333.022,405.605,0,3.278,3.398,3.579,3.975,4.242,0,0,0,0,0,35.05,24.848,20.418,25.73,26.492,0,0,0,0,0,-1.79875,0,0.225435,0,0.0244511,-0.0190982,0.129196,2.50709,1,39,2.5095,-17.048,0,-1.73311,-9.77015,1.44426,12.3023,1,39,14.8477,206,1,1,2.27068,2.27068,1,1,0.93>>”
=== Processing site: GL-NuF ===

=== Processing site: IT-Bsn ===

=== Processing site: CL-ACF ===

=== Processing site: CA-Man ===

=== Processing site: PA-SPs ===

=== Processing site: US-SRS ===

=== Processing site: US-Wjs ===

=== Processing site: US-RGB ===

=== Processing site: US-Kon ===

=== Processing site: US-WCr ===

=== Processing site: SJ-Blv ===

=== Processing site: CA-SF1 ===

=== Processing site: US-Sag ===

=== Processing site: US-Ro3 ===

=== Processing site: CA-SCC ===

=== Processing site: CA-ARB ===

=== Processing site: DE-RuC ===

=== Processing site: RU-Sam ===

=== Processing site: US-A39 ===

=== Processing site: IT-Ro1 ===

=== Processing site: US-xBL ===

=== Processing site: US-ARc ===

=== Processing site: IT-CA3 ===

=== Processing site: US-PFe ===

=== Processing site: US-xTR ===

=== Processing site: US-xCL ===

=== Processing site: US-Rwf ===

=== Processing site: CA-Qc2 ===

=== Processing site: UK-AMo ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 315602. Expected 236 fields but found 238. Consider fill=238 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<202101010000,202101010030,-9999,-9999,0.568,0.568,2,0,-9999,-9999,0,0,2,-9999,-9999,295.886,295.886,2,-9999,-9999,290.526,290.526,2,-9999,-9999,0.778,0.778,2,-9999,93.918,93.918,2,-9999,0,0,2,-9999,5.158,5.158,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-0.546364,3,-0.347205,-9999,-9999,-9999,-9999,-9999,-9999,-31.462,3,-19.9054,-9999,-9999,-9999,-9999,->>”
=== Processing site: CH-Cha ===

=== Processing site: CG-Tch ===

=== Processing site: US-Me3 ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 105219. Expected 224 fields but found 226. Consider fill=226 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200401010000,200401010030,-1.67,0,-0.743,-1.67,0,0,-9999,-9999,0,0,2,-9999,-9999,297.327,297.327,2,-9999,-9999,291.47,291.47,2,0.25,2,5.059,5.059,2,-9999,89.679,89.679,2,0,0,0,0,0.869,1.007,0.869,0,126.9,0.101,-9999,0.926,0,-9999,-9999,431.921,0,0.563,1.678,0,0,17.75,0,-9999,-9999,3.298,0,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-3.431,0,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,0.724834,1.42791,3,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,0.724834,1.42791,3,2,-9999,-9999,->>”
=== Processing site: DE-Spw ===

=== Processing site: US-PFa ===

=== Processing site: US-Rpf ===

=== Processing site: US-Vcp ===

=== Processing site: US-Prr ===

=== Processing site: US-SP1 ===

=== Processing site: US-AR1 ===

=== Processing site: US-UTB ===

=== Processing site: DE-RuW ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 227955. Expected 199 fields but found 243. Consider fill=243 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<201201010000,201201010030,-9999,-9999,7.777,7.777,2,0,-9999,-9999,0,0,2,-9999,-9999,351.272,351.272,2,-9999,-9999,343.367,343.367,2,-9999,-9999,0.266,0.266,2,-9999,93.761,93.761,2,0.1,0.031,0.1,0,-9999,3.333,3.333,2,-9999,-9999,-9999,-9999,-9999,-9999,377.877,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-4.7021,3,43.9433,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-41.3262,-9999,-9999,-9999,->>”
=== Processing site: CZ-Stn ===

=== Processing site: IT-MtM ===

=== Processing site: US-OWC ===

=== Processing site: SE-Sto ===

=== Processing site: AU-TTE ===

=== Processing site: ES-Ln2 ===

=== Processing site: CA-TP2 ===

=== Processing site: DK-Vng ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 175298. Expected 218 fields but found 245. Consider fill=245 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<202001010000,202001010030,-9999,-9999,2.919,2.919,2,0,-9999,-9999,0,0,2,-9999,-9999,265.498,265.498,2,-9999,-9999,257.916,257.916,2,-9999,-9999,0.847,0.847,2,-9999,102.28,102.28,2,-9999,0,0,2,-9999,2.289,2.289,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-3.456,3,-0.397273,-9999,-9999,-9999,-9999,-9999,-9999,-32.23,3,-3.64155>>”
=== Processing site: CH-Oe2 ===

=== Processing site: DE-RuR ===

=== Processing site: US-GLE ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 192867. Expected 225 fields but found 251. Consider fill=251 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200501010000,200501010030,-7.1,0,-5.389,-7.1,0,0,-9999,-9999,0,0,2,-9999,-9999,217.493,217.493,2,-9999,-9999,213.915,213.915,2,-9999,-9999,1.976,1.976,2,-9999,67.901,67.901,2,-9999,0.006,0.006,2,3.714,5.422,3.714,0,200.11645,0.601821,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,0.395,0.315,-9999,0.545,-9999,0.625,-9999,0.63,0.955,-9999,0,0,-9999,0,-9999,0,-9999,0,0,20.5,24.1,25.7,24.7,23.15,0,0,0,0,0,-1.235,0,-0.992859,0,-0.989342,-9999,-9999,-9999,-9999,-9999,-9999,-43.0785,0,-42.8643,>>”
=== Processing site: US-MN1 ===

=== Processing site: CN-Du3 ===

=== Processing site: US-BZB ===

=== Processing site: CN-Sw2 ===

=== Processing site: US-SRG ===

=== Processing site: US-Tw4 ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 35043. Expected 150 fields but found 175. Consider fill=175 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<201301010000,201301010030,-9999,-9999,1.223,1.223,2,0,-9999,-9999,0,0,2,-9999,-9999,276.38,276.38,2,-9999,-9999,256.558,256.558,2,-9999,-9999,2.352,2.352,2,-9999,102.558,102.558,2,-9999,0,0,2,-9999,2.164,2.164,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-0.120045,3,-0.238683,-9999,-9999,-9999,-9999,-9999,-9999,-1.83772,3,-3.65415,-9999,-9999,-9999,-9999,-9999,-9999,55,3,1,3.51013,3.51013,3,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,3.51013,3.51013,3,3,-9999,->>”
=== Processing site: RU-Fyo ===

=== Processing site: FI-Var ===

=== Processing site: IT-Niv ===

=== Processing site: DE-HoH ===

=== Processing site: US-Sta ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 87651. Expected 179 fields but found 221. Consider fill=221 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200501010000,200501010030,-9999,-9999,0.027,0.027,2,0,0,0,0,0,0,-9999,-9999,231.368,231.368,2,-9999,-9999,252.286,252.286,2,-9999,-9999,2.527,2.527,2,-9999,76.893,76.893,2,-9999,0.021,0.021,2,-9999,6.077,6.077,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,9.5862,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-48.1648,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,0.160919,0.160919,3,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,0.160919,0.160919,3,3,-9999,>>”
=== Processing site: IE-CaC ===

=== Processing site: CA-NS3 ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 87651. Expected 224 fields but found 226. Consider fill=226 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200101010000,200101010030,-9999,-9999,-16.769,-16.769,2,0,-9999,-9999,0,0,2,-9999,-9999,194.22,194.22,2,-9999,-9999,174.61,174.61,2,-9999,-9999,0.876,0.876,2,-9999,98.349,98.349,2,-9999,0.001,0.001,2,-9999,2.683,2.683,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,2.6428,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-17.4126,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,4.09675,4.09675,3,3,-9999,-9999,-9999,-9999,-999>>”
=== Processing site: US-Slt ===

=== Processing site: DE-Msr ===

=== Processing site: CA-SF3 ===

=== Processing site: CH-Lae ===

=== Processing site: CA-EM2 ===

=== Processing site: US-xKA ===

=== Processing site: ES-LgS ===

=== Processing site: CA-SCB ===

=== Processing site: US-PFm ===

=== Processing site: AU-Adr ===

=== Processing site: US-PFg ===

=== Processing site: AU-Boy ===

=== Processing site: US-xAB ===

=== Processing site: US-xHA ===

=== Processing site: US-Wi7 ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 17523. Expected 143 fields but found 145. Consider fill=145 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200501010000,200501010030,-9999,-9999,-16.2,-16.2,2,0,0,0,0,0,0,-9999,-9999,231.403,231.403,2,-9999,-9999,242.627,242.627,2,-9999,-9999,0,0,2,-9999,99.308,99.308,2,0,0.073,0,0,-9999,2.361,2.361,2,-9999,-9999,-9999,-9999,0,-9999,-9999,-9999,-9999,3.72033,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,2.76867,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,-4.22823,3,-9999,-9999,-9999,-9999,-4.22823,3,-9999,-9999,-9999,-9999,-2.24738,0,0.388545,-5.26654,-5.26654,-4.22823,-4.22823,-0.34834,0>>”
=== Processing site: US-xTA ===

=== Processing site: CN-Du2 ===

=== Processing site: DE-Kli ===

=== Processing site: AU-RDF ===

=== Processing site: US-YK2 ===

Warning message in unzip(zipfile, files = f, exdir = tempdir(), overwrite = TRUE):
“error -1 in extracting from zip file”
=== Processing site: BE-Bra ===

=== Processing site: CZ-BK2 ===

=== Processing site: US-CRK ===

=== Processing site: US-Snf ===

=== Processing site: US-ICh ===

=== Processing site: IT-TrF ===

=== Processing site: ZM-Mon ===

=== Processing site: US-xBN ===

=== Processing site: BE-Dor ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 175346. Expected 235 fields but found 241. Consider fill=241 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<202201010000,202201010030,-9999,-9999,8.34,8.34,2,0,-9999,-9999,0,0,2,-9999,-9999,308.699,308.699,2,-9999,-9999,294.598,294.598,2,-9999,-9999,3.109,3.109,2,-9999,99.543,99.543,2,-9999,0,0,2,-9999,1.343,1.343,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1.25,3,0.917377,-9999,-9999,-9999,-9999,-9999,-9999,-35.7283,3,-26.1669,-9999,-9999,-9>>”
=== Processing site: CA-LP1 ===

=== Processing site: US-xSL ===

=== Processing site: US-Mo3 ===

=== Processing site: US-CS8 ===

=== Processing site: AU-Stp ===

=== Processing site: ES-Agu ===

=== Processing site: IT-Isp ===

=== Processing site: US-UC1 ===

=== Processing site: JP-SMF ===

=== Processing site: EE-Pts ===

=== Processing site: US-CF4 ===

=== Processing site: US-Hn2 ===

=== Processing site: RU-Che ===

=== Processing site: US-Rms ===

=== Processing site: IT-CA1 ===

=== Processing site: US-xNG ===

=== Processing site: IT-MtP ===

=== Processing site: US-Ne3 ===

=== Processing site: US-CF3 ===

=== Processing site: US-DS2 ===

=== Processing site: US-Cst ===

=== Processing site: US-xNQ ===

=== Processing site: AU-Ade ===

=== Processing site: US-Rls ===

=== Processing site: IT-Tor ===

=== Processing site: ES-Abr ===

=== Processing site: US-Var ===

=== Processing site: FI-Sii ===

=== Processing site: AU-DaS ===

=== Processing site: US-CS3 ===

=== Processing site: CA-ARF ===

=== Processing site: US-Dmg ===

=== Processing site: US-StJ ===

=== Processing site: US-PFL ===

=== Processing site: FI-Lom ===

=== Processing site: US-EML ===

=== Processing site: US-Rws ===

=== Processing site: US-CF2 ===

=== Processing site: US-Blo ===

=== Processing site: US-Goo ===

=== Processing site: US-Lin ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 35043. Expected 149 fields but found 151. Consider fill=151 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200901010000,200901010030,-9999,-9999,9.658,9.658,2,0,-9999,-9999,0,0,2,-9999,-9999,250.496,250.496,2,-9999,-9999,281.066,281.066,2,-9999,-9999,3.061,3.061,2,-9999,100.48,100.48,2,-9999,0,0,2,-9999,0.568,0.568,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,2.38333,3,3.69572,-9999,-9999,-9999,-9999,-9999,-9999,-5.91333,3,-9.16841,-9999,-9999,-9999,-9999,-9999,-9999,55,3,1,1.63038,3,-9999,-9999,-9999,-9999,1.63038,3,-9999,-9999,-9999,-9999,1>>”
=== Processing site: US-PFk ===

=== Processing site: IT-Col ===

=== Processing site: US-RGA ===

=== Processing site: IT-Ro2 ===

=== Processing site: NL-Hor ===

=== Processing site: US-BZS ===

=== Processing site: AR-CCg ===

=== Processing site: FR-Tou ===

=== Processing site: US-KS1 ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):
“Stopped early on line 35043. Expected 143 fields but found 148. Consider fill=148 or even more based on your knowledge of the input file. Use fill=Inf for reading the whole file for detecting the number of fields. First discarded non-empty line: <<200201010000,200201010030,-9999,-9999,13.918,13.918,2,0,-9999,-9999,0,0,2,-9999,-9999,376.606,376.606,2,-9999,-9999,414.879,414.879,2,-9999,-9999,0,0,2,-9999,101.768,101.768,2,-9999,0.064,0.064,2,-9999,2.739,2.739,2,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1.3064,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-35.7508,3,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,3.651,3,-9999,-9999,-9999,-9999,3.651,3,-9999,-9999,-9999,-9999,3.63261,0,0.0677877,2.89>>”
=== Processing site: US-KS3 ===

=== Processing site: CA-ER1 ===

=== Processing site: US-Bi1 ===

=== Processing site: US-Ses ===

=== Processing site: AU-Tum ===

=== Processing site: US-Ha1 ===

Warning message in data.table::fread(cmd = cmd, showProgress = FALSE, fill = TRUE):

In [39]:
system("df -h .")                 # free space on the filesystem of your home dir
system("du -sh merged_sites")     # how big the output folder is

In [ ]:
View(EFP_site)

    SITE_ID siteID uWUE      ETmax      precipAvail Gavail GSmax
1   AT-Neu  AT-Neu 4.4531612 0.26577914 yes         yes    0.0149402500
2   BE-Lon  BE-Lon 2.9829694 0.23079557 yes         yes    0.0152947875
3   BR-CST  BR-CST 3.7205283 0.18012509 yes         yes    0.0005544469
4   BR-Npw  BR-Npw 1.9239528 0.35318931 yes         yes    0.0004802108
5   CA-Ca1  CA-Ca1 6.0950839 0.12927937 yes         yes    0.0064543504
6   CA-Ca2  CA-Ca2 2.9547596 0.15292241 yes         yes    0.0055918070
7   CA-Cbo  CA-Cbo 2.7412119 0.25932713 yes         yes    0.0134334459
8   CA-DB2  CA-DB2 0.8900540 0.13428289 yes         yes    0.0050754978
9   CA-DBB  CA-DBB 0.7071730 0.17592585 yes         yes    0.0057465202
10  CA-EM1  CA-EM1 1.2786731 0.21120272 yes         yes    0.0007597991
11  CA-Gro  CA-Gro 2.5516064 0.19145826 yes         yes    0.0111447820
12  CA-LP1  CA-LP1 2.4646896 0.11205929 yes         yes    0.0060691962
13  CA-MA2  CA-MA2 1.5648837 0.19194591 yes         yes    0.0080657792
14  CA-MA3  CA-MA3 3.3447730 0.18512602 yes         yes    0.0065324074
15  CA-Man  CA-Man 2.0832387 0.12859717 yes         yes    0.0004873520
16  CA-NS1  CA-NS1 3.0390393 0.12412875 yes         yes    0.0012626562
17  CA-NS2  CA-NS2 2.5277999 0.11757392 yes         yes    0.0004746460
18  CA-NS3  CA-NS3 2.1725709 0.13812957 yes         yes    0.0004888770
19  CA-NS4  CA-NS4 2.4603498 0.07883408 yes         yes    0.0002093995
20  CA-NS5  CA-NS5 2.4207379 0.14147595 yes         yes    0.0003959976
21  CA-NS6  CA-NS6 0.9715268 0.10676002 yes         yes    0.0003091219
22  CA-NS7  CA-NS7 0.9921836 0.13129285 yes         yes    0.0004846430
23  CA-Qc2  CA-Qc2 2.0192994 0.18212748 yes         yes    0.0113523084
24  CA-Qfo  CA-Qfo 2.0041313 0.12395157 yes         yes    0.0072632328
25  CA-SF1  CA-SF1 2.5310592 0.19741665 yes         yes    0.0138771856
26  CA-SF2  CA-SF2 3.3997501 0.20622088 yes         yes    0.0114840726
27  CA-TP1  CA-TP1 3.6448110 0.17944601 yes         yes    0.0095115661
28  CA-TP3  CA-TP3 3.1785926 0.17893311 yes         yes    0.0131452695
29  CA-TPD  CA-TPD 3.0848341 0.20072878 yes         yes    0.0081392202
30  CH-Aws  CH-Aws 1.8049793 0.34991631 yes         yes    0.0061554027
⋮   ⋮       ⋮      ⋮         ⋮          ⋮           ⋮      ⋮
255 US-xDJ  US-xDJ 1.9608901 0.09827521 yes         yes    0.006055651
256 US-xDL  US-xDL 2.7309558 0.31989533 yes         yes    0.010855640
257 US-xDS  US-xDS 2.2440011 0.23006658 yes         yes    0.005429681
258 US-xGR  US-xGR 3.4601099 0.27491959 yes         yes    0.010704838
259 US-xHA  US-xHA 2.7008645 0.24533977 yes         yes    0.011206327
260 US-xHE  US-xHE 1.2007447 0.11473271 yes         yes    0.005174975
261 US-xJE  US-xJE 2.7454803 0.29482825 yes         yes    0.010261522
262 US-xJR  US-xJR 0.7743949 0.08654977 yes         yes    0.001322031
263 US-xKA  US-xKA 1.1229976 0.23847836 yes         yes    0.006839200
264 US-xKZ  US-xKZ 1.9994946 0.26046896 yes         yes    0.006143015
265 US-xMB  US-xMB 1.0349168 0.07169217 yes         yes    0.002203011
266 US-xML  US-xML 1.8120252 0.20169205 yes         yes    0.010712483
267 US-xNG  US-xNG 1.4316608 0.22187247 yes         yes    0.007347937
268 US-xNQ  US-xNQ 0.6357708 0.10315480 yes         yes    0.003385913
269 US-xRM  US-xRM 1.4772492 0.15979488 yes         yes    0.006883641
270 US-xSB  US-xSB 2.9443988 0.18562093 yes         yes    0.007047335
271 US-xSC  US-xSC 2.4737661 0.27341883 yes         yes    0.010645534
272 US-xSE  US-xSE 2.9951342 0.26493049 yes         yes    0.009489407
273 US-xSJ  US-xSJ 2.4313449 0.12960235 yes         yes    0.004805949
274 US-xSL  US-xSL 0.5881143 0.11906496 yes         yes    0.003631479
275 US-xSR  US-xSR 1.1788469 0.07636935 yes         yes    0.001453269
276 US-xST  US-xST 2.0869331 0.24141236 yes         yes    0.010711627
277 US-xTA  US-xTA 3.0569242 0.27718355 yes         yes    0.008937724
278 US-xTL  US-xTL 0.9287366 0.10601959 yes         yes    0.007546772
279 US-xTR  US-xTR 2.3690829 0.23074366 yes         yes    0.010147525
280 US-xUK  US-xUK 2.8494763 0.27212032 yes         yes    0.008492977
281 US-xUN  US-xUN 2.1867378 0.20862585 yes         yes    0.009646437
282 US-xWD  US-xWD 1.6309591 0.19539614 yes         yes    0.006157789
283 US-xYE  US-xYE 1.4742150 0.16211501 yes         yes    0.008079774
284 US-YK2  US-YK2 1.0394295 0.10520446 yes         yes    0.013541361
    CO2avail G1         EF        ⋯ Rb         Rbmax      aCUE          TZ
1   yes       1.5027279 0.7901329 ⋯  15.385701  21.762126    0.45201781  1
2   yes       0.9652484 0.6458370 ⋯   3.343010   6.216584    0.47073279  1
3   yes      -1.0542127 0.2228430 ⋯         NA         NA            NA -3
4   yes      -0.8785709 0.7826637 ⋯         NA         NA            NA -3
5   yes       0.3026107 0.3228162 ⋯   3.486950   8.717625    0.77525906 -8
6   yes       1.7197547 0.3612395 ⋯         NA         NA            NA -8
7   yes       1.7711470 0.4188698 ⋯   6.278615  12.304131   -0.35495133 -5
8   yes       5.8545911 0.3734183 ⋯         NA         NA            NA -8
9   yes       5.9821966 0.4484511 ⋯         NA         NA            NA -8
10  yes      -0.5996231 0.7386375 ⋯         NA         NA            NA -6
11  yes       2.5615283 0.3362806 ⋯         NA         NA            NA -5
12  yes       2.9510491 0.2544924 ⋯         NA         NA            NA -8
13  yes       1.3772872 0.5511660 ⋯         NA         NA            NA -6
14  yes       1.8140374 0.6560685 ⋯         NA         NA            NA -6
15  yes      -0.5210523 0.2540195 ⋯   1.865768   4.078569    0.62435576 -6
16  yes      -0.6428224 0.2330035 ⋯         NA         NA            NA -6
17  yes      -0.6108277 0.2354185 ⋯         NA         NA            NA -6
18  yes      -0.5963751 0.2247715 ⋯   3.217114   5.043903    0.21701575 -6
19  yes      -0.7479176 0.2300299 ⋯ 292.514395 134.798108 -101.70062319 -6
20  yes      -0.7091549 0.2405241 ⋯         NA         NA            NA -6
21  yes      -0.7379863 0.2378149 ⋯         NA         NA            NA -6
22  yes      -0.6542998 0.2742839 ⋯   2.073708   2.851488   -0.66261396 -6
23  yes       2.7728580 0.2944462 ⋯         NA         NA            NA -5
24  yes       2.6452397 0.2303327 ⋯   2.826538   4.797617   -0.15949746 -5
25  yes       3.2979072 0.4197682 ⋯         NA         NA            NA -6
26  yes       1.9723580 0.3414434 ⋯         NA         NA            NA -6
27  yes       1.0753304 0.3851192 ⋯         NA         NA            NA -5
28  yes       2.0148523 0.3302751 ⋯         NA         NA            NA -5
29  yes       1.1265911 0.3996422 ⋯         NA         NA            NA -5
30  yes      -0.9628338 0.7338897 ⋯   4.505619   8.371894    0.04592198  1
⋮   ⋮        ⋮          ⋮         ⋱ ⋮          ⋮          ⋮             ⋮
255 yes      3.686621   0.2703610 ⋯ 1.770090   3.947015    0.7598760    -9
256 yes      1.677645   0.6007843 ⋯       NA         NA           NA    -6
257 yes      2.615305   0.5033735 ⋯       NA         NA           NA    -5
258 yes      1.317067   0.6276432 ⋯ 5.175529   8.302590   -0.1622663    -5
259 yes      2.111075   0.4071358 ⋯       NA         NA           NA    -5
260 yes      3.520827   0.4150292 ⋯ 3.021014   4.015267   -1.6491853    -9
261 yes      2.710191   0.5759304 ⋯       NA         NA           NA    -5
262 yes      2.274319   0.1234173 ⋯       NA         NA           NA    -7
263 yes      1.484649   0.4455459 ⋯       NA         NA           NA    -6
264 yes      1.295189   0.4175466 ⋯       NA         NA           NA    -6
265 yes      3.018588   0.2049840 ⋯       NA         NA           NA    -7
266 yes      2.095283   0.3221982 ⋯       NA         NA           NA    -5
267 yes      3.675183   0.4355035 ⋯       NA         NA           NA    -6
268 yes      6.034199   0.2211929 ⋯       NA         NA           NA    -7
269 yes      2.803791   0.2772661 ⋯       NA         NA           NA    -7
270 yes      2.383714   0.4385984 ⋯       NA         NA           NA    -5
271 yes      2.269339   0.4717928 ⋯       NA         NA           NA    -5
272 yes      1.772969   0.5228573 ⋯       NA         NA           NA    -5
273 yes      2.034601   0.2438348 ⋯       NA         NA           NA    -8
274 yes      1.703524   0.2576513 ⋯       NA         NA           NA    -7
275 yes      3.065517   0.1259602 ⋯       NA         NA           NA    -7
276 yes      2.733810   0.2891368 ⋯       NA         NA           NA    -6
277 yes      1.784217   0.5776293 ⋯       NA         NA           NA    -6
278 yes      4.800693   0.4526965 ⋯       NA         NA           NA    -9
279 yes      2.157708   0.3664407 ⋯       NA         NA           NA    -6
280 yes      1.866173   0.4446276 ⋯       NA         NA           NA    -6
281 yes      2.356856   0.3632036 ⋯       NA         NA           NA    -6
282 yes      2.739241   0.3932200 ⋯       NA         NA           NA    -6
283 yes      3.269045   0.3062198 ⋯ 2.305874   4.592782   -2.0047341    -7
284 yes      5.111403   0.4202034 ⋯ 2.955133   8.054365    0.7006754    -9
    nyears
1   19
2   21
3    2
4    5
5   15
6   12
7   27
8    2
9    7
10   3
11  12
12  16
13   3
14   3
15  15
16   5
17   5
18   5
19   5
20   5
21   5
22   5
23   4
24   8
25   4
26   6
27  22
28  16
29  12
30  18
⋮   ⋮
255 6
256 6
257 6
258 6
259 6
260 6
261 6
262 6
263 6
264 6
265 6
266 6
267 6
268 6
269 6
270 6
271 6
272 6
273 6
274 6
275 6
276 6
277 6
278 6
279 6
280 6
281 6
282 6
283 6
284 6
    SITE_NAME
1   Neustift
2   Lonzee
3   NA
4   Northern Pantanal Wetland
5   NA
6   NA
7   NA
8   NA
9   NA
10  NA
11  Ontario - Groundhog River, Boreal Mixedwood Forest
12  NA
13  NA
14  NA
15  Manitoba - Northern Old Black Spruce (former BOREAS Northern Study Area)
16  UCI-1850 burn site
17  UCI-1930 burn site
18  UCI-1964 burn site
19  UCI-1964 burn site wet
20  UCI-1981 burn site
21  UCI-1989 burn site
22  UCI-1998 burn site
23  NA
24  Quebec - Eastern Boreal, Mature Black Spruce
25  Saskatchewan - Western Boreal, forest burned in 1977
26  Saskatchewan - Western Boreal, forest burned in 1989
27  Ontario - Turkey Point 2002 Plantation White Pine
28  Ontario - Turkey Point 1974 Plantation White Pine
29  Ontario - Turkey Point Mature Deciduous
30  NA
⋮   ⋮
255 NA
256 NA
257 NA
258 NA
259 NA
260 NA
261 NA
262 NA
263 NA
264 NA
265 NA
266 NA
267 NA
268 NA
269 NA
270 NA
271 NA
272 NA
273 NA
274 NA
275 NA
276 NA
277 NA
278 NA
279 NA
280 NA
281 NA
282 NA
283 NA
284 NA
    LOCATION_LAT LOCATION_LONG LOCATION_ELEV IGBP
1    47.11670      11.317500    970.00       GRA
2    50.55162       4.746234    157.00       CRO
3    -7.96820     -38.384200    468.00       PFT_DNF
4   -16.49800     -56.412000    120.00       WSA
5    49.86730    -125.333600    303.06       PFT_ENF
6    49.87050    -125.290900    174.01       PFT_ENF
7    44.31670     -79.933300    215.72       PFT_DBF
8    49.11900    -122.995100      9.21       PFT_WET
9    49.12930    -122.984900     10.21       PFT_WET
10   50.36230    -100.202400    608.00       PFT_WET
11   48.21670     -82.155600    340.00       MF
12   55.11190    -122.841400    751.00       PFT_ENF
13   50.17100     -97.876200    259.00       PFT_CRO
14   50.17740     -97.868600    259.00       PFT_GRA
15   55.87960     -98.480800    259.00       ENF
16   55.87920     -98.483900    260.00       ENF
17   55.90580     -98.524700    260.00       ENF
18   55.91170     -98.382200    260.00       ENF
19   55.91440     -98.380600    260.00       ENF
20   55.86310     -98.485000    260.00       ENF
21   55.91670     -98.964400    244.00       OSH
22   56.63580     -99.948300    297.00       OSH
23   49.75980     -74.571100    387.30       PFT_MF
24   49.69250     -74.342100    382.00       ENF
25   54.48500    -105.817600    536.00       ENF
26   54.25390    -105.877500    520.00       ENF
27   42.66090     -80.559500    265.00       ENF
28   42.70680     -80.348300    184.00       ENF
29   42.63530     -80.557700    260.00       DBF
30   46.58319       9.790417   1942.00       PFT_GRA
⋮   ⋮            ⋮             ⋮             ⋮
255 63.8811      -145.7514      506.78       PFT_ENF
256 32.5417       -87.8039       24.59       PFT_MF
257 28.1250       -81.4362       20.70       PFT_CVM
258 35.6890       -83.5019      576.55       PFT_DBF
259 42.5369       -72.1727      348.23       PFT_DBF
260 63.8757      -149.2133      677.56       PFT_OSH
261 31.1948       -84.4686       46.53       PFT_ENF
262 32.5907      -106.8425     1323.42       PFT_OSH
263 39.1104       -96.6129      324.14       PFT_GRA
264 39.1008       -96.5631      415.06       PFT_GRA
265 38.2483      -109.3883     1801.24       PFT_OSH
266 37.3783       -80.5248     1170.36       PFT_DBF
267 46.7697      -100.9154      588.51       PFT_GRA
268 40.1776      -112.4524     1655.33       PFT_OSH
269 40.2759      -105.5459     2743.94       PFT_ENF
270 29.6893       -81.9934       46.15       PFT_ENF
271 38.8929       -78.1395      353.02       PFT_DBF
272 38.8901       -76.5600        9.79       PFT_DBF
273 37.1088      -119.7323      398.80       PFT_SAV
274 40.4619      -103.0293     1364.89       PFT_CRO
275 31.9107      -110.8355      997.32       PFT_OSH
276 45.5089       -89.5864      475.42       PFT_DBF
277 32.9505       -87.3933      165.87       PFT_ENF
278 68.6611      -149.3705      827.85       PFT_WET
279 45.4937       -89.5857      466.34       PFT_DBF
280 39.0404       -95.1921      321.35       PFT_DBF
281 46.2339       -89.5373      521.47       PFT_MF
282 47.1282       -99.2414      590.92       PFT_GRA
283 44.9535      -110.5391     2132.93       PFT_ENF
284 61.2548      -163.2590       18.68       PFT_WET

In [ ]:
#select each unique IGBP and SITE_ID which has more than 5 yearn in EFP_all data
EFP_summary <- EFP_site %>%
  group_by(IGBP, SITE_ID) %>%
  #summarise(years_count = n_distinct(YEAR)) %>%
  filter(nyears >= 5)

In [ ]:
View(EFP_summary)

    SITE_ID siteID uWUE      ETmax      precipAvail Gavail GSmax
1   AT-Neu  AT-Neu 4.4531612 0.26577914 yes         yes    0.0149402500
2   BE-Lon  BE-Lon 2.9829694 0.23079557 yes         yes    0.0152947875
3   BR-Npw  BR-Npw 1.9239528 0.35318931 yes         yes    0.0004802108
4   CA-Ca1  CA-Ca1 6.0950839 0.12927937 yes         yes    0.0064543504
5   CA-Ca2  CA-Ca2 2.9547596 0.15292241 yes         yes    0.0055918070
6   CA-Cbo  CA-Cbo 2.7412119 0.25932713 yes         yes    0.0134334459
7   CA-DBB  CA-DBB 0.7071730 0.17592585 yes         yes    0.0057465202
8   CA-Gro  CA-Gro 2.5516064 0.19145826 yes         yes    0.0111447820
9   CA-LP1  CA-LP1 2.4646896 0.11205929 yes         yes    0.0060691962
10  CA-Man  CA-Man 2.0832387 0.12859717 yes         yes    0.0004873520
11  CA-NS1  CA-NS1 3.0390393 0.12412875 yes         yes    0.0012626562
12  CA-NS2  CA-NS2 2.5277999 0.11757392 yes         yes    0.0004746460
13  CA-NS3  CA-NS3 2.1725709 0.13812957 yes         yes    0.0004888770
14  CA-NS4  CA-NS4 2.4603498 0.07883408 yes         yes    0.0002093995
15  CA-NS5  CA-NS5 2.4207379 0.14147595 yes         yes    0.0003959976
16  CA-NS6  CA-NS6 0.9715268 0.10676002 yes         yes    0.0003091219
17  CA-NS7  CA-NS7 0.9921836 0.13129285 yes         yes    0.0004846430
18  CA-Qfo  CA-Qfo 2.0041313 0.12395157 yes         yes    0.0072632328
19  CA-SF2  CA-SF2 3.3997501 0.20622088 yes         yes    0.0114840726
20  CA-TP1  CA-TP1 3.6448110 0.17944601 yes         yes    0.0095115661
21  CA-TP3  CA-TP3 3.1785926 0.17893311 yes         yes    0.0131452695
22  CA-TPD  CA-TPD 3.0848341 0.20072878 yes         yes    0.0081392202
23  CH-Aws  CH-Aws 1.8049793 0.34991631 yes         yes    0.0061554027
24  CH-Cha  CH-Cha 3.2194015 0.30122058 yes         yes    0.0238270066
25  CH-Fru  CH-Fru 2.4456363 0.26700153 yes         yes    0.0147127427
26  CL-SDF  CL-SDF 2.5896269 0.21007402 yes         yes    0.0214443696
27  CZ-KrP  CZ-KrP 2.6639413 0.18278270 yes         yes    0.0076658788
28  CZ-RAJ  CZ-RAJ 4.1857294 0.13413029 yes         yes    0.0065680723
29  CZ-Stn  CZ-Stn 3.5078717 0.20921179 yes         yes    0.0009735849
30  CZ-wet  CZ-wet 2.0517190 0.22497406 yes         yes    0.0072100648
⋮   ⋮       ⋮      ⋮         ⋮          ⋮           ⋮      ⋮
172 US-xDJ  US-xDJ 1.9608901 0.09827521 yes         yes    0.006055651
173 US-xDL  US-xDL 2.7309558 0.31989533 yes         yes    0.010855640
174 US-xDS  US-xDS 2.2440011 0.23006658 yes         yes    0.005429681
175 US-xGR  US-xGR 3.4601099 0.27491959 yes         yes    0.010704838
176 US-xHA  US-xHA 2.7008645 0.24533977 yes         yes    0.011206327
177 US-xHE  US-xHE 1.2007447 0.11473271 yes         yes    0.005174975
178 US-xJE  US-xJE 2.7454803 0.29482825 yes         yes    0.010261522
179 US-xJR  US-xJR 0.7743949 0.08654977 yes         yes    0.001322031
180 US-xKA  US-xKA 1.1229976 0.23847836 yes         yes    0.006839200
181 US-xKZ  US-xKZ 1.9994946 0.26046896 yes         yes    0.006143015
182 US-xMB  US-xMB 1.0349168 0.07169217 yes         yes    0.002203011
183 US-xML  US-xML 1.8120252 0.20169205 yes         yes    0.010712483
184 US-xNG  US-xNG 1.4316608 0.22187247 yes         yes    0.007347937
185 US-xNQ  US-xNQ 0.6357708 0.10315480 yes         yes    0.003385913
186 US-xRM  US-xRM 1.4772492 0.15979488 yes         yes    0.006883641
187 US-xSB  US-xSB 2.9443988 0.18562093 yes         yes    0.007047335
188 US-xSC  US-xSC 2.4737661 0.27341883 yes         yes    0.010645534
189 US-xSE  US-xSE 2.9951342 0.26493049 yes         yes    0.009489407
190 US-xSJ  US-xSJ 2.4313449 0.12960235 yes         yes    0.004805949
191 US-xSL  US-xSL 0.5881143 0.11906496 yes         yes    0.003631479
192 US-xSR  US-xSR 1.1788469 0.07636935 yes         yes    0.001453269
193 US-xST  US-xST 2.0869331 0.24141236 yes         yes    0.010711627
194 US-xTA  US-xTA 3.0569242 0.27718355 yes         yes    0.008937724
195 US-xTL  US-xTL 0.9287366 0.10601959 yes         yes    0.007546772
196 US-xTR  US-xTR 2.3690829 0.23074366 yes         yes    0.010147525
197 US-xUK  US-xUK 2.8494763 0.27212032 yes         yes    0.008492977
198 US-xUN  US-xUN 2.1867378 0.20862585 yes         yes    0.009646437
199 US-xWD  US-xWD 1.6309591 0.19539614 yes         yes    0.006157789
200 US-xYE  US-xYE 1.4742150 0.16211501 yes         yes    0.008079774
201 US-YK2  US-YK2 1.0394295 0.10520446 yes         yes    0.013541361
    CO2avail G1         EF        ⋯ Rb         Rbmax      aCUE          TZ
1   yes       1.5027279 0.7901329 ⋯  15.385701  21.762126    0.45201781  1
2   yes       0.9652484 0.6458370 ⋯   3.343010   6.216584    0.47073279  1
3   yes      -0.8785709 0.7826637 ⋯         NA         NA            NA -3
4   yes       0.3026107 0.3228162 ⋯   3.486950   8.717625    0.77525906 -8
5   yes       1.7197547 0.3612395 ⋯         NA         NA            NA -8
6   yes       1.7711470 0.4188698 ⋯   6.278615  12.304131   -0.35495133 -5
7   yes       5.9821966 0.4484511 ⋯         NA         NA            NA -8
8   yes       2.5615283 0.3362806 ⋯         NA         NA            NA -5
9   yes       2.9510491 0.2544924 ⋯         NA         NA            NA -8
10  yes      -0.5210523 0.2540195 ⋯   1.865768   4.078569    0.62435576 -6
11  yes      -0.6428224 0.2330035 ⋯         NA         NA            NA -6
12  yes      -0.6108277 0.2354185 ⋯         NA         NA            NA -6
13  yes      -0.5963751 0.2247715 ⋯   3.217114   5.043903    0.21701575 -6
14  yes      -0.7479176 0.2300299 ⋯ 292.514395 134.798108 -101.70062319 -6
15  yes      -0.7091549 0.2405241 ⋯         NA         NA            NA -6
16  yes      -0.7379863 0.2378149 ⋯         NA         NA            NA -6
17  yes      -0.6542998 0.2742839 ⋯   2.073708   2.851488   -0.66261396 -6
18  yes       2.6452397 0.2303327 ⋯   2.826538   4.797617   -0.15949746 -5
19  yes       1.9723580 0.3414434 ⋯         NA         NA            NA -6
20  yes       1.0753304 0.3851192 ⋯         NA         NA            NA -5
21  yes       2.0148523 0.3302751 ⋯         NA         NA            NA -5
22  yes       1.1265911 0.3996422 ⋯         NA         NA            NA -5
23  yes      -0.9628338 0.7338897 ⋯   4.505619   8.371894    0.04592198  1
24  yes       1.6607607 0.7654066 ⋯   6.069183  11.203497   -0.58857078  1
25  yes       0.1250682 0.7119719 ⋯   5.810336  11.355284   -0.45656461  1
26  yes       2.0312605 0.4271210 ⋯         NA         NA            NA -3
27  yes       0.9759660 0.5543440 ⋯         NA         NA            NA  1
28  yes       0.5679969 0.3121892 ⋯         NA         NA            NA  1
29  yes      -0.6842387 0.4836686 ⋯   3.329495   6.443072    0.22554632  1
30  yes       1.0357745 0.5473814 ⋯   3.964393   6.474829   -0.35955918  1
⋮   ⋮        ⋮          ⋮         ⋱ ⋮          ⋮          ⋮             ⋮
172 yes      3.686621   0.2703610 ⋯ 1.770090   3.947015    0.7598760    -9
173 yes      1.677645   0.6007843 ⋯       NA         NA           NA    -6
174 yes      2.615305   0.5033735 ⋯       NA         NA           NA    -5
175 yes      1.317067   0.6276432 ⋯ 5.175529   8.302590   -0.1622663    -5
176 yes      2.111075   0.4071358 ⋯       NA         NA           NA    -5
177 yes      3.520827   0.4150292 ⋯ 3.021014   4.015267   -1.6491853    -9
178 yes      2.710191   0.5759304 ⋯       NA         NA           NA    -5
179 yes      2.274319   0.1234173 ⋯       NA         NA           NA    -7
180 yes      1.484649   0.4455459 ⋯       NA         NA           NA    -6
181 yes      1.295189   0.4175466 ⋯       NA         NA           NA    -6
182 yes      3.018588   0.2049840 ⋯       NA         NA           NA    -7
183 yes      2.095283   0.3221982 ⋯       NA         NA           NA    -5
184 yes      3.675183   0.4355035 ⋯       NA         NA           NA    -6
185 yes      6.034199   0.2211929 ⋯       NA         NA           NA    -7
186 yes      2.803791   0.2772661 ⋯       NA         NA           NA    -7
187 yes      2.383714   0.4385984 ⋯       NA         NA           NA    -5
188 yes      2.269339   0.4717928 ⋯       NA         NA           NA    -5
189 yes      1.772969   0.5228573 ⋯       NA         NA           NA    -5
190 yes      2.034601   0.2438348 ⋯       NA         NA           NA    -8
191 yes      1.703524   0.2576513 ⋯       NA         NA           NA    -7
192 yes      3.065517   0.1259602 ⋯       NA         NA           NA    -7
193 yes      2.733810   0.2891368 ⋯       NA         NA           NA    -6
194 yes      1.784217   0.5776293 ⋯       NA         NA           NA    -6
195 yes      4.800693   0.4526965 ⋯       NA         NA           NA    -9
196 yes      2.157708   0.3664407 ⋯       NA         NA           NA    -6
197 yes      1.866173   0.4446276 ⋯       NA         NA           NA    -6
198 yes      2.356856   0.3632036 ⋯       NA         NA           NA    -6
199 yes      2.739241   0.3932200 ⋯       NA         NA           NA    -6
200 yes      3.269045   0.3062198 ⋯ 2.305874   4.592782   -2.0047341    -7
201 yes      5.111403   0.4202034 ⋯ 2.955133   8.054365    0.7006754    -9
    nyears
1   19
2   21
3    5
4   15
5   12
6   27
7    7
8   12
9   16
10  15
11   5
12   5
13   5
14   5
15   5
16   5
17   5
18   8
19   6
20  22
21  16
22  12
23  18
24  19
25  19
26   8
27   7
28  11
29  13
30  18
⋮   ⋮
172 6
173 6
174 6
175 6
176 6
177 6
178 6
179 6
180 6
181 6
182 6
183 6
184 6
185 6
186 6
187 6
188 6
189 6
190 6
191 6
192 6
193 6
194 6
195 6
196 6
197 6
198 6
199 6
200 6
201 6
    SITE_NAME
1   Neustift
2   Lonzee
3   Northern Pantanal Wetland
4   NA
5   NA
6   NA
7   NA
8   Ontario - Groundhog River, Boreal Mixedwood Forest
9   NA
10  Manitoba - Northern Old Black Spruce (former BOREAS Northern Study Area)
11  UCI-1850 burn site
12  UCI-1930 burn site
13  UCI-1964 burn site
14  UCI-1964 burn site wet
15  UCI-1981 burn site
16  UCI-1989 burn site
17  UCI-1998 burn site
18  Quebec - Eastern Boreal, Mature Black Spruce
19  Saskatchewan - Western Boreal, forest burned in 1989
20  Ontario - Turkey Point 2002 Plantation White Pine
21  Ontario - Turkey Point 1974 Plantation White Pine
22  Ontario - Turkey Point Mature Deciduous
23  NA
24  Chamau
25  Früebüel
26  NA
27  NA
28  NA
29  NA
30  Trebon (CZECHWET)
⋮   ⋮
172 NA
173 NA
174 NA
175 NA
176 NA
177 NA
178 NA
179 NA
180 NA
181 NA
182 NA
183 NA
184 NA
185 NA
186 NA
187 NA
188 NA
189 NA
190 NA
191 NA
192 NA
193 NA
194 NA
195 NA
196 NA
197 NA
198 NA
199 NA
200 NA
201 NA
    LOCATION_LAT LOCATION_LONG LOCATION_ELEV IGBP
1    47.11670      11.317500    970.00       GRA
2    50.55162       4.746234    157.00       CRO
3   -16.49800     -56.412000    120.00       WSA
4    49.86730    -125.333600    303.06       PFT_ENF
5    49.87050    -125.290900    174.01       PFT_ENF
6    44.31670     -79.933300    215.72       PFT_DBF
7    49.12930    -122.984900     10.21       PFT_WET
8    48.21670     -82.155600    340.00       MF
9    55.11190    -122.841400    751.00       PFT_ENF
10   55.87960     -98.480800    259.00       ENF
11   55.87920     -98.483900    260.00       ENF
12   55.90580     -98.524700    260.00       ENF
13   55.91170     -98.382200    260.00       ENF
14   55.91440     -98.380600    260.00       ENF
15   55.86310     -98.485000    260.00       ENF
16   55.91670     -98.964400    244.00       OSH
17   56.63580     -99.948300    297.00       OSH
18   49.69250     -74.342100    382.00       ENF
19   54.25390    -105.877500    520.00       ENF
20   42.66090     -80.559500    265.00       ENF
21   42.70680     -80.348300    184.00       ENF
22   42.63530     -80.557700    260.00       DBF
23   46.58319       9.790417   1942.00       PFT_GRA
24   47.21020       8.410400    393.00       GRA
25   47.11580       8.537800    982.00       GRA
26  -41.88300     -73.676000     31.00       PFT_EBF
27   49.57326      15.078773    540.00       PFT_CRO
28   49.44372      16.696513    648.00       PFT_ENF
29   49.03598      17.969900    564.00       PFT_DBF
30   49.02465      14.770350    426.00       WET
⋮   ⋮            ⋮             ⋮             ⋮
172 63.8811      -145.7514      506.78       PFT_ENF
173 32.5417       -87.8039       24.59       PFT_MF
174 28.1250       -81.4362       20.70       PFT_CVM
175 35.6890       -83.5019      576.55       PFT_DBF
176 42.5369       -72.1727      348.23       PFT_DBF
177 63.8757      -149.2133      677.56       PFT_OSH
178 31.1948       -84.4686       46.53       PFT_ENF
179 32.5907      -106.8425     1323.42       PFT_OSH
180 39.1104       -96.6129      324.14       PFT_GRA
181 39.1008       -96.5631      415.06       PFT_GRA
182 38.2483      -109.3883     1801.24       PFT_OSH
183 37.3783       -80.5248     1170.36       PFT_DBF
184 46.7697      -100.9154      588.51       PFT_GRA
185 40.1776      -112.4524     1655.33       PFT_OSH
186 40.2759      -105.5459     2743.94       PFT_ENF
187 29.6893       -81.9934       46.15       PFT_ENF
188 38.8929       -78.1395      353.02       PFT_DBF
189 38.8901       -76.5600        9.79       PFT_DBF
190 37.1088      -119.7323      398.80       PFT_SAV
191 40.4619      -103.0293     1364.89       PFT_CRO
192 31.9107      -110.8355      997.32       PFT_OSH
193 45.5089       -89.5864      475.42       PFT_DBF
194 32.9505       -87.3933      165.87       PFT_ENF
195 68.6611      -149.3705      827.85       PFT_WET
196 45.4937       -89.5857      466.34       PFT_DBF
197 39.0404       -95.1921      321.35       PFT_DBF
198 46.2339       -89.5373      521.47       PFT_MF
199 47.1282       -99.2414      590.92       PFT_GRA
200 44.9535      -110.5391     2132.93       PFT_ENF
201 61.2548      -163.2590       18.68       PFT_WET