# 14_calc_EFPs — corrected workflow for FLUXNET Shuttle HH CSV files

Calculates **per-site, per-year** ecosystem functional properties (EFPs) from
`FLUXNET_FLUXMET_HH` files inside FLUXNET Shuttle zip archives.

### Fixes vs previous version
1. Added missing `TimeZoneCalculatorFLUXNET()` definition.
2. Added missing `calc_yearly_efps_full()` — the main per-year orchestrator.
3. Added missing `calc_monthly_meteo()`.
4. Fixed `EFPcalc()` to work **per year** (separate `EFPcalc_year()`), not full-site.
5. Fixed REddyProc API: removed deprecated `.s` / `.n` argument suffixes.
6. Fixed `bigleaf::filter.data()` QC flag handling (FLUXNET 0–3 scale).
7. Fixed test cell: now uses the correct function signature with all arguments.
8. Fixed cell 9 QC checks to match actual output column names.
9. Removed stale references to `flux_all` / `tower_meta` objects from old script.

## 0. Packages and paths

In [1]:
# ============================================================
# 0. Packages and paths
# ============================================================

packages <- c(
  "dplyr", "tidyr", "purrr", "readr", "stringr",
  "lubridate", "tibble", "glue"
)

missing_pkgs <- packages[!packages %in% rownames(installed.packages())]
if (length(missing_pkgs) > 0) install.packages(missing_pkgs)
invisible(lapply(packages, library, character.only = TRUE))

# Optional packages used by EFP functions
optional_packages <- c("quantreg", "bigleaf", "REddyProc", "lutz", "sf", "broom", "plyr")
for (p in optional_packages) {
  if (!requireNamespace(p, quietly = TRUE))
    message("Optional package not installed: ", p, ". Related EFPs may return NA.")
}

# ── EDIT THESE PATHS ────────────────────────────────────────
base_dir   <- "/mnt/gsdata/projects/panops/panops-data-registry/data/flux/fluxnet_2017_2025_V02"
# Path to a CSV with at least: SITE_ID, LOCATION_LAT, LOCATION_LONG, LOCATION_ELEV
meta_path  <- file.path(base_dir, "fluxnet_site_metadata_clean_with_elevation.csv")

start_year <- 2017
end_year   <- 2025
# ────────────────────────────────────────────────────────────

out_dir   <- file.path(base_dir, "EFP_outputs_corrected")
efp_dir   <- file.path(out_dir, "yearly_EFP_per_site")
meteo_dir <- file.path(out_dir, "monthly_meteo_per_site")
qc_dir    <- file.path(out_dir, "logs")

for (d in c(out_dir, efp_dir, meteo_dir, qc_dir))
  dir.create(d, showWarnings = FALSE, recursive = TRUE)

cat("Base directory:", base_dir, "\n")
cat("Output directory:", out_dir, "\n")

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘lubridate’


The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union

Base directory: /mnt/gsdata/projects/panops/panops-data-registry/data/flux/fluxnet_2017_2025_V02
Output directory: /mnt/gsdata/projects/panops/panops-data-registry/data/flux/fluxnet_2017_2025_V02/EFP_outputs_corrected

## 1. Index FLUXMET HH files inside zip archives

In [2]:
# ============================================================
# 1. Build zip index — FLUXNET_FLUXMET_HH files only
# ============================================================

all_zip_files <- list.files(base_dir, pattern = "\\.zip$",
                            recursive = TRUE, full.names = TRUE)

zip_index_list <- list()
bad_zips       <- character()

for (z in all_zip_files) {
  files_inside <- tryCatch(
    unzip(z, list = TRUE)$Name,
    error = function(e) { bad_zips <<- c(bad_zips, z); NULL }
  )
  if (is.null(files_inside)) next

  hh_file <- files_inside[
    stringr::str_detect(files_inside, "FLUXNET_FLUXMET_HH") &
      stringr::str_detect(files_inside, "\\.csv$")
  ]

  if (length(hh_file) > 0)
    zip_index_list[[length(zip_index_list) + 1]] <-
      tibble(zip_path = z, hh_file = hh_file)
}

zip_index <- bind_rows(zip_index_list) %>%
  mutate(site_id = str_extract(hh_file, "[A-Z]{2}-[A-Za-z0-9]{3}")) %>%
  filter(!is.na(site_id)) %>%
  distinct(site_id, zip_path, hh_file, .keep_all = TRUE) %>%
  arrange(site_id)

write_csv(zip_index,        file.path(qc_dir, "fluxmet_hh_zip_index.csv"))
write_csv(tibble(zip_path = bad_zips), file.path(qc_dir, "bad_or_corrupted_zip_files.csv"))

cat("Total zip files:", length(all_zip_files), "\n")
cat("Good sites with FLUXMET HH:", n_distinct(zip_index$site_id), "\n")
cat("Bad/corrupted zip files:", length(bad_zips), "\n")
head(zip_index)

Total zip files: 357
Good sites with FLUXMET HH: 329
Bad/corrupted zip files: 24

  zip_path
1 /mnt/gsdata/projects/panops/panops-data-registry/data/flux/fluxnet_2017_2025_V02/AMF_AR-TF1_FLUXNET_2016-2018_v1.3_r1.zip
2 /mnt/gsdata/projects/panops/panops-data-registry/data/flux/fluxnet_2017_2025_V02/AMF_AR-TF2_FLUXNET_2016-2018_v1.3_r1.zip
3 /mnt/gsdata/projects/panops/panops-data-registry/data/flux/fluxnet_2017_2025_V02/EUF_AT-Mmg_FLUXNET_2021-2024_v1.3_r1.zip
4 /mnt/gsdata/projects/panops/panops-data-registry/data/flux/fluxnet_2017_2025_V02/EUF_AT-Nsd_FLUXNET_2018-2022_v1.3_r1.zip
5 /mnt/gsdata/projects/panops/panops-data-registry/data/flux/fluxnet_2017_2025_V02/EUF_AT-PsM_FLUXNET_2015-2019_v1.3_r1.zip
6 /mnt/gsdata/projects/panops/panops-data-registry/data/flux/fluxnet_2017_2025_V02/EUF_AT-Zoe_FLUXNET_2014-2024_v1.3_r1.zip
  hh_file                                             site_id
1 AMF_AR-TF1_FLUXNET_FLUXMET_HH_2016-2018_v1.3_r1.csv AR-TF1
2 AMF_AR-TF2_FLUXNET_FLUXMET_HH_2016-2018_v1.3_r1.csv AR-TF2
3 EUF_AT-Mmg_FLUXNET_FLUXMET_HH_2021-2024_v1.3_r1.csv AT-Mmg
4 EUF_AT-Nsd_FLUXNET_FLUXMET_HH_2018-2022_v1.3_r1.csv AT-Nsd
5 EUF_AT-PsM_FLUXNET_FLUXMET_HH_2015-2019_v1.3_r1.csv AT-PsM
6 EUF_AT-Zoe_FLUXNET_FLUXMET_HH_2014-2024_v1.3_r1.csv AT-Zoe

## 2. Load site metadata

In [3]:
# ============================================================
# 2. Load site metadata
# Required columns: SITE_ID, LOCATION_LAT, LOCATION_LONG, LOCATION_ELEV
# ============================================================

tower_meta <- readr::read_csv(meta_path, show_col_types = FALSE)

# Verify required columns exist
required_meta_cols <- c("SITE_ID", "LOCATION_LAT", "LOCATION_LONG", "LOCATION_ELEV")
missing_cols <- setdiff(required_meta_cols, names(tower_meta))
if (length(missing_cols) > 0)
  stop("Metadata is missing columns: ", paste(missing_cols, collapse = ", "))

cat("Sites in metadata:", nrow(tower_meta), "\n")
cat("Sites in zip index:", n_distinct(zip_index$site_id), "\n")
cat("Sites with both zip and metadata:",
    sum(zip_index$site_id %in% tower_meta$SITE_ID), "\n")

Sites in metadata: 357
Sites in zip index: 329
Sites with both zip and metadata: 329

## 3. Utility functions

Includes the previously missing `TimeZoneCalculatorFLUXNET()`.

In [4]:
# ============================================================
# 3. Utility functions
# ============================================================

# FIX 1: TimeZoneCalculatorFLUXNET was called inside EFPcalc but never defined.
TimeZoneCalculatorFLUXNET <- function(lat, lon) {
  if (!requireNamespace("lutz", quietly = TRUE) ||
      !requireNamespace("sf",   quietly = TRUE)) {
    message("lutz/sf not available — defaulting to UTC (TimeZone = 0)")
    return(0)
  }
  tz_name <- lutz::tz_lookup_coords(lat, lon, method = "accurate", warn = FALSE)
  offset  <- lutz::tz_offset(
    as.POSIXct("2018-07-01 12:00:00", tz = "UTC"), tz_name
  )
  as.numeric(offset$utc_offset_h)
}

# Safe quantile and mean helpers
q_safe    <- function(x, prob) {
  x <- x[is.finite(x)]
  if (length(x) == 0) return(NA_real_)
  as.numeric(stats::quantile(x, probs = prob, na.rm = TRUE, names = FALSE))
}
mean_safe <- function(x) { x <- x[is.finite(x)]; if (!length(x)) NA_real_ else mean(x) }

# Convert -9999 sentinel values to NA; return NA column if column absent
clean_col <- function(df, col) {
  if (col %in% names(df)) dplyr::na_if(df[[col]], -9999) else NA_real_
}

cat("Utility functions defined.\n")

Utility functions defined.

## 4. Read and standardise one FLUXMET HH file

In [5]:
# ============================================================
# 4. read_fluxmet_hh
# DATETIME is based on TIMESTAMP_END (REddyProc convention).
# YEAR / DOY are derived from TIMESTAMP_START so the final
# half-hour of a year stays in the correct year.
# ============================================================

read_fluxmet_hh <- function(zip_path, hh_file, site_id,
                            start_year = 2017, end_year = 2025) {

  dat <- readr::read_csv(unz(zip_path, hh_file),
                         show_col_types = FALSE, progress = FALSE)

  dat_clean <- dat %>%
    mutate(
      SITE_ID  = site_id,
      siteID   = site_id,

      DATETIME_START = lubridate::ymd_hm(as.character(TIMESTAMP_START), tz = "UTC"),
      DATETIME_END   = lubridate::ymd_hm(as.character(TIMESTAMP_END),   tz = "UTC"),
      DATETIME = DATETIME_END,
      DateTime = DATETIME_END,

      YEAR         = lubridate::year(DATETIME_START),
      year         = YEAR,
      MONTH        = lubridate::month(DATETIME_START),
      DOY          = lubridate::yday(DATETIME_START),
      doy          = DOY,
      HOUR_decimal = lubridate::hour(DATETIME_START) +
                     lubridate::minute(DATETIME_START) / 60,

      # Fluxes
      GPP    = clean_col(cur_data(), "GPP_NT_VUT_REF"),
      GPP_NT = GPP,
      RECO   = clean_col(cur_data(), "RECO_NT_VUT_REF"),
      RECO_NT = RECO,
      NEE    = clean_col(cur_data(), "NEE_VUT_REF"),
      NEP    = -NEE,
      LE     = clean_col(cur_data(), "LE_F_MDS"),
      H      = clean_col(cur_data(), "H_F_MDS"),

      # Meteorology
      TA     = clean_col(cur_data(), "TA_F"),
      VPD    = clean_col(cur_data(), "VPD_F"),
      VPD_kPa = VPD / 10,
      SW_IN  = clean_col(cur_data(), "SW_IN_F"),
      PPFD_IN_FROM_SWIN = SW_IN * 2.11,
      P      = clean_col(cur_data(), "P_F"),
      Precip = P,
      PA     = clean_col(cur_data(), "PA_F"),
      WS     = clean_col(cur_data(), "WS_F"),
      USTAR  = clean_col(cur_data(), "USTAR"),
      # NETRAD not always present; fallback handled downstream
      NETRAD = if ("NETRAD" %in% names(cur_data()))
                 dplyr::na_if(NETRAD, -9999) else NA_real_,
      G      = if ("G_F_MDS" %in% names(cur_data()))
                 dplyr::na_if(G_F_MDS, -9999) else NA_real_,
      CO2    = if ("CO2_F_MDS" %in% names(cur_data()))
                 dplyr::na_if(CO2_F_MDS, -9999) else NA_real_,

      # FIX 7: QC columns — map FLUXNET names; use 0 where absent
      # FLUXNET QC scale: 0 = measured, 1 = good gap-fill, 2-3 = poor gap-fill
      NEE_QC   = if ("NEE_VUT_REF_QC" %in% names(cur_data()))
                   dplyr::na_if(NEE_VUT_REF_QC, -9999) else 0L,
      LE_QC    = if ("LE_F_MDS_QC"    %in% names(cur_data()))
                   dplyr::na_if(LE_F_MDS_QC,    -9999) else 0L,
      H_QC     = if ("H_F_MDS_QC"     %in% names(cur_data()))
                   dplyr::na_if(H_F_MDS_QC,     -9999) else 0L,
      TA_QC    = if ("TA_F_QC"         %in% names(cur_data()))
                   dplyr::na_if(TA_F_QC,         -9999) else 0L,
      VPD_QC   = if ("VPD_F_QC"        %in% names(cur_data()))
                   dplyr::na_if(VPD_F_QC,        -9999) else 0L,
      SW_IN_QC = if ("SW_IN_F_QC"      %in% names(cur_data()))
                   dplyr::na_if(SW_IN_F_QC,      -9999) else 0L
    ) %>%
    filter(YEAR >= start_year, YEAR <= end_year) %>%
    group_by(SITE_ID, YEAR) %>%
    arrange(DATETIME_START, .by_group = TRUE) %>%
    mutate(FiveDaySeq = ceiling(row_number() / (48 * 5))) %>%
    ungroup()

  dat_clean
}

cat("read_fluxmet_hh() defined.\n")

read_fluxmet_hh() defined.

## 5. Per-year EFP calculation function

FIX 4 & 6: Replaced the full-site `EFPcalc()` with a proper per-year version.
FIX 5: REddyProc arguments use the current API (no `.s`/`.n` suffixes).

In [6]:
# ============================================================
# 5. EFPcalc_year — calculate EFPs for ONE site-year
# ============================================================
# Arguments:
#   dat_year  : data.frame, one year of half-hourly FLUXMET data
#               (already standardised by read_fluxmet_hh)
#   site      : character site ID
#   yr        : integer year
#   lat, lon  : numeric coordinates
#   elevation : numeric, metres
#   timezone  : numeric UTC offset hours (from TimeZoneCalculatorFLUXNET)
# Returns a one-row data.frame of EFPs.
# ============================================================

EFPcalc_year <- function(dat_year, site, yr, lat, lon, elevation, timezone) {

  GSfilt <- 0.3

  # ── Derived columns needed by bigleaf / REddyProc ────────
  dat_year <- dat_year %>%
    mutate(
      ET = if (requireNamespace("bigleaf", quietly = TRUE))
             bigleaf::LE.to.ET(LE, TA) * 1800 else NA_real_,
      NETRAD = if_else(is.na(NETRAD), SW_IN, NETRAD)  # fallback if absent
    )

  # ── Empty output returned on failure ─────────────────────
  empty_out <- tibble(
    SITE_ID = site, YEAR = yr,
    uWUE = NA_real_, WUE = NA_real_, ETmax = NA_real_,
    precipAvail = NA_character_, Gavail = NA_character_,
    GSmax = NA_real_, CO2avail = NA_character_, G1 = NA_real_,
    EF = NA_real_, EFampl = NA_real_,
    GPPsat = NA_real_, NEPmax = NA_real_,
    Rb = NA_real_, Rbmax = NA_real_, aCUE = NA_real_,
    TZ = timezone, nyears = 1L, status = "failed"
  )

  # ── Require bigleaf ───────────────────────────────────────
  if (!requireNamespace("bigleaf", quietly = TRUE)) {
    warning("bigleaf not installed — returning NA for site-year ", site, "-", yr)
    return(empty_out)
  }

  # ── Growing-season + precip filters ──────────────────────
  # FIX 7: bigleaf::filter.data uses QC columns with quality.ext appended
  # to vars.qc names. Here we pass good.quality = 1 which keeps QC in {0, 1}
  # (measured + good gap-fill on the FLUXNET 0–3 scale).
  # We exclude 'VPD' from vars.qc because VPD_QC can be absent in some files.
  qc_vars_available <- intersect(
    c("TA", "H", "LE", "NEE"),
    gsub("_QC", "", grep("_QC$", names(dat_year), value = TRUE))
  )

  precipAvail <- if (!all(is.na(dat_year$P)) && sum(dat_year$P > 0, na.rm = TRUE) > 0)
    "yes" else "no"

  dat_filtered <- tryCatch(
    bigleaf::filter.data(
      data.frame(dat_year),
      quality.control   = length(qc_vars_available) > 0,
      filter.growseas   = TRUE,
      filter.precip     = precipAvail == "yes",
      GPP = "GPP_NT", doy = "doy", year = "year", tGPP = GSfilt,
      precip = "P", tprecip = 0.1, precip.hours = 24,
      records.per.hour  = 2,
      vars.qc           = qc_vars_available,
      quality.ext       = "_QC",
      good.quality      = 1
    ),
    error = function(e) {
      message("  filter.data error for ", site, "-", yr, ": ", e$message)
      data.frame(dat_year)[0, ]  # empty frame → downstream checks return NA
    }
  )

  # Daytime + u* subset
  aaa <- subset(dat_filtered, SW_IN > 200 & USTAR > 0.2)

  out <- as.list(empty_out)
  out$precipAvail <- precipAvail
  out$TZ          <- timezone

  if (nrow(aaa) < 40) {
    warning("  Too few daytime records (", nrow(aaa), ") for ", site, "-", yr)
    return(as.data.frame(out))
  }

  # ── WUE / uWUE / ETmax ───────────────────────────────────
  wue <- tryCatch({
    bigleaf::WUE.metrics(
      aaa, GPP = "GPP_NT", NEE = "NEE", LE = "LE",
      VPD = "VPD_kPa", Tair = "TA",
      constants = bigleaf::bigleaf.constants()
    )
  }, error = function(e) NULL)

  if (!is.null(wue)) {
    out$uWUE <- wue[["uWUE"]]
    out$WUE  <- wue[["WUE"]]
  }
  out$ETmax <- q_safe(aaa$ET, 0.95)

  # ── Gsmax and G1 ─────────────────────────────────────────
  aaa_gs <- aaa %>% tidyr::drop_na(WS)

  if (nrow(aaa_gs) >= 10) {
    aaa_gs$pressure <- bigleaf::pressure.from.elevation(
      elevation, aaa_gs$TA, aaa_gs$VPD_kPa
    )

    Ga_vec <- tryCatch(
      bigleaf::aerodynamic.conductance(
        aaa_gs, Tair = "TA", pressure = "pressure",
        wind = "WS", ustar = "USTAR", H = "H",
        Rb_model = "Thom_1972"
      )[["Ga_h"]],
      error = function(e) NULL
    )

    if (!is.null(Ga_vec)) {
      Gs <- tryCatch(
        bigleaf::surface.conductance(
          aaa_gs, Ga = Ga_vec, Tair = "TA", pressure = "pressure",
          Rn = "NETRAD",
          G = if (all(is.na(aaa_gs$G))) NULL else "G",
          S = NULL, VPD = "VPD_kPa", LE = "LE",
          missing.G.as.NA = FALSE, missing.S.as.NA = FALSE
        ),
        error = function(e) NULL
      )

      out$Gavail <- if (all(is.na(aaa_gs$G))) "no" else "yes"

      if (!is.null(Gs)) {
        out$GSmax <- q_safe(Gs$Gs_ms, 0.90)

        aaa_gs$Gs_mol <- Gs$Gs_mol
        aaa_gs <- aaa_gs %>%
          tidyr::drop_na(Gs_mol) %>%
          filter(VPD_kPa > 0)

        if (nrow(aaa_gs) >= 40) {
          if (all(is.na(aaa_gs$CO2))) {
            aaa_gs$CO2 <- 400
            out$CO2avail <- "no"
          } else {
            out$CO2avail <- "yes"
          }

          mod_USO <- tryCatch(
            bigleaf::stomatal.slope(
              aaa_gs, model = "USO", GPP = "GPP_NT", Gs = "Gs_mol",
              Tair = "TA", pressure = "pressure", VPD = "VPD_kPa", Ca = "CO2",
              robust.nls = TRUE, nmin = 40, fitg0 = FALSE
            ),
            error = function(e) NULL
          )
          if (!is.null(mod_USO) && requireNamespace("broom", quietly = TRUE))
            out$G1 <- broom::tidy(mod_USO)$estimate[1]
        }
      }
    }
  }

  # ── EF / EFampl ──────────────────────────────────────────
  aaa$EF <- aaa$LE / (aaa$LE + aaa$H)
  aaa_ef  <- aaa[is.finite(aaa$EF), ]
  if (nrow(aaa_ef) > 0) {
    out$EF     <- median(aaa_ef$EF, na.rm = TRUE)
    out$EFampl <- q_safe(aaa_ef$EF, 0.75) - q_safe(aaa_ef$EF, 0.25)
  }

  # ── GPPsat and NEPmax via 5-day light-response curve ─────
  myLRC <- function(datafilt) {
    if (nrow(datafilt) < 10) return(NA_real_)
    if (mean(is.na(datafilt$NEE)) >= 0.8) return(NA_real_)
    tryCatch({
      fitLRC <- bigleaf::light.response(
        datafilt, NEE = "NEE", Reco = "Reco", PPFD = "PPFD", PPFD_ref = 2000
      )
      if (requireNamespace("broom", quietly = TRUE))
        broom::tidy(fitLRC)$estimate[2]
      else fitLRC$coefficients[2]
    }, error = function(e) NA_real_)
  }

  # For GPPsat, use only growing-season filter (no precip filter)
  dat_lrc <- tryCatch(
    bigleaf::filter.data(
      data.frame(dat_year),
      quality.control = length(qc_vars_available) > 0,
      filter.growseas = TRUE, filter.precip = FALSE,
      GPP = "GPP_NT", doy = "doy", year = "year", tGPP = GSfilt,
      precip = "P", tprecip = 0.1, precip.hours = 24,
      records.per.hour = 2,
      vars.qc = qc_vars_available, quality.ext = "_QC", good.quality = 1
    ),
    error = function(e) data.frame(dat_year)[0, ]
  )

  if (nrow(dat_lrc) > 48 * 5) {
    dat_lrc$FiveDaySeq <- ceiling(seq_len(nrow(dat_lrc)) / (48 * 5))
    zzz <- data.frame(
      NEE = dat_lrc$NEE, PPFD = dat_lrc$PPFD_IN_FROM_SWIN,
      Reco = dat_lrc$RECO_NT, FiveDaySeq = dat_lrc$FiveDaySeq
    )
    outGPPsat <- unlist(by(zzz, zzz$FiveDaySeq, myLRC), use.names = FALSE)
    out$GPPsat <- q_safe(outGPPsat, 0.90)
    daytime_nep <- subset(zzz, PPFD > 200 * 2.11)$NEE * -1
    out$NEPmax  <- q_safe(daytime_nep, 0.99)
  }

  # ── Basal respiration (Rb, Rbmax) via REddyProc ──────────
  # FIX 5: Use current REddyProc API (no .s/.n suffixes on arguments)
  if (requireNamespace("REddyProc", quietly = TRUE)) {
    tryCatch({
      ttt <- data.frame(dat_year) %>%
        dplyr::select(
          DateTime, NEE, NEE_QC, SW_IN, SW_IN_QC, TA, TA_QC
        ) %>%
        rename(
          NEE_QC_OK   = NEE_QC,
          SW_IN_QC_OK = SW_IN_QC,
          TA_QC_OK    = TA_QC
        ) %>%
        mutate(
          # Convert FLUXNET QC (0=measured, 1=good fill) to binary 0/1
          NEE_QC_OK   = as.integer(NEE_QC_OK   <= 1),
          SW_IN_QC_OK = as.integer(SW_IN_QC_OK <= 1),
          TA_QC_OK    = as.integer(TA_QC_OK    <= 1),
          # REddyProc expects DateTime at the end of the half-hour
          DateTime = as.POSIXct(DateTime, tz = "UTC")
        )

      ep <- REddyProc::sEddyProc$new(
        site, ttt,
        c("NEE", "NEE_QC_OK", "SW_IN", "SW_IN_QC_OK", "TA", "TA_QC_OK"),
        LatDeg = as.numeric(lat), LongDeg = as.numeric(lon),
        TimeZoneHour = timezone
      )

      # FIX 5: Current REddyProc API — no .s/.n argument suffixes
      ep$sMRFluxPartition(
        FluxVar    = "NEE",
        QFFluxVar  = "NEE_QC_OK",
        QFFluxValue = 0,          # use only QC_OK == 0 (measured)
        TempVar    = "TA",
        QFTempVar  = "TA_QC_OK",
        QFTempValue = 0,
        RadVar     = "SW_IN",
        TRef       = 273.15 + 15,
        suffix     = ""
      )

      Rref <- ep$sTEMP$R_ref
      out$Rb    <- mean_safe(Rref)
      out$Rbmax <- q_safe(Rref, 0.95)

      # ── aCUE ─────────────────────────────────────────────
      dat_year$Rb_hh <- Rref
      dat_cue <- dat_year %>%
        filter(doy %in% dat_lrc$doy) %>%   # growing-season rows only
        group_by(year, doy) %>%
        summarise(
          mean_GPP = mean(GPP_NT, na.rm = TRUE),
          mean_Rb  = mean(Rb_hh,  na.rm = TRUE),
          .groups  = "drop"
        )
      out$aCUE <- median(1 - dat_cue$mean_Rb / dat_cue$mean_GPP, na.rm = TRUE)

    }, error = function(e)
      message("  REddyProc error for ", site, "-", yr, ": ", e$message)
    )
  }

  out$SITE_ID <- site
  out$YEAR    <- yr
  out$nyears  <- 1L
  out$status  <- "ok"

  as.data.frame(out)
}

cat("EFPcalc_year() defined.\n")

EFPcalc_year() defined.

## 6. Monthly meteorology function

FIX 2: `calc_monthly_meteo()` was called in the batch loop but never defined.

In [ ]:
# ============================================================
# 6. calc_monthly_meteo
# ============================================================

calc_monthly_meteo <- function(dat_full) {
  dat_full %>%
    group_by(SITE_ID, YEAR, MONTH) %>%
    summarise(
      TA_mean   = mean_safe(TA),
      TA_p05    = q_safe(TA,    0.05),
      TA_p95    = q_safe(TA,    0.95),
      VPD_mean  = mean_safe(VPD),
      VPD_p05   = q_safe(VPD,  0.05),
      VPD_p95   = q_safe(VPD,  0.95),
      SW_IN_mean = mean_safe(SW_IN),
      SW_IN_p05  = q_safe(SW_IN, 0.05),
      SW_IN_p95  = q_safe(SW_IN, 0.95),
      P_sum     = sum_safe(P),
      P_mean    = mean_safe(P),
      P_p05     = q_safe(P, 0.05),
      P_p95     = q_safe(P, 0.95),
      n_obs     = n(),
      .groups   = "drop"
    )
}

sum_safe <- function(x) { x <- x[is.finite(x)]; if (!length(x)) NA_real_ else sum(x) }

cat("calc_monthly_meteo() defined.\n")

## 7. Yearly EFP orchestrator

FIX 1: `calc_yearly_efps_full()` was called in the batch loop but never defined.
This function loops over years and calls `EFPcalc_year()` for each.

In [8]:
# ============================================================
# 7. calc_yearly_efps_full — orchestrates per-year EFP calculation
# ============================================================

calc_yearly_efps_full <- function(dat_full, site_id, tower_meta_df) {

  # Get site metadata
  smeta <- tower_meta_df[tower_meta_df$SITE_ID == site_id, ][1, ]
  if (nrow(smeta) == 0 || is.na(smeta$LOCATION_LAT)) {
    warning("No metadata for ", site_id, " — skipping")
    return(tibble())
  }

  lat       <- as.numeric(smeta$LOCATION_LAT)
  lon       <- as.numeric(smeta$LOCATION_LONG)
  elevation <- as.numeric(smeta$LOCATION_ELEV)
  timezone  <- TimeZoneCalculatorFLUXNET(lat, lon)

  years <- sort(unique(dat_full$YEAR))
  cat("  Site:", site_id, "| Years:", paste(years, collapse = ", "), "\n")

  results <- purrr::map_dfr(years, function(yr) {
    dat_yr <- dat_full %>% filter(YEAR == yr)

    # Skip year if too few half-hours (< 3 months of data)
    if (nrow(dat_yr) < 48 * 30 * 3) {
      message("  Skipping ", site_id, "-", yr,
              " (only ", nrow(dat_yr), " half-hours)")
      return(tibble(
        SITE_ID = site_id, YEAR = yr, status = "insufficient_data"
      ))
    }

    tryCatch(
      EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone),
      error = function(e) {
        message("  ERROR ", site_id, "-", yr, ": ", e$message)
        tibble(SITE_ID = site_id, YEAR = yr, status = "error")
      }
    )
  })

  results
}

cat("calc_yearly_efps_full() defined.\n")

calc_yearly_efps_full() defined.

## 8. Test on a single site-year

FIX 4 & 9: Fixed the call signature and removed references to undefined objects.

In [9]:
# ============================================================
# 8. Quick test on first available site + first year
# ============================================================

# Pick the first site that also has metadata
test_candidates <- zip_index$site_id[zip_index$site_id %in% tower_meta$SITE_ID]
if (length(test_candidates) == 0) stop("No sites found in both zip_index and tower_meta.")
test_site_id <- test_candidates[1]

cat("Test site:", test_site_id, "\n")

# Read the data
test_row <- zip_index[zip_index$site_id == test_site_id, ][1, ]
test_dat <- read_fluxmet_hh(
  zip_path   = test_row$zip_path,
  hh_file    = test_row$hh_file,
  site_id    = test_site_id,
  start_year = start_year,
  end_year   = end_year
)
cat("Rows loaded:", nrow(test_dat), "| Years:",
    paste(sort(unique(test_dat$YEAR)), collapse = ", "), "\n")

# Get metadata for this site
test_meta <- tower_meta[tower_meta$SITE_ID == test_site_id, ][1, ]
test_lat  <- as.numeric(test_meta$LOCATION_LAT)
test_lon  <- as.numeric(test_meta$LOCATION_LONG)
test_elev <- as.numeric(test_meta$LOCATION_ELEV)
test_tz   <- TimeZoneCalculatorFLUXNET(test_lat, test_lon)

# Test EFPcalc_year on the first available year
test_yr   <- sort(unique(test_dat$YEAR))[1]
test_dat_yr <- test_dat %>% filter(YEAR == test_yr)

# FIX 4: Correct function call — EFPcalc_year requires all arguments
test_out <- EFPcalc_year(
  dat_year  = test_dat_yr,
  site      = test_site_id,
  yr        = test_yr,
  lat       = test_lat,
  lon       = test_lon,
  elevation = test_elev,
  timezone  = test_tz
)

cat("\nTest output for", test_site_id, test_yr, ":\n")
print(t(test_out))

Test site: AR-TF1

Warning message:
“There was 1 warning in `mutate()`.
ℹ In argument: `GPP = clean_col(cur_data(), "GPP_NT_VUT_REF")`.
Caused by warning:
! `cur_data()` was deprecated in dplyr 1.1.0.
ℹ Please use `pick()` instead.”

Rows loaded: 35040 | Years: 2017, 2018

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

Quality control:
TA: 179 data points (1.02%) set to NA
H: 207 data points (1.18%) set to NA
LE: 210 data points (1.2%) set to NA
NEE: 301 data points (1.72%) set to NA
-------------------------------------------------------------------
Data filtering:
8448 data points (48.22%) excluded by growing season filter
7856 additional data points (44.84%) excluded by precipitation filter (14682
 data points = 83.8 % in total)
16304 data points (93.06%) excluded in total
1216 valid data points (6.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 179 data points (1.02%) set to NA
H: 207 data points (1.18%) set to NA
LE: 210 data points (1.2%) set to NA
NEE: 301 data points (1.72%) set to NA
-------------------------------------------------------------------
Data filtering:
8448 data points (48.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8448 data points (48.22%) excluded in total
9072 valid data points (51.78%) remaining.

New sEddyProc class for site 'AR-TF1'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 97.99.

Regression of reference temperature R_ref for 4 periods.

Test output for AR-TF1 2017 :
            [,1]
SITE_ID     "AR-TF1"
YEAR        "2017"
uWUE        "1.372171"
WUE         "1.818027"
ETmax       "0.1828751"
precipAvail "yes"
Gavail      "no"
GSmax       "0.004534142"
CO2avail    "yes"
G1          "2.148585"
EF          "0.5637964"
EFampl      "0.2728276"
GPPsat      "11.10238"
NEPmax      "8.869746"
Rb          "1.149991"
Rbmax       "1.262253"
aCUE        "0.5997774"
TZ          "-3"
nyears      "1"
status      "ok"

## 9. Batch processing — all sites, all years

In [10]:
# ============================================================
# 9. Batch processing
# Writes per-site CSV files immediately so partial runs are not lost.
# Set skip_existing = TRUE to resume an interrupted run.
# ============================================================

skip_existing  <- TRUE
failed_records <- list()

# Process only sites present in BOTH zip_index and tower_meta
sites_to_run <- zip_index %>%
  filter(site_id %in% tower_meta$SITE_ID) %>%
  distinct(site_id, .keep_all = TRUE)

cat("Sites to process:", nrow(sites_to_run), "\n\n")

for (i in seq_len(nrow(sites_to_run))) {

  site_i     <- sites_to_run$site_id[i]
  efp_file_i <- file.path(efp_dir,   paste0(site_i, "_yearly_EFP.csv"))
  met_file_i <- file.path(meteo_dir, paste0(site_i, "_monthly_meteo.csv"))

  if (skip_existing && file.exists(efp_file_i) && file.exists(met_file_i)) {
    message("Skipping (output exists): ", site_i)
    next
  }

  message(sprintf("[%d/%d] Processing: %s", i, nrow(sites_to_run), site_i))

  tryCatch({
    dat_i <- read_fluxmet_hh(
      zip_path   = sites_to_run$zip_path[i],
      hh_file    = sites_to_run$hh_file[i],
      site_id    = site_i,
      start_year = start_year,
      end_year   = end_year
    )

    if (nrow(dat_i) < 48 * 30 * 3)
      stop("Too little data after year filtering: ", nrow(dat_i), " rows")

    efp_i  <- calc_yearly_efps_full(dat_i, site_i, tower_meta)
    meteo_i <- calc_monthly_meteo(dat_i)

    readr::write_csv(efp_i,   efp_file_i)
    readr::write_csv(meteo_i, met_file_i)

  }, error = function(e) {
    msg <- e$message
    message("  FAILED: ", msg)
    failed_records[[length(failed_records) + 1]] <<- tibble(
      site_id  = site_i,
      zip_path = sites_to_run$zip_path[i],
      hh_file  = sites_to_run$hh_file[i],
      error    = msg
    )
  })
}

failed_df <- bind_rows(failed_records)
readr::write_csv(failed_df, file.path(qc_dir, "failed_sites_batch.csv"))

cat("\nBatch complete.\n")
cat("Failed sites this run:", nrow(failed_df), "\n")
if (nrow(failed_df) > 0) print(failed_df)

Sites to process: 329

[1/329] Processing: AR-TF1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: AR-TF1 | Years: 2017, 2018
Quality control:
TA: 179 data points (1.02%) set to NA
H: 207 data points (1.18%) set to NA
LE: 210 data points (1.2%) set to NA
NEE: 301 data points (1.72%) set to NA
-------------------------------------------------------------------
Data filtering:
8448 data points (48.22%) excluded by growing season filter
7856 additional data points (44.84%) excluded by precipitation filter (14682
 data points = 83.8 % in total)
16304 data points (93.06%) excluded in total
1216 valid data points (6.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 179 data points (1.02%) set to NA
H: 207 data points (1.18%) set to NA
LE: 210 data points (1.2%) set to NA
NEE: 301 data points (1.72%) set to NA
-------------------------------------------------------------------
Data filtering:
8448 data points (48.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8448 data points (48.22%) excluded in total
9072 valid data points (51.78%) remaining.

New sEddyProc class for site 'AR-TF1'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 97.99.

Regression of reference temperature R_ref for 4 periods.

Quality control:
TA: 10942 data points (62.45%) set to NA
H: 11322 data points (64.62%) set to NA
LE: 11328 data points (64.66%) set to NA
NEE: 11444 data points (65.32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
14366 additional data points (82%) excluded by precipitation filter (14366
 data points = 82 % in total)
14366 data points (82%) excluded in total
3154 valid data points (18%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10942 data points (62.45%) set to NA
H: 11322 data points (64.62%) set to NA
LE: 11328 data points (64.66%) set to NA
NEE: 11444 data points (65.32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'AR-TF1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AR-TF1-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[2/329] Processing: AR-TF2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: AR-TF2 | Years: 2017, 2018
Quality control:
TA: 0 data points (0%) set to NA
H: 597 data points (3.41%) set to NA
LE: 600 data points (3.42%) set to NA
NEE: 982 data points (5.61%) set to NA
-------------------------------------------------------------------
Data filtering:
9024 data points (51.51%) excluded by growing season filter
7500 additional data points (42.81%) excluded by precipitation filter (15056
 data points = 85.94 % in total)
16524 data points (94.32%) excluded in total
996 valid data points (5.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 597 data points (3.41%) set to NA
LE: 600 data points (3.42%) set to NA
NEE: 982 data points (5.61%) set to NA
-------------------------------------------------------------------
Data filtering:
9024 data points (51.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9024 data points (51.51%) excluded in total
8496 valid data points (48.49%) remaining.

New sEddyProc class for site 'AR-TF2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AR-TF2-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 12462 data points (71.13%) set to NA
H: 14524 data points (82.9%) set to NA
LE: 14526 data points (82.91%) set to NA
NEE: 15200 data points (86.76%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
14072 additional data points (80.32%) excluded by precipitation filter (14072
 data points = 80.32 % in total)
14072 data points (80.32%) excluded in total
3448 valid data points (19.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12462 data points (71.13%) set to NA
H: 14524 data points (82.9%) set to NA
LE: 14526 data points (82.91%) set to NA
NEE: 15200 data points (86.76%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'AR-TF2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AR-TF2-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[3/329] Processing: AT-Mmg

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: AT-Mmg | Years: 2021, 2022, 2023, 2024
Quality control:
TA: 11789 data points (67.29%) set to NA
H: 7544 data points (43.06%) set to NA
LE: 7582 data points (43.28%) set to NA
NEE: 9956 data points (56.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 138”

-------------------------------------------------------------------
Data filtering:
2976 data points (16.99%) excluded by growing season filter
7502 additional data points (42.82%) excluded by precipitation filter (8422
 data points = 48.07 % in total)
10478 data points (59.81%) excluded in total
7042 valid data points (40.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11789 data points (67.29%) set to NA
H: 7544 data points (43.06%) set to NA
LE: 7582 data points (43.28%) set to NA
NEE: 9956 data points (56.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 138”

-------------------------------------------------------------------
Data filtering:
2976 data points (16.99%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2976 data points (16.99%) excluded in total
14544 valid data points (83.01%) remaining.

New sEddyProc class for site 'AT-Mmg'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 228.52.

Regression of reference temperature R_ref for 31 periods.

Quality control:
TA: 57 data points (0.33%) set to NA
H: 86 data points (0.49%) set to NA
LE: 82 data points (0.47%) set to NA
NEE: 1372 data points (7.83%) set to NA
-------------------------------------------------------------------
Data filtering:
5952 data points (33.97%) excluded by growing season filter
5069 additional data points (28.93%) excluded by precipitation filter (6882
 data points = 39.28 % in total)
11021 data points (62.91%) excluded in total
6499 valid data points (37.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 57 data points (0.33%) set to NA
H: 86 data points (0.49%) set to NA
LE: 82 data points (0.47%) set to NA
NEE: 1372 data points (7.83%) set to NA
-------------------------------------------------------------------
Data filtering:
5952 data points (33.97%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5952 data points (33.97%) excluded in total
11568 valid data points (66.03%) remaining.

New sEddyProc class for site 'AT-Mmg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-Mmg-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 101 data points (0.58%) set to NA
H: 138 data points (0.79%) set to NA
LE: 206 data points (1.18%) set to NA
NEE: 2058 data points (11.75%) set to NA
-------------------------------------------------------------------
Data filtering:
6096 data points (34.79%) excluded by growing season filter
5458 additional data points (31.15%) excluded by precipitation filter (7764
 data points = 44.32 % in total)
11554 data points (65.95%) excluded in total
5966 valid data points (34.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 101 data points (0.58%) set to NA
H: 138 data points (0.79%) set to NA
LE: 206 data points (1.18%) set to NA
NEE: 2058 data points (11.75%) set to NA
-------------------------------------------------------------------
Data filtering:
6096 data points (34.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6096 data points (34.79%) excluded in total
11424 valid data points (65.21%) remaining.

New sEddyProc class for site 'AT-Mmg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-Mmg-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 101 data points (0.57%) set to NA
H: 128 data points (0.73%) set to NA
LE: 124 data points (0.71%) set to NA
NEE: 2336 data points (13.3%) set to NA
-------------------------------------------------------------------
Data filtering:
5568 data points (31.69%) excluded by growing season filter
5809 additional data points (33.07%) excluded by precipitation filter (7462
 data points = 42.47 % in total)
11377 data points (64.76%) excluded in total
6191 valid data points (35.24%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 101 data points (0.57%) set to NA
H: 128 data points (0.73%) set to NA
LE: 124 data points (0.71%) set to NA
NEE: 2336 data points (13.3%) set to NA
-------------------------------------------------------------------
Data filtering:
5568 data points (31.69%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5568 data points (31.69%) excluded in total
12000 valid data points (68.31%) remaining.

New sEddyProc class for site 'AT-Mmg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-Mmg-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[4/329] Processing: AT-Nsd

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: AT-Nsd | Years: 2018, 2019, 2020, 2021, 2022
Quality control:
TA: 8680 data points (49.54%) set to NA
H: 8870 data points (50.63%) set to NA
LE: 9237 data points (52.72%) set to NA
NEE: 8835 data points (50.43%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 171”

-------------------------------------------------------------------
Data filtering:
4800 data points (27.4%) excluded by growing season filter
4519 additional data points (25.79%) excluded by precipitation filter (5939
 data points = 33.9 % in total)
9319 data points (53.19%) excluded in total
8201 valid data points (46.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8680 data points (49.54%) set to NA
H: 8870 data points (50.63%) set to NA
LE: 9237 data points (52.72%) set to NA
NEE: 8835 data points (50.43%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 171”

-------------------------------------------------------------------
Data filtering:
4800 data points (27.4%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4800 data points (27.4%) excluded in total
12720 valid data points (72.6%) remaining.

New sEddyProc class for site 'AT-Nsd'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 197.59.

Regression of reference temperature R_ref for 5 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 101 data points (0.58%) set to NA
LE: 113 data points (0.64%) set to NA
NEE: 272 data points (1.55%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
1780 additional data points (10.16%) excluded by precipitation filter (5329
 data points = 30.42 % in total)
12916 data points (73.72%) excluded in total
4604 valid data points (26.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 101 data points (0.58%) set to NA
LE: 113 data points (0.64%) set to NA
NEE: 272 data points (1.55%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11136 data points (63.56%) excluded in total
6384 valid data points (36.44%) remaining.

New sEddyProc class for site 'AT-Nsd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-Nsd-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1907 data points (10.85%) set to NA
LE: 2650 data points (15.08%) set to NA
NEE: 2792 data points (15.89%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.66%) excluded by growing season filter
2575 additional data points (14.66%) excluded by precipitation filter (5307
 data points = 30.21 % in total)
13231 data points (75.31%) excluded in total
4337 valid data points (24.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1907 data points (10.85%) set to NA
LE: 2650 data points (15.08%) set to NA
NEE: 2792 data points (15.89%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.66%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10656 data points (60.66%) excluded in total
6912 valid data points (39.34%) remaining.

New sEddyProc class for site 'AT-Nsd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-Nsd-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 331 data points (1.89%) set to NA
LE: 392 data points (2.24%) set to NA
NEE: 524 data points (2.99%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
1643 additional data points (9.38%) excluded by precipitation filter (4719
 data points = 26.93 % in total)
12779 data points (72.94%) excluded in total
4741 valid data points (27.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 331 data points (1.89%) set to NA
LE: 392 data points (2.24%) set to NA
NEE: 524 data points (2.99%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11136 data points (63.56%) excluded in total
6384 valid data points (36.44%) remaining.

New sEddyProc class for site 'AT-Nsd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-Nsd-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 789 data points (4.5%) set to NA
LE: 1350 data points (7.71%) set to NA
NEE: 1008 data points (5.75%) set to NA
-------------------------------------------------------------------
Data filtering:
11424 data points (65.21%) excluded by growing season filter
1931 additional data points (11.02%) excluded by precipitation filter (4715
 data points = 26.91 % in total)
13355 data points (76.23%) excluded in total
4165 valid data points (23.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 789 data points (4.5%) set to NA
LE: 1350 data points (7.71%) set to NA
NEE: 1008 data points (5.75%) set to NA
-------------------------------------------------------------------
Data filtering:
11424 data points (65.21%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11424 data points (65.21%) excluded in total
6096 valid data points (34.79%) remaining.

New sEddyProc class for site 'AT-Nsd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-Nsd-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[5/329] Processing: AT-PsM

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: AT-PsM | Years: 2017, 2018, 2019
Quality control:
TA: 0 data points (0%) set to NA
H: 1919 data points (10.95%) set to NA
LE: 4363 data points (24.9%) set to NA
NEE: 2535 data points (14.47%) set to NA
-------------------------------------------------------------------
Data filtering:
8976 data points (51.23%) excluded by growing season filter
4774 additional data points (27.25%) excluded by precipitation filter (9222
 data points = 52.64 % in total)
13750 data points (78.48%) excluded in total
3770 valid data points (21.52%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1919 data points (10.95%) set to NA
LE: 4363 data points (24.9%) set to NA
NEE: 2535 data points (14.47%) set to NA
-------------------------------------------------------------------
Data filtering:
8976 data points (51.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8976 data points (51.23%) excluded in total
8544 valid data points (48.77%) remaining.

New sEddyProc class for site 'AT-PsM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-PsM-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1344 data points (7.67%) set to NA
LE: 2310 data points (13.18%) set to NA
NEE: 1159 data points (6.62%) set to NA
-------------------------------------------------------------------
Data filtering:
8016 data points (45.75%) excluded by growing season filter
4126 additional data points (23.55%) excluded by precipitation filter (7691
 data points = 43.9 % in total)
12142 data points (69.3%) excluded in total
5378 valid data points (30.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1344 data points (7.67%) set to NA
LE: 2310 data points (13.18%) set to NA
NEE: 1159 data points (6.62%) set to NA
-------------------------------------------------------------------
Data filtering:
8016 data points (45.75%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8016 data points (45.75%) excluded in total
9504 valid data points (54.25%) remaining.

New sEddyProc class for site 'AT-PsM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-PsM-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1424 data points (8.13%) set to NA
LE: 1574 data points (8.98%) set to NA
NEE: 1403 data points (8.01%) set to NA
-------------------------------------------------------------------
Data filtering:
8064 data points (46.03%) excluded by growing season filter
4111 additional data points (23.46%) excluded by precipitation filter (8182
 data points = 46.7 % in total)
12175 data points (69.49%) excluded in total
5345 valid data points (30.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1424 data points (8.13%) set to NA
LE: 1574 data points (8.98%) set to NA
NEE: 1403 data points (8.01%) set to NA
-------------------------------------------------------------------
Data filtering:
8064 data points (46.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8064 data points (46.03%) excluded in total
9456 valid data points (53.97%) remaining.

New sEddyProc class for site 'AT-PsM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-PsM-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[6/329] Processing: AT-Zoe

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: AT-Zoe | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 6 data points (0.03%) set to NA
H: 4047 data points (23.1%) set to NA
LE: 4340 data points (24.77%) set to NA
NEE: 5342 data points (30.49%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 33”

-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
4201 additional data points (23.98%) excluded by precipitation filter (9289
 data points = 53.02 % in total)
13321 data points (76.03%) excluded in total
4199 valid data points (23.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6 data points (0.03%) set to NA
H: 4047 data points (23.1%) set to NA
LE: 4340 data points (24.77%) set to NA
NEE: 5342 data points (30.49%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 33”

-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9120 data points (52.05%) excluded in total
8400 valid data points (47.95%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -63, -63 ...”
New sEddyProc class for site 'AT-Zoe'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -63, -63 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-Zoe-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 142 data points (0.81%) set to NA
H: 10206 data points (58.25%) set to NA
LE: 16002 data points (91.34%) set to NA
NEE: 16396 data points (93.58%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8575 additional data points (48.94%) excluded by precipitation filter (8575
 data points = 48.94 % in total)
8575 data points (48.94%) excluded in total
8945 valid data points (51.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 142 data points (0.81%) set to NA
H: 10206 data points (58.25%) set to NA
LE: 16002 data points (91.34%) set to NA
NEE: 16396 data points (93.58%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'AT-Zoe'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-Zoe-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 5222 data points (29.81%) set to NA
LE: 6019 data points (34.36%) set to NA
NEE: 7193 data points (41.06%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 51”

-------------------------------------------------------------------
Data filtering:
8880 data points (50.68%) excluded by growing season filter
4075 additional data points (23.26%) excluded by precipitation filter (8578
 data points = 48.96 % in total)
12955 data points (73.94%) excluded in total
4565 valid data points (26.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5222 data points (29.81%) set to NA
LE: 6019 data points (34.36%) set to NA
NEE: 7193 data points (41.06%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 51”

-------------------------------------------------------------------
Data filtering:
8880 data points (50.68%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8880 data points (50.68%) excluded in total
8640 valid data points (49.32%) remaining.

New sEddyProc class for site 'AT-Zoe'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-Zoe-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 270 data points (1.54%) set to NA
H: 7468 data points (42.51%) set to NA
LE: 7459 data points (42.46%) set to NA
NEE: 8078 data points (45.98%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 61”

-------------------------------------------------------------------
Data filtering:
6240 data points (35.52%) excluded by growing season filter
5088 additional data points (28.96%) excluded by precipitation filter (8098
 data points = 46.1 % in total)
11328 data points (64.48%) excluded in total
6240 valid data points (35.52%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 270 data points (1.54%) set to NA
H: 7468 data points (42.51%) set to NA
LE: 7459 data points (42.46%) set to NA
NEE: 8078 data points (45.98%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 61”

-------------------------------------------------------------------
Data filtering:
6240 data points (35.52%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6240 data points (35.52%) excluded in total
11328 valid data points (64.48%) remaining.

New sEddyProc class for site 'AT-Zoe'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-Zoe-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 8184 data points (46.71%) set to NA
H: 6735 data points (38.44%) set to NA
LE: 8074 data points (46.08%) set to NA
NEE: 8126 data points (46.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 100”

-------------------------------------------------------------------
Data filtering:
9744 data points (55.62%) excluded by growing season filter
4316 additional data points (24.63%) excluded by precipitation filter (9516
 data points = 54.32 % in total)
14060 data points (80.25%) excluded in total
3460 valid data points (19.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8184 data points (46.71%) set to NA
H: 6735 data points (38.44%) set to NA
LE: 8074 data points (46.08%) set to NA
NEE: 8126 data points (46.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 100”

-------------------------------------------------------------------
Data filtering:
9744 data points (55.62%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9744 data points (55.62%) excluded in total
7776 valid data points (44.38%) remaining.

New sEddyProc class for site 'AT-Zoe'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-Zoe-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2190 data points (12.5%) set to NA
LE: 4465 data points (25.49%) set to NA
NEE: 7215 data points (41.18%) set to NA
-------------------------------------------------------------------
Data filtering:
7776 data points (44.38%) excluded by growing season filter
5349 additional data points (30.53%) excluded by precipitation filter (9982
 data points = 56.97 % in total)
13125 data points (74.91%) excluded in total
4395 valid data points (25.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2190 data points (12.5%) set to NA
LE: 4465 data points (25.49%) set to NA
NEE: 7215 data points (41.18%) set to NA
-------------------------------------------------------------------
Data filtering:
7776 data points (44.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7776 data points (44.38%) excluded in total
9744 valid data points (55.62%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 6 cases! Invalid values with 'NEE < -50': -59, -67, -55, -65, -70, -64 ...”
New sEddyProc class for site 'AT-Zoe'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 6 cases! Invalid values with 'NEE < -50': -59, -67, -55, -65, -70, -64 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-Zoe-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 196 data points (1.12%) set to NA
H: 3349 data points (19.12%) set to NA
LE: 3560 data points (20.32%) set to NA
NEE: 7055 data points (40.27%) set to NA
-------------------------------------------------------------------
Data filtering:
8592 data points (49.04%) excluded by growing season filter
3951 additional data points (22.55%) excluded by precipitation filter (9499
 data points = 54.22 % in total)
12543 data points (71.59%) excluded in total
4977 valid data points (28.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 196 data points (1.12%) set to NA
H: 3349 data points (19.12%) set to NA
LE: 3560 data points (20.32%) set to NA
NEE: 7055 data points (40.27%) set to NA
-------------------------------------------------------------------
Data filtering:
8592 data points (49.04%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8592 data points (49.04%) excluded in total
8928 valid data points (50.96%) remaining.

New sEddyProc class for site 'AT-Zoe'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-Zoe-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 7170 data points (40.81%) set to NA
LE: 10825 data points (61.62%) set to NA
NEE: 11805 data points (67.2%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 142”

-------------------------------------------------------------------
Data filtering:
4608 data points (26.23%) excluded by growing season filter
6701 additional data points (38.14%) excluded by precipitation filter (9555
 data points = 54.39 % in total)
11309 data points (64.37%) excluded in total
6259 valid data points (35.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 7170 data points (40.81%) set to NA
LE: 10825 data points (61.62%) set to NA
NEE: 11805 data points (67.2%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 142”

-------------------------------------------------------------------
Data filtering:
4608 data points (26.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4608 data points (26.23%) excluded in total
12960 valid data points (73.77%) remaining.

New sEddyProc class for site 'AT-Zoe'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AT-Zoe-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[7/329] Processing: AU-APL

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: AU-APL | Years: 2017, 2018, 2019, 2020, 2021, 2022
Quality control:
TA: 5936 data points (33.88%) set to NA
H: 5982 data points (34.14%) set to NA
LE: 6069 data points (34.64%) set to NA
NEE: 6612 data points (37.74%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 92”

-------------------------------------------------------------------
Data filtering:
7488 data points (42.74%) excluded by growing season filter
4994 additional data points (28.5%) excluded by precipitation filter (9394
 data points = 53.62 % in total)
12482 data points (71.24%) excluded in total
5038 valid data points (28.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 5936 data points (33.88%) set to NA
H: 5982 data points (34.14%) set to NA
LE: 6069 data points (34.64%) set to NA
NEE: 6612 data points (37.74%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 92”

-------------------------------------------------------------------
Data filtering:
7488 data points (42.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7488 data points (42.74%) excluded in total
10032 valid data points (57.26%) remaining.

New sEddyProc class for site 'AU-APL'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 36.29.

Regression of reference temperature R_ref for 20 periods.

Quality control:
TA: 1730 data points (9.87%) set to NA
H: 1812 data points (10.34%) set to NA
LE: 1911 data points (10.91%) set to NA
NEE: 3131 data points (17.87%) set to NA
-------------------------------------------------------------------
Data filtering:
7056 data points (40.27%) excluded by growing season filter
4606 additional data points (26.29%) excluded by precipitation filter (8602
 data points = 49.1 % in total)
11662 data points (66.56%) excluded in total
5858 valid data points (33.44%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 1730 data points (9.87%) set to NA
H: 1812 data points (10.34%) set to NA
LE: 1911 data points (10.91%) set to NA
NEE: 3131 data points (17.87%) set to NA
-------------------------------------------------------------------
Data filtering:
7056 data points (40.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7056 data points (40.27%) excluded in total
10464 valid data points (59.73%) remaining.

New sEddyProc class for site 'AU-APL'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 163.23.

Regression of reference temperature R_ref for 23 periods.

Quality control:
TA: 992 data points (5.66%) set to NA
H: 1099 data points (6.27%) set to NA
LE: 1213 data points (6.92%) set to NA
NEE: 2816 data points (16.07%) set to NA
-------------------------------------------------------------------
Data filtering:
6240 data points (35.62%) excluded by growing season filter
5332 additional data points (30.43%) excluded by precipitation filter (8890
 data points = 50.74 % in total)
11572 data points (66.05%) excluded in total
5948 valid data points (33.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 992 data points (5.66%) set to NA
H: 1099 data points (6.27%) set to NA
LE: 1213 data points (6.92%) set to NA
NEE: 2816 data points (16.07%) set to NA
-------------------------------------------------------------------
Data filtering:
6240 data points (35.62%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6240 data points (35.62%) excluded in total
11280 valid data points (64.38%) remaining.

New sEddyProc class for site 'AU-APL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 8 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-APL-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1645 data points (9.36%) set to NA
H: 1829 data points (10.41%) set to NA
LE: 1905 data points (10.84%) set to NA
NEE: 3348 data points (19.06%) set to NA
-------------------------------------------------------------------
Data filtering:
7008 data points (39.89%) excluded by growing season filter
5822 additional data points (33.14%) excluded by precipitation filter (9674
 data points = 55.07 % in total)
12830 data points (73.03%) excluded in total
4738 valid data points (26.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 1645 data points (9.36%) set to NA
H: 1829 data points (10.41%) set to NA
LE: 1905 data points (10.84%) set to NA
NEE: 3348 data points (19.06%) set to NA
-------------------------------------------------------------------
Data filtering:
7008 data points (39.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7008 data points (39.89%) excluded in total
10560 valid data points (60.11%) remaining.

New sEddyProc class for site 'AU-APL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 13 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-APL-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1333 data points (7.61%) set to NA
H: 1559 data points (8.9%) set to NA
LE: 1597 data points (9.12%) set to NA
NEE: 2364 data points (13.49%) set to NA
-------------------------------------------------------------------
Data filtering:
7056 data points (40.27%) excluded by growing season filter
5536 additional data points (31.6%) excluded by precipitation filter (10366
 data points = 59.17 % in total)
12592 data points (71.87%) excluded in total
4928 valid data points (28.13%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 1333 data points (7.61%) set to NA
H: 1559 data points (8.9%) set to NA
LE: 1597 data points (9.12%) set to NA
NEE: 2364 data points (13.49%) set to NA
-------------------------------------------------------------------
Data filtering:
7056 data points (40.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7056 data points (40.27%) excluded in total
10464 valid data points (59.73%) remaining.

New sEddyProc class for site 'AU-APL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-APL-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 9983 data points (56.98%) set to NA
H: 10039 data points (57.3%) set to NA
LE: 10098 data points (57.64%) set to NA
NEE: 10374 data points (59.21%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 184”

-------------------------------------------------------------------
Data filtering:
11472 data points (65.48%) excluded by growing season filter
3532 additional data points (20.16%) excluded by precipitation filter (11886
 data points = 67.84 % in total)
15004 data points (85.64%) excluded in total
2516 valid data points (14.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 9983 data points (56.98%) set to NA
H: 10039 data points (57.3%) set to NA
LE: 10098 data points (57.64%) set to NA
NEE: 10374 data points (59.21%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 184”

-------------------------------------------------------------------
Data filtering:
11472 data points (65.48%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11472 data points (65.48%) excluded in total
6048 valid data points (34.52%) remaining.

New sEddyProc class for site 'AU-APL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 12 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-APL-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[8/329] Processing: AU-ASM

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: AU-ASM | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 0 data points (0%) set to NA
H: 12 data points (0.07%) set to NA
LE: 13 data points (0.07%) set to NA
NEE: 321 data points (1.83%) set to NA
-------------------------------------------------------------------
Data filtering:
8256 data points (47.12%) excluded by growing season filter
1891 additional data points (10.79%) excluded by precipitation filter (2699
 data points = 15.41 % in total)
10147 data points (57.92%) excluded in total
7373 valid data points (42.08%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 12 data points (0.07%) set to NA
LE: 13 data points (0.07%) set to NA
NEE: 321 data points (1.83%) set to NA
-------------------------------------------------------------------
Data filtering:
8256 data points (47.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8256 data points (47.12%) excluded in total
9264 valid data points (52.88%) remaining.

  REddyProc error for AU-ASM-2017: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 626 data points (3.57%) set to NA
H: 636 data points (3.63%) set to NA
LE: 644 data points (3.68%) set to NA
NEE: 1050 data points (5.99%) set to NA
-------------------------------------------------------------------
Data filtering:
4608 data points (26.3%) excluded by growing season filter
1180 additional data points (6.74%) excluded by precipitation filter (1677
 data points = 9.57 % in total)
5788 data points (33.04%) excluded in total
11732 valid data points (66.96%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 626 data points (3.57%) set to NA
H: 636 data points (3.63%) set to NA
LE: 644 data points (3.68%) set to NA
NEE: 1050 data points (5.99%) set to NA
-------------------------------------------------------------------
Data filtering:
4608 data points (26.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4608 data points (26.3%) excluded in total
12912 valid data points (73.7%) remaining.

  REddyProc error for AU-ASM-2018: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 11 data points (0.06%) set to NA
NEE: 238 data points (1.36%) set to NA
-------------------------------------------------------------------
Data filtering:
768 data points (4.38%) excluded by growing season filter
798 additional data points (4.55%) excluded by precipitation filter (798
 data points = 4.55 % in total)
1566 data points (8.94%) excluded in total
15954 valid data points (91.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 11 data points (0.06%) set to NA
NEE: 238 data points (1.36%) set to NA
-------------------------------------------------------------------
Data filtering:
768 data points (4.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
768 data points (4.38%) excluded in total
16752 valid data points (95.62%) remaining.

  REddyProc error for AU-ASM-2019: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 0 data points (0%) set to NA
H: 18 data points (0.1%) set to NA
LE: 24 data points (0.14%) set to NA
NEE: 227 data points (1.29%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.66%) excluded by growing season filter
1624 additional data points (9.24%) excluded by precipitation filter (2594
 data points = 14.77 % in total)
12280 data points (69.9%) excluded in total
5288 valid data points (30.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 18 data points (0.1%) set to NA
LE: 24 data points (0.14%) set to NA
NEE: 227 data points (1.29%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.66%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10656 data points (60.66%) excluded in total
6912 valid data points (39.34%) remaining.

  REddyProc error for AU-ASM-2020: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 42 data points (0.24%) set to NA
H: 10967 data points (62.6%) set to NA
LE: 10968 data points (62.6%) set to NA
NEE: 11036 data points (62.99%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2473 additional data points (14.12%) excluded by precipitation filter (2473
 data points = 14.12 % in total)
2473 data points (14.12%) excluded in total
15047 valid data points (85.88%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 42 data points (0.24%) set to NA
H: 10967 data points (62.6%) set to NA
LE: 10968 data points (62.6%) set to NA
NEE: 11036 data points (62.99%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

  REddyProc error for AU-ASM-2021: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 2195 data points (12.53%) set to NA
H: 7106 data points (40.56%) set to NA
LE: 7115 data points (40.61%) set to NA
NEE: 7176 data points (40.96%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 138”

-------------------------------------------------------------------
Data filtering:
7248 data points (41.37%) excluded by growing season filter
49 additional data points (0.28%) excluded by precipitation filter (1147
 data points = 6.55 % in total)
7297 data points (41.65%) excluded in total
10223 valid data points (58.35%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 2195 data points (12.53%) set to NA
H: 7106 data points (40.56%) set to NA
LE: 7115 data points (40.61%) set to NA
NEE: 7176 data points (40.96%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 138”

-------------------------------------------------------------------
Data filtering:
7248 data points (41.37%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7248 data points (41.37%) excluded in total
10272 valid data points (58.63%) remaining.

  REddyProc error for AU-ASM-2022: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 14329 data points (81.79%) set to NA
H: 14331 data points (81.8%) set to NA
LE: 14332 data points (81.8%) set to NA
NEE: 14381 data points (82.08%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1585 additional data points (9.05%) excluded by precipitation filter (1585
 data points = 9.05 % in total)
1585 data points (9.05%) excluded in total
15935 valid data points (90.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 14329 data points (81.79%) set to NA
H: 14331 data points (81.8%) set to NA
LE: 14332 data points (81.8%) set to NA
NEE: 14381 data points (82.08%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

  REddyProc error for AU-ASM-2023: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 11174 data points (63.6%) set to NA
H: 11181 data points (63.64%) set to NA
LE: 11183 data points (63.66%) set to NA
NEE: 11213 data points (63.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3372 additional data points (19.19%) excluded by precipitation filter (3372
 data points = 19.19 % in total)
3372 data points (19.19%) excluded in total
14196 valid data points (80.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 11174 data points (63.6%) set to NA
H: 11181 data points (63.64%) set to NA
LE: 11183 data points (63.66%) set to NA
NEE: 11213 data points (63.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

  REddyProc error for AU-ASM-2024: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 36 data points (0.21%) set to NA
H: 85 data points (0.49%) set to NA
LE: 96 data points (0.55%) set to NA
NEE: 489 data points (2.79%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1951 additional data points (11.14%) excluded by precipitation filter (1951
 data points = 11.14 % in total)
1951 data points (11.14%) excluded in total
15569 valid data points (88.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 36 data points (0.21%) set to NA
H: 85 data points (0.49%) set to NA
LE: 96 data points (0.55%) set to NA
NEE: 489 data points (2.79%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

  REddyProc error for AU-ASM-2025: Timezone must be an integer in interval -12 to 12

[9/329] Processing: AU-Col

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: AU-Col | Years: 2017, 2018, 2019
Quality control:
TA: 10447 data points (59.63%) set to NA
H: 10466 data points (59.74%) set to NA
LE: 10474 data points (59.78%) set to NA
NEE: 10695 data points (61.04%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7326 additional data points (41.82%) excluded by precipitation filter (7326
 data points = 41.82 % in total)
7326 data points (41.82%) excluded in total
10194 valid data points (58.18%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 10447 data points (59.63%) set to NA
H: 10466 data points (59.74%) set to NA
LE: 10474 data points (59.78%) set to NA
NEE: 10695 data points (61.04%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'AU-Col'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 11 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-Col-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2 data points (0.01%) set to NA
H: 2546 data points (14.53%) set to NA
LE: 2566 data points (14.65%) set to NA
NEE: 3298 data points (18.82%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 27”

-------------------------------------------------------------------
Data filtering:
816 data points (4.66%) excluded by growing season filter
6860 additional data points (39.16%) excluded by precipitation filter (7392
 data points = 42.19 % in total)
7676 data points (43.81%) excluded in total
9844 valid data points (56.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 2 data points (0.01%) set to NA
H: 2546 data points (14.53%) set to NA
LE: 2566 data points (14.65%) set to NA
NEE: 3298 data points (18.82%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 27”

-------------------------------------------------------------------
Data filtering:
816 data points (4.66%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
816 data points (4.66%) excluded in total
16704 valid data points (95.34%) remaining.

New sEddyProc class for site 'AU-Col'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-Col-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2414 data points (13.78%) set to NA
H: 2422 data points (13.82%) set to NA
LE: 2437 data points (13.91%) set to NA
NEE: 3288 data points (18.77%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 40”

-------------------------------------------------------------------
Data filtering:
384 data points (2.19%) excluded by growing season filter
5254 additional data points (29.99%) excluded by precipitation filter (5326
 data points = 30.4 % in total)
5638 data points (32.18%) excluded in total
11882 valid data points (67.82%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 2414 data points (13.78%) set to NA
H: 2422 data points (13.82%) set to NA
LE: 2437 data points (13.91%) set to NA
NEE: 3288 data points (18.77%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 40”

-------------------------------------------------------------------
Data filtering:
384 data points (2.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
384 data points (2.19%) excluded in total
17136 valid data points (97.81%) remaining.

New sEddyProc class for site 'AU-Col'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-Col-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[10/329] Processing: AU-Cpr

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: AU-Cpr | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 0 data points (0%) set to NA
H: 78 data points (0.45%) set to NA
LE: 85 data points (0.49%) set to NA
NEE: 887 data points (5.06%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3513 additional data points (20.05%) excluded by precipitation filter (3513
 data points = 20.05 % in total)
3513 data points (20.05%) excluded in total
14007 valid data points (79.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 78 data points (0.45%) set to NA
LE: 85 data points (0.49%) set to NA
NEE: 887 data points (5.06%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

  REddyProc error for AU-Cpr-2017: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 0 data points (0%) set to NA
H: 76 data points (0.43%) set to NA
LE: 85 data points (0.49%) set to NA
NEE: 753 data points (4.3%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3369 additional data points (19.23%) excluded by precipitation filter (3369
 data points = 19.23 % in total)
3369 data points (19.23%) excluded in total
14151 valid data points (80.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 76 data points (0.43%) set to NA
LE: 85 data points (0.49%) set to NA
NEE: 753 data points (4.3%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

  REddyProc error for AU-Cpr-2018: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 0 data points (0%) set to NA
H: 70 data points (0.4%) set to NA
LE: 80 data points (0.46%) set to NA
NEE: 828 data points (4.73%) set to NA
-------------------------------------------------------------------
Data filtering:
1104 data points (6.3%) excluded by growing season filter
2509 additional data points (14.32%) excluded by precipitation filter (2571
 data points = 14.67 % in total)
3613 data points (20.62%) excluded in total
13907 valid data points (79.38%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 70 data points (0.4%) set to NA
LE: 80 data points (0.46%) set to NA
NEE: 828 data points (4.73%) set to NA
-------------------------------------------------------------------
Data filtering:
1104 data points (6.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1104 data points (6.3%) excluded in total
16416 valid data points (93.7%) remaining.

  REddyProc error for AU-Cpr-2019: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 561 data points (3.19%) set to NA
H: 832 data points (4.74%) set to NA
LE: 839 data points (4.78%) set to NA
NEE: 1637 data points (9.32%) set to NA
-------------------------------------------------------------------
Data filtering:
7248 data points (41.26%) excluded by growing season filter
2180 additional data points (12.41%) excluded by precipitation filter (3574
 data points = 20.34 % in total)
9428 data points (53.67%) excluded in total
8140 valid data points (46.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 561 data points (3.19%) set to NA
H: 832 data points (4.74%) set to NA
LE: 839 data points (4.78%) set to NA
NEE: 1637 data points (9.32%) set to NA
-------------------------------------------------------------------
Data filtering:
7248 data points (41.26%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7248 data points (41.26%) excluded in total
10320 valid data points (58.74%) remaining.

  REddyProc error for AU-Cpr-2020: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 41 data points (0.23%) set to NA
H: 203 data points (1.16%) set to NA
LE: 218 data points (1.24%) set to NA
NEE: 975 data points (5.57%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3948 additional data points (22.53%) excluded by precipitation filter (3948
 data points = 22.53 % in total)
3948 data points (22.53%) excluded in total
13572 valid data points (77.47%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 41 data points (0.23%) set to NA
H: 203 data points (1.16%) set to NA
LE: 218 data points (1.24%) set to NA
NEE: 975 data points (5.57%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

  REddyProc error for AU-Cpr-2021: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 667 data points (3.81%) set to NA
H: 992 data points (5.66%) set to NA
LE: 1006 data points (5.74%) set to NA
NEE: 4362 data points (24.9%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 34”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3959 additional data points (22.6%) excluded by precipitation filter (3959
 data points = 22.6 % in total)
3959 data points (22.6%) excluded in total
13561 valid data points (77.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 667 data points (3.81%) set to NA
H: 992 data points (5.66%) set to NA
LE: 1006 data points (5.74%) set to NA
NEE: 4362 data points (24.9%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 34”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

  REddyProc error for AU-Cpr-2022: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 10 data points (0.06%) set to NA
H: 2391 data points (13.65%) set to NA
LE: 2406 data points (13.73%) set to NA
NEE: 3279 data points (18.72%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3112 additional data points (17.76%) excluded by precipitation filter (3112
 data points = 17.76 % in total)
3112 data points (17.76%) excluded in total
14408 valid data points (82.24%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 10 data points (0.06%) set to NA
H: 2391 data points (13.65%) set to NA
LE: 2406 data points (13.73%) set to NA
NEE: 3279 data points (18.72%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

  REddyProc error for AU-Cpr-2023: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 55 data points (0.31%) set to NA
H: 191 data points (1.09%) set to NA
LE: 202 data points (1.15%) set to NA
NEE: 1186 data points (6.75%) set to NA
-------------------------------------------------------------------
Data filtering:
1680 data points (9.56%) excluded by growing season filter
2641 additional data points (15.03%) excluded by precipitation filter (3123
 data points = 17.78 % in total)
4321 data points (24.6%) excluded in total
13247 valid data points (75.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 55 data points (0.31%) set to NA
H: 191 data points (1.09%) set to NA
LE: 202 data points (1.15%) set to NA
NEE: 1186 data points (6.75%) set to NA
-------------------------------------------------------------------
Data filtering:
1680 data points (9.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1680 data points (9.56%) excluded in total
15888 valid data points (90.44%) remaining.

  REddyProc error for AU-Cpr-2024: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 0 data points (0%) set to NA
H: 77 data points (0.44%) set to NA
LE: 79 data points (0.45%) set to NA
NEE: 1104 data points (6.3%) set to NA
-------------------------------------------------------------------
Data filtering:
672 data points (3.84%) excluded by growing season filter
2094 additional data points (11.95%) excluded by precipitation filter (2410
 data points = 13.76 % in total)
2766 data points (15.79%) excluded in total
14754 valid data points (84.21%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 77 data points (0.44%) set to NA
LE: 79 data points (0.45%) set to NA
NEE: 1104 data points (6.3%) set to NA
-------------------------------------------------------------------
Data filtering:
672 data points (3.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
672 data points (3.84%) excluded in total
16848 valid data points (96.16%) remaining.

  REddyProc error for AU-Cpr-2025: Timezone must be an integer in interval -12 to 12

[11/329] Processing: AU-Fle

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: AU-Fle | Years: 2022, 2023, 2024, 2025
Quality control:
TA: 1046 data points (5.97%) set to NA
H: 6631 data points (37.85%) set to NA
LE: 6631 data points (37.85%) set to NA
NEE: 6943 data points (39.63%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 60”

-------------------------------------------------------------------
Data filtering:
672 data points (3.84%) excluded by growing season filter
3450 additional data points (19.69%) excluded by precipitation filter (3657
 data points = 20.87 % in total)
4122 data points (23.53%) excluded in total
13398 valid data points (76.47%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 1046 data points (5.97%) set to NA
H: 6631 data points (37.85%) set to NA
LE: 6631 data points (37.85%) set to NA
NEE: 6943 data points (39.63%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 60”

-------------------------------------------------------------------
Data filtering:
672 data points (3.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
672 data points (3.84%) excluded in total
16848 valid data points (96.16%) remaining.

New sEddyProc class for site 'AU-Fle'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-Fle-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 9 data points (0.05%) set to NA
H: 37 data points (0.21%) set to NA
LE: 37 data points (0.21%) set to NA
NEE: 472 data points (2.69%) set to NA
-------------------------------------------------------------------
Data filtering:
6336 data points (36.16%) excluded by growing season filter
3069 additional data points (17.52%) excluded by precipitation filter (3634
 data points = 20.74 % in total)
9405 data points (53.68%) excluded in total
8115 valid data points (46.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 9 data points (0.05%) set to NA
H: 37 data points (0.21%) set to NA
LE: 37 data points (0.21%) set to NA
NEE: 472 data points (2.69%) set to NA
-------------------------------------------------------------------
Data filtering:
6336 data points (36.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6336 data points (36.16%) excluded in total
11184 valid data points (63.84%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -54, -64, -51, -51 ...”
New sEddyProc class for site 'AU-Fle'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -54, -64, -51, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-Fle-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 31 data points (0.18%) set to NA
LE: 34 data points (0.19%) set to NA
NEE: 509 data points (2.9%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4335 additional data points (24.68%) excluded by precipitation filter (4335
 data points = 24.68 % in total)
4335 data points (24.68%) excluded in total
13233 valid data points (75.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 31 data points (0.18%) set to NA
LE: 34 data points (0.19%) set to NA
NEE: 509 data points (2.9%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -70, -50, -53 ...”
New sEddyProc class for site 'AU-Fle'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -70, -50, -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-Fle-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 36 data points (0.21%) set to NA
H: 118 data points (0.67%) set to NA
LE: 118 data points (0.67%) set to NA
NEE: 589 data points (3.36%) set to NA
-------------------------------------------------------------------
Data filtering:
1440 data points (8.22%) excluded by growing season filter
3883 additional data points (22.16%) excluded by precipitation filter (4381
 data points = 25.01 % in total)
5323 data points (30.38%) excluded in total
12197 valid data points (69.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 36 data points (0.21%) set to NA
H: 118 data points (0.67%) set to NA
LE: 118 data points (0.67%) set to NA
NEE: 589 data points (3.36%) set to NA
-------------------------------------------------------------------
Data filtering:
1440 data points (8.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1440 data points (8.22%) excluded in total
16080 valid data points (91.78%) remaining.

New sEddyProc class for site 'AU-Fle'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-Fle-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[12/329] Processing: AU-How

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: AU-How | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 0 data points (0%) set to NA
H: 10 data points (0.06%) set to NA
LE: 10 data points (0.06%) set to NA
NEE: 277 data points (1.58%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5493 additional data points (31.35%) excluded by precipitation filter (5493
 data points = 31.35 % in total)
5493 data points (31.35%) excluded in total
12027 valid data points (68.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 10 data points (0.06%) set to NA
LE: 10 data points (0.06%) set to NA
NEE: 277 data points (1.58%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -65, -51 ...”
  REddyProc error for AU-How-2017: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 931 data points (5.31%) set to NA
H: 949 data points (5.42%) set to NA
LE: 953 data points (5.44%) set to NA
NEE: 1252 data points (7.15%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6292 additional data points (35.91%) excluded by precipitation filter (6292
 data points = 35.91 % in total)
6292 data points (35.91%) excluded in total
11228 valid data points (64.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 931 data points (5.31%) set to NA
H: 949 data points (5.42%) set to NA
LE: 953 data points (5.44%) set to NA
NEE: 1252 data points (7.15%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

  REddyProc error for AU-How-2018: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 23 data points (0.13%) set to NA
H: 39 data points (0.22%) set to NA
LE: 43 data points (0.25%) set to NA
NEE: 571 data points (3.26%) set to NA
-------------------------------------------------------------------
Data filtering:
5088 data points (29.04%) excluded by growing season filter
4375 additional data points (24.97%) excluded by precipitation filter (4573
 data points = 26.1 % in total)
9463 data points (54.01%) excluded in total
8057 valid data points (45.99%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 23 data points (0.13%) set to NA
H: 39 data points (0.22%) set to NA
LE: 43 data points (0.25%) set to NA
NEE: 571 data points (3.26%) set to NA
-------------------------------------------------------------------
Data filtering:
5088 data points (29.04%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5088 data points (29.04%) excluded in total
12432 valid data points (70.96%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -52, -53, -60 ...”
  REddyProc error for AU-How-2019: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 1627 data points (9.26%) set to NA
H: 1650 data points (9.39%) set to NA
LE: 1651 data points (9.4%) set to NA
NEE: 1912 data points (10.88%) set to NA
-------------------------------------------------------------------
Data filtering:
1296 data points (7.38%) excluded by growing season filter
6475 additional data points (36.86%) excluded by precipitation filter (6475
 data points = 36.86 % in total)
7771 data points (44.23%) excluded in total
9797 valid data points (55.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 1627 data points (9.26%) set to NA
H: 1650 data points (9.39%) set to NA
LE: 1651 data points (9.4%) set to NA
NEE: 1912 data points (10.88%) set to NA
-------------------------------------------------------------------
Data filtering:
1296 data points (7.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1296 data points (7.38%) excluded in total
16272 valid data points (92.62%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -77, -51 ...”
  REddyProc error for AU-How-2020: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 43 data points (0.25%) set to NA
H: 1557 data points (8.89%) set to NA
LE: 1562 data points (8.92%) set to NA
NEE: 1939 data points (11.07%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6550 additional data points (37.39%) excluded by precipitation filter (6550
 data points = 37.39 % in total)
6550 data points (37.39%) excluded in total
10970 valid data points (62.61%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 43 data points (0.25%) set to NA
H: 1557 data points (8.89%) set to NA
LE: 1562 data points (8.92%) set to NA
NEE: 1939 data points (11.07%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -59 ...”
  REddyProc error for AU-How-2021: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 293 data points (1.67%) set to NA
H: 310 data points (1.77%) set to NA
LE: 313 data points (1.79%) set to NA
NEE: 574 data points (3.28%) set to NA
-------------------------------------------------------------------
Data filtering:
3120 data points (17.81%) excluded by growing season filter
6587 additional data points (37.6%) excluded by precipitation filter (6738
 data points = 38.46 % in total)
9707 data points (55.41%) excluded in total
7813 valid data points (44.59%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 293 data points (1.67%) set to NA
H: 310 data points (1.77%) set to NA
LE: 313 data points (1.79%) set to NA
NEE: 574 data points (3.28%) set to NA
-------------------------------------------------------------------
Data filtering:
3120 data points (17.81%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3120 data points (17.81%) excluded in total
14400 valid data points (82.19%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -58, -53 ...”
  REddyProc error for AU-How-2022: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 0 data points (0%) set to NA
H: 21 data points (0.12%) set to NA
LE: 23 data points (0.13%) set to NA
NEE: 436 data points (2.49%) set to NA
-------------------------------------------------------------------
Data filtering:
1536 data points (8.77%) excluded by growing season filter
5263 additional data points (30.04%) excluded by precipitation filter (5263
 data points = 30.04 % in total)
6799 data points (38.81%) excluded in total
10721 valid data points (61.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 21 data points (0.12%) set to NA
LE: 23 data points (0.13%) set to NA
NEE: 436 data points (2.49%) set to NA
-------------------------------------------------------------------
Data filtering:
1536 data points (8.77%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1536 data points (8.77%) excluded in total
15984 valid data points (91.23%) remaining.

  REddyProc error for AU-How-2023: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 0 data points (0%) set to NA
H: 35 data points (0.2%) set to NA
LE: 35 data points (0.2%) set to NA
NEE: 625 data points (3.56%) set to NA
-------------------------------------------------------------------
Data filtering:
2928 data points (16.67%) excluded by growing season filter
6270 additional data points (35.69%) excluded by precipitation filter (6367
 data points = 36.24 % in total)
9198 data points (52.36%) excluded in total
8370 valid data points (47.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 35 data points (0.2%) set to NA
LE: 35 data points (0.2%) set to NA
NEE: 625 data points (3.56%) set to NA
-------------------------------------------------------------------
Data filtering:
2928 data points (16.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2928 data points (16.67%) excluded in total
14640 valid data points (83.33%) remaining.

  REddyProc error for AU-How-2024: Timezone must be an integer in interval -12 to 12

Quality control:
TA: 5469 data points (31.22%) set to NA
H: 5486 data points (31.31%) set to NA
LE: 5482 data points (31.29%) set to NA
NEE: 5987 data points (34.17%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 104”

-------------------------------------------------------------------
Data filtering:
384 data points (2.19%) excluded by growing season filter
8598 additional data points (49.08%) excluded by precipitation filter (8598
 data points = 49.08 % in total)
8982 data points (51.27%) excluded in total
8538 valid data points (48.73%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 5469 data points (31.22%) set to NA
H: 5486 data points (31.31%) set to NA
LE: 5482 data points (31.29%) set to NA
NEE: 5987 data points (34.17%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 104”

-------------------------------------------------------------------
Data filtering:
384 data points (2.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
384 data points (2.19%) excluded in total
17136 valid data points (97.81%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
  REddyProc error for AU-How-2025: Timezone must be an integer in interval -12 to 12

[13/329] Processing: AU-Rob

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: AU-Rob | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 0 data points (0%) set to NA
H: 21 data points (0.12%) set to NA
LE: 20 data points (0.11%) set to NA
NEE: 152 data points (0.87%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12282 additional data points (70.1%) excluded by precipitation filter (12282
 data points = 70.1 % in total)
12282 data points (70.1%) excluded in total
5238 valid data points (29.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 21 data points (0.12%) set to NA
LE: 20 data points (0.11%) set to NA
NEE: 152 data points (0.87%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'AU-Rob'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-Rob-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2 data points (0.01%) set to NA
H: 25 data points (0.14%) set to NA
LE: 23 data points (0.13%) set to NA
NEE: 400 data points (2.28%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12022 additional data points (68.62%) excluded by precipitation filter (12022
 data points = 68.62 % in total)
12022 data points (68.62%) excluded in total
5498 valid data points (31.38%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 2 data points (0.01%) set to NA
H: 25 data points (0.14%) set to NA
LE: 23 data points (0.13%) set to NA
NEE: 400 data points (2.28%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
New sEddyProc class for site 'AU-Rob'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-Rob-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 351 data points (2%) set to NA
H: 393 data points (2.24%) set to NA
LE: 394 data points (2.25%) set to NA
NEE: 637 data points (3.64%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12006 additional data points (68.53%) excluded by precipitation filter (12006
 data points = 68.53 % in total)
12006 data points (68.53%) excluded in total
5514 valid data points (31.47%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 351 data points (2%) set to NA
H: 393 data points (2.24%) set to NA
LE: 394 data points (2.25%) set to NA
NEE: 637 data points (3.64%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -67, -55 ...”
New sEddyProc class for site 'AU-Rob'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -67, -55 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-Rob-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 72 data points (0.41%) set to NA
LE: 73 data points (0.42%) set to NA
NEE: 265 data points (1.51%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12596 additional data points (71.7%) excluded by precipitation filter (12596
 data points = 71.7 % in total)
12596 data points (71.7%) excluded in total
4972 valid data points (28.3%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 72 data points (0.41%) set to NA
LE: 73 data points (0.42%) set to NA
NEE: 265 data points (1.51%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -57, -50, -52 ...”
New sEddyProc class for site 'AU-Rob'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -57, -50, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-Rob-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1188 data points (6.78%) set to NA
LE: 1179 data points (6.73%) set to NA
NEE: 1475 data points (8.42%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8999 additional data points (51.36%) excluded by precipitation filter (8999
 data points = 51.36 % in total)
8999 data points (51.36%) excluded in total
8521 valid data points (48.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1188 data points (6.78%) set to NA
LE: 1179 data points (6.73%) set to NA
NEE: 1475 data points (8.42%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 20 cases! Invalid values with 'NEE < -50': -56, -53, -52, -51, -57, -50, -69, -51, -52, -65, -56, -54, -67, -67, -51, -51, -55, -52, -56, -61 ...”
New sEddyProc class for site 'AU-Rob'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 20 cases! Invalid values with 'NEE < -50': -56, -53, -52, -51, -57, -50, -69, -51, -52, -65, -56, -54, -67, -67, -51, -51, -55, -52, -56, -61 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-Rob-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2382 data points (13.6%) set to NA
LE: 2384 data points (13.61%) set to NA
NEE: 2450 data points (13.98%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
11702 additional data points (66.79%) excluded by precipitation filter (11702
 data points = 66.79 % in total)
11702 data points (66.79%) excluded in total
5818 valid data points (33.21%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2382 data points (13.6%) set to NA
LE: 2384 data points (13.61%) set to NA
NEE: 2450 data points (13.98%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 12 cases! Invalid values with 'NEE < -50': -60, -79, -61, -54, -56, -58, -52, -67, -58, -64, -61, -66 ...”
New sEddyProc class for site 'AU-Rob'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 12 cases! Invalid values with 'NEE < -50': -60, -79, -61, -54, -56, -58, -52, -67, -58, -64, -61, -66 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-Rob-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 23 data points (0.13%) set to NA
H: 56 data points (0.32%) set to NA
LE: 53 data points (0.3%) set to NA
NEE: 141 data points (0.8%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12842 additional data points (73.3%) excluded by precipitation filter (12842
 data points = 73.3 % in total)
12842 data points (73.3%) excluded in total
4678 valid data points (26.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 23 data points (0.13%) set to NA
H: 56 data points (0.32%) set to NA
LE: 53 data points (0.3%) set to NA
NEE: 141 data points (0.8%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 51 cases! Invalid values with 'NEE < -50': -77, -71, -57, -55, -63, -50, -61, -57, -72, -63, -63, -53, -61, -61, -53, -52, -52, -62, -58, -52, -51, -54, -58, -54, -59, -52, -52, -58, -63, -58, -64, -59, -61, -60, -56, -56, -56, -62, -50, -73, -63, -51, -56, -56, -56, -53, -56, -56, -51, -64 ...”
New sEddyProc class for site 'AU-Rob'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 51 cases! Invalid values with 'NEE < -50': -77, -71, -57, -55, -63, -50, -61, -57, -72, -63, -63, -53, -61, -61, -53, -52, -52, -62, -58, -52, -51, -54, -58, -54, -59, -52, -52, -58, -63, -58, -64, -59, -61, -60, -56, -56, -56, -62, -50, -73, -63, -51, -56, -56, -56, -53, -56, -56, -51, -64 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-Rob-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 32 data points (0.18%) set to NA
H: 273 data points (1.55%) set to NA
LE: 271 data points (1.54%) set to NA
NEE: 350 data points (1.99%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12982 additional data points (73.9%) excluded by precipitation filter (12982
 data points = 73.9 % in total)
12982 data points (73.9%) excluded in total
4586 valid data points (26.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 32 data points (0.18%) set to NA
H: 273 data points (1.55%) set to NA
LE: 271 data points (1.54%) set to NA
NEE: 350 data points (1.99%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 44 cases! Invalid values with 'NEE < -50': -56, -62, -51, -58, -67, -55, -68, -63, -78, -67, -67, -50, -52, -65, -78, -51, -63, -57, -78, -72, -62, -56, -62, -65, -63, -52, -51, -71, -75, -70, -52, -57, -52, -66, -75, -53, -56, -69, -53, -51, -53, -54, -52, -73 ...”
New sEddyProc class for site 'AU-Rob'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 44 cases! Invalid values with 'NEE < -50': -56, -62, -51, -58, -67, -55, -68, -63, -78, -67, -67, -50, -52, -65, -78, -51, -63, -57, -78, -72, -62, -56, -62, -65, -63, -52, -51, -71, -75, -70, -52, -57, -52, -66, -75, -53, -56, -69, -53, -51, -53, -54, -52, -73 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-Rob-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1650 data points (9.42%) set to NA
H: 3544 data points (20.23%) set to NA
LE: 3544 data points (20.23%) set to NA
NEE: 3604 data points (20.57%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7893 additional data points (45.05%) excluded by precipitation filter (7893
 data points = 45.05 % in total)
7893 data points (45.05%) excluded in total
9627 valid data points (54.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 1650 data points (9.42%) set to NA
H: 3544 data points (20.23%) set to NA
LE: 3544 data points (20.23%) set to NA
NEE: 3604 data points (20.57%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 37 cases! Invalid values with 'NEE < -50': -68, -53, -55, -55, -68, -67, -56, -76, -66, -58, -58, -52, -68, -71, -63, -67, -61, -51, -52, -69, -57, -55, -58, -62, -55, -51, -52, -65, -55, -75, -51, -53, -51, -57, -53, -68, -51 ...”
New sEddyProc class for site 'AU-Rob'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 37 cases! Invalid values with 'NEE < -50': -68, -53, -55, -55, -68, -67, -56, -76, -66, -58, -58, -52, -68, -71, -63, -67, -61, -51, -52, -69, -57, -55, -58, -62, -55, -51, -52, -65, -55, -75, -51, -53, -51, -57, -53, -68, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for AU-Rob-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[14/329] Processing: BE-Bra

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: BE-Bra | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 1375 data points (7.85%) set to NA
LE: 1373 data points (7.84%) set to NA
NEE: 1513 data points (8.64%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.4%) excluded by growing season filter
4415 additional data points (25.2%) excluded by precipitation filter (9479
 data points = 54.1 % in total)
12719 data points (72.6%) excluded in total
4801 valid data points (27.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1375 data points (7.85%) set to NA
LE: 1373 data points (7.84%) set to NA
NEE: 1513 data points (8.64%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.4%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8304 data points (47.4%) excluded in total
9216 valid data points (52.6%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 29 cases! Invalid values with 'NEE < -50': -62, -50, -60, -56, -80, -58, -69, -54, -73, -57, -72, -73, -69, -69, -65, -72, -80, -53, -79, -55, -76, -66, -57, -53, -63, -71, -61, -61, -63 ...”
New sEddyProc class for site 'BE-Bra'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 29 cases! Invalid values with 'NEE < -50': -62, -50, -60, -56, -80, -58, -69, -54, -73, -57, -72, -73, -69, -69, -65, -72, -80, -53, -79, -55, -76, -66, -57, -53, -63, -71, -61, -61, -63 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Bra-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3 data points (0.02%) set to NA
H: 1548 data points (8.84%) set to NA
LE: 1323 data points (7.55%) set to NA
NEE: 1693 data points (9.66%) set to NA
-------------------------------------------------------------------
Data filtering:
8640 data points (49.32%) excluded by growing season filter
2468 additional data points (14.09%) excluded by precipitation filter (7345
 data points = 41.92 % in total)
11108 data points (63.4%) excluded in total
6412 valid data points (36.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3 data points (0.02%) set to NA
H: 1548 data points (8.84%) set to NA
LE: 1323 data points (7.55%) set to NA
NEE: 1693 data points (9.66%) set to NA
-------------------------------------------------------------------
Data filtering:
8640 data points (49.32%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8640 data points (49.32%) excluded in total
8880 valid data points (50.68%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 95 cases! Invalid values with 'NEE < -50': -78, -61, -54, -50, -64, -53, -55, -59, -59, -66, -59, -67, -67, -61, -63, -62, -65, -57, -51, -66, -74, -67, -54, -65, -62, -56, -78, -67, -73, -65, -63, -65, -74, -57, -65, -64, -65, -53, -55, -59, -64, -52, -64, -66, -67, -59, -56, -51, -66, -70 ...”
New sEddyProc class for site 'BE-Bra'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 95 cases! Invalid values with 'NEE < -50': -78, -61, -54, -50, -64, -53, -55, -59, -59, -66, -59, -67, -67, -61, -63, -62, -65, -57, -51, -66, -74, -67, -54, -65, -62, -56, -78, -67, -73, -65, -63, -65, -74, -57, -65, -64, -65, -53, -55, -59, -64, -52, -64, -66, -67, -59, -56, -51, -66, -70 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Bra-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1314 data points (7.5%) set to NA
LE: 1348 data points (7.69%) set to NA
NEE: 1498 data points (8.55%) set to NA
-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
3604 additional data points (20.57%) excluded by precipitation filter (9087
 data points = 51.87 % in total)
12724 data points (72.63%) excluded in total
4796 valid data points (27.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1314 data points (7.5%) set to NA
LE: 1348 data points (7.69%) set to NA
NEE: 1498 data points (8.55%) set to NA
-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9120 data points (52.05%) excluded in total
8400 valid data points (47.95%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -63 ...”
New sEddyProc class for site 'BE-Bra'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -63 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Bra-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 174 data points (0.99%) set to NA
H: 1395 data points (7.94%) set to NA
LE: 1390 data points (7.91%) set to NA
NEE: 1585 data points (9.02%) set to NA
-------------------------------------------------------------------
Data filtering:
8448 data points (48.09%) excluded by growing season filter
3636 additional data points (20.7%) excluded by precipitation filter (8615
 data points = 49.04 % in total)
12084 data points (68.78%) excluded in total
5484 valid data points (31.22%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 174 data points (0.99%) set to NA
H: 1395 data points (7.94%) set to NA
LE: 1390 data points (7.91%) set to NA
NEE: 1585 data points (9.02%) set to NA
-------------------------------------------------------------------
Data filtering:
8448 data points (48.09%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8448 data points (48.09%) excluded in total
9120 valid data points (51.91%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -56 ...”
New sEddyProc class for site 'BE-Bra'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Bra-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 42 data points (0.24%) set to NA
H: 29 data points (0.17%) set to NA
LE: 28 data points (0.16%) set to NA
NEE: 90 data points (0.51%) set to NA
-------------------------------------------------------------------
Data filtering:
8496 data points (48.49%) excluded by growing season filter
4199 additional data points (23.97%) excluded by precipitation filter (9392
 data points = 53.61 % in total)
12695 data points (72.46%) excluded in total
4825 valid data points (27.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 42 data points (0.24%) set to NA
H: 29 data points (0.17%) set to NA
LE: 28 data points (0.16%) set to NA
NEE: 90 data points (0.51%) set to NA
-------------------------------------------------------------------
Data filtering:
8496 data points (48.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8496 data points (48.49%) excluded in total
9024 valid data points (51.51%) remaining.

New sEddyProc class for site 'BE-Bra'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Bra-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1369 data points (7.81%) set to NA
LE: 1373 data points (7.84%) set to NA
NEE: 1575 data points (8.99%) set to NA
-------------------------------------------------------------------
Data filtering:
7392 data points (42.19%) excluded by growing season filter
3211 additional data points (18.33%) excluded by precipitation filter (7381
 data points = 42.13 % in total)
10603 data points (60.52%) excluded in total
6917 valid data points (39.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1369 data points (7.81%) set to NA
LE: 1373 data points (7.84%) set to NA
NEE: 1575 data points (8.99%) set to NA
-------------------------------------------------------------------
Data filtering:
7392 data points (42.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7392 data points (42.19%) excluded in total
10128 valid data points (57.81%) remaining.

New sEddyProc class for site 'BE-Bra'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Bra-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 16 data points (0.09%) set to NA
H: 4 data points (0.02%) set to NA
LE: 16 data points (0.09%) set to NA
NEE: 46 data points (0.26%) set to NA
-------------------------------------------------------------------
Data filtering:
8544 data points (48.77%) excluded by growing season filter
3713 additional data points (21.19%) excluded by precipitation filter (9542
 data points = 54.46 % in total)
12257 data points (69.96%) excluded in total
5263 valid data points (30.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 16 data points (0.09%) set to NA
H: 4 data points (0.02%) set to NA
LE: 16 data points (0.09%) set to NA
NEE: 46 data points (0.26%) set to NA
-------------------------------------------------------------------
Data filtering:
8544 data points (48.77%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8544 data points (48.77%) excluded in total
8976 valid data points (51.23%) remaining.

New sEddyProc class for site 'BE-Bra'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Bra-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 178 data points (1.01%) set to NA
H: 1161 data points (6.61%) set to NA
LE: 1157 data points (6.59%) set to NA
NEE: 1194 data points (6.8%) set to NA
-------------------------------------------------------------------
Data filtering:
8544 data points (48.63%) excluded by growing season filter
4902 additional data points (27.9%) excluded by precipitation filter (9765
 data points = 55.58 % in total)
13446 data points (76.54%) excluded in total
4122 valid data points (23.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 178 data points (1.01%) set to NA
H: 1161 data points (6.61%) set to NA
LE: 1157 data points (6.59%) set to NA
NEE: 1194 data points (6.8%) set to NA
-------------------------------------------------------------------
Data filtering:
8544 data points (48.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8544 data points (48.63%) excluded in total
9024 valid data points (51.37%) remaining.

New sEddyProc class for site 'BE-Bra'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Bra-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[15/329] Processing: BE-Lcr

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: BE-Lcr | Years: 2019, 2020, 2021, 2022
Quality control:
TA: 793 data points (4.53%) set to NA
H: 1960 data points (11.19%) set to NA
LE: 546 data points (3.12%) set to NA
NEE: 2877 data points (16.42%) set to NA
-------------------------------------------------------------------
Data filtering:
10176 data points (58.08%) excluded by growing season filter
3224 additional data points (18.4%) excluded by precipitation filter (8464
 data points = 48.31 % in total)
13400 data points (76.48%) excluded in total
4120 valid data points (23.52%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 793 data points (4.53%) set to NA
H: 1960 data points (11.19%) set to NA
LE: 546 data points (3.12%) set to NA
NEE: 2877 data points (16.42%) set to NA
-------------------------------------------------------------------
Data filtering:
10176 data points (58.08%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10176 data points (58.08%) excluded in total
7344 valid data points (41.92%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
New sEddyProc class for site 'BE-Lcr'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 87.17.

Regression of reference temperature R_ref for 13 periods.

Quality control:
TA: 301 data points (1.71%) set to NA
H: 15 data points (0.09%) set to NA
LE: 23 data points (0.13%) set to NA
NEE: 1257 data points (7.16%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.27%) excluded by growing season filter
3448 additional data points (19.63%) excluded by precipitation filter (7876
 data points = 44.83 % in total)
11752 data points (66.89%) excluded in total
5816 valid data points (33.11%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 301 data points (1.71%) set to NA
H: 15 data points (0.09%) set to NA
LE: 23 data points (0.13%) set to NA
NEE: 1257 data points (7.16%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8304 data points (47.27%) excluded in total
9264 valid data points (52.73%) remaining.

New sEddyProc class for site 'BE-Lcr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Lcr-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 198 data points (1.13%) set to NA
H: 114 data points (0.65%) set to NA
LE: 126 data points (0.72%) set to NA
NEE: 567 data points (3.24%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.53%) excluded by growing season filter
3430 additional data points (19.58%) excluded by precipitation filter (8697
 data points = 49.64 % in total)
13510 data points (77.11%) excluded in total
4010 valid data points (22.89%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 198 data points (1.13%) set to NA
H: 114 data points (0.65%) set to NA
LE: 126 data points (0.72%) set to NA
NEE: 567 data points (3.24%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.53%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10080 data points (57.53%) excluded in total
7440 valid data points (42.47%) remaining.

New sEddyProc class for site 'BE-Lcr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Lcr-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 212 data points (1.21%) set to NA
H: 193 data points (1.1%) set to NA
LE: 192 data points (1.1%) set to NA
NEE: 671 data points (3.83%) set to NA
-------------------------------------------------------------------
Data filtering:
8592 data points (49.04%) excluded by growing season filter
2891 additional data points (16.5%) excluded by precipitation filter (7115
 data points = 40.61 % in total)
11483 data points (65.54%) excluded in total
6037 valid data points (34.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 212 data points (1.21%) set to NA
H: 193 data points (1.1%) set to NA
LE: 192 data points (1.1%) set to NA
NEE: 671 data points (3.83%) set to NA
-------------------------------------------------------------------
Data filtering:
8592 data points (49.04%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8592 data points (49.04%) excluded in total
8928 valid data points (50.96%) remaining.

New sEddyProc class for site 'BE-Lcr'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 107.12.

Regression of reference temperature R_ref for 4 periods.

[16/329] Processing: BE-Maa

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: BE-Maa | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 5 data points (0.03%) set to NA
H: 12 data points (0.07%) set to NA
LE: 25 data points (0.14%) set to NA
NEE: 410 data points (2.34%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
3851 additional data points (21.98%) excluded by precipitation filter (10299
 data points = 58.78 % in total)
14075 data points (80.34%) excluded in total
3445 valid data points (19.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5 data points (0.03%) set to NA
H: 12 data points (0.07%) set to NA
LE: 25 data points (0.14%) set to NA
NEE: 410 data points (2.34%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10224 data points (58.36%) excluded in total
7296 valid data points (41.64%) remaining.

New sEddyProc class for site 'BE-Maa'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Maa-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1386 data points (7.91%) set to NA
H: 931 data points (5.31%) set to NA
LE: 2091 data points (11.93%) set to NA
NEE: 4152 data points (23.7%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 38”

-------------------------------------------------------------------
Data filtering:
8880 data points (50.68%) excluded by growing season filter
3250 additional data points (18.55%) excluded by precipitation filter (8241
 data points = 47.04 % in total)
12130 data points (69.24%) excluded in total
5390 valid data points (30.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1386 data points (7.91%) set to NA
H: 931 data points (5.31%) set to NA
LE: 2091 data points (11.93%) set to NA
NEE: 4152 data points (23.7%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 38”

-------------------------------------------------------------------
Data filtering:
8880 data points (50.68%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8880 data points (50.68%) excluded in total
8640 valid data points (49.32%) remaining.

New sEddyProc class for site 'BE-Maa'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 66.97.

Regression of reference temperature R_ref for 12 periods.

Quality control:
TA: 1859 data points (10.61%) set to NA
H: 501 data points (2.86%) set to NA
LE: 3759 data points (21.46%) set to NA
NEE: 4309 data points (24.59%) set to NA
-------------------------------------------------------------------
Data filtering:
9264 data points (52.88%) excluded by growing season filter
2755 additional data points (15.72%) excluded by precipitation filter (6804
 data points = 38.84 % in total)
12019 data points (68.6%) excluded in total
5501 valid data points (31.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1859 data points (10.61%) set to NA
H: 501 data points (2.86%) set to NA
LE: 3759 data points (21.46%) set to NA
NEE: 4309 data points (24.59%) set to NA
-------------------------------------------------------------------
Data filtering:
9264 data points (52.88%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9264 data points (52.88%) excluded in total
8256 valid data points (47.12%) remaining.

New sEddyProc class for site 'BE-Maa'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 182.37.

Regression of reference temperature R_ref for 13 periods.

Quality control:
TA: 11 data points (0.06%) set to NA
H: 52 data points (0.3%) set to NA
LE: 55 data points (0.31%) set to NA
NEE: 373 data points (2.12%) set to NA
-------------------------------------------------------------------
Data filtering:
8736 data points (49.73%) excluded by growing season filter
1936 additional data points (11.02%) excluded by precipitation filter (3565
 data points = 20.29 % in total)
10672 data points (60.75%) excluded in total
6896 valid data points (39.25%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11 data points (0.06%) set to NA
H: 52 data points (0.3%) set to NA
LE: 55 data points (0.31%) set to NA
NEE: 373 data points (2.12%) set to NA
-------------------------------------------------------------------
Data filtering:
8736 data points (49.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8736 data points (49.73%) excluded in total
8832 valid data points (50.27%) remaining.

New sEddyProc class for site 'BE-Maa'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Maa-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6 data points (0.03%) set to NA
H: 577 data points (3.29%) set to NA
LE: 92 data points (0.53%) set to NA
NEE: 433 data points (2.47%) set to NA
-------------------------------------------------------------------
Data filtering:
9696 data points (55.34%) excluded by growing season filter
4112 additional data points (23.47%) excluded by precipitation filter (8648
 data points = 49.36 % in total)
13808 data points (78.81%) excluded in total
3712 valid data points (21.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6 data points (0.03%) set to NA
H: 577 data points (3.29%) set to NA
LE: 92 data points (0.53%) set to NA
NEE: 433 data points (2.47%) set to NA
-------------------------------------------------------------------
Data filtering:
9696 data points (55.34%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9696 data points (55.34%) excluded in total
7824 valid data points (44.66%) remaining.

New sEddyProc class for site 'BE-Maa'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Maa-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 218 data points (1.24%) set to NA
LE: 99 data points (0.57%) set to NA
NEE: 463 data points (2.64%) set to NA
-------------------------------------------------------------------
Data filtering:
8112 data points (46.3%) excluded by growing season filter
3273 additional data points (18.68%) excluded by precipitation filter (6945
 data points = 39.64 % in total)
11385 data points (64.98%) excluded in total
6135 valid data points (35.02%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 218 data points (1.24%) set to NA
LE: 99 data points (0.57%) set to NA
NEE: 463 data points (2.64%) set to NA
-------------------------------------------------------------------
Data filtering:
8112 data points (46.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8112 data points (46.3%) excluded in total
9408 valid data points (53.7%) remaining.

New sEddyProc class for site 'BE-Maa'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Maa-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 160 data points (0.91%) set to NA
LE: 56 data points (0.32%) set to NA
NEE: 293 data points (1.67%) set to NA
-------------------------------------------------------------------
Data filtering:
8256 data points (47.12%) excluded by growing season filter
3826 additional data points (21.84%) excluded by precipitation filter (9494
 data points = 54.19 % in total)
12082 data points (68.96%) excluded in total
5438 valid data points (31.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 160 data points (0.91%) set to NA
LE: 56 data points (0.32%) set to NA
NEE: 293 data points (1.67%) set to NA
-------------------------------------------------------------------
Data filtering:
8256 data points (47.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8256 data points (47.12%) excluded in total
9264 valid data points (52.88%) remaining.

New sEddyProc class for site 'BE-Maa'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Maa-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4 data points (0.02%) set to NA
H: 143 data points (0.81%) set to NA
LE: 74 data points (0.42%) set to NA
NEE: 365 data points (2.08%) set to NA
-------------------------------------------------------------------
Data filtering:
9264 data points (52.73%) excluded by growing season filter
4555 additional data points (25.93%) excluded by precipitation filter (9957
 data points = 56.68 % in total)
13819 data points (78.66%) excluded in total
3749 valid data points (21.34%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4 data points (0.02%) set to NA
H: 143 data points (0.81%) set to NA
LE: 74 data points (0.42%) set to NA
NEE: 365 data points (2.08%) set to NA
-------------------------------------------------------------------
Data filtering:
9264 data points (52.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9264 data points (52.73%) excluded in total
8304 valid data points (47.27%) remaining.

New sEddyProc class for site 'BE-Maa'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Maa-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[17/329] Processing: BE-Vie

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: BE-Vie | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 83 data points (0.47%) set to NA
LE: 124 data points (0.71%) set to NA
NEE: 407 data points (2.32%) set to NA
-------------------------------------------------------------------
Data filtering:
7056 data points (40.27%) excluded by growing season filter
4074 additional data points (23.25%) excluded by precipitation filter (7777
 data points = 44.39 % in total)
11130 data points (63.53%) excluded in total
6390 valid data points (36.47%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 83 data points (0.47%) set to NA
LE: 124 data points (0.71%) set to NA
NEE: 407 data points (2.32%) set to NA
-------------------------------------------------------------------
Data filtering:
7056 data points (40.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7056 data points (40.27%) excluded in total
10464 valid data points (59.73%) remaining.

New sEddyProc class for site 'BE-Vie'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Vie-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 642 data points (3.66%) set to NA
H: 387 data points (2.21%) set to NA
LE: 478 data points (2.73%) set to NA
NEE: 1085 data points (6.19%) set to NA
-------------------------------------------------------------------
Data filtering:
7728 data points (44.11%) excluded by growing season filter
3427 additional data points (19.56%) excluded by precipitation filter (6516
 data points = 37.19 % in total)
11155 data points (63.67%) excluded in total
6365 valid data points (36.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 642 data points (3.66%) set to NA
H: 387 data points (2.21%) set to NA
LE: 478 data points (2.73%) set to NA
NEE: 1085 data points (6.19%) set to NA
-------------------------------------------------------------------
Data filtering:
7728 data points (44.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7728 data points (44.11%) excluded in total
9792 valid data points (55.89%) remaining.

New sEddyProc class for site 'BE-Vie'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 8 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Vie-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 283 data points (1.62%) set to NA
LE: 342 data points (1.95%) set to NA
NEE: 1015 data points (5.79%) set to NA
-------------------------------------------------------------------
Data filtering:
7824 data points (44.66%) excluded by growing season filter
3890 additional data points (22.2%) excluded by precipitation filter (8067
 data points = 46.04 % in total)
11714 data points (66.86%) excluded in total
5806 valid data points (33.14%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 283 data points (1.62%) set to NA
LE: 342 data points (1.95%) set to NA
NEE: 1015 data points (5.79%) set to NA
-------------------------------------------------------------------
Data filtering:
7824 data points (44.66%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7824 data points (44.66%) excluded in total
9696 valid data points (55.34%) remaining.

New sEddyProc class for site 'BE-Vie'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Vie-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 8446 data points (48.08%) set to NA
H: 45 data points (0.26%) set to NA
LE: 1300 data points (7.4%) set to NA
NEE: 1386 data points (7.89%) set to NA
-------------------------------------------------------------------
Data filtering:
6624 data points (37.7%) excluded by growing season filter
4654 additional data points (26.49%) excluded by precipitation filter (8726
 data points = 49.67 % in total)
11278 data points (64.2%) excluded in total
6290 valid data points (35.8%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8446 data points (48.08%) set to NA
H: 45 data points (0.26%) set to NA
LE: 1300 data points (7.4%) set to NA
NEE: 1386 data points (7.89%) set to NA
-------------------------------------------------------------------
Data filtering:
6624 data points (37.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6624 data points (37.7%) excluded in total
10944 valid data points (62.3%) remaining.

New sEddyProc class for site 'BE-Vie'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Vie-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 612 data points (3.49%) set to NA
LE: 3830 data points (21.86%) set to NA
NEE: 4058 data points (23.16%) set to NA
-------------------------------------------------------------------
Data filtering:
7200 data points (41.1%) excluded by growing season filter
8659 additional data points (49.42%) excluded by precipitation filter (13496
 data points = 77.03 % in total)
15859 data points (90.52%) excluded in total
1661 valid data points (9.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 612 data points (3.49%) set to NA
LE: 3830 data points (21.86%) set to NA
NEE: 4058 data points (23.16%) set to NA
-------------------------------------------------------------------
Data filtering:
7200 data points (41.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7200 data points (41.1%) excluded in total
10320 valid data points (58.9%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -51, -50 ...”
New sEddyProc class for site 'BE-Vie'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -51, -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Vie-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2029 data points (11.58%) set to NA
LE: 1984 data points (11.32%) set to NA
NEE: 2270 data points (12.96%) set to NA
-------------------------------------------------------------------
Data filtering:
6288 data points (35.89%) excluded by growing season filter
4692 additional data points (26.78%) excluded by precipitation filter (8946
 data points = 51.06 % in total)
10980 data points (62.67%) excluded in total
6540 valid data points (37.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2029 data points (11.58%) set to NA
LE: 1984 data points (11.32%) set to NA
NEE: 2270 data points (12.96%) set to NA
-------------------------------------------------------------------
Data filtering:
6288 data points (35.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6288 data points (35.89%) excluded in total
11232 valid data points (64.11%) remaining.

New sEddyProc class for site 'BE-Vie'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Vie-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 18 data points (0.1%) set to NA
H: 695 data points (3.97%) set to NA
LE: 4776 data points (27.26%) set to NA
NEE: 5034 data points (28.73%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 36”

-------------------------------------------------------------------
Data filtering:
3984 data points (22.74%) excluded by growing season filter
7293 additional data points (41.63%) excluded by precipitation filter (10459
 data points = 59.7 % in total)
11277 data points (64.37%) excluded in total
6243 valid data points (35.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 18 data points (0.1%) set to NA
H: 695 data points (3.97%) set to NA
LE: 4776 data points (27.26%) set to NA
NEE: 5034 data points (28.73%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 36”

-------------------------------------------------------------------
Data filtering:
3984 data points (22.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3984 data points (22.74%) excluded in total
13536 valid data points (77.26%) remaining.

New sEddyProc class for site 'BE-Vie'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Vie-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 19 data points (0.11%) set to NA
H: 426 data points (2.42%) set to NA
LE: 646 data points (3.68%) set to NA
NEE: 922 data points (5.25%) set to NA
-------------------------------------------------------------------
Data filtering:
6912 data points (39.34%) excluded by growing season filter
6284 additional data points (35.77%) excluded by precipitation filter (9956
 data points = 56.67 % in total)
13196 data points (75.11%) excluded in total
4372 valid data points (24.89%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 19 data points (0.11%) set to NA
H: 426 data points (2.42%) set to NA
LE: 646 data points (3.68%) set to NA
NEE: 922 data points (5.25%) set to NA
-------------------------------------------------------------------
Data filtering:
6912 data points (39.34%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6912 data points (39.34%) excluded in total
10656 valid data points (60.66%) remaining.

New sEddyProc class for site 'BE-Vie'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BE-Vie-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[18/329] Processing: BJ-Bfg

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: BJ-Bfg | Years: 2017
Quality control:
TA: 521 data points (2.97%) set to NA
H: 1240 data points (7.08%) set to NA
LE: 1290 data points (7.36%) set to NA
NEE: 7130 data points (40.7%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 28”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4688 additional data points (26.76%) excluded by precipitation filter (4688
 data points = 26.76 % in total)
4688 data points (26.76%) excluded in total
12832 valid data points (73.24%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 521 data points (2.97%) set to NA
H: 1240 data points (7.08%) set to NA
LE: 1290 data points (7.36%) set to NA
NEE: 7130 data points (40.7%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 28”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 23 cases! Invalid values with 'NEE < -50': -71, -74, -63, -70, -68, -69, -51, -53, -68, -75, -59, -69, -58, -66, -52, -54, -54, -59, -51, -57, -59, -53, -61 ...”
New sEddyProc class for site 'BJ-Bfg'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 23 cases! Invalid values with 'NEE < -50': -71, -74, -63, -70, -68, -69, -51, -53, -68, -75, -59, -69, -58, -66, -52, -54, -54, -59, -51, -57, -59, -53, -61 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BJ-Bfg-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[19/329] Processing: BJ-Nhu

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: BJ-Nhu | Years: 2017
Quality control:
TA: 3028 data points (17.28%) set to NA
H: 5691 data points (32.48%) set to NA
LE: 6169 data points (35.21%) set to NA
NEE: 7743 data points (44.2%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5123 additional data points (29.24%) excluded by precipitation filter (5123
 data points = 29.24 % in total)
5123 data points (29.24%) excluded in total
12397 valid data points (70.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3028 data points (17.28%) set to NA
H: 5691 data points (32.48%) set to NA
LE: 6169 data points (35.21%) set to NA
NEE: 7743 data points (44.2%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'BJ-Nhu'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 19 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BJ-Nhu-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[20/329] Processing: BR-ITA

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: BR-ITA | Years: 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 14910 data points (84.87%) set to NA
H: 14976 data points (85.25%) set to NA
LE: 15040 data points (85.61%) set to NA
NEE: 15606 data points (88.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8181 additional data points (46.57%) excluded by precipitation filter (8181
 data points = 46.57 % in total)
8181 data points (46.57%) excluded in total
9387 valid data points (53.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 14910 data points (84.87%) set to NA
H: 14976 data points (85.25%) set to NA
LE: 15040 data points (85.61%) set to NA
NEE: 15606 data points (88.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'BR-ITA'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BR-ITA-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2963 data points (16.91%) set to NA
H: 3068 data points (17.51%) set to NA
LE: 3269 data points (18.66%) set to NA
NEE: 3845 data points (21.95%) set to NA
-------------------------------------------------------------------
Data filtering:
4032 data points (23.01%) excluded by growing season filter
6683 additional data points (38.14%) excluded by precipitation filter (7892
 data points = 45.05 % in total)
10715 data points (61.16%) excluded in total
6805 valid data points (38.84%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2963 data points (16.91%) set to NA
H: 3068 data points (17.51%) set to NA
LE: 3269 data points (18.66%) set to NA
NEE: 3845 data points (21.95%) set to NA
-------------------------------------------------------------------
Data filtering:
4032 data points (23.01%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4032 data points (23.01%) excluded in total
13488 valid data points (76.99%) remaining.

New sEddyProc class for site 'BR-ITA'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 114.23.

Regression of reference temperature R_ref for 17 periods.

Quality control:
TA: 2478 data points (14.14%) set to NA
H: 2483 data points (14.17%) set to NA
LE: 2501 data points (14.28%) set to NA
NEE: 2983 data points (17.03%) set to NA
-------------------------------------------------------------------
Data filtering:
1488 data points (8.49%) excluded by growing season filter
8387 additional data points (47.87%) excluded by precipitation filter (8990
 data points = 51.31 % in total)
9875 data points (56.36%) excluded in total
7645 valid data points (43.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2478 data points (14.14%) set to NA
H: 2483 data points (14.17%) set to NA
LE: 2501 data points (14.28%) set to NA
NEE: 2983 data points (17.03%) set to NA
-------------------------------------------------------------------
Data filtering:
1488 data points (8.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1488 data points (8.49%) excluded in total
16032 valid data points (91.51%) remaining.

New sEddyProc class for site 'BR-ITA'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 58.84.

Regression of reference temperature R_ref for 23 periods.

Quality control:
TA: 5629 data points (32.13%) set to NA
H: 5650 data points (32.25%) set to NA
LE: 5683 data points (32.44%) set to NA
NEE: 5888 data points (33.61%) set to NA
-------------------------------------------------------------------
Data filtering:
672 data points (3.84%) excluded by growing season filter
10040 additional data points (57.31%) excluded by precipitation filter (10258
 data points = 58.55 % in total)
10712 data points (61.14%) excluded in total
6808 valid data points (38.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5629 data points (32.13%) set to NA
H: 5650 data points (32.25%) set to NA
LE: 5683 data points (32.44%) set to NA
NEE: 5888 data points (33.61%) set to NA
-------------------------------------------------------------------
Data filtering:
672 data points (3.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
672 data points (3.84%) excluded in total
16848 valid data points (96.16%) remaining.

New sEddyProc class for site 'BR-ITA'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 300.44.

Regression of reference temperature R_ref for 36 periods.

Quality control:
TA: 6478 data points (36.87%) set to NA
H: 6494 data points (36.96%) set to NA
LE: 6505 data points (37.03%) set to NA
NEE: 6797 data points (38.69%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 112”

-------------------------------------------------------------------
Data filtering:
1440 data points (8.2%) excluded by growing season filter
7245 additional data points (41.24%) excluded by precipitation filter (7721
 data points = 43.95 % in total)
8685 data points (49.44%) excluded in total
8883 valid data points (50.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6478 data points (36.87%) set to NA
H: 6494 data points (36.96%) set to NA
LE: 6505 data points (37.03%) set to NA
NEE: 6797 data points (38.69%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 112”

-------------------------------------------------------------------
Data filtering:
1440 data points (8.2%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1440 data points (8.2%) excluded in total
16128 valid data points (91.8%) remaining.

New sEddyProc class for site 'BR-ITA'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 13 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BR-ITA-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[21/329] Processing: BR-Npw

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: BR-Npw | Years: 2017
Quality control:
TA: 8827 data points (50.38%) set to NA
H: 8824 data points (50.37%) set to NA
LE: 8926 data points (50.95%) set to NA
NEE: 10414 data points (59.44%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7332 additional data points (41.85%) excluded by precipitation filter (7332
 data points = 41.85 % in total)
7332 data points (41.85%) excluded in total
10188 valid data points (58.15%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8827 data points (50.38%) set to NA
H: 8824 data points (50.37%) set to NA
LE: 8926 data points (50.95%) set to NA
NEE: 10414 data points (59.44%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 38 cases! Invalid values with 'NEE < -50': -63, -54, -57, -63, -67, -51, -56, -51, -69, -52, -54, -57, -56, -56, -53, -59, -56, -56, -54, -51, -54, -50, -50, -50, -58, -62, -74, -53, -57, -66, -52, -58, -57, -52, -80, -72, -61, -55 ...”
New sEddyProc class for site 'BR-Npw'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 38 cases! Invalid values with 'NEE < -50': -63, -54, -57, -63, -67, -51, -56, -51, -69, -52, -54, -57, -56, -56, -53, -59, -56, -56, -54, -51, -54, -50, -50, -50, -58, -62, -74, -53, -57, -66, -52, -58, -57, -52, -80, -72, -61, -55 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for BR-Npw-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[22/329] Processing: BW-Gum

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: BW-Gum | Years: 2018, 2019, 2020
Quality control:
TA: 10109 data points (57.7%) set to NA
H: 6787 data points (38.74%) set to NA
LE: 6780 data points (38.7%) set to NA
NEE: 7731 data points (44.13%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 59”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6170 additional data points (35.22%) excluded by precipitation filter (6170
 data points = 35.22 % in total)
6170 data points (35.22%) excluded in total
11350 valid data points (64.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10109 data points (57.7%) set to NA
H: 6787 data points (38.74%) set to NA
LE: 6780 data points (38.7%) set to NA
NEE: 7731 data points (44.13%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 59”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'BW-Gum'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 153.06.

Regression of reference temperature R_ref for 35 periods.

Quality control:
TA: 1876 data points (10.71%) set to NA
H: 1951 data points (11.14%) set to NA
LE: 1941 data points (11.08%) set to NA
NEE: 2427 data points (13.85%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5304 additional data points (30.27%) excluded by precipitation filter (5304
 data points = 30.27 % in total)
5304 data points (30.27%) excluded in total
12216 valid data points (69.73%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1876 data points (10.71%) set to NA
H: 1951 data points (11.14%) set to NA
LE: 1941 data points (11.08%) set to NA
NEE: 2427 data points (13.85%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -53, -50, -52, -69 ...”
New sEddyProc class for site 'BW-Gum'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -53, -50, -52, -69 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 301.89.

Regression of reference temperature R_ref for 13 periods.

Quality control:
TA: 6652 data points (37.86%) set to NA
H: 4382 data points (24.94%) set to NA
LE: 4405 data points (25.07%) set to NA
NEE: 5184 data points (29.51%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 28”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7132 additional data points (40.6%) excluded by precipitation filter (7132
 data points = 40.6 % in total)
7132 data points (40.6%) excluded in total
10436 valid data points (59.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6652 data points (37.86%) set to NA
H: 4382 data points (24.94%) set to NA
LE: 4405 data points (25.07%) set to NA
NEE: 5184 data points (29.51%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 28”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -59, -66, -62, -74 ...”
New sEddyProc class for site 'BW-Gum'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -59, -66, -62, -74 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 252.62.

Regression of reference temperature R_ref for 36 periods.

[23/329] Processing: CA-ARB

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-ARB | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 8 data points (0.05%) set to NA
H: 3588 data points (20.48%) set to NA
LE: 7114 data points (40.61%) set to NA
NEE: 7658 data points (43.71%) set to NA
-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
2439 additional data points (13.92%) excluded by precipitation filter (5052
 data points = 28.84 % in total)
13671 data points (78.03%) excluded in total
3849 valid data points (21.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8 data points (0.05%) set to NA
H: 3588 data points (20.48%) set to NA
LE: 7114 data points (40.61%) set to NA
NEE: 7658 data points (43.71%) set to NA
-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11232 data points (64.11%) excluded in total
6288 valid data points (35.89%) remaining.

New sEddyProc class for site 'CA-ARB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-ARB-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 10576 data points (60.37%) set to NA
LE: 10580 data points (60.39%) set to NA
NEE: 10667 data points (60.88%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 64”

-------------------------------------------------------------------
Data filtering:
11760 data points (67.12%) excluded by growing season filter
2101 additional data points (11.99%) excluded by precipitation filter (5107
 data points = 29.15 % in total)
13861 data points (79.12%) excluded in total
3659 valid data points (20.88%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 10576 data points (60.37%) set to NA
LE: 10580 data points (60.39%) set to NA
NEE: 10667 data points (60.88%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 64”

-------------------------------------------------------------------
Data filtering:
11760 data points (67.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11760 data points (67.12%) excluded in total
5760 valid data points (32.88%) remaining.

New sEddyProc class for site 'CA-ARB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-ARB-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 8573 data points (48.93%) set to NA
LE: 8573 data points (48.93%) set to NA
NEE: 8681 data points (49.55%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 65”

-------------------------------------------------------------------
Data filtering:
7488 data points (42.74%) excluded by growing season filter
3892 additional data points (22.21%) excluded by precipitation filter (5372
 data points = 30.66 % in total)
11380 data points (64.95%) excluded in total
6140 valid data points (35.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 8573 data points (48.93%) set to NA
LE: 8573 data points (48.93%) set to NA
NEE: 8681 data points (49.55%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 65”

-------------------------------------------------------------------
Data filtering:
7488 data points (42.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7488 data points (42.74%) excluded in total
10032 valid data points (57.26%) remaining.

New sEddyProc class for site 'CA-ARB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-ARB-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 6524 data points (37.14%) set to NA
LE: 6525 data points (37.14%) set to NA
NEE: 6784 data points (38.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 77”

-------------------------------------------------------------------
Data filtering:
7872 data points (44.81%) excluded by growing season filter
2974 additional data points (16.93%) excluded by precipitation filter (5215
 data points = 29.68 % in total)
10846 data points (61.74%) excluded in total
6722 valid data points (38.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 6524 data points (37.14%) set to NA
LE: 6525 data points (37.14%) set to NA
NEE: 6784 data points (38.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 77”

-------------------------------------------------------------------
Data filtering:
7872 data points (44.81%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7872 data points (44.81%) excluded in total
9696 valid data points (55.19%) remaining.

New sEddyProc class for site 'CA-ARB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-ARB-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 9277 data points (52.95%) set to NA
LE: 9290 data points (53.03%) set to NA
NEE: 9448 data points (53.93%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 131”

-------------------------------------------------------------------
Data filtering:
3648 data points (20.82%) excluded by growing season filter
4720 additional data points (26.94%) excluded by precipitation filter (5855
 data points = 33.42 % in total)
8368 data points (47.76%) excluded in total
9152 valid data points (52.24%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 9277 data points (52.95%) set to NA
LE: 9290 data points (53.03%) set to NA
NEE: 9448 data points (53.93%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 131”

-------------------------------------------------------------------
Data filtering:
3648 data points (20.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3648 data points (20.82%) excluded in total
13872 valid data points (79.18%) remaining.

New sEddyProc class for site 'CA-ARB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-ARB-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 7149 data points (40.8%) set to NA
LE: 6948 data points (39.66%) set to NA
NEE: 7374 data points (42.09%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 61”

-------------------------------------------------------------------
Data filtering:
11376 data points (64.93%) excluded by growing season filter
2467 additional data points (14.08%) excluded by precipitation filter (5342
 data points = 30.49 % in total)
13843 data points (79.01%) excluded in total
3677 valid data points (20.99%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 7149 data points (40.8%) set to NA
LE: 6948 data points (39.66%) set to NA
NEE: 7374 data points (42.09%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 61”

-------------------------------------------------------------------
Data filtering:
11376 data points (64.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11376 data points (64.93%) excluded in total
6144 valid data points (35.07%) remaining.

New sEddyProc class for site 'CA-ARB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-ARB-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 17520 data points (100%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4810 additional data points (27.45%) excluded by precipitation filter (4810
 data points = 27.45 % in total)
4810 data points (27.45%) excluded in total
12710 valid data points (72.55%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for CA-ARB-2023”

Quality control:
TA: 0 data points (0%) set to NA
H: 7763 data points (44.19%) set to NA
LE: 7779 data points (44.28%) set to NA
NEE: 7921 data points (45.09%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 60”

-------------------------------------------------------------------
Data filtering:
8208 data points (46.72%) excluded by growing season filter
3155 additional data points (17.96%) excluded by precipitation filter (5434
 data points = 30.93 % in total)
11363 data points (64.68%) excluded in total
6205 valid data points (35.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 7763 data points (44.19%) set to NA
LE: 7779 data points (44.28%) set to NA
NEE: 7921 data points (45.09%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 60”

-------------------------------------------------------------------
Data filtering:
8208 data points (46.72%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8208 data points (46.72%) excluded in total
9360 valid data points (53.28%) remaining.

New sEddyProc class for site 'CA-ARB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-ARB-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[24/329] Processing: CA-ARF

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-ARF | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 10 data points (0.06%) set to NA
H: 2913 data points (16.63%) set to NA
LE: 2905 data points (16.58%) set to NA
NEE: 3085 data points (17.61%) set to NA
-------------------------------------------------------------------
Data filtering:
12288 data points (70.14%) excluded by growing season filter
2120 additional data points (12.1%) excluded by precipitation filter (5052
 data points = 28.84 % in total)
14408 data points (82.24%) excluded in total
3112 valid data points (17.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10 data points (0.06%) set to NA
H: 2913 data points (16.63%) set to NA
LE: 2905 data points (16.58%) set to NA
NEE: 3085 data points (17.61%) set to NA
-------------------------------------------------------------------
Data filtering:
12288 data points (70.14%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12288 data points (70.14%) excluded in total
5232 valid data points (29.86%) remaining.

New sEddyProc class for site 'CA-ARF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-ARF-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2633 data points (15.03%) set to NA
LE: 2592 data points (14.79%) set to NA
NEE: 2860 data points (16.32%) set to NA
-------------------------------------------------------------------
Data filtering:
12864 data points (73.42%) excluded by growing season filter
1651 additional data points (9.42%) excluded by precipitation filter (5107
 data points = 29.15 % in total)
14515 data points (82.85%) excluded in total
3005 valid data points (17.15%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2633 data points (15.03%) set to NA
LE: 2592 data points (14.79%) set to NA
NEE: 2860 data points (16.32%) set to NA
-------------------------------------------------------------------
Data filtering:
12864 data points (73.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12864 data points (73.42%) excluded in total
4656 valid data points (26.58%) remaining.

New sEddyProc class for site 'CA-ARF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-ARF-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 107 data points (0.61%) set to NA
H: 8433 data points (48.13%) set to NA
LE: 3709 data points (21.17%) set to NA
NEE: 3793 data points (21.65%) set to NA
-------------------------------------------------------------------
Data filtering:
12864 data points (73.42%) excluded by growing season filter
2265 additional data points (12.93%) excluded by precipitation filter (5372
 data points = 30.66 % in total)
15129 data points (86.35%) excluded in total
2391 valid data points (13.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 107 data points (0.61%) set to NA
H: 8433 data points (48.13%) set to NA
LE: 3709 data points (21.17%) set to NA
NEE: 3793 data points (21.65%) set to NA
-------------------------------------------------------------------
Data filtering:
12864 data points (73.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12864 data points (73.42%) excluded in total
4656 valid data points (26.58%) remaining.

New sEddyProc class for site 'CA-ARF'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 315.36.

Regression of reference temperature R_ref for 2 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 10039 data points (57.14%) set to NA
LE: 10010 data points (56.98%) set to NA
NEE: 10119 data points (57.6%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 104”

-------------------------------------------------------------------
Data filtering:
8784 data points (50%) excluded by growing season filter
3049 additional data points (17.36%) excluded by precipitation filter (5215
 data points = 29.68 % in total)
11833 data points (67.36%) excluded in total
5735 valid data points (32.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 10039 data points (57.14%) set to NA
LE: 10010 data points (56.98%) set to NA
NEE: 10119 data points (57.6%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 104”

-------------------------------------------------------------------
Data filtering:
8784 data points (50%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8784 data points (50%) excluded in total
8784 valid data points (50%) remaining.

New sEddyProc class for site 'CA-ARF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-ARF-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 8302 data points (47.39%) set to NA
LE: 8306 data points (47.41%) set to NA
NEE: 8323 data points (47.51%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 112”

-------------------------------------------------------------------
Data filtering:
6864 data points (39.18%) excluded by growing season filter
3601 additional data points (20.55%) excluded by precipitation filter (5855
 data points = 33.42 % in total)
10465 data points (59.73%) excluded in total
7055 valid data points (40.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 8302 data points (47.39%) set to NA
LE: 8306 data points (47.41%) set to NA
NEE: 8323 data points (47.51%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 112”

-------------------------------------------------------------------
Data filtering:
6864 data points (39.18%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6864 data points (39.18%) excluded in total
10656 valid data points (60.82%) remaining.

New sEddyProc class for site 'CA-ARF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-ARF-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 6389 data points (36.47%) set to NA
LE: 6388 data points (36.46%) set to NA
NEE: 6434 data points (36.72%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 74”

-------------------------------------------------------------------
Data filtering:
8832 data points (50.41%) excluded by growing season filter
2781 additional data points (15.87%) excluded by precipitation filter (5342
 data points = 30.49 % in total)
11613 data points (66.28%) excluded in total
5907 valid data points (33.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 6389 data points (36.47%) set to NA
LE: 6388 data points (36.46%) set to NA
NEE: 6434 data points (36.72%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 74”

-------------------------------------------------------------------
Data filtering:
8832 data points (50.41%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8832 data points (50.41%) excluded in total
8688 valid data points (49.59%) remaining.

New sEddyProc class for site 'CA-ARF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-ARF-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3201 data points (18.27%) set to NA
H: 3876 data points (22.12%) set to NA
LE: 3885 data points (22.17%) set to NA
NEE: 4634 data points (26.45%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 30”

-------------------------------------------------------------------
Data filtering:
12240 data points (69.86%) excluded by growing season filter
1676 additional data points (9.57%) excluded by precipitation filter (4810
 data points = 27.45 % in total)
13916 data points (79.43%) excluded in total
3604 valid data points (20.57%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3201 data points (18.27%) set to NA
H: 3876 data points (22.12%) set to NA
LE: 3885 data points (22.17%) set to NA
NEE: 4634 data points (26.45%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 30”

-------------------------------------------------------------------
Data filtering:
12240 data points (69.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12240 data points (69.86%) excluded in total
5280 valid data points (30.14%) remaining.

New sEddyProc class for site 'CA-ARF'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 104.14.

Regression of reference temperature R_ref for 17 periods.

Quality control:
TA: 24 data points (0.14%) set to NA
H: 5176 data points (29.46%) set to NA
LE: 5591 data points (31.82%) set to NA
NEE: 5656 data points (32.19%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 41”

-------------------------------------------------------------------
Data filtering:
9696 data points (55.19%) excluded by growing season filter
2527 additional data points (14.38%) excluded by precipitation filter (5434
 data points = 30.93 % in total)
12223 data points (69.58%) excluded in total
5345 valid data points (30.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 24 data points (0.14%) set to NA
H: 5176 data points (29.46%) set to NA
LE: 5591 data points (31.82%) set to NA
NEE: 5656 data points (32.19%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 41”

-------------------------------------------------------------------
Data filtering:
9696 data points (55.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9696 data points (55.19%) excluded in total
7872 valid data points (44.81%) remaining.

New sEddyProc class for site 'CA-ARF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-ARF-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[25/329] Processing: CA-BOU

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-BOU | Years: 2018, 2019, 2020
Quality control:
TA: 9005 data points (51.4%) set to NA
H: 10700 data points (61.07%) set to NA
LE: 10700 data points (61.07%) set to NA
NEE: 11177 data points (63.8%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6768 additional data points (38.63%) excluded by precipitation filter (6768
 data points = 38.63 % in total)
6768 data points (38.63%) excluded in total
10752 valid data points (61.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9005 data points (51.4%) set to NA
H: 10700 data points (61.07%) set to NA
LE: 10700 data points (61.07%) set to NA
NEE: 11177 data points (63.8%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-BOU'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 8 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-BOU-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 5073 data points (28.96%) set to NA
H: 5241 data points (29.91%) set to NA
LE: 5234 data points (29.87%) set to NA
NEE: 6146 data points (35.08%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 77”

-------------------------------------------------------------------
Data filtering:
7296 data points (41.64%) excluded by growing season filter
3736 additional data points (21.32%) excluded by precipitation filter (5193
 data points = 29.64 % in total)
11032 data points (62.97%) excluded in total
6488 valid data points (37.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5073 data points (28.96%) set to NA
H: 5241 data points (29.91%) set to NA
LE: 5234 data points (29.87%) set to NA
NEE: 6146 data points (35.08%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 77”

-------------------------------------------------------------------
Data filtering:
7296 data points (41.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7296 data points (41.64%) excluded in total
10224 valid data points (58.36%) remaining.

New sEddyProc class for site 'CA-BOU'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-BOU-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4294 data points (24.44%) set to NA
H: 13189 data points (75.07%) set to NA
LE: 10801 data points (61.48%) set to NA
NEE: 10932 data points (62.23%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 183”

-------------------------------------------------------------------
Data filtering:
4032 data points (22.95%) excluded by growing season filter
4760 additional data points (27.09%) excluded by precipitation filter (6476
 data points = 36.86 % in total)
8792 data points (50.05%) excluded in total
8776 valid data points (49.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4294 data points (24.44%) set to NA
H: 13189 data points (75.07%) set to NA
LE: 10801 data points (61.48%) set to NA
NEE: 10932 data points (62.23%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 183”

-------------------------------------------------------------------
Data filtering:
4032 data points (22.95%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4032 data points (22.95%) excluded in total
13536 valid data points (77.05%) remaining.

New sEddyProc class for site 'CA-BOU'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-BOU-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[26/329] Processing: CA-CF3

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-CF3 | Years: 2022, 2023, 2024, 2025
Quality control:
TA: 10534 data points (60.13%) set to NA
H: 12557 data points (71.67%) set to NA
LE: 12573 data points (71.76%) set to NA
NEE: 12616 data points (72.01%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3210 additional data points (18.32%) excluded by precipitation filter (3210
 data points = 18.32 % in total)
3210 data points (18.32%) excluded in total
14310 valid data points (81.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10534 data points (60.13%) set to NA
H: 12557 data points (71.67%) set to NA
LE: 12573 data points (71.76%) set to NA
NEE: 12616 data points (72.01%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-CF3'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 110.07.

Regression of reference temperature R_ref for 2 periods.

Quality control:
TA: 9 data points (0.05%) set to NA
H: 869 data points (4.96%) set to NA
LE: 955 data points (5.45%) set to NA
NEE: 1603 data points (9.15%) set to NA
-------------------------------------------------------------------
Data filtering:
12816 data points (73.15%) excluded by growing season filter
1761 additional data points (10.05%) excluded by precipitation filter (3236
 data points = 18.47 % in total)
14577 data points (83.2%) excluded in total
2943 valid data points (16.8%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9 data points (0.05%) set to NA
H: 869 data points (4.96%) set to NA
LE: 955 data points (5.45%) set to NA
NEE: 1603 data points (9.15%) set to NA
-------------------------------------------------------------------
Data filtering:
12816 data points (73.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12816 data points (73.15%) excluded in total
4704 valid data points (26.85%) remaining.

New sEddyProc class for site 'CA-CF3'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-CF3-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 501 data points (2.85%) set to NA
H: 1625 data points (9.25%) set to NA
LE: 1742 data points (9.92%) set to NA
NEE: 2165 data points (12.32%) set to NA
-------------------------------------------------------------------
Data filtering:
13392 data points (76.23%) excluded by growing season filter
1467 additional data points (8.35%) excluded by precipitation filter (3948
 data points = 22.47 % in total)
14859 data points (84.58%) excluded in total
2709 valid data points (15.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 501 data points (2.85%) set to NA
H: 1625 data points (9.25%) set to NA
LE: 1742 data points (9.92%) set to NA
NEE: 2165 data points (12.32%) set to NA
-------------------------------------------------------------------
Data filtering:
13392 data points (76.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13392 data points (76.23%) excluded in total
4176 valid data points (23.77%) remaining.

New sEddyProc class for site 'CA-CF3'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-CF3-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 381 data points (2.17%) set to NA
H: 671 data points (3.83%) set to NA
LE: 770 data points (4.39%) set to NA
NEE: 1109 data points (6.33%) set to NA
-------------------------------------------------------------------
Data filtering:
13584 data points (77.53%) excluded by growing season filter
841 additional data points (4.8%) excluded by precipitation filter (2141
 data points = 12.22 % in total)
14425 data points (82.33%) excluded in total
3095 valid data points (17.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 381 data points (2.17%) set to NA
H: 671 data points (3.83%) set to NA
LE: 770 data points (4.39%) set to NA
NEE: 1109 data points (6.33%) set to NA
-------------------------------------------------------------------
Data filtering:
13584 data points (77.53%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13584 data points (77.53%) excluded in total
3936 valid data points (22.47%) remaining.

New sEddyProc class for site 'CA-CF3'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-CF3-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[27/329] Processing: CA-Ca3

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-Ca3 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 37 data points (0.21%) set to NA
H: 689 data points (3.93%) set to NA
LE: 739 data points (4.22%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7680 additional data points (43.84%) excluded by precipitation filter (7680
 data points = 43.84 % in total)
7680 data points (43.84%) excluded in total
9840 valid data points (56.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 37 data points (0.21%) set to NA
H: 689 data points (3.93%) set to NA
LE: 739 data points (4.22%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-Ca3'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-Ca3-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6 data points (0.03%) set to NA
H: 132 data points (0.75%) set to NA
LE: 326 data points (1.86%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4483 additional data points (25.59%) excluded by precipitation filter (4483
 data points = 25.59 % in total)
4483 data points (25.59%) excluded in total
13037 valid data points (74.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 6 data points (0.03%) set to NA
H: 132 data points (0.75%) set to NA
LE: 326 data points (1.86%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-Ca3'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-Ca3-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 650 data points (3.71%) set to NA
H: 661 data points (3.77%) set to NA
LE: 698 data points (3.98%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8032 additional data points (45.84%) excluded by precipitation filter (8032
 data points = 45.84 % in total)
8032 data points (45.84%) excluded in total
9488 valid data points (54.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 650 data points (3.71%) set to NA
H: 661 data points (3.77%) set to NA
LE: 698 data points (3.98%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-Ca3'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-Ca3-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 10 data points (0.06%) set to NA
LE: 32 data points (0.18%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9353 additional data points (53.24%) excluded by precipitation filter (9353
 data points = 53.24 % in total)
9353 data points (53.24%) excluded in total
8215 valid data points (46.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 10 data points (0.06%) set to NA
LE: 32 data points (0.18%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'CA-Ca3'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-Ca3-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 111 data points (0.63%) set to NA
LE: 110 data points (0.63%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8594 additional data points (49.05%) excluded by precipitation filter (8594
 data points = 49.05 % in total)
8594 data points (49.05%) excluded in total
8926 valid data points (50.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 111 data points (0.63%) set to NA
LE: 110 data points (0.63%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-Ca3'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-Ca3-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 16 data points (0.09%) set to NA
LE: 153 data points (0.87%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7942 additional data points (45.33%) excluded by precipitation filter (7942
 data points = 45.33 % in total)
7942 data points (45.33%) excluded in total
9578 valid data points (54.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 16 data points (0.09%) set to NA
LE: 153 data points (0.87%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-Ca3'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-Ca3-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 117 data points (0.67%) set to NA
H: 867 data points (4.95%) set to NA
LE: 893 data points (5.1%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8299 additional data points (47.37%) excluded by precipitation filter (8299
 data points = 47.37 % in total)
8299 data points (47.37%) excluded in total
9221 valid data points (52.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 117 data points (0.67%) set to NA
H: 867 data points (4.95%) set to NA
LE: 893 data points (5.1%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-Ca3'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-Ca3-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 81 data points (0.46%) set to NA
LE: 87 data points (0.5%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9153 additional data points (52.1%) excluded by precipitation filter (9153
 data points = 52.1 % in total)
9153 data points (52.1%) excluded in total
8415 valid data points (47.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 81 data points (0.46%) set to NA
LE: 87 data points (0.5%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'CA-Ca3'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-Ca3-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[28/329] Processing: CA-DB2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-DB2 | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 15192 data points (86.71%) set to NA
H: 15422 data points (88.03%) set to NA
LE: 15637 data points (89.25%) set to NA
NEE: 15675 data points (89.47%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7007 additional data points (39.99%) excluded by precipitation filter (7007
 data points = 39.99 % in total)
7007 data points (39.99%) excluded in total
10513 valid data points (60.01%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (21) for CA-DB2-2019”

Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 9 data points (0.05%) set to NA
NEE: 124 data points (0.71%) set to NA
-------------------------------------------------------------------
Data filtering:
8640 data points (49.18%) excluded by growing season filter
2944 additional data points (16.76%) excluded by precipitation filter (8272
 data points = 47.09 % in total)
11584 data points (65.94%) excluded in total
5984 valid data points (34.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 9 data points (0.05%) set to NA
NEE: 124 data points (0.71%) set to NA
-------------------------------------------------------------------
Data filtering:
8640 data points (49.18%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8640 data points (49.18%) excluded in total
8928 valid data points (50.82%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -54, -50, -51, -52, -51 ...”
New sEddyProc class for site 'CA-DB2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -54, -50, -51, -52, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-DB2-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 17 data points (0.1%) set to NA
LE: 17 data points (0.1%) set to NA
NEE: 131 data points (0.75%) set to NA
-------------------------------------------------------------------
Data filtering:
8736 data points (49.86%) excluded by growing season filter
1876 additional data points (10.71%) excluded by precipitation filter (7047
 data points = 40.22 % in total)
10612 data points (60.57%) excluded in total
6908 valid data points (39.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 17 data points (0.1%) set to NA
LE: 17 data points (0.1%) set to NA
NEE: 131 data points (0.75%) set to NA
-------------------------------------------------------------------
Data filtering:
8736 data points (49.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8736 data points (49.86%) excluded in total
8784 valid data points (50.14%) remaining.

New sEddyProc class for site 'CA-DB2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-DB2-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 25 data points (0.14%) set to NA
LE: 33 data points (0.19%) set to NA
NEE: 249 data points (1.42%) set to NA
-------------------------------------------------------------------
Data filtering:
10176 data points (58.08%) excluded by growing season filter
1525 additional data points (8.7%) excluded by precipitation filter (6167
 data points = 35.2 % in total)
11701 data points (66.79%) excluded in total
5819 valid data points (33.21%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 25 data points (0.14%) set to NA
LE: 33 data points (0.19%) set to NA
NEE: 249 data points (1.42%) set to NA
-------------------------------------------------------------------
Data filtering:
10176 data points (58.08%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10176 data points (58.08%) excluded in total
7344 valid data points (41.92%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
New sEddyProc class for site 'CA-DB2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-DB2-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 75 data points (0.43%) set to NA
LE: 75 data points (0.43%) set to NA
NEE: 417 data points (2.38%) set to NA
-------------------------------------------------------------------
Data filtering:
9024 data points (51.51%) excluded by growing season filter
1602 additional data points (9.14%) excluded by precipitation filter (6610
 data points = 37.73 % in total)
10626 data points (60.65%) excluded in total
6894 valid data points (39.35%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 75 data points (0.43%) set to NA
LE: 75 data points (0.43%) set to NA
NEE: 417 data points (2.38%) set to NA
-------------------------------------------------------------------
Data filtering:
9024 data points (51.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9024 data points (51.51%) excluded in total
8496 valid data points (48.49%) remaining.

New sEddyProc class for site 'CA-DB2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-DB2-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 16 data points (0.09%) set to NA
LE: 17 data points (0.1%) set to NA
NEE: 366 data points (2.08%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.64%) excluded by growing season filter
2218 additional data points (12.63%) excluded by precipitation filter (7200
 data points = 40.98 % in total)
11290 data points (64.26%) excluded in total
6278 valid data points (35.74%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 16 data points (0.09%) set to NA
LE: 17 data points (0.1%) set to NA
NEE: 366 data points (2.08%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9072 data points (51.64%) excluded in total
8496 valid data points (48.36%) remaining.

New sEddyProc class for site 'CA-DB2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-DB2-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[29/329] Processing: CA-DBB

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-DBB | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 3648 data points (20.82%) set to NA
LE: 3644 data points (20.8%) set to NA
NEE: 3860 data points (22.03%) set to NA
-------------------------------------------------------------------
Data filtering:
11856 data points (67.67%) excluded by growing season filter
758 additional data points (4.33%) excluded by precipitation filter (7468
 data points = 42.63 % in total)
12614 data points (72%) excluded in total
4906 valid data points (28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 3648 data points (20.82%) set to NA
LE: 3644 data points (20.8%) set to NA
NEE: 3860 data points (22.03%) set to NA
-------------------------------------------------------------------
Data filtering:
11856 data points (67.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11856 data points (67.67%) excluded in total
5664 valid data points (32.33%) remaining.

New sEddyProc class for site 'CA-DBB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-DBB-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2542 data points (14.51%) set to NA
LE: 2909 data points (16.6%) set to NA
NEE: 4039 data points (23.05%) set to NA
-------------------------------------------------------------------
Data filtering:
9744 data points (55.62%) excluded by growing season filter
2025 additional data points (11.56%) excluded by precipitation filter (7543
 data points = 43.05 % in total)
11769 data points (67.17%) excluded in total
5751 valid data points (32.83%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2542 data points (14.51%) set to NA
LE: 2909 data points (16.6%) set to NA
NEE: 4039 data points (23.05%) set to NA
-------------------------------------------------------------------
Data filtering:
9744 data points (55.62%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9744 data points (55.62%) excluded in total
7776 valid data points (44.38%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -52, -54, -52 ...”
New sEddyProc class for site 'CA-DBB'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -52, -54, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-DBB-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 689 data points (3.93%) set to NA
LE: 748 data points (4.27%) set to NA
NEE: 1059 data points (6.04%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.47%) excluded by growing season filter
1498 additional data points (8.55%) excluded by precipitation filter (6525
 data points = 37.24 % in total)
12442 data points (71.02%) excluded in total
5078 valid data points (28.98%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 689 data points (3.93%) set to NA
LE: 748 data points (4.27%) set to NA
NEE: 1059 data points (6.04%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10944 data points (62.47%) excluded in total
6576 valid data points (37.53%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -63 ...”
New sEddyProc class for site 'CA-DBB'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -63 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-DBB-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1342 data points (7.64%) set to NA
LE: 1347 data points (7.67%) set to NA
NEE: 1757 data points (10%) set to NA
-------------------------------------------------------------------
Data filtering:
9504 data points (54.1%) excluded by growing season filter
2634 additional data points (14.99%) excluded by precipitation filter (8262
 data points = 47.03 % in total)
12138 data points (69.09%) excluded in total
5430 valid data points (30.91%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1342 data points (7.64%) set to NA
LE: 1347 data points (7.67%) set to NA
NEE: 1757 data points (10%) set to NA
-------------------------------------------------------------------
Data filtering:
9504 data points (54.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9504 data points (54.1%) excluded in total
8064 valid data points (45.9%) remaining.

New sEddyProc class for site 'CA-DBB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-DBB-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 539 data points (3.08%) set to NA
LE: 702 data points (4.01%) set to NA
NEE: 977 data points (5.58%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.73%) excluded by growing season filter
1782 additional data points (10.17%) excluded by precipitation filter (7682
 data points = 43.85 % in total)
12246 data points (69.9%) excluded in total
5274 valid data points (30.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 539 data points (3.08%) set to NA
LE: 702 data points (4.01%) set to NA
NEE: 977 data points (5.58%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10464 data points (59.73%) excluded in total
7056 valid data points (40.27%) remaining.

New sEddyProc class for site 'CA-DBB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-DBB-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 17518 data points (99.99%) set to NA
H: 17519 data points (99.99%) set to NA
LE: 17519 data points (99.99%) set to NA
NEE: 17520 data points (100%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7420 additional data points (42.35%) excluded by precipitation filter (7420
 data points = 42.35 % in total)
7420 data points (42.35%) excluded in total
10100 valid data points (57.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 17518 data points (99.99%) set to NA
H: 17519 data points (99.99%) set to NA
LE: 17519 data points (99.99%) set to NA
NEE: 17520 data points (100%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-DBB'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

  REddyProc error for CA-DBB-2022: sMRFluxPartition:::sRegrE0fromShortTerm:::fCheckColNum::: Detected following columns in dataset to be non numeric: FP_VARnight! First occurence of non-numeric value at column 'FP_VARnight' at row NA is 'NA'.

Quality control:
TA: 0 data points (0%) set to NA
H: 113 data points (0.64%) set to NA
LE: 111 data points (0.63%) set to NA
NEE: 668 data points (3.81%) set to NA
-------------------------------------------------------------------
Data filtering:
11328 data points (64.66%) excluded by growing season filter
742 additional data points (4.24%) excluded by precipitation filter (6816
 data points = 38.9 % in total)
12070 data points (68.89%) excluded in total
5450 valid data points (31.11%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 113 data points (0.64%) set to NA
LE: 111 data points (0.63%) set to NA
NEE: 668 data points (3.81%) set to NA
-------------------------------------------------------------------
Data filtering:
11328 data points (64.66%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11328 data points (64.66%) excluded in total
6192 valid data points (35.34%) remaining.

New sEddyProc class for site 'CA-DBB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-DBB-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 41 data points (0.23%) set to NA
LE: 43 data points (0.24%) set to NA
NEE: 223 data points (1.27%) set to NA
-------------------------------------------------------------------
Data filtering:
9408 data points (53.55%) excluded by growing season filter
2469 additional data points (14.05%) excluded by precipitation filter (7715
 data points = 43.92 % in total)
11877 data points (67.61%) excluded in total
5691 valid data points (32.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 41 data points (0.23%) set to NA
LE: 43 data points (0.24%) set to NA
NEE: 223 data points (1.27%) set to NA
-------------------------------------------------------------------
Data filtering:
9408 data points (53.55%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9408 data points (53.55%) excluded in total
8160 valid data points (46.45%) remaining.

New sEddyProc class for site 'CA-DBB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-DBB-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[30/329] Processing: CA-DSM

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-DSM | Years: 2021, 2022, 2023, 2024
Quality control:
TA: 11663 data points (66.57%) set to NA
H: 11808 data points (67.4%) set to NA
LE: 11823 data points (67.48%) set to NA
NEE: 12120 data points (69.18%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7970 additional data points (45.49%) excluded by precipitation filter (7970
 data points = 45.49 % in total)
7970 data points (45.49%) excluded in total
9550 valid data points (54.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 11663 data points (66.57%) set to NA
H: 11808 data points (67.4%) set to NA
LE: 11823 data points (67.48%) set to NA
NEE: 12120 data points (69.18%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-DSM'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 65.54.

Regression of reference temperature R_ref for 5 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 15 data points (0.09%) set to NA
LE: 16 data points (0.09%) set to NA
NEE: 363 data points (2.07%) set to NA
-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
2035 additional data points (11.62%) excluded by precipitation filter (6200
 data points = 35.39 % in total)
11155 data points (63.67%) excluded in total
6365 valid data points (36.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 15 data points (0.09%) set to NA
LE: 16 data points (0.09%) set to NA
NEE: 363 data points (2.07%) set to NA
-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9120 data points (52.05%) excluded in total
8400 valid data points (47.95%) remaining.

New sEddyProc class for site 'CA-DSM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-DSM-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 40 data points (0.23%) set to NA
LE: 41 data points (0.23%) set to NA
NEE: 206 data points (1.18%) set to NA
-------------------------------------------------------------------
Data filtering:
10752 data points (61.37%) excluded by growing season filter
988 additional data points (5.64%) excluded by precipitation filter (6697
 data points = 38.22 % in total)
11740 data points (67.01%) excluded in total
5780 valid data points (32.99%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 40 data points (0.23%) set to NA
LE: 41 data points (0.23%) set to NA
NEE: 206 data points (1.18%) set to NA
-------------------------------------------------------------------
Data filtering:
10752 data points (61.37%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10752 data points (61.37%) excluded in total
6768 valid data points (38.63%) remaining.

New sEddyProc class for site 'CA-DSM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-DSM-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 46 data points (0.26%) set to NA
LE: 49 data points (0.28%) set to NA
NEE: 285 data points (1.62%) set to NA
-------------------------------------------------------------------
Data filtering:
10032 data points (57.1%) excluded by growing season filter
2075 additional data points (11.81%) excluded by precipitation filter (7601
 data points = 43.27 % in total)
12107 data points (68.92%) excluded in total
5461 valid data points (31.08%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 46 data points (0.26%) set to NA
LE: 49 data points (0.28%) set to NA
NEE: 285 data points (1.62%) set to NA
-------------------------------------------------------------------
Data filtering:
10032 data points (57.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10032 data points (57.1%) excluded in total
7536 valid data points (42.9%) remaining.

New sEddyProc class for site 'CA-DSM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-DSM-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[31/329] Processing: CA-EM1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-EM1 | Years: 2021, 2022, 2023
Quality control:
TA: 5512 data points (31.46%) set to NA
H: 7975 data points (45.52%) set to NA
LE: 8010 data points (45.72%) set to NA
NEE: 8048 data points (45.94%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 109”

-------------------------------------------------------------------
Data filtering:
12768 data points (72.88%) excluded by growing season filter
1245 additional data points (7.11%) excluded by precipitation filter (2846
 data points = 16.24 % in total)
14013 data points (79.98%) excluded in total
3507 valid data points (20.02%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5512 data points (31.46%) set to NA
H: 7975 data points (45.52%) set to NA
LE: 8010 data points (45.72%) set to NA
NEE: 8048 data points (45.94%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 109”

-------------------------------------------------------------------
Data filtering:
12768 data points (72.88%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12768 data points (72.88%) excluded in total
4752 valid data points (27.12%) remaining.

New sEddyProc class for site 'CA-EM1'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 133.56.

Regression of reference temperature R_ref for 6 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 403 data points (2.3%) set to NA
LE: 414 data points (2.36%) set to NA
NEE: 634 data points (3.62%) set to NA
-------------------------------------------------------------------
Data filtering:
12816 data points (73.15%) excluded by growing season filter
1507 additional data points (8.6%) excluded by precipitation filter (3465
 data points = 19.78 % in total)
14323 data points (81.75%) excluded in total
3197 valid data points (18.25%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 403 data points (2.3%) set to NA
LE: 414 data points (2.36%) set to NA
NEE: 634 data points (3.62%) set to NA
-------------------------------------------------------------------
Data filtering:
12816 data points (73.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12816 data points (73.15%) excluded in total
4704 valid data points (26.85%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -53, -52 ...”
New sEddyProc class for site 'CA-EM1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -53, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-EM1-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 198 data points (1.13%) set to NA
H: 626 data points (3.57%) set to NA
LE: 638 data points (3.64%) set to NA
NEE: 943 data points (5.38%) set to NA
-------------------------------------------------------------------
Data filtering:
12672 data points (72.33%) excluded by growing season filter
1558 additional data points (8.89%) excluded by precipitation filter (2922
 data points = 16.68 % in total)
14230 data points (81.22%) excluded in total
3290 valid data points (18.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 198 data points (1.13%) set to NA
H: 626 data points (3.57%) set to NA
LE: 638 data points (3.64%) set to NA
NEE: 943 data points (5.38%) set to NA
-------------------------------------------------------------------
Data filtering:
12672 data points (72.33%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12672 data points (72.33%) excluded in total
4848 valid data points (27.67%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -64, -55, -71 ...”
New sEddyProc class for site 'CA-EM1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -64, -55, -71 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-EM1-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[32/329] Processing: CA-EM2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-EM2 | Years: 2021, 2022, 2023
Quality control:
TA: 5510 data points (31.45%) set to NA
H: 5614 data points (32.04%) set to NA
LE: 5614 data points (32.04%) set to NA
NEE: 5865 data points (33.48%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 102”

-------------------------------------------------------------------
Data filtering:
12720 data points (72.6%) excluded by growing season filter
1253 additional data points (7.15%) excluded by precipitation filter (2530
 data points = 14.44 % in total)
13973 data points (79.75%) excluded in total
3547 valid data points (20.25%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5510 data points (31.45%) set to NA
H: 5614 data points (32.04%) set to NA
LE: 5614 data points (32.04%) set to NA
NEE: 5865 data points (33.48%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 102”

-------------------------------------------------------------------
Data filtering:
12720 data points (72.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12720 data points (72.6%) excluded in total
4800 valid data points (27.4%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
New sEddyProc class for site 'CA-EM2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 10 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-EM2-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 424 data points (2.42%) set to NA
LE: 478 data points (2.73%) set to NA
NEE: 693 data points (3.96%) set to NA
-------------------------------------------------------------------
Data filtering:
13104 data points (74.79%) excluded by growing season filter
1258 additional data points (7.18%) excluded by precipitation filter (2777
 data points = 15.85 % in total)
14362 data points (81.97%) excluded in total
3158 valid data points (18.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 424 data points (2.42%) set to NA
LE: 478 data points (2.73%) set to NA
NEE: 693 data points (3.96%) set to NA
-------------------------------------------------------------------
Data filtering:
13104 data points (74.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13104 data points (74.79%) excluded in total
4416 valid data points (25.21%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -58 ...”
New sEddyProc class for site 'CA-EM2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -58 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-EM2-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 504 data points (2.88%) set to NA
LE: 562 data points (3.21%) set to NA
NEE: 849 data points (4.85%) set to NA
-------------------------------------------------------------------
Data filtering:
12192 data points (69.59%) excluded by growing season filter
1352 additional data points (7.72%) excluded by precipitation filter (2416
 data points = 13.79 % in total)
13544 data points (77.31%) excluded in total
3976 valid data points (22.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 504 data points (2.88%) set to NA
LE: 562 data points (3.21%) set to NA
NEE: 849 data points (4.85%) set to NA
-------------------------------------------------------------------
Data filtering:
12192 data points (69.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12192 data points (69.59%) excluded in total
5328 valid data points (30.41%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
New sEddyProc class for site 'CA-EM2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-EM2-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[33/329] Processing: CA-HPC

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-HPC | Years: 2018
Quality control:
TA: 21 data points (0.12%) set to NA
H: 6967 data points (39.77%) set to NA
LE: 6977 data points (39.82%) set to NA
NEE: 7060 data points (40.3%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 123”

-------------------------------------------------------------------
Data filtering:
6912 data points (39.45%) excluded by growing season filter
6477 additional data points (36.97%) excluded by precipitation filter (9675
 data points = 55.22 % in total)
13389 data points (76.42%) excluded in total
4131 valid data points (23.58%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 21 data points (0.12%) set to NA
H: 6967 data points (39.77%) set to NA
LE: 6977 data points (39.82%) set to NA
NEE: 7060 data points (40.3%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 123”

-------------------------------------------------------------------
Data filtering:
6912 data points (39.45%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6912 data points (39.45%) excluded in total
10608 valid data points (60.55%) remaining.

New sEddyProc class for site 'CA-HPC'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-HPC-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[34/329] Processing: CA-KLP

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-KLP | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 36 data points (0.21%) set to NA
H: 4519 data points (25.79%) set to NA
LE: 4533 data points (25.87%) set to NA
NEE: 4893 data points (27.93%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
2831 additional data points (16.16%) excluded by precipitation filter (5782
 data points = 33 % in total)
13487 data points (76.98%) excluded in total
4033 valid data points (23.02%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 36 data points (0.21%) set to NA
H: 4519 data points (25.79%) set to NA
LE: 4533 data points (25.87%) set to NA
NEE: 4893 data points (27.93%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10656 data points (60.82%) excluded in total
6864 valid data points (39.18%) remaining.

New sEddyProc class for site 'CA-KLP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-KLP-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 6507 data points (37.14%) set to NA
LE: 6499 data points (37.09%) set to NA
NEE: 7048 data points (40.23%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 46”

-------------------------------------------------------------------
Data filtering:
9552 data points (54.52%) excluded by growing season filter
2749 additional data points (15.69%) excluded by precipitation filter (5188
 data points = 29.61 % in total)
12301 data points (70.21%) excluded in total
5219 valid data points (29.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 6507 data points (37.14%) set to NA
LE: 6499 data points (37.09%) set to NA
NEE: 7048 data points (40.23%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 46”

-------------------------------------------------------------------
Data filtering:
9552 data points (54.52%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9552 data points (54.52%) excluded in total
7968 valid data points (45.48%) remaining.

New sEddyProc class for site 'CA-KLP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-KLP-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6 data points (0.03%) set to NA
H: 9088 data points (51.87%) set to NA
LE: 9034 data points (51.56%) set to NA
NEE: 9210 data points (52.57%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 46”

-------------------------------------------------------------------
Data filtering:
8448 data points (48.22%) excluded by growing season filter
3524 additional data points (20.11%) excluded by precipitation filter (6002
 data points = 34.26 % in total)
11972 data points (68.33%) excluded in total
5548 valid data points (31.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6 data points (0.03%) set to NA
H: 9088 data points (51.87%) set to NA
LE: 9034 data points (51.56%) set to NA
NEE: 9210 data points (52.57%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 46”

-------------------------------------------------------------------
Data filtering:
8448 data points (48.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8448 data points (48.22%) excluded in total
9072 valid data points (51.78%) remaining.

New sEddyProc class for site 'CA-KLP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-KLP-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 6042 data points (34.39%) set to NA
LE: 6028 data points (34.31%) set to NA
NEE: 6320 data points (35.97%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 59”

-------------------------------------------------------------------
Data filtering:
11616 data points (66.12%) excluded by growing season filter
2776 additional data points (15.8%) excluded by precipitation filter (6209
 data points = 35.34 % in total)
14392 data points (81.92%) excluded in total
3176 valid data points (18.08%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 6042 data points (34.39%) set to NA
LE: 6028 data points (34.31%) set to NA
NEE: 6320 data points (35.97%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 59”

-------------------------------------------------------------------
Data filtering:
11616 data points (66.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11616 data points (66.12%) excluded in total
5952 valid data points (33.88%) remaining.

New sEddyProc class for site 'CA-KLP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-KLP-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[35/329] Processing: CA-LP1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-LP1 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 2405 data points (13.73%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5786 additional data points (33.03%) excluded by precipitation filter (5786
 data points = 33.03 % in total)
5786 data points (33.03%) excluded in total
11734 valid data points (66.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2405 data points (13.73%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-LP1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-LP1-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 837 data points (4.78%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4137 additional data points (23.61%) excluded by precipitation filter (4137
 data points = 23.61 % in total)
4137 data points (23.61%) excluded in total
13383 valid data points (76.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 837 data points (4.78%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-LP1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-LP1-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 155 data points (0.88%) set to NA
LE: 1266 data points (7.23%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5097 additional data points (29.09%) excluded by precipitation filter (5097
 data points = 29.09 % in total)
5097 data points (29.09%) excluded in total
12423 valid data points (70.91%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 155 data points (0.88%) set to NA
LE: 1266 data points (7.23%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-LP1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-LP1-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 32 data points (0.18%) set to NA
LE: 1282 data points (7.3%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5837 additional data points (33.23%) excluded by precipitation filter (5837
 data points = 33.23 % in total)
5837 data points (33.23%) excluded in total
11731 valid data points (66.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 32 data points (0.18%) set to NA
LE: 1282 data points (7.3%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'CA-LP1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-LP1-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 7446 data points (42.5%) set to NA
LE: 7508 data points (42.85%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6321 additional data points (36.08%) excluded by precipitation filter (6321
 data points = 36.08 % in total)
6321 data points (36.08%) excluded in total
11199 valid data points (63.92%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 7446 data points (42.5%) set to NA
LE: 7508 data points (42.85%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-LP1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-LP1-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 579 data points (3.3%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5874 additional data points (33.53%) excluded by precipitation filter (5874
 data points = 33.53 % in total)
5874 data points (33.53%) excluded in total
11646 valid data points (66.47%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 579 data points (3.3%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-LP1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-LP1-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 9 data points (0.05%) set to NA
LE: 321 data points (1.83%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5342 additional data points (30.49%) excluded by precipitation filter (5342
 data points = 30.49 % in total)
5342 data points (30.49%) excluded in total
12178 valid data points (69.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 9 data points (0.05%) set to NA
LE: 321 data points (1.83%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-LP1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-LP1-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 518 data points (2.95%) set to NA
LE: 974 data points (5.54%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5799 additional data points (33.01%) excluded by precipitation filter (5799
 data points = 33.01 % in total)
5799 data points (33.01%) excluded in total
11769 valid data points (66.99%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 518 data points (2.95%) set to NA
LE: 974 data points (5.54%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'CA-LP1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-LP1-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[36/329] Processing: CA-LU1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-LU1 | Years: 2020, 2021, 2022, 2023
Quality control:
TA: 0 data points (0%) set to NA
H: 13566 data points (77.22%) set to NA
LE: 13563 data points (77.2%) set to NA
NEE: 13728 data points (78.14%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6100 additional data points (34.72%) excluded by precipitation filter (6100
 data points = 34.72 % in total)
6100 data points (34.72%) excluded in total
11468 valid data points (65.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 13566 data points (77.22%) set to NA
LE: 13563 data points (77.2%) set to NA
NEE: 13728 data points (78.14%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'CA-LU1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-LU1-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3918 data points (22.36%) set to NA
H: 4628 data points (26.42%) set to NA
LE: 4636 data points (26.46%) set to NA
NEE: 5122 data points (29.24%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 35”

-------------------------------------------------------------------
Data filtering:
11616 data points (66.3%) excluded by growing season filter
1876 additional data points (10.71%) excluded by precipitation filter (4625
 data points = 26.4 % in total)
13492 data points (77.01%) excluded in total
4028 valid data points (22.99%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3918 data points (22.36%) set to NA
H: 4628 data points (26.42%) set to NA
LE: 4636 data points (26.46%) set to NA
NEE: 5122 data points (29.24%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 35”

-------------------------------------------------------------------
Data filtering:
11616 data points (66.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11616 data points (66.3%) excluded in total
5904 valid data points (33.7%) remaining.

New sEddyProc class for site 'CA-LU1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 21 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-LU1-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 247 data points (1.41%) set to NA
H: 985 data points (5.62%) set to NA
LE: 991 data points (5.66%) set to NA
NEE: 1663 data points (9.49%) set to NA
-------------------------------------------------------------------
Data filtering:
11904 data points (67.95%) excluded by growing season filter
1646 additional data points (9.39%) excluded by precipitation filter (4716
 data points = 26.92 % in total)
13550 data points (77.34%) excluded in total
3970 valid data points (22.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 247 data points (1.41%) set to NA
H: 985 data points (5.62%) set to NA
LE: 991 data points (5.66%) set to NA
NEE: 1663 data points (9.49%) set to NA
-------------------------------------------------------------------
Data filtering:
11904 data points (67.95%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11904 data points (67.95%) excluded in total
5616 valid data points (32.05%) remaining.

New sEddyProc class for site 'CA-LU1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-LU1-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 10707 data points (61.11%) set to NA
LE: 10746 data points (61.34%) set to NA
NEE: 11116 data points (63.45%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4043 additional data points (23.08%) excluded by precipitation filter (4043
 data points = 23.08 % in total)
4043 data points (23.08%) excluded in total
13477 valid data points (76.92%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 10707 data points (61.11%) set to NA
LE: 10746 data points (61.34%) set to NA
NEE: 11116 data points (63.45%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-LU1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-LU1-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[37/329] Processing: CA-LU2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-LU2 | Years: 2020, 2021, 2022, 2023
Quality control:
TA: 0 data points (0%) set to NA
H: 16747 data points (95.33%) set to NA
LE: 16746 data points (95.32%) set to NA
NEE: 16746 data points (95.32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6060 additional data points (34.49%) excluded by precipitation filter (6060
 data points = 34.49 % in total)
6060 data points (34.49%) excluded in total
11508 valid data points (65.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 16747 data points (95.33%) set to NA
LE: 16746 data points (95.32%) set to NA
NEE: 16746 data points (95.32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'CA-LU2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-LU2-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4878 data points (27.84%) set to NA
H: 8422 data points (48.07%) set to NA
LE: 9509 data points (54.28%) set to NA
NEE: 9974 data points (56.93%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 131”

-------------------------------------------------------------------
Data filtering:
4944 data points (28.22%) excluded by growing season filter
3382 additional data points (19.3%) excluded by precipitation filter (4571
 data points = 26.09 % in total)
8326 data points (47.52%) excluded in total
9194 valid data points (52.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4878 data points (27.84%) set to NA
H: 8422 data points (48.07%) set to NA
LE: 9509 data points (54.28%) set to NA
NEE: 9974 data points (56.93%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 131”

-------------------------------------------------------------------
Data filtering:
4944 data points (28.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4944 data points (28.22%) excluded in total
12576 valid data points (71.78%) remaining.

New sEddyProc class for site 'CA-LU2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 193.86.

Regression of reference temperature R_ref for 2 periods.

Quality control:
TA: 259 data points (1.48%) set to NA
H: 1321 data points (7.54%) set to NA
LE: 3971 data points (22.67%) set to NA
NEE: 4152 data points (23.7%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 34”

-------------------------------------------------------------------
Data filtering:
11904 data points (67.95%) excluded by growing season filter
1686 additional data points (9.62%) excluded by precipitation filter (4455
 data points = 25.43 % in total)
13590 data points (77.57%) excluded in total
3930 valid data points (22.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 259 data points (1.48%) set to NA
H: 1321 data points (7.54%) set to NA
LE: 3971 data points (22.67%) set to NA
NEE: 4152 data points (23.7%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 34”

-------------------------------------------------------------------
Data filtering:
11904 data points (67.95%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11904 data points (67.95%) excluded in total
5616 valid data points (32.05%) remaining.

New sEddyProc class for site 'CA-LU2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-LU2-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 5018 data points (28.64%) set to NA
LE: 5822 data points (33.23%) set to NA
NEE: 6132 data points (35%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 59”

-------------------------------------------------------------------
Data filtering:
11424 data points (65.21%) excluded by growing season filter
1335 additional data points (7.62%) excluded by precipitation filter (3885
 data points = 22.17 % in total)
12759 data points (72.83%) excluded in total
4761 valid data points (27.17%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5018 data points (28.64%) set to NA
LE: 5822 data points (33.23%) set to NA
NEE: 6132 data points (35%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 59”

-------------------------------------------------------------------
Data filtering:
11424 data points (65.21%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11424 data points (65.21%) excluded in total
6096 valid data points (34.79%) remaining.

New sEddyProc class for site 'CA-LU2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-LU2-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[38/329] Processing: CA-Mer

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-Mer | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 0 data points (0%) set to NA
H: 47 data points (0.27%) set to NA
LE: 91 data points (0.52%) set to NA
NEE: 906 data points (5.17%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.89%) excluded by growing season filter
3460 additional data points (19.75%) excluded by precipitation filter (8326
 data points = 47.52 % in total)
13252 data points (75.64%) excluded in total
4268 valid data points (24.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 47 data points (0.27%) set to NA
LE: 91 data points (0.52%) set to NA
NEE: 906 data points (5.17%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9792 data points (55.89%) excluded in total
7728 valid data points (44.11%) remaining.

New sEddyProc class for site 'CA-Mer'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-Mer-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 169 data points (0.96%) set to NA
H: 279 data points (1.59%) set to NA
LE: 292 data points (1.67%) set to NA
NEE: 989 data points (5.64%) set to NA
-------------------------------------------------------------------
Data filtering:
9888 data points (56.44%) excluded by growing season filter
3351 additional data points (19.13%) excluded by precipitation filter (8261
 data points = 47.15 % in total)
13239 data points (75.57%) excluded in total
4281 valid data points (24.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 169 data points (0.96%) set to NA
H: 279 data points (1.59%) set to NA
LE: 292 data points (1.67%) set to NA
NEE: 989 data points (5.64%) set to NA
-------------------------------------------------------------------
Data filtering:
9888 data points (56.44%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9888 data points (56.44%) excluded in total
7632 valid data points (43.56%) remaining.

New sEddyProc class for site 'CA-Mer'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-Mer-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1308 data points (7.47%) set to NA
H: 378 data points (2.16%) set to NA
LE: 449 data points (2.56%) set to NA
NEE: 1645 data points (9.39%) set to NA
-------------------------------------------------------------------
Data filtering:
9408 data points (53.7%) excluded by growing season filter
3186 additional data points (18.18%) excluded by precipitation filter (8230
 data points = 46.97 % in total)
12594 data points (71.88%) excluded in total
4926 valid data points (28.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1308 data points (7.47%) set to NA
H: 378 data points (2.16%) set to NA
LE: 449 data points (2.56%) set to NA
NEE: 1645 data points (9.39%) set to NA
-------------------------------------------------------------------
Data filtering:
9408 data points (53.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9408 data points (53.7%) excluded in total
8112 valid data points (46.3%) remaining.

New sEddyProc class for site 'CA-Mer'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 106.75.

Regression of reference temperature R_ref for 15 periods.

Quality control:
TA: 293 data points (1.67%) set to NA
H: 253 data points (1.44%) set to NA
LE: 400 data points (2.28%) set to NA
NEE: 1279 data points (7.28%) set to NA
-------------------------------------------------------------------
Data filtering:
9888 data points (56.28%) excluded by growing season filter
3492 additional data points (19.88%) excluded by precipitation filter (8087
 data points = 46.03 % in total)
13380 data points (76.16%) excluded in total
4188 valid data points (23.84%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 293 data points (1.67%) set to NA
H: 253 data points (1.44%) set to NA
LE: 400 data points (2.28%) set to NA
NEE: 1279 data points (7.28%) set to NA
-------------------------------------------------------------------
Data filtering:
9888 data points (56.28%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9888 data points (56.28%) excluded in total
7680 valid data points (43.72%) remaining.

New sEddyProc class for site 'CA-Mer'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 105.85.

Regression of reference temperature R_ref for 5 periods.

[39/329] Processing: CA-PB1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-PB1 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 17519 data points (99.99%) set to NA
H: 6940 data points (39.61%) set to NA
LE: 6954 data points (39.69%) set to NA
NEE: 7019 data points (40.06%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5998 additional data points (34.24%) excluded by precipitation filter (5998
 data points = 34.24 % in total)
5998 data points (34.24%) excluded in total
11522 valid data points (65.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 17519 data points (99.99%) set to NA
H: 6940 data points (39.61%) set to NA
LE: 6954 data points (39.69%) set to NA
NEE: 7019 data points (40.06%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-PB1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 16 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-PB1-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 14435 data points (82.39%) set to NA
H: 15948 data points (91.03%) set to NA
LE: 15947 data points (91.02%) set to NA
NEE: 15961 data points (91.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
982 additional data points (5.61%) excluded by precipitation filter (982
 data points = 5.61 % in total)
982 data points (5.61%) excluded in total
16538 valid data points (94.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 14435 data points (82.39%) set to NA
H: 15948 data points (91.03%) set to NA
LE: 15947 data points (91.02%) set to NA
NEE: 15961 data points (91.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-PB1'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 73.01.

Regression of reference temperature R_ref for 7 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 3910 data points (22.32%) set to NA
LE: 3903 data points (22.28%) set to NA
NEE: 4360 data points (24.89%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 21”

-------------------------------------------------------------------
Data filtering:
12624 data points (72.05%) excluded by growing season filter
2379 additional data points (13.58%) excluded by precipitation filter (5420
 data points = 30.94 % in total)
15003 data points (85.63%) excluded in total
2517 valid data points (14.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 3910 data points (22.32%) set to NA
LE: 3903 data points (22.28%) set to NA
NEE: 4360 data points (24.89%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 21”

-------------------------------------------------------------------
Data filtering:
12624 data points (72.05%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12624 data points (72.05%) excluded in total
4896 valid data points (27.95%) remaining.

New sEddyProc class for site 'CA-PB1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-PB1-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 16746 data points (95.32%) set to NA
LE: 16747 data points (95.33%) set to NA
NEE: 16752 data points (95.36%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5811 additional data points (33.08%) excluded by precipitation filter (5811
 data points = 33.08 % in total)
5811 data points (33.08%) excluded in total
11757 valid data points (66.92%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (8) for CA-PB1-2020”

Quality control:
TA: 11938 data points (68.14%) set to NA
H: 13631 data points (77.8%) set to NA
LE: 13667 data points (78.01%) set to NA
NEE: 13657 data points (77.95%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6584 additional data points (37.58%) excluded by precipitation filter (6584
 data points = 37.58 % in total)
6584 data points (37.58%) excluded in total
10936 valid data points (62.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11938 data points (68.14%) set to NA
H: 13631 data points (77.8%) set to NA
LE: 13667 data points (78.01%) set to NA
NEE: 13657 data points (77.95%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-PB1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-PB1-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3 data points (0.02%) set to NA
H: 6760 data points (38.58%) set to NA
LE: 6811 data points (38.88%) set to NA
NEE: 6803 data points (38.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 62”

-------------------------------------------------------------------
Data filtering:
12240 data points (69.86%) excluded by growing season filter
2208 additional data points (12.6%) excluded by precipitation filter (5589
 data points = 31.9 % in total)
14448 data points (82.47%) excluded in total
3072 valid data points (17.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3 data points (0.02%) set to NA
H: 6760 data points (38.58%) set to NA
LE: 6811 data points (38.88%) set to NA
NEE: 6803 data points (38.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 62”

-------------------------------------------------------------------
Data filtering:
12240 data points (69.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12240 data points (69.86%) excluded in total
5280 valid data points (30.14%) remaining.

New sEddyProc class for site 'CA-PB1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-PB1-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 15379 data points (87.78%) set to NA
LE: 15316 data points (87.42%) set to NA
NEE: 15634 data points (89.24%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5761 additional data points (32.88%) excluded by precipitation filter (5761
 data points = 32.88 % in total)
5761 data points (32.88%) excluded in total
11759 valid data points (67.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 15379 data points (87.78%) set to NA
LE: 15316 data points (87.42%) set to NA
NEE: 15634 data points (89.24%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-PB1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-PB1-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1051 data points (5.98%) set to NA
H: 4918 data points (27.99%) set to NA
LE: 5099 data points (29.02%) set to NA
NEE: 5321 data points (30.29%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 43”

-------------------------------------------------------------------
Data filtering:
12000 data points (68.31%) excluded by growing season filter
2299 additional data points (13.09%) excluded by precipitation filter (6287
 data points = 35.79 % in total)
14299 data points (81.39%) excluded in total
3269 valid data points (18.61%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.

Warning message in nlrob(Gs ~ g0 + DwDc * (1 + g1/sqrt(VPD)) * GPP/Ca, data = df, :
“failed to converge in 20 steps”

Quality control:
TA: 1051 data points (5.98%) set to NA
H: 4918 data points (27.99%) set to NA
LE: 5099 data points (29.02%) set to NA
NEE: 5321 data points (30.29%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 43”

-------------------------------------------------------------------
Data filtering:
12000 data points (68.31%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12000 data points (68.31%) excluded in total
5568 valid data points (31.69%) remaining.

New sEddyProc class for site 'CA-PB1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-PB1-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[40/329] Processing: CA-PB2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-PB2 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 12422 data points (70.9%) set to NA
H: 13243 data points (75.59%) set to NA
LE: 13244 data points (75.59%) set to NA
NEE: 13273 data points (75.76%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6034 additional data points (34.44%) excluded by precipitation filter (6034
 data points = 34.44 % in total)
6034 data points (34.44%) excluded in total
11486 valid data points (65.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12422 data points (70.9%) set to NA
H: 13243 data points (75.59%) set to NA
LE: 13244 data points (75.59%) set to NA
NEE: 13273 data points (75.76%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-PB2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-PB2-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2838 data points (16.2%) set to NA
LE: 2879 data points (16.43%) set to NA
NEE: 3140 data points (17.92%) set to NA
-------------------------------------------------------------------
Data filtering:
13200 data points (75.34%) excluded by growing season filter
2274 additional data points (12.98%) excluded by precipitation filter (5903
 data points = 33.69 % in total)
15474 data points (88.32%) excluded in total
2046 valid data points (11.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2838 data points (16.2%) set to NA
LE: 2879 data points (16.43%) set to NA
NEE: 3140 data points (17.92%) set to NA
-------------------------------------------------------------------
Data filtering:
13200 data points (75.34%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13200 data points (75.34%) excluded in total
4320 valid data points (24.66%) remaining.

New sEddyProc class for site 'CA-PB2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-PB2-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 4074 data points (23.25%) set to NA
LE: 4074 data points (23.25%) set to NA
NEE: 4168 data points (23.79%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 21”

-------------------------------------------------------------------
Data filtering:
13056 data points (74.52%) excluded by growing season filter
2288 additional data points (13.06%) excluded by precipitation filter (5746
 data points = 32.8 % in total)
15344 data points (87.58%) excluded in total
2176 valid data points (12.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 4074 data points (23.25%) set to NA
LE: 4074 data points (23.25%) set to NA
NEE: 4168 data points (23.79%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 21”

-------------------------------------------------------------------
Data filtering:
13056 data points (74.52%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13056 data points (74.52%) excluded in total
4464 valid data points (25.48%) remaining.

New sEddyProc class for site 'CA-PB2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-PB2-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 10497 data points (59.75%) set to NA
H: 16688 data points (94.99%) set to NA
LE: 16691 data points (95.01%) set to NA
NEE: 16695 data points (95.03%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6467 additional data points (36.81%) excluded by precipitation filter (6467
 data points = 36.81 % in total)
6467 data points (36.81%) excluded in total
11101 valid data points (63.19%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (8) for CA-PB2-2020”

Quality control:
TA: 12854 data points (73.37%) set to NA
H: 13148 data points (75.05%) set to NA
LE: 13152 data points (75.07%) set to NA
NEE: 13235 data points (75.54%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7026 additional data points (40.1%) excluded by precipitation filter (7026
 data points = 40.1 % in total)
7026 data points (40.1%) excluded in total
10494 valid data points (59.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12854 data points (73.37%) set to NA
H: 13148 data points (75.05%) set to NA
LE: 13152 data points (75.07%) set to NA
NEE: 13235 data points (75.54%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-PB2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-PB2-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 6598 data points (37.66%) set to NA
LE: 6602 data points (37.68%) set to NA
NEE: 6909 data points (39.43%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 63”

-------------------------------------------------------------------
Data filtering:
12384 data points (70.68%) excluded by growing season filter
2092 additional data points (11.94%) excluded by precipitation filter (5963
 data points = 34.04 % in total)
14476 data points (82.63%) excluded in total
3044 valid data points (17.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 6598 data points (37.66%) set to NA
LE: 6602 data points (37.68%) set to NA
NEE: 6909 data points (39.43%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 63”

-------------------------------------------------------------------
Data filtering:
12384 data points (70.68%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12384 data points (70.68%) excluded in total
5136 valid data points (29.32%) remaining.

New sEddyProc class for site 'CA-PB2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-PB2-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 8325 data points (47.52%) set to NA
LE: 8297 data points (47.36%) set to NA
NEE: 10862 data points (62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 141”

-------------------------------------------------------------------
Data filtering:
6672 data points (38.08%) excluded by growing season filter
4210 additional data points (24.03%) excluded by precipitation filter (6375
 data points = 36.39 % in total)
10882 data points (62.11%) excluded in total
6638 valid data points (37.89%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 8325 data points (47.52%) set to NA
LE: 8297 data points (47.36%) set to NA
NEE: 10862 data points (62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 141”

-------------------------------------------------------------------
Data filtering:
6672 data points (38.08%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6672 data points (38.08%) excluded in total
10848 valid data points (61.92%) remaining.

New sEddyProc class for site 'CA-PB2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-PB2-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 5070 data points (28.86%) set to NA
LE: 5069 data points (28.85%) set to NA
NEE: 5186 data points (29.52%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 43”

-------------------------------------------------------------------
Data filtering:
12144 data points (69.13%) excluded by growing season filter
2473 additional data points (14.08%) excluded by precipitation filter (6702
 data points = 38.15 % in total)
14617 data points (83.2%) excluded in total
2951 valid data points (16.8%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5070 data points (28.86%) set to NA
LE: 5069 data points (28.85%) set to NA
NEE: 5186 data points (29.52%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 43”

-------------------------------------------------------------------
Data filtering:
12144 data points (69.13%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12144 data points (69.13%) excluded in total
5424 valid data points (30.87%) remaining.

New sEddyProc class for site 'CA-PB2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-PB2-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[41/329] Processing: CA-RBM

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-RBM | Years: 2022, 2023, 2024
Quality control:
TA: 6924 data points (39.52%) set to NA
H: 7463 data points (42.6%) set to NA
LE: 7464 data points (42.6%) set to NA
NEE: 7539 data points (43.03%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 139”

-------------------------------------------------------------------
Data filtering:
4272 data points (24.38%) excluded by growing season filter
4343 additional data points (24.79%) excluded by precipitation filter (6012
 data points = 34.32 % in total)
8615 data points (49.17%) excluded in total
8905 valid data points (50.83%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 6924 data points (39.52%) set to NA
H: 7463 data points (42.6%) set to NA
LE: 7464 data points (42.6%) set to NA
NEE: 7539 data points (43.03%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 139”

-------------------------------------------------------------------
Data filtering:
4272 data points (24.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4272 data points (24.38%) excluded in total
13248 valid data points (75.62%) remaining.

New sEddyProc class for site 'CA-RBM'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 117.56.

Regression of reference temperature R_ref for 4 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 7 data points (0.04%) set to NA
NEE: 75 data points (0.43%) set to NA
-------------------------------------------------------------------
Data filtering:
11664 data points (66.58%) excluded by growing season filter
613 additional data points (3.5%) excluded by precipitation filter (5949
 data points = 33.96 % in total)
12277 data points (70.07%) excluded in total
5243 valid data points (29.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 7 data points (0.04%) set to NA
NEE: 75 data points (0.43%) set to NA
-------------------------------------------------------------------
Data filtering:
11664 data points (66.58%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11664 data points (66.58%) excluded in total
5856 valid data points (33.42%) remaining.

New sEddyProc class for site 'CA-RBM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-RBM-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 12 data points (0.07%) set to NA
LE: 7 data points (0.04%) set to NA
NEE: 211 data points (1.2%) set to NA
-------------------------------------------------------------------
Data filtering:
11568 data points (65.85%) excluded by growing season filter
1440 additional data points (8.2%) excluded by precipitation filter (7069
 data points = 40.24 % in total)
13008 data points (74.04%) excluded in total
4560 valid data points (25.96%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 12 data points (0.07%) set to NA
LE: 7 data points (0.04%) set to NA
NEE: 211 data points (1.2%) set to NA
-------------------------------------------------------------------
Data filtering:
11568 data points (65.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11568 data points (65.85%) excluded in total
6000 valid data points (34.15%) remaining.

New sEddyProc class for site 'CA-RBM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-RBM-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[42/329] Processing: CA-SCB

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-SCB | Years: 2017, 2018, 2019
Quality control:
TA: 4203 data points (23.99%) set to NA
H: 6183 data points (35.29%) set to NA
LE: 6184 data points (35.3%) set to NA
NEE: 6355 data points (36.27%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 91”

-------------------------------------------------------------------
Data filtering:
6960 data points (39.73%) excluded by growing season filter
2074 additional data points (11.84%) excluded by precipitation filter (3439
 data points = 19.63 % in total)
9034 data points (51.56%) excluded in total
8486 valid data points (48.44%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4203 data points (23.99%) set to NA
H: 6183 data points (35.29%) set to NA
LE: 6184 data points (35.3%) set to NA
NEE: 6355 data points (36.27%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 91”

-------------------------------------------------------------------
Data filtering:
6960 data points (39.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6960 data points (39.73%) excluded in total
10560 valid data points (60.27%) remaining.

New sEddyProc class for site 'CA-SCB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 14 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-SCB-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1647 data points (9.4%) set to NA
H: 8018 data points (45.76%) set to NA
LE: 8034 data points (45.86%) set to NA
NEE: 8090 data points (46.18%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 80”

-------------------------------------------------------------------
Data filtering:
7776 data points (44.38%) excluded by growing season filter
2412 additional data points (13.77%) excluded by precipitation filter (3229
 data points = 18.43 % in total)
10188 data points (58.15%) excluded in total
7332 valid data points (41.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1647 data points (9.4%) set to NA
H: 8018 data points (45.76%) set to NA
LE: 8034 data points (45.86%) set to NA
NEE: 8090 data points (46.18%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 80”

-------------------------------------------------------------------
Data filtering:
7776 data points (44.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7776 data points (44.38%) excluded in total
9744 valid data points (55.62%) remaining.

New sEddyProc class for site 'CA-SCB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 14 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-SCB-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 5322 data points (30.38%) set to NA
H: 10647 data points (60.77%) set to NA
LE: 10673 data points (60.92%) set to NA
NEE: 10666 data points (60.88%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 146”

-------------------------------------------------------------------
Data filtering:
4272 data points (24.38%) excluded by growing season filter
3465 additional data points (19.78%) excluded by precipitation filter (4052
 data points = 23.13 % in total)
7737 data points (44.16%) excluded in total
9783 valid data points (55.84%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5322 data points (30.38%) set to NA
H: 10647 data points (60.77%) set to NA
LE: 10673 data points (60.92%) set to NA
NEE: 10666 data points (60.88%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 146”

-------------------------------------------------------------------
Data filtering:
4272 data points (24.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4272 data points (24.38%) excluded in total
13248 valid data points (75.62%) remaining.

New sEddyProc class for site 'CA-SCB'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 62.54.

Regression of reference temperature R_ref for 11 periods.

[43/329] Processing: CA-SCC

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-SCC | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 1650 data points (9.42%) set to NA
H: 1677 data points (9.57%) set to NA
LE: 1693 data points (9.66%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2916 additional data points (16.64%) excluded by precipitation filter (2916
 data points = 16.64 % in total)
2916 data points (16.64%) excluded in total
14604 valid data points (83.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1650 data points (9.42%) set to NA
H: 1677 data points (9.57%) set to NA
LE: 1693 data points (9.66%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-SCC'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-SCC-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1021 data points (5.83%) set to NA
LE: 1302 data points (7.43%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2972 additional data points (16.96%) excluded by precipitation filter (2972
 data points = 16.96 % in total)
2972 data points (16.96%) excluded in total
14548 valid data points (83.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1021 data points (5.83%) set to NA
LE: 1302 data points (7.43%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-SCC'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-SCC-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4844 data points (27.65%) set to NA
H: 8542 data points (48.76%) set to NA
LE: 8541 data points (48.75%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3583 additional data points (20.45%) excluded by precipitation filter (3583
 data points = 20.45 % in total)
3583 data points (20.45%) excluded in total
13937 valid data points (79.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4844 data points (27.65%) set to NA
H: 8542 data points (48.76%) set to NA
LE: 8541 data points (48.75%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-SCC'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-SCC-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 17568 data points (100%) set to NA
H: 17568 data points (100%) set to NA
LE: 17568 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4040 additional data points (23%) excluded by precipitation filter (4040
 data points = 23 % in total)
4040 data points (23%) excluded in total
13528 valid data points (77%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for CA-SCC-2020”

Quality control:
TA: 17520 data points (100%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3934 additional data points (22.45%) excluded by precipitation filter (3934
 data points = 22.45 % in total)
3934 data points (22.45%) excluded in total
13586 valid data points (77.55%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for CA-SCC-2021”

Quality control:
TA: 17520 data points (100%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3214 additional data points (18.34%) excluded by precipitation filter (3214
 data points = 18.34 % in total)
3214 data points (18.34%) excluded in total
14306 valid data points (81.66%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for CA-SCC-2022”

Quality control:
TA: 3593 data points (20.51%) set to NA
H: 3632 data points (20.73%) set to NA
LE: 3655 data points (20.86%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2378 additional data points (13.57%) excluded by precipitation filter (2378
 data points = 13.57 % in total)
2378 data points (13.57%) excluded in total
15142 valid data points (86.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3593 data points (20.51%) set to NA
H: 3632 data points (20.73%) set to NA
LE: 3655 data points (20.86%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CA-SCC'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-SCC-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 10377 data points (59.07%) set to NA
H: 11930 data points (67.91%) set to NA
LE: 11947 data points (68%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2738 additional data points (15.59%) excluded by precipitation filter (2738
 data points = 15.59 % in total)
2738 data points (15.59%) excluded in total
14830 valid data points (84.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10377 data points (59.07%) set to NA
H: 11930 data points (67.91%) set to NA
LE: 11947 data points (68%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'CA-SCC'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-SCC-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[44/329] Processing: CA-SMC

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-SMC | Years: 2018
Quality control:
TA: 4638 data points (26.47%) set to NA
H: 4751 data points (27.12%) set to NA
LE: 6814 data points (38.89%) set to NA
NEE: 6957 data points (39.71%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 115”

-------------------------------------------------------------------
Data filtering:
6000 data points (34.25%) excluded by growing season filter
5830 additional data points (33.28%) excluded by precipitation filter (8192
 data points = 46.76 % in total)
11830 data points (67.52%) excluded in total
5690 valid data points (32.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4638 data points (26.47%) set to NA
H: 4751 data points (27.12%) set to NA
LE: 6814 data points (38.89%) set to NA
NEE: 6957 data points (39.71%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 115”

-------------------------------------------------------------------
Data filtering:
6000 data points (34.25%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6000 data points (34.25%) excluded in total
11520 valid data points (65.75%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -62 ...”
New sEddyProc class for site 'CA-SMC'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -62 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-SMC-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[45/329] Processing: CA-TP1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-TP1 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023
Quality control:
TA: 0 data points (0%) set to NA
H: 80 data points (0.46%) set to NA
LE: 49 data points (0.28%) set to NA
NEE: 1801 data points (10.28%) set to NA
-------------------------------------------------------------------
Data filtering:
7488 data points (42.74%) excluded by growing season filter
1247 additional data points (7.12%) excluded by precipitation filter (2308
 data points = 13.17 % in total)
8735 data points (49.86%) excluded in total
8785 valid data points (50.14%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 80 data points (0.46%) set to NA
LE: 49 data points (0.28%) set to NA
NEE: 1801 data points (10.28%) set to NA
-------------------------------------------------------------------
Data filtering:
7488 data points (42.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7488 data points (42.74%) excluded in total
10032 valid data points (57.26%) remaining.

New sEddyProc class for site 'CA-TP1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TP1-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 63 data points (0.36%) set to NA
H: 28 data points (0.16%) set to NA
LE: 24 data points (0.14%) set to NA
NEE: 2034 data points (11.61%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.15%) excluded by growing season filter
1347 additional data points (7.69%) excluded by precipitation filter (4265
 data points = 24.34 % in total)
10659 data points (60.84%) excluded in total
6861 valid data points (39.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 63 data points (0.36%) set to NA
H: 28 data points (0.16%) set to NA
LE: 24 data points (0.14%) set to NA
NEE: 2034 data points (11.61%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9312 data points (53.15%) excluded in total
8208 valid data points (46.85%) remaining.

New sEddyProc class for site 'CA-TP1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TP1-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1890 data points (10.79%) set to NA
H: 1528 data points (8.72%) set to NA
LE: 1511 data points (8.62%) set to NA
NEE: 4194 data points (23.94%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.85%) excluded by growing season filter
2948 additional data points (16.83%) excluded by precipitation filter (5009
 data points = 28.59 % in total)
11156 data points (63.68%) excluded in total
6364 valid data points (36.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1890 data points (10.79%) set to NA
H: 1528 data points (8.72%) set to NA
LE: 1511 data points (8.62%) set to NA
NEE: 4194 data points (23.94%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8208 data points (46.85%) excluded in total
9312 valid data points (53.15%) remaining.

New sEddyProc class for site 'CA-TP1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 8 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TP1-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 14 data points (0.08%) set to NA
H: 2637 data points (15.01%) set to NA
LE: 2641 data points (15.03%) set to NA
NEE: 4268 data points (24.29%) set to NA
-------------------------------------------------------------------
Data filtering:
7776 data points (44.26%) excluded by growing season filter
1910 additional data points (10.87%) excluded by precipitation filter (3528
 data points = 20.08 % in total)
9686 data points (55.13%) excluded in total
7882 valid data points (44.87%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 14 data points (0.08%) set to NA
H: 2637 data points (15.01%) set to NA
LE: 2641 data points (15.03%) set to NA
NEE: 4268 data points (24.29%) set to NA
-------------------------------------------------------------------
Data filtering:
7776 data points (44.26%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7776 data points (44.26%) excluded in total
9792 valid data points (55.74%) remaining.

New sEddyProc class for site 'CA-TP1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TP1-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 20 data points (0.11%) set to NA
H: 2290 data points (13.07%) set to NA
LE: 2290 data points (13.07%) set to NA
NEE: 3595 data points (20.52%) set to NA
-------------------------------------------------------------------
Data filtering:
6480 data points (36.99%) excluded by growing season filter
3001 additional data points (17.13%) excluded by precipitation filter (4001
 data points = 22.84 % in total)
9481 data points (54.12%) excluded in total
8039 valid data points (45.88%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 20 data points (0.11%) set to NA
H: 2290 data points (13.07%) set to NA
LE: 2290 data points (13.07%) set to NA
NEE: 3595 data points (20.52%) set to NA
-------------------------------------------------------------------
Data filtering:
6480 data points (36.99%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6480 data points (36.99%) excluded in total
11040 valid data points (63.01%) remaining.

New sEddyProc class for site 'CA-TP1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TP1-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 290 data points (1.66%) set to NA
LE: 279 data points (1.59%) set to NA
NEE: 1791 data points (10.22%) set to NA
-------------------------------------------------------------------
Data filtering:
7392 data points (42.19%) excluded by growing season filter
1359 additional data points (7.76%) excluded by precipitation filter (1823
 data points = 10.41 % in total)
8751 data points (49.95%) excluded in total
8769 valid data points (50.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 290 data points (1.66%) set to NA
LE: 279 data points (1.59%) set to NA
NEE: 1791 data points (10.22%) set to NA
-------------------------------------------------------------------
Data filtering:
7392 data points (42.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7392 data points (42.19%) excluded in total
10128 valid data points (57.81%) remaining.

New sEddyProc class for site 'CA-TP1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TP1-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 62 data points (0.35%) set to NA
LE: 64 data points (0.37%) set to NA
NEE: 1432 data points (8.17%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.67%) excluded by growing season filter
699 additional data points (3.99%) excluded by precipitation filter (2642
 data points = 15.08 % in total)
9051 data points (51.66%) excluded in total
8469 valid data points (48.34%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 62 data points (0.35%) set to NA
LE: 64 data points (0.37%) set to NA
NEE: 1432 data points (8.17%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8352 data points (47.67%) excluded in total
9168 valid data points (52.33%) remaining.

New sEddyProc class for site 'CA-TP1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TP1-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[46/329] Processing: CA-TP3

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-TP3 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023
Quality control:
TA: 0 data points (0%) set to NA
H: 40 data points (0.23%) set to NA
LE: 28 data points (0.16%) set to NA
NEE: 287 data points (1.64%) set to NA
-------------------------------------------------------------------
Data filtering:
7296 data points (41.64%) excluded by growing season filter
3663 additional data points (20.91%) excluded by precipitation filter (8190
 data points = 46.75 % in total)
10959 data points (62.55%) excluded in total
6561 valid data points (37.45%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 40 data points (0.23%) set to NA
LE: 28 data points (0.16%) set to NA
NEE: 287 data points (1.64%) set to NA
-------------------------------------------------------------------
Data filtering:
7296 data points (41.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7296 data points (41.64%) excluded in total
10224 valid data points (58.36%) remaining.

New sEddyProc class for site 'CA-TP3'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TP3-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1056 data points (6.03%) set to NA
LE: 964 data points (5.5%) set to NA
NEE: 2234 data points (12.75%) set to NA
-------------------------------------------------------------------
Data filtering:
8592 data points (49.04%) excluded by growing season filter
8372 additional data points (47.79%) excluded by precipitation filter (14033
 data points = 80.1 % in total)
16964 data points (96.83%) excluded in total
556 valid data points (3.17%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1056 data points (6.03%) set to NA
LE: 964 data points (5.5%) set to NA
NEE: 2234 data points (12.75%) set to NA
-------------------------------------------------------------------
Data filtering:
8592 data points (49.04%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8592 data points (49.04%) excluded in total
8928 valid data points (50.96%) remaining.

New sEddyProc class for site 'CA-TP3'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TP3-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1002 data points (5.72%) set to NA
LE: 1013 data points (5.78%) set to NA
NEE: 1169 data points (6.67%) set to NA
-------------------------------------------------------------------
Data filtering:
8592 data points (49.04%) excluded by growing season filter
7057 additional data points (40.28%) excluded by precipitation filter (13491
 data points = 77 % in total)
15649 data points (89.32%) excluded in total
1871 valid data points (10.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1002 data points (5.72%) set to NA
LE: 1013 data points (5.78%) set to NA
NEE: 1169 data points (6.67%) set to NA
-------------------------------------------------------------------
Data filtering:
8592 data points (49.04%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8592 data points (49.04%) excluded in total
8928 valid data points (50.96%) remaining.

New sEddyProc class for site 'CA-TP3'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TP3-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 64 data points (0.36%) set to NA
LE: 65 data points (0.37%) set to NA
NEE: 299 data points (1.7%) set to NA
-------------------------------------------------------------------
Data filtering:
7776 data points (44.26%) excluded by growing season filter
7877 additional data points (44.84%) excluded by precipitation filter (12936
 data points = 73.63 % in total)
15653 data points (89.1%) excluded in total
1915 valid data points (10.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 64 data points (0.36%) set to NA
LE: 65 data points (0.37%) set to NA
NEE: 299 data points (1.7%) set to NA
-------------------------------------------------------------------
Data filtering:
7776 data points (44.26%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7776 data points (44.26%) excluded in total
9792 valid data points (55.74%) remaining.

New sEddyProc class for site 'CA-TP3'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TP3-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 360 data points (2.05%) set to NA
LE: 366 data points (2.09%) set to NA
NEE: 651 data points (3.72%) set to NA
-------------------------------------------------------------------
Data filtering:
7488 data points (42.74%) excluded by growing season filter
3800 additional data points (21.69%) excluded by precipitation filter (7552
 data points = 43.11 % in total)
11288 data points (64.43%) excluded in total
6232 valid data points (35.57%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 360 data points (2.05%) set to NA
LE: 366 data points (2.09%) set to NA
NEE: 651 data points (3.72%) set to NA
-------------------------------------------------------------------
Data filtering:
7488 data points (42.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7488 data points (42.74%) excluded in total
10032 valid data points (57.26%) remaining.

New sEddyProc class for site 'CA-TP3'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TP3-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 8 data points (0.05%) set to NA
H: 61 data points (0.35%) set to NA
LE: 50 data points (0.29%) set to NA
NEE: 245 data points (1.4%) set to NA
-------------------------------------------------------------------
Data filtering:
7440 data points (42.47%) excluded by growing season filter
9114 additional data points (52.02%) excluded by precipitation filter (12220
 data points = 69.75 % in total)
16554 data points (94.49%) excluded in total
966 valid data points (5.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8 data points (0.05%) set to NA
H: 61 data points (0.35%) set to NA
LE: 50 data points (0.29%) set to NA
NEE: 245 data points (1.4%) set to NA
-------------------------------------------------------------------
Data filtering:
7440 data points (42.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7440 data points (42.47%) excluded in total
10080 valid data points (57.53%) remaining.

New sEddyProc class for site 'CA-TP3'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TP3-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 44 data points (0.25%) set to NA
H: 80 data points (0.46%) set to NA
LE: 73 data points (0.42%) set to NA
NEE: 172 data points (0.98%) set to NA
-------------------------------------------------------------------
Data filtering:
7152 data points (40.82%) excluded by growing season filter
9326 additional data points (53.23%) excluded by precipitation filter (13970
 data points = 79.74 % in total)
16478 data points (94.05%) excluded in total
1042 valid data points (5.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 44 data points (0.25%) set to NA
H: 80 data points (0.46%) set to NA
LE: 73 data points (0.42%) set to NA
NEE: 172 data points (0.98%) set to NA
-------------------------------------------------------------------
Data filtering:
7152 data points (40.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7152 data points (40.82%) excluded in total
10368 valid data points (59.18%) remaining.

New sEddyProc class for site 'CA-TP3'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TP3-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[47/329] Processing: CA-TPD

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CA-TPD | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023
Quality control:
TA: 110 data points (0.63%) set to NA
H: 67 data points (0.38%) set to NA
LE: 69 data points (0.39%) set to NA
NEE: 802 data points (4.58%) set to NA
-------------------------------------------------------------------
Data filtering:
10320 data points (58.9%) excluded by growing season filter
2602 additional data points (14.85%) excluded by precipitation filter (7213
 data points = 41.17 % in total)
12922 data points (73.76%) excluded in total
4598 valid data points (26.24%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 110 data points (0.63%) set to NA
H: 67 data points (0.38%) set to NA
LE: 69 data points (0.39%) set to NA
NEE: 802 data points (4.58%) set to NA
-------------------------------------------------------------------
Data filtering:
10320 data points (58.9%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10320 data points (58.9%) excluded in total
7200 valid data points (41.1%) remaining.

New sEddyProc class for site 'CA-TPD'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TPD-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2017 data points (11.51%) set to NA
H: 176 data points (1%) set to NA
LE: 167 data points (0.95%) set to NA
NEE: 1435 data points (8.19%) set to NA
-------------------------------------------------------------------
Data filtering:
10128 data points (57.81%) excluded by growing season filter
2954 additional data points (16.86%) excluded by precipitation filter (7843
 data points = 44.77 % in total)
13082 data points (74.67%) excluded in total
4438 valid data points (25.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2017 data points (11.51%) set to NA
H: 176 data points (1%) set to NA
LE: 167 data points (0.95%) set to NA
NEE: 1435 data points (8.19%) set to NA
-------------------------------------------------------------------
Data filtering:
10128 data points (57.81%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10128 data points (57.81%) excluded in total
7392 valid data points (42.19%) remaining.

New sEddyProc class for site 'CA-TPD'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 251.09.

Regression of reference temperature R_ref for 13 periods.

Quality control:
TA: 256 data points (1.46%) set to NA
H: 1999 data points (11.41%) set to NA
LE: 1997 data points (11.4%) set to NA
NEE: 2533 data points (14.46%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.73%) excluded by growing season filter
3336 additional data points (19.04%) excluded by precipitation filter (8810
 data points = 50.29 % in total)
13800 data points (78.77%) excluded in total
3720 valid data points (21.23%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 256 data points (1.46%) set to NA
H: 1999 data points (11.41%) set to NA
LE: 1997 data points (11.4%) set to NA
NEE: 2533 data points (14.46%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10464 data points (59.73%) excluded in total
7056 valid data points (40.27%) remaining.

New sEddyProc class for site 'CA-TPD'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TPD-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 292 data points (1.66%) set to NA
H: 273 data points (1.55%) set to NA
LE: 270 data points (1.54%) set to NA
NEE: 904 data points (5.15%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.11%) excluded by growing season filter
2324 additional data points (13.23%) excluded by precipitation filter (8100
 data points = 46.11 % in total)
12884 data points (73.34%) excluded in total
4684 valid data points (26.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 292 data points (1.66%) set to NA
H: 273 data points (1.55%) set to NA
LE: 270 data points (1.54%) set to NA
NEE: 904 data points (5.15%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10560 data points (60.11%) excluded in total
7008 valid data points (39.89%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -51 ...”
New sEddyProc class for site 'CA-TPD'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 224.35.

Regression of reference temperature R_ref for 3 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 8 data points (0.05%) set to NA
LE: 7 data points (0.04%) set to NA
NEE: 573 data points (3.27%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.16%) excluded by growing season filter
3089 additional data points (17.63%) excluded by precipitation filter (7776
 data points = 44.38 % in total)
12929 data points (73.8%) excluded in total
4591 valid data points (26.2%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 8 data points (0.05%) set to NA
LE: 7 data points (0.04%) set to NA
NEE: 573 data points (3.27%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9840 data points (56.16%) excluded in total
7680 valid data points (43.84%) remaining.

New sEddyProc class for site 'CA-TPD'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TPD-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 10 data points (0.06%) set to NA
H: 225 data points (1.28%) set to NA
LE: 231 data points (1.32%) set to NA
NEE: 932 data points (5.32%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
2564 additional data points (14.63%) excluded by precipitation filter (7516
 data points = 42.9 % in total)
12788 data points (72.99%) excluded in total
4732 valid data points (27.01%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10 data points (0.06%) set to NA
H: 225 data points (1.28%) set to NA
LE: 231 data points (1.32%) set to NA
NEE: 932 data points (5.32%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10224 data points (58.36%) excluded in total
7296 valid data points (41.64%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -72 ...”
New sEddyProc class for site 'CA-TPD'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -72 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TPD-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 735 data points (4.2%) set to NA
LE: 638 data points (3.64%) set to NA
NEE: 8369 data points (47.77%) set to NA
-------------------------------------------------------------------
Data filtering:
10176 data points (58.08%) excluded by growing season filter
2317 additional data points (13.22%) excluded by precipitation filter (7464
 data points = 42.6 % in total)
12493 data points (71.31%) excluded in total
5027 valid data points (28.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 735 data points (4.2%) set to NA
LE: 638 data points (3.64%) set to NA
NEE: 8369 data points (47.77%) set to NA
-------------------------------------------------------------------
Data filtering:
10176 data points (58.08%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10176 data points (58.08%) excluded in total
7344 valid data points (41.92%) remaining.

New sEddyProc class for site 'CA-TPD'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CA-TPD-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[48/329] Processing: CD-Ygb

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CD-Ygb | Years: 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 13250 data points (75.42%) set to NA
H: 13484 data points (76.75%) set to NA
LE: 13585 data points (77.33%) set to NA
NEE: 13551 data points (77.13%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
14087 additional data points (80.19%) excluded by precipitation filter (14087
 data points = 80.19 % in total)
14087 data points (80.19%) excluded in total
3481 valid data points (19.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 13250 data points (75.42%) set to NA
H: 13484 data points (76.75%) set to NA
LE: 13585 data points (77.33%) set to NA
NEE: 13551 data points (77.13%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -61 ...”
New sEddyProc class for site 'CD-Ygb'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -61 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CD-Ygb-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3388 data points (19.34%) set to NA
H: 11197 data points (63.91%) set to NA
LE: 11290 data points (64.44%) set to NA
NEE: 11870 data points (67.75%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10195 additional data points (58.19%) excluded by precipitation filter (10195
 data points = 58.19 % in total)
10195 data points (58.19%) excluded in total
7325 valid data points (41.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3388 data points (19.34%) set to NA
H: 11197 data points (63.91%) set to NA
LE: 11290 data points (64.44%) set to NA
NEE: 11870 data points (67.75%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -63 ...”
New sEddyProc class for site 'CD-Ygb'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -63 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CD-Ygb-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1854 data points (10.58%) set to NA
H: 3112 data points (17.76%) set to NA
LE: 3100 data points (17.69%) set to NA
NEE: 3171 data points (18.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8105 additional data points (46.26%) excluded by precipitation filter (8105
 data points = 46.26 % in total)
8105 data points (46.26%) excluded in total
9415 valid data points (53.74%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1854 data points (10.58%) set to NA
H: 3112 data points (17.76%) set to NA
LE: 3100 data points (17.69%) set to NA
NEE: 3171 data points (18.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
New sEddyProc class for site 'CD-Ygb'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 79.39.

Regression of reference temperature R_ref for 20 periods.

Quality control:
TA: 5023 data points (28.67%) set to NA
H: 1864 data points (10.64%) set to NA
LE: 1951 data points (11.14%) set to NA
NEE: 2399 data points (13.69%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9355 additional data points (53.4%) excluded by precipitation filter (9355
 data points = 53.4 % in total)
9355 data points (53.4%) excluded in total
8165 valid data points (46.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5023 data points (28.67%) set to NA
H: 1864 data points (10.64%) set to NA
LE: 1951 data points (11.14%) set to NA
NEE: 2399 data points (13.69%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -50, -59, -58 ...”
New sEddyProc class for site 'CD-Ygb'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -50, -59, -58 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CD-Ygb-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 789 data points (4.49%) set to NA
H: 996 data points (5.67%) set to NA
LE: 1113 data points (6.34%) set to NA
NEE: 1573 data points (8.95%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7637 additional data points (43.47%) excluded by precipitation filter (7637
 data points = 43.47 % in total)
7637 data points (43.47%) excluded in total
9931 valid data points (56.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 789 data points (4.49%) set to NA
H: 996 data points (5.67%) set to NA
LE: 1113 data points (6.34%) set to NA
NEE: 1573 data points (8.95%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -54, -58, -53, -72, -62, -62, -50 ...”
New sEddyProc class for site 'CD-Ygb'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -54, -58, -53, -72, -62, -62, -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CD-Ygb-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[49/329] Processing: CH-Dav

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CH-Dav | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 29 data points (0.17%) set to NA
LE: 14 data points (0.08%) set to NA
NEE: 572 data points (3.26%) set to NA
-------------------------------------------------------------------
Data filtering:
8400 data points (47.95%) excluded by growing season filter
4315 additional data points (24.63%) excluded by precipitation filter (7285
 data points = 41.58 % in total)
12715 data points (72.57%) excluded in total
4805 valid data points (27.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 29 data points (0.17%) set to NA
LE: 14 data points (0.08%) set to NA
NEE: 572 data points (3.26%) set to NA
-------------------------------------------------------------------
Data filtering:
8400 data points (47.95%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8400 data points (47.95%) excluded in total
9120 valid data points (52.05%) remaining.

New sEddyProc class for site 'CH-Dav'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CH-Dav-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 83 data points (0.47%) set to NA
LE: 2166 data points (12.36%) set to NA
NEE: 2753 data points (15.71%) set to NA
-------------------------------------------------------------------
Data filtering:
6528 data points (37.26%) excluded by growing season filter
4416 additional data points (25.21%) excluded by precipitation filter (6908
 data points = 39.43 % in total)
10944 data points (62.47%) excluded in total
6576 valid data points (37.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 83 data points (0.47%) set to NA
LE: 2166 data points (12.36%) set to NA
NEE: 2753 data points (15.71%) set to NA
-------------------------------------------------------------------
Data filtering:
6528 data points (37.26%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6528 data points (37.26%) excluded in total
10992 valid data points (62.74%) remaining.

New sEddyProc class for site 'CH-Dav'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CH-Dav-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 57 data points (0.33%) set to NA
H: 27 data points (0.15%) set to NA
LE: 25 data points (0.14%) set to NA
NEE: 395 data points (2.25%) set to NA
-------------------------------------------------------------------
Data filtering:
7728 data points (44.11%) excluded by growing season filter
4311 additional data points (24.61%) excluded by precipitation filter (7420
 data points = 42.35 % in total)
12039 data points (68.72%) excluded in total
5481 valid data points (31.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 57 data points (0.33%) set to NA
H: 27 data points (0.15%) set to NA
LE: 25 data points (0.14%) set to NA
NEE: 395 data points (2.25%) set to NA
-------------------------------------------------------------------
Data filtering:
7728 data points (44.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7728 data points (44.11%) excluded in total
9792 valid data points (55.89%) remaining.

New sEddyProc class for site 'CH-Dav'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CH-Dav-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1055 data points (6.01%) set to NA
H: 156 data points (0.89%) set to NA
LE: 127 data points (0.72%) set to NA
NEE: 613 data points (3.49%) set to NA
-------------------------------------------------------------------
Data filtering:
7008 data points (39.89%) excluded by growing season filter
4898 additional data points (27.88%) excluded by precipitation filter (7297
 data points = 41.54 % in total)
11906 data points (67.77%) excluded in total
5662 valid data points (32.23%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1055 data points (6.01%) set to NA
H: 156 data points (0.89%) set to NA
LE: 127 data points (0.72%) set to NA
NEE: 613 data points (3.49%) set to NA
-------------------------------------------------------------------
Data filtering:
7008 data points (39.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7008 data points (39.89%) excluded in total
10560 valid data points (60.11%) remaining.

New sEddyProc class for site 'CH-Dav'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CH-Dav-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 78 data points (0.45%) set to NA
H: 273 data points (1.56%) set to NA
LE: 253 data points (1.44%) set to NA
NEE: 929 data points (5.3%) set to NA
-------------------------------------------------------------------
Data filtering:
7632 data points (43.56%) excluded by growing season filter
4506 additional data points (25.72%) excluded by precipitation filter (7310
 data points = 41.72 % in total)
12138 data points (69.28%) excluded in total
5382 valid data points (30.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 78 data points (0.45%) set to NA
H: 273 data points (1.56%) set to NA
LE: 253 data points (1.44%) set to NA
NEE: 929 data points (5.3%) set to NA
-------------------------------------------------------------------
Data filtering:
7632 data points (43.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7632 data points (43.56%) excluded in total
9888 valid data points (56.44%) remaining.

New sEddyProc class for site 'CH-Dav'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CH-Dav-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 154 data points (0.88%) set to NA
LE: 136 data points (0.78%) set to NA
NEE: 570 data points (3.25%) set to NA
-------------------------------------------------------------------
Data filtering:
7296 data points (41.64%) excluded by growing season filter
4658 additional data points (26.59%) excluded by precipitation filter (6953
 data points = 39.69 % in total)
11954 data points (68.23%) excluded in total
5566 valid data points (31.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 154 data points (0.88%) set to NA
LE: 136 data points (0.78%) set to NA
NEE: 570 data points (3.25%) set to NA
-------------------------------------------------------------------
Data filtering:
7296 data points (41.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7296 data points (41.64%) excluded in total
10224 valid data points (58.36%) remaining.

New sEddyProc class for site 'CH-Dav'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CH-Dav-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 150 data points (0.86%) set to NA
H: 392 data points (2.24%) set to NA
LE: 352 data points (2.01%) set to NA
NEE: 884 data points (5.05%) set to NA
-------------------------------------------------------------------
Data filtering:
7632 data points (43.56%) excluded by growing season filter
4568 additional data points (26.07%) excluded by precipitation filter (7960
 data points = 45.43 % in total)
12200 data points (69.63%) excluded in total
5320 valid data points (30.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 150 data points (0.86%) set to NA
H: 392 data points (2.24%) set to NA
LE: 352 data points (2.01%) set to NA
NEE: 884 data points (5.05%) set to NA
-------------------------------------------------------------------
Data filtering:
7632 data points (43.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7632 data points (43.56%) excluded in total
9888 valid data points (56.44%) remaining.

New sEddyProc class for site 'CH-Dav'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CH-Dav-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 154 data points (0.88%) set to NA
LE: 149 data points (0.85%) set to NA
NEE: 811 data points (4.62%) set to NA
-------------------------------------------------------------------
Data filtering:
6672 data points (37.98%) excluded by growing season filter
5411 additional data points (30.8%) excluded by precipitation filter (8040
 data points = 45.77 % in total)
12083 data points (68.78%) excluded in total
5485 valid data points (31.22%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 154 data points (0.88%) set to NA
LE: 149 data points (0.85%) set to NA
NEE: 811 data points (4.62%) set to NA
-------------------------------------------------------------------
Data filtering:
6672 data points (37.98%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6672 data points (37.98%) excluded in total
10896 valid data points (62.02%) remaining.

New sEddyProc class for site 'CH-Dav'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CH-Dav-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[50/329] Processing: CH-Lae

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CH-Lae | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 101 data points (0.58%) set to NA
LE: 105 data points (0.6%) set to NA
NEE: 2132 data points (12.17%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
3786 additional data points (21.61%) excluded by precipitation filter (7281
 data points = 41.56 % in total)
13146 data points (75.03%) excluded in total
4374 valid data points (24.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 101 data points (0.58%) set to NA
LE: 105 data points (0.6%) set to NA
NEE: 2132 data points (12.17%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9360 data points (53.42%) excluded in total
8160 valid data points (46.58%) remaining.

New sEddyProc class for site 'CH-Lae'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CH-Lae-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 20 data points (0.11%) set to NA
LE: 741 data points (4.23%) set to NA
NEE: 2175 data points (12.41%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.67%) excluded by growing season filter
2827 additional data points (16.14%) excluded by precipitation filter (6381
 data points = 36.42 % in total)
11179 data points (63.81%) excluded in total
6341 valid data points (36.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 20 data points (0.11%) set to NA
LE: 741 data points (4.23%) set to NA
NEE: 2175 data points (12.41%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8352 data points (47.67%) excluded in total
9168 valid data points (52.33%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -59 ...”
New sEddyProc class for site 'CH-Lae'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CH-Lae-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 740 data points (4.22%) set to NA
H: 58 data points (0.33%) set to NA
LE: 86 data points (0.49%) set to NA
NEE: 2279 data points (13.01%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.85%) excluded by growing season filter
3885 additional data points (22.17%) excluded by precipitation filter (7716
 data points = 44.04 % in total)
12093 data points (69.02%) excluded in total
5427 valid data points (30.98%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 740 data points (4.22%) set to NA
H: 58 data points (0.33%) set to NA
LE: 86 data points (0.49%) set to NA
NEE: 2279 data points (13.01%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8208 data points (46.85%) excluded in total
9312 valid data points (53.15%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 6 cases! Invalid values with 'NEE < -50': -64, -58, -56, -59, -60, -55 ...”
New sEddyProc class for site 'CH-Lae'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 6 cases! Invalid values with 'NEE < -50': -64, -58, -56, -59, -60, -55 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CH-Lae-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 22 data points (0.13%) set to NA
LE: 311 data points (1.77%) set to NA
NEE: 2516 data points (14.32%) set to NA
-------------------------------------------------------------------
Data filtering:
7296 data points (41.53%) excluded by growing season filter
3642 additional data points (20.73%) excluded by precipitation filter (6885
 data points = 39.19 % in total)
10938 data points (62.26%) excluded in total
6630 valid data points (37.74%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 22 data points (0.13%) set to NA
LE: 311 data points (1.77%) set to NA
NEE: 2516 data points (14.32%) set to NA
-------------------------------------------------------------------
Data filtering:
7296 data points (41.53%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7296 data points (41.53%) excluded in total
10272 valid data points (58.47%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -73 ...”
New sEddyProc class for site 'CH-Lae'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -73 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CH-Lae-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 730 data points (4.17%) set to NA
LE: 1277 data points (7.29%) set to NA
NEE: 3717 data points (21.22%) set to NA
-------------------------------------------------------------------
Data filtering:
9168 data points (52.33%) excluded by growing season filter
3804 additional data points (21.71%) excluded by precipitation filter (7303
 data points = 41.68 % in total)
12972 data points (74.04%) excluded in total
4548 valid data points (25.96%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 730 data points (4.17%) set to NA
LE: 1277 data points (7.29%) set to NA
NEE: 3717 data points (21.22%) set to NA
-------------------------------------------------------------------
Data filtering:
9168 data points (52.33%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9168 data points (52.33%) excluded in total
8352 valid data points (47.67%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -56 ...”
New sEddyProc class for site 'CH-Lae'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CH-Lae-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1543 data points (8.81%) set to NA
LE: 1534 data points (8.76%) set to NA
NEE: 3344 data points (19.09%) set to NA
-------------------------------------------------------------------
Data filtering:
7872 data points (44.93%) excluded by growing season filter
3661 additional data points (20.9%) excluded by precipitation filter (7054
 data points = 40.26 % in total)
11533 data points (65.83%) excluded in total
5987 valid data points (34.17%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1543 data points (8.81%) set to NA
LE: 1534 data points (8.76%) set to NA
NEE: 3344 data points (19.09%) set to NA
-------------------------------------------------------------------
Data filtering:
7872 data points (44.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7872 data points (44.93%) excluded in total
9648 valid data points (55.07%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -51, -52 ...”
New sEddyProc class for site 'CH-Lae'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -51, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CH-Lae-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3 data points (0.02%) set to NA
H: 55 data points (0.31%) set to NA
LE: 57 data points (0.33%) set to NA
NEE: 1878 data points (10.72%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
3051 additional data points (17.41%) excluded by precipitation filter (8229
 data points = 46.97 % in total)
12267 data points (70.02%) excluded in total
5253 valid data points (29.98%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3 data points (0.02%) set to NA
H: 55 data points (0.31%) set to NA
LE: 57 data points (0.33%) set to NA
NEE: 1878 data points (10.72%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9216 data points (52.6%) excluded in total
8304 valid data points (47.4%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -57, -62 ...”
New sEddyProc class for site 'CH-Lae'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -57, -62 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CH-Lae-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 65 data points (0.37%) set to NA
H: 119 data points (0.68%) set to NA
LE: 117 data points (0.67%) set to NA
NEE: 2144 data points (12.2%) set to NA
-------------------------------------------------------------------
Data filtering:
9408 data points (53.55%) excluded by growing season filter
4329 additional data points (24.64%) excluded by precipitation filter (8581
 data points = 48.84 % in total)
13737 data points (78.19%) excluded in total
3831 valid data points (21.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 65 data points (0.37%) set to NA
H: 119 data points (0.68%) set to NA
LE: 117 data points (0.67%) set to NA
NEE: 2144 data points (12.2%) set to NA
-------------------------------------------------------------------
Data filtering:
9408 data points (53.55%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9408 data points (53.55%) excluded in total
8160 valid data points (46.45%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -53, -53, -53, -52 ...”
New sEddyProc class for site 'CH-Lae'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -53, -53, -53, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CH-Lae-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[51/329] Processing: CL-ACF

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CL-ACF | Years: 2018, 2019, 2020
Quality control:
TA: 1412 data points (8.06%) set to NA
H: 2296 data points (13.11%) set to NA
LE: 2296 data points (13.11%) set to NA
NEE: 3726 data points (21.27%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 21”

-------------------------------------------------------------------
Data filtering:
1200 data points (6.85%) excluded by growing season filter
8151 additional data points (46.52%) excluded by precipitation filter (9015
 data points = 51.46 % in total)
9351 data points (53.37%) excluded in total
8169 valid data points (46.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1412 data points (8.06%) set to NA
H: 2296 data points (13.11%) set to NA
LE: 2296 data points (13.11%) set to NA
NEE: 3726 data points (21.27%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 21”

-------------------------------------------------------------------
Data filtering:
1200 data points (6.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1200 data points (6.85%) excluded in total
16320 valid data points (93.15%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -58 ...”
New sEddyProc class for site 'CL-ACF'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -58 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CL-ACF-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 747 data points (4.26%) set to NA
LE: 1075 data points (6.14%) set to NA
NEE: 2598 data points (14.83%) set to NA
-------------------------------------------------------------------
Data filtering:
3264 data points (18.63%) excluded by growing season filter
5948 additional data points (33.95%) excluded by precipitation filter (8204
 data points = 46.83 % in total)
9212 data points (52.58%) excluded in total
8308 valid data points (47.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 747 data points (4.26%) set to NA
LE: 1075 data points (6.14%) set to NA
NEE: 2598 data points (14.83%) set to NA
-------------------------------------------------------------------
Data filtering:
3264 data points (18.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3264 data points (18.63%) excluded in total
14256 valid data points (81.37%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -53, -68, -63, -66, -66, -66, -67 ...”
New sEddyProc class for site 'CL-ACF'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -53, -68, -63, -66, -66, -66, -67 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CL-ACF-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 295 data points (1.68%) set to NA
LE: 1859 data points (10.58%) set to NA
NEE: 4693 data points (26.71%) set to NA
-------------------------------------------------------------------
Data filtering:
2112 data points (12.02%) excluded by growing season filter
7014 additional data points (39.92%) excluded by precipitation filter (8601
 data points = 48.96 % in total)
9126 data points (51.95%) excluded in total
8442 valid data points (48.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 295 data points (1.68%) set to NA
LE: 1859 data points (10.58%) set to NA
NEE: 4693 data points (26.71%) set to NA
-------------------------------------------------------------------
Data filtering:
2112 data points (12.02%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2112 data points (12.02%) excluded in total
15456 valid data points (87.98%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -64 ...”
New sEddyProc class for site 'CL-ACF'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -64 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CL-ACF-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[52/329] Processing: CL-SDF

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CL-SDF | Years: 2017, 2018, 2019, 2020, 2021
Quality control:
TA: 5246 data points (29.94%) set to NA
H: 5081 data points (29%) set to NA
LE: 5095 data points (29.08%) set to NA
NEE: 5615 data points (32.05%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9885 additional data points (56.42%) excluded by precipitation filter (9885
 data points = 56.42 % in total)
9885 data points (56.42%) excluded in total
7635 valid data points (43.58%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5246 data points (29.94%) set to NA
H: 5081 data points (29%) set to NA
LE: 5095 data points (29.08%) set to NA
NEE: 5615 data points (32.05%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CL-SDF'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 76.14.

Regression of reference temperature R_ref for 32 periods.

Quality control:
TA: 615 data points (3.51%) set to NA
H: 662 data points (3.78%) set to NA
LE: 651 data points (3.72%) set to NA
NEE: 1252 data points (7.15%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9024 additional data points (51.51%) excluded by precipitation filter (9024
 data points = 51.51 % in total)
9024 data points (51.51%) excluded in total
8496 valid data points (48.49%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 615 data points (3.51%) set to NA
H: 662 data points (3.78%) set to NA
LE: 651 data points (3.72%) set to NA
NEE: 1252 data points (7.15%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CL-SDF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CL-SDF-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 925 data points (5.28%) set to NA
H: 868 data points (4.95%) set to NA
LE: 896 data points (5.11%) set to NA
NEE: 1462 data points (8.34%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8617 additional data points (49.18%) excluded by precipitation filter (8617
 data points = 49.18 % in total)
8617 data points (49.18%) excluded in total
8903 valid data points (50.82%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 925 data points (5.28%) set to NA
H: 868 data points (4.95%) set to NA
LE: 896 data points (5.11%) set to NA
NEE: 1462 data points (8.34%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CL-SDF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CL-SDF-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3386 data points (19.27%) set to NA
H: 3380 data points (19.24%) set to NA
LE: 3596 data points (20.47%) set to NA
NEE: 4148 data points (23.61%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8280 additional data points (47.13%) excluded by precipitation filter (8280
 data points = 47.13 % in total)
8280 data points (47.13%) excluded in total
9288 valid data points (52.87%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3386 data points (19.27%) set to NA
H: 3380 data points (19.24%) set to NA
LE: 3596 data points (20.47%) set to NA
NEE: 4148 data points (23.61%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'CL-SDF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 22 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CL-SDF-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6900 data points (39.38%) set to NA
H: 5904 data points (33.7%) set to NA
LE: 5917 data points (33.77%) set to NA
NEE: 7188 data points (41.03%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7332 additional data points (41.85%) excluded by precipitation filter (7332
 data points = 41.85 % in total)
7332 data points (41.85%) excluded in total
10188 valid data points (58.15%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6900 data points (39.38%) set to NA
H: 5904 data points (33.7%) set to NA
LE: 5917 data points (33.77%) set to NA
NEE: 7188 data points (41.03%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CL-SDF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 29 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CL-SDF-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[53/329] Processing: CL-SDP

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CL-SDP | Years: 2017, 2018, 2019, 2020, 2021
Quality control:
TA: 2655 data points (15.15%) set to NA
H: 2615 data points (14.93%) set to NA
LE: 3149 data points (17.97%) set to NA
NEE: 3623 data points (20.68%) set to NA
-------------------------------------------------------------------
Data filtering:
1248 data points (7.12%) excluded by growing season filter
7365 additional data points (42.04%) excluded by precipitation filter (8221
 data points = 46.92 % in total)
8613 data points (49.16%) excluded in total
8907 valid data points (50.84%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2655 data points (15.15%) set to NA
H: 2615 data points (14.93%) set to NA
LE: 3149 data points (17.97%) set to NA
NEE: 3623 data points (20.68%) set to NA
-------------------------------------------------------------------
Data filtering:
1248 data points (7.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1248 data points (7.12%) excluded in total
16272 valid data points (92.88%) remaining.

New sEddyProc class for site 'CL-SDP'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 71.74.

Regression of reference temperature R_ref for 20 periods.

Quality control:
TA: 63 data points (0.36%) set to NA
H: 121 data points (0.69%) set to NA
LE: 713 data points (4.07%) set to NA
NEE: 1435 data points (8.19%) set to NA
-------------------------------------------------------------------
Data filtering:
2736 data points (15.62%) excluded by growing season filter
6358 additional data points (36.29%) excluded by precipitation filter (7816
 data points = 44.61 % in total)
9094 data points (51.91%) excluded in total
8426 valid data points (48.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 63 data points (0.36%) set to NA
H: 121 data points (0.69%) set to NA
LE: 713 data points (4.07%) set to NA
NEE: 1435 data points (8.19%) set to NA
-------------------------------------------------------------------
Data filtering:
2736 data points (15.62%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2736 data points (15.62%) excluded in total
14784 valid data points (84.38%) remaining.

New sEddyProc class for site 'CL-SDP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CL-SDP-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3062 data points (17.48%) set to NA
H: 3384 data points (19.32%) set to NA
LE: 7657 data points (43.7%) set to NA
NEE: 4360 data points (24.89%) set to NA
-------------------------------------------------------------------
Data filtering:
5472 data points (31.23%) excluded by growing season filter
3747 additional data points (21.39%) excluded by precipitation filter (7451
 data points = 42.53 % in total)
9219 data points (52.62%) excluded in total
8301 valid data points (47.38%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3062 data points (17.48%) set to NA
H: 3384 data points (19.32%) set to NA
LE: 7657 data points (43.7%) set to NA
NEE: 4360 data points (24.89%) set to NA
-------------------------------------------------------------------
Data filtering:
5472 data points (31.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5472 data points (31.23%) excluded in total
12048 valid data points (68.77%) remaining.

New sEddyProc class for site 'CL-SDP'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 96.98.

Regression of reference temperature R_ref for 27 periods.

Quality control:
TA: 649 data points (3.69%) set to NA
H: 699 data points (3.98%) set to NA
LE: 7302 data points (41.56%) set to NA
NEE: 2879 data points (16.39%) set to NA
-------------------------------------------------------------------
Data filtering:
7584 data points (43.17%) excluded by growing season filter
3595 additional data points (20.46%) excluded by precipitation filter (8069
 data points = 45.93 % in total)
11179 data points (63.63%) excluded in total
6389 valid data points (36.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 649 data points (3.69%) set to NA
H: 699 data points (3.98%) set to NA
LE: 7302 data points (41.56%) set to NA
NEE: 2879 data points (16.39%) set to NA
-------------------------------------------------------------------
Data filtering:
7584 data points (43.17%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7584 data points (43.17%) excluded in total
9984 valid data points (56.83%) remaining.

New sEddyProc class for site 'CL-SDP'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 156.88.

Regression of reference temperature R_ref for 11 periods.

Quality control:
TA: 6167 data points (35.2%) set to NA
H: 3376 data points (19.27%) set to NA
LE: 3360 data points (19.18%) set to NA
NEE: 5274 data points (30.1%) set to NA
-------------------------------------------------------------------
Data filtering:
624 data points (3.56%) excluded by growing season filter
5085 additional data points (29.02%) excluded by precipitation filter (5427
 data points = 30.98 % in total)
5709 data points (32.59%) excluded in total
11811 valid data points (67.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6167 data points (35.2%) set to NA
H: 3376 data points (19.27%) set to NA
LE: 3360 data points (19.18%) set to NA
NEE: 5274 data points (30.1%) set to NA
-------------------------------------------------------------------
Data filtering:
624 data points (3.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
624 data points (3.56%) excluded in total
16896 valid data points (96.44%) remaining.

New sEddyProc class for site 'CL-SDP'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 49.98.

Regression of reference temperature R_ref for 39 periods.

[54/329] Processing: CN-Ash

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-Ash | Years: 2017, 2018, 2019
Quality control:
TA: 404 data points (2.31%) set to NA
H: 1017 data points (5.8%) set to NA
LE: 1019 data points (5.82%) set to NA
NEE: 1177 data points (6.72%) set to NA
-------------------------------------------------------------------
Data filtering:
5040 data points (28.77%) excluded by growing season filter
6359 additional data points (36.3%) excluded by precipitation filter (7760
 data points = 44.29 % in total)
11399 data points (65.06%) excluded in total
6121 valid data points (34.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 404 data points (2.31%) set to NA
H: 1017 data points (5.8%) set to NA
LE: 1019 data points (5.82%) set to NA
NEE: 1177 data points (6.72%) set to NA
-------------------------------------------------------------------
Data filtering:
5040 data points (28.77%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5040 data points (28.77%) excluded in total
12480 valid data points (71.23%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 62 cases! Invalid values with 'NEE < -50': -63, -75, -65, -58, -66, -60, -56, -53, -76, -74, -77, -67, -51, -74, -62, -52, -62, -79, -58, -78, -74, -67, -51, -57, -68, -71, -67, -57, -53, -56, -65, -57, -51, -60, -59, -56, -71, -60, -73, -79, -68, -53, -57, -59, -65, -55, -56, -55, -64, -61 ...”
New sEddyProc class for site 'CN-Ash'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 62 cases! Invalid values with 'NEE < -50': -63, -75, -65, -58, -66, -60, -56, -53, -76, -74, -77, -67, -51, -74, -62, -52, -62, -79, -58, -78, -74, -67, -51, -57, -68, -71, -67, -57, -53, -56, -65, -57, -51, -60, -59, -56, -71, -60, -73, -79, -68, -53, -57, -59, -65, -55, -56, -55, -64, -61 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Ash-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1398 data points (7.98%) set to NA
H: 898 data points (5.13%) set to NA
LE: 926 data points (5.29%) set to NA
NEE: 1233 data points (7.04%) set to NA
-------------------------------------------------------------------
Data filtering:
7440 data points (42.47%) excluded by growing season filter
5152 additional data points (29.41%) excluded by precipitation filter (6971
 data points = 39.79 % in total)
12592 data points (71.87%) excluded in total
4928 valid data points (28.13%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 1398 data points (7.98%) set to NA
H: 898 data points (5.13%) set to NA
LE: 926 data points (5.29%) set to NA
NEE: 1233 data points (7.04%) set to NA
-------------------------------------------------------------------
Data filtering:
7440 data points (42.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7440 data points (42.47%) excluded in total
10080 valid data points (57.53%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 41 cases! Invalid values with 'NEE < -50': -73, -65, -66, -55, -50, -79, -79, -65, -64, -73, -80, -73, -55, -58, -69, -53, -55, -78, -54, -60, -55, -50, -69, -62, -56, -51, -56, -57, -71, -52, -55, -52, -61, -74, -66, -53, -76, -51, -60, -62, -51 ...”
New sEddyProc class for site 'CN-Ash'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 41 cases! Invalid values with 'NEE < -50': -73, -65, -66, -55, -50, -79, -79, -65, -64, -73, -80, -73, -55, -58, -69, -53, -55, -78, -54, -60, -55, -50, -69, -62, -56, -51, -56, -57, -71, -52, -55, -52, -61, -74, -66, -53, -76, -51, -60, -62, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 8 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Ash-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1003 data points (5.72%) set to NA
LE: 1038 data points (5.92%) set to NA
NEE: 1484 data points (8.47%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3899 additional data points (22.25%) excluded by precipitation filter (3899
 data points = 22.25 % in total)
3899 data points (22.25%) excluded in total
13621 valid data points (77.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1003 data points (5.72%) set to NA
LE: 1038 data points (5.92%) set to NA
NEE: 1484 data points (8.47%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 27 cases! Invalid values with 'NEE < -50': -77, -56, -63, -77, -63, -64, -77, -64, -69, -64, -54, -53, -51, -63, -66, -79, -75, -52, -51, -75, -52, -59, -61, -53, -58, -62, -72 ...”
New sEddyProc class for site 'CN-Ash'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 27 cases! Invalid values with 'NEE < -50': -77, -56, -63, -77, -63, -64, -77, -64, -69, -64, -54, -53, -51, -63, -66, -79, -75, -52, -51, -75, -52, -59, -61, -53, -58, -62, -72 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Ash-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[55/329] Processing: CN-BeO

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-BeO | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 453 data points (2.59%) set to NA
H: 481 data points (2.75%) set to NA
LE: 494 data points (2.82%) set to NA
NEE: 1748 data points (9.98%) set to NA
-------------------------------------------------------------------
Data filtering:
7920 data points (45.21%) excluded by growing season filter
2019 additional data points (11.52%) excluded by precipitation filter (2248
 data points = 12.83 % in total)
9939 data points (56.73%) excluded in total
7581 valid data points (43.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 453 data points (2.59%) set to NA
H: 481 data points (2.75%) set to NA
LE: 494 data points (2.82%) set to NA
NEE: 1748 data points (9.98%) set to NA
-------------------------------------------------------------------
Data filtering:
7920 data points (45.21%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7920 data points (45.21%) excluded in total
9600 valid data points (54.79%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
New sEddyProc class for site 'CN-BeO'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 166.35.

Regression of reference temperature R_ref for 3 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 76 data points (0.43%) set to NA
LE: 108 data points (0.62%) set to NA
NEE: 1506 data points (8.6%) set to NA
-------------------------------------------------------------------
Data filtering:
8928 data points (50.96%) excluded by growing season filter
2058 additional data points (11.75%) excluded by precipitation filter (2485
 data points = 14.18 % in total)
10986 data points (62.71%) excluded in total
6534 valid data points (37.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 76 data points (0.43%) set to NA
LE: 108 data points (0.62%) set to NA
NEE: 1506 data points (8.6%) set to NA
-------------------------------------------------------------------
Data filtering:
8928 data points (50.96%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8928 data points (50.96%) excluded in total
8592 valid data points (49.04%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -70 ...”
New sEddyProc class for site 'CN-BeO'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -70 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-BeO-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 10 data points (0.06%) set to NA
H: 66 data points (0.38%) set to NA
LE: 74 data points (0.42%) set to NA
NEE: 1157 data points (6.6%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.85%) excluded by growing season filter
2146 additional data points (12.25%) excluded by precipitation filter (2558
 data points = 14.6 % in total)
10354 data points (59.1%) excluded in total
7166 valid data points (40.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 10 data points (0.06%) set to NA
H: 66 data points (0.38%) set to NA
LE: 74 data points (0.42%) set to NA
NEE: 1157 data points (6.6%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8208 data points (46.85%) excluded in total
9312 valid data points (53.15%) remaining.

New sEddyProc class for site 'CN-BeO'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-BeO-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1718 data points (9.78%) set to NA
H: 1785 data points (10.16%) set to NA
LE: 1880 data points (10.7%) set to NA
NEE: 2851 data points (16.23%) set to NA
-------------------------------------------------------------------
Data filtering:
8976 data points (51.09%) excluded by growing season filter
2309 additional data points (13.14%) excluded by precipitation filter (3076
 data points = 17.51 % in total)
11285 data points (64.24%) excluded in total
6283 valid data points (35.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 1718 data points (9.78%) set to NA
H: 1785 data points (10.16%) set to NA
LE: 1880 data points (10.7%) set to NA
NEE: 2851 data points (16.23%) set to NA
-------------------------------------------------------------------
Data filtering:
8976 data points (51.09%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8976 data points (51.09%) excluded in total
8592 valid data points (48.91%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -65 ...”
New sEddyProc class for site 'CN-BeO'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -65 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 143.55.

Regression of reference temperature R_ref for 10 periods.

[56/329] Processing: CN-DaW

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-DaW | Years: 2017, 2018, 2019
Quality control:
TA: 0 data points (0%) set to NA
H: 4708 data points (26.87%) set to NA
LE: 4713 data points (26.9%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4947 additional data points (28.24%) excluded by precipitation filter (4947
 data points = 28.24 % in total)
4947 data points (28.24%) excluded in total
12573 valid data points (71.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 4708 data points (26.87%) set to NA
LE: 4713 data points (26.9%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CN-DaW'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-DaW-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 831 data points (4.74%) set to NA
LE: 828 data points (4.73%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5953 additional data points (33.98%) excluded by precipitation filter (5953
 data points = 33.98 % in total)
5953 data points (33.98%) excluded in total
11567 valid data points (66.02%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 831 data points (4.74%) set to NA
LE: 828 data points (4.73%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CN-DaW'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-DaW-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 4351 data points (24.83%) set to NA
LE: 4351 data points (24.83%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4266 additional data points (24.35%) excluded by precipitation filter (4266
 data points = 24.35 % in total)
4266 data points (24.35%) excluded in total
13254 valid data points (75.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 4351 data points (24.83%) set to NA
LE: 4351 data points (24.83%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CN-DaW'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-DaW-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[57/329] Processing: CN-Din

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-Din | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 17520 data points (100%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
11351 additional data points (64.79%) excluded by precipitation filter (11351
 data points = 64.79 % in total)
11351 data points (64.79%) excluded in total
6169 valid data points (35.21%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for CN-Din-2017”

Quality control:
TA: 17519 data points (99.99%) set to NA
H: 17519 data points (99.99%) set to NA
LE: 17519 data points (99.99%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10985 additional data points (62.7%) excluded by precipitation filter (10985
 data points = 62.7 % in total)
10985 data points (62.7%) excluded in total
6535 valid data points (37.3%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for CN-Din-2018”

Quality control:
TA: 0 data points (0%) set to NA
H: 9 data points (0.05%) set to NA
LE: 13 data points (0.07%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6440 additional data points (36.76%) excluded by precipitation filter (6440
 data points = 36.76 % in total)
6440 data points (36.76%) excluded in total
11080 valid data points (63.24%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 9 data points (0.05%) set to NA
LE: 13 data points (0.07%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'CN-Din'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Din-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1059 data points (6.03%) set to NA
H: 59 data points (0.34%) set to NA
LE: 211 data points (1.2%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10127 additional data points (57.64%) excluded by precipitation filter (10127
 data points = 57.64 % in total)
10127 data points (57.64%) excluded in total
7441 valid data points (42.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 1059 data points (6.03%) set to NA
H: 59 data points (0.34%) set to NA
LE: 211 data points (1.2%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'CN-Din'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Din-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[58/329] Processing: CN-Dzo

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-Dzo | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 17519 data points (99.99%) set to NA
H: 17519 data points (99.99%) set to NA
LE: 17519 data points (99.99%) set to NA
NEE: 17520 data points (100%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12277 additional data points (70.07%) excluded by precipitation filter (12277
 data points = 70.07 % in total)
12277 data points (70.07%) excluded in total
5243 valid data points (29.93%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for CN-Dzo-2017”

Quality control:
TA: 658 data points (3.76%) set to NA
H: 3090 data points (17.64%) set to NA
LE: 3135 data points (17.89%) set to NA
NEE: 3459 data points (19.74%) set to NA
-------------------------------------------------------------------
Data filtering:
3312 data points (18.9%) excluded by growing season filter
6779 additional data points (38.69%) excluded by precipitation filter (7520
 data points = 42.92 % in total)
10091 data points (57.6%) excluded in total
7429 valid data points (42.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 658 data points (3.76%) set to NA
H: 3090 data points (17.64%) set to NA
LE: 3135 data points (17.89%) set to NA
NEE: 3459 data points (19.74%) set to NA
-------------------------------------------------------------------
Data filtering:
3312 data points (18.9%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3312 data points (18.9%) excluded in total
14208 valid data points (81.1%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 20 cases! Invalid values with 'NEE < -50': -72, -52, -52, -66, -52, -73, -59, -54, -61, -75, -50, -76, -74, -69, -56, -67, -56, -60, -79, -58 ...”
New sEddyProc class for site 'CN-Dzo'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 20 cases! Invalid values with 'NEE < -50': -72, -52, -52, -66, -52, -73, -59, -54, -61, -75, -50, -76, -74, -69, -56, -67, -56, -60, -79, -58 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Dzo-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 113 data points (0.64%) set to NA
H: 293 data points (1.67%) set to NA
LE: 484 data points (2.76%) set to NA
NEE: 1987 data points (11.34%) set to NA
-------------------------------------------------------------------
Data filtering:
2304 data points (13.15%) excluded by growing season filter
5861 additional data points (33.45%) excluded by precipitation filter (6368
 data points = 36.35 % in total)
8165 data points (46.6%) excluded in total
9355 valid data points (53.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 113 data points (0.64%) set to NA
H: 293 data points (1.67%) set to NA
LE: 484 data points (2.76%) set to NA
NEE: 1987 data points (11.34%) set to NA
-------------------------------------------------------------------
Data filtering:
2304 data points (13.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2304 data points (13.15%) excluded in total
15216 valid data points (86.85%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 50 cases! Invalid values with 'NEE < -50': -54, -60, -53, -60, -61, -73, -56, -72, -62, -70, -68, -60, -50, -56, -57, -51, -79, -60, -65, -68, -50, -56, -53, -78, -73, -57, -60, -62, -57, -67, -58, -55, -71, -61, -53, -62, -80, -75, -70, -54, -77, -71, -52, -58, -71, -66, -50, -56, -69, -52 ...”
New sEddyProc class for site 'CN-Dzo'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 50 cases! Invalid values with 'NEE < -50': -54, -60, -53, -60, -61, -73, -56, -72, -62, -70, -68, -60, -50, -56, -57, -51, -79, -60, -65, -68, -50, -56, -53, -78, -73, -57, -60, -62, -57, -67, -58, -55, -71, -61, -53, -62, -80, -75, -70, -54, -77, -71, -52, -58, -71, -66, -50, -56, -69, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Dzo-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 155 data points (0.88%) set to NA
H: 141 data points (0.8%) set to NA
LE: 154 data points (0.88%) set to NA
NEE: 293 data points (1.67%) set to NA
-------------------------------------------------------------------
Data filtering:
2880 data points (16.39%) excluded by growing season filter
5795 additional data points (32.99%) excluded by precipitation filter (6384
 data points = 36.34 % in total)
8675 data points (49.38%) excluded in total
8893 valid data points (50.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 155 data points (0.88%) set to NA
H: 141 data points (0.8%) set to NA
LE: 154 data points (0.88%) set to NA
NEE: 293 data points (1.67%) set to NA
-------------------------------------------------------------------
Data filtering:
2880 data points (16.39%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2880 data points (16.39%) excluded in total
14688 valid data points (83.61%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 38 cases! Invalid values with 'NEE < -50': -51, -64, -67, -55, -53, -50, -55, -56, -54, -50, -51, -56, -72, -53, -56, -51, -60, -75, -51, -74, -54, -61, -59, -69, -69, -75, -51, -79, -57, -68, -61, -79, -62, -52, -60, -61, -68, -53 ...”
New sEddyProc class for site 'CN-Dzo'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 38 cases! Invalid values with 'NEE < -50': -51, -64, -67, -55, -53, -50, -55, -56, -54, -50, -51, -56, -72, -53, -56, -51, -60, -75, -51, -74, -54, -61, -59, -69, -69, -75, -51, -79, -57, -68, -61, -79, -62, -52, -60, -61, -68, -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Dzo-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[59/329] Processing: CN-Ha2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-Ha2 | Years: 2017, 2018, 2019
Quality control:
TA: 60 data points (0.34%) set to NA
H: 4490 data points (25.63%) set to NA
LE: 4524 data points (25.82%) set to NA
NEE: 4703 data points (26.84%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 20”

-------------------------------------------------------------------
Data filtering:
12096 data points (69.04%) excluded by growing season filter
4678 additional data points (26.7%) excluded by precipitation filter (10150
 data points = 57.93 % in total)
16774 data points (95.74%) excluded in total
746 valid data points (4.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 60 data points (0.34%) set to NA
H: 4490 data points (25.63%) set to NA
LE: 4524 data points (25.82%) set to NA
NEE: 4703 data points (26.84%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 20”

-------------------------------------------------------------------
Data filtering:
12096 data points (69.04%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12096 data points (69.04%) excluded in total
5424 valid data points (30.96%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 14 cases! Invalid values with 'NEE < -50': -69, -62, -51, -69, -56, -55, -77, -67, -59, -52, -71, -68, -55, -56 ...”
New sEddyProc class for site 'CN-Ha2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 14 cases! Invalid values with 'NEE < -50': -69, -62, -51, -69, -56, -55, -77, -67, -59, -52, -71, -68, -55, -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Ha2-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 69 data points (0.39%) set to NA
H: 3315 data points (18.92%) set to NA
LE: 3317 data points (18.93%) set to NA
NEE: 4056 data points (23.15%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.19%) excluded by growing season filter
5960 additional data points (34.02%) excluded by precipitation filter (10802
 data points = 61.66 % in total)
16856 data points (96.21%) excluded in total
664 valid data points (3.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 69 data points (0.39%) set to NA
H: 3315 data points (18.92%) set to NA
LE: 3317 data points (18.93%) set to NA
NEE: 4056 data points (23.15%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10896 data points (62.19%) excluded in total
6624 valid data points (37.81%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 20 cases! Invalid values with 'NEE < -50': -65, -56, -67, -54, -78, -66, -53, -71, -53, -69, -66, -59, -51, -67, -66, -64, -67, -56, -60, -72 ...”
New sEddyProc class for site 'CN-Ha2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 20 cases! Invalid values with 'NEE < -50': -65, -56, -67, -54, -78, -66, -53, -71, -53, -69, -66, -59, -51, -67, -66, -64, -67, -56, -60, -72 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Ha2-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 43 data points (0.25%) set to NA
H: 9878 data points (56.38%) set to NA
LE: 9920 data points (56.62%) set to NA
NEE: 10307 data points (58.83%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
5700 additional data points (32.53%) excluded by precipitation filter (10944
 data points = 62.47 % in total)
16500 data points (94.18%) excluded in total
1020 valid data points (5.82%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (36) for CN-Ha2-2019”
[60/329] Processing: CN-HaW

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-HaW | Years: 2017, 2018
Quality control:
TA: 84 data points (0.48%) set to NA
H: 5829 data points (33.27%) set to NA
LE: 5869 data points (33.5%) set to NA
NEE: 6135 data points (35.02%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 36”

-------------------------------------------------------------------
Data filtering:
8832 data points (50.41%) excluded by growing season filter
3323 additional data points (18.97%) excluded by precipitation filter (5617
 data points = 32.06 % in total)
12155 data points (69.38%) excluded in total
5365 valid data points (30.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 84 data points (0.48%) set to NA
H: 5829 data points (33.27%) set to NA
LE: 5869 data points (33.5%) set to NA
NEE: 6135 data points (35.02%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 36”

-------------------------------------------------------------------
Data filtering:
8832 data points (50.41%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8832 data points (50.41%) excluded in total
8688 valid data points (49.59%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 43 cases! Invalid values with 'NEE < -50': -79, -51, -54, -54, -67, -54, -77, -74, -59, -51, -57, -69, -71, -65, -69, -67, -65, -74, -75, -78, -73, -74, -56, -71, -51, -58, -74, -62, -63, -76, -63, -56, -50, -59, -76, -61, -56, -63, -62, -74, -59, -71, -72 ...”
New sEddyProc class for site 'CN-HaW'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 43 cases! Invalid values with 'NEE < -50': -79, -51, -54, -54, -67, -54, -77, -74, -59, -51, -57, -69, -71, -65, -69, -67, -65, -74, -75, -78, -73, -74, -56, -71, -51, -58, -74, -62, -63, -76, -63, -56, -50, -59, -76, -61, -56, -63, -62, -74, -59, -71, -72 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-HaW-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 824 data points (4.7%) set to NA
H: 3513 data points (20.05%) set to NA
LE: 3537 data points (20.19%) set to NA
NEE: 3728 data points (21.28%) set to NA
-------------------------------------------------------------------
Data filtering:
11520 data points (65.75%) excluded by growing season filter
3674 additional data points (20.97%) excluded by precipitation filter (5609
 data points = 32.01 % in total)
15194 data points (86.72%) excluded in total
2326 valid data points (13.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 824 data points (4.7%) set to NA
H: 3513 data points (20.05%) set to NA
LE: 3537 data points (20.19%) set to NA
NEE: 3728 data points (21.28%) set to NA
-------------------------------------------------------------------
Data filtering:
11520 data points (65.75%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11520 data points (65.75%) excluded in total
6000 valid data points (34.25%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 21 cases! Invalid values with 'NEE < -50': -75, -78, -63, -63, -75, -62, -58, -73, -56, -65, -54, -78, -59, -51, -51, -62, -66, -53, -59, -65, -51 ...”
New sEddyProc class for site 'CN-HaW'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 21 cases! Invalid values with 'NEE < -50': -75, -78, -63, -63, -75, -62, -58, -73, -56, -65, -54, -78, -59, -51, -51, -62, -66, -53, -59, -65, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-HaW-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[61/329] Processing: CN-HeM

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-HeM | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 120 data points (0.68%) set to NA
LE: 4144 data points (23.65%) set to NA
NEE: 6007 data points (34.29%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.27%) excluded by growing season filter
802 additional data points (4.58%) excluded by precipitation filter (1270
 data points = 7.25 % in total)
11362 data points (64.85%) excluded in total
6158 valid data points (35.15%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 120 data points (0.68%) set to NA
LE: 4144 data points (23.65%) set to NA
NEE: 6007 data points (34.29%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10560 data points (60.27%) excluded in total
6960 valid data points (39.73%) remaining.

New sEddyProc class for site 'CN-HeM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-HeM-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 92 data points (0.53%) set to NA
H: 75 data points (0.43%) set to NA
LE: 119 data points (0.68%) set to NA
NEE: 2272 data points (12.97%) set to NA
-------------------------------------------------------------------
Data filtering:
9552 data points (54.52%) excluded by growing season filter
1168 additional data points (6.67%) excluded by precipitation filter (1636
 data points = 9.34 % in total)
10720 data points (61.19%) excluded in total
6800 valid data points (38.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 92 data points (0.53%) set to NA
H: 75 data points (0.43%) set to NA
LE: 119 data points (0.68%) set to NA
NEE: 2272 data points (12.97%) set to NA
-------------------------------------------------------------------
Data filtering:
9552 data points (54.52%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9552 data points (54.52%) excluded in total
7968 valid data points (45.48%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -66, -50, -72, -66 ...”
New sEddyProc class for site 'CN-HeM'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -66, -50, -72, -66 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-HeM-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 111 data points (0.63%) set to NA
H: 277 data points (1.58%) set to NA
LE: 396 data points (2.26%) set to NA
NEE: 2103 data points (12%) set to NA
-------------------------------------------------------------------
Data filtering:
9648 data points (55.07%) excluded by growing season filter
1266 additional data points (7.23%) excluded by precipitation filter (1642
 data points = 9.37 % in total)
10914 data points (62.29%) excluded in total
6606 valid data points (37.71%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 111 data points (0.63%) set to NA
H: 277 data points (1.58%) set to NA
LE: 396 data points (2.26%) set to NA
NEE: 2103 data points (12%) set to NA
-------------------------------------------------------------------
Data filtering:
9648 data points (55.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9648 data points (55.07%) excluded in total
7872 valid data points (44.93%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -59, -68, -57 ...”
New sEddyProc class for site 'CN-HeM'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -59, -68, -57 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-HeM-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 153 data points (0.87%) set to NA
H: 404 data points (2.3%) set to NA
LE: 691 data points (3.93%) set to NA
NEE: 5538 data points (31.52%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.72%) excluded by growing season filter
1048 additional data points (5.97%) excluded by precipitation filter (1100
 data points = 6.26 % in total)
9256 data points (52.69%) excluded in total
8312 valid data points (47.31%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 153 data points (0.87%) set to NA
H: 404 data points (2.3%) set to NA
LE: 691 data points (3.93%) set to NA
NEE: 5538 data points (31.52%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.72%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8208 data points (46.72%) excluded in total
9360 valid data points (53.28%) remaining.

New sEddyProc class for site 'CN-HeM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-HeM-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1087 data points (6.2%) set to NA
H: 1332 data points (7.6%) set to NA
LE: 3521 data points (20.1%) set to NA
NEE: 7900 data points (45.09%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 70”

-------------------------------------------------------------------
Data filtering:
7392 data points (42.19%) excluded by growing season filter
718 additional data points (4.1%) excluded by precipitation filter (1120
 data points = 6.39 % in total)
8110 data points (46.29%) excluded in total
9410 valid data points (53.71%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1087 data points (6.2%) set to NA
H: 1332 data points (7.6%) set to NA
LE: 3521 data points (20.1%) set to NA
NEE: 7900 data points (45.09%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 70”

-------------------------------------------------------------------
Data filtering:
7392 data points (42.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7392 data points (42.19%) excluded in total
10128 valid data points (57.81%) remaining.

New sEddyProc class for site 'CN-HeM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-HeM-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1 data points (0.01%) set to NA
H: 276 data points (1.58%) set to NA
LE: 9331 data points (53.26%) set to NA
NEE: 4314 data points (24.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 29”

-------------------------------------------------------------------
Data filtering:
9600 data points (54.79%) excluded by growing season filter
738 additional data points (4.21%) excluded by precipitation filter (1360
 data points = 7.76 % in total)
10338 data points (59.01%) excluded in total
7182 valid data points (40.99%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1 data points (0.01%) set to NA
H: 276 data points (1.58%) set to NA
LE: 9331 data points (53.26%) set to NA
NEE: 4314 data points (24.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 29”

-------------------------------------------------------------------
Data filtering:
9600 data points (54.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9600 data points (54.79%) excluded in total
7920 valid data points (45.21%) remaining.

New sEddyProc class for site 'CN-HeM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-HeM-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2179 data points (12.44%) set to NA
LE: 3704 data points (21.14%) set to NA
NEE: 3971 data points (22.67%) set to NA
-------------------------------------------------------------------
Data filtering:
6192 data points (35.34%) excluded by growing season filter
1072 additional data points (6.12%) excluded by precipitation filter (1262
 data points = 7.2 % in total)
7264 data points (41.46%) excluded in total
10256 valid data points (58.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2179 data points (12.44%) set to NA
LE: 3704 data points (21.14%) set to NA
NEE: 3971 data points (22.67%) set to NA
-------------------------------------------------------------------
Data filtering:
6192 data points (35.34%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6192 data points (35.34%) excluded in total
11328 valid data points (64.66%) remaining.

New sEddyProc class for site 'CN-HeM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-HeM-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 391 data points (2.23%) set to NA
LE: 1079 data points (6.14%) set to NA
NEE: 2593 data points (14.76%) set to NA
-------------------------------------------------------------------
Data filtering:
8592 data points (48.91%) excluded by growing season filter
1304 additional data points (7.42%) excluded by precipitation filter (1916
 data points = 10.91 % in total)
9896 data points (56.33%) excluded in total
7672 valid data points (43.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 391 data points (2.23%) set to NA
LE: 1079 data points (6.14%) set to NA
NEE: 2593 data points (14.76%) set to NA
-------------------------------------------------------------------
Data filtering:
8592 data points (48.91%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8592 data points (48.91%) excluded in total
8976 valid data points (51.09%) remaining.

New sEddyProc class for site 'CN-HeM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-HeM-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[62/329] Processing: CN-Mxn

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-Mxn | Years: 2017, 2018, 2019
Quality control:
TA: 17519 data points (99.99%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 17520 data points (100%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12377 additional data points (70.64%) excluded by precipitation filter (12377
 data points = 70.64 % in total)
12377 data points (70.64%) excluded in total
5143 valid data points (29.36%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for CN-Mxn-2017”

Quality control:
TA: 17519 data points (99.99%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 17520 data points (100%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12318 additional data points (70.31%) excluded by precipitation filter (12318
 data points = 70.31 % in total)
12318 data points (70.31%) excluded in total
5202 valid data points (29.69%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for CN-Mxn-2018”

Quality control:
TA: 0 data points (0%) set to NA
H: 6121 data points (34.94%) set to NA
LE: 6139 data points (35.04%) set to NA
NEE: 6283 data points (35.86%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9594 additional data points (54.76%) excluded by precipitation filter (9594
 data points = 54.76 % in total)
9594 data points (54.76%) excluded in total
7926 valid data points (45.24%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 6121 data points (34.94%) set to NA
LE: 6139 data points (35.04%) set to NA
NEE: 6283 data points (35.86%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 24 cases! Invalid values with 'NEE < -50': -62, -78, -61, -53, -70, -69, -51, -53, -55, -60, -51, -73, -63, -71, -61, -73, -76, -52, -72, -51, -77, -76, -71, -66 ...”
New sEddyProc class for site 'CN-Mxn'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 24 cases! Invalid values with 'NEE < -50': -62, -78, -61, -53, -70, -69, -51, -53, -55, -60, -51, -73, -63, -71, -61, -73, -76, -52, -72, -51, -77, -76, -71, -66 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Mxn-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[63/329] Processing: CN-Qng

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-Qng | Years: 2022, 2023, 2024
Quality control:
TA: 6102 data points (34.83%) set to NA
H: 6138 data points (35.03%) set to NA
LE: 6148 data points (35.09%) set to NA
NEE: 6156 data points (35.14%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
11336 additional data points (64.7%) excluded by precipitation filter (11336
 data points = 64.7 % in total)
11336 data points (64.7%) excluded in total
6184 valid data points (35.3%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 6102 data points (34.83%) set to NA
H: 6138 data points (35.03%) set to NA
LE: 6148 data points (35.09%) set to NA
NEE: 6156 data points (35.14%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 25 cases! Invalid values with 'NEE < -50': -50, -64, -65, -50, -56, -55, -71, -74, -68, -51, -78, -55, -56, -65, -51, -52, -60, -58, -60, -66, -62, -58, -70, -56, -51 ...”
New sEddyProc class for site 'CN-Qng'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 25 cases! Invalid values with 'NEE < -50': -50, -64, -65, -50, -56, -55, -71, -74, -68, -51, -78, -55, -56, -65, -51, -52, -60, -58, -60, -66, -62, -58, -70, -56, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 23 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Qng-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1404 data points (8.01%) set to NA
H: 1885 data points (10.76%) set to NA
LE: 8627 data points (49.24%) set to NA
NEE: 8631 data points (49.26%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10894 additional data points (62.18%) excluded by precipitation filter (10894
 data points = 62.18 % in total)
10894 data points (62.18%) excluded in total
6626 valid data points (37.82%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 1404 data points (8.01%) set to NA
H: 1885 data points (10.76%) set to NA
LE: 8627 data points (49.24%) set to NA
NEE: 8631 data points (49.26%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -51, -67, -63, -50, -77, -59, -58, -62, -73 ...”
New sEddyProc class for site 'CN-Qng'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -51, -67, -63, -50, -77, -59, -58, -62, -73 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 27 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Qng-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 11189 data points (63.69%) set to NA
H: 11371 data points (64.73%) set to NA
LE: 11385 data points (64.81%) set to NA
NEE: 11408 data points (64.94%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
11602 additional data points (66.04%) excluded by precipitation filter (11602
 data points = 66.04 % in total)
11602 data points (66.04%) excluded in total
5966 valid data points (33.96%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 11189 data points (63.69%) set to NA
H: 11371 data points (64.73%) set to NA
LE: 11385 data points (64.81%) set to NA
NEE: 11408 data points (64.94%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 10 cases! Invalid values with 'NEE < -50': -64, -68, -64, -66, -56, -59, -60, -55, -59, -53 ...”
New sEddyProc class for site 'CN-Qng'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 10 cases! Invalid values with 'NEE < -50': -64, -68, -64, -66, -56, -59, -60, -55, -59, -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 133.64.

Regression of reference temperature R_ref for 34 periods.

[64/329] Processing: CN-Sb1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-Sb1 | Years: 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 10405 data points (59.23%) set to NA
H: 10426 data points (59.35%) set to NA
LE: 10419 data points (59.31%) set to NA
NEE: 10760 data points (61.25%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7606 additional data points (43.29%) excluded by precipitation filter (7606
 data points = 43.29 % in total)
7606 data points (43.29%) excluded in total
9962 valid data points (56.71%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10405 data points (59.23%) set to NA
H: 10426 data points (59.35%) set to NA
LE: 10419 data points (59.31%) set to NA
NEE: 10760 data points (61.25%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -53, -62, -77, -65, -50, -53, -56, -78, -62 ...”
New sEddyProc class for site 'CN-Sb1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -53, -62, -77, -65, -50, -53, -56, -78, -62 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 149.76.

Regression of reference temperature R_ref for 7 periods.

Quality control:
TA: 621 data points (3.54%) set to NA
H: 661 data points (3.77%) set to NA
LE: 684 data points (3.9%) set to NA
NEE: 1321 data points (7.54%) set to NA
-------------------------------------------------------------------
Data filtering:
4272 data points (24.38%) excluded by growing season filter
7870 additional data points (44.92%) excluded by precipitation filter (8712
 data points = 49.73 % in total)
12142 data points (69.3%) excluded in total
5378 valid data points (30.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 621 data points (3.54%) set to NA
H: 661 data points (3.77%) set to NA
LE: 684 data points (3.9%) set to NA
NEE: 1321 data points (7.54%) set to NA
-------------------------------------------------------------------
Data filtering:
4272 data points (24.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4272 data points (24.38%) excluded in total
13248 valid data points (75.62%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 21 cases! Invalid values with 'NEE < -50': -61, -55, -56, -70, -54, -56, -59, -58, -51, -50, -54, -66, -50, -52, -56, -55, -51, -66, -51, -66, -74 ...”
New sEddyProc class for site 'CN-Sb1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 21 cases! Invalid values with 'NEE < -50': -61, -55, -56, -70, -54, -56, -59, -58, -51, -50, -54, -66, -50, -52, -56, -55, -51, -66, -51, -66, -74 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Sb1-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 351 data points (2%) set to NA
H: 388 data points (2.21%) set to NA
LE: 406 data points (2.32%) set to NA
NEE: 1335 data points (7.62%) set to NA
-------------------------------------------------------------------
Data filtering:
3360 data points (19.18%) excluded by growing season filter
5940 additional data points (33.9%) excluded by precipitation filter (6876
 data points = 39.25 % in total)
9300 data points (53.08%) excluded in total
8220 valid data points (46.92%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 351 data points (2%) set to NA
H: 388 data points (2.21%) set to NA
LE: 406 data points (2.32%) set to NA
NEE: 1335 data points (7.62%) set to NA
-------------------------------------------------------------------
Data filtering:
3360 data points (19.18%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3360 data points (19.18%) excluded in total
14160 valid data points (80.82%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 31 cases! Invalid values with 'NEE < -50': -59, -55, -79, -52, -51, -75, -54, -66, -74, -70, -68, -70, -58, -63, -76, -55, -54, -68, -50, -52, -57, -75, -51, -57, -53, -54, -50, -51, -50, -51, -72 ...”
New sEddyProc class for site 'CN-Sb1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 31 cases! Invalid values with 'NEE < -50': -59, -55, -79, -52, -51, -75, -54, -66, -74, -70, -68, -70, -58, -63, -76, -55, -54, -68, -50, -52, -57, -75, -51, -57, -53, -54, -50, -51, -50, -51, -72 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Sb1-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 424 data points (2.42%) set to NA
H: 456 data points (2.6%) set to NA
LE: 489 data points (2.79%) set to NA
NEE: 1056 data points (6.03%) set to NA
-------------------------------------------------------------------
Data filtering:
3456 data points (19.73%) excluded by growing season filter
6364 additional data points (36.32%) excluded by precipitation filter (7340
 data points = 41.89 % in total)
9820 data points (56.05%) excluded in total
7700 valid data points (43.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 424 data points (2.42%) set to NA
H: 456 data points (2.6%) set to NA
LE: 489 data points (2.79%) set to NA
NEE: 1056 data points (6.03%) set to NA
-------------------------------------------------------------------
Data filtering:
3456 data points (19.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3456 data points (19.73%) excluded in total
14064 valid data points (80.27%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 10 cases! Invalid values with 'NEE < -50': -75, -62, -51, -56, -56, -54, -51, -57, -57, -52 ...”
New sEddyProc class for site 'CN-Sb1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 10 cases! Invalid values with 'NEE < -50': -75, -62, -51, -56, -56, -54, -51, -57, -57, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Sb1-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 632 data points (3.6%) set to NA
H: 679 data points (3.86%) set to NA
LE: 699 data points (3.98%) set to NA
NEE: 1342 data points (7.64%) set to NA
-------------------------------------------------------------------
Data filtering:
4416 data points (25.14%) excluded by growing season filter
7142 additional data points (40.65%) excluded by precipitation filter (8356
 data points = 47.56 % in total)
11558 data points (65.79%) excluded in total
6010 valid data points (34.21%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 632 data points (3.6%) set to NA
H: 679 data points (3.86%) set to NA
LE: 699 data points (3.98%) set to NA
NEE: 1342 data points (7.64%) set to NA
-------------------------------------------------------------------
Data filtering:
4416 data points (25.14%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4416 data points (25.14%) excluded in total
13152 valid data points (74.86%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 30 cases! Invalid values with 'NEE < -50': -52, -61, -56, -54, -62, -54, -58, -54, -55, -63, -54, -51, -51, -51, -55, -51, -52, -51, -53, -53, -52, -53, -50, -60, -57, -67, -54, -74, -51, -62 ...”
New sEddyProc class for site 'CN-Sb1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 30 cases! Invalid values with 'NEE < -50': -52, -61, -56, -54, -62, -54, -58, -54, -55, -63, -54, -51, -51, -51, -55, -51, -52, -51, -53, -53, -52, -53, -50, -60, -57, -67, -54, -74, -51, -62 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Sb1-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[65/329] Processing: CN-Sb2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-Sb2 | Years: 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 10419 data points (59.31%) set to NA
H: 10458 data points (59.53%) set to NA
LE: 10438 data points (59.41%) set to NA
NEE: 10728 data points (61.07%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7606 additional data points (43.29%) excluded by precipitation filter (7606
 data points = 43.29 % in total)
7606 data points (43.29%) excluded in total
9962 valid data points (56.71%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10419 data points (59.31%) set to NA
H: 10458 data points (59.53%) set to NA
LE: 10438 data points (59.41%) set to NA
NEE: 10728 data points (61.07%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -61, -53, -68, -53 ...”
New sEddyProc class for site 'CN-Sb2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -61, -53, -68, -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Sb2-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 642 data points (3.66%) set to NA
H: 682 data points (3.89%) set to NA
LE: 712 data points (4.06%) set to NA
NEE: 1801 data points (10.28%) set to NA
-------------------------------------------------------------------
Data filtering:
2832 data points (16.16%) excluded by growing season filter
7986 additional data points (45.58%) excluded by precipitation filter (8712
 data points = 49.73 % in total)
10818 data points (61.75%) excluded in total
6702 valid data points (38.25%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 642 data points (3.66%) set to NA
H: 682 data points (3.89%) set to NA
LE: 712 data points (4.06%) set to NA
NEE: 1801 data points (10.28%) set to NA
-------------------------------------------------------------------
Data filtering:
2832 data points (16.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2832 data points (16.16%) excluded in total
14688 valid data points (83.84%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -52, -56, -68, -53, -52 ...”
New sEddyProc class for site 'CN-Sb2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -52, -56, -68, -53, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Sb2-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 394 data points (2.25%) set to NA
H: 437 data points (2.49%) set to NA
LE: 444 data points (2.53%) set to NA
NEE: 1546 data points (8.82%) set to NA
-------------------------------------------------------------------
Data filtering:
2832 data points (16.16%) excluded by growing season filter
6124 additional data points (34.95%) excluded by precipitation filter (6876
 data points = 39.25 % in total)
8956 data points (51.12%) excluded in total
8564 valid data points (48.88%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 394 data points (2.25%) set to NA
H: 437 data points (2.49%) set to NA
LE: 444 data points (2.53%) set to NA
NEE: 1546 data points (8.82%) set to NA
-------------------------------------------------------------------
Data filtering:
2832 data points (16.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2832 data points (16.16%) excluded in total
14688 valid data points (83.84%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -53, -51, -64, -67, -61, -57, -63 ...”
New sEddyProc class for site 'CN-Sb2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -53, -51, -64, -67, -61, -57, -63 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Sb2-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 434 data points (2.48%) set to NA
H: 479 data points (2.73%) set to NA
LE: 504 data points (2.88%) set to NA
NEE: 1748 data points (9.98%) set to NA
-------------------------------------------------------------------
Data filtering:
3312 data points (18.9%) excluded by growing season filter
6276 additional data points (35.82%) excluded by precipitation filter (7340
 data points = 41.89 % in total)
9588 data points (54.73%) excluded in total
7932 valid data points (45.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 434 data points (2.48%) set to NA
H: 479 data points (2.73%) set to NA
LE: 504 data points (2.88%) set to NA
NEE: 1748 data points (9.98%) set to NA
-------------------------------------------------------------------
Data filtering:
3312 data points (18.9%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3312 data points (18.9%) excluded in total
14208 valid data points (81.1%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -77, -77, -69, -58 ...”
New sEddyProc class for site 'CN-Sb2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -77, -77, -69, -58 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Sb2-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1560 data points (8.88%) set to NA
H: 1619 data points (9.22%) set to NA
LE: 1619 data points (9.22%) set to NA
NEE: 2823 data points (16.07%) set to NA
-------------------------------------------------------------------
Data filtering:
4752 data points (27.05%) excluded by growing season filter
7168 additional data points (40.8%) excluded by precipitation filter (8356
 data points = 47.56 % in total)
11920 data points (67.85%) excluded in total
5648 valid data points (32.15%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1560 data points (8.88%) set to NA
H: 1619 data points (9.22%) set to NA
LE: 1619 data points (9.22%) set to NA
NEE: 2823 data points (16.07%) set to NA
-------------------------------------------------------------------
Data filtering:
4752 data points (27.05%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4752 data points (27.05%) excluded in total
12816 valid data points (72.95%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -65, -75, -59, -50, -53, -58, -56 ...”
New sEddyProc class for site 'CN-Sb2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -65, -75, -59, -50, -53, -58, -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 166.31.

Regression of reference temperature R_ref for 11 periods.

[66/329] Processing: CN-Sdq

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-Sdq | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 52 data points (0.3%) set to NA
LE: 53 data points (0.3%) set to NA
NEE: 1891 data points (10.79%) set to NA
-------------------------------------------------------------------
Data filtering:
11280 data points (64.38%) excluded by growing season filter
734 additional data points (4.19%) excluded by precipitation filter (1270
 data points = 7.25 % in total)
12014 data points (68.57%) excluded in total
5506 valid data points (31.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 52 data points (0.3%) set to NA
LE: 53 data points (0.3%) set to NA
NEE: 1891 data points (10.79%) set to NA
-------------------------------------------------------------------
Data filtering:
11280 data points (64.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11280 data points (64.38%) excluded in total
6240 valid data points (35.62%) remaining.

New sEddyProc class for site 'CN-Sdq'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Sdq-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 13 data points (0.07%) set to NA
LE: 103 data points (0.59%) set to NA
NEE: 2801 data points (15.99%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
1168 additional data points (6.67%) excluded by precipitation filter (1636
 data points = 9.34 % in total)
11392 data points (65.02%) excluded in total
6128 valid data points (34.98%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 13 data points (0.07%) set to NA
LE: 103 data points (0.59%) set to NA
NEE: 2801 data points (15.99%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10224 data points (58.36%) excluded in total
7296 valid data points (41.64%) remaining.

New sEddyProc class for site 'CN-Sdq'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Sdq-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 9010 data points (51.43%) set to NA
H: 1056 data points (6.03%) set to NA
LE: 1131 data points (6.46%) set to NA
NEE: 6723 data points (38.37%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.15%) excluded by growing season filter
1078 additional data points (6.15%) excluded by precipitation filter (1642
 data points = 9.37 % in total)
10390 data points (59.3%) excluded in total
7130 valid data points (40.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9010 data points (51.43%) set to NA
H: 1056 data points (6.03%) set to NA
LE: 1131 data points (6.46%) set to NA
NEE: 6723 data points (38.37%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9312 data points (53.15%) excluded in total
8208 valid data points (46.85%) remaining.

New sEddyProc class for site 'CN-Sdq'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 98.97.

Regression of reference temperature R_ref for 48 periods.

Quality control:
TA: 10889 data points (61.98%) set to NA
H: 893 data points (5.08%) set to NA
LE: 2146 data points (12.22%) set to NA
NEE: 7949 data points (45.25%) set to NA
-------------------------------------------------------------------
Data filtering:
3792 data points (21.58%) excluded by growing season filter
1100 additional data points (6.26%) excluded by precipitation filter (1100
 data points = 6.26 % in total)
4892 data points (27.85%) excluded in total
12676 valid data points (72.15%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10889 data points (61.98%) set to NA
H: 893 data points (5.08%) set to NA
LE: 2146 data points (12.22%) set to NA
NEE: 7949 data points (45.25%) set to NA
-------------------------------------------------------------------
Data filtering:
3792 data points (21.58%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3792 data points (21.58%) excluded in total
13776 valid data points (78.42%) remaining.

New sEddyProc class for site 'CN-Sdq'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 43.33.

Regression of reference temperature R_ref for 58 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 30 data points (0.17%) set to NA
LE: 455 data points (2.6%) set to NA
NEE: 1039 data points (5.93%) set to NA
-------------------------------------------------------------------
Data filtering:
8784 data points (50.14%) excluded by growing season filter
1012 additional data points (5.78%) excluded by precipitation filter (1120
 data points = 6.39 % in total)
9796 data points (55.91%) excluded in total
7724 valid data points (44.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 30 data points (0.17%) set to NA
LE: 455 data points (2.6%) set to NA
NEE: 1039 data points (5.93%) set to NA
-------------------------------------------------------------------
Data filtering:
8784 data points (50.14%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8784 data points (50.14%) excluded in total
8736 valid data points (49.86%) remaining.

New sEddyProc class for site 'CN-Sdq'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Sdq-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 0 data points (0%) set to NA
LE: 1034 data points (5.9%) set to NA
NEE: 1337 data points (7.63%) set to NA
-------------------------------------------------------------------
Data filtering:
7104 data points (40.55%) excluded by growing season filter
960 additional data points (5.48%) excluded by precipitation filter (1360
 data points = 7.76 % in total)
8064 data points (46.03%) excluded in total
9456 valid data points (53.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 0 data points (0%) set to NA
LE: 1034 data points (5.9%) set to NA
NEE: 1337 data points (7.63%) set to NA
-------------------------------------------------------------------
Data filtering:
7104 data points (40.55%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7104 data points (40.55%) excluded in total
10416 valid data points (59.45%) remaining.

New sEddyProc class for site 'CN-Sdq'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Sdq-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2106 data points (12.02%) set to NA
LE: 3001 data points (17.13%) set to NA
NEE: 4219 data points (24.08%) set to NA
-------------------------------------------------------------------
Data filtering:
6864 data points (39.18%) excluded by growing season filter
1072 additional data points (6.12%) excluded by precipitation filter (1262
 data points = 7.2 % in total)
7936 data points (45.3%) excluded in total
9584 valid data points (54.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2106 data points (12.02%) set to NA
LE: 3001 data points (17.13%) set to NA
NEE: 4219 data points (24.08%) set to NA
-------------------------------------------------------------------
Data filtering:
6864 data points (39.18%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6864 data points (39.18%) excluded in total
10656 valid data points (60.82%) remaining.

New sEddyProc class for site 'CN-Sdq'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Sdq-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 94 data points (0.54%) set to NA
LE: 184 data points (1.05%) set to NA
NEE: 1087 data points (6.19%) set to NA
-------------------------------------------------------------------
Data filtering:
5568 data points (31.69%) excluded by growing season filter
1698 additional data points (9.67%) excluded by precipitation filter (1916
 data points = 10.91 % in total)
7266 data points (41.36%) excluded in total
10302 valid data points (58.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 94 data points (0.54%) set to NA
LE: 184 data points (1.05%) set to NA
NEE: 1087 data points (6.19%) set to NA
-------------------------------------------------------------------
Data filtering:
5568 data points (31.69%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5568 data points (31.69%) excluded in total
12000 valid data points (68.31%) remaining.

New sEddyProc class for site 'CN-Sdq'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Sdq-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[67/329] Processing: CN-SnB

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-SnB | Years: 2021
Quality control:
TA: 2942 data points (16.79%) set to NA
H: 8764 data points (50.02%) set to NA
LE: 8542 data points (48.76%) set to NA
NEE: 9067 data points (51.75%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 158”

-------------------------------------------------------------------
Data filtering:
14736 data points (84.11%) excluded by growing season filter
837 additional data points (4.78%) excluded by precipitation filter (6053
 data points = 34.55 % in total)
15573 data points (88.89%) excluded in total
1947 valid data points (11.11%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2942 data points (16.79%) set to NA
H: 8764 data points (50.02%) set to NA
LE: 8542 data points (48.76%) set to NA
NEE: 9067 data points (51.75%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 158”

-------------------------------------------------------------------
Data filtering:
14736 data points (84.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14736 data points (84.11%) excluded in total
2784 valid data points (15.89%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -51, -56, -57, -50, -51, -52, -50, -51, -57 ...”
New sEddyProc class for site 'CN-SnB'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -51, -56, -57, -50, -51, -52, -50, -51, -57 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-SnB-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[68/329] Processing: CN-YaS

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-YaS | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 0 data points (0%) set to NA
H: 28 data points (0.16%) set to NA
LE: 43 data points (0.25%) set to NA
NEE: 582 data points (3.32%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
1926 additional data points (10.99%) excluded by precipitation filter (2921
 data points = 16.67 % in total)
11862 data points (67.71%) excluded in total
5658 valid data points (32.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 28 data points (0.16%) set to NA
LE: 43 data points (0.25%) set to NA
NEE: 582 data points (3.32%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9936 data points (56.71%) excluded in total
7584 valid data points (43.29%) remaining.

New sEddyProc class for site 'CN-YaS'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-YaS-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 328 data points (1.87%) set to NA
H: 89 data points (0.51%) set to NA
LE: 89 data points (0.51%) set to NA
NEE: 565 data points (3.22%) set to NA
-------------------------------------------------------------------
Data filtering:
10032 data points (57.26%) excluded by growing season filter
2017 additional data points (11.51%) excluded by precipitation filter (2516
 data points = 14.36 % in total)
12049 data points (68.77%) excluded in total
5471 valid data points (31.23%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 328 data points (1.87%) set to NA
H: 89 data points (0.51%) set to NA
LE: 89 data points (0.51%) set to NA
NEE: 565 data points (3.22%) set to NA
-------------------------------------------------------------------
Data filtering:
10032 data points (57.26%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10032 data points (57.26%) excluded in total
7488 valid data points (42.74%) remaining.

New sEddyProc class for site 'CN-YaS'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-YaS-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 312 data points (1.78%) set to NA
H: 174 data points (0.99%) set to NA
LE: 209 data points (1.19%) set to NA
NEE: 746 data points (4.26%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
1518 additional data points (8.66%) excluded by precipitation filter (2581
 data points = 14.73 % in total)
12318 data points (70.31%) excluded in total
5202 valid data points (29.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 312 data points (1.78%) set to NA
H: 174 data points (0.99%) set to NA
LE: 209 data points (1.19%) set to NA
NEE: 746 data points (4.26%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10800 data points (61.64%) excluded in total
6720 valid data points (38.36%) remaining.

New sEddyProc class for site 'CN-YaS'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 211.19.

Regression of reference temperature R_ref for 3 periods.

Quality control:
TA: 7922 data points (45.09%) set to NA
H: 2593 data points (14.76%) set to NA
LE: 2490 data points (14.17%) set to NA
NEE: 5217 data points (29.7%) set to NA
-------------------------------------------------------------------
Data filtering:
12816 data points (72.95%) excluded by growing season filter
923 additional data points (5.25%) excluded by precipitation filter (2646
 data points = 15.06 % in total)
13739 data points (78.2%) excluded in total
3829 valid data points (21.8%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 7922 data points (45.09%) set to NA
H: 2593 data points (14.76%) set to NA
LE: 2490 data points (14.17%) set to NA
NEE: 5217 data points (29.7%) set to NA
-------------------------------------------------------------------
Data filtering:
12816 data points (72.95%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12816 data points (72.95%) excluded in total
4752 valid data points (27.05%) remaining.

New sEddyProc class for site 'CN-YaS'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 78.76.

Regression of reference temperature R_ref for 42 periods.

[69/329] Processing: CN-Yan

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-Yan | Years: 2017, 2018
Quality control:
TA: 2558 data points (14.6%) set to NA
H: 5717 data points (32.63%) set to NA
LE: 5948 data points (33.95%) set to NA
NEE: 6415 data points (36.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 78”

-------------------------------------------------------------------
Data filtering:
6624 data points (37.81%) excluded by growing season filter
2498 additional data points (14.26%) excluded by precipitation filter (3008
 data points = 17.17 % in total)
9122 data points (52.07%) excluded in total
8398 valid data points (47.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 2558 data points (14.6%) set to NA
H: 5717 data points (32.63%) set to NA
LE: 5948 data points (33.95%) set to NA
NEE: 6415 data points (36.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 78”

-------------------------------------------------------------------
Data filtering:
6624 data points (37.81%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6624 data points (37.81%) excluded in total
10896 valid data points (62.19%) remaining.

New sEddyProc class for site 'CN-Yan'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 131.35.

Regression of reference temperature R_ref for 15 periods.

Quality control:
TA: 3787 data points (21.62%) set to NA
H: 4067 data points (23.21%) set to NA
LE: 4087 data points (23.33%) set to NA
NEE: 4168 data points (23.79%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 51”

-------------------------------------------------------------------
Data filtering:
9552 data points (54.52%) excluded by growing season filter
1954 additional data points (11.15%) excluded by precipitation filter (2516
 data points = 14.36 % in total)
11506 data points (65.67%) excluded in total
6014 valid data points (34.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 3787 data points (21.62%) set to NA
H: 4067 data points (23.21%) set to NA
LE: 4087 data points (23.33%) set to NA
NEE: 4168 data points (23.79%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 51”

-------------------------------------------------------------------
Data filtering:
9552 data points (54.52%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9552 data points (54.52%) excluded in total
7968 valid data points (45.48%) remaining.

New sEddyProc class for site 'CN-Yan'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 15 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Yan-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[70/329] Processing: CN-Zha

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CN-Zha | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 216 data points (1.23%) set to NA
H: 96 data points (0.55%) set to NA
LE: 121 data points (0.69%) set to NA
NEE: 598 data points (3.41%) set to NA
-------------------------------------------------------------------
Data filtering:
11904 data points (67.95%) excluded by growing season filter
2078 additional data points (11.86%) excluded by precipitation filter (4000
 data points = 22.83 % in total)
13982 data points (79.81%) excluded in total
3538 valid data points (20.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 216 data points (1.23%) set to NA
H: 96 data points (0.55%) set to NA
LE: 121 data points (0.69%) set to NA
NEE: 598 data points (3.41%) set to NA
-------------------------------------------------------------------
Data filtering:
11904 data points (67.95%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11904 data points (67.95%) excluded in total
5616 valid data points (32.05%) remaining.

New sEddyProc class for site 'CN-Zha'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Zha-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1739 data points (9.93%) set to NA
LE: 1872 data points (10.68%) set to NA
NEE: 2826 data points (16.13%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
2900 additional data points (16.55%) excluded by precipitation filter (4188
 data points = 23.9 % in total)
13124 data points (74.91%) excluded in total
4396 valid data points (25.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1739 data points (9.93%) set to NA
LE: 1872 data points (10.68%) set to NA
NEE: 2826 data points (16.13%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10224 data points (58.36%) excluded in total
7296 valid data points (41.64%) remaining.

New sEddyProc class for site 'CN-Zha'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Zha-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1343 data points (7.67%) set to NA
LE: 1358 data points (7.75%) set to NA
NEE: 1833 data points (10.46%) set to NA
-------------------------------------------------------------------
Data filtering:
11376 data points (64.93%) excluded by growing season filter
1708 additional data points (9.75%) excluded by precipitation filter (3858
 data points = 22.02 % in total)
13084 data points (74.68%) excluded in total
4436 valid data points (25.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1343 data points (7.67%) set to NA
LE: 1358 data points (7.75%) set to NA
NEE: 1833 data points (10.46%) set to NA
-------------------------------------------------------------------
Data filtering:
11376 data points (64.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11376 data points (64.93%) excluded in total
6144 valid data points (35.07%) remaining.

New sEddyProc class for site 'CN-Zha'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Zha-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 183 data points (1.04%) set to NA
H: 0 data points (0%) set to NA
LE: 211 data points (1.2%) set to NA
NEE: 275 data points (1.57%) set to NA
-------------------------------------------------------------------
Data filtering:
11280 data points (64.21%) excluded by growing season filter
2124 additional data points (12.09%) excluded by precipitation filter (3338
 data points = 19 % in total)
13404 data points (76.3%) excluded in total
4164 valid data points (23.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 183 data points (1.04%) set to NA
H: 0 data points (0%) set to NA
LE: 211 data points (1.2%) set to NA
NEE: 275 data points (1.57%) set to NA
-------------------------------------------------------------------
Data filtering:
11280 data points (64.21%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11280 data points (64.21%) excluded in total
6288 valid data points (35.79%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -51 ...”
New sEddyProc class for site 'CN-Zha'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Zha-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 195 data points (1.11%) set to NA
H: 10 data points (0.06%) set to NA
LE: 15 data points (0.09%) set to NA
NEE: 233 data points (1.33%) set to NA
-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
2086 additional data points (11.91%) excluded by precipitation filter (3552
 data points = 20.27 % in total)
13174 data points (75.19%) excluded in total
4346 valid data points (24.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 195 data points (1.11%) set to NA
H: 10 data points (0.06%) set to NA
LE: 15 data points (0.09%) set to NA
NEE: 233 data points (1.33%) set to NA
-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11088 data points (63.29%) excluded in total
6432 valid data points (36.71%) remaining.

New sEddyProc class for site 'CN-Zha'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Zha-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 15 data points (0.09%) set to NA
H: 3 data points (0.02%) set to NA
LE: 119 data points (0.68%) set to NA
NEE: 338 data points (1.93%) set to NA
-------------------------------------------------------------------
Data filtering:
11424 data points (65.21%) excluded by growing season filter
2060 additional data points (11.76%) excluded by precipitation filter (3430
 data points = 19.58 % in total)
13484 data points (76.96%) excluded in total
4036 valid data points (23.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 15 data points (0.09%) set to NA
H: 3 data points (0.02%) set to NA
LE: 119 data points (0.68%) set to NA
NEE: 338 data points (1.93%) set to NA
-------------------------------------------------------------------
Data filtering:
11424 data points (65.21%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11424 data points (65.21%) excluded in total
6096 valid data points (34.79%) remaining.

New sEddyProc class for site 'CN-Zha'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Zha-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 223 data points (1.27%) set to NA
H: 3 data points (0.02%) set to NA
LE: 891 data points (5.09%) set to NA
NEE: 1616 data points (9.22%) set to NA
-------------------------------------------------------------------
Data filtering:
11952 data points (68.22%) excluded by growing season filter
1254 additional data points (7.16%) excluded by precipitation filter (3664
 data points = 20.91 % in total)
13206 data points (75.38%) excluded in total
4314 valid data points (24.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 223 data points (1.27%) set to NA
H: 3 data points (0.02%) set to NA
LE: 891 data points (5.09%) set to NA
NEE: 1616 data points (9.22%) set to NA
-------------------------------------------------------------------
Data filtering:
11952 data points (68.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11952 data points (68.22%) excluded in total
5568 valid data points (31.78%) remaining.

New sEddyProc class for site 'CN-Zha'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Zha-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 155 data points (0.88%) set to NA
H: 113 data points (0.64%) set to NA
LE: 594 data points (3.38%) set to NA
NEE: 1479 data points (8.42%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.66%) excluded by growing season filter
2382 additional data points (13.56%) excluded by precipitation filter (3850
 data points = 21.91 % in total)
13566 data points (77.22%) excluded in total
4002 valid data points (22.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 155 data points (0.88%) set to NA
H: 113 data points (0.64%) set to NA
LE: 594 data points (3.38%) set to NA
NEE: 1479 data points (8.42%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.66%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11184 data points (63.66%) excluded in total
6384 valid data points (36.34%) remaining.

New sEddyProc class for site 'CN-Zha'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CN-Zha-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[71/329] Processing: CZ-BK1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CZ-BK1 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 151 data points (0.86%) set to NA
LE: 115 data points (0.66%) set to NA
NEE: 1041 data points (5.94%) set to NA
-------------------------------------------------------------------
Data filtering:
7824 data points (44.66%) excluded by growing season filter
5011 additional data points (28.6%) excluded by precipitation filter (9261
 data points = 52.86 % in total)
12835 data points (73.26%) excluded in total
4685 valid data points (26.74%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 151 data points (0.86%) set to NA
LE: 115 data points (0.66%) set to NA
NEE: 1041 data points (5.94%) set to NA
-------------------------------------------------------------------
Data filtering:
7824 data points (44.66%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7824 data points (44.66%) excluded in total
9696 valid data points (55.34%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -62 ...”
New sEddyProc class for site 'CZ-BK1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -62 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-BK1-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 25 data points (0.14%) set to NA
LE: 1118 data points (6.38%) set to NA
NEE: 2323 data points (13.26%) set to NA
-------------------------------------------------------------------
Data filtering:
8064 data points (46.03%) excluded by growing season filter
3700 additional data points (21.12%) excluded by precipitation filter (7531
 data points = 42.99 % in total)
11764 data points (67.15%) excluded in total
5756 valid data points (32.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 25 data points (0.14%) set to NA
LE: 1118 data points (6.38%) set to NA
NEE: 2323 data points (13.26%) set to NA
-------------------------------------------------------------------
Data filtering:
8064 data points (46.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8064 data points (46.03%) excluded in total
9456 valid data points (53.97%) remaining.

New sEddyProc class for site 'CZ-BK1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-BK1-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 159 data points (0.91%) set to NA
LE: 119 data points (0.68%) set to NA
NEE: 951 data points (5.43%) set to NA
-------------------------------------------------------------------
Data filtering:
7584 data points (43.29%) excluded by growing season filter
4238 additional data points (24.19%) excluded by precipitation filter (8209
 data points = 46.86 % in total)
11822 data points (67.48%) excluded in total
5698 valid data points (32.52%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 159 data points (0.91%) set to NA
LE: 119 data points (0.68%) set to NA
NEE: 951 data points (5.43%) set to NA
-------------------------------------------------------------------
Data filtering:
7584 data points (43.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7584 data points (43.29%) excluded in total
9936 valid data points (56.71%) remaining.

New sEddyProc class for site 'CZ-BK1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-BK1-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 31 data points (0.18%) set to NA
LE: 133 data points (0.76%) set to NA
NEE: 1090 data points (6.2%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.64%) excluded by growing season filter
3978 additional data points (22.64%) excluded by precipitation filter (8188
 data points = 46.61 % in total)
13050 data points (74.28%) excluded in total
4518 valid data points (25.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 31 data points (0.18%) set to NA
LE: 133 data points (0.76%) set to NA
NEE: 1090 data points (6.2%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9072 data points (51.64%) excluded in total
8496 valid data points (48.36%) remaining.

New sEddyProc class for site 'CZ-BK1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-BK1-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 108 data points (0.62%) set to NA
LE: 264 data points (1.51%) set to NA
NEE: 866 data points (4.94%) set to NA
-------------------------------------------------------------------
Data filtering:
8256 data points (47.12%) excluded by growing season filter
4233 additional data points (24.16%) excluded by precipitation filter (8817
 data points = 50.33 % in total)
12489 data points (71.28%) excluded in total
5031 valid data points (28.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 108 data points (0.62%) set to NA
LE: 264 data points (1.51%) set to NA
NEE: 866 data points (4.94%) set to NA
-------------------------------------------------------------------
Data filtering:
8256 data points (47.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8256 data points (47.12%) excluded in total
9264 valid data points (52.88%) remaining.

New sEddyProc class for site 'CZ-BK1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-BK1-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 16 data points (0.09%) set to NA
LE: 15 data points (0.09%) set to NA
NEE: 791 data points (4.51%) set to NA
-------------------------------------------------------------------
Data filtering:
7824 data points (44.66%) excluded by growing season filter
4624 additional data points (26.39%) excluded by precipitation filter (9150
 data points = 52.23 % in total)
12448 data points (71.05%) excluded in total
5072 valid data points (28.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 16 data points (0.09%) set to NA
LE: 15 data points (0.09%) set to NA
NEE: 791 data points (4.51%) set to NA
-------------------------------------------------------------------
Data filtering:
7824 data points (44.66%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7824 data points (44.66%) excluded in total
9696 valid data points (55.34%) remaining.

New sEddyProc class for site 'CZ-BK1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-BK1-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 110 data points (0.63%) set to NA
H: 397 data points (2.27%) set to NA
LE: 315 data points (1.8%) set to NA
NEE: 891 data points (5.09%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.4%) excluded by growing season filter
3995 additional data points (22.8%) excluded by precipitation filter (9081
 data points = 51.83 % in total)
12299 data points (70.2%) excluded in total
5221 valid data points (29.8%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 110 data points (0.63%) set to NA
H: 397 data points (2.27%) set to NA
LE: 315 data points (1.8%) set to NA
NEE: 891 data points (5.09%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.4%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8304 data points (47.4%) excluded in total
9216 valid data points (52.6%) remaining.

New sEddyProc class for site 'CZ-BK1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-BK1-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 106 data points (0.6%) set to NA
H: 89 data points (0.51%) set to NA
LE: 39 data points (0.22%) set to NA
NEE: 1102 data points (6.27%) set to NA
-------------------------------------------------------------------
Data filtering:
5568 data points (31.69%) excluded by growing season filter
4979 additional data points (28.34%) excluded by precipitation filter (7715
 data points = 43.92 % in total)
10547 data points (60.04%) excluded in total
7021 valid data points (39.96%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 106 data points (0.6%) set to NA
H: 89 data points (0.51%) set to NA
LE: 39 data points (0.22%) set to NA
NEE: 1102 data points (6.27%) set to NA
-------------------------------------------------------------------
Data filtering:
5568 data points (31.69%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5568 data points (31.69%) excluded in total
12000 valid data points (68.31%) remaining.

New sEddyProc class for site 'CZ-BK1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-BK1-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[72/329] Processing: CZ-Lnz

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CZ-Lnz | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 390 data points (2.23%) set to NA
H: 119 data points (0.68%) set to NA
LE: 36 data points (0.21%) set to NA
NEE: 510 data points (2.91%) set to NA
-------------------------------------------------------------------
Data filtering:
9600 data points (54.79%) excluded by growing season filter
2976 additional data points (16.99%) excluded by precipitation filter (6468
 data points = 36.92 % in total)
12576 data points (71.78%) excluded in total
4944 valid data points (28.22%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 390 data points (2.23%) set to NA
H: 119 data points (0.68%) set to NA
LE: 36 data points (0.21%) set to NA
NEE: 510 data points (2.91%) set to NA
-------------------------------------------------------------------
Data filtering:
9600 data points (54.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9600 data points (54.79%) excluded in total
7920 valid data points (45.21%) remaining.

New sEddyProc class for site 'CZ-Lnz'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-Lnz-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2360 data points (13.47%) set to NA
H: 1779 data points (10.15%) set to NA
LE: 1765 data points (10.07%) set to NA
NEE: 2142 data points (12.23%) set to NA
-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
2218 additional data points (12.66%) excluded by precipitation filter (5015
 data points = 28.62 % in total)
11338 data points (64.71%) excluded in total
6182 valid data points (35.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2360 data points (13.47%) set to NA
H: 1779 data points (10.15%) set to NA
LE: 1765 data points (10.07%) set to NA
NEE: 2142 data points (12.23%) set to NA
-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9120 data points (52.05%) excluded in total
8400 valid data points (47.95%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -54, -59 ...”
New sEddyProc class for site 'CZ-Lnz'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -54, -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 249.17.

Regression of reference temperature R_ref for 11 periods.

Quality control:
TA: 6039 data points (34.47%) set to NA
H: 117 data points (0.67%) set to NA
LE: 115 data points (0.66%) set to NA
NEE: 941 data points (5.37%) set to NA
-------------------------------------------------------------------
Data filtering:
9600 data points (54.79%) excluded by growing season filter
3391 additional data points (19.36%) excluded by precipitation filter (6671
 data points = 38.08 % in total)
12991 data points (74.15%) excluded in total
4529 valid data points (25.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6039 data points (34.47%) set to NA
H: 117 data points (0.67%) set to NA
LE: 115 data points (0.66%) set to NA
NEE: 941 data points (5.37%) set to NA
-------------------------------------------------------------------
Data filtering:
9600 data points (54.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9600 data points (54.79%) excluded in total
7920 valid data points (45.21%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
New sEddyProc class for site 'CZ-Lnz'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 209.8.

Regression of reference temperature R_ref for 16 periods.

Quality control:
TA: 78 data points (0.44%) set to NA
H: 87 data points (0.5%) set to NA
LE: 110 data points (0.63%) set to NA
NEE: 658 data points (3.75%) set to NA
-------------------------------------------------------------------
Data filtering:
9264 data points (52.73%) excluded by growing season filter
3488 additional data points (19.85%) excluded by precipitation filter (6888
 data points = 39.21 % in total)
12752 data points (72.59%) excluded in total
4816 valid data points (27.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 78 data points (0.44%) set to NA
H: 87 data points (0.5%) set to NA
LE: 110 data points (0.63%) set to NA
NEE: 658 data points (3.75%) set to NA
-------------------------------------------------------------------
Data filtering:
9264 data points (52.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9264 data points (52.73%) excluded in total
8304 valid data points (47.27%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
New sEddyProc class for site 'CZ-Lnz'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-Lnz-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 58 data points (0.33%) set to NA
LE: 7 data points (0.04%) set to NA
NEE: 202 data points (1.15%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.16%) excluded by growing season filter
2625 additional data points (14.98%) excluded by precipitation filter (5843
 data points = 33.35 % in total)
12465 data points (71.15%) excluded in total
5055 valid data points (28.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 58 data points (0.33%) set to NA
LE: 7 data points (0.04%) set to NA
NEE: 202 data points (1.15%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9840 data points (56.16%) excluded in total
7680 valid data points (43.84%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -52, -66, -51, -63, -51 ...”
New sEddyProc class for site 'CZ-Lnz'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -52, -66, -51, -63, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-Lnz-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6624 data points (37.81%) set to NA
H: 6642 data points (37.91%) set to NA
LE: 6625 data points (37.81%) set to NA
NEE: 6743 data points (38.49%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 117”

-------------------------------------------------------------------
Data filtering:
4560 data points (26.03%) excluded by growing season filter
4839 additional data points (27.62%) excluded by precipitation filter (6504
 data points = 37.12 % in total)
9399 data points (53.65%) excluded in total
8121 valid data points (46.35%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6624 data points (37.81%) set to NA
H: 6642 data points (37.91%) set to NA
LE: 6625 data points (37.81%) set to NA
NEE: 6743 data points (38.49%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 117”

-------------------------------------------------------------------
Data filtering:
4560 data points (26.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4560 data points (26.03%) excluded in total
12960 valid data points (73.97%) remaining.

New sEddyProc class for site 'CZ-Lnz'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-Lnz-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 290 data points (1.66%) set to NA
H: 180 data points (1.03%) set to NA
LE: 142 data points (0.81%) set to NA
NEE: 335 data points (1.91%) set to NA
-------------------------------------------------------------------
Data filtering:
9024 data points (51.51%) excluded by growing season filter
2650 additional data points (15.13%) excluded by precipitation filter (6491
 data points = 37.05 % in total)
11674 data points (66.63%) excluded in total
5846 valid data points (33.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 290 data points (1.66%) set to NA
H: 180 data points (1.03%) set to NA
LE: 142 data points (0.81%) set to NA
NEE: 335 data points (1.91%) set to NA
-------------------------------------------------------------------
Data filtering:
9024 data points (51.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9024 data points (51.51%) excluded in total
8496 valid data points (48.49%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -50, -56 ...”
New sEddyProc class for site 'CZ-Lnz'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -50, -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-Lnz-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6 data points (0.03%) set to NA
H: 80 data points (0.46%) set to NA
LE: 59 data points (0.34%) set to NA
NEE: 226 data points (1.29%) set to NA
-------------------------------------------------------------------
Data filtering:
8832 data points (50.27%) excluded by growing season filter
3072 additional data points (17.49%) excluded by precipitation filter (5860
 data points = 33.36 % in total)
11904 data points (67.76%) excluded in total
5664 valid data points (32.24%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6 data points (0.03%) set to NA
H: 80 data points (0.46%) set to NA
LE: 59 data points (0.34%) set to NA
NEE: 226 data points (1.29%) set to NA
-------------------------------------------------------------------
Data filtering:
8832 data points (50.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8832 data points (50.27%) excluded in total
8736 valid data points (49.73%) remaining.

New sEddyProc class for site 'CZ-Lnz'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-Lnz-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[73/329] Processing: CZ-RAJ

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CZ-RAJ | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 3 data points (0.02%) set to NA
LE: 11 data points (0.06%) set to NA
NEE: 1091 data points (6.23%) set to NA
-------------------------------------------------------------------
Data filtering:
5664 data points (32.33%) excluded by growing season filter
5359 additional data points (30.59%) excluded by precipitation filter (7551
 data points = 43.1 % in total)
11023 data points (62.92%) excluded in total
6497 valid data points (37.08%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 3 data points (0.02%) set to NA
LE: 11 data points (0.06%) set to NA
NEE: 1091 data points (6.23%) set to NA
-------------------------------------------------------------------
Data filtering:
5664 data points (32.33%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5664 data points (32.33%) excluded in total
11856 valid data points (67.67%) remaining.

New sEddyProc class for site 'CZ-RAJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-RAJ-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2 data points (0.01%) set to NA
LE: 2 data points (0.01%) set to NA
NEE: 1011 data points (5.77%) set to NA
-------------------------------------------------------------------
Data filtering:
7488 data points (42.74%) excluded by growing season filter
3483 additional data points (19.88%) excluded by precipitation filter (6564
 data points = 37.47 % in total)
10971 data points (62.62%) excluded in total
6549 valid data points (37.38%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2 data points (0.01%) set to NA
LE: 2 data points (0.01%) set to NA
NEE: 1011 data points (5.77%) set to NA
-------------------------------------------------------------------
Data filtering:
7488 data points (42.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7488 data points (42.74%) excluded in total
10032 valid data points (57.26%) remaining.

New sEddyProc class for site 'CZ-RAJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-RAJ-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 0 data points (0%) set to NA
LE: 6 data points (0.03%) set to NA
NEE: 887 data points (5.06%) set to NA
-------------------------------------------------------------------
Data filtering:
5904 data points (33.7%) excluded by growing season filter
4664 additional data points (26.62%) excluded by precipitation filter (7378
 data points = 42.11 % in total)
10568 data points (60.32%) excluded in total
6952 valid data points (39.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 0 data points (0%) set to NA
LE: 6 data points (0.03%) set to NA
NEE: 887 data points (5.06%) set to NA
-------------------------------------------------------------------
Data filtering:
5904 data points (33.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5904 data points (33.7%) excluded in total
11616 valid data points (66.3%) remaining.

New sEddyProc class for site 'CZ-RAJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-RAJ-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 12 data points (0.07%) set to NA
NEE: 855 data points (4.87%) set to NA
-------------------------------------------------------------------
Data filtering:
6624 data points (37.7%) excluded by growing season filter
4386 additional data points (24.97%) excluded by precipitation filter (6858
 data points = 39.04 % in total)
11010 data points (62.67%) excluded in total
6558 valid data points (37.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 12 data points (0.07%) set to NA
NEE: 855 data points (4.87%) set to NA
-------------------------------------------------------------------
Data filtering:
6624 data points (37.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6624 data points (37.7%) excluded in total
10944 valid data points (62.3%) remaining.

New sEddyProc class for site 'CZ-RAJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-RAJ-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 11 data points (0.06%) set to NA
LE: 12 data points (0.07%) set to NA
NEE: 1320 data points (7.53%) set to NA
-------------------------------------------------------------------
Data filtering:
7008 data points (40%) excluded by growing season filter
4612 additional data points (26.32%) excluded by precipitation filter (7745
 data points = 44.21 % in total)
11620 data points (66.32%) excluded in total
5900 valid data points (33.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 11 data points (0.06%) set to NA
LE: 12 data points (0.07%) set to NA
NEE: 1320 data points (7.53%) set to NA
-------------------------------------------------------------------
Data filtering:
7008 data points (40%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7008 data points (40%) excluded in total
10512 valid data points (60%) remaining.

New sEddyProc class for site 'CZ-RAJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-RAJ-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 6 data points (0.03%) set to NA
LE: 11 data points (0.06%) set to NA
NEE: 1157 data points (6.6%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.4%) excluded by growing season filter
4145 additional data points (23.66%) excluded by precipitation filter (7645
 data points = 43.64 % in total)
12449 data points (71.06%) excluded in total
5071 valid data points (28.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 6 data points (0.03%) set to NA
LE: 11 data points (0.06%) set to NA
NEE: 1157 data points (6.6%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.4%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8304 data points (47.4%) excluded in total
9216 valid data points (52.6%) remaining.

New sEddyProc class for site 'CZ-RAJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-RAJ-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 9 data points (0.05%) set to NA
LE: 13 data points (0.07%) set to NA
NEE: 1578 data points (9.01%) set to NA
-------------------------------------------------------------------
Data filtering:
8448 data points (48.22%) excluded by growing season filter
3554 additional data points (20.29%) excluded by precipitation filter (7910
 data points = 45.15 % in total)
12002 data points (68.5%) excluded in total
5518 valid data points (31.5%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 9 data points (0.05%) set to NA
LE: 13 data points (0.07%) set to NA
NEE: 1578 data points (9.01%) set to NA
-------------------------------------------------------------------
Data filtering:
8448 data points (48.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8448 data points (48.22%) excluded in total
9072 valid data points (51.78%) remaining.

New sEddyProc class for site 'CZ-RAJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-RAJ-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 66 data points (0.38%) set to NA
LE: 38 data points (0.22%) set to NA
NEE: 1832 data points (10.43%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.47%) excluded by growing season filter
3340 additional data points (19.01%) excluded by precipitation filter (7464
 data points = 42.49 % in total)
13612 data points (77.48%) excluded in total
3956 valid data points (22.52%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 66 data points (0.38%) set to NA
LE: 38 data points (0.22%) set to NA
NEE: 1832 data points (10.43%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10272 data points (58.47%) excluded in total
7296 valid data points (41.53%) remaining.

New sEddyProc class for site 'CZ-RAJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-RAJ-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[74/329] Processing: CZ-Stn

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CZ-Stn | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 19 data points (0.11%) set to NA
LE: 112 data points (0.64%) set to NA
NEE: 1263 data points (7.21%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
3011 additional data points (17.19%) excluded by precipitation filter (6996
 data points = 39.93 % in total)
12947 data points (73.9%) excluded in total
4573 valid data points (26.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 19 data points (0.11%) set to NA
LE: 112 data points (0.64%) set to NA
NEE: 1263 data points (7.21%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9936 data points (56.71%) excluded in total
7584 valid data points (43.29%) remaining.

New sEddyProc class for site 'CZ-Stn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-Stn-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 3 data points (0.02%) set to NA
LE: 5 data points (0.03%) set to NA
NEE: 1470 data points (8.39%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
2446 additional data points (13.96%) excluded by precipitation filter (5700
 data points = 32.53 % in total)
11806 data points (67.39%) excluded in total
5714 valid data points (32.61%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 3 data points (0.02%) set to NA
LE: 5 data points (0.03%) set to NA
NEE: 1470 data points (8.39%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9360 data points (53.42%) excluded in total
8160 valid data points (46.58%) remaining.

New sEddyProc class for site 'CZ-Stn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-Stn-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 132 data points (0.75%) set to NA
LE: 9 data points (0.05%) set to NA
NEE: 993 data points (5.67%) set to NA
-------------------------------------------------------------------
Data filtering:
9648 data points (55.07%) excluded by growing season filter
3378 additional data points (19.28%) excluded by precipitation filter (7673
 data points = 43.8 % in total)
13026 data points (74.35%) excluded in total
4494 valid data points (25.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 132 data points (0.75%) set to NA
LE: 9 data points (0.05%) set to NA
NEE: 993 data points (5.67%) set to NA
-------------------------------------------------------------------
Data filtering:
9648 data points (55.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9648 data points (55.07%) excluded in total
7872 valid data points (44.93%) remaining.

New sEddyProc class for site 'CZ-Stn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-Stn-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 524 data points (2.98%) set to NA
LE: 27 data points (0.15%) set to NA
NEE: 1495 data points (8.51%) set to NA
-------------------------------------------------------------------
Data filtering:
10032 data points (57.1%) excluded by growing season filter
3409 additional data points (19.4%) excluded by precipitation filter (7181
 data points = 40.88 % in total)
13441 data points (76.51%) excluded in total
4127 valid data points (23.49%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 524 data points (2.98%) set to NA
LE: 27 data points (0.15%) set to NA
NEE: 1495 data points (8.51%) set to NA
-------------------------------------------------------------------
Data filtering:
10032 data points (57.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10032 data points (57.1%) excluded in total
7536 valid data points (42.9%) remaining.

New sEddyProc class for site 'CZ-Stn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-Stn-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 121 data points (0.69%) set to NA
LE: 94 data points (0.54%) set to NA
NEE: 1468 data points (8.38%) set to NA
-------------------------------------------------------------------
Data filtering:
10368 data points (59.18%) excluded by growing season filter
2624 additional data points (14.98%) excluded by precipitation filter (7122
 data points = 40.65 % in total)
12992 data points (74.16%) excluded in total
4528 valid data points (25.84%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 121 data points (0.69%) set to NA
LE: 94 data points (0.54%) set to NA
NEE: 1468 data points (8.38%) set to NA
-------------------------------------------------------------------
Data filtering:
10368 data points (59.18%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10368 data points (59.18%) excluded in total
7152 valid data points (40.82%) remaining.

New sEddyProc class for site 'CZ-Stn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-Stn-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 123 data points (0.7%) set to NA
LE: 129 data points (0.74%) set to NA
NEE: 1364 data points (7.79%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
3160 additional data points (18.04%) excluded by precipitation filter (7301
 data points = 41.67 % in total)
13384 data points (76.39%) excluded in total
4136 valid data points (23.61%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 123 data points (0.7%) set to NA
LE: 129 data points (0.74%) set to NA
NEE: 1364 data points (7.79%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10224 data points (58.36%) excluded in total
7296 valid data points (41.64%) remaining.

New sEddyProc class for site 'CZ-Stn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-Stn-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 413 data points (2.36%) set to NA
LE: 420 data points (2.4%) set to NA
NEE: 2007 data points (11.46%) set to NA
-------------------------------------------------------------------
Data filtering:
10176 data points (58.08%) excluded by growing season filter
2524 additional data points (14.41%) excluded by precipitation filter (8103
 data points = 46.25 % in total)
12700 data points (72.49%) excluded in total
4820 valid data points (27.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 413 data points (2.36%) set to NA
LE: 420 data points (2.4%) set to NA
NEE: 2007 data points (11.46%) set to NA
-------------------------------------------------------------------
Data filtering:
10176 data points (58.08%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10176 data points (58.08%) excluded in total
7344 valid data points (41.92%) remaining.

New sEddyProc class for site 'CZ-Stn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-Stn-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 23 data points (0.13%) set to NA
LE: 16 data points (0.09%) set to NA
NEE: 1229 data points (7%) set to NA
-------------------------------------------------------------------
Data filtering:
9888 data points (56.28%) excluded by growing season filter
3028 additional data points (17.24%) excluded by precipitation filter (7034
 data points = 40.04 % in total)
12916 data points (73.52%) excluded in total
4652 valid data points (26.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 23 data points (0.13%) set to NA
LE: 16 data points (0.09%) set to NA
NEE: 1229 data points (7%) set to NA
-------------------------------------------------------------------
Data filtering:
9888 data points (56.28%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9888 data points (56.28%) excluded in total
7680 valid data points (43.72%) remaining.

New sEddyProc class for site 'CZ-Stn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-Stn-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[75/329] Processing: CZ-wet

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: CZ-wet | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 3035 data points (17.32%) set to NA
H: 24 data points (0.14%) set to NA
LE: 32 data points (0.18%) set to NA
NEE: 458 data points (2.61%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.27%) excluded by growing season filter
3245 additional data points (18.52%) excluded by precipitation filter (7582
 data points = 43.28 % in total)
13805 data points (78.8%) excluded in total
3715 valid data points (21.2%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3035 data points (17.32%) set to NA
H: 24 data points (0.14%) set to NA
LE: 32 data points (0.18%) set to NA
NEE: 458 data points (2.61%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10560 data points (60.27%) excluded in total
6960 valid data points (39.73%) remaining.

New sEddyProc class for site 'CZ-wet'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-wet-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2 data points (0.01%) set to NA
LE: 5 data points (0.03%) set to NA
NEE: 338 data points (1.93%) set to NA
-------------------------------------------------------------------
Data filtering:
10368 data points (59.18%) excluded by growing season filter
3014 additional data points (17.2%) excluded by precipitation filter (6700
 data points = 38.24 % in total)
13382 data points (76.38%) excluded in total
4138 valid data points (23.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2 data points (0.01%) set to NA
LE: 5 data points (0.03%) set to NA
NEE: 338 data points (1.93%) set to NA
-------------------------------------------------------------------
Data filtering:
10368 data points (59.18%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10368 data points (59.18%) excluded in total
7152 valid data points (40.82%) remaining.

New sEddyProc class for site 'CZ-wet'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-wet-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1 data points (0.01%) set to NA
H: 54 data points (0.31%) set to NA
LE: 68 data points (0.39%) set to NA
NEE: 517 data points (2.95%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
2432 additional data points (13.88%) excluded by precipitation filter (6642
 data points = 37.91 % in total)
13568 data points (77.44%) excluded in total
3952 valid data points (22.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1 data points (0.01%) set to NA
H: 54 data points (0.31%) set to NA
LE: 68 data points (0.39%) set to NA
NEE: 517 data points (2.95%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11136 data points (63.56%) excluded in total
6384 valid data points (36.44%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -58, -76 ...”
New sEddyProc class for site 'CZ-wet'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -58, -76 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-wet-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 340 data points (1.94%) set to NA
H: 40 data points (0.23%) set to NA
LE: 34 data points (0.19%) set to NA
NEE: 565 data points (3.22%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.48%) excluded by growing season filter
3799 additional data points (21.62%) excluded by precipitation filter (9478
 data points = 53.95 % in total)
14599 data points (83.1%) excluded in total
2969 valid data points (16.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 340 data points (1.94%) set to NA
H: 40 data points (0.23%) set to NA
LE: 34 data points (0.19%) set to NA
NEE: 565 data points (3.22%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.48%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10800 data points (61.48%) excluded in total
6768 valid data points (38.52%) remaining.

New sEddyProc class for site 'CZ-wet'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-wet-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 58 data points (0.33%) set to NA
LE: 59 data points (0.34%) set to NA
NEE: 515 data points (2.94%) set to NA
-------------------------------------------------------------------
Data filtering:
11280 data points (64.38%) excluded by growing season filter
3243 additional data points (18.51%) excluded by precipitation filter (7258
 data points = 41.43 % in total)
14523 data points (82.89%) excluded in total
2997 valid data points (17.11%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 58 data points (0.33%) set to NA
LE: 59 data points (0.34%) set to NA
NEE: 515 data points (2.94%) set to NA
-------------------------------------------------------------------
Data filtering:
11280 data points (64.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11280 data points (64.38%) excluded in total
6240 valid data points (35.62%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
New sEddyProc class for site 'CZ-wet'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-wet-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 236 data points (1.35%) set to NA
LE: 271 data points (1.55%) set to NA
NEE: 881 data points (5.03%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.73%) excluded by growing season filter
3605 additional data points (20.58%) excluded by precipitation filter (7508
 data points = 42.85 % in total)
14069 data points (80.3%) excluded in total
3451 valid data points (19.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 236 data points (1.35%) set to NA
LE: 271 data points (1.55%) set to NA
NEE: 881 data points (5.03%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10464 data points (59.73%) excluded in total
7056 valid data points (40.27%) remaining.

New sEddyProc class for site 'CZ-wet'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-wet-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 158 data points (0.9%) set to NA
H: 83 data points (0.47%) set to NA
LE: 102 data points (0.58%) set to NA
NEE: 784 data points (4.47%) set to NA
-------------------------------------------------------------------
Data filtering:
10752 data points (61.37%) excluded by growing season filter
2873 additional data points (16.4%) excluded by precipitation filter (7603
 data points = 43.4 % in total)
13625 data points (77.77%) excluded in total
3895 valid data points (22.23%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 158 data points (0.9%) set to NA
H: 83 data points (0.47%) set to NA
LE: 102 data points (0.58%) set to NA
NEE: 784 data points (4.47%) set to NA
-------------------------------------------------------------------
Data filtering:
10752 data points (61.37%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10752 data points (61.37%) excluded in total
6768 valid data points (38.63%) remaining.

New sEddyProc class for site 'CZ-wet'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-wet-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 66 data points (0.38%) set to NA
H: 26 data points (0.15%) set to NA
LE: 53 data points (0.3%) set to NA
NEE: 509 data points (2.9%) set to NA
-------------------------------------------------------------------
Data filtering:
10704 data points (60.93%) excluded by growing season filter
3224 additional data points (18.35%) excluded by precipitation filter (7660
 data points = 43.6 % in total)
13928 data points (79.28%) excluded in total
3640 valid data points (20.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 66 data points (0.38%) set to NA
H: 26 data points (0.15%) set to NA
LE: 53 data points (0.3%) set to NA
NEE: 509 data points (2.9%) set to NA
-------------------------------------------------------------------
Data filtering:
10704 data points (60.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10704 data points (60.93%) excluded in total
6864 valid data points (39.07%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
New sEddyProc class for site 'CZ-wet'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for CZ-wet-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[76/329] Processing: DE-Akm

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DE-Akm | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 9326 data points (53.23%) set to NA
H: 9449 data points (53.93%) set to NA
LE: 9642 data points (55.03%) set to NA
NEE: 10194 data points (58.18%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 160”

-------------------------------------------------------------------
Data filtering:
2208 data points (12.6%) excluded by growing season filter
10406 additional data points (59.39%) excluded by precipitation filter (12060
 data points = 68.84 % in total)
12614 data points (72%) excluded in total
4906 valid data points (28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9326 data points (53.23%) set to NA
H: 9449 data points (53.93%) set to NA
LE: 9642 data points (55.03%) set to NA
NEE: 10194 data points (58.18%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 160”

-------------------------------------------------------------------
Data filtering:
2208 data points (12.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2208 data points (12.6%) excluded in total
15312 valid data points (87.4%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -58, -50, -59 ...”
New sEddyProc class for site 'DE-Akm'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -58, -50, -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 107.44.

Regression of reference temperature R_ref for 31 periods.

Quality control:
TA: 10105 data points (57.68%) set to NA
H: 11175 data points (63.78%) set to NA
LE: 11482 data points (65.54%) set to NA
NEE: 11691 data points (66.73%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 163”

-------------------------------------------------------------------
Data filtering:
2064 data points (11.78%) excluded by growing season filter
8344 additional data points (47.63%) excluded by precipitation filter (9532
 data points = 54.41 % in total)
10408 data points (59.41%) excluded in total
7112 valid data points (40.59%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10105 data points (57.68%) set to NA
H: 11175 data points (63.78%) set to NA
LE: 11482 data points (65.54%) set to NA
NEE: 11691 data points (66.73%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 163”

-------------------------------------------------------------------
Data filtering:
2064 data points (11.78%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2064 data points (11.78%) excluded in total
15456 valid data points (88.22%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
New sEddyProc class for site 'DE-Akm'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 81.98.

Regression of reference temperature R_ref for 24 periods.

Quality control:
TA: 12879 data points (73.51%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 17520 data points (100%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
11558 additional data points (65.97%) excluded by precipitation filter (11558
 data points = 65.97 % in total)
11558 data points (65.97%) excluded in total
5962 valid data points (34.03%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for DE-Akm-2019”

Quality control:
TA: 111 data points (0.63%) set to NA
H: 9588 data points (54.58%) set to NA
LE: 9663 data points (55%) set to NA
NEE: 9864 data points (56.15%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 106”

-------------------------------------------------------------------
Data filtering:
4560 data points (25.96%) excluded by growing season filter
7764 additional data points (44.19%) excluded by precipitation filter (10840
 data points = 61.7 % in total)
12324 data points (70.15%) excluded in total
5244 valid data points (29.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 111 data points (0.63%) set to NA
H: 9588 data points (54.58%) set to NA
LE: 9663 data points (55%) set to NA
NEE: 9864 data points (56.15%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 106”

-------------------------------------------------------------------
Data filtering:
4560 data points (25.96%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4560 data points (25.96%) excluded in total
13008 valid data points (74.04%) remaining.

New sEddyProc class for site 'DE-Akm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Akm-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 520 data points (2.97%) set to NA
H: 9149 data points (52.22%) set to NA
LE: 9198 data points (52.5%) set to NA
NEE: 9322 data points (53.21%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 111”

-------------------------------------------------------------------
Data filtering:
7344 data points (41.92%) excluded by growing season filter
7094 additional data points (40.49%) excluded by precipitation filter (12612
 data points = 71.99 % in total)
14438 data points (82.41%) excluded in total
3082 valid data points (17.59%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 520 data points (2.97%) set to NA
H: 9149 data points (52.22%) set to NA
LE: 9198 data points (52.5%) set to NA
NEE: 9322 data points (53.21%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 111”

-------------------------------------------------------------------
Data filtering:
7344 data points (41.92%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7344 data points (41.92%) excluded in total
10176 valid data points (58.08%) remaining.

New sEddyProc class for site 'DE-Akm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Akm-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 191 data points (1.09%) set to NA
H: 8313 data points (47.45%) set to NA
LE: 8373 data points (47.79%) set to NA
NEE: 8518 data points (48.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 111”

-------------------------------------------------------------------
Data filtering:
6672 data points (38.08%) excluded by growing season filter
6892 additional data points (39.34%) excluded by precipitation filter (10074
 data points = 57.5 % in total)
13564 data points (77.42%) excluded in total
3956 valid data points (22.58%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 191 data points (1.09%) set to NA
H: 8313 data points (47.45%) set to NA
LE: 8373 data points (47.79%) set to NA
NEE: 8518 data points (48.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 111”

-------------------------------------------------------------------
Data filtering:
6672 data points (38.08%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6672 data points (38.08%) excluded in total
10848 valid data points (61.92%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
New sEddyProc class for site 'DE-Akm'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Akm-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2495 data points (14.24%) set to NA
H: 6803 data points (38.83%) set to NA
LE: 6848 data points (39.09%) set to NA
NEE: 7092 data points (40.48%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 51”

-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
4374 additional data points (24.97%) excluded by precipitation filter (11602
 data points = 66.22 % in total)
14310 data points (81.68%) excluded in total
3210 valid data points (18.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2495 data points (14.24%) set to NA
H: 6803 data points (38.83%) set to NA
LE: 6848 data points (39.09%) set to NA
NEE: 7092 data points (40.48%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 51”

-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9936 data points (56.71%) excluded in total
7584 valid data points (43.29%) remaining.

New sEddyProc class for site 'DE-Akm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 19 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Akm-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 9736 data points (55.42%) set to NA
H: 10178 data points (57.93%) set to NA
LE: 10208 data points (58.11%) set to NA
NEE: 10364 data points (58.99%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 133”

-------------------------------------------------------------------
Data filtering:
8976 data points (51.09%) excluded by growing season filter
5498 additional data points (31.3%) excluded by precipitation filter (10870
 data points = 61.87 % in total)
14474 data points (82.39%) excluded in total
3094 valid data points (17.61%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9736 data points (55.42%) set to NA
H: 10178 data points (57.93%) set to NA
LE: 10208 data points (58.11%) set to NA
NEE: 10364 data points (58.99%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 133”

-------------------------------------------------------------------
Data filtering:
8976 data points (51.09%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8976 data points (51.09%) excluded in total
8592 valid data points (48.91%) remaining.

New sEddyProc class for site 'DE-Akm'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 63.02.

Regression of reference temperature R_ref for 39 periods.

[77/329] Processing: DE-Amv

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DE-Amv | Years: 2023, 2024
Quality control:
TA: 1064 data points (6.07%) set to NA
H: 1010 data points (5.76%) set to NA
LE: 1012 data points (5.78%) set to NA
NEE: 1436 data points (8.2%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
2530 additional data points (14.44%) excluded by precipitation filter (8300
 data points = 47.37 % in total)
12466 data points (71.15%) excluded in total
5054 valid data points (28.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1064 data points (6.07%) set to NA
H: 1010 data points (5.76%) set to NA
LE: 1012 data points (5.78%) set to NA
NEE: 1436 data points (8.2%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9936 data points (56.71%) excluded in total
7584 valid data points (43.29%) remaining.

New sEddyProc class for site 'DE-Amv'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 96.15.

Regression of reference temperature R_ref for 6 periods.

Quality control:
TA: 1267 data points (7.21%) set to NA
H: 560 data points (3.19%) set to NA
LE: 574 data points (3.27%) set to NA
NEE: 865 data points (4.92%) set to NA
-------------------------------------------------------------------
Data filtering:
10032 data points (57.1%) excluded by growing season filter
3557 additional data points (20.25%) excluded by precipitation filter (8870
 data points = 50.49 % in total)
13589 data points (77.35%) excluded in total
3979 valid data points (22.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1267 data points (7.21%) set to NA
H: 560 data points (3.19%) set to NA
LE: 574 data points (3.27%) set to NA
NEE: 865 data points (4.92%) set to NA
-------------------------------------------------------------------
Data filtering:
10032 data points (57.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10032 data points (57.1%) excluded in total
7536 valid data points (42.9%) remaining.

New sEddyProc class for site 'DE-Amv'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 112.57.

Regression of reference temperature R_ref for 11 periods.

[78/329] Processing: DE-Etn

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DE-Etn | Years: 2024
Quality control:
TA: 6488 data points (36.93%) set to NA
H: 6154 data points (35.03%) set to NA
LE: 6213 data points (35.37%) set to NA
NEE: 7419 data points (42.23%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 117”

-------------------------------------------------------------------
Data filtering:
3696 data points (21.04%) excluded by growing season filter
9948 additional data points (56.63%) excluded by precipitation filter (11816
 data points = 67.26 % in total)
13644 data points (77.66%) excluded in total
3924 valid data points (22.34%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6488 data points (36.93%) set to NA
H: 6154 data points (35.03%) set to NA
LE: 6213 data points (35.37%) set to NA
NEE: 7419 data points (42.23%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 117”

-------------------------------------------------------------------
Data filtering:
3696 data points (21.04%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3696 data points (21.04%) excluded in total
13872 valid data points (78.96%) remaining.

New sEddyProc class for site 'DE-Etn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Etn-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[79/329] Processing: DE-Hai

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DE-Hai | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 142 data points (0.81%) set to NA
LE: 118 data points (0.67%) set to NA
NEE: 870 data points (4.97%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
3116 additional data points (17.79%) excluded by precipitation filter (7694
 data points = 43.92 % in total)
13916 data points (79.43%) excluded in total
3604 valid data points (20.57%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 142 data points (0.81%) set to NA
LE: 118 data points (0.67%) set to NA
NEE: 870 data points (4.97%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10800 data points (61.64%) excluded in total
6720 valid data points (38.36%) remaining.

New sEddyProc class for site 'DE-Hai'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Hai-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1506 data points (8.6%) set to NA
LE: 1509 data points (8.61%) set to NA
NEE: 2477 data points (14.14%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
1559 additional data points (8.9%) excluded by precipitation filter (5791
 data points = 33.05 % in total)
12695 data points (72.46%) excluded in total
4825 valid data points (27.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1506 data points (8.6%) set to NA
LE: 1509 data points (8.61%) set to NA
NEE: 2477 data points (14.14%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11136 data points (63.56%) excluded in total
6384 valid data points (36.44%) remaining.

New sEddyProc class for site 'DE-Hai'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Hai-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1682 data points (9.6%) set to NA
LE: 2323 data points (13.26%) set to NA
NEE: 3193 data points (18.22%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.53%) excluded by growing season filter
4019 additional data points (22.94%) excluded by precipitation filter (8685
 data points = 49.57 % in total)
14099 data points (80.47%) excluded in total
3421 valid data points (19.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1682 data points (9.6%) set to NA
LE: 2323 data points (13.26%) set to NA
NEE: 3193 data points (18.22%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.53%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10080 data points (57.53%) excluded in total
7440 valid data points (42.47%) remaining.

New sEddyProc class for site 'DE-Hai'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Hai-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 141 data points (0.8%) set to NA
H: 378 data points (2.15%) set to NA
LE: 485 data points (2.76%) set to NA
NEE: 1789 data points (10.18%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.74%) excluded by growing season filter
2419 additional data points (13.77%) excluded by precipitation filter (6645
 data points = 37.82 % in total)
12211 data points (69.51%) excluded in total
5357 valid data points (30.49%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 141 data points (0.8%) set to NA
H: 378 data points (2.15%) set to NA
LE: 485 data points (2.76%) set to NA
NEE: 1789 data points (10.18%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9792 data points (55.74%) excluded in total
7776 valid data points (44.26%) remaining.

New sEddyProc class for site 'DE-Hai'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Hai-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 85 data points (0.49%) set to NA
H: 5480 data points (31.28%) set to NA
LE: 5521 data points (31.51%) set to NA
NEE: 7200 data points (41.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 82”

-------------------------------------------------------------------
Data filtering:
6336 data points (36.16%) excluded by growing season filter
6268 additional data points (35.78%) excluded by precipitation filter (9376
 data points = 53.52 % in total)
12604 data points (71.94%) excluded in total
4916 valid data points (28.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 85 data points (0.49%) set to NA
H: 5480 data points (31.28%) set to NA
LE: 5521 data points (31.51%) set to NA
NEE: 7200 data points (41.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 82”

-------------------------------------------------------------------
Data filtering:
6336 data points (36.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6336 data points (36.16%) excluded in total
11184 valid data points (63.84%) remaining.

New sEddyProc class for site 'DE-Hai'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Hai-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 267 data points (1.52%) set to NA
H: 2378 data points (13.57%) set to NA
LE: 2425 data points (13.84%) set to NA
NEE: 4310 data points (24.6%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 11”

-------------------------------------------------------------------
Data filtering:
9552 data points (54.52%) excluded by growing season filter
3013 additional data points (17.2%) excluded by precipitation filter (7606
 data points = 43.41 % in total)
12565 data points (71.72%) excluded in total
4955 valid data points (28.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 267 data points (1.52%) set to NA
H: 2378 data points (13.57%) set to NA
LE: 2425 data points (13.84%) set to NA
NEE: 4310 data points (24.6%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 11”

-------------------------------------------------------------------
Data filtering:
9552 data points (54.52%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9552 data points (54.52%) excluded in total
7968 valid data points (45.48%) remaining.

New sEddyProc class for site 'DE-Hai'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Hai-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2305 data points (13.16%) set to NA
H: 3312 data points (18.9%) set to NA
LE: 6969 data points (39.78%) set to NA
NEE: 7697 data points (43.93%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 70”

-------------------------------------------------------------------
Data filtering:
6432 data points (36.71%) excluded by growing season filter
4915 additional data points (28.05%) excluded by precipitation filter (9144
 data points = 52.19 % in total)
11347 data points (64.77%) excluded in total
6173 valid data points (35.23%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2305 data points (13.16%) set to NA
H: 3312 data points (18.9%) set to NA
LE: 6969 data points (39.78%) set to NA
NEE: 7697 data points (43.93%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 70”

-------------------------------------------------------------------
Data filtering:
6432 data points (36.71%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6432 data points (36.71%) excluded in total
11088 valid data points (63.29%) remaining.

New sEddyProc class for site 'DE-Hai'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 12 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Hai-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 12354 data points (70.32%) set to NA
H: 1520 data points (8.65%) set to NA
LE: 3315 data points (18.87%) set to NA
NEE: 4637 data points (26.39%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.01%) excluded by growing season filter
3399 additional data points (19.35%) excluded by precipitation filter (7616
 data points = 43.35 % in total)
12711 data points (72.35%) excluded in total
4857 valid data points (27.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12354 data points (70.32%) set to NA
H: 1520 data points (8.65%) set to NA
LE: 3315 data points (18.87%) set to NA
NEE: 4637 data points (26.39%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.01%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9312 data points (53.01%) excluded in total
8256 valid data points (46.99%) remaining.

New sEddyProc class for site 'DE-Hai'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 128.96.

Regression of reference temperature R_ref for 32 periods.

[80/329] Processing: DE-Har

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DE-Har | Years: 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 928 data points (5.28%) set to NA
H: 327 data points (1.86%) set to NA
LE: 327 data points (1.86%) set to NA
NEE: 1761 data points (10.02%) set to NA
-------------------------------------------------------------------
Data filtering:
8160 data points (46.45%) excluded by growing season filter
2578 additional data points (14.67%) excluded by precipitation filter (4779
 data points = 27.2 % in total)
10738 data points (61.12%) excluded in total
6830 valid data points (38.88%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 928 data points (5.28%) set to NA
H: 327 data points (1.86%) set to NA
LE: 327 data points (1.86%) set to NA
NEE: 1761 data points (10.02%) set to NA
-------------------------------------------------------------------
Data filtering:
8160 data points (46.45%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8160 data points (46.45%) excluded in total
9408 valid data points (53.55%) remaining.

New sEddyProc class for site 'DE-Har'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Har-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 177 data points (1.01%) set to NA
LE: 184 data points (1.05%) set to NA
NEE: 919 data points (5.25%) set to NA
-------------------------------------------------------------------
Data filtering:
9264 data points (52.88%) excluded by growing season filter
3608 additional data points (20.59%) excluded by precipitation filter (6899
 data points = 39.38 % in total)
12872 data points (73.47%) excluded in total
4648 valid data points (26.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 177 data points (1.01%) set to NA
LE: 184 data points (1.05%) set to NA
NEE: 919 data points (5.25%) set to NA
-------------------------------------------------------------------
Data filtering:
9264 data points (52.88%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9264 data points (52.88%) excluded in total
8256 valid data points (47.12%) remaining.

New sEddyProc class for site 'DE-Har'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Har-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 63 data points (0.36%) set to NA
H: 242 data points (1.38%) set to NA
LE: 258 data points (1.47%) set to NA
NEE: 1302 data points (7.43%) set to NA
-------------------------------------------------------------------
Data filtering:
8496 data points (48.49%) excluded by growing season filter
3137 additional data points (17.91%) excluded by precipitation filter (5956
 data points = 34 % in total)
11633 data points (66.4%) excluded in total
5887 valid data points (33.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 63 data points (0.36%) set to NA
H: 242 data points (1.38%) set to NA
LE: 258 data points (1.47%) set to NA
NEE: 1302 data points (7.43%) set to NA
-------------------------------------------------------------------
Data filtering:
8496 data points (48.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8496 data points (48.49%) excluded in total
9024 valid data points (51.51%) remaining.

New sEddyProc class for site 'DE-Har'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Har-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1 data points (0.01%) set to NA
H: 17 data points (0.1%) set to NA
LE: 24 data points (0.14%) set to NA
NEE: 800 data points (4.57%) set to NA
-------------------------------------------------------------------
Data filtering:
8256 data points (47.12%) excluded by growing season filter
3319 additional data points (18.94%) excluded by precipitation filter (7049
 data points = 40.23 % in total)
11575 data points (66.07%) excluded in total
5945 valid data points (33.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1 data points (0.01%) set to NA
H: 17 data points (0.1%) set to NA
LE: 24 data points (0.14%) set to NA
NEE: 800 data points (4.57%) set to NA
-------------------------------------------------------------------
Data filtering:
8256 data points (47.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8256 data points (47.12%) excluded in total
9264 valid data points (52.88%) remaining.

New sEddyProc class for site 'DE-Har'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Har-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 50 data points (0.28%) set to NA
H: 567 data points (3.23%) set to NA
LE: 568 data points (3.23%) set to NA
NEE: 1515 data points (8.62%) set to NA
-------------------------------------------------------------------
Data filtering:
8784 data points (50%) excluded by growing season filter
4157 additional data points (23.66%) excluded by precipitation filter (7659
 data points = 43.6 % in total)
12941 data points (73.66%) excluded in total
4627 valid data points (26.34%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 50 data points (0.28%) set to NA
H: 567 data points (3.23%) set to NA
LE: 568 data points (3.23%) set to NA
NEE: 1515 data points (8.62%) set to NA
-------------------------------------------------------------------
Data filtering:
8784 data points (50%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8784 data points (50%) excluded in total
8784 valid data points (50%) remaining.

New sEddyProc class for site 'DE-Har'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Har-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[81/329] Processing: DE-HoH

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DE-HoH | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 4 data points (0.02%) set to NA
H: 93 data points (0.53%) set to NA
LE: 135 data points (0.77%) set to NA
NEE: 716 data points (4.09%) set to NA
-------------------------------------------------------------------
Data filtering:
10368 data points (59.18%) excluded by growing season filter
3393 additional data points (19.37%) excluded by precipitation filter (7443
 data points = 42.48 % in total)
13761 data points (78.54%) excluded in total
3759 valid data points (21.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4 data points (0.02%) set to NA
H: 93 data points (0.53%) set to NA
LE: 135 data points (0.77%) set to NA
NEE: 716 data points (4.09%) set to NA
-------------------------------------------------------------------
Data filtering:
10368 data points (59.18%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10368 data points (59.18%) excluded in total
7152 valid data points (40.82%) remaining.

New sEddyProc class for site 'DE-HoH'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-HoH-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3 data points (0.02%) set to NA
H: 54 data points (0.31%) set to NA
LE: 72 data points (0.41%) set to NA
NEE: 1005 data points (5.74%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
1706 additional data points (9.74%) excluded by precipitation filter (4828
 data points = 27.56 % in total)
11066 data points (63.16%) excluded in total
6454 valid data points (36.84%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3 data points (0.02%) set to NA
H: 54 data points (0.31%) set to NA
LE: 72 data points (0.41%) set to NA
NEE: 1005 data points (5.74%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9360 data points (53.42%) excluded in total
8160 valid data points (46.58%) remaining.

New sEddyProc class for site 'DE-HoH'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-HoH-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 344 data points (1.96%) set to NA
H: 85 data points (0.49%) set to NA
LE: 93 data points (0.53%) set to NA
NEE: 817 data points (4.66%) set to NA
-------------------------------------------------------------------
Data filtering:
9744 data points (55.62%) excluded by growing season filter
2897 additional data points (16.54%) excluded by precipitation filter (6996
 data points = 39.93 % in total)
12641 data points (72.15%) excluded in total
4879 valid data points (27.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 344 data points (1.96%) set to NA
H: 85 data points (0.49%) set to NA
LE: 93 data points (0.53%) set to NA
NEE: 817 data points (4.66%) set to NA
-------------------------------------------------------------------
Data filtering:
9744 data points (55.62%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9744 data points (55.62%) excluded in total
7776 valid data points (44.38%) remaining.

New sEddyProc class for site 'DE-HoH'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-HoH-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1829 data points (10.41%) set to NA
H: 244 data points (1.39%) set to NA
LE: 212 data points (1.21%) set to NA
NEE: 1369 data points (7.79%) set to NA
-------------------------------------------------------------------
Data filtering:
9504 data points (54.1%) excluded by growing season filter
2725 additional data points (15.51%) excluded by precipitation filter (6528
 data points = 37.16 % in total)
12229 data points (69.61%) excluded in total
5339 valid data points (30.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1829 data points (10.41%) set to NA
H: 244 data points (1.39%) set to NA
LE: 212 data points (1.21%) set to NA
NEE: 1369 data points (7.79%) set to NA
-------------------------------------------------------------------
Data filtering:
9504 data points (54.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9504 data points (54.1%) excluded in total
8064 valid data points (45.9%) remaining.

New sEddyProc class for site 'DE-HoH'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 14 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-HoH-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 784 data points (4.47%) set to NA
H: 192 data points (1.1%) set to NA
LE: 177 data points (1.01%) set to NA
NEE: 563 data points (3.21%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.53%) excluded by growing season filter
3207 additional data points (18.3%) excluded by precipitation filter (7341
 data points = 41.9 % in total)
13287 data points (75.84%) excluded in total
4233 valid data points (24.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 784 data points (4.47%) set to NA
H: 192 data points (1.1%) set to NA
LE: 177 data points (1.01%) set to NA
NEE: 563 data points (3.21%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.53%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10080 data points (57.53%) excluded in total
7440 valid data points (42.47%) remaining.

New sEddyProc class for site 'DE-HoH'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-HoH-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 41 data points (0.23%) set to NA
H: 204 data points (1.16%) set to NA
LE: 127 data points (0.72%) set to NA
NEE: 601 data points (3.43%) set to NA
-------------------------------------------------------------------
Data filtering:
9552 data points (54.52%) excluded by growing season filter
2929 additional data points (16.72%) excluded by precipitation filter (6610
 data points = 37.73 % in total)
12481 data points (71.24%) excluded in total
5039 valid data points (28.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 41 data points (0.23%) set to NA
H: 204 data points (1.16%) set to NA
LE: 127 data points (0.72%) set to NA
NEE: 601 data points (3.43%) set to NA
-------------------------------------------------------------------
Data filtering:
9552 data points (54.52%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9552 data points (54.52%) excluded in total
7968 valid data points (45.48%) remaining.

New sEddyProc class for site 'DE-HoH'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-HoH-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 580 data points (3.31%) set to NA
H: 407 data points (2.32%) set to NA
LE: 296 data points (1.69%) set to NA
NEE: 896 data points (5.11%) set to NA
-------------------------------------------------------------------
Data filtering:
9744 data points (55.62%) excluded by growing season filter
3500 additional data points (19.98%) excluded by precipitation filter (9448
 data points = 53.93 % in total)
13244 data points (75.59%) excluded in total
4276 valid data points (24.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 580 data points (3.31%) set to NA
H: 407 data points (2.32%) set to NA
LE: 296 data points (1.69%) set to NA
NEE: 896 data points (5.11%) set to NA
-------------------------------------------------------------------
Data filtering:
9744 data points (55.62%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9744 data points (55.62%) excluded in total
7776 valid data points (44.38%) remaining.

New sEddyProc class for site 'DE-HoH'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-HoH-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 161 data points (0.92%) set to NA
H: 231 data points (1.31%) set to NA
LE: 1784 data points (10.15%) set to NA
NEE: 2329 data points (13.26%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.64%) excluded by growing season filter
4397 additional data points (25.03%) excluded by precipitation filter (7982
 data points = 45.43 % in total)
13469 data points (76.67%) excluded in total
4099 valid data points (23.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 161 data points (0.92%) set to NA
H: 231 data points (1.31%) set to NA
LE: 1784 data points (10.15%) set to NA
NEE: 2329 data points (13.26%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9072 data points (51.64%) excluded in total
8496 valid data points (48.36%) remaining.

New sEddyProc class for site 'DE-HoH'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-HoH-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[82/329] Processing: DE-Hte

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DE-Hte | Years: 2017, 2018
Quality control:
TA: 0 data points (0%) set to NA
H: 7 data points (0.04%) set to NA
LE: 0 data points (0%) set to NA
NEE: 23 data points (0.13%) set to NA
-------------------------------------------------------------------
Data filtering:
11712 data points (66.85%) excluded by growing season filter
2837 additional data points (16.19%) excluded by precipitation filter (8704
 data points = 49.68 % in total)
14549 data points (83.04%) excluded in total
2971 valid data points (16.96%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 7 data points (0.04%) set to NA
LE: 0 data points (0%) set to NA
NEE: 23 data points (0.13%) set to NA
-------------------------------------------------------------------
Data filtering:
11712 data points (66.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11712 data points (66.85%) excluded in total
5808 valid data points (33.15%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 27 cases! Invalid values with 'NEE < -50': -56, -56, -56, -59, -77, -65, -56, -58, -59, -55, -59, -69, -52, -51, -75, -51, -63, -51, -78, -69, -54, -62, -63, -77, -74, -79, -59 ...”
New sEddyProc class for site 'DE-Hte'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 27 cases! Invalid values with 'NEE < -50': -56, -56, -56, -59, -77, -65, -56, -58, -59, -55, -59, -69, -52, -51, -75, -51, -63, -51, -78, -69, -54, -62, -63, -77, -74, -79, -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Hte-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1360 data points (7.76%) set to NA
LE: 1355 data points (7.73%) set to NA
NEE: 1422 data points (8.12%) set to NA
-------------------------------------------------------------------
Data filtering:
9648 data points (55.07%) excluded by growing season filter
1866 additional data points (10.65%) excluded by precipitation filter (6090
 data points = 34.76 % in total)
11514 data points (65.72%) excluded in total
6006 valid data points (34.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1360 data points (7.76%) set to NA
LE: 1355 data points (7.73%) set to NA
NEE: 1422 data points (8.12%) set to NA
-------------------------------------------------------------------
Data filtering:
9648 data points (55.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9648 data points (55.07%) excluded in total
7872 valid data points (44.93%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -56, -59, -57, -55, -72, -69, -65 ...”
New sEddyProc class for site 'DE-Hte'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -56, -59, -57, -55, -72, -69, -65 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Hte-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[83/329] Processing: DE-Hzd

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DE-Hzd | Years: 2022, 2023, 2024
Quality control:
TA: 4720 data points (26.94%) set to NA
H: 4182 data points (23.87%) set to NA
LE: 4275 data points (24.4%) set to NA
NEE: 5985 data points (34.16%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.15%) excluded by growing season filter
5474 additional data points (31.24%) excluded by precipitation filter (11556
 data points = 65.96 % in total)
14786 data points (84.39%) excluded in total
2734 valid data points (15.61%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4720 data points (26.94%) set to NA
H: 4182 data points (23.87%) set to NA
LE: 4275 data points (24.4%) set to NA
NEE: 5985 data points (34.16%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9312 data points (53.15%) excluded in total
8208 valid data points (46.85%) remaining.

New sEddyProc class for site 'DE-Hzd'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 114.68.

Regression of reference temperature R_ref for 41 periods.

Quality control:
TA: 80 data points (0.46%) set to NA
H: 161 data points (0.92%) set to NA
LE: 205 data points (1.17%) set to NA
NEE: 1144 data points (6.53%) set to NA
-------------------------------------------------------------------
Data filtering:
11424 data points (65.21%) excluded by growing season filter
3550 additional data points (20.26%) excluded by precipitation filter (12518
 data points = 71.45 % in total)
14974 data points (85.47%) excluded in total
2546 valid data points (14.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 80 data points (0.46%) set to NA
H: 161 data points (0.92%) set to NA
LE: 205 data points (1.17%) set to NA
NEE: 1144 data points (6.53%) set to NA
-------------------------------------------------------------------
Data filtering:
11424 data points (65.21%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11424 data points (65.21%) excluded in total
6096 valid data points (34.79%) remaining.

New sEddyProc class for site 'DE-Hzd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Hzd-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 324 data points (1.84%) set to NA
H: 396 data points (2.25%) set to NA
LE: 408 data points (2.32%) set to NA
NEE: 1827 data points (10.4%) set to NA
-------------------------------------------------------------------
Data filtering:
12864 data points (73.22%) excluded by growing season filter
3128 additional data points (17.81%) excluded by precipitation filter (11292
 data points = 64.28 % in total)
15992 data points (91.03%) excluded in total
1576 valid data points (8.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 324 data points (1.84%) set to NA
H: 396 data points (2.25%) set to NA
LE: 408 data points (2.32%) set to NA
NEE: 1827 data points (10.4%) set to NA
-------------------------------------------------------------------
Data filtering:
12864 data points (73.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12864 data points (73.22%) excluded in total
4704 valid data points (26.78%) remaining.

New sEddyProc class for site 'DE-Hzd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 8 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Hzd-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[84/329] Processing: DE-Lnf

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DE-Lnf | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 2236 data points (12.76%) set to NA
H: 3848 data points (21.96%) set to NA
LE: 4130 data points (23.57%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7302 additional data points (41.68%) excluded by precipitation filter (7302
 data points = 41.68 % in total)
7302 data points (41.68%) excluded in total
10218 valid data points (58.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2236 data points (12.76%) set to NA
H: 3848 data points (21.96%) set to NA
LE: 4130 data points (23.57%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'DE-Lnf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Lnf-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2147 data points (12.25%) set to NA
H: 1598 data points (9.12%) set to NA
LE: 3583 data points (20.45%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5421 additional data points (30.94%) excluded by precipitation filter (5421
 data points = 30.94 % in total)
5421 data points (30.94%) excluded in total
12099 valid data points (69.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2147 data points (12.25%) set to NA
H: 1598 data points (9.12%) set to NA
LE: 3583 data points (20.45%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'DE-Lnf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Lnf-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 75 data points (0.43%) set to NA
H: 95 data points (0.54%) set to NA
LE: 98 data points (0.56%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6693 additional data points (38.2%) excluded by precipitation filter (6693
 data points = 38.2 % in total)
6693 data points (38.2%) excluded in total
10827 valid data points (61.8%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 75 data points (0.43%) set to NA
H: 95 data points (0.54%) set to NA
LE: 98 data points (0.56%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'DE-Lnf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Lnf-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 12 data points (0.07%) set to NA
H: 30 data points (0.17%) set to NA
LE: 30 data points (0.17%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6661 additional data points (37.92%) excluded by precipitation filter (6661
 data points = 37.92 % in total)
6661 data points (37.92%) excluded in total
10907 valid data points (62.08%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12 data points (0.07%) set to NA
H: 30 data points (0.17%) set to NA
LE: 30 data points (0.17%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'DE-Lnf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Lnf-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 149 data points (0.85%) set to NA
LE: 191 data points (1.09%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7164 additional data points (40.89%) excluded by precipitation filter (7164
 data points = 40.89 % in total)
7164 data points (40.89%) excluded in total
10356 valid data points (59.11%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 149 data points (0.85%) set to NA
LE: 191 data points (1.09%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'DE-Lnf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Lnf-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 15311 data points (87.39%) set to NA
H: 9693 data points (55.33%) set to NA
LE: 9468 data points (54.04%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8954 additional data points (51.11%) excluded by precipitation filter (8954
 data points = 51.11 % in total)
8954 data points (51.11%) excluded in total
8566 valid data points (48.89%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 15311 data points (87.39%) set to NA
H: 9693 data points (55.33%) set to NA
LE: 9468 data points (54.04%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'DE-Lnf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Lnf-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 916 data points (5.23%) set to NA
H: 127 data points (0.72%) set to NA
LE: 5660 data points (32.31%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3349 additional data points (19.12%) excluded by precipitation filter (3349
 data points = 19.12 % in total)
3349 data points (19.12%) excluded in total
14171 valid data points (80.88%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 916 data points (5.23%) set to NA
H: 127 data points (0.72%) set to NA
LE: 5660 data points (32.31%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'DE-Lnf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Lnf-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 22 data points (0.13%) set to NA
H: 31 data points (0.18%) set to NA
LE: 78 data points (0.44%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7118 additional data points (40.52%) excluded by precipitation filter (7118
 data points = 40.52 % in total)
7118 data points (40.52%) excluded in total
10450 valid data points (59.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 22 data points (0.13%) set to NA
H: 31 data points (0.18%) set to NA
LE: 78 data points (0.44%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'DE-Lnf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Lnf-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[85/329] Processing: DE-Msr

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DE-Msr | Years: 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 9122 data points (51.92%) set to NA
H: 9167 data points (52.18%) set to NA
LE: 9235 data points (52.57%) set to NA
NEE: 9332 data points (53.12%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 142”

-------------------------------------------------------------------
Data filtering:
4896 data points (27.87%) excluded by growing season filter
5436 additional data points (30.94%) excluded by precipitation filter (7149
 data points = 40.69 % in total)
10332 data points (58.81%) excluded in total
7236 valid data points (41.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9122 data points (51.92%) set to NA
H: 9167 data points (52.18%) set to NA
LE: 9235 data points (52.57%) set to NA
NEE: 9332 data points (53.12%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 142”

-------------------------------------------------------------------
Data filtering:
4896 data points (27.87%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4896 data points (27.87%) excluded in total
12672 valid data points (72.13%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 18 cases! Invalid values with 'NEE < -50': -65, -70, -63, -68, -72, -77, -67, -70, -50, -71, -58, -67, -55, -52, -69, -51, -52, -56 ...”
New sEddyProc class for site 'DE-Msr'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 18 cases! Invalid values with 'NEE < -50': -65, -70, -63, -68, -72, -77, -67, -70, -50, -71, -58, -67, -55, -52, -69, -51, -52, -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 126.51.

Regression of reference temperature R_ref for 25 periods.

Quality control:
TA: 636 data points (3.63%) set to NA
H: 2474 data points (14.12%) set to NA
LE: 2742 data points (15.65%) set to NA
NEE: 2837 data points (16.19%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
3517 additional data points (20.07%) excluded by precipitation filter (8358
 data points = 47.71 % in total)
14173 data points (80.9%) excluded in total
3347 valid data points (19.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 636 data points (3.63%) set to NA
H: 2474 data points (14.12%) set to NA
LE: 2742 data points (15.65%) set to NA
NEE: 2837 data points (16.19%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10656 data points (60.82%) excluded in total
6864 valid data points (39.18%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -73, -53, -65, -69, -59, -52, -70 ...”
New sEddyProc class for site 'DE-Msr'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -73, -53, -65, -69, -59, -52, -70 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Msr-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 10343 data points (59.04%) set to NA
LE: 10362 data points (59.14%) set to NA
NEE: 11559 data points (65.98%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8137 additional data points (46.44%) excluded by precipitation filter (8137
 data points = 46.44 % in total)
8137 data points (46.44%) excluded in total
9383 valid data points (53.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 10343 data points (59.04%) set to NA
LE: 10362 data points (59.14%) set to NA
NEE: 11559 data points (65.98%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -66, -54, -54, -71 ...”
New sEddyProc class for site 'DE-Msr'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -66, -54, -54, -71 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Msr-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1193 data points (6.81%) set to NA
H: 1321 data points (7.54%) set to NA
LE: 1352 data points (7.72%) set to NA
NEE: 1587 data points (9.06%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.59%) excluded by growing season filter
4745 additional data points (27.08%) excluded by precipitation filter (9484
 data points = 54.13 % in total)
13433 data points (76.67%) excluded in total
4087 valid data points (23.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1193 data points (6.81%) set to NA
H: 1321 data points (7.54%) set to NA
LE: 1352 data points (7.72%) set to NA
NEE: 1587 data points (9.06%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8688 data points (49.59%) excluded in total
8832 valid data points (50.41%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 57 cases! Invalid values with 'NEE < -50': -61, -58, -51, -58, -78, -53, -58, -56, -53, -57, -55, -59, -69, -79, -55, -51, -52, -59, -55, -79, -64, -61, -73, -53, -52, -69, -57, -57, -54, -71, -50, -57, -56, -58, -76, -60, -55, -79, -59, -57, -75, -59, -61, -56, -60, -72, -51, -73, -53, -53 ...”
New sEddyProc class for site 'DE-Msr'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 57 cases! Invalid values with 'NEE < -50': -61, -58, -51, -58, -78, -53, -58, -56, -53, -57, -55, -59, -69, -79, -55, -51, -52, -59, -55, -79, -64, -61, -73, -53, -52, -69, -57, -57, -54, -71, -50, -57, -56, -58, -76, -60, -55, -79, -59, -57, -75, -59, -61, -56, -60, -72, -51, -73, -53, -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 104.54.

Regression of reference temperature R_ref for 13 periods.

Quality control:
TA: 1504 data points (8.56%) set to NA
H: 1640 data points (9.34%) set to NA
LE: 1628 data points (9.27%) set to NA
NEE: 1848 data points (10.52%) set to NA
-------------------------------------------------------------------
Data filtering:
5136 data points (29.23%) excluded by growing season filter
7742 additional data points (44.07%) excluded by precipitation filter (9854
 data points = 56.09 % in total)
12878 data points (73.3%) excluded in total
4690 valid data points (26.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1504 data points (8.56%) set to NA
H: 1640 data points (9.34%) set to NA
LE: 1628 data points (9.27%) set to NA
NEE: 1848 data points (10.52%) set to NA
-------------------------------------------------------------------
Data filtering:
5136 data points (29.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5136 data points (29.23%) excluded in total
12432 valid data points (70.77%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 99 cases! Invalid values with 'NEE < -50': -50, -57, -50, -60, -53, -58, -51, -58, -62, -50, -78, -58, -60, -58, -56, -70, -67, -51, -76, -73, -52, -54, -57, -51, -50, -61, -67, -62, -72, -68, -54, -60, -65, -56, -51, -52, -51, -56, -70, -71, -59, -59, -51, -68, -52, -50, -57, -63, -53, -51 ...”
New sEddyProc class for site 'DE-Msr'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 99 cases! Invalid values with 'NEE < -50': -50, -57, -50, -60, -53, -58, -51, -58, -62, -50, -78, -58, -60, -58, -56, -70, -67, -51, -76, -73, -52, -54, -57, -51, -50, -61, -67, -62, -72, -68, -54, -60, -65, -56, -51, -52, -51, -56, -70, -71, -59, -59, -51, -68, -52, -50, -57, -63, -53, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 13 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Msr-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[86/329] Processing: DE-Obe

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DE-Obe | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 167 data points (0.95%) set to NA
LE: 115 data points (0.66%) set to NA
NEE: 859 data points (4.9%) set to NA
-------------------------------------------------------------------
Data filtering:
7008 data points (40%) excluded by growing season filter
5107 additional data points (29.15%) excluded by precipitation filter (8875
 data points = 50.66 % in total)
12115 data points (69.15%) excluded in total
5405 valid data points (30.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 167 data points (0.95%) set to NA
LE: 115 data points (0.66%) set to NA
NEE: 859 data points (4.9%) set to NA
-------------------------------------------------------------------
Data filtering:
7008 data points (40%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7008 data points (40%) excluded in total
10512 valid data points (60%) remaining.

New sEddyProc class for site 'DE-Obe'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Obe-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 185 data points (1.06%) set to NA
H: 650 data points (3.71%) set to NA
LE: 677 data points (3.86%) set to NA
NEE: 2965 data points (16.92%) set to NA
-------------------------------------------------------------------
Data filtering:
7632 data points (43.56%) excluded by growing season filter
3057 additional data points (17.45%) excluded by precipitation filter (6726
 data points = 38.39 % in total)
10689 data points (61.01%) excluded in total
6831 valid data points (38.99%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 185 data points (1.06%) set to NA
H: 650 data points (3.71%) set to NA
LE: 677 data points (3.86%) set to NA
NEE: 2965 data points (16.92%) set to NA
-------------------------------------------------------------------
Data filtering:
7632 data points (43.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7632 data points (43.56%) excluded in total
9888 valid data points (56.44%) remaining.

New sEddyProc class for site 'DE-Obe'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Obe-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 967 data points (5.52%) set to NA
H: 616 data points (3.52%) set to NA
LE: 634 data points (3.62%) set to NA
NEE: 2676 data points (15.27%) set to NA
-------------------------------------------------------------------
Data filtering:
5520 data points (31.51%) excluded by growing season filter
4770 additional data points (27.23%) excluded by precipitation filter (7634
 data points = 43.57 % in total)
10290 data points (58.73%) excluded in total
7230 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 967 data points (5.52%) set to NA
H: 616 data points (3.52%) set to NA
LE: 634 data points (3.62%) set to NA
NEE: 2676 data points (15.27%) set to NA
-------------------------------------------------------------------
Data filtering:
5520 data points (31.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5520 data points (31.51%) excluded in total
12000 valid data points (68.49%) remaining.

New sEddyProc class for site 'DE-Obe'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 92.76.

Regression of reference temperature R_ref for 9 periods.

Quality control:
TA: 3 data points (0.02%) set to NA
H: 8 data points (0.05%) set to NA
LE: 10 data points (0.06%) set to NA
NEE: 2125 data points (12.1%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.54%) excluded by growing season filter
3543 additional data points (20.17%) excluded by precipitation filter (7489
 data points = 42.63 % in total)
11895 data points (67.71%) excluded in total
5673 valid data points (32.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3 data points (0.02%) set to NA
H: 8 data points (0.05%) set to NA
LE: 10 data points (0.06%) set to NA
NEE: 2125 data points (12.1%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.54%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8352 data points (47.54%) excluded in total
9216 valid data points (52.46%) remaining.

New sEddyProc class for site 'DE-Obe'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Obe-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 16 data points (0.09%) set to NA
H: 1757 data points (10.03%) set to NA
LE: 1755 data points (10.02%) set to NA
NEE: 2817 data points (16.08%) set to NA
-------------------------------------------------------------------
Data filtering:
7536 data points (43.01%) excluded by growing season filter
5003 additional data points (28.56%) excluded by precipitation filter (9567
 data points = 54.61 % in total)
12539 data points (71.57%) excluded in total
4981 valid data points (28.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 16 data points (0.09%) set to NA
H: 1757 data points (10.03%) set to NA
LE: 1755 data points (10.02%) set to NA
NEE: 2817 data points (16.08%) set to NA
-------------------------------------------------------------------
Data filtering:
7536 data points (43.01%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7536 data points (43.01%) excluded in total
9984 valid data points (56.99%) remaining.

New sEddyProc class for site 'DE-Obe'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Obe-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 12 data points (0.07%) set to NA
LE: 19 data points (0.11%) set to NA
NEE: 1555 data points (8.88%) set to NA
-------------------------------------------------------------------
Data filtering:
6912 data points (39.45%) excluded by growing season filter
4697 additional data points (26.81%) excluded by precipitation filter (8345
 data points = 47.63 % in total)
11609 data points (66.26%) excluded in total
5911 valid data points (33.74%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 12 data points (0.07%) set to NA
LE: 19 data points (0.11%) set to NA
NEE: 1555 data points (8.88%) set to NA
-------------------------------------------------------------------
Data filtering:
6912 data points (39.45%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6912 data points (39.45%) excluded in total
10608 valid data points (60.55%) remaining.

New sEddyProc class for site 'DE-Obe'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Obe-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 67 data points (0.38%) set to NA
LE: 71 data points (0.41%) set to NA
NEE: 1168 data points (6.67%) set to NA
-------------------------------------------------------------------
Data filtering:
6624 data points (37.81%) excluded by growing season filter
4753 additional data points (27.13%) excluded by precipitation filter (9025
 data points = 51.51 % in total)
11377 data points (64.94%) excluded in total
6143 valid data points (35.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 67 data points (0.38%) set to NA
LE: 71 data points (0.41%) set to NA
NEE: 1168 data points (6.67%) set to NA
-------------------------------------------------------------------
Data filtering:
6624 data points (37.81%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6624 data points (37.81%) excluded in total
10896 valid data points (62.19%) remaining.

New sEddyProc class for site 'DE-Obe'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Obe-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 38 data points (0.22%) set to NA
LE: 67 data points (0.38%) set to NA
NEE: 1151 data points (6.55%) set to NA
-------------------------------------------------------------------
Data filtering:
6912 data points (39.34%) excluded by growing season filter
4730 additional data points (26.92%) excluded by precipitation filter (8193
 data points = 46.64 % in total)
11642 data points (66.27%) excluded in total
5926 valid data points (33.73%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 38 data points (0.22%) set to NA
LE: 67 data points (0.38%) set to NA
NEE: 1151 data points (6.55%) set to NA
-------------------------------------------------------------------
Data filtering:
6912 data points (39.34%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6912 data points (39.34%) excluded in total
10656 valid data points (60.66%) remaining.

New sEddyProc class for site 'DE-Obe'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Obe-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[87/329] Processing: DE-RuC

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DE-RuC | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 359 data points (2.05%) set to NA
H: 388 data points (2.21%) set to NA
LE: 642 data points (3.66%) set to NA
NEE: 1356 data points (7.74%) set to NA
-------------------------------------------------------------------
Data filtering:
7968 data points (45.48%) excluded by growing season filter
4883 additional data points (27.87%) excluded by precipitation filter (10221
 data points = 58.34 % in total)
12851 data points (73.35%) excluded in total
4669 valid data points (26.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 359 data points (2.05%) set to NA
H: 388 data points (2.21%) set to NA
LE: 642 data points (3.66%) set to NA
NEE: 1356 data points (7.74%) set to NA
-------------------------------------------------------------------
Data filtering:
7968 data points (45.48%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7968 data points (45.48%) excluded in total
9552 valid data points (54.52%) remaining.

New sEddyProc class for site 'DE-RuC'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 100.95.

Regression of reference temperature R_ref for 4 periods.

Quality control:
TA: 1010 data points (5.76%) set to NA
H: 1034 data points (5.9%) set to NA
LE: 1048 data points (5.98%) set to NA
NEE: 1682 data points (9.6%) set to NA
-------------------------------------------------------------------
Data filtering:
9984 data points (56.99%) excluded by growing season filter
3126 additional data points (17.84%) excluded by precipitation filter (8760
 data points = 50 % in total)
13110 data points (74.83%) excluded in total
4410 valid data points (25.17%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1010 data points (5.76%) set to NA
H: 1034 data points (5.9%) set to NA
LE: 1048 data points (5.98%) set to NA
NEE: 1682 data points (9.6%) set to NA
-------------------------------------------------------------------
Data filtering:
9984 data points (56.99%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9984 data points (56.99%) excluded in total
7536 valid data points (43.01%) remaining.

New sEddyProc class for site 'DE-RuC'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 166.11.

Regression of reference temperature R_ref for 8 periods.

Quality control:
TA: 487 data points (2.78%) set to NA
H: 1562 data points (8.92%) set to NA
LE: 1648 data points (9.41%) set to NA
NEE: 2198 data points (12.55%) set to NA
-------------------------------------------------------------------
Data filtering:
9648 data points (55.07%) excluded by growing season filter
3549 additional data points (20.26%) excluded by precipitation filter (9940
 data points = 56.74 % in total)
13197 data points (75.33%) excluded in total
4323 valid data points (24.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 487 data points (2.78%) set to NA
H: 1562 data points (8.92%) set to NA
LE: 1648 data points (9.41%) set to NA
NEE: 2198 data points (12.55%) set to NA
-------------------------------------------------------------------
Data filtering:
9648 data points (55.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9648 data points (55.07%) excluded in total
7872 valid data points (44.93%) remaining.

New sEddyProc class for site 'DE-RuC'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-RuC-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 487 data points (2.77%) set to NA
H: 886 data points (5.04%) set to NA
LE: 952 data points (5.42%) set to NA
NEE: 1720 data points (9.79%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.01%) excluded by growing season filter
2984 additional data points (16.99%) excluded by precipitation filter (9014
 data points = 51.31 % in total)
12296 data points (69.99%) excluded in total
5272 valid data points (30.01%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 487 data points (2.77%) set to NA
H: 886 data points (5.04%) set to NA
LE: 952 data points (5.42%) set to NA
NEE: 1720 data points (9.79%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.01%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9312 data points (53.01%) excluded in total
8256 valid data points (46.99%) remaining.

New sEddyProc class for site 'DE-RuC'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-RuC-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1148 data points (6.55%) set to NA
H: 28 data points (0.16%) set to NA
LE: 66 data points (0.38%) set to NA
NEE: 353 data points (2.01%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
3892 additional data points (22.21%) excluded by precipitation filter (10528
 data points = 60.09 % in total)
14164 data points (80.84%) excluded in total
3356 valid data points (19.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1148 data points (6.55%) set to NA
H: 28 data points (0.16%) set to NA
LE: 66 data points (0.38%) set to NA
NEE: 353 data points (2.01%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10272 data points (58.63%) excluded in total
7248 valid data points (41.37%) remaining.

New sEddyProc class for site 'DE-RuC'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-RuC-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 69 data points (0.39%) set to NA
H: 104 data points (0.59%) set to NA
LE: 142 data points (0.81%) set to NA
NEE: 1180 data points (6.74%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
3332 additional data points (19.02%) excluded by precipitation filter (9213
 data points = 52.59 % in total)
12548 data points (71.62%) excluded in total
4972 valid data points (28.38%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 69 data points (0.39%) set to NA
H: 104 data points (0.59%) set to NA
LE: 142 data points (0.81%) set to NA
NEE: 1180 data points (6.74%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9216 data points (52.6%) excluded in total
8304 valid data points (47.4%) remaining.

New sEddyProc class for site 'DE-RuC'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-RuC-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1057 data points (6.03%) set to NA
H: 1134 data points (6.47%) set to NA
LE: 1156 data points (6.6%) set to NA
NEE: 1681 data points (9.59%) set to NA
-------------------------------------------------------------------
Data filtering:
9024 data points (51.51%) excluded by growing season filter
3886 additional data points (22.18%) excluded by precipitation filter (11463
 data points = 65.43 % in total)
12910 data points (73.69%) excluded in total
4610 valid data points (26.31%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1057 data points (6.03%) set to NA
H: 1134 data points (6.47%) set to NA
LE: 1156 data points (6.6%) set to NA
NEE: 1681 data points (9.59%) set to NA
-------------------------------------------------------------------
Data filtering:
9024 data points (51.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9024 data points (51.51%) excluded in total
8496 valid data points (48.49%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -68 ...”
New sEddyProc class for site 'DE-RuC'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -68 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 318.07.

Regression of reference temperature R_ref for 7 periods.

Quality control:
TA: 143 data points (0.81%) set to NA
H: 608 data points (3.46%) set to NA
LE: 638 data points (3.63%) set to NA
NEE: 1298 data points (7.39%) set to NA
-------------------------------------------------------------------
Data filtering:
7344 data points (41.8%) excluded by growing season filter
5602 additional data points (31.89%) excluded by precipitation filter (10517
 data points = 59.86 % in total)
12946 data points (73.69%) excluded in total
4622 valid data points (26.31%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 143 data points (0.81%) set to NA
H: 608 data points (3.46%) set to NA
LE: 638 data points (3.63%) set to NA
NEE: 1298 data points (7.39%) set to NA
-------------------------------------------------------------------
Data filtering:
7344 data points (41.8%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7344 data points (41.8%) excluded in total
10224 valid data points (58.2%) remaining.

New sEddyProc class for site 'DE-RuC'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-RuC-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[88/329] Processing: DE-SbM

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DE-SbM | Years: 2023, 2024
Quality control:
TA: 7673 data points (43.8%) set to NA
H: 6401 data points (36.54%) set to NA
LE: 6523 data points (37.23%) set to NA
NEE: 6583 data points (37.57%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 88”

-------------------------------------------------------------------
Data filtering:
5472 data points (31.23%) excluded by growing season filter
8240 additional data points (47.03%) excluded by precipitation filter (12926
 data points = 73.78 % in total)
13712 data points (78.26%) excluded in total
3808 valid data points (21.74%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7673 data points (43.8%) set to NA
H: 6401 data points (36.54%) set to NA
LE: 6523 data points (37.23%) set to NA
NEE: 6583 data points (37.57%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 88”

-------------------------------------------------------------------
Data filtering:
5472 data points (31.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5472 data points (31.23%) excluded in total
12048 valid data points (68.77%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -56, -60, -65 ...”
New sEddyProc class for site 'DE-SbM'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -56, -60, -65 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 108.21.

Regression of reference temperature R_ref for 21 periods.

Quality control:
TA: 776 data points (4.42%) set to NA
H: 981 data points (5.58%) set to NA
LE: 1481 data points (8.43%) set to NA
NEE: 1932 data points (11%) set to NA
-------------------------------------------------------------------
Data filtering:
6912 data points (39.34%) excluded by growing season filter
6834 additional data points (38.9%) excluded by precipitation filter (12160
 data points = 69.22 % in total)
13746 data points (78.24%) excluded in total
3822 valid data points (21.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 776 data points (4.42%) set to NA
H: 981 data points (5.58%) set to NA
LE: 1481 data points (8.43%) set to NA
NEE: 1932 data points (11%) set to NA
-------------------------------------------------------------------
Data filtering:
6912 data points (39.34%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6912 data points (39.34%) excluded in total
10656 valid data points (60.66%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -68, -52, -51, -54, -55, -66, -56, -64 ...”
New sEddyProc class for site 'DE-SbM'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -68, -52, -51, -54, -55, -66, -56, -64 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 277.66.

Regression of reference temperature R_ref for 19 periods.

[89/329] Processing: DE-Tha

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DE-Tha | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 6 data points (0.03%) set to NA
LE: 8 data points (0.05%) set to NA
NEE: 253 data points (1.44%) set to NA
-------------------------------------------------------------------
Data filtering:
6480 data points (36.99%) excluded by growing season filter
4985 additional data points (28.45%) excluded by precipitation filter (8278
 data points = 47.25 % in total)
11465 data points (65.44%) excluded in total
6055 valid data points (34.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 6 data points (0.03%) set to NA
LE: 8 data points (0.05%) set to NA
NEE: 253 data points (1.44%) set to NA
-------------------------------------------------------------------
Data filtering:
6480 data points (36.99%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6480 data points (36.99%) excluded in total
11040 valid data points (63.01%) remaining.

New sEddyProc class for site 'DE-Tha'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Tha-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 7 data points (0.04%) set to NA
LE: 18 data points (0.1%) set to NA
NEE: 180 data points (1.03%) set to NA
-------------------------------------------------------------------
Data filtering:
7632 data points (43.56%) excluded by growing season filter
2543 additional data points (14.51%) excluded by precipitation filter (5541
 data points = 31.63 % in total)
10175 data points (58.08%) excluded in total
7345 valid data points (41.92%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 7 data points (0.04%) set to NA
LE: 18 data points (0.1%) set to NA
NEE: 180 data points (1.03%) set to NA
-------------------------------------------------------------------
Data filtering:
7632 data points (43.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7632 data points (43.56%) excluded in total
9888 valid data points (56.44%) remaining.

New sEddyProc class for site 'DE-Tha'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Tha-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 6 data points (0.03%) set to NA
LE: 256 data points (1.46%) set to NA
NEE: 589 data points (3.36%) set to NA
-------------------------------------------------------------------
Data filtering:
6336 data points (36.16%) excluded by growing season filter
3987 additional data points (22.76%) excluded by precipitation filter (7135
 data points = 40.72 % in total)
10323 data points (58.92%) excluded in total
7197 valid data points (41.08%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 6 data points (0.03%) set to NA
LE: 256 data points (1.46%) set to NA
NEE: 589 data points (3.36%) set to NA
-------------------------------------------------------------------
Data filtering:
6336 data points (36.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6336 data points (36.16%) excluded in total
11184 valid data points (63.84%) remaining.

New sEddyProc class for site 'DE-Tha'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Tha-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4 data points (0.02%) set to NA
H: 1280 data points (7.29%) set to NA
LE: 1267 data points (7.21%) set to NA
NEE: 1573 data points (8.95%) set to NA
-------------------------------------------------------------------
Data filtering:
6288 data points (35.79%) excluded by growing season filter
3981 additional data points (22.66%) excluded by precipitation filter (6751
 data points = 38.43 % in total)
10269 data points (58.45%) excluded in total
7299 valid data points (41.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4 data points (0.02%) set to NA
H: 1280 data points (7.29%) set to NA
LE: 1267 data points (7.21%) set to NA
NEE: 1573 data points (8.95%) set to NA
-------------------------------------------------------------------
Data filtering:
6288 data points (35.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6288 data points (35.79%) excluded in total
11280 valid data points (64.21%) remaining.

New sEddyProc class for site 'DE-Tha'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Tha-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 676 data points (3.86%) set to NA
H: 280 data points (1.6%) set to NA
LE: 273 data points (1.56%) set to NA
NEE: 633 data points (3.61%) set to NA
-------------------------------------------------------------------
Data filtering:
7344 data points (41.92%) excluded by growing season filter
4703 additional data points (26.84%) excluded by precipitation filter (8397
 data points = 47.93 % in total)
12047 data points (68.76%) excluded in total
5473 valid data points (31.24%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 676 data points (3.86%) set to NA
H: 280 data points (1.6%) set to NA
LE: 273 data points (1.56%) set to NA
NEE: 633 data points (3.61%) set to NA
-------------------------------------------------------------------
Data filtering:
7344 data points (41.92%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7344 data points (41.92%) excluded in total
10176 valid data points (58.08%) remaining.

New sEddyProc class for site 'DE-Tha'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Tha-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 888 data points (5.07%) set to NA
H: 113 data points (0.64%) set to NA
LE: 111 data points (0.63%) set to NA
NEE: 333 data points (1.9%) set to NA
-------------------------------------------------------------------
Data filtering:
6288 data points (35.89%) excluded by growing season filter
4295 additional data points (24.51%) excluded by precipitation filter (7482
 data points = 42.71 % in total)
10583 data points (60.41%) excluded in total
6937 valid data points (39.59%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 888 data points (5.07%) set to NA
H: 113 data points (0.64%) set to NA
LE: 111 data points (0.63%) set to NA
NEE: 333 data points (1.9%) set to NA
-------------------------------------------------------------------
Data filtering:
6288 data points (35.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6288 data points (35.89%) excluded in total
11232 valid data points (64.11%) remaining.

New sEddyProc class for site 'DE-Tha'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Tha-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 531 data points (3.03%) set to NA
H: 175 data points (1%) set to NA
LE: 105 data points (0.6%) set to NA
NEE: 384 data points (2.19%) set to NA
-------------------------------------------------------------------
Data filtering:
6864 data points (39.18%) excluded by growing season filter
4387 additional data points (25.04%) excluded by precipitation filter (8777
 data points = 50.1 % in total)
11251 data points (64.22%) excluded in total
6269 valid data points (35.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 531 data points (3.03%) set to NA
H: 175 data points (1%) set to NA
LE: 105 data points (0.6%) set to NA
NEE: 384 data points (2.19%) set to NA
-------------------------------------------------------------------
Data filtering:
6864 data points (39.18%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6864 data points (39.18%) excluded in total
10656 valid data points (60.82%) remaining.

New sEddyProc class for site 'DE-Tha'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Tha-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 417 data points (2.37%) set to NA
H: 488 data points (2.78%) set to NA
LE: 494 data points (2.81%) set to NA
NEE: 754 data points (4.29%) set to NA
-------------------------------------------------------------------
Data filtering:
6048 data points (34.43%) excluded by growing season filter
4460 additional data points (25.39%) excluded by precipitation filter (7434
 data points = 42.32 % in total)
10508 data points (59.81%) excluded in total
7060 valid data points (40.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 417 data points (2.37%) set to NA
H: 488 data points (2.78%) set to NA
LE: 494 data points (2.81%) set to NA
NEE: 754 data points (4.29%) set to NA
-------------------------------------------------------------------
Data filtering:
6048 data points (34.43%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6048 data points (34.43%) excluded in total
11520 valid data points (65.57%) remaining.

New sEddyProc class for site 'DE-Tha'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 1 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DE-Tha-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[90/329] Processing: DK-Gds

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DK-Gds | Years: 2020, 2021, 2022
Quality control:
TA: 14360 data points (81.74%) set to NA
H: 9469 data points (53.9%) set to NA
LE: 9555 data points (54.39%) set to NA
NEE: 9692 data points (55.17%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10360 additional data points (58.97%) excluded by precipitation filter (10360
 data points = 58.97 % in total)
10360 data points (58.97%) excluded in total
7208 valid data points (41.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 14360 data points (81.74%) set to NA
H: 9469 data points (53.9%) set to NA
LE: 9555 data points (54.39%) set to NA
NEE: 9692 data points (55.17%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 22 cases! Invalid values with 'NEE < -50': -54, -70, -65, -67, -76, -57, -65, -74, -60, -71, -66, -52, -64, -64, -61, -73, -68, -80, -54, -55, -70, -57 ...”
New sEddyProc class for site 'DK-Gds'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 22 cases! Invalid values with 'NEE < -50': -54, -70, -65, -67, -76, -57, -65, -74, -60, -71, -66, -52, -64, -64, -61, -73, -68, -80, -54, -55, -70, -57 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DK-Gds-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1203 data points (6.87%) set to NA
H: 1256 data points (7.17%) set to NA
LE: 1339 data points (7.64%) set to NA
NEE: 1457 data points (8.32%) set to NA
-------------------------------------------------------------------
Data filtering:
6144 data points (35.07%) excluded by growing season filter
5396 additional data points (30.8%) excluded by precipitation filter (8401
 data points = 47.95 % in total)
11540 data points (65.87%) excluded in total
5980 valid data points (34.13%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1203 data points (6.87%) set to NA
H: 1256 data points (7.17%) set to NA
LE: 1339 data points (7.64%) set to NA
NEE: 1457 data points (8.32%) set to NA
-------------------------------------------------------------------
Data filtering:
6144 data points (35.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6144 data points (35.07%) excluded in total
11376 valid data points (64.93%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 36 cases! Invalid values with 'NEE < -50': -58, -52, -68, -55, -55, -57, -55, -58, -71, -59, -72, -54, -57, -59, -56, -51, -60, -79, -56, -50, -56, -50, -56, -50, -53, -53, -56, -50, -59, -64, -74, -75, -68, -62, -50, -76 ...”
New sEddyProc class for site 'DK-Gds'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 36 cases! Invalid values with 'NEE < -50': -58, -52, -68, -55, -55, -57, -55, -58, -71, -59, -72, -54, -57, -59, -56, -51, -60, -79, -56, -50, -56, -50, -56, -50, -53, -53, -56, -50, -59, -64, -74, -75, -68, -62, -50, -76 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 10 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DK-Gds-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3428 data points (19.57%) set to NA
H: 4254 data points (24.28%) set to NA
LE: 5765 data points (32.91%) set to NA
NEE: 5838 data points (33.32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 47”

-------------------------------------------------------------------
Data filtering:
4656 data points (26.58%) excluded by growing season filter
6376 additional data points (36.39%) excluded by precipitation filter (8768
 data points = 50.05 % in total)
11032 data points (62.97%) excluded in total
6488 valid data points (37.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3428 data points (19.57%) set to NA
H: 4254 data points (24.28%) set to NA
LE: 5765 data points (32.91%) set to NA
NEE: 5838 data points (33.32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 47”

-------------------------------------------------------------------
Data filtering:
4656 data points (26.58%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4656 data points (26.58%) excluded in total
12864 valid data points (73.42%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -67, -62, -68, -62, -77, -77, -64, -59, -72 ...”
New sEddyProc class for site 'DK-Gds'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -67, -62, -68, -62, -77, -77, -64, -59, -72 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 153.16.

Regression of reference temperature R_ref for 4 periods.

[91/329] Processing: DK-RCW

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DK-RCW | Years: 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 270 data points (1.54%) set to NA
LE: 356 data points (2.03%) set to NA
NEE: 594 data points (3.39%) set to NA
-------------------------------------------------------------------
Data filtering:
9600 data points (54.79%) excluded by growing season filter
1841 additional data points (10.51%) excluded by precipitation filter (6146
 data points = 35.08 % in total)
11441 data points (65.3%) excluded in total
6079 valid data points (34.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 270 data points (1.54%) set to NA
LE: 356 data points (2.03%) set to NA
NEE: 594 data points (3.39%) set to NA
-------------------------------------------------------------------
Data filtering:
9600 data points (54.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9600 data points (54.79%) excluded in total
7920 valid data points (45.21%) remaining.

New sEddyProc class for site 'DK-RCW'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DK-RCW-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 211 data points (1.2%) set to NA
LE: 1306 data points (7.43%) set to NA
NEE: 1400 data points (7.97%) set to NA
-------------------------------------------------------------------
Data filtering:
9984 data points (56.83%) excluded by growing season filter
2903 additional data points (16.52%) excluded by precipitation filter (6443
 data points = 36.67 % in total)
12887 data points (73.35%) excluded in total
4681 valid data points (26.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 211 data points (1.2%) set to NA
LE: 1306 data points (7.43%) set to NA
NEE: 1400 data points (7.97%) set to NA
-------------------------------------------------------------------
Data filtering:
9984 data points (56.83%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9984 data points (56.83%) excluded in total
7584 valid data points (43.17%) remaining.

New sEddyProc class for site 'DK-RCW'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DK-RCW-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[92/329] Processing: DK-Skj

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DK-Skj | Years: 2020, 2021, 2022
Quality control:
TA: 11682 data points (66.5%) set to NA
H: 11693 data points (66.56%) set to NA
LE: 11705 data points (66.63%) set to NA
NEE: 11816 data points (67.26%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9216 additional data points (52.46%) excluded by precipitation filter (9216
 data points = 52.46 % in total)
9216 data points (52.46%) excluded in total
8352 valid data points (47.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11682 data points (66.5%) set to NA
H: 11693 data points (66.56%) set to NA
LE: 11705 data points (66.63%) set to NA
NEE: 11816 data points (67.26%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
New sEddyProc class for site 'DK-Skj'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DK-Skj-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 755 data points (4.31%) set to NA
H: 781 data points (4.46%) set to NA
LE: 2376 data points (13.56%) set to NA
NEE: 2742 data points (15.65%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.78%) excluded by growing season filter
3662 additional data points (20.9%) excluded by precipitation filter (8103
 data points = 46.25 % in total)
12734 data points (72.68%) excluded in total
4786 valid data points (27.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 755 data points (4.31%) set to NA
H: 781 data points (4.46%) set to NA
LE: 2376 data points (13.56%) set to NA
NEE: 2742 data points (15.65%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.78%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9072 data points (51.78%) excluded in total
8448 valid data points (48.22%) remaining.

New sEddyProc class for site 'DK-Skj'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 10 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DK-Skj-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1135 data points (6.48%) set to NA
H: 66 data points (0.38%) set to NA
LE: 864 data points (4.93%) set to NA
NEE: 1236 data points (7.05%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
3288 additional data points (18.77%) excluded by precipitation filter (9150
 data points = 52.23 % in total)
12648 data points (72.19%) excluded in total
4872 valid data points (27.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1135 data points (6.48%) set to NA
H: 66 data points (0.38%) set to NA
LE: 864 data points (4.93%) set to NA
NEE: 1236 data points (7.05%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9360 data points (53.42%) excluded in total
8160 valid data points (46.58%) remaining.

New sEddyProc class for site 'DK-Skj'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 123.21.

Regression of reference temperature R_ref for 7 periods.

[93/329] Processing: DK-Sor

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: DK-Sor | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 25 data points (0.14%) set to NA
H: 26 data points (0.15%) set to NA
LE: 26 data points (0.15%) set to NA
NEE: 36 data points (0.21%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
3614 additional data points (20.63%) excluded by precipitation filter (8789
 data points = 50.17 % in total)
13886 data points (79.26%) excluded in total
3634 valid data points (20.74%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 25 data points (0.14%) set to NA
H: 26 data points (0.15%) set to NA
LE: 26 data points (0.15%) set to NA
NEE: 36 data points (0.21%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10272 data points (58.63%) excluded in total
7248 valid data points (41.37%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -52, -51 ...”
New sEddyProc class for site 'DK-Sor'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -52, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DK-Sor-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 10 data points (0.06%) set to NA
H: 72 data points (0.41%) set to NA
LE: 463 data points (2.64%) set to NA
NEE: 232 data points (1.32%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
2052 additional data points (11.71%) excluded by precipitation filter (5179
 data points = 29.56 % in total)
11268 data points (64.32%) excluded in total
6252 valid data points (35.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10 data points (0.06%) set to NA
H: 72 data points (0.41%) set to NA
LE: 463 data points (2.64%) set to NA
NEE: 232 data points (1.32%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9216 data points (52.6%) excluded in total
8304 valid data points (47.4%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -51, -53 ...”
New sEddyProc class for site 'DK-Sor'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -51, -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DK-Sor-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 155 data points (0.88%) set to NA
H: 157 data points (0.9%) set to NA
LE: 603 data points (3.44%) set to NA
NEE: 658 data points (3.76%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.53%) excluded by growing season filter
3761 additional data points (21.47%) excluded by precipitation filter (8310
 data points = 47.43 % in total)
13841 data points (79%) excluded in total
3679 valid data points (21%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 155 data points (0.88%) set to NA
H: 157 data points (0.9%) set to NA
LE: 603 data points (3.44%) set to NA
NEE: 658 data points (3.76%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.53%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10080 data points (57.53%) excluded in total
7440 valid data points (42.47%) remaining.

New sEddyProc class for site 'DK-Sor'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 102.61.

Regression of reference temperature R_ref for 4 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 2 data points (0.01%) set to NA
LE: 2 data points (0.01%) set to NA
NEE: 34 data points (0.19%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.74%) excluded by growing season filter
5013 additional data points (28.53%) excluded by precipitation filter (9825
 data points = 55.93 % in total)
14805 data points (84.27%) excluded in total
2763 valid data points (15.73%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2 data points (0.01%) set to NA
LE: 2 data points (0.01%) set to NA
NEE: 34 data points (0.19%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9792 data points (55.74%) excluded in total
7776 valid data points (44.26%) remaining.

New sEddyProc class for site 'DK-Sor'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DK-Sor-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 5 data points (0.03%) set to NA
H: 1640 data points (9.36%) set to NA
LE: 1638 data points (9.35%) set to NA
NEE: 1721 data points (9.82%) set to NA
-------------------------------------------------------------------
Data filtering:
10320 data points (58.9%) excluded by growing season filter
2569 additional data points (14.66%) excluded by precipitation filter (6335
 data points = 36.16 % in total)
12889 data points (73.57%) excluded in total
4631 valid data points (26.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5 data points (0.03%) set to NA
H: 1640 data points (9.36%) set to NA
LE: 1638 data points (9.35%) set to NA
NEE: 1721 data points (9.82%) set to NA
-------------------------------------------------------------------
Data filtering:
10320 data points (58.9%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10320 data points (58.9%) excluded in total
7200 valid data points (41.1%) remaining.

New sEddyProc class for site 'DK-Sor'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DK-Sor-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 233 data points (1.33%) set to NA
H: 153 data points (0.87%) set to NA
LE: 153 data points (0.87%) set to NA
NEE: 190 data points (1.08%) set to NA
-------------------------------------------------------------------
Data filtering:
9456 data points (53.97%) excluded by growing season filter
2823 additional data points (16.11%) excluded by precipitation filter (6533
 data points = 37.29 % in total)
12279 data points (70.09%) excluded in total
5241 valid data points (29.91%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 233 data points (1.33%) set to NA
H: 153 data points (0.87%) set to NA
LE: 153 data points (0.87%) set to NA
NEE: 190 data points (1.08%) set to NA
-------------------------------------------------------------------
Data filtering:
9456 data points (53.97%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9456 data points (53.97%) excluded in total
8064 valid data points (46.03%) remaining.

New sEddyProc class for site 'DK-Sor'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DK-Sor-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 6 data points (0.03%) set to NA
NEE: 45 data points (0.26%) set to NA
-------------------------------------------------------------------
Data filtering:
9696 data points (55.34%) excluded by growing season filter
2844 additional data points (16.23%) excluded by precipitation filter (7585
 data points = 43.29 % in total)
12540 data points (71.58%) excluded in total
4980 valid data points (28.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 6 data points (0.03%) set to NA
NEE: 45 data points (0.26%) set to NA
-------------------------------------------------------------------
Data filtering:
9696 data points (55.34%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9696 data points (55.34%) excluded in total
7824 valid data points (44.66%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
New sEddyProc class for site 'DK-Sor'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DK-Sor-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 246 data points (1.4%) set to NA
H: 341 data points (1.94%) set to NA
LE: 475 data points (2.7%) set to NA
NEE: 377 data points (2.15%) set to NA
-------------------------------------------------------------------
Data filtering:
10032 data points (57.1%) excluded by growing season filter
4293 additional data points (24.44%) excluded by precipitation filter (9715
 data points = 55.3 % in total)
14325 data points (81.54%) excluded in total
3243 valid data points (18.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 246 data points (1.4%) set to NA
H: 341 data points (1.94%) set to NA
LE: 475 data points (2.7%) set to NA
NEE: 377 data points (2.15%) set to NA
-------------------------------------------------------------------
Data filtering:
10032 data points (57.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10032 data points (57.1%) excluded in total
7536 valid data points (42.9%) remaining.

New sEddyProc class for site 'DK-Sor'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for DK-Sor-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[94/329] Processing: EE-Pts

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: EE-Pts | Years: 2022, 2023, 2024
Quality control:
TA: 13258 data points (75.67%) set to NA
H: 12443 data points (71.02%) set to NA
LE: 12455 data points (71.09%) set to NA
NEE: 12751 data points (72.78%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8683 additional data points (49.56%) excluded by precipitation filter (8683
 data points = 49.56 % in total)
8683 data points (49.56%) excluded in total
8837 valid data points (50.44%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 13258 data points (75.67%) set to NA
H: 12443 data points (71.02%) set to NA
LE: 12455 data points (71.09%) set to NA
NEE: 12751 data points (72.78%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -68, -56, -63 ...”
New sEddyProc class for site 'EE-Pts'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -68, -56, -63 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 111.16.

Regression of reference temperature R_ref for 13 periods.

Quality control:
TA: 373 data points (2.13%) set to NA
H: 348 data points (1.99%) set to NA
LE: 358 data points (2.04%) set to NA
NEE: 595 data points (3.4%) set to NA
-------------------------------------------------------------------
Data filtering:
10848 data points (61.92%) excluded by growing season filter
2829 additional data points (16.15%) excluded by precipitation filter (6778
 data points = 38.69 % in total)
13677 data points (78.07%) excluded in total
3843 valid data points (21.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 373 data points (2.13%) set to NA
H: 348 data points (1.99%) set to NA
LE: 358 data points (2.04%) set to NA
NEE: 595 data points (3.4%) set to NA
-------------------------------------------------------------------
Data filtering:
10848 data points (61.92%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10848 data points (61.92%) excluded in total
6672 valid data points (38.08%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 11 cases! Invalid values with 'NEE < -50': -78, -50, -79, -66, -55, -62, -63, -50, -73, -61, -54 ...”
New sEddyProc class for site 'EE-Pts'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 11 cases! Invalid values with 'NEE < -50': -78, -50, -79, -66, -55, -62, -63, -50, -73, -61, -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 227.54.

Regression of reference temperature R_ref for 5 periods.

Quality control:
TA: 7006 data points (39.88%) set to NA
H: 466 data points (2.65%) set to NA
LE: 517 data points (2.94%) set to NA
NEE: 840 data points (4.78%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.56%) excluded by growing season filter
2423 additional data points (13.79%) excluded by precipitation filter (6822
 data points = 38.83 % in total)
12887 data points (73.35%) excluded in total
4681 valid data points (26.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7006 data points (39.88%) set to NA
H: 466 data points (2.65%) set to NA
LE: 517 data points (2.94%) set to NA
NEE: 840 data points (4.78%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10464 data points (59.56%) excluded in total
7104 valid data points (40.44%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -61, -59, -78, -74, -64, -57, -69, -65, -61 ...”
New sEddyProc class for site 'EE-Pts'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -61, -59, -78, -74, -64, -57, -69, -65, -61 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 10 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for EE-Pts-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[95/329] Processing: EE-Rng

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: EE-Rng | Years: 2023, 2024
Quality control:
TA: 15862 data points (90.54%) set to NA
H: 15873 data points (90.6%) set to NA
LE: 15871 data points (90.59%) set to NA
NEE: 15900 data points (90.75%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9963 additional data points (56.87%) excluded by precipitation filter (9963
 data points = 56.87 % in total)
9963 data points (56.87%) excluded in total
7557 valid data points (43.13%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (2) for EE-Rng-2023”

Quality control:
TA: 1312 data points (7.47%) set to NA
H: 632 data points (3.6%) set to NA
LE: 737 data points (4.2%) set to NA
NEE: 1145 data points (6.52%) set to NA
-------------------------------------------------------------------
Data filtering:
12144 data points (69.13%) excluded by growing season filter
2046 additional data points (11.65%) excluded by precipitation filter (7478
 data points = 42.57 % in total)
14190 data points (80.77%) excluded in total
3378 valid data points (19.23%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1312 data points (7.47%) set to NA
H: 632 data points (3.6%) set to NA
LE: 737 data points (4.2%) set to NA
NEE: 1145 data points (6.52%) set to NA
-------------------------------------------------------------------
Data filtering:
12144 data points (69.13%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12144 data points (69.13%) excluded in total
5424 valid data points (30.87%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 10 cases! Invalid values with 'NEE < -50': -80, -66, -71, -58, -52, -58, -76, -55, -57, -54 ...”
New sEddyProc class for site 'EE-Rng'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 10 cases! Invalid values with 'NEE < -50': -80, -66, -71, -58, -52, -58, -76, -55, -57, -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 13 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for EE-Rng-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[96/329] Processing: EE-Stg

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: EE-Stg | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 257 data points (1.47%) set to NA
H: 253 data points (1.44%) set to NA
LE: 255 data points (1.46%) set to NA
NEE: 313 data points (1.79%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.89%) excluded by growing season filter
5384 additional data points (30.73%) excluded by precipitation filter (12320
 data points = 70.32 % in total)
15176 data points (86.62%) excluded in total
2344 valid data points (13.38%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 257 data points (1.47%) set to NA
H: 253 data points (1.44%) set to NA
LE: 255 data points (1.46%) set to NA
NEE: 313 data points (1.79%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9792 data points (55.89%) excluded in total
7728 valid data points (44.11%) remaining.

New sEddyProc class for site 'EE-Stg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for EE-Stg-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 624 data points (3.56%) set to NA
H: 505 data points (2.88%) set to NA
LE: 574 data points (3.28%) set to NA
NEE: 652 data points (3.72%) set to NA
-------------------------------------------------------------------
Data filtering:
8592 data points (49.04%) excluded by growing season filter
5762 additional data points (32.89%) excluded by precipitation filter (10792
 data points = 61.6 % in total)
14354 data points (81.93%) excluded in total
3166 valid data points (18.07%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 624 data points (3.56%) set to NA
H: 505 data points (2.88%) set to NA
LE: 574 data points (3.28%) set to NA
NEE: 652 data points (3.72%) set to NA
-------------------------------------------------------------------
Data filtering:
8592 data points (49.04%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8592 data points (49.04%) excluded in total
8928 valid data points (50.96%) remaining.

New sEddyProc class for site 'EE-Stg'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 154.59.

Regression of reference temperature R_ref for 11 periods.

Quality control:
TA: 27 data points (0.15%) set to NA
H: 551 data points (3.14%) set to NA
LE: 563 data points (3.21%) set to NA
NEE: 881 data points (5.03%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
5228 additional data points (29.84%) excluded by precipitation filter (11904
 data points = 67.95 % in total)
14588 data points (83.26%) excluded in total
2932 valid data points (16.74%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 27 data points (0.15%) set to NA
H: 551 data points (3.14%) set to NA
LE: 563 data points (3.21%) set to NA
NEE: 881 data points (5.03%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9360 data points (53.42%) excluded in total
8160 valid data points (46.58%) remaining.

New sEddyProc class for site 'EE-Stg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for EE-Stg-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 30 data points (0.17%) set to NA
H: 57 data points (0.32%) set to NA
LE: 73 data points (0.42%) set to NA
NEE: 503 data points (2.86%) set to NA
-------------------------------------------------------------------
Data filtering:
9552 data points (54.37%) excluded by growing season filter
5158 additional data points (29.36%) excluded by precipitation filter (12078
 data points = 68.75 % in total)
14710 data points (83.73%) excluded in total
2858 valid data points (16.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 30 data points (0.17%) set to NA
H: 57 data points (0.32%) set to NA
LE: 73 data points (0.42%) set to NA
NEE: 503 data points (2.86%) set to NA
-------------------------------------------------------------------
Data filtering:
9552 data points (54.37%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9552 data points (54.37%) excluded in total
8016 valid data points (45.63%) remaining.

New sEddyProc class for site 'EE-Stg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for EE-Stg-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 66 data points (0.38%) set to NA
H: 90 data points (0.51%) set to NA
LE: 111 data points (0.63%) set to NA
NEE: 236 data points (1.35%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.16%) excluded by growing season filter
5340 additional data points (30.48%) excluded by precipitation filter (11482
 data points = 65.54 % in total)
15180 data points (86.64%) excluded in total
2340 valid data points (13.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 66 data points (0.38%) set to NA
H: 90 data points (0.51%) set to NA
LE: 111 data points (0.63%) set to NA
NEE: 236 data points (1.35%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9840 data points (56.16%) excluded in total
7680 valid data points (43.84%) remaining.

New sEddyProc class for site 'EE-Stg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for EE-Stg-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 27 data points (0.15%) set to NA
H: 66 data points (0.38%) set to NA
LE: 92 data points (0.53%) set to NA
NEE: 1298 data points (7.41%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.16%) excluded by growing season filter
5108 additional data points (29.16%) excluded by precipitation filter (11572
 data points = 66.05 % in total)
14948 data points (85.32%) excluded in total
2572 valid data points (14.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 27 data points (0.15%) set to NA
H: 66 data points (0.38%) set to NA
LE: 92 data points (0.53%) set to NA
NEE: 1298 data points (7.41%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9840 data points (56.16%) excluded in total
7680 valid data points (43.84%) remaining.

New sEddyProc class for site 'EE-Stg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for EE-Stg-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 703 data points (4.01%) set to NA
H: 942 data points (5.38%) set to NA
LE: 966 data points (5.51%) set to NA
NEE: 1224 data points (6.99%) set to NA
-------------------------------------------------------------------
Data filtering:
8784 data points (50.14%) excluded by growing season filter
5608 additional data points (32.01%) excluded by precipitation filter (11810
 data points = 67.41 % in total)
14392 data points (82.15%) excluded in total
3128 valid data points (17.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 703 data points (4.01%) set to NA
H: 942 data points (5.38%) set to NA
LE: 966 data points (5.51%) set to NA
NEE: 1224 data points (6.99%) set to NA
-------------------------------------------------------------------
Data filtering:
8784 data points (50.14%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8784 data points (50.14%) excluded in total
8736 valid data points (49.86%) remaining.

New sEddyProc class for site 'EE-Stg'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 140.73.

Regression of reference temperature R_ref for 17 periods.

Quality control:
TA: 108 data points (0.61%) set to NA
H: 194 data points (1.1%) set to NA
LE: 235 data points (1.34%) set to NA
NEE: 564 data points (3.21%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.74%) excluded by growing season filter
4876 additional data points (27.76%) excluded by precipitation filter (11184
 data points = 63.66 % in total)
14668 data points (83.49%) excluded in total
2900 valid data points (16.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 108 data points (0.61%) set to NA
H: 194 data points (1.1%) set to NA
LE: 235 data points (1.34%) set to NA
NEE: 564 data points (3.21%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9792 data points (55.74%) excluded in total
7776 valid data points (44.26%) remaining.

New sEddyProc class for site 'EE-Stg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for EE-Stg-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[97/329] Processing: ES-Abr

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-Abr | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 0 data points (0%) set to NA
H: 58 data points (0.33%) set to NA
LE: 77 data points (0.44%) set to NA
NEE: 904 data points (5.16%) set to NA
-------------------------------------------------------------------
Data filtering:
9888 data points (56.44%) excluded by growing season filter
1330 additional data points (7.59%) excluded by precipitation filter (2528
 data points = 14.43 % in total)
11218 data points (64.03%) excluded in total
6302 valid data points (35.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 58 data points (0.33%) set to NA
LE: 77 data points (0.44%) set to NA
NEE: 904 data points (5.16%) set to NA
-------------------------------------------------------------------
Data filtering:
9888 data points (56.44%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9888 data points (56.44%) excluded in total
7632 valid data points (43.56%) remaining.

New sEddyProc class for site 'ES-Abr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Abr-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 8 data points (0.05%) set to NA
LE: 29 data points (0.17%) set to NA
NEE: 422 data points (2.41%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.78%) excluded by growing season filter
2968 additional data points (16.94%) excluded by precipitation filter (4202
 data points = 23.98 % in total)
12040 data points (68.72%) excluded in total
5480 valid data points (31.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 8 data points (0.05%) set to NA
LE: 29 data points (0.17%) set to NA
NEE: 422 data points (2.41%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.78%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9072 data points (51.78%) excluded in total
8448 valid data points (48.22%) remaining.

New sEddyProc class for site 'ES-Abr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Abr-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 308 data points (1.76%) set to NA
LE: 351 data points (2%) set to NA
NEE: 875 data points (4.99%) set to NA
-------------------------------------------------------------------
Data filtering:
9264 data points (52.88%) excluded by growing season filter
1661 additional data points (9.48%) excluded by precipitation filter (2861
 data points = 16.33 % in total)
10925 data points (62.36%) excluded in total
6595 valid data points (37.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 308 data points (1.76%) set to NA
LE: 351 data points (2%) set to NA
NEE: 875 data points (4.99%) set to NA
-------------------------------------------------------------------
Data filtering:
9264 data points (52.88%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9264 data points (52.88%) excluded in total
8256 valid data points (47.12%) remaining.

New sEddyProc class for site 'ES-Abr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Abr-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 223 data points (1.27%) set to NA
H: 68 data points (0.39%) set to NA
LE: 115 data points (0.65%) set to NA
NEE: 566 data points (3.22%) set to NA
-------------------------------------------------------------------
Data filtering:
8592 data points (48.91%) excluded by growing season filter
2917 additional data points (16.6%) excluded by precipitation filter (3601
 data points = 20.5 % in total)
11509 data points (65.51%) excluded in total
6059 valid data points (34.49%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 223 data points (1.27%) set to NA
H: 68 data points (0.39%) set to NA
LE: 115 data points (0.65%) set to NA
NEE: 566 data points (3.22%) set to NA
-------------------------------------------------------------------
Data filtering:
8592 data points (48.91%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8592 data points (48.91%) excluded in total
8976 valid data points (51.09%) remaining.

New sEddyProc class for site 'ES-Abr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Abr-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[98/329] Processing: ES-Agu

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-Agu | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 1555 data points (8.88%) set to NA
H: 6445 data points (36.79%) set to NA
LE: 8516 data points (48.61%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4377 additional data points (24.98%) excluded by precipitation filter (4377
 data points = 24.98 % in total)
4377 data points (24.98%) excluded in total
13143 valid data points (75.02%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1555 data points (8.88%) set to NA
H: 6445 data points (36.79%) set to NA
LE: 8516 data points (48.61%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Agu'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Agu-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 248 data points (1.42%) set to NA
LE: 260 data points (1.48%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6174 additional data points (35.24%) excluded by precipitation filter (6174
 data points = 35.24 % in total)
6174 data points (35.24%) excluded in total
11346 valid data points (64.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 248 data points (1.42%) set to NA
LE: 260 data points (1.48%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Agu'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Agu-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 17519 data points (99.99%) set to NA
H: 17519 data points (99.99%) set to NA
LE: 17519 data points (99.99%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3161 additional data points (18.04%) excluded by precipitation filter (3161
 data points = 18.04 % in total)
3161 data points (18.04%) excluded in total
14359 valid data points (81.96%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for ES-Agu-2019”

Quality control:
TA: 17568 data points (100%) set to NA
H: 17568 data points (100%) set to NA
LE: 17568 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3039 additional data points (17.3%) excluded by precipitation filter (3039
 data points = 17.3 % in total)
3039 data points (17.3%) excluded in total
14529 valid data points (82.7%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for ES-Agu-2020”

Quality control:
TA: 17520 data points (100%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3959 additional data points (22.6%) excluded by precipitation filter (3959
 data points = 22.6 % in total)
3959 data points (22.6%) excluded in total
13561 valid data points (77.4%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for ES-Agu-2021”

Quality control:
TA: 17520 data points (100%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4134 additional data points (23.6%) excluded by precipitation filter (4134
 data points = 23.6 % in total)
4134 data points (23.6%) excluded in total
13386 valid data points (76.4%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for ES-Agu-2022”

Quality control:
TA: 938 data points (5.35%) set to NA
H: 4305 data points (24.57%) set to NA
LE: 4321 data points (24.66%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5081 additional data points (29%) excluded by precipitation filter (5081
 data points = 29 % in total)
5081 data points (29%) excluded in total
12439 valid data points (71%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 938 data points (5.35%) set to NA
H: 4305 data points (24.57%) set to NA
LE: 4321 data points (24.66%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Agu'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Agu-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 810 data points (4.61%) set to NA
H: 810 data points (4.61%) set to NA
LE: 819 data points (4.66%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4932 additional data points (28.07%) excluded by precipitation filter (4932
 data points = 28.07 % in total)
4932 data points (28.07%) excluded in total
12636 valid data points (71.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 810 data points (4.61%) set to NA
H: 810 data points (4.61%) set to NA
LE: 819 data points (4.66%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Agu'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Agu-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[99/329] Processing: ES-Amo

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-Amo | Years: 2017, 2018, 2019
Quality control:
TA: 9338 data points (53.3%) set to NA
H: 9342 data points (53.32%) set to NA
LE: 9338 data points (53.3%) set to NA
NEE: 9389 data points (53.59%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2539 additional data points (14.49%) excluded by precipitation filter (2539
 data points = 14.49 % in total)
2539 data points (14.49%) excluded in total
14981 valid data points (85.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9338 data points (53.3%) set to NA
H: 9342 data points (53.32%) set to NA
LE: 9338 data points (53.3%) set to NA
NEE: 9389 data points (53.59%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Amo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Amo-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1967 data points (11.23%) set to NA
H: 2124 data points (12.12%) set to NA
LE: 2372 data points (13.54%) set to NA
NEE: 4563 data points (26.04%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4395 additional data points (25.09%) excluded by precipitation filter (4395
 data points = 25.09 % in total)
4395 data points (25.09%) excluded in total
13125 valid data points (74.91%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1967 data points (11.23%) set to NA
H: 2124 data points (12.12%) set to NA
LE: 2372 data points (13.54%) set to NA
NEE: 4563 data points (26.04%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Amo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 11 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Amo-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1193 data points (6.81%) set to NA
H: 851 data points (4.86%) set to NA
LE: 1134 data points (6.47%) set to NA
NEE: 1365 data points (7.79%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2867 additional data points (16.36%) excluded by precipitation filter (2867
 data points = 16.36 % in total)
2867 data points (16.36%) excluded in total
14653 valid data points (83.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1193 data points (6.81%) set to NA
H: 851 data points (4.86%) set to NA
LE: 1134 data points (6.47%) set to NA
NEE: 1365 data points (7.79%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Amo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 1 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Amo-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[100/329] Processing: ES-Cnd

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-Cnd | Years: 2017, 2018, 2019, 2020, 2021
Quality control:
TA: 1587 data points (9.06%) set to NA
H: 2072 data points (11.83%) set to NA
LE: 2070 data points (11.82%) set to NA
NEE: 4999 data points (28.53%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4942 additional data points (28.21%) excluded by precipitation filter (4942
 data points = 28.21 % in total)
4942 data points (28.21%) excluded in total
12578 valid data points (71.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1587 data points (9.06%) set to NA
H: 2072 data points (11.83%) set to NA
LE: 2070 data points (11.82%) set to NA
NEE: 4999 data points (28.53%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Cnd'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 324.68.

Regression of reference temperature R_ref for 10 periods.

Quality control:
TA: 2830 data points (16.15%) set to NA
H: 1286 data points (7.34%) set to NA
LE: 1296 data points (7.4%) set to NA
NEE: 4481 data points (25.58%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8372 additional data points (47.79%) excluded by precipitation filter (8372
 data points = 47.79 % in total)
8372 data points (47.79%) excluded in total
9148 valid data points (52.21%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2830 data points (16.15%) set to NA
H: 1286 data points (7.34%) set to NA
LE: 1296 data points (7.4%) set to NA
NEE: 4481 data points (25.58%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Cnd'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 136.03.

Regression of reference temperature R_ref for 18 periods.

Quality control:
TA: 2520 data points (14.38%) set to NA
H: 2001 data points (11.42%) set to NA
LE: 2144 data points (12.24%) set to NA
NEE: 5308 data points (30.3%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6332 additional data points (36.14%) excluded by precipitation filter (6332
 data points = 36.14 % in total)
6332 data points (36.14%) excluded in total
11188 valid data points (63.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2520 data points (14.38%) set to NA
H: 2001 data points (11.42%) set to NA
LE: 2144 data points (12.24%) set to NA
NEE: 5308 data points (30.3%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
New sEddyProc class for site 'ES-Cnd'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 183.78.

Regression of reference temperature R_ref for 15 periods.

Quality control:
TA: 2490 data points (14.17%) set to NA
H: 5006 data points (28.49%) set to NA
LE: 5007 data points (28.5%) set to NA
NEE: 6829 data points (38.87%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6796 additional data points (38.68%) excluded by precipitation filter (6796
 data points = 38.68 % in total)
6796 data points (38.68%) excluded in total
10772 valid data points (61.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2490 data points (14.17%) set to NA
H: 5006 data points (28.49%) set to NA
LE: 5007 data points (28.5%) set to NA
NEE: 6829 data points (38.87%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Cnd'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 215.17.

Regression of reference temperature R_ref for 15 periods.

Quality control:
TA: 3872 data points (22.1%) set to NA
H: 3889 data points (22.2%) set to NA
LE: 3887 data points (22.19%) set to NA
NEE: 5519 data points (31.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6962 additional data points (39.74%) excluded by precipitation filter (6962
 data points = 39.74 % in total)
6962 data points (39.74%) excluded in total
10558 valid data points (60.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3872 data points (22.1%) set to NA
H: 3889 data points (22.2%) set to NA
LE: 3887 data points (22.19%) set to NA
NEE: 5519 data points (31.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Cnd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 13 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Cnd-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[101/329] Processing: ES-Crg

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-Crg | Years: 2021, 2022, 2023, 2024
Quality control:
TA: 14407 data points (82.23%) set to NA
H: 14048 data points (80.18%) set to NA
LE: 14121 data points (80.6%) set to NA
NEE: 14679 data points (83.78%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5072 additional data points (28.95%) excluded by precipitation filter (5072
 data points = 28.95 % in total)
5072 data points (28.95%) excluded in total
12448 valid data points (71.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 14407 data points (82.23%) set to NA
H: 14048 data points (80.18%) set to NA
LE: 14121 data points (80.6%) set to NA
NEE: 14679 data points (83.78%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Crg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Crg-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 795 data points (4.54%) set to NA
H: 2692 data points (15.37%) set to NA
LE: 2719 data points (15.52%) set to NA
NEE: 5199 data points (29.67%) set to NA
-------------------------------------------------------------------
Data filtering:
528 data points (3.01%) excluded by growing season filter
3890 additional data points (22.2%) excluded by precipitation filter (4305
 data points = 24.57 % in total)
4418 data points (25.22%) excluded in total
13102 valid data points (74.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 795 data points (4.54%) set to NA
H: 2692 data points (15.37%) set to NA
LE: 2719 data points (15.52%) set to NA
NEE: 5199 data points (29.67%) set to NA
-------------------------------------------------------------------
Data filtering:
528 data points (3.01%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
528 data points (3.01%) excluded in total
16992 valid data points (96.99%) remaining.

New sEddyProc class for site 'ES-Crg'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 130.45.

Regression of reference temperature R_ref for 6 periods.

Quality control:
TA: 29 data points (0.17%) set to NA
H: 1369 data points (7.81%) set to NA
LE: 1410 data points (8.05%) set to NA
NEE: 2220 data points (12.67%) set to NA
-------------------------------------------------------------------
Data filtering:
1680 data points (9.59%) excluded by growing season filter
3083 additional data points (17.6%) excluded by precipitation filter (3181
 data points = 18.16 % in total)
4763 data points (27.19%) excluded in total
12757 valid data points (72.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 29 data points (0.17%) set to NA
H: 1369 data points (7.81%) set to NA
LE: 1410 data points (8.05%) set to NA
NEE: 2220 data points (12.67%) set to NA
-------------------------------------------------------------------
Data filtering:
1680 data points (9.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1680 data points (9.59%) excluded in total
15840 valid data points (90.41%) remaining.

New sEddyProc class for site 'ES-Crg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Crg-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 596 data points (3.39%) set to NA
H: 547 data points (3.11%) set to NA
LE: 597 data points (3.4%) set to NA
NEE: 2360 data points (13.43%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3845 additional data points (21.89%) excluded by precipitation filter (3845
 data points = 21.89 % in total)
3845 data points (21.89%) excluded in total
13723 valid data points (78.11%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 596 data points (3.39%) set to NA
H: 547 data points (3.11%) set to NA
LE: 597 data points (3.4%) set to NA
NEE: 2360 data points (13.43%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Crg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Crg-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[102/329] Processing: ES-Dnn

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-Dnn | Years: 2024
Quality control:
TA: 7273 data points (41.4%) set to NA
H: 9961 data points (56.7%) set to NA
LE: 9980 data points (56.81%) set to NA
NEE: 10090 data points (57.43%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4862 additional data points (27.68%) excluded by precipitation filter (4862
 data points = 27.68 % in total)
4862 data points (27.68%) excluded in total
12706 valid data points (72.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7273 data points (41.4%) set to NA
H: 9961 data points (56.7%) set to NA
LE: 9980 data points (56.81%) set to NA
NEE: 10090 data points (57.43%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Dnn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Dnn-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[103/329] Processing: ES-FtD

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-FtD | Years: 2021, 2022, 2023, 2024
Quality control:
TA: 394 data points (2.25%) set to NA
H: 416 data points (2.37%) set to NA
LE: 415 data points (2.37%) set to NA
NEE: 797 data points (4.55%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
1604 additional data points (9.16%) excluded by precipitation filter (4666
 data points = 26.63 % in total)
12404 data points (70.8%) excluded in total
5116 valid data points (29.2%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 394 data points (2.25%) set to NA
H: 416 data points (2.37%) set to NA
LE: 415 data points (2.37%) set to NA
NEE: 797 data points (4.55%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10800 data points (61.64%) excluded in total
6720 valid data points (38.36%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -73, -63 ...”
New sEddyProc class for site 'ES-FtD'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -73, -63 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-FtD-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 724 data points (4.13%) set to NA
H: 743 data points (4.24%) set to NA
LE: 747 data points (4.26%) set to NA
NEE: 1030 data points (5.88%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.84%) excluded by growing season filter
996 additional data points (5.68%) excluded by precipitation filter (4972
 data points = 28.38 % in total)
12180 data points (69.52%) excluded in total
5340 valid data points (30.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 724 data points (4.13%) set to NA
H: 743 data points (4.24%) set to NA
LE: 747 data points (4.26%) set to NA
NEE: 1030 data points (5.88%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11184 data points (63.84%) excluded in total
6336 valid data points (36.16%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -73, -66, -51 ...”
New sEddyProc class for site 'ES-FtD'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -73, -66, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-FtD-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3917 data points (22.36%) set to NA
H: 3940 data points (22.49%) set to NA
LE: 4784 data points (27.31%) set to NA
NEE: 5150 data points (29.39%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 62”

-------------------------------------------------------------------
Data filtering:
4464 data points (25.48%) excluded by growing season filter
2414 additional data points (13.78%) excluded by precipitation filter (4140
 data points = 23.63 % in total)
6878 data points (39.26%) excluded in total
10642 valid data points (60.74%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3917 data points (22.36%) set to NA
H: 3940 data points (22.49%) set to NA
LE: 4784 data points (27.31%) set to NA
NEE: 5150 data points (29.39%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 62”

-------------------------------------------------------------------
Data filtering:
4464 data points (25.48%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4464 data points (25.48%) excluded in total
13056 valid data points (74.52%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -63, -73, -76 ...”
New sEddyProc class for site 'ES-FtD'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -63, -73, -76 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 13 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-FtD-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 158 data points (0.9%) set to NA
H: 184 data points (1.05%) set to NA
LE: 248 data points (1.41%) set to NA
NEE: 1307 data points (7.44%) set to NA
-------------------------------------------------------------------
Data filtering:
12240 data points (69.67%) excluded by growing season filter
1542 additional data points (8.78%) excluded by precipitation filter (4862
 data points = 27.68 % in total)
13782 data points (78.45%) excluded in total
3786 valid data points (21.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 158 data points (0.9%) set to NA
H: 184 data points (1.05%) set to NA
LE: 248 data points (1.41%) set to NA
NEE: 1307 data points (7.44%) set to NA
-------------------------------------------------------------------
Data filtering:
12240 data points (69.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12240 data points (69.67%) excluded in total
5328 valid data points (30.33%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -74, -58, -56, -76 ...”
New sEddyProc class for site 'ES-FtD'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -74, -58, -56, -76 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-FtD-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[104/329] Processing: ES-Gdn

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-Gdn | Years: 2017, 2018, 2019, 2020, 2021
Quality control:
TA: 4295 data points (24.51%) set to NA
H: 4336 data points (24.75%) set to NA
LE: 4460 data points (25.46%) set to NA
NEE: 6174 data points (35.24%) set to NA
-------------------------------------------------------------------
Data filtering:
3408 data points (19.45%) excluded by growing season filter
3816 additional data points (21.78%) excluded by precipitation filter (4942
 data points = 28.21 % in total)
7224 data points (41.23%) excluded in total
10296 valid data points (58.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4295 data points (24.51%) set to NA
H: 4336 data points (24.75%) set to NA
LE: 4460 data points (25.46%) set to NA
NEE: 6174 data points (35.24%) set to NA
-------------------------------------------------------------------
Data filtering:
3408 data points (19.45%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3408 data points (19.45%) excluded in total
14112 valid data points (80.55%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
New sEddyProc class for site 'ES-Gdn'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 121.13.

Regression of reference temperature R_ref for 23 periods.

Quality control:
TA: 2417 data points (13.8%) set to NA
H: 2451 data points (13.99%) set to NA
LE: 2637 data points (15.05%) set to NA
NEE: 4689 data points (26.76%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8372 additional data points (47.79%) excluded by precipitation filter (8372
 data points = 47.79 % in total)
8372 data points (47.79%) excluded in total
9148 valid data points (52.21%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2417 data points (13.8%) set to NA
H: 2451 data points (13.99%) set to NA
LE: 2637 data points (15.05%) set to NA
NEE: 4689 data points (26.76%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Gdn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 21 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Gdn-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3831 data points (21.87%) set to NA
H: 3957 data points (22.59%) set to NA
LE: 4442 data points (25.35%) set to NA
NEE: 10587 data points (60.43%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6332 additional data points (36.14%) excluded by precipitation filter (6332
 data points = 36.14 % in total)
6332 data points (36.14%) excluded in total
11188 valid data points (63.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3831 data points (21.87%) set to NA
H: 3957 data points (22.59%) set to NA
LE: 4442 data points (25.35%) set to NA
NEE: 10587 data points (60.43%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Gdn'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 228.45.

Regression of reference temperature R_ref for 32 periods.

Quality control:
TA: 6308 data points (35.91%) set to NA
H: 6333 data points (36.05%) set to NA
LE: 6378 data points (36.3%) set to NA
NEE: 8564 data points (48.75%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6796 additional data points (38.68%) excluded by precipitation filter (6796
 data points = 38.68 % in total)
6796 data points (38.68%) excluded in total
10772 valid data points (61.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6308 data points (35.91%) set to NA
H: 6333 data points (36.05%) set to NA
LE: 6378 data points (36.3%) set to NA
NEE: 8564 data points (48.75%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Gdn'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 213.88.

Regression of reference temperature R_ref for 18 periods.

Quality control:
TA: 4319 data points (24.65%) set to NA
H: 4338 data points (24.76%) set to NA
LE: 4335 data points (24.74%) set to NA
NEE: 5970 data points (34.08%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 57”

-------------------------------------------------------------------
Data filtering:
12432 data points (70.96%) excluded by growing season filter
2546 additional data points (14.53%) excluded by precipitation filter (6962
 data points = 39.74 % in total)
14978 data points (85.49%) excluded in total
2542 valid data points (14.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4319 data points (24.65%) set to NA
H: 4338 data points (24.76%) set to NA
LE: 4335 data points (24.74%) set to NA
NEE: 5970 data points (34.08%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 57”

-------------------------------------------------------------------
Data filtering:
12432 data points (70.96%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12432 data points (70.96%) excluded in total
5088 valid data points (29.04%) remaining.

New sEddyProc class for site 'ES-Gdn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 17 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Gdn-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[105/329] Processing: ES-HdD

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-HdD | Years: 2024
Quality control:
TA: 4244 data points (24.16%) set to NA
H: 4248 data points (24.18%) set to NA
LE: 4255 data points (24.22%) set to NA
NEE: 4539 data points (25.84%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 44”

-------------------------------------------------------------------
Data filtering:
8688 data points (49.45%) excluded by growing season filter
2534 additional data points (14.42%) excluded by precipitation filter (3383
 data points = 19.26 % in total)
11222 data points (63.88%) excluded in total
6346 valid data points (36.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 4244 data points (24.16%) set to NA
H: 4248 data points (24.18%) set to NA
LE: 4255 data points (24.22%) set to NA
NEE: 4539 data points (25.84%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 44”

-------------------------------------------------------------------
Data filtering:
8688 data points (49.45%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8688 data points (49.45%) excluded in total
8880 valid data points (50.55%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -55, -50, -63 ...”
New sEddyProc class for site 'ES-HdD'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -55, -50, -63 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 82.49.

Regression of reference temperature R_ref for 20 periods.

[106/329] Processing: ES-HeB

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-HeB | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 55 data points (0.31%) set to NA
LE: 95 data points (0.54%) set to NA
NEE: 737 data points (4.21%) set to NA
-------------------------------------------------------------------
Data filtering:
4368 data points (24.93%) excluded by growing season filter
1282 additional data points (7.32%) excluded by precipitation filter (1713
 data points = 9.78 % in total)
5650 data points (32.25%) excluded in total
11870 valid data points (67.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 55 data points (0.31%) set to NA
LE: 95 data points (0.54%) set to NA
NEE: 737 data points (4.21%) set to NA
-------------------------------------------------------------------
Data filtering:
4368 data points (24.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4368 data points (24.93%) excluded in total
13152 valid data points (75.07%) remaining.

New sEddyProc class for site 'ES-HeB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-HeB-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1088 data points (6.19%) set to NA
LE: 1184 data points (6.74%) set to NA
NEE: 1784 data points (10.15%) set to NA
-------------------------------------------------------------------
Data filtering:
4176 data points (23.77%) excluded by growing season filter
2724 additional data points (15.51%) excluded by precipitation filter (3150
 data points = 17.93 % in total)
6900 data points (39.28%) excluded in total
10668 valid data points (60.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1088 data points (6.19%) set to NA
LE: 1184 data points (6.74%) set to NA
NEE: 1784 data points (10.15%) set to NA
-------------------------------------------------------------------
Data filtering:
4176 data points (23.77%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4176 data points (23.77%) excluded in total
13392 valid data points (76.23%) remaining.

New sEddyProc class for site 'ES-HeB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-HeB-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 223 data points (1.27%) set to NA
H: 98 data points (0.56%) set to NA
LE: 154 data points (0.88%) set to NA
NEE: 695 data points (3.97%) set to NA
-------------------------------------------------------------------
Data filtering:
3648 data points (20.82%) excluded by growing season filter
2772 additional data points (15.82%) excluded by precipitation filter (3353
 data points = 19.14 % in total)
6420 data points (36.64%) excluded in total
11100 valid data points (63.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 223 data points (1.27%) set to NA
H: 98 data points (0.56%) set to NA
LE: 154 data points (0.88%) set to NA
NEE: 695 data points (3.97%) set to NA
-------------------------------------------------------------------
Data filtering:
3648 data points (20.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3648 data points (20.82%) excluded in total
13872 valid data points (79.18%) remaining.

New sEddyProc class for site 'ES-HeB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-HeB-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 65 data points (0.37%) set to NA
H: 971 data points (5.54%) set to NA
LE: 1027 data points (5.86%) set to NA
NEE: 1817 data points (10.37%) set to NA
-------------------------------------------------------------------
Data filtering:
5760 data points (32.88%) excluded by growing season filter
1513 additional data points (8.64%) excluded by precipitation filter (2763
 data points = 15.77 % in total)
7273 data points (41.51%) excluded in total
10247 valid data points (58.49%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 65 data points (0.37%) set to NA
H: 971 data points (5.54%) set to NA
LE: 1027 data points (5.86%) set to NA
NEE: 1817 data points (10.37%) set to NA
-------------------------------------------------------------------
Data filtering:
5760 data points (32.88%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5760 data points (32.88%) excluded in total
11760 valid data points (67.12%) remaining.

New sEddyProc class for site 'ES-HeB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 1 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-HeB-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 263 data points (1.5%) set to NA
H: 84 data points (0.48%) set to NA
LE: 170 data points (0.97%) set to NA
NEE: 1178 data points (6.72%) set to NA
-------------------------------------------------------------------
Data filtering:
7680 data points (43.84%) excluded by growing season filter
1670 additional data points (9.53%) excluded by precipitation filter (2412
 data points = 13.77 % in total)
9350 data points (53.37%) excluded in total
8170 valid data points (46.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 263 data points (1.5%) set to NA
H: 84 data points (0.48%) set to NA
LE: 170 data points (0.97%) set to NA
NEE: 1178 data points (6.72%) set to NA
-------------------------------------------------------------------
Data filtering:
7680 data points (43.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7680 data points (43.84%) excluded in total
9840 valid data points (56.16%) remaining.

New sEddyProc class for site 'ES-HeB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-HeB-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 430 data points (2.45%) set to NA
LE: 601 data points (3.42%) set to NA
NEE: 2058 data points (11.71%) set to NA
-------------------------------------------------------------------
Data filtering:
1488 data points (8.47%) excluded by growing season filter
2205 additional data points (12.55%) excluded by precipitation filter (2431
 data points = 13.84 % in total)
3693 data points (21.02%) excluded in total
13875 valid data points (78.98%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 430 data points (2.45%) set to NA
LE: 601 data points (3.42%) set to NA
NEE: 2058 data points (11.71%) set to NA
-------------------------------------------------------------------
Data filtering:
1488 data points (8.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1488 data points (8.47%) excluded in total
16080 valid data points (91.53%) remaining.

New sEddyProc class for site 'ES-HeB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-HeB-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[107/329] Processing: ES-Hen

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-Hen | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 1061 data points (6.06%) set to NA
LE: 1128 data points (6.44%) set to NA
NEE: 2002 data points (11.43%) set to NA
-------------------------------------------------------------------
Data filtering:
1248 data points (7.12%) excluded by growing season filter
1487 additional data points (8.49%) excluded by precipitation filter (1487
 data points = 8.49 % in total)
2735 data points (15.61%) excluded in total
14785 valid data points (84.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1061 data points (6.06%) set to NA
LE: 1128 data points (6.44%) set to NA
NEE: 2002 data points (11.43%) set to NA
-------------------------------------------------------------------
Data filtering:
1248 data points (7.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1248 data points (7.12%) excluded in total
16272 valid data points (92.88%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -70, -78 ...”
New sEddyProc class for site 'ES-Hen'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -70, -78 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Hen-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 60 data points (0.34%) set to NA
LE: 90 data points (0.51%) set to NA
NEE: 1764 data points (10.04%) set to NA
-------------------------------------------------------------------
Data filtering:
6720 data points (38.25%) excluded by growing season filter
2044 additional data points (11.63%) excluded by precipitation filter (2707
 data points = 15.41 % in total)
8764 data points (49.89%) excluded in total
8804 valid data points (50.11%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 60 data points (0.34%) set to NA
LE: 90 data points (0.51%) set to NA
NEE: 1764 data points (10.04%) set to NA
-------------------------------------------------------------------
Data filtering:
6720 data points (38.25%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6720 data points (38.25%) excluded in total
10848 valid data points (61.75%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -70 ...”
New sEddyProc class for site 'ES-Hen'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -70 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Hen-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 119 data points (0.68%) set to NA
LE: 147 data points (0.84%) set to NA
NEE: 1476 data points (8.42%) set to NA
-------------------------------------------------------------------
Data filtering:
864 data points (4.93%) excluded by growing season filter
2036 additional data points (11.62%) excluded by precipitation filter (2036
 data points = 11.62 % in total)
2900 data points (16.55%) excluded in total
14620 valid data points (83.45%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 119 data points (0.68%) set to NA
LE: 147 data points (0.84%) set to NA
NEE: 1476 data points (8.42%) set to NA
-------------------------------------------------------------------
Data filtering:
864 data points (4.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
864 data points (4.93%) excluded in total
16656 valid data points (95.07%) remaining.

New sEddyProc class for site 'ES-Hen'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Hen-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1551 data points (8.85%) set to NA
LE: 1645 data points (9.39%) set to NA
NEE: 2728 data points (15.57%) set to NA
-------------------------------------------------------------------
Data filtering:
4080 data points (23.29%) excluded by growing season filter
2293 additional data points (13.09%) excluded by precipitation filter (2567
 data points = 14.65 % in total)
6373 data points (36.38%) excluded in total
11147 valid data points (63.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1551 data points (8.85%) set to NA
LE: 1645 data points (9.39%) set to NA
NEE: 2728 data points (15.57%) set to NA
-------------------------------------------------------------------
Data filtering:
4080 data points (23.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4080 data points (23.29%) excluded in total
13440 valid data points (76.71%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -57, -77 ...”
New sEddyProc class for site 'ES-Hen'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -57, -77 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Hen-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 417 data points (2.38%) set to NA
LE: 482 data points (2.75%) set to NA
NEE: 1481 data points (8.45%) set to NA
-------------------------------------------------------------------
Data filtering:
4416 data points (25.21%) excluded by growing season filter
1886 additional data points (10.76%) excluded by precipitation filter (2185
 data points = 12.47 % in total)
6302 data points (35.97%) excluded in total
11218 valid data points (64.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 417 data points (2.38%) set to NA
LE: 482 data points (2.75%) set to NA
NEE: 1481 data points (8.45%) set to NA
-------------------------------------------------------------------
Data filtering:
4416 data points (25.21%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4416 data points (25.21%) excluded in total
13104 valid data points (74.79%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -69 ...”
New sEddyProc class for site 'ES-Hen'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -69 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Hen-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 471 data points (2.68%) set to NA
H: 514 data points (2.93%) set to NA
LE: 612 data points (3.48%) set to NA
NEE: 1995 data points (11.36%) set to NA
-------------------------------------------------------------------
Data filtering:
4080 data points (23.22%) excluded by growing season filter
1898 additional data points (10.8%) excluded by precipitation filter (2418
 data points = 13.76 % in total)
5978 data points (34.03%) excluded in total
11590 valid data points (65.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 471 data points (2.68%) set to NA
H: 514 data points (2.93%) set to NA
LE: 612 data points (3.48%) set to NA
NEE: 1995 data points (11.36%) set to NA
-------------------------------------------------------------------
Data filtering:
4080 data points (23.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4080 data points (23.22%) excluded in total
13488 valid data points (76.78%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -58, -73, -73, -69 ...”
New sEddyProc class for site 'ES-Hen'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -58, -73, -73, -69 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Hen-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[108/329] Processing: ES-LJu

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-LJu | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 7821 data points (44.64%) set to NA
H: 7825 data points (44.66%) set to NA
LE: 7853 data points (44.82%) set to NA
NEE: 7992 data points (45.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3351 additional data points (19.13%) excluded by precipitation filter (3351
 data points = 19.13 % in total)
3351 data points (19.13%) excluded in total
14169 valid data points (80.87%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7821 data points (44.64%) set to NA
H: 7825 data points (44.66%) set to NA
LE: 7853 data points (44.82%) set to NA
NEE: 7992 data points (45.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-LJu'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 167.71.

Regression of reference temperature R_ref for 32 periods.

Quality control:
TA: 3534 data points (20.17%) set to NA
H: 3538 data points (20.19%) set to NA
LE: 3534 data points (20.17%) set to NA
NEE: 3667 data points (20.93%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5645 additional data points (32.22%) excluded by precipitation filter (5645
 data points = 32.22 % in total)
5645 data points (32.22%) excluded in total
11875 valid data points (67.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3534 data points (20.17%) set to NA
H: 3538 data points (20.19%) set to NA
LE: 3534 data points (20.17%) set to NA
NEE: 3667 data points (20.93%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-LJu'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 21 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LJu-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 9005 data points (51.4%) set to NA
H: 9079 data points (51.82%) set to NA
LE: 9108 data points (51.99%) set to NA
NEE: 11832 data points (67.53%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3399 additional data points (19.4%) excluded by precipitation filter (3399
 data points = 19.4 % in total)
3399 data points (19.4%) excluded in total
14121 valid data points (80.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9005 data points (51.4%) set to NA
H: 9079 data points (51.82%) set to NA
LE: 9108 data points (51.99%) set to NA
NEE: 11832 data points (67.53%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-LJu'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 80.64.

Regression of reference temperature R_ref for 23 periods.

Quality control:
TA: 987 data points (5.62%) set to NA
H: 991 data points (5.64%) set to NA
LE: 1001 data points (5.7%) set to NA
NEE: 2204 data points (12.55%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4035 additional data points (22.97%) excluded by precipitation filter (4035
 data points = 22.97 % in total)
4035 data points (22.97%) excluded in total
13533 valid data points (77.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 987 data points (5.62%) set to NA
H: 991 data points (5.64%) set to NA
LE: 1001 data points (5.7%) set to NA
NEE: 2204 data points (12.55%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'ES-LJu'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LJu-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 5359 data points (30.59%) set to NA
H: 5360 data points (30.59%) set to NA
LE: 5368 data points (30.64%) set to NA
NEE: 5919 data points (33.78%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4676 additional data points (26.69%) excluded by precipitation filter (4676
 data points = 26.69 % in total)
4676 data points (26.69%) excluded in total
12844 valid data points (73.31%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5359 data points (30.59%) set to NA
H: 5360 data points (30.59%) set to NA
LE: 5368 data points (30.64%) set to NA
NEE: 5919 data points (33.78%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-LJu'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 15 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LJu-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1334 data points (7.61%) set to NA
H: 1459 data points (8.33%) set to NA
LE: 1339 data points (7.64%) set to NA
NEE: 3382 data points (19.3%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4650 additional data points (26.54%) excluded by precipitation filter (4650
 data points = 26.54 % in total)
4650 data points (26.54%) excluded in total
12870 valid data points (73.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1334 data points (7.61%) set to NA
H: 1459 data points (8.33%) set to NA
LE: 1339 data points (7.64%) set to NA
NEE: 3382 data points (19.3%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-LJu'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 253.94.

Regression of reference temperature R_ref for 10 periods.

Quality control:
TA: 3420 data points (19.52%) set to NA
H: 3492 data points (19.93%) set to NA
LE: 3424 data points (19.54%) set to NA
NEE: 5195 data points (29.65%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3141 additional data points (17.93%) excluded by precipitation filter (3141
 data points = 17.93 % in total)
3141 data points (17.93%) excluded in total
14379 valid data points (82.07%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3420 data points (19.52%) set to NA
H: 3492 data points (19.93%) set to NA
LE: 3424 data points (19.54%) set to NA
NEE: 5195 data points (29.65%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ES-LJu'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 11 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LJu-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3871 data points (22.03%) set to NA
H: 4555 data points (25.93%) set to NA
LE: 4559 data points (25.95%) set to NA
NEE: 5476 data points (31.17%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2534 additional data points (14.42%) excluded by precipitation filter (2534
 data points = 14.42 % in total)
2534 data points (14.42%) excluded in total
15034 valid data points (85.58%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3871 data points (22.03%) set to NA
H: 4555 data points (25.93%) set to NA
LE: 4559 data points (25.95%) set to NA
NEE: 5476 data points (31.17%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'ES-LJu'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 110.03.

Regression of reference temperature R_ref for 27 periods.

[109/329] Processing: ES-LM1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-LM1 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 17 data points (0.1%) set to NA
LE: 27 data points (0.15%) set to NA
NEE: 1142 data points (6.52%) set to NA
-------------------------------------------------------------------
Data filtering:
6000 data points (34.25%) excluded by growing season filter
2047 additional data points (11.68%) excluded by precipitation filter (2611
 data points = 14.9 % in total)
8047 data points (45.93%) excluded in total
9473 valid data points (54.07%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 17 data points (0.1%) set to NA
LE: 27 data points (0.15%) set to NA
NEE: 1142 data points (6.52%) set to NA
-------------------------------------------------------------------
Data filtering:
6000 data points (34.25%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6000 data points (34.25%) excluded in total
11520 valid data points (65.75%) remaining.

New sEddyProc class for site 'ES-LM1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LM1-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 23 data points (0.13%) set to NA
LE: 232 data points (1.32%) set to NA
NEE: 708 data points (4.04%) set to NA
-------------------------------------------------------------------
Data filtering:
7488 data points (42.74%) excluded by growing season filter
2991 additional data points (17.07%) excluded by precipitation filter (4476
 data points = 25.55 % in total)
10479 data points (59.81%) excluded in total
7041 valid data points (40.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 23 data points (0.13%) set to NA
LE: 232 data points (1.32%) set to NA
NEE: 708 data points (4.04%) set to NA
-------------------------------------------------------------------
Data filtering:
7488 data points (42.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7488 data points (42.74%) excluded in total
10032 valid data points (57.26%) remaining.

New sEddyProc class for site 'ES-LM1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LM1-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 222 data points (1.27%) set to NA
H: 224 data points (1.28%) set to NA
LE: 248 data points (1.42%) set to NA
NEE: 944 data points (5.39%) set to NA
-------------------------------------------------------------------
Data filtering:
5904 data points (33.7%) excluded by growing season filter
3036 additional data points (17.33%) excluded by precipitation filter (3759
 data points = 21.46 % in total)
8940 data points (51.03%) excluded in total
8580 valid data points (48.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 222 data points (1.27%) set to NA
H: 224 data points (1.28%) set to NA
LE: 248 data points (1.42%) set to NA
NEE: 944 data points (5.39%) set to NA
-------------------------------------------------------------------
Data filtering:
5904 data points (33.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5904 data points (33.7%) excluded in total
11616 valid data points (66.3%) remaining.

New sEddyProc class for site 'ES-LM1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LM1-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 40 data points (0.23%) set to NA
LE: 40 data points (0.23%) set to NA
NEE: 535 data points (3.05%) set to NA
-------------------------------------------------------------------
Data filtering:
5808 data points (33.06%) excluded by growing season filter
3026 additional data points (17.22%) excluded by precipitation filter (4085
 data points = 23.25 % in total)
8834 data points (50.28%) excluded in total
8734 valid data points (49.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 40 data points (0.23%) set to NA
LE: 40 data points (0.23%) set to NA
NEE: 535 data points (3.05%) set to NA
-------------------------------------------------------------------
Data filtering:
5808 data points (33.06%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5808 data points (33.06%) excluded in total
11760 valid data points (66.94%) remaining.

New sEddyProc class for site 'ES-LM1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LM1-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 71 data points (0.41%) set to NA
LE: 82 data points (0.47%) set to NA
NEE: 852 data points (4.86%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.85%) excluded by growing season filter
2088 additional data points (11.92%) excluded by precipitation filter (3359
 data points = 19.17 % in total)
10296 data points (58.77%) excluded in total
7224 valid data points (41.23%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 71 data points (0.41%) set to NA
LE: 82 data points (0.47%) set to NA
NEE: 852 data points (4.86%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8208 data points (46.85%) excluded in total
9312 valid data points (53.15%) remaining.

New sEddyProc class for site 'ES-LM1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LM1-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1434 data points (8.18%) set to NA
H: 1175 data points (6.71%) set to NA
LE: 1186 data points (6.77%) set to NA
NEE: 1871 data points (10.68%) set to NA
-------------------------------------------------------------------
Data filtering:
6192 data points (35.34%) excluded by growing season filter
3467 additional data points (19.79%) excluded by precipitation filter (4318
 data points = 24.65 % in total)
9659 data points (55.13%) excluded in total
7861 valid data points (44.87%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1434 data points (8.18%) set to NA
H: 1175 data points (6.71%) set to NA
LE: 1186 data points (6.77%) set to NA
NEE: 1871 data points (10.68%) set to NA
-------------------------------------------------------------------
Data filtering:
6192 data points (35.34%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6192 data points (35.34%) excluded in total
11328 valid data points (64.66%) remaining.

New sEddyProc class for site 'ES-LM1'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 131.32.

Regression of reference temperature R_ref for 13 periods.

Quality control:
TA: 808 data points (4.61%) set to NA
H: 34 data points (0.19%) set to NA
LE: 58 data points (0.33%) set to NA
NEE: 980 data points (5.59%) set to NA
-------------------------------------------------------------------
Data filtering:
4512 data points (25.75%) excluded by growing season filter
2273 additional data points (12.97%) excluded by precipitation filter (3269
 data points = 18.66 % in total)
6785 data points (38.73%) excluded in total
10735 valid data points (61.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 808 data points (4.61%) set to NA
H: 34 data points (0.19%) set to NA
LE: 58 data points (0.33%) set to NA
NEE: 980 data points (5.59%) set to NA
-------------------------------------------------------------------
Data filtering:
4512 data points (25.75%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4512 data points (25.75%) excluded in total
13008 valid data points (74.25%) remaining.

New sEddyProc class for site 'ES-LM1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LM1-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 451 data points (2.57%) set to NA
H: 472 data points (2.69%) set to NA
LE: 4929 data points (28.06%) set to NA
NEE: 5570 data points (31.71%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 39”

-------------------------------------------------------------------
Data filtering:
3264 data points (18.58%) excluded by growing season filter
4039 additional data points (22.99%) excluded by precipitation filter (4233
 data points = 24.09 % in total)
7303 data points (41.57%) excluded in total
10265 valid data points (58.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 451 data points (2.57%) set to NA
H: 472 data points (2.69%) set to NA
LE: 4929 data points (28.06%) set to NA
NEE: 5570 data points (31.71%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 39”

-------------------------------------------------------------------
Data filtering:
3264 data points (18.58%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3264 data points (18.58%) excluded in total
14304 valid data points (81.42%) remaining.

New sEddyProc class for site 'ES-LM1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LM1-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[110/329] Processing: ES-LM2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-LM2 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 9 data points (0.05%) set to NA
H: 553 data points (3.16%) set to NA
LE: 551 data points (3.14%) set to NA
NEE: 1354 data points (7.73%) set to NA
-------------------------------------------------------------------
Data filtering:
6336 data points (36.16%) excluded by growing season filter
1955 additional data points (11.16%) excluded by precipitation filter (2550
 data points = 14.55 % in total)
8291 data points (47.32%) excluded in total
9229 valid data points (52.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9 data points (0.05%) set to NA
H: 553 data points (3.16%) set to NA
LE: 551 data points (3.14%) set to NA
NEE: 1354 data points (7.73%) set to NA
-------------------------------------------------------------------
Data filtering:
6336 data points (36.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6336 data points (36.16%) excluded in total
11184 valid data points (63.84%) remaining.

New sEddyProc class for site 'ES-LM2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LM2-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 15 data points (0.09%) set to NA
H: 177 data points (1.01%) set to NA
LE: 176 data points (1%) set to NA
NEE: 630 data points (3.6%) set to NA
-------------------------------------------------------------------
Data filtering:
6144 data points (35.07%) excluded by growing season filter
3406 additional data points (19.44%) excluded by precipitation filter (4237
 data points = 24.18 % in total)
9550 data points (54.51%) excluded in total
7970 valid data points (45.49%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 15 data points (0.09%) set to NA
H: 177 data points (1.01%) set to NA
LE: 176 data points (1%) set to NA
NEE: 630 data points (3.6%) set to NA
-------------------------------------------------------------------
Data filtering:
6144 data points (35.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6144 data points (35.07%) excluded in total
11376 valid data points (64.93%) remaining.

New sEddyProc class for site 'ES-LM2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LM2-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 48 data points (0.27%) set to NA
LE: 77 data points (0.44%) set to NA
NEE: 686 data points (3.92%) set to NA
-------------------------------------------------------------------
Data filtering:
5184 data points (29.59%) excluded by growing season filter
2804 additional data points (16%) excluded by precipitation filter (3573
 data points = 20.39 % in total)
7988 data points (45.59%) excluded in total
9532 valid data points (54.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 48 data points (0.27%) set to NA
LE: 77 data points (0.44%) set to NA
NEE: 686 data points (3.92%) set to NA
-------------------------------------------------------------------
Data filtering:
5184 data points (29.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5184 data points (29.59%) excluded in total
12336 valid data points (70.41%) remaining.

New sEddyProc class for site 'ES-LM2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LM2-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 20 data points (0.11%) set to NA
LE: 27 data points (0.15%) set to NA
NEE: 505 data points (2.87%) set to NA
-------------------------------------------------------------------
Data filtering:
6912 data points (39.34%) excluded by growing season filter
2842 additional data points (16.18%) excluded by precipitation filter (4180
 data points = 23.79 % in total)
9754 data points (55.52%) excluded in total
7814 valid data points (44.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 20 data points (0.11%) set to NA
LE: 27 data points (0.15%) set to NA
NEE: 505 data points (2.87%) set to NA
-------------------------------------------------------------------
Data filtering:
6912 data points (39.34%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6912 data points (39.34%) excluded in total
10656 valid data points (60.66%) remaining.

New sEddyProc class for site 'ES-LM2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LM2-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 7 data points (0.04%) set to NA
LE: 1051 data points (6%) set to NA
NEE: 1560 data points (8.9%) set to NA
-------------------------------------------------------------------
Data filtering:
3648 data points (20.82%) excluded by growing season filter
3138 additional data points (17.91%) excluded by precipitation filter (3477
 data points = 19.85 % in total)
6786 data points (38.73%) excluded in total
10734 valid data points (61.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 7 data points (0.04%) set to NA
LE: 1051 data points (6%) set to NA
NEE: 1560 data points (8.9%) set to NA
-------------------------------------------------------------------
Data filtering:
3648 data points (20.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3648 data points (20.82%) excluded in total
13872 valid data points (79.18%) remaining.

New sEddyProc class for site 'ES-LM2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LM2-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2363 data points (13.49%) set to NA
H: 1313 data points (7.49%) set to NA
LE: 1355 data points (7.73%) set to NA
NEE: 2236 data points (12.76%) set to NA
-------------------------------------------------------------------
Data filtering:
6288 data points (35.89%) excluded by growing season filter
3494 additional data points (19.94%) excluded by precipitation filter (4318
 data points = 24.65 % in total)
9782 data points (55.83%) excluded in total
7738 valid data points (44.17%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2363 data points (13.49%) set to NA
H: 1313 data points (7.49%) set to NA
LE: 1355 data points (7.73%) set to NA
NEE: 2236 data points (12.76%) set to NA
-------------------------------------------------------------------
Data filtering:
6288 data points (35.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6288 data points (35.89%) excluded in total
11232 valid data points (64.11%) remaining.

New sEddyProc class for site 'ES-LM2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 14 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LM2-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 820 data points (4.68%) set to NA
H: 78 data points (0.45%) set to NA
LE: 518 data points (2.96%) set to NA
NEE: 1278 data points (7.29%) set to NA
-------------------------------------------------------------------
Data filtering:
4272 data points (24.38%) excluded by growing season filter
2487 additional data points (14.2%) excluded by precipitation filter (3269
 data points = 18.66 % in total)
6759 data points (38.58%) excluded in total
10761 valid data points (61.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 820 data points (4.68%) set to NA
H: 78 data points (0.45%) set to NA
LE: 518 data points (2.96%) set to NA
NEE: 1278 data points (7.29%) set to NA
-------------------------------------------------------------------
Data filtering:
4272 data points (24.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4272 data points (24.38%) excluded in total
13248 valid data points (75.62%) remaining.

New sEddyProc class for site 'ES-LM2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LM2-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 8 data points (0.05%) set to NA
LE: 1578 data points (8.98%) set to NA
NEE: 2306 data points (13.13%) set to NA
-------------------------------------------------------------------
Data filtering:
2976 data points (16.94%) excluded by growing season filter
3661 additional data points (20.84%) excluded by precipitation filter (4233
 data points = 24.09 % in total)
6637 data points (37.78%) excluded in total
10931 valid data points (62.22%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 8 data points (0.05%) set to NA
LE: 1578 data points (8.98%) set to NA
NEE: 2306 data points (13.13%) set to NA
-------------------------------------------------------------------
Data filtering:
2976 data points (16.94%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2976 data points (16.94%) excluded in total
14592 valid data points (83.06%) remaining.

New sEddyProc class for site 'ES-LM2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LM2-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[111/329] Processing: ES-LMa

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-LMa | Years: 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 35 data points (0.2%) set to NA
LE: 47 data points (0.27%) set to NA
NEE: 664 data points (3.78%) set to NA
-------------------------------------------------------------------
Data filtering:
8112 data points (46.17%) excluded by growing season filter
2669 additional data points (15.19%) excluded by precipitation filter (4280
 data points = 24.36 % in total)
10781 data points (61.37%) excluded in total
6787 valid data points (38.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 35 data points (0.2%) set to NA
LE: 47 data points (0.27%) set to NA
NEE: 664 data points (3.78%) set to NA
-------------------------------------------------------------------
Data filtering:
8112 data points (46.17%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8112 data points (46.17%) excluded in total
9456 valid data points (53.83%) remaining.

New sEddyProc class for site 'ES-LMa'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LMa-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 178 data points (1.02%) set to NA
LE: 183 data points (1.04%) set to NA
NEE: 1051 data points (6%) set to NA
-------------------------------------------------------------------
Data filtering:
4176 data points (23.84%) excluded by growing season filter
2946 additional data points (16.82%) excluded by precipitation filter (3457
 data points = 19.73 % in total)
7122 data points (40.65%) excluded in total
10398 valid data points (59.35%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 178 data points (1.02%) set to NA
LE: 183 data points (1.04%) set to NA
NEE: 1051 data points (6%) set to NA
-------------------------------------------------------------------
Data filtering:
4176 data points (23.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4176 data points (23.84%) excluded in total
13344 valid data points (76.16%) remaining.

New sEddyProc class for site 'ES-LMa'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LMa-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 685 data points (3.91%) set to NA
H: 1013 data points (5.78%) set to NA
LE: 1047 data points (5.98%) set to NA
NEE: 1907 data points (10.88%) set to NA
-------------------------------------------------------------------
Data filtering:
6528 data points (37.26%) excluded by growing season filter
3143 additional data points (17.94%) excluded by precipitation filter (4114
 data points = 23.48 % in total)
9671 data points (55.2%) excluded in total
7849 valid data points (44.8%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 685 data points (3.91%) set to NA
H: 1013 data points (5.78%) set to NA
LE: 1047 data points (5.98%) set to NA
NEE: 1907 data points (10.88%) set to NA
-------------------------------------------------------------------
Data filtering:
6528 data points (37.26%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6528 data points (37.26%) excluded in total
10992 valid data points (62.74%) remaining.

New sEddyProc class for site 'ES-LMa'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LMa-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 34 data points (0.19%) set to NA
H: 137 data points (0.78%) set to NA
LE: 166 data points (0.95%) set to NA
NEE: 865 data points (4.94%) set to NA
-------------------------------------------------------------------
Data filtering:
3600 data points (20.55%) excluded by growing season filter
2226 additional data points (12.71%) excluded by precipitation filter (3253
 data points = 18.57 % in total)
5826 data points (33.25%) excluded in total
11694 valid data points (66.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 34 data points (0.19%) set to NA
H: 137 data points (0.78%) set to NA
LE: 166 data points (0.95%) set to NA
NEE: 865 data points (4.94%) set to NA
-------------------------------------------------------------------
Data filtering:
3600 data points (20.55%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3600 data points (20.55%) excluded in total
13920 valid data points (79.45%) remaining.

New sEddyProc class for site 'ES-LMa'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LMa-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 26 data points (0.15%) set to NA
H: 156 data points (0.89%) set to NA
LE: 246 data points (1.4%) set to NA
NEE: 907 data points (5.16%) set to NA
-------------------------------------------------------------------
Data filtering:
3168 data points (18.03%) excluded by growing season filter
3955 additional data points (22.51%) excluded by precipitation filter (4233
 data points = 24.09 % in total)
7123 data points (40.55%) excluded in total
10445 valid data points (59.45%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 26 data points (0.15%) set to NA
H: 156 data points (0.89%) set to NA
LE: 246 data points (1.4%) set to NA
NEE: 907 data points (5.16%) set to NA
-------------------------------------------------------------------
Data filtering:
3168 data points (18.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3168 data points (18.03%) excluded in total
14400 valid data points (81.97%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -67, -73, -62 ...”
New sEddyProc class for site 'ES-LMa'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -67, -73, -62 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-LMa-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[112/329] Processing: ES-Mcd

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-Mcd | Years: 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 9656 data points (55.11%) set to NA
H: 9745 data points (55.62%) set to NA
LE: 9747 data points (55.63%) set to NA
NEE: 9800 data points (55.94%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 175”

-------------------------------------------------------------------
Data filtering:
960 data points (5.48%) excluded by growing season filter
4003 additional data points (22.85%) excluded by precipitation filter (4003
 data points = 22.85 % in total)
4963 data points (28.33%) excluded in total
12557 valid data points (71.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9656 data points (55.11%) set to NA
H: 9745 data points (55.62%) set to NA
LE: 9747 data points (55.63%) set to NA
NEE: 9800 data points (55.94%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 175”

-------------------------------------------------------------------
Data filtering:
960 data points (5.48%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
960 data points (5.48%) excluded in total
16560 valid data points (94.52%) remaining.

New sEddyProc class for site 'ES-Mcd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 18 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Mcd-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 826 data points (4.71%) set to NA
H: 414 data points (2.36%) set to NA
LE: 508 data points (2.9%) set to NA
NEE: 1067 data points (6.09%) set to NA
-------------------------------------------------------------------
Data filtering:
4128 data points (23.56%) excluded by growing season filter
6026 additional data points (34.39%) excluded by precipitation filter (6175
 data points = 35.25 % in total)
10154 data points (57.96%) excluded in total
7366 valid data points (42.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 826 data points (4.71%) set to NA
H: 414 data points (2.36%) set to NA
LE: 508 data points (2.9%) set to NA
NEE: 1067 data points (6.09%) set to NA
-------------------------------------------------------------------
Data filtering:
4128 data points (23.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4128 data points (23.56%) excluded in total
13392 valid data points (76.44%) remaining.

New sEddyProc class for site 'ES-Mcd'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 210.08.

Regression of reference temperature R_ref for 8 periods.

Quality control:
TA: 3409 data points (19.4%) set to NA
H: 81 data points (0.46%) set to NA
LE: 166 data points (0.94%) set to NA
NEE: 1435 data points (8.17%) set to NA
-------------------------------------------------------------------
Data filtering:
3408 data points (19.4%) excluded by growing season filter
4327 additional data points (24.63%) excluded by precipitation filter (4689
 data points = 26.69 % in total)
7735 data points (44.03%) excluded in total
9833 valid data points (55.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3409 data points (19.4%) set to NA
H: 81 data points (0.46%) set to NA
LE: 166 data points (0.94%) set to NA
NEE: 1435 data points (8.17%) set to NA
-------------------------------------------------------------------
Data filtering:
3408 data points (19.4%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3408 data points (19.4%) excluded in total
14160 valid data points (80.6%) remaining.

New sEddyProc class for site 'ES-Mcd'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 149.18.

Regression of reference temperature R_ref for 21 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 121 data points (0.69%) set to NA
LE: 123 data points (0.7%) set to NA
NEE: 443 data points (2.53%) set to NA
-------------------------------------------------------------------
Data filtering:
3936 data points (22.47%) excluded by growing season filter
3103 additional data points (17.71%) excluded by precipitation filter (3902
 data points = 22.27 % in total)
7039 data points (40.18%) excluded in total
10481 valid data points (59.82%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 121 data points (0.69%) set to NA
LE: 123 data points (0.7%) set to NA
NEE: 443 data points (2.53%) set to NA
-------------------------------------------------------------------
Data filtering:
3936 data points (22.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3936 data points (22.47%) excluded in total
13584 valid data points (77.53%) remaining.

New sEddyProc class for site 'ES-Mcd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Mcd-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 25 data points (0.14%) set to NA
H: 78 data points (0.45%) set to NA
LE: 90 data points (0.51%) set to NA
NEE: 540 data points (3.08%) set to NA
-------------------------------------------------------------------
Data filtering:
5376 data points (30.68%) excluded by growing season filter
2795 additional data points (15.95%) excluded by precipitation filter (5829
 data points = 33.27 % in total)
8171 data points (46.64%) excluded in total
9349 valid data points (53.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 25 data points (0.14%) set to NA
H: 78 data points (0.45%) set to NA
LE: 90 data points (0.51%) set to NA
NEE: 540 data points (3.08%) set to NA
-------------------------------------------------------------------
Data filtering:
5376 data points (30.68%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5376 data points (30.68%) excluded in total
12144 valid data points (69.32%) remaining.

New sEddyProc class for site 'ES-Mcd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Mcd-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 78 data points (0.45%) set to NA
H: 279 data points (1.59%) set to NA
LE: 279 data points (1.59%) set to NA
NEE: 873 data points (4.98%) set to NA
-------------------------------------------------------------------
Data filtering:
6048 data points (34.52%) excluded by growing season filter
1495 additional data points (8.53%) excluded by precipitation filter (2380
 data points = 13.58 % in total)
7543 data points (43.05%) excluded in total
9977 valid data points (56.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 78 data points (0.45%) set to NA
H: 279 data points (1.59%) set to NA
LE: 279 data points (1.59%) set to NA
NEE: 873 data points (4.98%) set to NA
-------------------------------------------------------------------
Data filtering:
6048 data points (34.52%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6048 data points (34.52%) excluded in total
11472 valid data points (65.48%) remaining.

New sEddyProc class for site 'ES-Mcd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Mcd-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 13 data points (0.07%) set to NA
H: 75 data points (0.43%) set to NA
LE: 81 data points (0.46%) set to NA
NEE: 683 data points (3.89%) set to NA
-------------------------------------------------------------------
Data filtering:
4944 data points (28.14%) excluded by growing season filter
2521 additional data points (14.35%) excluded by precipitation filter (4210
 data points = 23.96 % in total)
7465 data points (42.49%) excluded in total
10103 valid data points (57.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 13 data points (0.07%) set to NA
H: 75 data points (0.43%) set to NA
LE: 81 data points (0.46%) set to NA
NEE: 683 data points (3.89%) set to NA
-------------------------------------------------------------------
Data filtering:
4944 data points (28.14%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4944 data points (28.14%) excluded in total
12624 valid data points (71.86%) remaining.

New sEddyProc class for site 'ES-Mcd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Mcd-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[113/329] Processing: ES-MtB

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-MtB | Years: 2021, 2022, 2023, 2024
Quality control:
TA: 1228 data points (7.01%) set to NA
H: 1365 data points (7.79%) set to NA
LE: 1504 data points (8.58%) set to NA
NEE: 2664 data points (15.21%) set to NA
-------------------------------------------------------------------
Data filtering:
2976 data points (16.99%) excluded by growing season filter
3084 additional data points (17.6%) excluded by precipitation filter (4666
 data points = 26.63 % in total)
6060 data points (34.59%) excluded in total
11460 valid data points (65.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1228 data points (7.01%) set to NA
H: 1365 data points (7.79%) set to NA
LE: 1504 data points (8.58%) set to NA
NEE: 2664 data points (15.21%) set to NA
-------------------------------------------------------------------
Data filtering:
2976 data points (16.99%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2976 data points (16.99%) excluded in total
14544 valid data points (83.01%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -53, -54, -55 ...”
New sEddyProc class for site 'ES-MtB'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -53, -54, -55 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-MtB-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 7 data points (0.04%) set to NA
LE: 49 data points (0.28%) set to NA
NEE: 299 data points (1.71%) set to NA
-------------------------------------------------------------------
Data filtering:
2400 data points (13.7%) excluded by growing season filter
3896 additional data points (22.24%) excluded by precipitation filter (4972
 data points = 28.38 % in total)
6296 data points (35.94%) excluded in total
11224 valid data points (64.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 7 data points (0.04%) set to NA
LE: 49 data points (0.28%) set to NA
NEE: 299 data points (1.71%) set to NA
-------------------------------------------------------------------
Data filtering:
2400 data points (13.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2400 data points (13.7%) excluded in total
15120 valid data points (86.3%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -58, -54, -65, -55, -52, -59, -63, -61, -59 ...”
New sEddyProc class for site 'ES-MtB'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -58, -54, -65, -55, -52, -59, -63, -61, -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-MtB-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3 data points (0.02%) set to NA
H: 14 data points (0.08%) set to NA
LE: 46 data points (0.26%) set to NA
NEE: 220 data points (1.26%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4140 additional data points (23.63%) excluded by precipitation filter (4140
 data points = 23.63 % in total)
4140 data points (23.63%) excluded in total
13380 valid data points (76.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3 data points (0.02%) set to NA
H: 14 data points (0.08%) set to NA
LE: 46 data points (0.26%) set to NA
NEE: 220 data points (1.26%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -62, -53, -67 ...”
New sEddyProc class for site 'ES-MtB'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -62, -53, -67 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-MtB-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3 data points (0.02%) set to NA
H: 16 data points (0.09%) set to NA
LE: 102 data points (0.58%) set to NA
NEE: 1132 data points (6.44%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4862 additional data points (27.68%) excluded by precipitation filter (4862
 data points = 27.68 % in total)
4862 data points (27.68%) excluded in total
12706 valid data points (72.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3 data points (0.02%) set to NA
H: 16 data points (0.09%) set to NA
LE: 102 data points (0.58%) set to NA
NEE: 1132 data points (6.44%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -62, -57 ...”
New sEddyProc class for site 'ES-MtB'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -62, -57 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-MtB-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[114/329] Processing: ES-MtN

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-MtN | Years: 2024
Quality control:
TA: 7476 data points (42.55%) set to NA
H: 7482 data points (42.59%) set to NA
LE: 7504 data points (42.71%) set to NA
NEE: 7683 data points (43.73%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 145”

-------------------------------------------------------------------
Data filtering:
384 data points (2.19%) excluded by growing season filter
4862 additional data points (27.68%) excluded by precipitation filter (4862
 data points = 27.68 % in total)
5246 data points (29.86%) excluded in total
12322 valid data points (70.14%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7476 data points (42.55%) set to NA
H: 7482 data points (42.59%) set to NA
LE: 7504 data points (42.71%) set to NA
NEE: 7683 data points (43.73%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 145”

-------------------------------------------------------------------
Data filtering:
384 data points (2.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
384 data points (2.19%) excluded in total
17184 valid data points (97.81%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 11 cases! Invalid values with 'NEE < -50': -63, -59, -64, -75, -52, -52, -75, -64, -75, -62, -74 ...”
New sEddyProc class for site 'ES-MtN'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 11 cases! Invalid values with 'NEE < -50': -63, -59, -64, -75, -52, -52, -75, -64, -75, -62, -74 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 183.02.

Regression of reference temperature R_ref for 7 periods.

[115/329] Processing: ES-Mzn

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-Mzn | Years: 2023, 2024
Quality control:
TA: 7239 data points (41.32%) set to NA
H: 7244 data points (41.35%) set to NA
LE: 7255 data points (41.41%) set to NA
NEE: 7685 data points (43.86%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 141”

-------------------------------------------------------------------
Data filtering:
2112 data points (12.05%) excluded by growing season filter
6466 additional data points (36.91%) excluded by precipitation filter (6694
 data points = 38.21 % in total)
8578 data points (48.96%) excluded in total
8942 valid data points (51.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7239 data points (41.32%) set to NA
H: 7244 data points (41.35%) set to NA
LE: 7255 data points (41.41%) set to NA
NEE: 7685 data points (43.86%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 141”

-------------------------------------------------------------------
Data filtering:
2112 data points (12.05%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2112 data points (12.05%) excluded in total
15408 valid data points (87.95%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 12 cases! Invalid values with 'NEE < -50': -78, -73, -52, -67, -72, -62, -63, -57, -61, -59, -65, -64 ...”
New sEddyProc class for site 'ES-Mzn'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 12 cases! Invalid values with 'NEE < -50': -78, -73, -52, -67, -72, -62, -63, -57, -61, -59, -65, -64 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 78.66.

Regression of reference temperature R_ref for 6 periods.

Quality control:
TA: 150 data points (0.85%) set to NA
H: 158 data points (0.9%) set to NA
LE: 167 data points (0.95%) set to NA
NEE: 574 data points (3.27%) set to NA
-------------------------------------------------------------------
Data filtering:
1200 data points (6.83%) excluded by growing season filter
7226 additional data points (41.13%) excluded by precipitation filter (7890
 data points = 44.91 % in total)
8426 data points (47.96%) excluded in total
9142 valid data points (52.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 150 data points (0.85%) set to NA
H: 158 data points (0.9%) set to NA
LE: 167 data points (0.95%) set to NA
NEE: 574 data points (3.27%) set to NA
-------------------------------------------------------------------
Data filtering:
1200 data points (6.83%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1200 data points (6.83%) excluded in total
16368 valid data points (93.17%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 22 cases! Invalid values with 'NEE < -50': -66, -62, -74, -64, -68, -71, -71, -72, -54, -72, -69, -67, -66, -66, -52, -51, -53, -69, -57, -62, -56, -71 ...”
New sEddyProc class for site 'ES-Mzn'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 22 cases! Invalid values with 'NEE < -50': -66, -62, -74, -64, -68, -71, -71, -72, -54, -72, -69, -67, -66, -66, -52, -51, -53, -69, -57, -62, -56, -71 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Mzn-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[116/329] Processing: ES-Srn

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-Srn | Years: 2023, 2024
Quality control:
TA: 7249 data points (41.38%) set to NA
H: 7260 data points (41.44%) set to NA
LE: 7279 data points (41.55%) set to NA
NEE: 7696 data points (43.93%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 142”

-------------------------------------------------------------------
Data filtering:
4512 data points (25.75%) excluded by growing season filter
6004 additional data points (34.27%) excluded by precipitation filter (7336
 data points = 41.87 % in total)
10516 data points (60.02%) excluded in total
7004 valid data points (39.98%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7249 data points (41.38%) set to NA
H: 7260 data points (41.44%) set to NA
LE: 7279 data points (41.55%) set to NA
NEE: 7696 data points (43.93%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 142”

-------------------------------------------------------------------
Data filtering:
4512 data points (25.75%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4512 data points (25.75%) excluded in total
13008 valid data points (74.25%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -54, -62, -57, -64 ...”
New sEddyProc class for site 'ES-Srn'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -54, -62, -57, -64 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 304.36.

Regression of reference temperature R_ref for 6 periods.

Quality control:
TA: 27 data points (0.15%) set to NA
H: 34 data points (0.19%) set to NA
LE: 47 data points (0.27%) set to NA
NEE: 314 data points (1.79%) set to NA
-------------------------------------------------------------------
Data filtering:
960 data points (5.46%) excluded by growing season filter
8294 additional data points (47.21%) excluded by precipitation filter (8760
 data points = 49.86 % in total)
9254 data points (52.68%) excluded in total
8314 valid data points (47.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 27 data points (0.15%) set to NA
H: 34 data points (0.19%) set to NA
LE: 47 data points (0.27%) set to NA
NEE: 314 data points (1.79%) set to NA
-------------------------------------------------------------------
Data filtering:
960 data points (5.46%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
960 data points (5.46%) excluded in total
16608 valid data points (94.54%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 10 cases! Invalid values with 'NEE < -50': -74, -53, -66, -61, -76, -50, -52, -54, -62, -60 ...”
New sEddyProc class for site 'ES-Srn'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 10 cases! Invalid values with 'NEE < -50': -74, -53, -66, -61, -76, -50, -52, -54, -62, -60 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Srn-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[117/329] Processing: ES-TzM

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-TzM | Years: 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 11485 data points (65.37%) set to NA
H: 11496 data points (65.44%) set to NA
LE: 11486 data points (65.38%) set to NA
NEE: 11564 data points (65.82%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6128 additional data points (34.88%) excluded by precipitation filter (6128
 data points = 34.88 % in total)
6128 data points (34.88%) excluded in total
11440 valid data points (65.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11485 data points (65.37%) set to NA
H: 11496 data points (65.44%) set to NA
LE: 11486 data points (65.38%) set to NA
NEE: 11564 data points (65.82%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -71, -64 ...”
New sEddyProc class for site 'ES-TzM'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -71, -64 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 188.57.

Regression of reference temperature R_ref for 12 periods.

Quality control:
TA: 7145 data points (40.78%) set to NA
H: 7158 data points (40.86%) set to NA
LE: 7165 data points (40.9%) set to NA
NEE: 7376 data points (42.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 108”

-------------------------------------------------------------------
Data filtering:
3072 data points (17.53%) excluded by growing season filter
5918 additional data points (33.78%) excluded by precipitation filter (6734
 data points = 38.44 % in total)
8990 data points (51.31%) excluded in total
8530 valid data points (48.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7145 data points (40.78%) set to NA
H: 7158 data points (40.86%) set to NA
LE: 7165 data points (40.9%) set to NA
NEE: 7376 data points (42.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 108”

-------------------------------------------------------------------
Data filtering:
3072 data points (17.53%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3072 data points (17.53%) excluded in total
14448 valid data points (82.47%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -56, -74, -65, -69, -61 ...”
New sEddyProc class for site 'ES-TzM'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -56, -74, -65, -69, -61 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 25 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-TzM-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3840 data points (21.92%) set to NA
H: 3863 data points (22.05%) set to NA
LE: 4015 data points (22.92%) set to NA
NEE: 4916 data points (28.06%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 14”

-------------------------------------------------------------------
Data filtering:
7008 data points (40%) excluded by growing season filter
3884 additional data points (22.17%) excluded by precipitation filter (7052
 data points = 40.25 % in total)
10892 data points (62.17%) excluded in total
6628 valid data points (37.83%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3840 data points (21.92%) set to NA
H: 3863 data points (22.05%) set to NA
LE: 4015 data points (22.92%) set to NA
NEE: 4916 data points (28.06%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 14”

-------------------------------------------------------------------
Data filtering:
7008 data points (40%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7008 data points (40%) excluded in total
10512 valid data points (60%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -55 ...”
New sEddyProc class for site 'ES-TzM'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -55 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 96.24.

Regression of reference temperature R_ref for 24 periods.

Quality control:
TA: 7829 data points (44.69%) set to NA
H: 7852 data points (44.82%) set to NA
LE: 7945 data points (45.35%) set to NA
NEE: 8685 data points (49.57%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 112”

-------------------------------------------------------------------
Data filtering:
3888 data points (22.19%) excluded by growing season filter
4890 additional data points (27.91%) excluded by precipitation filter (5736
 data points = 32.74 % in total)
8778 data points (50.1%) excluded in total
8742 valid data points (49.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7829 data points (44.69%) set to NA
H: 7852 data points (44.82%) set to NA
LE: 7945 data points (45.35%) set to NA
NEE: 8685 data points (49.57%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 112”

-------------------------------------------------------------------
Data filtering:
3888 data points (22.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3888 data points (22.19%) excluded in total
13632 valid data points (77.81%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 11 cases! Invalid values with 'NEE < -50': -67, -76, -58, -59, -64, -73, -54, -67, -57, -64, -60 ...”
New sEddyProc class for site 'ES-TzM'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 11 cases! Invalid values with 'NEE < -50': -67, -76, -58, -59, -64, -73, -54, -67, -57, -64, -60 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 264.85.

Regression of reference temperature R_ref for 37 periods.

Quality control:
TA: 5230 data points (29.77%) set to NA
H: 5246 data points (29.86%) set to NA
LE: 5303 data points (30.19%) set to NA
NEE: 5789 data points (32.95%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 44”

-------------------------------------------------------------------
Data filtering:
8400 data points (47.81%) excluded by growing season filter
2974 additional data points (16.93%) excluded by precipitation filter (6190
 data points = 35.23 % in total)
11374 data points (64.74%) excluded in total
6194 valid data points (35.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5230 data points (29.77%) set to NA
H: 5246 data points (29.86%) set to NA
LE: 5303 data points (30.19%) set to NA
NEE: 5789 data points (32.95%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 44”

-------------------------------------------------------------------
Data filtering:
8400 data points (47.81%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8400 data points (47.81%) excluded in total
9168 valid data points (52.19%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 12 cases! Invalid values with 'NEE < -50': -79, -62, -66, -55, -75, -61, -65, -58, -53, -52, -55, -60 ...”
New sEddyProc class for site 'ES-TzM'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 12 cases! Invalid values with 'NEE < -50': -79, -62, -66, -55, -75, -61, -65, -58, -53, -52, -55, -60 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 207.79.

Regression of reference temperature R_ref for 23 periods.

[118/329] Processing: ES-Yst

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ES-Yst | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 6974 data points (39.81%) set to NA
H: 7520 data points (42.92%) set to NA
LE: 7552 data points (43.11%) set to NA
NEE: 8011 data points (45.72%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 77”

-------------------------------------------------------------------
Data filtering:
1536 data points (8.77%) excluded by growing season filter
3691 additional data points (21.07%) excluded by precipitation filter (4224
 data points = 24.11 % in total)
5227 data points (29.83%) excluded in total
12293 valid data points (70.17%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6974 data points (39.81%) set to NA
H: 7520 data points (42.92%) set to NA
LE: 7552 data points (43.11%) set to NA
NEE: 8011 data points (45.72%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 77”

-------------------------------------------------------------------
Data filtering:
1536 data points (8.77%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1536 data points (8.77%) excluded in total
15984 valid data points (91.23%) remaining.

New sEddyProc class for site 'ES-Yst'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 258.76.

Regression of reference temperature R_ref for 26 periods.

Quality control:
TA: 2210 data points (12.58%) set to NA
H: 10216 data points (58.15%) set to NA
LE: 10247 data points (58.33%) set to NA
NEE: 11080 data points (63.07%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 183”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3635 additional data points (20.69%) excluded by precipitation filter (3635
 data points = 20.69 % in total)
3635 data points (20.69%) excluded in total
13933 valid data points (79.31%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2210 data points (12.58%) set to NA
H: 10216 data points (58.15%) set to NA
LE: 10247 data points (58.33%) set to NA
NEE: 11080 data points (63.07%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 183”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'ES-Yst'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 216.78.

Regression of reference temperature R_ref for 5 periods.

Quality control:
TA: 2030 data points (11.59%) set to NA
H: 2962 data points (16.91%) set to NA
LE: 2990 data points (17.07%) set to NA
NEE: 3985 data points (22.75%) set to NA
-------------------------------------------------------------------
Data filtering:
5568 data points (31.78%) excluded by growing season filter
2543 additional data points (14.51%) excluded by precipitation filter (4077
 data points = 23.27 % in total)
8111 data points (46.3%) excluded in total
9409 valid data points (53.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2030 data points (11.59%) set to NA
H: 2962 data points (16.91%) set to NA
LE: 2990 data points (17.07%) set to NA
NEE: 3985 data points (22.75%) set to NA
-------------------------------------------------------------------
Data filtering:
5568 data points (31.78%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5568 data points (31.78%) excluded in total
11952 valid data points (68.22%) remaining.

New sEddyProc class for site 'ES-Yst'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 149.52.

Regression of reference temperature R_ref for 13 periods.

Quality control:
TA: 66 data points (0.38%) set to NA
H: 1214 data points (6.93%) set to NA
LE: 1270 data points (7.25%) set to NA
NEE: 2601 data points (14.85%) set to NA
-------------------------------------------------------------------
Data filtering:
4944 data points (28.22%) excluded by growing season filter
3332 additional data points (19.02%) excluded by precipitation filter (4363
 data points = 24.9 % in total)
8276 data points (47.24%) excluded in total
9244 valid data points (52.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 66 data points (0.38%) set to NA
H: 1214 data points (6.93%) set to NA
LE: 1270 data points (7.25%) set to NA
NEE: 2601 data points (14.85%) set to NA
-------------------------------------------------------------------
Data filtering:
4944 data points (28.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4944 data points (28.22%) excluded in total
12576 valid data points (71.78%) remaining.

New sEddyProc class for site 'ES-Yst'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ES-Yst-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 484 data points (2.76%) set to NA
H: 1175 data points (6.71%) set to NA
LE: 1205 data points (6.88%) set to NA
NEE: 2381 data points (13.59%) set to NA
-------------------------------------------------------------------
Data filtering:
576 data points (3.29%) excluded by growing season filter
3233 additional data points (18.45%) excluded by precipitation filter (3233
 data points = 18.45 % in total)
3809 data points (21.74%) excluded in total
13711 valid data points (78.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 484 data points (2.76%) set to NA
H: 1175 data points (6.71%) set to NA
LE: 1205 data points (6.88%) set to NA
NEE: 2381 data points (13.59%) set to NA
-------------------------------------------------------------------
Data filtering:
576 data points (3.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
576 data points (3.29%) excluded in total
16944 valid data points (96.71%) remaining.

New sEddyProc class for site 'ES-Yst'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 113.66.

Regression of reference temperature R_ref for 4 periods.

Quality control:
TA: 367 data points (2.09%) set to NA
H: 1640 data points (9.34%) set to NA
LE: 1697 data points (9.66%) set to NA
NEE: 2498 data points (14.22%) set to NA
-------------------------------------------------------------------
Data filtering:
2640 data points (15.03%) excluded by growing season filter
3236 additional data points (18.42%) excluded by precipitation filter (3525
 data points = 20.06 % in total)
5876 data points (33.45%) excluded in total
11692 valid data points (66.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 367 data points (2.09%) set to NA
H: 1640 data points (9.34%) set to NA
LE: 1697 data points (9.66%) set to NA
NEE: 2498 data points (14.22%) set to NA
-------------------------------------------------------------------
Data filtering:
2640 data points (15.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2640 data points (15.03%) excluded in total
14928 valid data points (84.97%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -59 ...”
New sEddyProc class for site 'ES-Yst'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 218.43.

Regression of reference temperature R_ref for 3 periods.

[119/329] Processing: FI-Hyy

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: FI-Hyy | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 34 data points (0.19%) set to NA
H: 246 data points (1.4%) set to NA
LE: 1858 data points (10.61%) set to NA
NEE: 2657 data points (15.17%) set to NA
-------------------------------------------------------------------
Data filtering:
10752 data points (61.37%) excluded by growing season filter
3414 additional data points (19.49%) excluded by precipitation filter (9590
 data points = 54.74 % in total)
14166 data points (80.86%) excluded in total
3354 valid data points (19.14%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 34 data points (0.19%) set to NA
H: 246 data points (1.4%) set to NA
LE: 1858 data points (10.61%) set to NA
NEE: 2657 data points (15.17%) set to NA
-------------------------------------------------------------------
Data filtering:
10752 data points (61.37%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10752 data points (61.37%) excluded in total
6768 valid data points (38.63%) remaining.

New sEddyProc class for site 'FI-Hyy'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Hyy-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 821 data points (4.69%) set to NA
H: 1028 data points (5.87%) set to NA
LE: 1024 data points (5.84%) set to NA
NEE: 9079 data points (51.82%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 57”

-------------------------------------------------------------------
Data filtering:
9792 data points (55.89%) excluded by growing season filter
2754 additional data points (15.72%) excluded by precipitation filter (6840
 data points = 39.04 % in total)
12546 data points (71.61%) excluded in total
4974 valid data points (28.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 821 data points (4.69%) set to NA
H: 1028 data points (5.87%) set to NA
LE: 1024 data points (5.84%) set to NA
NEE: 9079 data points (51.82%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 57”

-------------------------------------------------------------------
Data filtering:
9792 data points (55.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9792 data points (55.89%) excluded in total
7728 valid data points (44.11%) remaining.

New sEddyProc class for site 'FI-Hyy'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 65.45.

Regression of reference temperature R_ref for 6 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 751 data points (4.29%) set to NA
LE: 489 data points (2.79%) set to NA
NEE: 1613 data points (9.21%) set to NA
-------------------------------------------------------------------
Data filtering:
9600 data points (54.79%) excluded by growing season filter
2943 additional data points (16.8%) excluded by precipitation filter (8434
 data points = 48.14 % in total)
12543 data points (71.59%) excluded in total
4977 valid data points (28.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 751 data points (4.29%) set to NA
LE: 489 data points (2.79%) set to NA
NEE: 1613 data points (9.21%) set to NA
-------------------------------------------------------------------
Data filtering:
9600 data points (54.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9600 data points (54.79%) excluded in total
7920 valid data points (45.21%) remaining.

New sEddyProc class for site 'FI-Hyy'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Hyy-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 58 data points (0.33%) set to NA
LE: 38 data points (0.22%) set to NA
NEE: 1094 data points (6.23%) set to NA
-------------------------------------------------------------------
Data filtering:
10416 data points (59.29%) excluded by growing season filter
2772 additional data points (15.78%) excluded by precipitation filter (8580
 data points = 48.84 % in total)
13188 data points (75.07%) excluded in total
4380 valid data points (24.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 58 data points (0.33%) set to NA
LE: 38 data points (0.22%) set to NA
NEE: 1094 data points (6.23%) set to NA
-------------------------------------------------------------------
Data filtering:
10416 data points (59.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10416 data points (59.29%) excluded in total
7152 valid data points (40.71%) remaining.

New sEddyProc class for site 'FI-Hyy'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Hyy-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 223 data points (1.27%) set to NA
H: 406 data points (2.32%) set to NA
LE: 2012 data points (11.48%) set to NA
NEE: 2784 data points (15.89%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.27%) excluded by growing season filter
3125 additional data points (17.84%) excluded by precipitation filter (8531
 data points = 48.69 % in total)
13685 data points (78.11%) excluded in total
3835 valid data points (21.89%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 223 data points (1.27%) set to NA
H: 406 data points (2.32%) set to NA
LE: 2012 data points (11.48%) set to NA
NEE: 2784 data points (15.89%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10560 data points (60.27%) excluded in total
6960 valid data points (39.73%) remaining.

New sEddyProc class for site 'FI-Hyy'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Hyy-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 933 data points (5.33%) set to NA
LE: 387 data points (2.21%) set to NA
NEE: 2057 data points (11.74%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.19%) excluded by growing season filter
3076 additional data points (17.56%) excluded by precipitation filter (8607
 data points = 49.13 % in total)
13972 data points (79.75%) excluded in total
3548 valid data points (20.25%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 933 data points (5.33%) set to NA
LE: 387 data points (2.21%) set to NA
NEE: 2057 data points (11.74%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10896 data points (62.19%) excluded in total
6624 valid data points (37.81%) remaining.

New sEddyProc class for site 'FI-Hyy'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Hyy-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2 data points (0.01%) set to NA
H: 483 data points (2.76%) set to NA
LE: 730 data points (4.17%) set to NA
NEE: 1948 data points (11.12%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.89%) excluded by growing season filter
3451 additional data points (19.7%) excluded by precipitation filter (8065
 data points = 46.03 % in total)
13243 data points (75.59%) excluded in total
4277 valid data points (24.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2 data points (0.01%) set to NA
H: 483 data points (2.76%) set to NA
LE: 730 data points (4.17%) set to NA
NEE: 1948 data points (11.12%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9792 data points (55.89%) excluded in total
7728 valid data points (44.11%) remaining.

New sEddyProc class for site 'FI-Hyy'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Hyy-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 690 data points (3.93%) set to NA
LE: 656 data points (3.73%) set to NA
NEE: 2098 data points (11.94%) set to NA
-------------------------------------------------------------------
Data filtering:
9984 data points (56.83%) excluded by growing season filter
3350 additional data points (19.07%) excluded by precipitation filter (8076
 data points = 45.97 % in total)
13334 data points (75.9%) excluded in total
4234 valid data points (24.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.

Warning message in nlrob(Gs ~ g0 + DwDc * (1 + g1/sqrt(VPD)) * GPP/Ca, data = df, :
“failed to converge in 20 steps”

Quality control:
TA: 0 data points (0%) set to NA
H: 690 data points (3.93%) set to NA
LE: 656 data points (3.73%) set to NA
NEE: 2098 data points (11.94%) set to NA
-------------------------------------------------------------------
Data filtering:
9984 data points (56.83%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9984 data points (56.83%) excluded in total
7584 valid data points (43.17%) remaining.

New sEddyProc class for site 'FI-Hyy'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Hyy-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[120/329] Processing: FI-Ken

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: FI-Ken | Years: 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 1863 data points (10.63%) set to NA
LE: 1962 data points (11.2%) set to NA
NEE: 4001 data points (22.84%) set to NA
-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
2882 additional data points (16.45%) excluded by precipitation filter (8609
 data points = 49.14 % in total)
14114 data points (80.56%) excluded in total
3406 valid data points (19.44%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1863 data points (10.63%) set to NA
LE: 1962 data points (11.2%) set to NA
NEE: 4001 data points (22.84%) set to NA
-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11232 data points (64.11%) excluded in total
6288 valid data points (35.89%) remaining.

New sEddyProc class for site 'FI-Ken'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Ken-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 589 data points (3.36%) set to NA
LE: 879 data points (5.02%) set to NA
NEE: 2445 data points (13.96%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.47%) excluded by growing season filter
3284 additional data points (18.74%) excluded by precipitation filter (8728
 data points = 49.82 % in total)
14228 data points (81.21%) excluded in total
3292 valid data points (18.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 589 data points (3.36%) set to NA
LE: 879 data points (5.02%) set to NA
NEE: 2445 data points (13.96%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10944 data points (62.47%) excluded in total
6576 valid data points (37.53%) remaining.

New sEddyProc class for site 'FI-Ken'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Ken-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 68 data points (0.39%) set to NA
LE: 55 data points (0.31%) set to NA
NEE: 468 data points (2.66%) set to NA
-------------------------------------------------------------------
Data filtering:
11568 data points (65.85%) excluded by growing season filter
2925 additional data points (16.65%) excluded by precipitation filter (9349
 data points = 53.22 % in total)
14493 data points (82.5%) excluded in total
3075 valid data points (17.5%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 68 data points (0.39%) set to NA
LE: 55 data points (0.31%) set to NA
NEE: 468 data points (2.66%) set to NA
-------------------------------------------------------------------
Data filtering:
11568 data points (65.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11568 data points (65.85%) excluded in total
6000 valid data points (34.15%) remaining.

New sEddyProc class for site 'FI-Ken'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Ken-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 343 data points (1.96%) set to NA
LE: 357 data points (2.04%) set to NA
NEE: 633 data points (3.61%) set to NA
-------------------------------------------------------------------
Data filtering:
11856 data points (67.67%) excluded by growing season filter
2315 additional data points (13.21%) excluded by precipitation filter (7734
 data points = 44.14 % in total)
14171 data points (80.88%) excluded in total
3349 valid data points (19.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 343 data points (1.96%) set to NA
LE: 357 data points (2.04%) set to NA
NEE: 633 data points (3.61%) set to NA
-------------------------------------------------------------------
Data filtering:
11856 data points (67.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11856 data points (67.67%) excluded in total
5664 valid data points (32.33%) remaining.

New sEddyProc class for site 'FI-Ken'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Ken-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 588 data points (3.36%) set to NA
LE: 662 data points (3.78%) set to NA
NEE: 1225 data points (6.99%) set to NA
-------------------------------------------------------------------
Data filtering:
11856 data points (67.67%) excluded by growing season filter
2785 additional data points (15.9%) excluded by precipitation filter (7974
 data points = 45.51 % in total)
14641 data points (83.57%) excluded in total
2879 valid data points (16.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 588 data points (3.36%) set to NA
LE: 662 data points (3.78%) set to NA
NEE: 1225 data points (6.99%) set to NA
-------------------------------------------------------------------
Data filtering:
11856 data points (67.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11856 data points (67.67%) excluded in total
5664 valid data points (32.33%) remaining.

New sEddyProc class for site 'FI-Ken'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Ken-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 58 data points (0.33%) set to NA
H: 4046 data points (23.09%) set to NA
LE: 4089 data points (23.34%) set to NA
NEE: 5661 data points (32.31%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
3317 additional data points (18.93%) excluded by precipitation filter (8228
 data points = 46.96 % in total)
13973 data points (79.75%) excluded in total
3547 valid data points (20.25%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 58 data points (0.33%) set to NA
H: 4046 data points (23.09%) set to NA
LE: 4089 data points (23.34%) set to NA
NEE: 5661 data points (32.31%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10656 data points (60.82%) excluded in total
6864 valid data points (39.18%) remaining.

New sEddyProc class for site 'FI-Ken'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Ken-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 65 data points (0.37%) set to NA
H: 249 data points (1.42%) set to NA
LE: 3300 data points (18.78%) set to NA
NEE: 4523 data points (25.75%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.66%) excluded by growing season filter
3201 additional data points (18.22%) excluded by precipitation filter (8452
 data points = 48.11 % in total)
14385 data points (81.88%) excluded in total
3183 valid data points (18.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 65 data points (0.37%) set to NA
H: 249 data points (1.42%) set to NA
LE: 3300 data points (18.78%) set to NA
NEE: 4523 data points (25.75%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.66%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11184 data points (63.66%) excluded in total
6384 valid data points (36.34%) remaining.

New sEddyProc class for site 'FI-Ken'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Ken-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[121/329] Processing: FI-Let

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: FI-Let | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 2116 data points (12.08%) set to NA
H: 2273 data points (12.97%) set to NA
LE: 2282 data points (13.03%) set to NA
NEE: 2839 data points (16.2%) set to NA
-------------------------------------------------------------------
Data filtering:
11904 data points (67.95%) excluded by growing season filter
3231 additional data points (18.44%) excluded by precipitation filter (8738
 data points = 49.87 % in total)
15135 data points (86.39%) excluded in total
2385 valid data points (13.61%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2116 data points (12.08%) set to NA
H: 2273 data points (12.97%) set to NA
LE: 2282 data points (13.03%) set to NA
NEE: 2839 data points (16.2%) set to NA
-------------------------------------------------------------------
Data filtering:
11904 data points (67.95%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11904 data points (67.95%) excluded in total
5616 valid data points (32.05%) remaining.

New sEddyProc class for site 'FI-Let'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 146.33.

Regression of reference temperature R_ref for 20 periods.

Quality control:
TA: 2805 data points (16.01%) set to NA
H: 2815 data points (16.07%) set to NA
LE: 2832 data points (16.16%) set to NA
NEE: 3615 data points (20.63%) set to NA
-------------------------------------------------------------------
Data filtering:
12480 data points (71.23%) excluded by growing season filter
2435 additional data points (13.9%) excluded by precipitation filter (5856
 data points = 33.42 % in total)
14915 data points (85.13%) excluded in total
2605 valid data points (14.87%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2805 data points (16.01%) set to NA
H: 2815 data points (16.07%) set to NA
LE: 2832 data points (16.16%) set to NA
NEE: 3615 data points (20.63%) set to NA
-------------------------------------------------------------------
Data filtering:
12480 data points (71.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12480 data points (71.23%) excluded in total
5040 valid data points (28.77%) remaining.

New sEddyProc class for site 'FI-Let'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 105.93.

Regression of reference temperature R_ref for 25 periods.

Quality control:
TA: 3661 data points (20.9%) set to NA
H: 3753 data points (21.42%) set to NA
LE: 3759 data points (21.46%) set to NA
NEE: 4275 data points (24.4%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 38”

-------------------------------------------------------------------
Data filtering:
10896 data points (62.19%) excluded by growing season filter
3015 additional data points (17.21%) excluded by precipitation filter (8019
 data points = 45.77 % in total)
13911 data points (79.4%) excluded in total
3609 valid data points (20.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3661 data points (20.9%) set to NA
H: 3753 data points (21.42%) set to NA
LE: 3759 data points (21.46%) set to NA
NEE: 4275 data points (24.4%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 38”

-------------------------------------------------------------------
Data filtering:
10896 data points (62.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10896 data points (62.19%) excluded in total
6624 valid data points (37.81%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
New sEddyProc class for site 'FI-Let'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 112.97.

Regression of reference temperature R_ref for 15 periods.

Quality control:
TA: 456 data points (2.6%) set to NA
H: 472 data points (2.69%) set to NA
LE: 476 data points (2.71%) set to NA
NEE: 1951 data points (11.11%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.39%) excluded by growing season filter
2766 additional data points (15.74%) excluded by precipitation filter (9235
 data points = 52.57 % in total)
13902 data points (79.13%) excluded in total
3666 valid data points (20.87%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 456 data points (2.6%) set to NA
H: 472 data points (2.69%) set to NA
LE: 476 data points (2.71%) set to NA
NEE: 1951 data points (11.11%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.39%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11136 data points (63.39%) excluded in total
6432 valid data points (36.61%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -78, -75, -73 ...”
New sEddyProc class for site 'FI-Let'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -78, -75, -73 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 146.93.

Regression of reference temperature R_ref for 4 periods.

Quality control:
TA: 1277 data points (7.29%) set to NA
H: 1310 data points (7.48%) set to NA
LE: 2415 data points (13.78%) set to NA
NEE: 4457 data points (25.44%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
2738 additional data points (15.63%) excluded by precipitation filter (8011
 data points = 45.72 % in total)
13394 data points (76.45%) excluded in total
4126 valid data points (23.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1277 data points (7.29%) set to NA
H: 1310 data points (7.48%) set to NA
LE: 2415 data points (13.78%) set to NA
NEE: 4457 data points (25.44%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10656 data points (60.82%) excluded in total
6864 valid data points (39.18%) remaining.

New sEddyProc class for site 'FI-Let'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 146.93.

Regression of reference temperature R_ref for 15 periods.

Quality control:
TA: 4216 data points (24.06%) set to NA
H: 4254 data points (24.28%) set to NA
LE: 5440 data points (31.05%) set to NA
NEE: 7560 data points (43.15%) set to NA
-------------------------------------------------------------------
Data filtering:
11280 data points (64.38%) excluded by growing season filter
2290 additional data points (13.07%) excluded by precipitation filter (7414
 data points = 42.32 % in total)
13570 data points (77.45%) excluded in total
3950 valid data points (22.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4216 data points (24.06%) set to NA
H: 4254 data points (24.28%) set to NA
LE: 5440 data points (31.05%) set to NA
NEE: 7560 data points (43.15%) set to NA
-------------------------------------------------------------------
Data filtering:
11280 data points (64.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11280 data points (64.38%) excluded in total
6240 valid data points (35.62%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -64 ...”
New sEddyProc class for site 'FI-Let'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -64 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 147.99.

Regression of reference temperature R_ref for 68 periods.

Quality control:
TA: 929 data points (5.3%) set to NA
H: 942 data points (5.38%) set to NA
LE: 949 data points (5.42%) set to NA
NEE: 2126 data points (12.13%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.16%) excluded by growing season filter
3403 additional data points (19.42%) excluded by precipitation filter (7920
 data points = 45.21 % in total)
13243 data points (75.59%) excluded in total
4277 valid data points (24.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 929 data points (5.3%) set to NA
H: 942 data points (5.38%) set to NA
LE: 949 data points (5.42%) set to NA
NEE: 2126 data points (12.13%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9840 data points (56.16%) excluded in total
7680 valid data points (43.84%) remaining.

New sEddyProc class for site 'FI-Let'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 60.

Regression of reference temperature R_ref for 21 periods.

Quality control:
TA: 6574 data points (37.42%) set to NA
H: 6578 data points (37.44%) set to NA
LE: 6577 data points (37.44%) set to NA
NEE: 7290 data points (41.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 53”

-------------------------------------------------------------------
Data filtering:
7968 data points (45.36%) excluded by growing season filter
4174 additional data points (23.76%) excluded by precipitation filter (7887
 data points = 44.89 % in total)
12142 data points (69.11%) excluded in total
5426 valid data points (30.89%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6574 data points (37.42%) set to NA
H: 6578 data points (37.44%) set to NA
LE: 6577 data points (37.44%) set to NA
NEE: 7290 data points (41.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 53”

-------------------------------------------------------------------
Data filtering:
7968 data points (45.36%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7968 data points (45.36%) excluded in total
9600 valid data points (54.64%) remaining.

New sEddyProc class for site 'FI-Let'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 37.47.

Regression of reference temperature R_ref for 31 periods.

[122/329] Processing: FI-Rk2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: FI-Rk2 | Years: 2020, 2021, 2022, 2023
Quality control:
TA: 511 data points (2.91%) set to NA
H: 469 data points (2.67%) set to NA
LE: 469 data points (2.67%) set to NA
NEE: 3862 data points (21.98%) set to NA
-------------------------------------------------------------------
Data filtering:
9984 data points (56.83%) excluded by growing season filter
3938 additional data points (22.42%) excluded by precipitation filter (9279
 data points = 52.82 % in total)
13922 data points (79.25%) excluded in total
3646 valid data points (20.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 511 data points (2.91%) set to NA
H: 469 data points (2.67%) set to NA
LE: 469 data points (2.67%) set to NA
NEE: 3862 data points (21.98%) set to NA
-------------------------------------------------------------------
Data filtering:
9984 data points (56.83%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9984 data points (56.83%) excluded in total
7584 valid data points (43.17%) remaining.

New sEddyProc class for site 'FI-Rk2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Rk2-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 331 data points (1.89%) set to NA
H: 174 data points (0.99%) set to NA
LE: 177 data points (1.01%) set to NA
NEE: 4071 data points (23.24%) set to NA
-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
3466 additional data points (19.78%) excluded by precipitation filter (8248
 data points = 47.08 % in total)
12586 data points (71.84%) excluded in total
4934 valid data points (28.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 331 data points (1.89%) set to NA
H: 174 data points (0.99%) set to NA
LE: 177 data points (1.01%) set to NA
NEE: 4071 data points (23.24%) set to NA
-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9120 data points (52.05%) excluded in total
8400 valid data points (47.95%) remaining.

New sEddyProc class for site 'FI-Rk2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Rk2-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 8 data points (0.05%) set to NA
NEE: 1615 data points (9.22%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.73%) excluded by growing season filter
2926 additional data points (16.7%) excluded by precipitation filter (8055
 data points = 45.98 % in total)
13390 data points (76.43%) excluded in total
4130 valid data points (23.57%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 8 data points (0.05%) set to NA
NEE: 1615 data points (9.22%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10464 data points (59.73%) excluded in total
7056 valid data points (40.27%) remaining.

New sEddyProc class for site 'FI-Rk2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Rk2-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 67 data points (0.38%) set to NA
H: 24 data points (0.14%) set to NA
LE: 76 data points (0.43%) set to NA
NEE: 3017 data points (17.22%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
3371 additional data points (19.24%) excluded by precipitation filter (8485
 data points = 48.43 % in total)
13595 data points (77.6%) excluded in total
3925 valid data points (22.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 67 data points (0.38%) set to NA
H: 24 data points (0.14%) set to NA
LE: 76 data points (0.43%) set to NA
NEE: 3017 data points (17.22%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10224 data points (58.36%) excluded in total
7296 valid data points (41.64%) remaining.

New sEddyProc class for site 'FI-Rk2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Rk2-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[123/329] Processing: FI-Sii

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: FI-Sii | Years: 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 96 data points (0.55%) set to NA
H: 5498 data points (31.38%) set to NA
LE: 5438 data points (31.04%) set to NA
NEE: 5979 data points (34.13%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 75”

-------------------------------------------------------------------
Data filtering:
10848 data points (61.92%) excluded by growing season filter
2031 additional data points (11.59%) excluded by precipitation filter (6477
 data points = 36.97 % in total)
12879 data points (73.51%) excluded in total
4641 valid data points (26.49%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 96 data points (0.55%) set to NA
H: 5498 data points (31.38%) set to NA
LE: 5438 data points (31.04%) set to NA
NEE: 5979 data points (34.13%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 75”

-------------------------------------------------------------------
Data filtering:
10848 data points (61.92%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10848 data points (61.92%) excluded in total
6672 valid data points (38.08%) remaining.

New sEddyProc class for site 'FI-Sii'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Sii-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 517 data points (2.95%) set to NA
H: 266 data points (1.52%) set to NA
LE: 178 data points (1.02%) set to NA
NEE: 732 data points (4.18%) set to NA
-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
2761 additional data points (15.76%) excluded by precipitation filter (8006
 data points = 45.7 % in total)
13849 data points (79.05%) excluded in total
3671 valid data points (20.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 517 data points (2.95%) set to NA
H: 266 data points (1.52%) set to NA
LE: 178 data points (1.02%) set to NA
NEE: 732 data points (4.18%) set to NA
-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11088 data points (63.29%) excluded in total
6432 valid data points (36.71%) remaining.

New sEddyProc class for site 'FI-Sii'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Sii-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 67 data points (0.38%) set to NA
H: 173 data points (0.98%) set to NA
LE: 112 data points (0.64%) set to NA
NEE: 490 data points (2.79%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.02%) excluded by growing season filter
2424 additional data points (13.8%) excluded by precipitation filter (7964
 data points = 45.33 % in total)
13320 data points (75.82%) excluded in total
4248 valid data points (24.18%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 67 data points (0.38%) set to NA
H: 173 data points (0.98%) set to NA
LE: 112 data points (0.64%) set to NA
NEE: 490 data points (2.79%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.02%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10896 data points (62.02%) excluded in total
6672 valid data points (37.98%) remaining.

New sEddyProc class for site 'FI-Sii'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Sii-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2 data points (0.01%) set to NA
H: 3891 data points (22.21%) set to NA
LE: 3883 data points (22.16%) set to NA
NEE: 4112 data points (23.47%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
2944 additional data points (16.8%) excluded by precipitation filter (8605
 data points = 49.12 % in total)
13744 data points (78.45%) excluded in total
3776 valid data points (21.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2 data points (0.01%) set to NA
H: 3891 data points (22.21%) set to NA
LE: 3883 data points (22.16%) set to NA
NEE: 4112 data points (23.47%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10800 data points (61.64%) excluded in total
6720 valid data points (38.36%) remaining.

New sEddyProc class for site 'FI-Sii'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Sii-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 349 data points (1.99%) set to NA
H: 1603 data points (9.15%) set to NA
LE: 1582 data points (9.03%) set to NA
NEE: 1999 data points (11.41%) set to NA
-------------------------------------------------------------------
Data filtering:
11616 data points (66.3%) excluded by growing season filter
2506 additional data points (14.3%) excluded by precipitation filter (8239
 data points = 47.03 % in total)
14122 data points (80.61%) excluded in total
3398 valid data points (19.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 349 data points (1.99%) set to NA
H: 1603 data points (9.15%) set to NA
LE: 1582 data points (9.03%) set to NA
NEE: 1999 data points (11.41%) set to NA
-------------------------------------------------------------------
Data filtering:
11616 data points (66.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11616 data points (66.3%) excluded in total
5904 valid data points (33.7%) remaining.

New sEddyProc class for site 'FI-Sii'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Sii-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 462 data points (2.64%) set to NA
H: 262 data points (1.5%) set to NA
LE: 270 data points (1.54%) set to NA
NEE: 608 data points (3.47%) set to NA
-------------------------------------------------------------------
Data filtering:
10704 data points (61.1%) excluded by growing season filter
2850 additional data points (16.27%) excluded by precipitation filter (7856
 data points = 44.84 % in total)
13554 data points (77.36%) excluded in total
3966 valid data points (22.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 462 data points (2.64%) set to NA
H: 262 data points (1.5%) set to NA
LE: 270 data points (1.54%) set to NA
NEE: 608 data points (3.47%) set to NA
-------------------------------------------------------------------
Data filtering:
10704 data points (61.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10704 data points (61.1%) excluded in total
6816 valid data points (38.9%) remaining.

New sEddyProc class for site 'FI-Sii'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Sii-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 85 data points (0.48%) set to NA
H: 200 data points (1.14%) set to NA
LE: 154 data points (0.88%) set to NA
NEE: 535 data points (3.05%) set to NA
-------------------------------------------------------------------
Data filtering:
10848 data points (61.75%) excluded by growing season filter
3091 additional data points (17.59%) excluded by precipitation filter (7928
 data points = 45.13 % in total)
13939 data points (79.34%) excluded in total
3629 valid data points (20.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 85 data points (0.48%) set to NA
H: 200 data points (1.14%) set to NA
LE: 154 data points (0.88%) set to NA
NEE: 535 data points (3.05%) set to NA
-------------------------------------------------------------------
Data filtering:
10848 data points (61.75%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10848 data points (61.75%) excluded in total
6720 valid data points (38.25%) remaining.

New sEddyProc class for site 'FI-Sii'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Sii-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[124/329] Processing: FI-Sod

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: FI-Sod | Years: 2023, 2024
Quality control:
TA: 9256 data points (52.83%) set to NA
H: 6424 data points (36.67%) set to NA
LE: 6322 data points (36.08%) set to NA
NEE: 7471 data points (42.64%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 100”

-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
2748 additional data points (15.68%) excluded by precipitation filter (6924
 data points = 39.52 % in total)
13884 data points (79.25%) excluded in total
3636 valid data points (20.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9256 data points (52.83%) set to NA
H: 6424 data points (36.67%) set to NA
LE: 6322 data points (36.08%) set to NA
NEE: 7471 data points (42.64%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 100”

-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11136 data points (63.56%) excluded in total
6384 valid data points (36.44%) remaining.

New sEddyProc class for site 'FI-Sod'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 56.77.

Regression of reference temperature R_ref for 27 periods.

Quality control:
TA: 196 data points (1.12%) set to NA
H: 555 data points (3.16%) set to NA
LE: 557 data points (3.17%) set to NA
NEE: 1303 data points (7.42%) set to NA
-------------------------------------------------------------------
Data filtering:
11568 data points (65.85%) excluded by growing season filter
3003 additional data points (17.09%) excluded by precipitation filter (7822
 data points = 44.52 % in total)
14571 data points (82.94%) excluded in total
2997 valid data points (17.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 196 data points (1.12%) set to NA
H: 555 data points (3.16%) set to NA
LE: 557 data points (3.17%) set to NA
NEE: 1303 data points (7.42%) set to NA
-------------------------------------------------------------------
Data filtering:
11568 data points (65.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11568 data points (65.85%) excluded in total
6000 valid data points (34.15%) remaining.

New sEddyProc class for site 'FI-Sod'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Sod-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[125/329] Processing: FI-Var

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: FI-Var | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 0 data points (0%) set to NA
LE: 0 data points (0%) set to NA
NEE: 24 data points (0.14%) set to NA
-------------------------------------------------------------------
Data filtering:
12480 data points (71.23%) excluded by growing season filter
2940 additional data points (16.78%) excluded by precipitation filter (8591
 data points = 49.04 % in total)
15420 data points (88.01%) excluded in total
2100 valid data points (11.99%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 0 data points (0%) set to NA
LE: 0 data points (0%) set to NA
NEE: 24 data points (0.14%) set to NA
-------------------------------------------------------------------
Data filtering:
12480 data points (71.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12480 data points (71.23%) excluded in total
5040 valid data points (28.77%) remaining.

New sEddyProc class for site 'FI-Var'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Var-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 20 data points (0.11%) set to NA
H: 4 data points (0.02%) set to NA
LE: 4 data points (0.02%) set to NA
NEE: 205 data points (1.17%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
3167 additional data points (18.08%) excluded by precipitation filter (7867
 data points = 44.9 % in total)
14303 data points (81.64%) excluded in total
3217 valid data points (18.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 20 data points (0.11%) set to NA
H: 4 data points (0.02%) set to NA
LE: 4 data points (0.02%) set to NA
NEE: 205 data points (1.17%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11136 data points (63.56%) excluded in total
6384 valid data points (36.44%) remaining.

New sEddyProc class for site 'FI-Var'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Var-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 11 data points (0.06%) set to NA
H: 3 data points (0.02%) set to NA
LE: 5 data points (0.03%) set to NA
NEE: 1303 data points (7.44%) set to NA
-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
3129 additional data points (17.86%) excluded by precipitation filter (8845
 data points = 50.49 % in total)
14361 data points (81.97%) excluded in total
3159 valid data points (18.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11 data points (0.06%) set to NA
H: 3 data points (0.02%) set to NA
LE: 5 data points (0.03%) set to NA
NEE: 1303 data points (7.44%) set to NA
-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11232 data points (64.11%) excluded in total
6288 valid data points (35.89%) remaining.

New sEddyProc class for site 'FI-Var'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Var-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 35 data points (0.2%) set to NA
H: 5 data points (0.03%) set to NA
LE: 0 data points (0%) set to NA
NEE: 165 data points (0.94%) set to NA
-------------------------------------------------------------------
Data filtering:
11520 data points (65.57%) excluded by growing season filter
3033 additional data points (17.26%) excluded by precipitation filter (8737
 data points = 49.73 % in total)
14553 data points (82.84%) excluded in total
3015 valid data points (17.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 35 data points (0.2%) set to NA
H: 5 data points (0.03%) set to NA
LE: 0 data points (0%) set to NA
NEE: 165 data points (0.94%) set to NA
-------------------------------------------------------------------
Data filtering:
11520 data points (65.57%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11520 data points (65.57%) excluded in total
6048 valid data points (34.43%) remaining.

New sEddyProc class for site 'FI-Var'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Var-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 139 data points (0.79%) set to NA
H: 3 data points (0.02%) set to NA
LE: 2 data points (0.01%) set to NA
NEE: 211 data points (1.2%) set to NA
-------------------------------------------------------------------
Data filtering:
12144 data points (69.32%) excluded by growing season filter
2765 additional data points (15.78%) excluded by precipitation filter (9117
 data points = 52.04 % in total)
14909 data points (85.1%) excluded in total
2611 valid data points (14.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 139 data points (0.79%) set to NA
H: 3 data points (0.02%) set to NA
LE: 2 data points (0.01%) set to NA
NEE: 211 data points (1.2%) set to NA
-------------------------------------------------------------------
Data filtering:
12144 data points (69.32%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12144 data points (69.32%) excluded in total
5376 valid data points (30.68%) remaining.

New sEddyProc class for site 'FI-Var'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Var-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6 data points (0.03%) set to NA
H: 15 data points (0.09%) set to NA
LE: 10 data points (0.06%) set to NA
NEE: 99 data points (0.57%) set to NA
-------------------------------------------------------------------
Data filtering:
12672 data points (72.33%) excluded by growing season filter
2790 additional data points (15.92%) excluded by precipitation filter (8926
 data points = 50.95 % in total)
15462 data points (88.25%) excluded in total
2058 valid data points (11.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6 data points (0.03%) set to NA
H: 15 data points (0.09%) set to NA
LE: 10 data points (0.06%) set to NA
NEE: 99 data points (0.57%) set to NA
-------------------------------------------------------------------
Data filtering:
12672 data points (72.33%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12672 data points (72.33%) excluded in total
4848 valid data points (27.67%) remaining.

New sEddyProc class for site 'FI-Var'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Var-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 11 data points (0.06%) set to NA
H: 7 data points (0.04%) set to NA
LE: 3342 data points (19.08%) set to NA
NEE: 3563 data points (20.34%) set to NA
-------------------------------------------------------------------
Data filtering:
10992 data points (62.74%) excluded by growing season filter
2934 additional data points (16.75%) excluded by precipitation filter (7984
 data points = 45.57 % in total)
13926 data points (79.49%) excluded in total
3594 valid data points (20.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11 data points (0.06%) set to NA
H: 7 data points (0.04%) set to NA
LE: 3342 data points (19.08%) set to NA
NEE: 3563 data points (20.34%) set to NA
-------------------------------------------------------------------
Data filtering:
10992 data points (62.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10992 data points (62.74%) excluded in total
6528 valid data points (37.26%) remaining.

New sEddyProc class for site 'FI-Var'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Var-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 9 data points (0.05%) set to NA
H: 39 data points (0.22%) set to NA
LE: 1875 data points (10.67%) set to NA
NEE: 2065 data points (11.75%) set to NA
-------------------------------------------------------------------
Data filtering:
11712 data points (66.67%) excluded by growing season filter
2528 additional data points (14.39%) excluded by precipitation filter (8017
 data points = 45.63 % in total)
14240 data points (81.06%) excluded in total
3328 valid data points (18.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9 data points (0.05%) set to NA
H: 39 data points (0.22%) set to NA
LE: 1875 data points (10.67%) set to NA
NEE: 2065 data points (11.75%) set to NA
-------------------------------------------------------------------
Data filtering:
11712 data points (66.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11712 data points (66.67%) excluded in total
5856 valid data points (33.33%) remaining.

New sEddyProc class for site 'FI-Var'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FI-Var-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[126/329] Processing: FR-Bil

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: FR-Bil | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 162 data points (0.92%) set to NA
H: 174 data points (0.99%) set to NA
LE: 247 data points (1.41%) set to NA
NEE: 799 data points (4.56%) set to NA
-------------------------------------------------------------------
Data filtering:
4752 data points (27.12%) excluded by growing season filter
5079 additional data points (28.99%) excluded by precipitation filter (7480
 data points = 42.69 % in total)
9831 data points (56.11%) excluded in total
7689 valid data points (43.89%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 162 data points (0.92%) set to NA
H: 174 data points (0.99%) set to NA
LE: 247 data points (1.41%) set to NA
NEE: 799 data points (4.56%) set to NA
-------------------------------------------------------------------
Data filtering:
4752 data points (27.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4752 data points (27.12%) excluded in total
12768 valid data points (72.88%) remaining.

New sEddyProc class for site 'FR-Bil'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Bil-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 819 data points (4.67%) set to NA
H: 824 data points (4.7%) set to NA
LE: 856 data points (4.89%) set to NA
NEE: 1191 data points (6.8%) set to NA
-------------------------------------------------------------------
Data filtering:
7824 data points (44.66%) excluded by growing season filter
4717 additional data points (26.92%) excluded by precipitation filter (10068
 data points = 57.47 % in total)
12541 data points (71.58%) excluded in total
4979 valid data points (28.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 819 data points (4.67%) set to NA
H: 824 data points (4.7%) set to NA
LE: 856 data points (4.89%) set to NA
NEE: 1191 data points (6.8%) set to NA
-------------------------------------------------------------------
Data filtering:
7824 data points (44.66%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7824 data points (44.66%) excluded in total
9696 valid data points (55.34%) remaining.

New sEddyProc class for site 'FR-Bil'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Bil-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 204 data points (1.16%) set to NA
LE: 205 data points (1.17%) set to NA
NEE: 537 data points (3.07%) set to NA
-------------------------------------------------------------------
Data filtering:
4224 data points (24.11%) excluded by growing season filter
5469 additional data points (31.22%) excluded by precipitation filter (8291
 data points = 47.32 % in total)
9693 data points (55.33%) excluded in total
7827 valid data points (44.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 204 data points (1.16%) set to NA
LE: 205 data points (1.17%) set to NA
NEE: 537 data points (3.07%) set to NA
-------------------------------------------------------------------
Data filtering:
4224 data points (24.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4224 data points (24.11%) excluded in total
13296 valid data points (75.89%) remaining.

New sEddyProc class for site 'FR-Bil'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Bil-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 446 data points (2.54%) set to NA
H: 627 data points (3.57%) set to NA
LE: 629 data points (3.58%) set to NA
NEE: 855 data points (4.87%) set to NA
-------------------------------------------------------------------
Data filtering:
3120 data points (17.76%) excluded by growing season filter
5895 additional data points (33.56%) excluded by precipitation filter (7668
 data points = 43.65 % in total)
9015 data points (51.31%) excluded in total
8553 valid data points (48.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 446 data points (2.54%) set to NA
H: 627 data points (3.57%) set to NA
LE: 629 data points (3.58%) set to NA
NEE: 855 data points (4.87%) set to NA
-------------------------------------------------------------------
Data filtering:
3120 data points (17.76%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3120 data points (17.76%) excluded in total
14448 valid data points (82.24%) remaining.

New sEddyProc class for site 'FR-Bil'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Bil-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 601 data points (3.43%) set to NA
H: 680 data points (3.88%) set to NA
LE: 669 data points (3.82%) set to NA
NEE: 1018 data points (5.81%) set to NA
-------------------------------------------------------------------
Data filtering:
5904 data points (33.7%) excluded by growing season filter
3946 additional data points (22.52%) excluded by precipitation filter (7161
 data points = 40.87 % in total)
9850 data points (56.22%) excluded in total
7670 valid data points (43.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 601 data points (3.43%) set to NA
H: 680 data points (3.88%) set to NA
LE: 669 data points (3.82%) set to NA
NEE: 1018 data points (5.81%) set to NA
-------------------------------------------------------------------
Data filtering:
5904 data points (33.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5904 data points (33.7%) excluded in total
11616 valid data points (66.3%) remaining.

New sEddyProc class for site 'FR-Bil'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Bil-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 223 data points (1.27%) set to NA
H: 655 data points (3.74%) set to NA
LE: 607 data points (3.46%) set to NA
NEE: 965 data points (5.51%) set to NA
-------------------------------------------------------------------
Data filtering:
7200 data points (41.1%) excluded by growing season filter
3912 additional data points (22.33%) excluded by precipitation filter (6348
 data points = 36.23 % in total)
11112 data points (63.42%) excluded in total
6408 valid data points (36.58%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 223 data points (1.27%) set to NA
H: 655 data points (3.74%) set to NA
LE: 607 data points (3.46%) set to NA
NEE: 965 data points (5.51%) set to NA
-------------------------------------------------------------------
Data filtering:
7200 data points (41.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7200 data points (41.1%) excluded in total
10320 valid data points (58.9%) remaining.

New sEddyProc class for site 'FR-Bil'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Bil-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 597 data points (3.41%) set to NA
H: 496 data points (2.83%) set to NA
LE: 344 data points (1.96%) set to NA
NEE: 817 data points (4.66%) set to NA
-------------------------------------------------------------------
Data filtering:
4608 data points (26.3%) excluded by growing season filter
6023 additional data points (34.38%) excluded by precipitation filter (8177
 data points = 46.67 % in total)
10631 data points (60.68%) excluded in total
6889 valid data points (39.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 597 data points (3.41%) set to NA
H: 496 data points (2.83%) set to NA
LE: 344 data points (1.96%) set to NA
NEE: 817 data points (4.66%) set to NA
-------------------------------------------------------------------
Data filtering:
4608 data points (26.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4608 data points (26.3%) excluded in total
12912 valid data points (73.7%) remaining.

New sEddyProc class for site 'FR-Bil'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 281.03.

Regression of reference temperature R_ref for 13 periods.

Quality control:
TA: 276 data points (1.57%) set to NA
H: 211 data points (1.2%) set to NA
LE: 147 data points (0.84%) set to NA
NEE: 444 data points (2.53%) set to NA
-------------------------------------------------------------------
Data filtering:
4704 data points (26.78%) excluded by growing season filter
5863 additional data points (33.37%) excluded by precipitation filter (8350
 data points = 47.53 % in total)
10567 data points (60.15%) excluded in total
7001 valid data points (39.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 276 data points (1.57%) set to NA
H: 211 data points (1.2%) set to NA
LE: 147 data points (0.84%) set to NA
NEE: 444 data points (2.53%) set to NA
-------------------------------------------------------------------
Data filtering:
4704 data points (26.78%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4704 data points (26.78%) excluded in total
12864 valid data points (73.22%) remaining.

New sEddyProc class for site 'FR-Bil'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Bil-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[127/329] Processing: FR-FBn

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: FR-FBn | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 89 data points (0.51%) set to NA
H: 232 data points (1.32%) set to NA
LE: 4515 data points (25.77%) set to NA
NEE: 5251 data points (29.97%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 31”

-------------------------------------------------------------------
Data filtering:
6480 data points (36.99%) excluded by growing season filter
1595 additional data points (9.1%) excluded by precipitation filter (3072
 data points = 17.53 % in total)
8075 data points (46.09%) excluded in total
9445 valid data points (53.91%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 89 data points (0.51%) set to NA
H: 232 data points (1.32%) set to NA
LE: 4515 data points (25.77%) set to NA
NEE: 5251 data points (29.97%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 31”

-------------------------------------------------------------------
Data filtering:
6480 data points (36.99%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6480 data points (36.99%) excluded in total
11040 valid data points (63.01%) remaining.

New sEddyProc class for site 'FR-FBn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-FBn-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 15 data points (0.09%) set to NA
H: 15 data points (0.09%) set to NA
LE: 21 data points (0.12%) set to NA
NEE: 1327 data points (7.57%) set to NA
-------------------------------------------------------------------
Data filtering:
2640 data points (15.07%) excluded by growing season filter
4445 additional data points (25.37%) excluded by precipitation filter (5670
 data points = 32.36 % in total)
7085 data points (40.44%) excluded in total
10435 valid data points (59.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 15 data points (0.09%) set to NA
H: 15 data points (0.09%) set to NA
LE: 21 data points (0.12%) set to NA
NEE: 1327 data points (7.57%) set to NA
-------------------------------------------------------------------
Data filtering:
2640 data points (15.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2640 data points (15.07%) excluded in total
14880 valid data points (84.93%) remaining.

New sEddyProc class for site 'FR-FBn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-FBn-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 66 data points (0.38%) set to NA
NEE: 898 data points (5.13%) set to NA
-------------------------------------------------------------------
Data filtering:
1584 data points (9.04%) excluded by growing season filter
3572 additional data points (20.39%) excluded by precipitation filter (3724
 data points = 21.26 % in total)
5156 data points (29.43%) excluded in total
12364 valid data points (70.57%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 66 data points (0.38%) set to NA
NEE: 898 data points (5.13%) set to NA
-------------------------------------------------------------------
Data filtering:
1584 data points (9.04%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1584 data points (9.04%) excluded in total
15936 valid data points (90.96%) remaining.

New sEddyProc class for site 'FR-FBn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-FBn-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 108 data points (0.61%) set to NA
H: 93 data points (0.53%) set to NA
LE: 123 data points (0.7%) set to NA
NEE: 959 data points (5.46%) set to NA
-------------------------------------------------------------------
Data filtering:
4944 data points (28.14%) excluded by growing season filter
2521 additional data points (14.35%) excluded by precipitation filter (3777
 data points = 21.5 % in total)
7465 data points (42.49%) excluded in total
10103 valid data points (57.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 108 data points (0.61%) set to NA
H: 93 data points (0.53%) set to NA
LE: 123 data points (0.7%) set to NA
NEE: 959 data points (5.46%) set to NA
-------------------------------------------------------------------
Data filtering:
4944 data points (28.14%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4944 data points (28.14%) excluded in total
12624 valid data points (71.86%) remaining.

New sEddyProc class for site 'FR-FBn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-FBn-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 9 data points (0.05%) set to NA
H: 4 data points (0.02%) set to NA
LE: 14 data points (0.08%) set to NA
NEE: 921 data points (5.26%) set to NA
-------------------------------------------------------------------
Data filtering:
3696 data points (21.1%) excluded by growing season filter
3561 additional data points (20.33%) excluded by precipitation filter (4408
 data points = 25.16 % in total)
7257 data points (41.42%) excluded in total
10263 valid data points (58.58%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9 data points (0.05%) set to NA
H: 4 data points (0.02%) set to NA
LE: 14 data points (0.08%) set to NA
NEE: 921 data points (5.26%) set to NA
-------------------------------------------------------------------
Data filtering:
3696 data points (21.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3696 data points (21.1%) excluded in total
13824 valid data points (78.9%) remaining.

New sEddyProc class for site 'FR-FBn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-FBn-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 3 data points (0.02%) set to NA
LE: 12 data points (0.07%) set to NA
NEE: 1832 data points (10.46%) set to NA
-------------------------------------------------------------------
Data filtering:
1008 data points (5.75%) excluded by growing season filter
2871 additional data points (16.39%) excluded by precipitation filter (2942
 data points = 16.79 % in total)
3879 data points (22.14%) excluded in total
13641 valid data points (77.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 3 data points (0.02%) set to NA
LE: 12 data points (0.07%) set to NA
NEE: 1832 data points (10.46%) set to NA
-------------------------------------------------------------------
Data filtering:
1008 data points (5.75%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1008 data points (5.75%) excluded in total
16512 valid data points (94.25%) remaining.

New sEddyProc class for site 'FR-FBn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-FBn-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 38 data points (0.22%) set to NA
NEE: 1606 data points (9.17%) set to NA
-------------------------------------------------------------------
Data filtering:
1632 data points (9.32%) excluded by growing season filter
3660 additional data points (20.89%) excluded by precipitation filter (3805
 data points = 21.72 % in total)
5292 data points (30.21%) excluded in total
12228 valid data points (69.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 38 data points (0.22%) set to NA
NEE: 1606 data points (9.17%) set to NA
-------------------------------------------------------------------
Data filtering:
1632 data points (9.32%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1632 data points (9.32%) excluded in total
15888 valid data points (90.68%) remaining.

New sEddyProc class for site 'FR-FBn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-FBn-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2155 data points (12.27%) set to NA
H: 3 data points (0.02%) set to NA
LE: 16 data points (0.09%) set to NA
NEE: 756 data points (4.3%) set to NA
-------------------------------------------------------------------
Data filtering:
1248 data points (7.1%) excluded by growing season filter
4137 additional data points (23.55%) excluded by precipitation filter (4188
 data points = 23.84 % in total)
5385 data points (30.65%) excluded in total
12183 valid data points (69.35%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2155 data points (12.27%) set to NA
H: 3 data points (0.02%) set to NA
LE: 16 data points (0.09%) set to NA
NEE: 756 data points (4.3%) set to NA
-------------------------------------------------------------------
Data filtering:
1248 data points (7.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1248 data points (7.1%) excluded in total
16320 valid data points (92.9%) remaining.

New sEddyProc class for site 'FR-FBn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-FBn-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[128/329] Processing: FR-Fon

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: FR-Fon | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 14406 data points (82.23%) set to NA
H: 14406 data points (82.23%) set to NA
LE: 14398 data points (82.18%) set to NA
NEE: 14402 data points (82.2%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8523 additional data points (48.65%) excluded by precipitation filter (8523
 data points = 48.65 % in total)
8523 data points (48.65%) excluded in total
8997 valid data points (51.35%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 14406 data points (82.23%) set to NA
H: 14406 data points (82.23%) set to NA
LE: 14398 data points (82.18%) set to NA
NEE: 14402 data points (82.2%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'FR-Fon'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Fon-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1164 data points (6.63%) set to NA
H: 338 data points (1.92%) set to NA
LE: 255 data points (1.45%) set to NA
NEE: 684 data points (3.89%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.45%) excluded by growing season filter
2981 additional data points (16.97%) excluded by precipitation filter (7606
 data points = 43.29 % in total)
11669 data points (66.42%) excluded in total
5899 valid data points (33.58%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1164 data points (6.63%) set to NA
H: 338 data points (1.92%) set to NA
LE: 255 data points (1.45%) set to NA
NEE: 684 data points (3.89%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.45%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8688 data points (49.45%) excluded in total
8880 valid data points (50.55%) remaining.

New sEddyProc class for site 'FR-Fon'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 194.54.

Regression of reference temperature R_ref for 16 periods.

Quality control:
TA: 2259 data points (12.89%) set to NA
H: 999 data points (5.7%) set to NA
LE: 1936 data points (11.05%) set to NA
NEE: 2854 data points (16.29%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.15%) excluded by growing season filter
3844 additional data points (21.94%) excluded by precipitation filter (8251
 data points = 47.09 % in total)
13156 data points (75.09%) excluded in total
4364 valid data points (24.91%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2259 data points (12.89%) set to NA
H: 999 data points (5.7%) set to NA
LE: 1936 data points (11.05%) set to NA
NEE: 2854 data points (16.29%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9312 data points (53.15%) excluded in total
8208 valid data points (46.85%) remaining.

New sEddyProc class for site 'FR-Fon'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 180.89.

Regression of reference temperature R_ref for 27 periods.

Quality control:
TA: 1622 data points (9.26%) set to NA
H: 2114 data points (12.07%) set to NA
LE: 1754 data points (10.01%) set to NA
NEE: 2300 data points (13.13%) set to NA
-------------------------------------------------------------------
Data filtering:
9504 data points (54.25%) excluded by growing season filter
2524 additional data points (14.41%) excluded by precipitation filter (7291
 data points = 41.62 % in total)
12028 data points (68.65%) excluded in total
5492 valid data points (31.35%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1622 data points (9.26%) set to NA
H: 2114 data points (12.07%) set to NA
LE: 1754 data points (10.01%) set to NA
NEE: 2300 data points (13.13%) set to NA
-------------------------------------------------------------------
Data filtering:
9504 data points (54.25%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9504 data points (54.25%) excluded in total
8016 valid data points (45.75%) remaining.

New sEddyProc class for site 'FR-Fon'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 225.95.

Regression of reference temperature R_ref for 15 periods.

Quality control:
TA: 11 data points (0.06%) set to NA
H: 405 data points (2.31%) set to NA
LE: 125 data points (0.71%) set to NA
NEE: 250 data points (1.43%) set to NA
-------------------------------------------------------------------
Data filtering:
9024 data points (51.51%) excluded by growing season filter
3016 additional data points (17.21%) excluded by precipitation filter (8244
 data points = 47.05 % in total)
12040 data points (68.72%) excluded in total
5480 valid data points (31.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11 data points (0.06%) set to NA
H: 405 data points (2.31%) set to NA
LE: 125 data points (0.71%) set to NA
NEE: 250 data points (1.43%) set to NA
-------------------------------------------------------------------
Data filtering:
9024 data points (51.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9024 data points (51.51%) excluded in total
8496 valid data points (48.49%) remaining.

New sEddyProc class for site 'FR-Fon'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Fon-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 835 data points (4.75%) set to NA
H: 1406 data points (8%) set to NA
LE: 1444 data points (8.22%) set to NA
NEE: 1711 data points (9.74%) set to NA
-------------------------------------------------------------------
Data filtering:
8928 data points (50.82%) excluded by growing season filter
4844 additional data points (27.57%) excluded by precipitation filter (9932
 data points = 56.53 % in total)
13772 data points (78.39%) excluded in total
3796 valid data points (21.61%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 835 data points (4.75%) set to NA
H: 1406 data points (8%) set to NA
LE: 1444 data points (8.22%) set to NA
NEE: 1711 data points (9.74%) set to NA
-------------------------------------------------------------------
Data filtering:
8928 data points (50.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8928 data points (50.82%) excluded in total
8640 valid data points (49.18%) remaining.

New sEddyProc class for site 'FR-Fon'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Fon-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[129/329] Processing: FR-Hes

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: FR-Hes | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 2 data points (0.01%) set to NA
H: 245 data points (1.4%) set to NA
LE: 345 data points (1.97%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8047 additional data points (45.93%) excluded by precipitation filter (8047
 data points = 45.93 % in total)
8047 data points (45.93%) excluded in total
9473 valid data points (54.07%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2 data points (0.01%) set to NA
H: 245 data points (1.4%) set to NA
LE: 345 data points (1.97%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'FR-Hes'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Hes-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 51 data points (0.29%) set to NA
LE: 63 data points (0.36%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7282 additional data points (41.56%) excluded by precipitation filter (7282
 data points = 41.56 % in total)
7282 data points (41.56%) excluded in total
10238 valid data points (58.44%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 51 data points (0.29%) set to NA
LE: 63 data points (0.36%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'FR-Hes'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Hes-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 88 data points (0.5%) set to NA
LE: 96 data points (0.55%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8382 additional data points (47.84%) excluded by precipitation filter (8382
 data points = 47.84 % in total)
8382 data points (47.84%) excluded in total
9138 valid data points (52.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 88 data points (0.5%) set to NA
LE: 96 data points (0.55%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'FR-Hes'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Hes-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1 data points (0.01%) set to NA
H: 1138 data points (6.48%) set to NA
LE: 1135 data points (6.46%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7652 additional data points (43.56%) excluded by precipitation filter (7652
 data points = 43.56 % in total)
7652 data points (43.56%) excluded in total
9916 valid data points (56.44%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1 data points (0.01%) set to NA
H: 1138 data points (6.48%) set to NA
LE: 1135 data points (6.46%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'FR-Hes'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Hes-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 17519 data points (99.99%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10654 additional data points (60.81%) excluded by precipitation filter (10654
 data points = 60.81 % in total)
10654 data points (60.81%) excluded in total
6866 valid data points (39.19%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for FR-Hes-2021”

Quality control:
TA: 13708 data points (78.24%) set to NA
H: 8345 data points (47.63%) set to NA
LE: 8344 data points (47.63%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7767 additional data points (44.33%) excluded by precipitation filter (7767
 data points = 44.33 % in total)
7767 data points (44.33%) excluded in total
9753 valid data points (55.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 13708 data points (78.24%) set to NA
H: 8345 data points (47.63%) set to NA
LE: 8344 data points (47.63%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'FR-Hes'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Hes-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 707 data points (4.04%) set to NA
LE: 678 data points (3.87%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8647 additional data points (49.36%) excluded by precipitation filter (8647
 data points = 49.36 % in total)
8647 data points (49.36%) excluded in total
8873 valid data points (50.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 707 data points (4.04%) set to NA
LE: 678 data points (3.87%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'FR-Hes'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Hes-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2066 data points (11.76%) set to NA
H: 143 data points (0.81%) set to NA
LE: 129 data points (0.73%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10058 additional data points (57.25%) excluded by precipitation filter (10058
 data points = 57.25 % in total)
10058 data points (57.25%) excluded in total
7510 valid data points (42.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2066 data points (11.76%) set to NA
H: 143 data points (0.81%) set to NA
LE: 129 data points (0.73%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'FR-Hes'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Hes-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[130/329] Processing: FR-LGt

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: FR-LGt | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 9 data points (0.05%) set to NA
H: 1277 data points (7.29%) set to NA
LE: 1296 data points (7.4%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9290 additional data points (53.03%) excluded by precipitation filter (9290
 data points = 53.03 % in total)
9290 data points (53.03%) excluded in total
8230 valid data points (46.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9 data points (0.05%) set to NA
H: 1277 data points (7.29%) set to NA
LE: 1296 data points (7.4%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'FR-LGt'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-LGt-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1234 data points (7.04%) set to NA
LE: 1249 data points (7.13%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8865 additional data points (50.6%) excluded by precipitation filter (8865
 data points = 50.6 % in total)
8865 data points (50.6%) excluded in total
8655 valid data points (49.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1234 data points (7.04%) set to NA
LE: 1249 data points (7.13%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'FR-LGt'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-LGt-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 50 data points (0.29%) set to NA
LE: 24 data points (0.14%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9679 additional data points (55.25%) excluded by precipitation filter (9679
 data points = 55.25 % in total)
9679 data points (55.25%) excluded in total
7841 valid data points (44.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 50 data points (0.29%) set to NA
LE: 24 data points (0.14%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'FR-LGt'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-LGt-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 848 data points (4.83%) set to NA
LE: 846 data points (4.82%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7942 additional data points (45.21%) excluded by precipitation filter (7942
 data points = 45.21 % in total)
7942 data points (45.21%) excluded in total
9626 valid data points (54.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 848 data points (4.83%) set to NA
LE: 846 data points (4.82%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'FR-LGt'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-LGt-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 59 data points (0.34%) set to NA
H: 8707 data points (49.7%) set to NA
LE: 8725 data points (49.8%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9453 additional data points (53.96%) excluded by precipitation filter (9453
 data points = 53.96 % in total)
9453 data points (53.96%) excluded in total
8067 valid data points (46.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 59 data points (0.34%) set to NA
H: 8707 data points (49.7%) set to NA
LE: 8725 data points (49.8%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'FR-LGt'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-LGt-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 29 data points (0.17%) set to NA
H: 47 data points (0.27%) set to NA
LE: 2636 data points (15.05%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7322 additional data points (41.79%) excluded by precipitation filter (7322
 data points = 41.79 % in total)
7322 data points (41.79%) excluded in total
10198 valid data points (58.21%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 29 data points (0.17%) set to NA
H: 47 data points (0.27%) set to NA
LE: 2636 data points (15.05%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'FR-LGt'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-LGt-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 12510 data points (71.4%) set to NA
LE: 15615 data points (89.13%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10338 additional data points (59.01%) excluded by precipitation filter (10338
 data points = 59.01 % in total)
10338 data points (59.01%) excluded in total
7182 valid data points (40.99%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (16) for FR-LGt-2023”

Quality control:
TA: 0 data points (0%) set to NA
H: 3762 data points (21.41%) set to NA
LE: 9810 data points (55.84%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10300 additional data points (58.63%) excluded by precipitation filter (10300
 data points = 58.63 % in total)
10300 data points (58.63%) excluded in total
7268 valid data points (41.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 3762 data points (21.41%) set to NA
LE: 9810 data points (55.84%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'FR-LGt'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-LGt-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[131/329] Processing: FR-Pue

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: FR-Pue | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 14 data points (0.08%) set to NA
LE: 18 data points (0.1%) set to NA
NEE: 521 data points (2.97%) set to NA
-------------------------------------------------------------------
Data filtering:
7728 data points (44.11%) excluded by growing season filter
3124 additional data points (17.83%) excluded by precipitation filter (5740
 data points = 32.76 % in total)
10852 data points (61.94%) excluded in total
6668 valid data points (38.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 14 data points (0.08%) set to NA
LE: 18 data points (0.1%) set to NA
NEE: 521 data points (2.97%) set to NA
-------------------------------------------------------------------
Data filtering:
7728 data points (44.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7728 data points (44.11%) excluded in total
9792 valid data points (55.89%) remaining.

New sEddyProc class for site 'FR-Pue'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Pue-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 84 data points (0.48%) set to NA
LE: 89 data points (0.51%) set to NA
NEE: 691 data points (3.94%) set to NA
-------------------------------------------------------------------
Data filtering:
7872 data points (44.93%) excluded by growing season filter
4012 additional data points (22.9%) excluded by precipitation filter (7792
 data points = 44.47 % in total)
11884 data points (67.83%) excluded in total
5636 valid data points (32.17%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 84 data points (0.48%) set to NA
LE: 89 data points (0.51%) set to NA
NEE: 691 data points (3.94%) set to NA
-------------------------------------------------------------------
Data filtering:
7872 data points (44.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7872 data points (44.93%) excluded in total
9648 valid data points (55.07%) remaining.

New sEddyProc class for site 'FR-Pue'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Pue-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 165 data points (0.94%) set to NA
LE: 183 data points (1.04%) set to NA
NEE: 748 data points (4.27%) set to NA
-------------------------------------------------------------------
Data filtering:
4032 data points (23.01%) excluded by growing season filter
4804 additional data points (27.42%) excluded by precipitation filter (6063
 data points = 34.61 % in total)
8836 data points (50.43%) excluded in total
8684 valid data points (49.57%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 165 data points (0.94%) set to NA
LE: 183 data points (1.04%) set to NA
NEE: 748 data points (4.27%) set to NA
-------------------------------------------------------------------
Data filtering:
4032 data points (23.01%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4032 data points (23.01%) excluded in total
13488 valid data points (76.99%) remaining.

New sEddyProc class for site 'FR-Pue'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Pue-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 124 data points (0.71%) set to NA
LE: 136 data points (0.77%) set to NA
NEE: 956 data points (5.44%) set to NA
-------------------------------------------------------------------
Data filtering:
3984 data points (22.68%) excluded by growing season filter
4513 additional data points (25.69%) excluded by precipitation filter (6811
 data points = 38.77 % in total)
8497 data points (48.37%) excluded in total
9071 valid data points (51.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 124 data points (0.71%) set to NA
LE: 136 data points (0.77%) set to NA
NEE: 956 data points (5.44%) set to NA
-------------------------------------------------------------------
Data filtering:
3984 data points (22.68%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3984 data points (22.68%) excluded in total
13584 valid data points (77.32%) remaining.

New sEddyProc class for site 'FR-Pue'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Pue-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 12 data points (0.07%) set to NA
LE: 12 data points (0.07%) set to NA
NEE: 723 data points (4.13%) set to NA
-------------------------------------------------------------------
Data filtering:
3504 data points (20%) excluded by growing season filter
5493 additional data points (31.35%) excluded by precipitation filter (6941
 data points = 39.62 % in total)
8997 data points (51.35%) excluded in total
8523 valid data points (48.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 12 data points (0.07%) set to NA
LE: 12 data points (0.07%) set to NA
NEE: 723 data points (4.13%) set to NA
-------------------------------------------------------------------
Data filtering:
3504 data points (20%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3504 data points (20%) excluded in total
14016 valid data points (80%) remaining.

New sEddyProc class for site 'FR-Pue'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Pue-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 161 data points (0.92%) set to NA
H: 358 data points (2.04%) set to NA
LE: 243 data points (1.39%) set to NA
NEE: 1293 data points (7.38%) set to NA
-------------------------------------------------------------------
Data filtering:
3648 data points (20.82%) excluded by growing season filter
3751 additional data points (21.41%) excluded by precipitation filter (4594
 data points = 26.22 % in total)
7399 data points (42.23%) excluded in total
10121 valid data points (57.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 161 data points (0.92%) set to NA
H: 358 data points (2.04%) set to NA
LE: 243 data points (1.39%) set to NA
NEE: 1293 data points (7.38%) set to NA
-------------------------------------------------------------------
Data filtering:
3648 data points (20.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3648 data points (20.82%) excluded in total
13872 valid data points (79.18%) remaining.

New sEddyProc class for site 'FR-Pue'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Pue-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 989 data points (5.64%) set to NA
H: 1740 data points (9.93%) set to NA
LE: 1803 data points (10.29%) set to NA
NEE: 3164 data points (18.06%) set to NA
-------------------------------------------------------------------
Data filtering:
3360 data points (19.18%) excluded by growing season filter
4094 additional data points (23.37%) excluded by precipitation filter (4588
 data points = 26.19 % in total)
7454 data points (42.55%) excluded in total
10066 valid data points (57.45%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 989 data points (5.64%) set to NA
H: 1740 data points (9.93%) set to NA
LE: 1803 data points (10.29%) set to NA
NEE: 3164 data points (18.06%) set to NA
-------------------------------------------------------------------
Data filtering:
3360 data points (19.18%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3360 data points (19.18%) excluded in total
14160 valid data points (80.82%) remaining.

New sEddyProc class for site 'FR-Pue'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 103.83.

Regression of reference temperature R_ref for 15 periods.

Quality control:
TA: 435 data points (2.48%) set to NA
H: 538 data points (3.06%) set to NA
LE: 423 data points (2.41%) set to NA
NEE: 1059 data points (6.03%) set to NA
-------------------------------------------------------------------
Data filtering:
2736 data points (15.57%) excluded by growing season filter
4228 additional data points (24.07%) excluded by precipitation filter (5099
 data points = 29.02 % in total)
6964 data points (39.64%) excluded in total
10604 valid data points (60.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 435 data points (2.48%) set to NA
H: 538 data points (3.06%) set to NA
LE: 423 data points (2.41%) set to NA
NEE: 1059 data points (6.03%) set to NA
-------------------------------------------------------------------
Data filtering:
2736 data points (15.57%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2736 data points (15.57%) excluded in total
14832 valid data points (84.43%) remaining.

New sEddyProc class for site 'FR-Pue'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for FR-Pue-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[132/329] Processing: GF-Guy

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: GF-Guy | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 102 data points (0.58%) set to NA
LE: 103 data points (0.59%) set to NA
NEE: 164 data points (0.94%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
13220 additional data points (75.46%) excluded by precipitation filter (13220
 data points = 75.46 % in total)
13220 data points (75.46%) excluded in total
4300 valid data points (24.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 102 data points (0.58%) set to NA
LE: 103 data points (0.59%) set to NA
NEE: 164 data points (0.94%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 46 cases! Invalid values with 'NEE < -50': -77, -60, -50, -64, -78, -57, -54, -53, -71, -56, -66, -56, -79, -70, -62, -52, -79, -63, -52, -57, -56, -50, -59, -68, -69, -64, -78, -50, -58, -61, -51, -53, -57, -58, -55, -53, -53, -56, -72, -70, -54, -63, -57, -52, -78, -61 ...”
New sEddyProc class for site 'GF-Guy'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 46 cases! Invalid values with 'NEE < -50': -77, -60, -50, -64, -78, -57, -54, -53, -71, -56, -66, -56, -79, -70, -62, -52, -79, -63, -52, -57, -56, -50, -59, -68, -69, -64, -78, -50, -58, -61, -51, -53, -57, -58, -55, -53, -53, -56, -72, -70, -54, -63, -57, -52, -78, -61 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GF-Guy-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 399 data points (2.28%) set to NA
LE: 331 data points (1.89%) set to NA
NEE: 472 data points (2.69%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12913 additional data points (73.7%) excluded by precipitation filter (12913
 data points = 73.7 % in total)
12913 data points (73.7%) excluded in total
4607 valid data points (26.3%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 399 data points (2.28%) set to NA
LE: 331 data points (1.89%) set to NA
NEE: 472 data points (2.69%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -58, -55, -53, -56 ...”
New sEddyProc class for site 'GF-Guy'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -58, -55, -53, -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GF-Guy-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 680 data points (3.88%) set to NA
LE: 694 data points (3.96%) set to NA
NEE: 896 data points (5.11%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12685 additional data points (72.4%) excluded by precipitation filter (12685
 data points = 72.4 % in total)
12685 data points (72.4%) excluded in total
4835 valid data points (27.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 680 data points (3.88%) set to NA
LE: 694 data points (3.96%) set to NA
NEE: 896 data points (5.11%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -66 ...”
New sEddyProc class for site 'GF-Guy'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -66 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GF-Guy-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 27 data points (0.15%) set to NA
H: 1519 data points (8.65%) set to NA
LE: 1565 data points (8.91%) set to NA
NEE: 2000 data points (11.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12329 additional data points (70.18%) excluded by precipitation filter (12329
 data points = 70.18 % in total)
12329 data points (70.18%) excluded in total
5239 valid data points (29.82%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 27 data points (0.15%) set to NA
H: 1519 data points (8.65%) set to NA
LE: 1565 data points (8.91%) set to NA
NEE: 2000 data points (11.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -56, -66, -52, -52, -65 ...”
New sEddyProc class for site 'GF-Guy'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -56, -66, -52, -52, -65 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GF-Guy-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 164 data points (0.94%) set to NA
LE: 175 data points (1%) set to NA
NEE: 262 data points (1.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
14207 additional data points (81.09%) excluded by precipitation filter (14207
 data points = 81.09 % in total)
14207 data points (81.09%) excluded in total
3313 valid data points (18.91%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 164 data points (0.94%) set to NA
LE: 175 data points (1%) set to NA
NEE: 262 data points (1.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -61, -57, -52, -56, -56 ...”
New sEddyProc class for site 'GF-Guy'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -61, -57, -52, -56, -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GF-Guy-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 166 data points (0.95%) set to NA
H: 281 data points (1.6%) set to NA
LE: 250 data points (1.43%) set to NA
NEE: 351 data points (2%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
13671 additional data points (78.03%) excluded by precipitation filter (13671
 data points = 78.03 % in total)
13671 data points (78.03%) excluded in total
3849 valid data points (21.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 166 data points (0.95%) set to NA
H: 281 data points (1.6%) set to NA
LE: 250 data points (1.43%) set to NA
NEE: 351 data points (2%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -53, -58, -70, -51, -68 ...”
New sEddyProc class for site 'GF-Guy'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -53, -58, -70, -51, -68 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GF-Guy-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 881 data points (5.03%) set to NA
LE: 910 data points (5.19%) set to NA
NEE: 1023 data points (5.84%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
11315 additional data points (64.58%) excluded by precipitation filter (11315
 data points = 64.58 % in total)
11315 data points (64.58%) excluded in total
6205 valid data points (35.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 881 data points (5.03%) set to NA
LE: 910 data points (5.19%) set to NA
NEE: 1023 data points (5.84%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -51, -54, -64 ...”
New sEddyProc class for site 'GF-Guy'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -51, -54, -64 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GF-Guy-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 736 data points (4.19%) set to NA
H: 2701 data points (15.37%) set to NA
LE: 2766 data points (15.74%) set to NA
NEE: 2912 data points (16.58%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10306 additional data points (58.66%) excluded by precipitation filter (10306
 data points = 58.66 % in total)
10306 data points (58.66%) excluded in total
7262 valid data points (41.34%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 736 data points (4.19%) set to NA
H: 2701 data points (15.37%) set to NA
LE: 2766 data points (15.74%) set to NA
NEE: 2912 data points (16.58%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -77 ...”
New sEddyProc class for site 'GF-Guy'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -77 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GF-Guy-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[133/329] Processing: GL-Dsk

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: GL-Dsk | Years: 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 12 data points (0.07%) set to NA
H: 7 data points (0.04%) set to NA
LE: 10 data points (0.06%) set to NA
NEE: 238 data points (1.35%) set to NA
-------------------------------------------------------------------
Data filtering:
13776 data points (78.42%) excluded by growing season filter
1594 additional data points (9.07%) excluded by precipitation filter (9094
 data points = 51.76 % in total)
15370 data points (87.49%) excluded in total
2198 valid data points (12.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12 data points (0.07%) set to NA
H: 7 data points (0.04%) set to NA
LE: 10 data points (0.06%) set to NA
NEE: 238 data points (1.35%) set to NA
-------------------------------------------------------------------
Data filtering:
13776 data points (78.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13776 data points (78.42%) excluded in total
3792 valid data points (21.58%) remaining.

New sEddyProc class for site 'GL-Dsk'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GL-Dsk-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 5 data points (0.03%) set to NA
H: 271 data points (1.55%) set to NA
LE: 271 data points (1.55%) set to NA
NEE: 754 data points (4.3%) set to NA
-------------------------------------------------------------------
Data filtering:
13344 data points (76.16%) excluded by growing season filter
2400 additional data points (13.7%) excluded by precipitation filter (8922
 data points = 50.92 % in total)
15744 data points (89.86%) excluded in total
1776 valid data points (10.14%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5 data points (0.03%) set to NA
H: 271 data points (1.55%) set to NA
LE: 271 data points (1.55%) set to NA
NEE: 754 data points (4.3%) set to NA
-------------------------------------------------------------------
Data filtering:
13344 data points (76.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13344 data points (76.16%) excluded in total
4176 valid data points (23.84%) remaining.

New sEddyProc class for site 'GL-Dsk'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GL-Dsk-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 560 data points (3.2%) set to NA
H: 268 data points (1.53%) set to NA
LE: 281 data points (1.6%) set to NA
NEE: 1745 data points (9.96%) set to NA
-------------------------------------------------------------------
Data filtering:
14112 data points (80.55%) excluded by growing season filter
1916 additional data points (10.94%) excluded by precipitation filter (9994
 data points = 57.04 % in total)
16028 data points (91.48%) excluded in total
1492 valid data points (8.52%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 560 data points (3.2%) set to NA
H: 268 data points (1.53%) set to NA
LE: 281 data points (1.6%) set to NA
NEE: 1745 data points (9.96%) set to NA
-------------------------------------------------------------------
Data filtering:
14112 data points (80.55%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14112 data points (80.55%) excluded in total
3408 valid data points (19.45%) remaining.

New sEddyProc class for site 'GL-Dsk'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GL-Dsk-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 954 data points (5.45%) set to NA
H: 1771 data points (10.11%) set to NA
LE: 1757 data points (10.03%) set to NA
NEE: 4311 data points (24.61%) set to NA
-------------------------------------------------------------------
Data filtering:
14448 data points (82.47%) excluded by growing season filter
1922 additional data points (10.97%) excluded by precipitation filter (8770
 data points = 50.06 % in total)
16370 data points (93.44%) excluded in total
1150 valid data points (6.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 954 data points (5.45%) set to NA
H: 1771 data points (10.11%) set to NA
LE: 1757 data points (10.03%) set to NA
NEE: 4311 data points (24.61%) set to NA
-------------------------------------------------------------------
Data filtering:
14448 data points (82.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14448 data points (82.47%) excluded in total
3072 valid data points (17.53%) remaining.

New sEddyProc class for site 'GL-Dsk'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GL-Dsk-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4 data points (0.02%) set to NA
H: 1079 data points (6.14%) set to NA
LE: 1082 data points (6.16%) set to NA
NEE: 1728 data points (9.84%) set to NA
-------------------------------------------------------------------
Data filtering:
14208 data points (80.87%) excluded by growing season filter
1444 additional data points (8.22%) excluded by precipitation filter (8452
 data points = 48.11 % in total)
15652 data points (89.09%) excluded in total
1916 valid data points (10.91%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4 data points (0.02%) set to NA
H: 1079 data points (6.14%) set to NA
LE: 1082 data points (6.16%) set to NA
NEE: 1728 data points (9.84%) set to NA
-------------------------------------------------------------------
Data filtering:
14208 data points (80.87%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14208 data points (80.87%) excluded in total
3360 valid data points (19.13%) remaining.

New sEddyProc class for site 'GL-Dsk'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GL-Dsk-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[134/329] Processing: GL-NuF

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: GL-NuF | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 3279 data points (18.72%) set to NA
H: 14465 data points (82.56%) set to NA
LE: 14463 data points (82.55%) set to NA
NEE: 14498 data points (82.75%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3780 additional data points (21.58%) excluded by precipitation filter (3780
 data points = 21.58 % in total)
3780 data points (21.58%) excluded in total
13740 valid data points (78.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3279 data points (18.72%) set to NA
H: 14465 data points (82.56%) set to NA
LE: 14463 data points (82.55%) set to NA
NEE: 14498 data points (82.75%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'GL-NuF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GL-NuF-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6464 data points (36.79%) set to NA
H: 13036 data points (74.2%) set to NA
LE: 13029 data points (74.16%) set to NA
NEE: 13699 data points (77.98%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6113 additional data points (34.8%) excluded by precipitation filter (6113
 data points = 34.8 % in total)
6113 data points (34.8%) excluded in total
11455 valid data points (65.2%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6464 data points (36.79%) set to NA
H: 13036 data points (74.2%) set to NA
LE: 13029 data points (74.16%) set to NA
NEE: 13699 data points (77.98%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'GL-NuF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GL-NuF-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2433 data points (13.89%) set to NA
H: 16865 data points (96.26%) set to NA
LE: 16865 data points (96.26%) set to NA
NEE: 16881 data points (96.35%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5296 additional data points (30.23%) excluded by precipitation filter (5296
 data points = 30.23 % in total)
5296 data points (30.23%) excluded in total
12224 valid data points (69.77%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (39) for GL-NuF-2021”

Quality control:
TA: 2070 data points (11.82%) set to NA
H: 11444 data points (65.32%) set to NA
LE: 11457 data points (65.39%) set to NA
NEE: 11711 data points (66.84%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 176”

-------------------------------------------------------------------
Data filtering:
5040 data points (28.77%) excluded by growing season filter
4080 additional data points (23.29%) excluded by precipitation filter (6263
 data points = 35.75 % in total)
9120 data points (52.05%) excluded in total
8400 valid data points (47.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2070 data points (11.82%) set to NA
H: 11444 data points (65.32%) set to NA
LE: 11457 data points (65.39%) set to NA
NEE: 11711 data points (66.84%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 176”

-------------------------------------------------------------------
Data filtering:
5040 data points (28.77%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5040 data points (28.77%) excluded in total
12480 valid data points (71.23%) remaining.

New sEddyProc class for site 'GL-NuF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GL-NuF-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 8 data points (0.05%) set to NA
H: 12708 data points (72.53%) set to NA
LE: 12711 data points (72.55%) set to NA
NEE: 12905 data points (73.66%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4140 additional data points (23.63%) excluded by precipitation filter (4140
 data points = 23.63 % in total)
4140 data points (23.63%) excluded in total
13380 valid data points (76.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8 data points (0.05%) set to NA
H: 12708 data points (72.53%) set to NA
LE: 12711 data points (72.55%) set to NA
NEE: 12905 data points (73.66%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'GL-NuF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GL-NuF-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4133 data points (23.53%) set to NA
H: 11966 data points (68.11%) set to NA
LE: 11952 data points (68.03%) set to NA
NEE: 14017 data points (79.79%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5610 additional data points (31.93%) excluded by precipitation filter (5610
 data points = 31.93 % in total)
5610 data points (31.93%) excluded in total
11958 valid data points (68.07%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4133 data points (23.53%) set to NA
H: 11966 data points (68.11%) set to NA
LE: 11952 data points (68.03%) set to NA
NEE: 14017 data points (79.79%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'GL-NuF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GL-NuF-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[135/329] Processing: GL-ZaF

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: GL-ZaF | Years: 2023, 2024
Quality control:
TA: 5577 data points (31.83%) set to NA
H: 7922 data points (45.22%) set to NA
LE: 7932 data points (45.27%) set to NA
NEE: 8416 data points (48.04%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 104”

-------------------------------------------------------------------
Data filtering:
14928 data points (85.21%) excluded by growing season filter
1095 additional data points (6.25%) excluded by precipitation filter (9596
 data points = 54.77 % in total)
16023 data points (91.46%) excluded in total
1497 valid data points (8.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5577 data points (31.83%) set to NA
H: 7922 data points (45.22%) set to NA
LE: 7932 data points (45.27%) set to NA
NEE: 8416 data points (48.04%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 104”

-------------------------------------------------------------------
Data filtering:
14928 data points (85.21%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14928 data points (85.21%) excluded in total
2592 valid data points (14.79%) remaining.

New sEddyProc class for site 'GL-ZaF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 8 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GL-ZaF-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 5554 data points (31.61%) set to NA
H: 5500 data points (31.31%) set to NA
LE: 5445 data points (30.99%) set to NA
NEE: 6312 data points (35.93%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 96”

-------------------------------------------------------------------
Data filtering:
15120 data points (86.07%) excluded by growing season filter
1027 additional data points (5.85%) excluded by precipitation filter (7878
 data points = 44.84 % in total)
16147 data points (91.91%) excluded in total
1421 valid data points (8.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5554 data points (31.61%) set to NA
H: 5500 data points (31.31%) set to NA
LE: 5445 data points (30.99%) set to NA
NEE: 6312 data points (35.93%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 96”

-------------------------------------------------------------------
Data filtering:
15120 data points (86.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
15120 data points (86.07%) excluded in total
2448 valid data points (13.93%) remaining.

New sEddyProc class for site 'GL-ZaF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for GL-ZaF-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[136/329] Processing: ID-JOP

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ID-JOP | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 114 data points (0.65%) set to NA
H: 303 data points (1.73%) set to NA
LE: 3113 data points (17.77%) set to NA
NEE: 5147 data points (29.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5257 additional data points (30.01%) excluded by precipitation filter (5257
 data points = 30.01 % in total)
5257 data points (30.01%) excluded in total
12263 valid data points (69.99%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 114 data points (0.65%) set to NA
H: 303 data points (1.73%) set to NA
LE: 3113 data points (17.77%) set to NA
NEE: 5147 data points (29.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -53, -52 ...”
New sEddyProc class for site 'ID-JOP'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -53, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ID-JOP-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1341 data points (7.65%) set to NA
H: 739 data points (4.22%) set to NA
LE: 5784 data points (33.01%) set to NA
NEE: 6498 data points (37.09%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9096 additional data points (51.92%) excluded by precipitation filter (9096
 data points = 51.92 % in total)
9096 data points (51.92%) excluded in total
8424 valid data points (48.08%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1341 data points (7.65%) set to NA
H: 739 data points (4.22%) set to NA
LE: 5784 data points (33.01%) set to NA
NEE: 6498 data points (37.09%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'ID-JOP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 11 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ID-JOP-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 559 data points (3.19%) set to NA
H: 378 data points (2.16%) set to NA
LE: 1062 data points (6.06%) set to NA
NEE: 1726 data points (9.85%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
13405 additional data points (76.51%) excluded by precipitation filter (13405
 data points = 76.51 % in total)
13405 data points (76.51%) excluded in total
4115 valid data points (23.49%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 559 data points (3.19%) set to NA
H: 378 data points (2.16%) set to NA
LE: 1062 data points (6.06%) set to NA
NEE: 1726 data points (9.85%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -53, -56 ...”
New sEddyProc class for site 'ID-JOP'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -53, -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ID-JOP-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 102 data points (0.58%) set to NA
H: 769 data points (4.38%) set to NA
LE: 3888 data points (22.13%) set to NA
NEE: 4103 data points (23.35%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10212 additional data points (58.13%) excluded by precipitation filter (10212
 data points = 58.13 % in total)
10212 data points (58.13%) excluded in total
7356 valid data points (41.87%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 102 data points (0.58%) set to NA
H: 769 data points (4.38%) set to NA
LE: 3888 data points (22.13%) set to NA
NEE: 4103 data points (23.35%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -51 ...”
New sEddyProc class for site 'ID-JOP'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ID-JOP-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3348 data points (19.11%) set to NA
H: 3550 data points (20.26%) set to NA
LE: 11675 data points (66.64%) set to NA
NEE: 11722 data points (66.91%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
14647 additional data points (83.6%) excluded by precipitation filter (14647
 data points = 83.6 % in total)
14647 data points (83.6%) excluded in total
2873 valid data points (16.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3348 data points (19.11%) set to NA
H: 3550 data points (20.26%) set to NA
LE: 11675 data points (66.64%) set to NA
NEE: 11722 data points (66.91%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -57 ...”
New sEddyProc class for site 'ID-JOP'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -57 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ID-JOP-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3403 data points (19.42%) set to NA
H: 4180 data points (23.86%) set to NA
LE: 6808 data points (38.86%) set to NA
NEE: 6930 data points (39.55%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
14482 additional data points (82.66%) excluded by precipitation filter (14482
 data points = 82.66 % in total)
14482 data points (82.66%) excluded in total
3038 valid data points (17.34%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3403 data points (19.42%) set to NA
H: 4180 data points (23.86%) set to NA
LE: 6808 data points (38.86%) set to NA
NEE: 6930 data points (39.55%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -59, -72, -52, -50 ...”
New sEddyProc class for site 'ID-JOP'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -59, -72, -52, -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ID-JOP-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 9811 data points (56%) set to NA
H: 1775 data points (10.13%) set to NA
LE: 1911 data points (10.91%) set to NA
NEE: 2125 data points (12.13%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7970 additional data points (45.49%) excluded by precipitation filter (7970
 data points = 45.49 % in total)
7970 data points (45.49%) excluded in total
9550 valid data points (54.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9811 data points (56%) set to NA
H: 1775 data points (10.13%) set to NA
LE: 1911 data points (10.91%) set to NA
NEE: 2125 data points (12.13%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -60, -54, -54 ...”
New sEddyProc class for site 'ID-JOP'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -60, -54, -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ID-JOP-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4674 data points (26.61%) set to NA
H: 7451 data points (42.41%) set to NA
LE: 11493 data points (65.42%) set to NA
NEE: 11585 data points (65.94%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9650 additional data points (54.93%) excluded by precipitation filter (9650
 data points = 54.93 % in total)
9650 data points (54.93%) excluded in total
7918 valid data points (45.07%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4674 data points (26.61%) set to NA
H: 7451 data points (42.41%) set to NA
LE: 11493 data points (65.42%) set to NA
NEE: 11585 data points (65.94%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'ID-JOP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 8 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ID-JOP-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[137/329] Processing: ID-PaD

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ID-PaD | Years: 2017
Quality control:
TA: 9998 data points (57.07%) set to NA
H: 10051 data points (57.37%) set to NA
LE: 10049 data points (57.36%) set to NA
NEE: 10198 data points (58.21%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
13022 additional data points (74.33%) excluded by precipitation filter (13022
 data points = 74.33 % in total)
13022 data points (74.33%) excluded in total
4498 valid data points (25.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 9998 data points (57.07%) set to NA
H: 10051 data points (57.37%) set to NA
LE: 10049 data points (57.36%) set to NA
NEE: 10198 data points (58.21%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -52, -51, -51, -52, -56 ...”
New sEddyProc class for site 'ID-PaD'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -52, -51, -51, -52, -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ID-PaD-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[138/329] Processing: ID-Pag

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ID-Pag | Years: 2017, 2018
Quality control:
TA: 0 data points (0%) set to NA
H: 9549 data points (54.5%) set to NA
LE: 5420 data points (30.94%) set to NA
NEE: 5756 data points (32.85%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10801 additional data points (61.65%) excluded by precipitation filter (10801
 data points = 61.65 % in total)
10801 data points (61.65%) excluded in total
6719 valid data points (38.35%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 9549 data points (54.5%) set to NA
LE: 5420 data points (30.94%) set to NA
NEE: 5756 data points (32.85%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -60, -55, -54, -60, -54, -61, -57, -52 ...”
New sEddyProc class for site 'ID-Pag'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -60, -55, -54, -60, -54, -61, -57, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ID-Pag-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 10458 data points (59.69%) set to NA
LE: 10415 data points (59.45%) set to NA
NEE: 13124 data points (74.91%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9312 additional data points (53.15%) excluded by precipitation filter (9312
 data points = 53.15 % in total)
9312 data points (53.15%) excluded in total
8208 valid data points (46.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 10458 data points (59.69%) set to NA
LE: 10415 data points (59.45%) set to NA
NEE: 13124 data points (74.91%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -56, -55, -65, -51 ...”
New sEddyProc class for site 'ID-Pag'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -56, -55, -65, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ID-Pag-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[139/329] Processing: IE-Cra

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: IE-Cra | Years: 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 17 data points (0.1%) set to NA
LE: 60 data points (0.34%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12656 additional data points (72.04%) excluded by precipitation filter (12656
 data points = 72.04 % in total)
12656 data points (72.04%) excluded in total
4912 valid data points (27.96%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 17 data points (0.1%) set to NA
LE: 60 data points (0.34%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'IE-Cra'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IE-Cra-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 17519 data points (99.99%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12286 additional data points (70.13%) excluded by precipitation filter (12286
 data points = 70.13 % in total)
12286 data points (70.13%) excluded in total
5234 valid data points (29.87%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for IE-Cra-2021”

Quality control:
TA: 17520 data points (100%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12486 additional data points (71.27%) excluded by precipitation filter (12486
 data points = 71.27 % in total)
12486 data points (71.27%) excluded in total
5034 valid data points (28.73%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for IE-Cra-2022”

Quality control:
TA: 17520 data points (100%) set to NA
H: 17519 data points (99.99%) set to NA
LE: 17519 data points (99.99%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
13370 additional data points (76.31%) excluded by precipitation filter (13370
 data points = 76.31 % in total)
13370 data points (76.31%) excluded in total
4150 valid data points (23.69%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for IE-Cra-2023”

Quality control:
TA: 844 data points (4.8%) set to NA
H: 709 data points (4.04%) set to NA
LE: 779 data points (4.43%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12888 additional data points (73.36%) excluded by precipitation filter (12888
 data points = 73.36 % in total)
12888 data points (73.36%) excluded in total
4680 valid data points (26.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 844 data points (4.8%) set to NA
H: 709 data points (4.04%) set to NA
LE: 779 data points (4.43%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'IE-Cra'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IE-Cra-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[140/329] Processing: IL-RmH

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: IL-RmH | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 8823 data points (50.36%) set to NA
H: 9763 data points (55.72%) set to NA
LE: 9830 data points (56.11%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2946 additional data points (16.82%) excluded by precipitation filter (2946
 data points = 16.82 % in total)
2946 data points (16.82%) excluded in total
14574 valid data points (83.18%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8823 data points (50.36%) set to NA
H: 9763 data points (55.72%) set to NA
LE: 9830 data points (56.11%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'IL-RmH'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IL-RmH-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 12175 data points (69.49%) set to NA
H: 13416 data points (76.58%) set to NA
LE: 13438 data points (76.7%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5141 additional data points (29.34%) excluded by precipitation filter (5141
 data points = 29.34 % in total)
5141 data points (29.34%) excluded in total
12379 valid data points (70.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12175 data points (69.49%) set to NA
H: 13416 data points (76.58%) set to NA
LE: 13438 data points (76.7%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'IL-RmH'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IL-RmH-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 17460 data points (99.66%) set to NA
H: 12224 data points (69.77%) set to NA
LE: 12453 data points (71.08%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3146 additional data points (17.96%) excluded by precipitation filter (3146
 data points = 17.96 % in total)
3146 data points (17.96%) excluded in total
14374 valid data points (82.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 17460 data points (99.66%) set to NA
H: 12224 data points (69.77%) set to NA
LE: 12453 data points (71.08%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'IL-RmH'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IL-RmH-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 15960 data points (90.85%) set to NA
H: 14734 data points (83.87%) set to NA
LE: 14757 data points (84%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4665 additional data points (26.55%) excluded by precipitation filter (4665
 data points = 26.55 % in total)
4665 data points (26.55%) excluded in total
12903 valid data points (73.45%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 15960 data points (90.85%) set to NA
H: 14734 data points (83.87%) set to NA
LE: 14757 data points (84%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'IL-RmH'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IL-RmH-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[141/329] Processing: IL-Yat

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: IL-Yat | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 5 data points (0.03%) set to NA
H: 10 data points (0.06%) set to NA
LE: 337 data points (1.92%) set to NA
NEE: 1040 data points (5.94%) set to NA
-------------------------------------------------------------------
Data filtering:
11424 data points (65.21%) excluded by growing season filter
949 additional data points (5.42%) excluded by precipitation filter (1425
 data points = 8.13 % in total)
12373 data points (70.62%) excluded in total
5147 valid data points (29.38%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5 data points (0.03%) set to NA
H: 10 data points (0.06%) set to NA
LE: 337 data points (1.92%) set to NA
NEE: 1040 data points (5.94%) set to NA
-------------------------------------------------------------------
Data filtering:
11424 data points (65.21%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11424 data points (65.21%) excluded in total
6096 valid data points (34.79%) remaining.

New sEddyProc class for site 'IL-Yat'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IL-Yat-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 145 data points (0.83%) set to NA
H: 26 data points (0.15%) set to NA
LE: 92 data points (0.53%) set to NA
NEE: 1951 data points (11.14%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
2025 additional data points (11.56%) excluded by precipitation filter (2590
 data points = 14.78 % in total)
11961 data points (68.27%) excluded in total
5559 valid data points (31.73%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 145 data points (0.83%) set to NA
H: 26 data points (0.15%) set to NA
LE: 92 data points (0.53%) set to NA
NEE: 1951 data points (11.14%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9936 data points (56.71%) excluded in total
7584 valid data points (43.29%) remaining.

New sEddyProc class for site 'IL-Yat'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IL-Yat-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 143 data points (0.82%) set to NA
H: 8 data points (0.05%) set to NA
LE: 98 data points (0.56%) set to NA
NEE: 1001 data points (5.71%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.47%) excluded by growing season filter
1563 additional data points (8.92%) excluded by precipitation filter (1839
 data points = 10.5 % in total)
12507 data points (71.39%) excluded in total
5013 valid data points (28.61%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 143 data points (0.82%) set to NA
H: 8 data points (0.05%) set to NA
LE: 98 data points (0.56%) set to NA
NEE: 1001 data points (5.71%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10944 data points (62.47%) excluded in total
6576 valid data points (37.53%) remaining.

New sEddyProc class for site 'IL-Yat'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IL-Yat-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 5 data points (0.03%) set to NA
H: 15 data points (0.09%) set to NA
LE: 17 data points (0.1%) set to NA
NEE: 461 data points (2.62%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.27%) excluded by growing season filter
2446 additional data points (13.92%) excluded by precipitation filter (2971
 data points = 16.91 % in total)
10750 data points (61.19%) excluded in total
6818 valid data points (38.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5 data points (0.03%) set to NA
H: 15 data points (0.09%) set to NA
LE: 17 data points (0.1%) set to NA
NEE: 461 data points (2.62%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8304 data points (47.27%) excluded in total
9264 valid data points (52.73%) remaining.

New sEddyProc class for site 'IL-Yat'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IL-Yat-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 159 data points (0.91%) set to NA
H: 33 data points (0.19%) set to NA
LE: 37 data points (0.21%) set to NA
NEE: 1138 data points (6.5%) set to NA
-------------------------------------------------------------------
Data filtering:
12624 data points (72.05%) excluded by growing season filter
916 additional data points (5.23%) excluded by precipitation filter (1531
 data points = 8.74 % in total)
13540 data points (77.28%) excluded in total
3980 valid data points (22.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 159 data points (0.91%) set to NA
H: 33 data points (0.19%) set to NA
LE: 37 data points (0.21%) set to NA
NEE: 1138 data points (6.5%) set to NA
-------------------------------------------------------------------
Data filtering:
12624 data points (72.05%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12624 data points (72.05%) excluded in total
4896 valid data points (27.95%) remaining.

New sEddyProc class for site 'IL-Yat'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IL-Yat-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 7 data points (0.04%) set to NA
H: 0 data points (0%) set to NA
LE: 1 data points (0.01%) set to NA
NEE: 398 data points (2.27%) set to NA
-------------------------------------------------------------------
Data filtering:
12672 data points (72.33%) excluded by growing season filter
1132 additional data points (6.46%) excluded by precipitation filter (2064
 data points = 11.78 % in total)
13804 data points (78.79%) excluded in total
3716 valid data points (21.21%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7 data points (0.04%) set to NA
H: 0 data points (0%) set to NA
LE: 1 data points (0.01%) set to NA
NEE: 398 data points (2.27%) set to NA
-------------------------------------------------------------------
Data filtering:
12672 data points (72.33%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12672 data points (72.33%) excluded in total
4848 valid data points (27.67%) remaining.

New sEddyProc class for site 'IL-Yat'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IL-Yat-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 264 data points (1.51%) set to NA
H: 0 data points (0%) set to NA
LE: 5 data points (0.03%) set to NA
NEE: 490 data points (2.8%) set to NA
-------------------------------------------------------------------
Data filtering:
12000 data points (68.49%) excluded by growing season filter
772 additional data points (4.41%) excluded by precipitation filter (1899
 data points = 10.84 % in total)
12772 data points (72.9%) excluded in total
4748 valid data points (27.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 264 data points (1.51%) set to NA
H: 0 data points (0%) set to NA
LE: 5 data points (0.03%) set to NA
NEE: 490 data points (2.8%) set to NA
-------------------------------------------------------------------
Data filtering:
12000 data points (68.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12000 data points (68.49%) excluded in total
5520 valid data points (31.51%) remaining.

New sEddyProc class for site 'IL-Yat'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IL-Yat-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 9 data points (0.05%) set to NA
LE: 15 data points (0.09%) set to NA
NEE: 771 data points (4.39%) set to NA
-------------------------------------------------------------------
Data filtering:
12480 data points (71.04%) excluded by growing season filter
1417 additional data points (8.07%) excluded by precipitation filter (2038
 data points = 11.6 % in total)
13897 data points (79.1%) excluded in total
3671 valid data points (20.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 9 data points (0.05%) set to NA
LE: 15 data points (0.09%) set to NA
NEE: 771 data points (4.39%) set to NA
-------------------------------------------------------------------
Data filtering:
12480 data points (71.04%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12480 data points (71.04%) excluded in total
5088 valid data points (28.96%) remaining.

New sEddyProc class for site 'IL-Yat'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IL-Yat-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[142/329] Processing: IT-Arz

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: IT-Arz | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 319 data points (1.82%) set to NA
H: 327 data points (1.87%) set to NA
LE: 416 data points (2.37%) set to NA
NEE: 725 data points (4.14%) set to NA
-------------------------------------------------------------------
Data filtering:
8400 data points (47.95%) excluded by growing season filter
4766 additional data points (27.2%) excluded by precipitation filter (8186
 data points = 46.72 % in total)
13166 data points (75.15%) excluded in total
4354 valid data points (24.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 319 data points (1.82%) set to NA
H: 327 data points (1.87%) set to NA
LE: 416 data points (2.37%) set to NA
NEE: 725 data points (4.14%) set to NA
-------------------------------------------------------------------
Data filtering:
8400 data points (47.95%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8400 data points (47.95%) excluded in total
9120 valid data points (52.05%) remaining.

New sEddyProc class for site 'IT-Arz'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 89.32.

Regression of reference temperature R_ref for 5 periods.

Quality control:
TA: 329 data points (1.88%) set to NA
H: 335 data points (1.91%) set to NA
LE: 393 data points (2.24%) set to NA
NEE: 581 data points (3.32%) set to NA
-------------------------------------------------------------------
Data filtering:
8160 data points (46.58%) excluded by growing season filter
6766 additional data points (38.62%) excluded by precipitation filter (11430
 data points = 65.24 % in total)
14926 data points (85.19%) excluded in total
2594 valid data points (14.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 329 data points (1.88%) set to NA
H: 335 data points (1.91%) set to NA
LE: 393 data points (2.24%) set to NA
NEE: 581 data points (3.32%) set to NA
-------------------------------------------------------------------
Data filtering:
8160 data points (46.58%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8160 data points (46.58%) excluded in total
9360 valid data points (53.42%) remaining.

New sEddyProc class for site 'IT-Arz'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Arz-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 470 data points (2.68%) set to NA
H: 483 data points (2.76%) set to NA
LE: 507 data points (2.89%) set to NA
NEE: 687 data points (3.92%) set to NA
-------------------------------------------------------------------
Data filtering:
7584 data points (43.29%) excluded by growing season filter
6042 additional data points (34.49%) excluded by precipitation filter (9460
 data points = 54 % in total)
13626 data points (77.77%) excluded in total
3894 valid data points (22.23%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 470 data points (2.68%) set to NA
H: 483 data points (2.76%) set to NA
LE: 507 data points (2.89%) set to NA
NEE: 687 data points (3.92%) set to NA
-------------------------------------------------------------------
Data filtering:
7584 data points (43.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7584 data points (43.29%) excluded in total
9936 valid data points (56.71%) remaining.

New sEddyProc class for site 'IT-Arz'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Arz-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 501 data points (2.85%) set to NA
H: 514 data points (2.93%) set to NA
LE: 974 data points (5.54%) set to NA
NEE: 4937 data points (28.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 18”

-------------------------------------------------------------------
Data filtering:
10896 data points (62.02%) excluded by growing season filter
4262 additional data points (24.26%) excluded by precipitation filter (8906
 data points = 50.69 % in total)
15158 data points (86.28%) excluded in total
2410 valid data points (13.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 501 data points (2.85%) set to NA
H: 514 data points (2.93%) set to NA
LE: 974 data points (5.54%) set to NA
NEE: 4937 data points (28.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 18”

-------------------------------------------------------------------
Data filtering:
10896 data points (62.02%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10896 data points (62.02%) excluded in total
6672 valid data points (37.98%) remaining.

New sEddyProc class for site 'IT-Arz'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 224.

Regression of reference temperature R_ref for 7 periods.

Quality control:
TA: 130 data points (0.74%) set to NA
H: 139 data points (0.79%) set to NA
LE: 180 data points (1.03%) set to NA
NEE: 755 data points (4.31%) set to NA
-------------------------------------------------------------------
Data filtering:
6624 data points (37.81%) excluded by growing season filter
6048 additional data points (34.52%) excluded by precipitation filter (9286
 data points = 53 % in total)
12672 data points (72.33%) excluded in total
4848 valid data points (27.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 130 data points (0.74%) set to NA
H: 139 data points (0.79%) set to NA
LE: 180 data points (1.03%) set to NA
NEE: 755 data points (4.31%) set to NA
-------------------------------------------------------------------
Data filtering:
6624 data points (37.81%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6624 data points (37.81%) excluded in total
10896 valid data points (62.19%) remaining.

New sEddyProc class for site 'IT-Arz'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 1 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Arz-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1659 data points (9.47%) set to NA
H: 1684 data points (9.61%) set to NA
LE: 1727 data points (9.86%) set to NA
NEE: 1923 data points (10.98%) set to NA
-------------------------------------------------------------------
Data filtering:
7584 data points (43.29%) excluded by growing season filter
4754 additional data points (27.13%) excluded by precipitation filter (7658
 data points = 43.71 % in total)
12338 data points (70.42%) excluded in total
5182 valid data points (29.58%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1659 data points (9.47%) set to NA
H: 1684 data points (9.61%) set to NA
LE: 1727 data points (9.86%) set to NA
NEE: 1923 data points (10.98%) set to NA
-------------------------------------------------------------------
Data filtering:
7584 data points (43.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7584 data points (43.29%) excluded in total
9936 valid data points (56.71%) remaining.

New sEddyProc class for site 'IT-Arz'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 129.09.

Regression of reference temperature R_ref for 20 periods.

Quality control:
TA: 161 data points (0.92%) set to NA
H: 176 data points (1%) set to NA
LE: 5858 data points (33.44%) set to NA
NEE: 6149 data points (35.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 69”

-------------------------------------------------------------------
Data filtering:
9168 data points (52.33%) excluded by growing season filter
5464 additional data points (31.19%) excluded by precipitation filter (9434
 data points = 53.85 % in total)
14632 data points (83.52%) excluded in total
2888 valid data points (16.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 161 data points (0.92%) set to NA
H: 176 data points (1%) set to NA
LE: 5858 data points (33.44%) set to NA
NEE: 6149 data points (35.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 69”

-------------------------------------------------------------------
Data filtering:
9168 data points (52.33%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9168 data points (52.33%) excluded in total
8352 valid data points (47.67%) remaining.

New sEddyProc class for site 'IT-Arz'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Arz-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2229 data points (12.69%) set to NA
H: 8177 data points (46.54%) set to NA
LE: 8494 data points (48.35%) set to NA
NEE: 8590 data points (48.9%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 97”

-------------------------------------------------------------------
Data filtering:
6816 data points (38.8%) excluded by growing season filter
6616 additional data points (37.66%) excluded by precipitation filter (10608
 data points = 60.38 % in total)
13432 data points (76.46%) excluded in total
4136 valid data points (23.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2229 data points (12.69%) set to NA
H: 8177 data points (46.54%) set to NA
LE: 8494 data points (48.35%) set to NA
NEE: 8590 data points (48.9%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 97”

-------------------------------------------------------------------
Data filtering:
6816 data points (38.8%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6816 data points (38.8%) excluded in total
10752 valid data points (61.2%) remaining.

New sEddyProc class for site 'IT-Arz'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Arz-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[143/329] Processing: IT-BFt

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: IT-BFt | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 18 data points (0.1%) set to NA
LE: 72 data points (0.41%) set to NA
NEE: 501 data points (2.86%) set to NA
-------------------------------------------------------------------
Data filtering:
5520 data points (31.51%) excluded by growing season filter
2724 additional data points (15.55%) excluded by precipitation filter (4891
 data points = 27.92 % in total)
8244 data points (47.05%) excluded in total
9276 valid data points (52.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.

Warning message in nlrob(Gs ~ g0 + DwDc * (1 + g1/sqrt(VPD)) * GPP/Ca, data = df, :
“failed to converge in 20 steps”

Quality control:
TA: 0 data points (0%) set to NA
H: 18 data points (0.1%) set to NA
LE: 72 data points (0.41%) set to NA
NEE: 501 data points (2.86%) set to NA
-------------------------------------------------------------------
Data filtering:
5520 data points (31.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5520 data points (31.51%) excluded in total
12000 valid data points (68.49%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
New sEddyProc class for site 'IT-BFt'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-BFt-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 116 data points (0.66%) set to NA
NEE: 428 data points (2.44%) set to NA
-------------------------------------------------------------------
Data filtering:
6192 data points (35.25%) excluded by growing season filter
1552 additional data points (8.83%) excluded by precipitation filter (2760
 data points = 15.71 % in total)
7744 data points (44.08%) excluded in total
9824 valid data points (55.92%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 116 data points (0.66%) set to NA
NEE: 428 data points (2.44%) set to NA
-------------------------------------------------------------------
Data filtering:
6192 data points (35.25%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6192 data points (35.25%) excluded in total
11376 valid data points (64.75%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -62, -64, -58 ...”
New sEddyProc class for site 'IT-BFt'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -62, -64, -58 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-BFt-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 131 data points (0.75%) set to NA
NEE: 325 data points (1.86%) set to NA
-------------------------------------------------------------------
Data filtering:
6048 data points (34.52%) excluded by growing season filter
2575 additional data points (14.7%) excluded by precipitation filter (4140
 data points = 23.63 % in total)
8623 data points (49.22%) excluded in total
8897 valid data points (50.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 131 data points (0.75%) set to NA
NEE: 325 data points (1.86%) set to NA
-------------------------------------------------------------------
Data filtering:
6048 data points (34.52%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6048 data points (34.52%) excluded in total
11472 valid data points (65.48%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -70, -63, -53, -50 ...”
New sEddyProc class for site 'IT-BFt'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -70, -63, -53, -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-BFt-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 0 data points (0%) set to NA
LE: 28 data points (0.16%) set to NA
NEE: 300 data points (1.71%) set to NA
-------------------------------------------------------------------
Data filtering:
5904 data points (33.7%) excluded by growing season filter
1941 additional data points (11.08%) excluded by precipitation filter (3067
 data points = 17.51 % in total)
7845 data points (44.78%) excluded in total
9675 valid data points (55.22%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 0 data points (0%) set to NA
LE: 28 data points (0.16%) set to NA
NEE: 300 data points (1.71%) set to NA
-------------------------------------------------------------------
Data filtering:
5904 data points (33.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5904 data points (33.7%) excluded in total
11616 valid data points (66.3%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -64, -55, -62 ...”
New sEddyProc class for site 'IT-BFt'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -64, -55, -62 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-BFt-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 17518 data points (99.99%) set to NA
H: 17520 data points (100%) set to NA
LE: 17519 data points (99.99%) set to NA
NEE: 17520 data points (100%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5688 additional data points (32.47%) excluded by precipitation filter (5688
 data points = 32.47 % in total)
5688 data points (32.47%) excluded in total
11832 valid data points (67.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 17518 data points (99.99%) set to NA
H: 17520 data points (100%) set to NA
LE: 17519 data points (99.99%) set to NA
NEE: 17520 data points (100%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'IT-BFt'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

  REddyProc error for IT-BFt-2023: sMRFluxPartition:::sRegrE0fromShortTerm:::fCheckColNum::: Detected following columns in dataset to be non numeric: FP_VARnight! First occurence of non-numeric value at column 'FP_VARnight' at row NA is 'NA'.

Quality control:
TA: 0 data points (0%) set to NA
H: 190 data points (1.08%) set to NA
LE: 192 data points (1.09%) set to NA
NEE: 406 data points (2.31%) set to NA
-------------------------------------------------------------------
Data filtering:
5952 data points (33.88%) excluded by growing season filter
2838 additional data points (16.15%) excluded by precipitation filter (4293
 data points = 24.44 % in total)
8790 data points (50.03%) excluded in total
8778 valid data points (49.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 190 data points (1.08%) set to NA
LE: 192 data points (1.09%) set to NA
NEE: 406 data points (2.31%) set to NA
-------------------------------------------------------------------
Data filtering:
5952 data points (33.88%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5952 data points (33.88%) excluded in total
11616 valid data points (66.12%) remaining.

New sEddyProc class for site 'IT-BFt'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-BFt-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[144/329] Processing: IT-BsB

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: IT-BsB | Years: 2021, 2022, 2023, 2024
Quality control:
TA: 4290 data points (24.49%) set to NA
H: 4567 data points (26.07%) set to NA
LE: 4564 data points (26.05%) set to NA
NEE: 6284 data points (35.87%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 76”

-------------------------------------------------------------------
Data filtering:
9024 data points (51.51%) excluded by growing season filter
3196 additional data points (18.24%) excluded by precipitation filter (4869
 data points = 27.79 % in total)
12220 data points (69.75%) excluded in total
5300 valid data points (30.25%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4290 data points (24.49%) set to NA
H: 4567 data points (26.07%) set to NA
LE: 4564 data points (26.05%) set to NA
NEE: 6284 data points (35.87%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 76”

-------------------------------------------------------------------
Data filtering:
9024 data points (51.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9024 data points (51.51%) excluded in total
8496 valid data points (48.49%) remaining.

New sEddyProc class for site 'IT-BsB'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 174.89.

Regression of reference temperature R_ref for 15 periods.

Quality control:
TA: 145 data points (0.83%) set to NA
H: 911 data points (5.2%) set to NA
LE: 912 data points (5.21%) set to NA
NEE: 5487 data points (31.32%) set to NA
-------------------------------------------------------------------
Data filtering:
8448 data points (48.22%) excluded by growing season filter
2693 additional data points (15.37%) excluded by precipitation filter (4209
 data points = 24.02 % in total)
11141 data points (63.59%) excluded in total
6379 valid data points (36.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 145 data points (0.83%) set to NA
H: 911 data points (5.2%) set to NA
LE: 912 data points (5.21%) set to NA
NEE: 5487 data points (31.32%) set to NA
-------------------------------------------------------------------
Data filtering:
8448 data points (48.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8448 data points (48.22%) excluded in total
9072 valid data points (51.78%) remaining.

New sEddyProc class for site 'IT-BsB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-BsB-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 180 data points (1.03%) set to NA
H: 287 data points (1.64%) set to NA
LE: 1243 data points (7.09%) set to NA
NEE: 6541 data points (37.33%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.15%) excluded by growing season filter
3079 additional data points (17.57%) excluded by precipitation filter (5484
 data points = 31.3 % in total)
12391 data points (70.72%) excluded in total
5129 valid data points (29.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 180 data points (1.03%) set to NA
H: 287 data points (1.64%) set to NA
LE: 1243 data points (7.09%) set to NA
NEE: 6541 data points (37.33%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9312 data points (53.15%) excluded in total
8208 valid data points (46.85%) remaining.

New sEddyProc class for site 'IT-BsB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-BsB-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 868 data points (4.94%) set to NA
LE: 835 data points (4.75%) set to NA
NEE: 6393 data points (36.39%) set to NA
-------------------------------------------------------------------
Data filtering:
9168 data points (52.19%) excluded by growing season filter
3207 additional data points (18.25%) excluded by precipitation filter (6040
 data points = 34.38 % in total)
12375 data points (70.44%) excluded in total
5193 valid data points (29.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 868 data points (4.94%) set to NA
LE: 835 data points (4.75%) set to NA
NEE: 6393 data points (36.39%) set to NA
-------------------------------------------------------------------
Data filtering:
9168 data points (52.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9168 data points (52.19%) excluded in total
8400 valid data points (47.81%) remaining.

New sEddyProc class for site 'IT-BsB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-BsB-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[145/329] Processing: IT-Cp2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: IT-Cp2 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 663 data points (3.78%) set to NA
H: 8742 data points (49.9%) set to NA
LE: 10913 data points (62.29%) set to NA
NEE: 11110 data points (63.41%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 184”

-------------------------------------------------------------------
Data filtering:
816 data points (4.66%) excluded by growing season filter
5512 additional data points (31.46%) excluded by precipitation filter (5834
 data points = 33.3 % in total)
6328 data points (36.12%) excluded in total
11192 valid data points (63.88%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 663 data points (3.78%) set to NA
H: 8742 data points (49.9%) set to NA
LE: 10913 data points (62.29%) set to NA
NEE: 11110 data points (63.41%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 184”

-------------------------------------------------------------------
Data filtering:
816 data points (4.66%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
816 data points (4.66%) excluded in total
16704 valid data points (95.34%) remaining.

New sEddyProc class for site 'IT-Cp2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 286.79.

Regression of reference temperature R_ref for 5 periods.

Quality control:
TA: 4988 data points (28.47%) set to NA
H: 10910 data points (62.27%) set to NA
LE: 10997 data points (62.77%) set to NA
NEE: 11117 data points (63.45%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7668 additional data points (43.77%) excluded by precipitation filter (7668
 data points = 43.77 % in total)
7668 data points (43.77%) excluded in total
9852 valid data points (56.23%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4988 data points (28.47%) set to NA
H: 10910 data points (62.27%) set to NA
LE: 10997 data points (62.77%) set to NA
NEE: 11117 data points (63.45%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'IT-Cp2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 8 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Cp2-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 14849 data points (84.75%) set to NA
H: 428 data points (2.44%) set to NA
LE: 779 data points (4.45%) set to NA
NEE: 1202 data points (6.86%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7651 additional data points (43.67%) excluded by precipitation filter (7651
 data points = 43.67 % in total)
7651 data points (43.67%) excluded in total
9869 valid data points (56.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 14849 data points (84.75%) set to NA
H: 428 data points (2.44%) set to NA
LE: 779 data points (4.45%) set to NA
NEE: 1202 data points (6.86%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -52, -65 ...”
New sEddyProc class for site 'IT-Cp2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -52, -65 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Cp2-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2459 data points (14%) set to NA
H: 2631 data points (14.98%) set to NA
LE: 2634 data points (14.99%) set to NA
NEE: 2878 data points (16.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 43”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6449 additional data points (36.71%) excluded by precipitation filter (6449
 data points = 36.71 % in total)
6449 data points (36.71%) excluded in total
11119 valid data points (63.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2459 data points (14%) set to NA
H: 2631 data points (14.98%) set to NA
LE: 2634 data points (14.99%) set to NA
NEE: 2878 data points (16.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 43”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'IT-Cp2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Cp2-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 7871 data points (44.93%) set to NA
H: 8100 data points (46.23%) set to NA
LE: 8093 data points (46.19%) set to NA
NEE: 8215 data points (46.89%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 134”

-------------------------------------------------------------------
Data filtering:
288 data points (1.64%) excluded by growing season filter
5936 additional data points (33.88%) excluded by precipitation filter (6224
 data points = 35.53 % in total)
6224 data points (35.53%) excluded in total
11296 valid data points (64.47%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7871 data points (44.93%) set to NA
H: 8100 data points (46.23%) set to NA
LE: 8093 data points (46.19%) set to NA
NEE: 8215 data points (46.89%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 134”

-------------------------------------------------------------------
Data filtering:
288 data points (1.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
288 data points (1.64%) excluded in total
17232 valid data points (98.36%) remaining.

New sEddyProc class for site 'IT-Cp2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Cp2-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1079 data points (6.16%) set to NA
H: 4099 data points (23.4%) set to NA
LE: 4198 data points (23.96%) set to NA
NEE: 4308 data points (24.59%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 19”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9260 additional data points (52.85%) excluded by precipitation filter (9260
 data points = 52.85 % in total)
9260 data points (52.85%) excluded in total
8260 valid data points (47.15%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1079 data points (6.16%) set to NA
H: 4099 data points (23.4%) set to NA
LE: 4198 data points (23.96%) set to NA
NEE: 4308 data points (24.59%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 19”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'IT-Cp2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Cp2-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 426 data points (2.43%) set to NA
H: 1057 data points (6.03%) set to NA
LE: 2080 data points (11.87%) set to NA
NEE: 2134 data points (12.18%) set to NA
-------------------------------------------------------------------
Data filtering:
4464 data points (25.48%) excluded by growing season filter
8960 additional data points (51.14%) excluded by precipitation filter (11985
 data points = 68.41 % in total)
13424 data points (76.62%) excluded in total
4096 valid data points (23.38%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 426 data points (2.43%) set to NA
H: 1057 data points (6.03%) set to NA
LE: 2080 data points (11.87%) set to NA
NEE: 2134 data points (12.18%) set to NA
-------------------------------------------------------------------
Data filtering:
4464 data points (25.48%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4464 data points (25.48%) excluded in total
13056 valid data points (74.52%) remaining.

New sEddyProc class for site 'IT-Cp2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Cp2-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 9905 data points (56.38%) set to NA
H: 489 data points (2.78%) set to NA
LE: 3148 data points (17.92%) set to NA
NEE: 3450 data points (19.64%) set to NA
-------------------------------------------------------------------
Data filtering:
3936 data points (22.4%) excluded by growing season filter
5708 additional data points (32.49%) excluded by precipitation filter (8242
 data points = 46.91 % in total)
9644 data points (54.9%) excluded in total
7924 valid data points (45.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9905 data points (56.38%) set to NA
H: 489 data points (2.78%) set to NA
LE: 3148 data points (17.92%) set to NA
NEE: 3450 data points (19.64%) set to NA
-------------------------------------------------------------------
Data filtering:
3936 data points (22.4%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3936 data points (22.4%) excluded in total
13632 valid data points (77.6%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -54, -54, -54, -54, -54, -54, -51, -57, -58 ...”
New sEddyProc class for site 'IT-Cp2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -54, -54, -54, -54, -54, -54, -51, -57, -58 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Cp2-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[146/329] Processing: IT-Lav

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: IT-Lav | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 398 data points (2.27%) set to NA
H: 1659 data points (9.47%) set to NA
LE: 1659 data points (9.47%) set to NA
NEE: 1744 data points (9.95%) set to NA
-------------------------------------------------------------------
Data filtering:
3936 data points (22.47%) excluded by growing season filter
3649 additional data points (20.83%) excluded by precipitation filter (4514
 data points = 25.76 % in total)
7585 data points (43.29%) excluded in total
9935 valid data points (56.71%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 398 data points (2.27%) set to NA
H: 1659 data points (9.47%) set to NA
LE: 1659 data points (9.47%) set to NA
NEE: 1744 data points (9.95%) set to NA
-------------------------------------------------------------------
Data filtering:
3936 data points (22.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3936 data points (22.47%) excluded in total
13584 valid data points (77.53%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -61, -57, -53, -68 ...”
New sEddyProc class for site 'IT-Lav'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -61, -57, -53, -68 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Lav-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1956 data points (11.16%) set to NA
LE: 1989 data points (11.35%) set to NA
NEE: 2173 data points (12.4%) set to NA
-------------------------------------------------------------------
Data filtering:
2736 data points (15.62%) excluded by growing season filter
5697 additional data points (32.52%) excluded by precipitation filter (6431
 data points = 36.71 % in total)
8433 data points (48.13%) excluded in total
9087 valid data points (51.87%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1956 data points (11.16%) set to NA
LE: 1989 data points (11.35%) set to NA
NEE: 2173 data points (12.4%) set to NA
-------------------------------------------------------------------
Data filtering:
2736 data points (15.62%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2736 data points (15.62%) excluded in total
14784 valid data points (84.38%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 6 cases! Invalid values with 'NEE < -50': -61, -60, -53, -53, -51, -53 ...”
New sEddyProc class for site 'IT-Lav'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 6 cases! Invalid values with 'NEE < -50': -61, -60, -53, -53, -51, -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Lav-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 949 data points (5.42%) set to NA
LE: 979 data points (5.59%) set to NA
NEE: 1109 data points (6.33%) set to NA
-------------------------------------------------------------------
Data filtering:
4656 data points (26.58%) excluded by growing season filter
5317 additional data points (30.35%) excluded by precipitation filter (6670
 data points = 38.07 % in total)
9973 data points (56.92%) excluded in total
7547 valid data points (43.08%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 949 data points (5.42%) set to NA
LE: 979 data points (5.59%) set to NA
NEE: 1109 data points (6.33%) set to NA
-------------------------------------------------------------------
Data filtering:
4656 data points (26.58%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4656 data points (26.58%) excluded in total
12864 valid data points (73.42%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -54, -50, -55, -52, -53 ...”
New sEddyProc class for site 'IT-Lav'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -54, -50, -55, -52, -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Lav-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 16 data points (0.09%) set to NA
LE: 25 data points (0.14%) set to NA
NEE: 151 data points (0.86%) set to NA
-------------------------------------------------------------------
Data filtering:
3888 data points (22.13%) excluded by growing season filter
4123 additional data points (23.47%) excluded by precipitation filter (4941
 data points = 28.12 % in total)
8011 data points (45.6%) excluded in total
9557 valid data points (54.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 16 data points (0.09%) set to NA
LE: 25 data points (0.14%) set to NA
NEE: 151 data points (0.86%) set to NA
-------------------------------------------------------------------
Data filtering:
3888 data points (22.13%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3888 data points (22.13%) excluded in total
13680 valid data points (77.87%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -69, -62, -50, -50, -51 ...”
New sEddyProc class for site 'IT-Lav'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -69, -62, -50, -50, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Lav-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[147/329] Processing: IT-Lsn

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: IT-Lsn | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 32 data points (0.18%) set to NA
LE: 41 data points (0.23%) set to NA
NEE: 399 data points (2.28%) set to NA
-------------------------------------------------------------------
Data filtering:
9600 data points (54.79%) excluded by growing season filter
2930 additional data points (16.72%) excluded by precipitation filter (5113
 data points = 29.18 % in total)
12530 data points (71.52%) excluded in total
4990 valid data points (28.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 32 data points (0.18%) set to NA
LE: 41 data points (0.23%) set to NA
NEE: 399 data points (2.28%) set to NA
-------------------------------------------------------------------
Data filtering:
9600 data points (54.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9600 data points (54.79%) excluded in total
7920 valid data points (45.21%) remaining.

New sEddyProc class for site 'IT-Lsn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Lsn-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 21 data points (0.12%) set to NA
LE: 28 data points (0.16%) set to NA
NEE: 307 data points (1.75%) set to NA
-------------------------------------------------------------------
Data filtering:
8160 data points (46.58%) excluded by growing season filter
2975 additional data points (16.98%) excluded by precipitation filter (5644
 data points = 32.21 % in total)
11135 data points (63.56%) excluded in total
6385 valid data points (36.44%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 21 data points (0.12%) set to NA
LE: 28 data points (0.16%) set to NA
NEE: 307 data points (1.75%) set to NA
-------------------------------------------------------------------
Data filtering:
8160 data points (46.58%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8160 data points (46.58%) excluded in total
9360 valid data points (53.42%) remaining.

New sEddyProc class for site 'IT-Lsn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Lsn-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 947 data points (5.41%) set to NA
LE: 945 data points (5.39%) set to NA
NEE: 1384 data points (7.9%) set to NA
-------------------------------------------------------------------
Data filtering:
6960 data points (39.73%) excluded by growing season filter
4177 additional data points (23.84%) excluded by precipitation filter (6422
 data points = 36.66 % in total)
11137 data points (63.57%) excluded in total
6383 valid data points (36.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 947 data points (5.41%) set to NA
LE: 945 data points (5.39%) set to NA
NEE: 1384 data points (7.9%) set to NA
-------------------------------------------------------------------
Data filtering:
6960 data points (39.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6960 data points (39.73%) excluded in total
10560 valid data points (60.27%) remaining.

New sEddyProc class for site 'IT-Lsn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Lsn-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2835 data points (16.14%) set to NA
LE: 2836 data points (16.14%) set to NA
NEE: 3229 data points (18.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 19”

-------------------------------------------------------------------
Data filtering:
7584 data points (43.17%) excluded by growing season filter
3228 additional data points (18.37%) excluded by precipitation filter (5123
 data points = 29.16 % in total)
10812 data points (61.54%) excluded in total
6756 valid data points (38.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2835 data points (16.14%) set to NA
LE: 2836 data points (16.14%) set to NA
NEE: 3229 data points (18.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 19”

-------------------------------------------------------------------
Data filtering:
7584 data points (43.17%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7584 data points (43.17%) excluded in total
9984 valid data points (56.83%) remaining.

New sEddyProc class for site 'IT-Lsn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Lsn-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 6953 data points (39.69%) set to NA
LE: 7170 data points (40.92%) set to NA
NEE: 7728 data points (44.11%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 67”

-------------------------------------------------------------------
Data filtering:
5664 data points (32.33%) excluded by growing season filter
4342 additional data points (24.78%) excluded by precipitation filter (6155
 data points = 35.13 % in total)
10006 data points (57.11%) excluded in total
7514 valid data points (42.89%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 6953 data points (39.69%) set to NA
LE: 7170 data points (40.92%) set to NA
NEE: 7728 data points (44.11%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 67”

-------------------------------------------------------------------
Data filtering:
5664 data points (32.33%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5664 data points (32.33%) excluded in total
11856 valid data points (67.67%) remaining.

New sEddyProc class for site 'IT-Lsn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Lsn-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 28 data points (0.16%) set to NA
LE: 27 data points (0.15%) set to NA
NEE: 295 data points (1.68%) set to NA
-------------------------------------------------------------------
Data filtering:
9552 data points (54.52%) excluded by growing season filter
2620 additional data points (14.95%) excluded by precipitation filter (4678
 data points = 26.7 % in total)
12172 data points (69.47%) excluded in total
5348 valid data points (30.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 28 data points (0.16%) set to NA
LE: 27 data points (0.15%) set to NA
NEE: 295 data points (1.68%) set to NA
-------------------------------------------------------------------
Data filtering:
9552 data points (54.52%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9552 data points (54.52%) excluded in total
7968 valid data points (45.48%) remaining.

New sEddyProc class for site 'IT-Lsn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Lsn-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1110 data points (6.34%) set to NA
LE: 1118 data points (6.38%) set to NA
NEE: 2619 data points (14.95%) set to NA
-------------------------------------------------------------------
Data filtering:
8256 data points (47.12%) excluded by growing season filter
4129 additional data points (23.57%) excluded by precipitation filter (6036
 data points = 34.45 % in total)
12385 data points (70.69%) excluded in total
5135 valid data points (29.31%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1110 data points (6.34%) set to NA
LE: 1118 data points (6.38%) set to NA
NEE: 2619 data points (14.95%) set to NA
-------------------------------------------------------------------
Data filtering:
8256 data points (47.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8256 data points (47.12%) excluded in total
9264 valid data points (52.88%) remaining.

New sEddyProc class for site 'IT-Lsn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Lsn-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 98 data points (0.56%) set to NA
LE: 94 data points (0.54%) set to NA
NEE: 1138 data points (6.48%) set to NA
-------------------------------------------------------------------
Data filtering:
6048 data points (34.43%) excluded by growing season filter
3945 additional data points (22.46%) excluded by precipitation filter (5780
 data points = 32.9 % in total)
9993 data points (56.88%) excluded in total
7575 valid data points (43.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 98 data points (0.56%) set to NA
LE: 94 data points (0.54%) set to NA
NEE: 1138 data points (6.48%) set to NA
-------------------------------------------------------------------
Data filtering:
6048 data points (34.43%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6048 data points (34.43%) excluded in total
11520 valid data points (65.57%) remaining.

New sEddyProc class for site 'IT-Lsn'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Lsn-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[148/329] Processing: IT-Noe

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: IT-Noe | Years: 2022, 2023, 2024
Quality control:
TA: 12759 data points (72.83%) set to NA
H: 12766 data points (72.87%) set to NA
LE: 13698 data points (78.18%) set to NA
NEE: 13755 data points (78.51%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4555 additional data points (26%) excluded by precipitation filter (4555
 data points = 26 % in total)
4555 data points (26%) excluded in total
12965 valid data points (74%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12759 data points (72.83%) set to NA
H: 12766 data points (72.87%) set to NA
LE: 13698 data points (78.18%) set to NA
NEE: 13755 data points (78.51%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'IT-Noe'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 80.66.

Regression of reference temperature R_ref for 16 periods.

Quality control:
TA: 1955 data points (11.16%) set to NA
H: 322 data points (1.84%) set to NA
LE: 412 data points (2.35%) set to NA
NEE: 1045 data points (5.96%) set to NA
-------------------------------------------------------------------
Data filtering:
2352 data points (13.42%) excluded by growing season filter
4492 additional data points (25.64%) excluded by precipitation filter (4830
 data points = 27.57 % in total)
6844 data points (39.06%) excluded in total
10676 valid data points (60.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1955 data points (11.16%) set to NA
H: 322 data points (1.84%) set to NA
LE: 412 data points (2.35%) set to NA
NEE: 1045 data points (5.96%) set to NA
-------------------------------------------------------------------
Data filtering:
2352 data points (13.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2352 data points (13.42%) excluded in total
15168 valid data points (86.58%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
New sEddyProc class for site 'IT-Noe'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 124.49.

Regression of reference temperature R_ref for 12 periods.

Quality control:
TA: 2001 data points (11.39%) set to NA
H: 69 data points (0.39%) set to NA
LE: 158 data points (0.9%) set to NA
NEE: 1049 data points (5.97%) set to NA
-------------------------------------------------------------------
Data filtering:
3072 data points (17.49%) excluded by growing season filter
4146 additional data points (23.6%) excluded by precipitation filter (4940
 data points = 28.12 % in total)
7218 data points (41.09%) excluded in total
10350 valid data points (58.91%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2001 data points (11.39%) set to NA
H: 69 data points (0.39%) set to NA
LE: 158 data points (0.9%) set to NA
NEE: 1049 data points (5.97%) set to NA
-------------------------------------------------------------------
Data filtering:
3072 data points (17.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3072 data points (17.49%) excluded in total
14496 valid data points (82.51%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -58, -68, -59, -51, -55, -60, -62, -59 ...”
New sEddyProc class for site 'IT-Noe'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -58, -68, -59, -51, -55, -60, -62, -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 144.32.

Regression of reference temperature R_ref for 12 periods.

[149/329] Processing: IT-Ren

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: IT-Ren | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 8 data points (0.05%) set to NA
LE: 2 data points (0.01%) set to NA
NEE: 1644 data points (9.38%) set to NA
-------------------------------------------------------------------
Data filtering:
7392 data points (42.19%) excluded by growing season filter
3894 additional data points (22.23%) excluded by precipitation filter (5831
 data points = 33.28 % in total)
11286 data points (64.42%) excluded in total
6234 valid data points (35.58%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 8 data points (0.05%) set to NA
LE: 2 data points (0.01%) set to NA
NEE: 1644 data points (9.38%) set to NA
-------------------------------------------------------------------
Data filtering:
7392 data points (42.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7392 data points (42.19%) excluded in total
10128 valid data points (57.81%) remaining.

New sEddyProc class for site 'IT-Ren'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Ren-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2059 data points (11.75%) set to NA
LE: 2064 data points (11.78%) set to NA
NEE: 2959 data points (16.89%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
4194 additional data points (23.94%) excluded by precipitation filter (7603
 data points = 43.4 % in total)
13554 data points (77.36%) excluded in total
3966 valid data points (22.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2059 data points (11.75%) set to NA
LE: 2064 data points (11.78%) set to NA
NEE: 2959 data points (16.89%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9360 data points (53.42%) excluded in total
8160 valid data points (46.58%) remaining.

New sEddyProc class for site 'IT-Ren'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Ren-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 508 data points (2.9%) set to NA
LE: 512 data points (2.92%) set to NA
NEE: 3749 data points (21.4%) set to NA
-------------------------------------------------------------------
Data filtering:
7392 data points (42.19%) excluded by growing season filter
5379 additional data points (30.7%) excluded by precipitation filter (7802
 data points = 44.53 % in total)
12771 data points (72.89%) excluded in total
4749 valid data points (27.11%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 508 data points (2.9%) set to NA
LE: 512 data points (2.92%) set to NA
NEE: 3749 data points (21.4%) set to NA
-------------------------------------------------------------------
Data filtering:
7392 data points (42.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7392 data points (42.19%) excluded in total
10128 valid data points (57.81%) remaining.

New sEddyProc class for site 'IT-Ren'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Ren-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 43 data points (0.24%) set to NA
H: 84 data points (0.48%) set to NA
LE: 67 data points (0.38%) set to NA
NEE: 6109 data points (34.77%) set to NA
-------------------------------------------------------------------
Data filtering:
7056 data points (40.16%) excluded by growing season filter
5969 additional data points (33.98%) excluded by precipitation filter (8481
 data points = 48.28 % in total)
13025 data points (74.14%) excluded in total
4543 valid data points (25.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 43 data points (0.24%) set to NA
H: 84 data points (0.48%) set to NA
LE: 67 data points (0.38%) set to NA
NEE: 6109 data points (34.77%) set to NA
-------------------------------------------------------------------
Data filtering:
7056 data points (40.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7056 data points (40.16%) excluded in total
10512 valid data points (59.84%) remaining.

New sEddyProc class for site 'IT-Ren'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Ren-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 17518 data points (99.99%) set to NA
H: 17519 data points (99.99%) set to NA
LE: 17519 data points (99.99%) set to NA
NEE: 17520 data points (100%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8367 additional data points (47.76%) excluded by precipitation filter (8367
 data points = 47.76 % in total)
8367 data points (47.76%) excluded in total
9153 valid data points (52.24%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for IT-Ren-2021”

Quality control:
TA: 600 data points (3.42%) set to NA
H: 63 data points (0.36%) set to NA
LE: 2121 data points (12.11%) set to NA
NEE: 2812 data points (16.05%) set to NA
-------------------------------------------------------------------
Data filtering:
7152 data points (40.82%) excluded by growing season filter
4503 additional data points (25.7%) excluded by precipitation filter (5925
 data points = 33.82 % in total)
11655 data points (66.52%) excluded in total
5865 valid data points (33.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 600 data points (3.42%) set to NA
H: 63 data points (0.36%) set to NA
LE: 2121 data points (12.11%) set to NA
NEE: 2812 data points (16.05%) set to NA
-------------------------------------------------------------------
Data filtering:
7152 data points (40.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7152 data points (40.82%) excluded in total
10368 valid data points (59.18%) remaining.

New sEddyProc class for site 'IT-Ren'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Ren-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 23 data points (0.13%) set to NA
H: 123 data points (0.7%) set to NA
LE: 6063 data points (34.61%) set to NA
NEE: 7260 data points (41.44%) set to NA
-------------------------------------------------------------------
Data filtering:
4320 data points (24.66%) excluded by growing season filter
4782 additional data points (27.29%) excluded by precipitation filter (6513
 data points = 37.17 % in total)
9102 data points (51.95%) excluded in total
8418 valid data points (48.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 23 data points (0.13%) set to NA
H: 123 data points (0.7%) set to NA
LE: 6063 data points (34.61%) set to NA
NEE: 7260 data points (41.44%) set to NA
-------------------------------------------------------------------
Data filtering:
4320 data points (24.66%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4320 data points (24.66%) excluded in total
13200 valid data points (75.34%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 124 cases! Invalid values with 'NEE < -50': -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65 ...”
New sEddyProc class for site 'IT-Ren'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 124 cases! Invalid values with 'NEE < -50': -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65, -65 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Ren-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4553 data points (25.92%) set to NA
H: 113 data points (0.64%) set to NA
LE: 107 data points (0.61%) set to NA
NEE: 1187 data points (6.76%) set to NA
-------------------------------------------------------------------
Data filtering:
5472 data points (31.15%) excluded by growing season filter
4612 additional data points (26.25%) excluded by precipitation filter (5955
 data points = 33.9 % in total)
10084 data points (57.4%) excluded in total
7484 valid data points (42.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4553 data points (25.92%) set to NA
H: 113 data points (0.64%) set to NA
LE: 107 data points (0.61%) set to NA
NEE: 1187 data points (6.76%) set to NA
-------------------------------------------------------------------
Data filtering:
5472 data points (31.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5472 data points (31.15%) excluded in total
12096 valid data points (68.85%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
New sEddyProc class for site 'IT-Ren'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-Ren-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[150/329] Processing: IT-SR2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: IT-SR2 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 78 data points (0.45%) set to NA
H: 1451 data points (8.28%) set to NA
LE: 1472 data points (8.4%) set to NA
NEE: 2155 data points (12.3%) set to NA
-------------------------------------------------------------------
Data filtering:
2544 data points (14.52%) excluded by growing season filter
4355 additional data points (24.86%) excluded by precipitation filter (5379
 data points = 30.7 % in total)
6899 data points (39.38%) excluded in total
10621 valid data points (60.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 78 data points (0.45%) set to NA
H: 1451 data points (8.28%) set to NA
LE: 1472 data points (8.4%) set to NA
NEE: 2155 data points (12.3%) set to NA
-------------------------------------------------------------------
Data filtering:
2544 data points (14.52%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2544 data points (14.52%) excluded in total
14976 valid data points (85.48%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
New sEddyProc class for site 'IT-SR2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-SR2-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 195 data points (1.11%) set to NA
H: 204 data points (1.16%) set to NA
LE: 203 data points (1.16%) set to NA
NEE: 944 data points (5.39%) set to NA
-------------------------------------------------------------------
Data filtering:
3024 data points (17.26%) excluded by growing season filter
5466 additional data points (31.2%) excluded by precipitation filter (6924
 data points = 39.52 % in total)
8490 data points (48.46%) excluded in total
9030 valid data points (51.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 195 data points (1.11%) set to NA
H: 204 data points (1.16%) set to NA
LE: 203 data points (1.16%) set to NA
NEE: 944 data points (5.39%) set to NA
-------------------------------------------------------------------
Data filtering:
3024 data points (17.26%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3024 data points (17.26%) excluded in total
14496 valid data points (82.74%) remaining.

New sEddyProc class for site 'IT-SR2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-SR2-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 335 data points (1.91%) set to NA
H: 659 data points (3.76%) set to NA
LE: 1362 data points (7.77%) set to NA
NEE: 3713 data points (21.19%) set to NA
-------------------------------------------------------------------
Data filtering:
2976 data points (16.99%) excluded by growing season filter
4806 additional data points (27.43%) excluded by precipitation filter (6482
 data points = 37 % in total)
7782 data points (44.42%) excluded in total
9738 valid data points (55.58%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 335 data points (1.91%) set to NA
H: 659 data points (3.76%) set to NA
LE: 1362 data points (7.77%) set to NA
NEE: 3713 data points (21.19%) set to NA
-------------------------------------------------------------------
Data filtering:
2976 data points (16.99%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2976 data points (16.99%) excluded in total
14544 valid data points (83.01%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
New sEddyProc class for site 'IT-SR2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-SR2-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 945 data points (5.38%) set to NA
H: 376 data points (2.14%) set to NA
LE: 5037 data points (28.67%) set to NA
NEE: 5757 data points (32.77%) set to NA
-------------------------------------------------------------------
Data filtering:
3168 data points (18.03%) excluded by growing season filter
5164 additional data points (29.39%) excluded by precipitation filter (7083
 data points = 40.32 % in total)
8332 data points (47.43%) excluded in total
9236 valid data points (52.57%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 945 data points (5.38%) set to NA
H: 376 data points (2.14%) set to NA
LE: 5037 data points (28.67%) set to NA
NEE: 5757 data points (32.77%) set to NA
-------------------------------------------------------------------
Data filtering:
3168 data points (18.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3168 data points (18.03%) excluded in total
14400 valid data points (81.97%) remaining.

New sEddyProc class for site 'IT-SR2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 223.88.

Regression of reference temperature R_ref for 14 periods.

Quality control:
TA: 1651 data points (9.42%) set to NA
H: 245 data points (1.4%) set to NA
LE: 492 data points (2.81%) set to NA
NEE: 1663 data points (9.49%) set to NA
-------------------------------------------------------------------
Data filtering:
4080 data points (23.29%) excluded by growing season filter
3326 additional data points (18.98%) excluded by precipitation filter (5937
 data points = 33.89 % in total)
7406 data points (42.27%) excluded in total
10114 valid data points (57.73%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1651 data points (9.42%) set to NA
H: 245 data points (1.4%) set to NA
LE: 492 data points (2.81%) set to NA
NEE: 1663 data points (9.49%) set to NA
-------------------------------------------------------------------
Data filtering:
4080 data points (23.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4080 data points (23.29%) excluded in total
13440 valid data points (76.71%) remaining.

New sEddyProc class for site 'IT-SR2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-SR2-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 641 data points (3.66%) set to NA
H: 184 data points (1.05%) set to NA
LE: 117 data points (0.67%) set to NA
NEE: 1001 data points (5.71%) set to NA
-------------------------------------------------------------------
Data filtering:
1440 data points (8.22%) excluded by growing season filter
4785 additional data points (27.31%) excluded by precipitation filter (5747
 data points = 32.8 % in total)
6225 data points (35.53%) excluded in total
11295 valid data points (64.47%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 641 data points (3.66%) set to NA
H: 184 data points (1.05%) set to NA
LE: 117 data points (0.67%) set to NA
NEE: 1001 data points (5.71%) set to NA
-------------------------------------------------------------------
Data filtering:
1440 data points (8.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1440 data points (8.22%) excluded in total
16080 valid data points (91.78%) remaining.

New sEddyProc class for site 'IT-SR2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 266.58.

Regression of reference temperature R_ref for 15 periods.

Quality control:
TA: 1253 data points (7.15%) set to NA
H: 3392 data points (19.36%) set to NA
LE: 3362 data points (19.19%) set to NA
NEE: 4099 data points (23.4%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6290 additional data points (35.9%) excluded by precipitation filter (6290
 data points = 35.9 % in total)
6290 data points (35.9%) excluded in total
11230 valid data points (64.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1253 data points (7.15%) set to NA
H: 3392 data points (19.36%) set to NA
LE: 3362 data points (19.19%) set to NA
NEE: 4099 data points (23.4%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'IT-SR2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 219.23.

Regression of reference temperature R_ref for 15 periods.

Quality control:
TA: 5086 data points (28.95%) set to NA
H: 6116 data points (34.81%) set to NA
LE: 8762 data points (49.87%) set to NA
NEE: 8947 data points (50.93%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 71”

-------------------------------------------------------------------
Data filtering:
1584 data points (9.02%) excluded by growing season filter
7435 additional data points (42.32%) excluded by precipitation filter (8270
 data points = 47.07 % in total)
9019 data points (51.34%) excluded in total
8549 valid data points (48.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5086 data points (28.95%) set to NA
H: 6116 data points (34.81%) set to NA
LE: 8762 data points (49.87%) set to NA
NEE: 8947 data points (50.93%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 71”

-------------------------------------------------------------------
Data filtering:
1584 data points (9.02%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1584 data points (9.02%) excluded in total
15984 valid data points (90.98%) remaining.

New sEddyProc class for site 'IT-SR2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-SR2-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[151/329] Processing: IT-TrF

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: IT-TrF | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 281 data points (1.6%) set to NA
H: 328 data points (1.87%) set to NA
LE: 325 data points (1.86%) set to NA
NEE: 438 data points (2.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5589 additional data points (31.9%) excluded by precipitation filter (5589
 data points = 31.9 % in total)
5589 data points (31.9%) excluded in total
11931 valid data points (68.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 281 data points (1.6%) set to NA
H: 328 data points (1.87%) set to NA
LE: 325 data points (1.86%) set to NA
NEE: 438 data points (2.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'IT-TrF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-TrF-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 96 data points (0.55%) set to NA
H: 1215 data points (6.93%) set to NA
LE: 1234 data points (7.04%) set to NA
NEE: 1318 data points (7.52%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8539 additional data points (48.74%) excluded by precipitation filter (8539
 data points = 48.74 % in total)
8539 data points (48.74%) excluded in total
8981 valid data points (51.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 96 data points (0.55%) set to NA
H: 1215 data points (6.93%) set to NA
LE: 1234 data points (7.04%) set to NA
NEE: 1318 data points (7.52%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'IT-TrF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-TrF-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 46 data points (0.26%) set to NA
H: 142 data points (0.81%) set to NA
LE: 154 data points (0.88%) set to NA
NEE: 193 data points (1.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6714 additional data points (38.32%) excluded by precipitation filter (6714
 data points = 38.32 % in total)
6714 data points (38.32%) excluded in total
10806 valid data points (61.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 46 data points (0.26%) set to NA
H: 142 data points (0.81%) set to NA
LE: 154 data points (0.88%) set to NA
NEE: 193 data points (1.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'IT-TrF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-TrF-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 42 data points (0.24%) set to NA
H: 138 data points (0.79%) set to NA
LE: 144 data points (0.82%) set to NA
NEE: 274 data points (1.56%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6334 additional data points (36.05%) excluded by precipitation filter (6334
 data points = 36.05 % in total)
6334 data points (36.05%) excluded in total
11234 valid data points (63.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 42 data points (0.24%) set to NA
H: 138 data points (0.79%) set to NA
LE: 144 data points (0.82%) set to NA
NEE: 274 data points (1.56%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'IT-TrF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-TrF-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 945 data points (5.39%) set to NA
H: 2864 data points (16.35%) set to NA
LE: 2883 data points (16.46%) set to NA
NEE: 3035 data points (17.32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7295 additional data points (41.64%) excluded by precipitation filter (7295
 data points = 41.64 % in total)
7295 data points (41.64%) excluded in total
10225 valid data points (58.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 945 data points (5.39%) set to NA
H: 2864 data points (16.35%) set to NA
LE: 2883 data points (16.46%) set to NA
NEE: 3035 data points (17.32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'IT-TrF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-TrF-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 60 data points (0.34%) set to NA
H: 125 data points (0.71%) set to NA
LE: 142 data points (0.81%) set to NA
NEE: 328 data points (1.87%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6234 additional data points (35.58%) excluded by precipitation filter (6234
 data points = 35.58 % in total)
6234 data points (35.58%) excluded in total
11286 valid data points (64.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 60 data points (0.34%) set to NA
H: 125 data points (0.71%) set to NA
LE: 142 data points (0.81%) set to NA
NEE: 328 data points (1.87%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'IT-TrF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-TrF-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 66 data points (0.38%) set to NA
H: 768 data points (4.38%) set to NA
LE: 789 data points (4.5%) set to NA
NEE: 968 data points (5.53%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7056 additional data points (40.27%) excluded by precipitation filter (7056
 data points = 40.27 % in total)
7056 data points (40.27%) excluded in total
10464 valid data points (59.73%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 66 data points (0.38%) set to NA
H: 768 data points (4.38%) set to NA
LE: 789 data points (4.5%) set to NA
NEE: 968 data points (5.53%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'IT-TrF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-TrF-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 93 data points (0.53%) set to NA
H: 356 data points (2.03%) set to NA
LE: 396 data points (2.25%) set to NA
NEE: 585 data points (3.33%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7390 additional data points (42.07%) excluded by precipitation filter (7390
 data points = 42.07 % in total)
7390 data points (42.07%) excluded in total
10178 valid data points (57.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 93 data points (0.53%) set to NA
H: 356 data points (2.03%) set to NA
LE: 396 data points (2.25%) set to NA
NEE: 585 data points (3.33%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'IT-TrF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for IT-TrF-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[152/329] Processing: JP-Api

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: JP-Api | Years: 2017, 2018, 2019, 2020, 2021, 2022
Quality control:
TA: 0 data points (0%) set to NA
H: 10 data points (0.06%) set to NA
LE: 9 data points (0.05%) set to NA
NEE: 1072 data points (6.12%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
5000 additional data points (28.54%) excluded by precipitation filter (13490
 data points = 77 % in total)
15656 data points (89.36%) excluded in total
1864 valid data points (10.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 10 data points (0.06%) set to NA
LE: 9 data points (0.05%) set to NA
NEE: 1072 data points (6.12%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10656 data points (60.82%) excluded in total
6864 valid data points (39.18%) remaining.

New sEddyProc class for site 'JP-Api'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Api-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 37 data points (0.21%) set to NA
H: 14 data points (0.08%) set to NA
LE: 53 data points (0.3%) set to NA
NEE: 936 data points (5.34%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.27%) excluded by growing season filter
5012 additional data points (28.61%) excluded by precipitation filter (12684
 data points = 72.4 % in total)
15572 data points (88.88%) excluded in total
1948 valid data points (11.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 37 data points (0.21%) set to NA
H: 14 data points (0.08%) set to NA
LE: 53 data points (0.3%) set to NA
NEE: 936 data points (5.34%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10560 data points (60.27%) excluded in total
6960 valid data points (39.73%) remaining.

New sEddyProc class for site 'JP-Api'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Api-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 37 data points (0.21%) set to NA
LE: 41 data points (0.23%) set to NA
NEE: 1150 data points (6.56%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (60%) excluded by growing season filter
4644 additional data points (26.51%) excluded by precipitation filter (12362
 data points = 70.56 % in total)
15156 data points (86.51%) excluded in total
2364 valid data points (13.49%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 37 data points (0.21%) set to NA
LE: 41 data points (0.23%) set to NA
NEE: 1150 data points (6.56%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (60%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10512 data points (60%) excluded in total
7008 valid data points (40%) remaining.

New sEddyProc class for site 'JP-Api'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Api-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 588 data points (3.35%) set to NA
H: 787 data points (4.48%) set to NA
LE: 790 data points (4.5%) set to NA
NEE: 4654 data points (26.49%) set to NA
-------------------------------------------------------------------
Data filtering:
10176 data points (57.92%) excluded by growing season filter
5652 additional data points (32.17%) excluded by precipitation filter (13710
 data points = 78.04 % in total)
15828 data points (90.1%) excluded in total
1740 valid data points (9.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 588 data points (3.35%) set to NA
H: 787 data points (4.48%) set to NA
LE: 790 data points (4.5%) set to NA
NEE: 4654 data points (26.49%) set to NA
-------------------------------------------------------------------
Data filtering:
10176 data points (57.92%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10176 data points (57.92%) excluded in total
7392 valid data points (42.08%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -51 ...”
New sEddyProc class for site 'JP-Api'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Api-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 213 data points (1.22%) set to NA
LE: 213 data points (1.22%) set to NA
NEE: 1385 data points (7.91%) set to NA
-------------------------------------------------------------------
Data filtering:
11568 data points (66.03%) excluded by growing season filter
4810 additional data points (27.45%) excluded by precipitation filter (13094
 data points = 74.74 % in total)
16378 data points (93.48%) excluded in total
1142 valid data points (6.52%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 213 data points (1.22%) set to NA
LE: 213 data points (1.22%) set to NA
NEE: 1385 data points (7.91%) set to NA
-------------------------------------------------------------------
Data filtering:
11568 data points (66.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11568 data points (66.03%) excluded in total
5952 valid data points (33.97%) remaining.

New sEddyProc class for site 'JP-Api'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Api-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 11 data points (0.06%) set to NA
LE: 19 data points (0.11%) set to NA
NEE: 2233 data points (12.75%) set to NA
-------------------------------------------------------------------
Data filtering:
10176 data points (58.08%) excluded by growing season filter
4884 additional data points (27.88%) excluded by precipitation filter (12668
 data points = 72.31 % in total)
15060 data points (85.96%) excluded in total
2460 valid data points (14.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 11 data points (0.06%) set to NA
LE: 19 data points (0.11%) set to NA
NEE: 2233 data points (12.75%) set to NA
-------------------------------------------------------------------
Data filtering:
10176 data points (58.08%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10176 data points (58.08%) excluded in total
7344 valid data points (41.92%) remaining.

New sEddyProc class for site 'JP-Api'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Api-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[153/329] Processing: JP-Tkb

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: JP-Tkb | Years: 2018, 2019
Quality control:
TA: 7035 data points (40.15%) set to NA
H: 7406 data points (42.27%) set to NA
LE: 7406 data points (42.27%) set to NA
NEE: 8201 data points (46.81%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 134”

-------------------------------------------------------------------
Data filtering:
1008 data points (5.75%) excluded by growing season filter
9868 additional data points (56.32%) excluded by precipitation filter (10468
 data points = 59.75 % in total)
10876 data points (62.08%) excluded in total
6644 valid data points (37.92%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7035 data points (40.15%) set to NA
H: 7406 data points (42.27%) set to NA
LE: 7406 data points (42.27%) set to NA
NEE: 8201 data points (46.81%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 134”

-------------------------------------------------------------------
Data filtering:
1008 data points (5.75%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1008 data points (5.75%) excluded in total
16512 valid data points (94.25%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
New sEddyProc class for site 'JP-Tkb'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 272.65.

Regression of reference temperature R_ref for 8 periods.

Quality control:
TA: 9609 data points (54.85%) set to NA
H: 10824 data points (61.78%) set to NA
LE: 10866 data points (62.02%) set to NA
NEE: 11259 data points (64.26%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10870 additional data points (62.04%) excluded by precipitation filter (10870
 data points = 62.04 % in total)
10870 data points (62.04%) excluded in total
6650 valid data points (37.96%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9609 data points (54.85%) set to NA
H: 10824 data points (61.78%) set to NA
LE: 10866 data points (62.02%) set to NA
NEE: 11259 data points (64.26%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'JP-Tkb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Tkb-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[154/329] Processing: JP-Yms

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: JP-Yms | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023
Quality control:
TA: 220 data points (1.26%) set to NA
H: 2523 data points (14.4%) set to NA
LE: 572 data points (3.26%) set to NA
NEE: 4714 data points (26.91%) set to NA
-------------------------------------------------------------------
Data filtering:
6912 data points (39.45%) excluded by growing season filter
6168 additional data points (35.21%) excluded by precipitation filter (10294
 data points = 58.76 % in total)
13080 data points (74.66%) excluded in total
4440 valid data points (25.34%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 220 data points (1.26%) set to NA
H: 2523 data points (14.4%) set to NA
LE: 572 data points (3.26%) set to NA
NEE: 4714 data points (26.91%) set to NA
-------------------------------------------------------------------
Data filtering:
6912 data points (39.45%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6912 data points (39.45%) excluded in total
10608 valid data points (60.55%) remaining.

New sEddyProc class for site 'JP-Yms'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Yms-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 36 data points (0.21%) set to NA
H: 437 data points (2.49%) set to NA
LE: 2426 data points (13.85%) set to NA
NEE: 5718 data points (32.64%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 49”

-------------------------------------------------------------------
Data filtering:
6384 data points (36.44%) excluded by growing season filter
5906 additional data points (33.71%) excluded by precipitation filter (9438
 data points = 53.87 % in total)
12290 data points (70.15%) excluded in total
5230 valid data points (29.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 36 data points (0.21%) set to NA
H: 437 data points (2.49%) set to NA
LE: 2426 data points (13.85%) set to NA
NEE: 5718 data points (32.64%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 49”

-------------------------------------------------------------------
Data filtering:
6384 data points (36.44%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6384 data points (36.44%) excluded in total
11136 valid data points (63.56%) remaining.

New sEddyProc class for site 'JP-Yms'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Yms-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 235 data points (1.34%) set to NA
H: 213 data points (1.22%) set to NA
LE: 1526 data points (8.71%) set to NA
NEE: 2291 data points (13.08%) set to NA
-------------------------------------------------------------------
Data filtering:
8496 data points (48.49%) excluded by growing season filter
5466 additional data points (31.2%) excluded by precipitation filter (9984
 data points = 56.99 % in total)
13962 data points (79.69%) excluded in total
3558 valid data points (20.31%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 235 data points (1.34%) set to NA
H: 213 data points (1.22%) set to NA
LE: 1526 data points (8.71%) set to NA
NEE: 2291 data points (13.08%) set to NA
-------------------------------------------------------------------
Data filtering:
8496 data points (48.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8496 data points (48.49%) excluded in total
9024 valid data points (51.51%) remaining.

New sEddyProc class for site 'JP-Yms'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Yms-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 3 data points (0.02%) set to NA
LE: 1544 data points (8.79%) set to NA
NEE: 3366 data points (19.16%) set to NA
-------------------------------------------------------------------
Data filtering:
10752 data points (61.2%) excluded by growing season filter
3724 additional data points (21.2%) excluded by precipitation filter (10114
 data points = 57.57 % in total)
14476 data points (82.4%) excluded in total
3092 valid data points (17.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 3 data points (0.02%) set to NA
LE: 1544 data points (8.79%) set to NA
NEE: 3366 data points (19.16%) set to NA
-------------------------------------------------------------------
Data filtering:
10752 data points (61.2%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10752 data points (61.2%) excluded in total
6816 valid data points (38.8%) remaining.

New sEddyProc class for site 'JP-Yms'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Yms-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 95 data points (0.54%) set to NA
LE: 746 data points (4.26%) set to NA
NEE: 2520 data points (14.38%) set to NA
-------------------------------------------------------------------
Data filtering:
6912 data points (39.45%) excluded by growing season filter
6522 additional data points (37.23%) excluded by precipitation filter (9688
 data points = 55.3 % in total)
13434 data points (76.68%) excluded in total
4086 valid data points (23.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 95 data points (0.54%) set to NA
LE: 746 data points (4.26%) set to NA
NEE: 2520 data points (14.38%) set to NA
-------------------------------------------------------------------
Data filtering:
6912 data points (39.45%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6912 data points (39.45%) excluded in total
10608 valid data points (60.55%) remaining.

New sEddyProc class for site 'JP-Yms'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Yms-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 133 data points (0.76%) set to NA
LE: 2491 data points (14.22%) set to NA
NEE: 4962 data points (28.32%) set to NA
-------------------------------------------------------------------
Data filtering:
7008 data points (40%) excluded by growing season filter
6158 additional data points (35.15%) excluded by precipitation filter (9860
 data points = 56.28 % in total)
13166 data points (75.15%) excluded in total
4354 valid data points (24.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 133 data points (0.76%) set to NA
LE: 2491 data points (14.22%) set to NA
NEE: 4962 data points (28.32%) set to NA
-------------------------------------------------------------------
Data filtering:
7008 data points (40%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7008 data points (40%) excluded in total
10512 valid data points (60%) remaining.

New sEddyProc class for site 'JP-Yms'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Yms-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 174 data points (0.99%) set to NA
LE: 558 data points (3.18%) set to NA
NEE: 2782 data points (15.88%) set to NA
-------------------------------------------------------------------
Data filtering:
7296 data points (41.64%) excluded by growing season filter
5876 additional data points (33.54%) excluded by precipitation filter (9328
 data points = 53.24 % in total)
13172 data points (75.18%) excluded in total
4348 valid data points (24.82%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 174 data points (0.99%) set to NA
LE: 558 data points (3.18%) set to NA
NEE: 2782 data points (15.88%) set to NA
-------------------------------------------------------------------
Data filtering:
7296 data points (41.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7296 data points (41.64%) excluded in total
10224 valid data points (58.36%) remaining.

New sEddyProc class for site 'JP-Yms'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Yms-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[155/329] Processing: JP-Ynf

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: JP-Ynf | Years: 2017, 2018, 2019, 2020, 2021, 2022
Quality control:
TA: 0 data points (0%) set to NA
H: 982 data points (5.61%) set to NA
LE: 1008 data points (5.75%) set to NA
NEE: 1224 data points (6.99%) set to NA
-------------------------------------------------------------------
Data filtering:
480 data points (2.74%) excluded by growing season filter
11588 additional data points (66.14%) excluded by precipitation filter (12024
 data points = 68.63 % in total)
12068 data points (68.88%) excluded in total
5452 valid data points (31.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 982 data points (5.61%) set to NA
LE: 1008 data points (5.75%) set to NA
NEE: 1224 data points (6.99%) set to NA
-------------------------------------------------------------------
Data filtering:
480 data points (2.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
480 data points (2.74%) excluded in total
17040 valid data points (97.26%) remaining.

New sEddyProc class for site 'JP-Ynf'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Ynf-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4173 data points (23.82%) set to NA
H: 6286 data points (35.88%) set to NA
LE: 7159 data points (40.86%) set to NA
NEE: 11412 data points (65.14%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
11938 additional data points (68.14%) excluded by precipitation filter (11938
 data points = 68.14 % in total)
11938 data points (68.14%) excluded in total
5582 valid data points (31.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4173 data points (23.82%) set to NA
H: 6286 data points (35.88%) set to NA
LE: 7159 data points (40.86%) set to NA
NEE: 11412 data points (65.14%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'JP-Ynf'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Ynf-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 46 data points (0.26%) set to NA
H: 13489 data points (76.99%) set to NA
LE: 14591 data points (83.28%) set to NA
NEE: 15462 data points (88.25%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12326 additional data points (70.35%) excluded by precipitation filter (12326
 data points = 70.35 % in total)
12326 data points (70.35%) excluded in total
5194 valid data points (29.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 46 data points (0.26%) set to NA
H: 13489 data points (76.99%) set to NA
LE: 14591 data points (83.28%) set to NA
NEE: 15462 data points (88.25%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'JP-Ynf'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Ynf-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 34 data points (0.19%) set to NA
H: 28 data points (0.16%) set to NA
LE: 26 data points (0.15%) set to NA
NEE: 228 data points (1.3%) set to NA
-------------------------------------------------------------------
Data filtering:
1008 data points (5.74%) excluded by growing season filter
11554 additional data points (65.77%) excluded by precipitation filter (12556
 data points = 71.47 % in total)
12562 data points (71.51%) excluded in total
5006 valid data points (28.49%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 34 data points (0.19%) set to NA
H: 28 data points (0.16%) set to NA
LE: 26 data points (0.15%) set to NA
NEE: 228 data points (1.3%) set to NA
-------------------------------------------------------------------
Data filtering:
1008 data points (5.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1008 data points (5.74%) excluded in total
16560 valid data points (94.26%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -61 ...”
New sEddyProc class for site 'JP-Ynf'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -61 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Ynf-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 7655 data points (43.69%) set to NA
H: 4843 data points (27.64%) set to NA
LE: 4857 data points (27.72%) set to NA
NEE: 5044 data points (28.79%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 69”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12094 additional data points (69.03%) excluded by precipitation filter (12094
 data points = 69.03 % in total)
12094 data points (69.03%) excluded in total
5426 valid data points (30.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7655 data points (43.69%) set to NA
H: 4843 data points (27.64%) set to NA
LE: 4857 data points (27.72%) set to NA
NEE: 5044 data points (28.79%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 69”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'JP-Ynf'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Ynf-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2075 data points (11.84%) set to NA
H: 37 data points (0.21%) set to NA
LE: 47 data points (0.27%) set to NA
NEE: 1446 data points (8.25%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
13252 additional data points (75.64%) excluded by precipitation filter (13252
 data points = 75.64 % in total)
13252 data points (75.64%) excluded in total
4268 valid data points (24.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2075 data points (11.84%) set to NA
H: 37 data points (0.21%) set to NA
LE: 47 data points (0.27%) set to NA
NEE: 1446 data points (8.25%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'JP-Ynf'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for JP-Ynf-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[156/329] Processing: KE-Chk

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: KE-Chk | Years: 2022, 2023, 2024
Quality control:
TA: 13333 data points (76.1%) set to NA
H: 13334 data points (76.11%) set to NA
LE: 13335 data points (76.11%) set to NA
NEE: 13337 data points (76.12%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4390 additional data points (25.06%) excluded by precipitation filter (4390
 data points = 25.06 % in total)
4390 data points (25.06%) excluded in total
13130 valid data points (74.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 13333 data points (76.1%) set to NA
H: 13334 data points (76.11%) set to NA
LE: 13335 data points (76.11%) set to NA
NEE: 13337 data points (76.12%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'KE-Chk'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KE-Chk-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1435 data points (8.19%) set to NA
H: 888 data points (5.07%) set to NA
LE: 931 data points (5.31%) set to NA
NEE: 1844 data points (10.53%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 21”

-------------------------------------------------------------------
Data filtering:
12000 data points (68.49%) excluded by growing season filter
1912 additional data points (10.91%) excluded by precipitation filter (3617
 data points = 20.64 % in total)
13912 data points (79.41%) excluded in total
3608 valid data points (20.59%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1435 data points (8.19%) set to NA
H: 888 data points (5.07%) set to NA
LE: 931 data points (5.31%) set to NA
NEE: 1844 data points (10.53%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 21”

-------------------------------------------------------------------
Data filtering:
12000 data points (68.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12000 data points (68.49%) excluded in total
5520 valid data points (31.51%) remaining.

New sEddyProc class for site 'KE-Chk'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KE-Chk-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 9599 data points (54.64%) set to NA
H: 7189 data points (40.92%) set to NA
LE: 7261 data points (41.33%) set to NA
NEE: 9745 data points (55.47%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5142 additional data points (29.27%) excluded by precipitation filter (5142
 data points = 29.27 % in total)
5142 data points (29.27%) excluded in total
12426 valid data points (70.73%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9599 data points (54.64%) set to NA
H: 7189 data points (40.92%) set to NA
LE: 7261 data points (41.33%) set to NA
NEE: 9745 data points (55.47%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'KE-Chk'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 65.62.

Regression of reference temperature R_ref for 22 periods.

[157/329] Processing: KR-AdC

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: KR-AdC | Years: 2017, 2018
Quality control:
TA: 0 data points (0%) set to NA
H: 963 data points (5.5%) set to NA
LE: 1042 data points (5.95%) set to NA
NEE: 1837 data points (10.49%) set to NA
-------------------------------------------------------------------
Data filtering:
3264 data points (18.63%) excluded by growing season filter
3793 additional data points (21.65%) excluded by precipitation filter (4248
 data points = 24.25 % in total)
7057 data points (40.28%) excluded in total
10463 valid data points (59.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 963 data points (5.5%) set to NA
LE: 1042 data points (5.95%) set to NA
NEE: 1837 data points (10.49%) set to NA
-------------------------------------------------------------------
Data filtering:
3264 data points (18.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3264 data points (18.63%) excluded in total
14256 valid data points (81.37%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -64 ...”
New sEddyProc class for site 'KR-AdC'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -64 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-AdC-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 3885 data points (22.17%) set to NA
LE: 3924 data points (22.4%) set to NA
NEE: 4534 data points (25.88%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 29”

-------------------------------------------------------------------
Data filtering:
1824 data points (10.41%) excluded by growing season filter
3916 additional data points (22.35%) excluded by precipitation filter (4120
 data points = 23.52 % in total)
5740 data points (32.76%) excluded in total
11780 valid data points (67.24%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 3885 data points (22.17%) set to NA
LE: 3924 data points (22.4%) set to NA
NEE: 4534 data points (25.88%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 29”

-------------------------------------------------------------------
Data filtering:
1824 data points (10.41%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1824 data points (10.41%) excluded in total
15696 valid data points (89.59%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -52, -64, -51, -56, -56, -59, -63 ...”
New sEddyProc class for site 'KR-AdC'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -52, -64, -51, -56, -56, -59, -63 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-AdC-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[158/329] Processing: KR-HcM

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: KR-HcM | Years: 2017, 2018
Quality control:
TA: 0 data points (0%) set to NA
H: 31 data points (0.18%) set to NA
LE: 984 data points (5.62%) set to NA
NEE: 2405 data points (13.73%) set to NA
-------------------------------------------------------------------
Data filtering:
8640 data points (49.32%) excluded by growing season filter
2801 additional data points (15.99%) excluded by precipitation filter (4366
 data points = 24.92 % in total)
11441 data points (65.3%) excluded in total
6079 valid data points (34.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 31 data points (0.18%) set to NA
LE: 984 data points (5.62%) set to NA
NEE: 2405 data points (13.73%) set to NA
-------------------------------------------------------------------
Data filtering:
8640 data points (49.32%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8640 data points (49.32%) excluded in total
8880 valid data points (50.68%) remaining.

New sEddyProc class for site 'KR-HcM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-HcM-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 30 data points (0.17%) set to NA
LE: 1034 data points (5.9%) set to NA
NEE: 1181 data points (6.74%) set to NA
-------------------------------------------------------------------
Data filtering:
7296 data points (41.64%) excluded by growing season filter
3071 additional data points (17.53%) excluded by precipitation filter (4309
 data points = 24.59 % in total)
10367 data points (59.17%) excluded in total
7153 valid data points (40.83%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 30 data points (0.17%) set to NA
LE: 1034 data points (5.9%) set to NA
NEE: 1181 data points (6.74%) set to NA
-------------------------------------------------------------------
Data filtering:
7296 data points (41.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7296 data points (41.64%) excluded in total
10224 valid data points (58.36%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 23 cases! Invalid values with 'NEE < -50': -59, -50, -54, -50, -52, -50, -50, -51, -65, -67, -56, -51, -50, -63, -60, -62, -57, -52, -51, -52, -51, -56, -59 ...”
New sEddyProc class for site 'KR-HcM'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 23 cases! Invalid values with 'NEE < -50': -59, -50, -54, -50, -52, -50, -50, -51, -65, -67, -56, -51, -50, -63, -60, -62, -57, -52, -51, -52, -51, -56, -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-HcM-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[159/329] Processing: KR-JjM

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: KR-JjM | Years: 2017, 2018
Quality control:
TA: 1753 data points (10.01%) set to NA
H: 1765 data points (10.07%) set to NA
LE: 1790 data points (10.22%) set to NA
NEE: 2293 data points (13.09%) set to NA
-------------------------------------------------------------------
Data filtering:
8064 data points (46.03%) excluded by growing season filter
3558 additional data points (20.31%) excluded by precipitation filter (6599
 data points = 37.67 % in total)
11622 data points (66.34%) excluded in total
5898 valid data points (33.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1753 data points (10.01%) set to NA
H: 1765 data points (10.07%) set to NA
LE: 1790 data points (10.22%) set to NA
NEE: 2293 data points (13.09%) set to NA
-------------------------------------------------------------------
Data filtering:
8064 data points (46.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8064 data points (46.03%) excluded in total
9456 valid data points (53.97%) remaining.

New sEddyProc class for site 'KR-JjM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-JjM-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 11 data points (0.06%) set to NA
H: 15 data points (0.09%) set to NA
LE: 23 data points (0.13%) set to NA
NEE: 775 data points (4.42%) set to NA
-------------------------------------------------------------------
Data filtering:
8256 data points (47.12%) excluded by growing season filter
4092 additional data points (23.36%) excluded by precipitation filter (7075
 data points = 40.38 % in total)
12348 data points (70.48%) excluded in total
5172 valid data points (29.52%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11 data points (0.06%) set to NA
H: 15 data points (0.09%) set to NA
LE: 23 data points (0.13%) set to NA
NEE: 775 data points (4.42%) set to NA
-------------------------------------------------------------------
Data filtering:
8256 data points (47.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8256 data points (47.12%) excluded in total
9264 valid data points (52.88%) remaining.

New sEddyProc class for site 'KR-JjM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-JjM-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[160/329] Processing: KR-Kw1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: KR-Kw1 | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 40 data points (0.23%) set to NA
H: 149 data points (0.85%) set to NA
LE: 154 data points (0.88%) set to NA
NEE: 637 data points (3.64%) set to NA
-------------------------------------------------------------------
Data filtering:
5520 data points (31.51%) excluded by growing season filter
3239 additional data points (18.49%) excluded by precipitation filter (4430
 data points = 25.29 % in total)
8759 data points (49.99%) excluded in total
8761 valid data points (50.01%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 40 data points (0.23%) set to NA
H: 149 data points (0.85%) set to NA
LE: 154 data points (0.88%) set to NA
NEE: 637 data points (3.64%) set to NA
-------------------------------------------------------------------
Data filtering:
5520 data points (31.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5520 data points (31.51%) excluded in total
12000 valid data points (68.49%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -51, -53 ...”
New sEddyProc class for site 'KR-Kw1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -51, -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-Kw1-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 204 data points (1.16%) set to NA
H: 209 data points (1.19%) set to NA
LE: 233 data points (1.33%) set to NA
NEE: 758 data points (4.33%) set to NA
-------------------------------------------------------------------
Data filtering:
6480 data points (36.99%) excluded by growing season filter
3129 additional data points (17.86%) excluded by precipitation filter (3901
 data points = 22.27 % in total)
9609 data points (54.85%) excluded in total
7911 valid data points (45.15%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 204 data points (1.16%) set to NA
H: 209 data points (1.19%) set to NA
LE: 233 data points (1.33%) set to NA
NEE: 758 data points (4.33%) set to NA
-------------------------------------------------------------------
Data filtering:
6480 data points (36.99%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6480 data points (36.99%) excluded in total
11040 valid data points (63.01%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -55, -50 ...”
New sEddyProc class for site 'KR-Kw1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -55, -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-Kw1-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 17 data points (0.1%) set to NA
LE: 25 data points (0.14%) set to NA
NEE: 1829 data points (10.44%) set to NA
-------------------------------------------------------------------
Data filtering:
5568 data points (31.78%) excluded by growing season filter
3996 additional data points (22.81%) excluded by precipitation filter (5027
 data points = 28.69 % in total)
9564 data points (54.59%) excluded in total
7956 valid data points (45.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 17 data points (0.1%) set to NA
LE: 25 data points (0.14%) set to NA
NEE: 1829 data points (10.44%) set to NA
-------------------------------------------------------------------
Data filtering:
5568 data points (31.78%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5568 data points (31.78%) excluded in total
11952 valid data points (68.22%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -56, -65 ...”
New sEddyProc class for site 'KR-Kw1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -56, -65 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-Kw1-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 39 data points (0.22%) set to NA
H: 43 data points (0.24%) set to NA
LE: 30 data points (0.17%) set to NA
NEE: 1306 data points (7.43%) set to NA
-------------------------------------------------------------------
Data filtering:
5760 data points (32.79%) excluded by growing season filter
4509 additional data points (25.67%) excluded by precipitation filter (5379
 data points = 30.62 % in total)
10269 data points (58.45%) excluded in total
7299 valid data points (41.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 39 data points (0.22%) set to NA
H: 43 data points (0.24%) set to NA
LE: 30 data points (0.17%) set to NA
NEE: 1306 data points (7.43%) set to NA
-------------------------------------------------------------------
Data filtering:
5760 data points (32.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5760 data points (32.79%) excluded in total
11808 valid data points (67.21%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -58, -50 ...”
New sEddyProc class for site 'KR-Kw1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -58, -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-Kw1-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[161/329] Processing: KR-Kw2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: KR-Kw2 | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 0 data points (0%) set to NA
H: 103 data points (0.59%) set to NA
LE: 132 data points (0.75%) set to NA
NEE: 779 data points (4.45%) set to NA
-------------------------------------------------------------------
Data filtering:
9264 data points (52.88%) excluded by growing season filter
2444 additional data points (13.95%) excluded by precipitation filter (4206
 data points = 24.01 % in total)
11708 data points (66.83%) excluded in total
5812 valid data points (33.17%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 103 data points (0.59%) set to NA
LE: 132 data points (0.75%) set to NA
NEE: 779 data points (4.45%) set to NA
-------------------------------------------------------------------
Data filtering:
9264 data points (52.88%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9264 data points (52.88%) excluded in total
8256 valid data points (47.12%) remaining.

New sEddyProc class for site 'KR-Kw2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-Kw2-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 901 data points (5.14%) set to NA
H: 866 data points (4.94%) set to NA
LE: 885 data points (5.05%) set to NA
NEE: 1637 data points (9.34%) set to NA
-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
2627 additional data points (14.99%) excluded by precipitation filter (4246
 data points = 24.24 % in total)
11747 data points (67.05%) excluded in total
5773 valid data points (32.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 901 data points (5.14%) set to NA
H: 866 data points (4.94%) set to NA
LE: 885 data points (5.05%) set to NA
NEE: 1637 data points (9.34%) set to NA
-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9120 data points (52.05%) excluded in total
8400 valid data points (47.95%) remaining.

New sEddyProc class for site 'KR-Kw2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-Kw2-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 153 data points (0.87%) set to NA
H: 193 data points (1.1%) set to NA
LE: 195 data points (1.11%) set to NA
NEE: 967 data points (5.52%) set to NA
-------------------------------------------------------------------
Data filtering:
8928 data points (50.96%) excluded by growing season filter
2318 additional data points (13.23%) excluded by precipitation filter (4214
 data points = 24.05 % in total)
11246 data points (64.19%) excluded in total
6274 valid data points (35.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 153 data points (0.87%) set to NA
H: 193 data points (1.1%) set to NA
LE: 195 data points (1.11%) set to NA
NEE: 967 data points (5.52%) set to NA
-------------------------------------------------------------------
Data filtering:
8928 data points (50.96%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8928 data points (50.96%) excluded in total
8592 valid data points (49.04%) remaining.

New sEddyProc class for site 'KR-Kw2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-Kw2-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 40 data points (0.23%) set to NA
H: 86 data points (0.49%) set to NA
LE: 85 data points (0.48%) set to NA
NEE: 836 data points (4.76%) set to NA
-------------------------------------------------------------------
Data filtering:
9648 data points (54.92%) excluded by growing season filter
3287 additional data points (18.71%) excluded by precipitation filter (4757
 data points = 27.08 % in total)
12935 data points (73.63%) excluded in total
4633 valid data points (26.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 40 data points (0.23%) set to NA
H: 86 data points (0.49%) set to NA
LE: 85 data points (0.48%) set to NA
NEE: 836 data points (4.76%) set to NA
-------------------------------------------------------------------
Data filtering:
9648 data points (54.92%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9648 data points (54.92%) excluded in total
7920 valid data points (45.08%) remaining.

New sEddyProc class for site 'KR-Kw2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-Kw2-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[162/329] Processing: KR-PcD

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: KR-PcD | Years: 2017, 2018
Quality control:
TA: 3 data points (0.02%) set to NA
H: 50 data points (0.29%) set to NA
LE: 178 data points (1.02%) set to NA
NEE: 2682 data points (15.31%) set to NA
-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
3248 additional data points (18.54%) excluded by precipitation filter (5771
 data points = 32.94 % in total)
12368 data points (70.59%) excluded in total
5152 valid data points (29.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3 data points (0.02%) set to NA
H: 50 data points (0.29%) set to NA
LE: 178 data points (1.02%) set to NA
NEE: 2682 data points (15.31%) set to NA
-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9120 data points (52.05%) excluded in total
8400 valid data points (47.95%) remaining.

New sEddyProc class for site 'KR-PcD'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-PcD-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 18 data points (0.1%) set to NA
H: 44 data points (0.25%) set to NA
LE: 578 data points (3.3%) set to NA
NEE: 2487 data points (14.2%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.27%) excluded by growing season filter
1788 additional data points (10.21%) excluded by precipitation filter (4022
 data points = 22.96 % in total)
12348 data points (70.48%) excluded in total
5172 valid data points (29.52%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 18 data points (0.1%) set to NA
H: 44 data points (0.25%) set to NA
LE: 578 data points (3.3%) set to NA
NEE: 2487 data points (14.2%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10560 data points (60.27%) excluded in total
6960 valid data points (39.73%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
New sEddyProc class for site 'KR-PcD'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-PcD-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[163/329] Processing: KR-ScC

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: KR-ScC | Years: 2017, 2018
Quality control:
TA: 0 data points (0%) set to NA
H: 34 data points (0.19%) set to NA
LE: 45 data points (0.26%) set to NA
NEE: 2888 data points (16.48%) set to NA
-------------------------------------------------------------------
Data filtering:
8880 data points (50.68%) excluded by growing season filter
3565 additional data points (20.35%) excluded by precipitation filter (5709
 data points = 32.59 % in total)
12445 data points (71.03%) excluded in total
5075 valid data points (28.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 34 data points (0.19%) set to NA
LE: 45 data points (0.26%) set to NA
NEE: 2888 data points (16.48%) set to NA
-------------------------------------------------------------------
Data filtering:
8880 data points (50.68%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8880 data points (50.68%) excluded in total
8640 valid data points (49.32%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -58, -54, -56, -50, -73, -56, -59 ...”
New sEddyProc class for site 'KR-ScC'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -58, -54, -56, -50, -73, -56, -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-ScC-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 45 data points (0.26%) set to NA
LE: 51 data points (0.29%) set to NA
NEE: 2767 data points (15.79%) set to NA
-------------------------------------------------------------------
Data filtering:
8160 data points (46.58%) excluded by growing season filter
3113 additional data points (17.77%) excluded by precipitation filter (5059
 data points = 28.88 % in total)
11273 data points (64.34%) excluded in total
6247 valid data points (35.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 45 data points (0.26%) set to NA
LE: 51 data points (0.29%) set to NA
NEE: 2767 data points (15.79%) set to NA
-------------------------------------------------------------------
Data filtering:
8160 data points (46.58%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8160 data points (46.58%) excluded in total
9360 valid data points (53.42%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -50, -76, -59, -56 ...”
New sEddyProc class for site 'KR-ScC'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -50, -76, -59, -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-ScC-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[164/329] Processing: KR-SmM

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: KR-SmM | Years: 2017, 2018, 2019, 2020, 2021
Quality control:
TA: 0 data points (0%) set to NA
H: 1734 data points (9.9%) set to NA
LE: 1734 data points (9.9%) set to NA
NEE: 2018 data points (11.52%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2897 additional data points (16.54%) excluded by precipitation filter (2897
 data points = 16.54 % in total)
2897 data points (16.54%) excluded in total
14623 valid data points (83.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1734 data points (9.9%) set to NA
LE: 1734 data points (9.9%) set to NA
NEE: 2018 data points (11.52%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -59 ...”
New sEddyProc class for site 'KR-SmM'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-SmM-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 837 data points (4.78%) set to NA
H: 1030 data points (5.88%) set to NA
LE: 1017 data points (5.8%) set to NA
NEE: 1279 data points (7.3%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3256 additional data points (18.58%) excluded by precipitation filter (3256
 data points = 18.58 % in total)
3256 data points (18.58%) excluded in total
14264 valid data points (81.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 837 data points (4.78%) set to NA
H: 1030 data points (5.88%) set to NA
LE: 1017 data points (5.8%) set to NA
NEE: 1279 data points (7.3%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -72, -54 ...”
New sEddyProc class for site 'KR-SmM'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -72, -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-SmM-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 4966 data points (28.34%) set to NA
LE: 6479 data points (36.98%) set to NA
NEE: 6744 data points (38.49%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3423 additional data points (19.54%) excluded by precipitation filter (3423
 data points = 19.54 % in total)
3423 data points (19.54%) excluded in total
14097 valid data points (80.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 4966 data points (28.34%) set to NA
LE: 6479 data points (36.98%) set to NA
NEE: 6744 data points (38.49%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -64, -74, -55, -59 ...”
New sEddyProc class for site 'KR-SmM'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -64, -74, -55, -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-SmM-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 6265 data points (35.66%) set to NA
LE: 8112 data points (46.17%) set to NA
NEE: 8227 data points (46.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4107 additional data points (23.38%) excluded by precipitation filter (4107
 data points = 23.38 % in total)
4107 data points (23.38%) excluded in total
13461 valid data points (76.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 6265 data points (35.66%) set to NA
LE: 8112 data points (46.17%) set to NA
NEE: 8227 data points (46.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -56, -57 ...”
New sEddyProc class for site 'KR-SmM'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -56, -57 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-SmM-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2577 data points (14.71%) set to NA
LE: 4355 data points (24.86%) set to NA
NEE: 5248 data points (29.95%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2868 additional data points (16.37%) excluded by precipitation filter (2868
 data points = 16.37 % in total)
2868 data points (16.37%) excluded in total
14652 valid data points (83.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2577 data points (14.71%) set to NA
LE: 4355 data points (24.86%) set to NA
NEE: 5248 data points (29.95%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -57 ...”
New sEddyProc class for site 'KR-SmM'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -57 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-SmM-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[165/329] Processing: KR-TwB

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: KR-TwB | Years: 2024
Quality control:
TA: 4539 data points (25.84%) set to NA
H: 4148 data points (23.61%) set to NA
LE: 4149 data points (23.62%) set to NA
NEE: 4627 data points (26.34%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 67”

-------------------------------------------------------------------
Data filtering:
8784 data points (50%) excluded by growing season filter
5372 additional data points (30.58%) excluded by precipitation filter (8830
 data points = 50.26 % in total)
14156 data points (80.58%) excluded in total
3412 valid data points (19.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4539 data points (25.84%) set to NA
H: 4148 data points (23.61%) set to NA
LE: 4149 data points (23.62%) set to NA
NEE: 4627 data points (26.34%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 67”

-------------------------------------------------------------------
Data filtering:
8784 data points (50%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8784 data points (50%) excluded in total
8784 valid data points (50%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 23 cases! Invalid values with 'NEE < -50': -54, -74, -75, -53, -61, -68, -78, -58, -57, -61, -52, -78, -77, -59, -51, -61, -54, -72, -62, -68, -68, -67, -62 ...”
New sEddyProc class for site 'KR-TwB'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 23 cases! Invalid values with 'NEE < -50': -54, -74, -75, -53, -61, -68, -78, -58, -57, -61, -52, -78, -77, -59, -51, -61, -54, -72, -62, -68, -68, -67, -62 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 12 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-TwB-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[166/329] Processing: KR-TwC

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: KR-TwC | Years: 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 18 data points (0.1%) set to NA
LE: 1801 data points (10.25%) set to NA
NEE: 1934 data points (11.01%) set to NA
-------------------------------------------------------------------
Data filtering:
6432 data points (36.61%) excluded by growing season filter
5946 additional data points (33.85%) excluded by precipitation filter (8830
 data points = 50.26 % in total)
12378 data points (70.46%) excluded in total
5190 valid data points (29.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 18 data points (0.1%) set to NA
LE: 1801 data points (10.25%) set to NA
NEE: 1934 data points (11.01%) set to NA
-------------------------------------------------------------------
Data filtering:
6432 data points (36.61%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6432 data points (36.61%) excluded in total
11136 valid data points (63.39%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 11 cases! Invalid values with 'NEE < -50': -60, -52, -75, -51, -70, -58, -67, -55, -58, -58, -66 ...”
New sEddyProc class for site 'KR-TwC'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 11 cases! Invalid values with 'NEE < -50': -60, -52, -75, -51, -70, -58, -67, -55, -58, -58, -66 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-TwC-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[167/329] Processing: KR-WdE

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: KR-WdE | Years: 2017, 2018
Quality control:
TA: 1188 data points (6.78%) set to NA
H: 4101 data points (23.41%) set to NA
LE: 4310 data points (24.6%) set to NA
NEE: 5255 data points (29.99%) set to NA
-------------------------------------------------------------------
Data filtering:
4416 data points (25.21%) excluded by growing season filter
2915 additional data points (16.64%) excluded by precipitation filter (3915
 data points = 22.35 % in total)
7331 data points (41.84%) excluded in total
10189 valid data points (58.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1188 data points (6.78%) set to NA
H: 4101 data points (23.41%) set to NA
LE: 4310 data points (24.6%) set to NA
NEE: 5255 data points (29.99%) set to NA
-------------------------------------------------------------------
Data filtering:
4416 data points (25.21%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4416 data points (25.21%) excluded in total
13104 valid data points (74.79%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
New sEddyProc class for site 'KR-WdE'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-WdE-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 579 data points (3.3%) set to NA
H: 224 data points (1.28%) set to NA
LE: 263 data points (1.5%) set to NA
NEE: 1611 data points (9.2%) set to NA
-------------------------------------------------------------------
Data filtering:
3024 data points (17.26%) excluded by growing season filter
3398 additional data points (19.39%) excluded by precipitation filter (3745
 data points = 21.38 % in total)
6422 data points (36.66%) excluded in total
11098 valid data points (63.34%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 579 data points (3.3%) set to NA
H: 224 data points (1.28%) set to NA
LE: 263 data points (1.5%) set to NA
NEE: 1611 data points (9.2%) set to NA
-------------------------------------------------------------------
Data filtering:
3024 data points (17.26%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3024 data points (17.26%) excluded in total
14496 valid data points (82.74%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -51, -65 ...”
New sEddyProc class for site 'KR-WdE'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -51, -65 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 1 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for KR-WdE-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[168/329] Processing: MX-Aog

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: MX-Aog | Years: 2017, 2018
Quality control:
TA: 0 data points (0%) set to NA
H: 53 data points (0.3%) set to NA
LE: 425 data points (2.43%) set to NA
NEE: 928 data points (5.3%) set to NA
-------------------------------------------------------------------
Data filtering:
11664 data points (66.58%) excluded by growing season filter
1803 additional data points (10.29%) excluded by precipitation filter (2672
 data points = 15.25 % in total)
13467 data points (76.87%) excluded in total
4053 valid data points (23.13%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 53 data points (0.3%) set to NA
LE: 425 data points (2.43%) set to NA
NEE: 928 data points (5.3%) set to NA
-------------------------------------------------------------------
Data filtering:
11664 data points (66.58%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11664 data points (66.58%) excluded in total
5856 valid data points (33.42%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 20 cases! Invalid values with 'NEE < -50': -56, -57, -55, -69, -52, -60, -68, -63, -59, -56, -61, -52, -58, -57, -65, -70, -56, -52, -80, -69 ...”
New sEddyProc class for site 'MX-Aog'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 20 cases! Invalid values with 'NEE < -50': -56, -57, -55, -69, -52, -60, -68, -63, -59, -56, -61, -52, -58, -57, -65, -70, -56, -52, -80, -69 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for MX-Aog-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 101 data points (0.58%) set to NA
H: 3543 data points (20.22%) set to NA
LE: 3615 data points (20.63%) set to NA
NEE: 4437 data points (25.33%) set to NA
-------------------------------------------------------------------
Data filtering:
7920 data points (45.21%) excluded by growing season filter
2470 additional data points (14.1%) excluded by precipitation filter (2971
 data points = 16.96 % in total)
10390 data points (59.3%) excluded in total
7130 valid data points (40.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 101 data points (0.58%) set to NA
H: 3543 data points (20.22%) set to NA
LE: 3615 data points (20.63%) set to NA
NEE: 4437 data points (25.33%) set to NA
-------------------------------------------------------------------
Data filtering:
7920 data points (45.21%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7920 data points (45.21%) excluded in total
9600 valid data points (54.79%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -66, -55, -50, -50, -75, -55, -67, -70, -65 ...”
New sEddyProc class for site 'MX-Aog'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -66, -55, -50, -50, -75, -55, -67, -70, -65 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for MX-Aog-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[169/329] Processing: MX-PMm

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: MX-PMm | Years: 2017, 2018
Quality control:
TA: 8614 data points (49.17%) set to NA
H: 9194 data points (52.48%) set to NA
LE: 9296 data points (53.06%) set to NA
NEE: 9687 data points (55.29%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
13934 additional data points (79.53%) excluded by precipitation filter (13934
 data points = 79.53 % in total)
13934 data points (79.53%) excluded in total
3586 valid data points (20.47%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8614 data points (49.17%) set to NA
H: 9194 data points (52.48%) set to NA
LE: 9296 data points (53.06%) set to NA
NEE: 9687 data points (55.29%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -53, -59, -61 ...”
New sEddyProc class for site 'MX-PMm'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -53, -59, -61 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for MX-PMm-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3861 data points (22.04%) set to NA
H: 4013 data points (22.91%) set to NA
LE: 4065 data points (23.2%) set to NA
NEE: 4177 data points (23.84%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
13916 additional data points (79.43%) excluded by precipitation filter (13916
 data points = 79.43 % in total)
13916 data points (79.43%) excluded in total
3604 valid data points (20.57%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3861 data points (22.04%) set to NA
H: 4013 data points (22.91%) set to NA
LE: 4065 data points (23.2%) set to NA
NEE: 4177 data points (23.84%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 13 cases! Invalid values with 'NEE < -50': -60, -54, -53, -67, -50, -71, -63, -51, -59, -56, -59, -52, -64 ...”
New sEddyProc class for site 'MX-PMm'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 13 cases! Invalid values with 'NEE < -50': -60, -54, -53, -67, -50, -71, -63, -51, -59, -56, -59, -52, -64 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 13 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for MX-PMm-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[170/329] Processing: MY-LHP

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: MY-LHP | Years: 2017, 2018, 2019
Quality control:
TA: 0 data points (0%) set to NA
H: 8124 data points (46.37%) set to NA
LE: 8438 data points (48.16%) set to NA
NEE: 9845 data points (56.19%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10753 additional data points (61.38%) excluded by precipitation filter (10753
 data points = 61.38 % in total)
10753 data points (61.38%) excluded in total
6767 valid data points (38.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 8124 data points (46.37%) set to NA
LE: 8438 data points (48.16%) set to NA
NEE: 9845 data points (56.19%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -52, -53, -63, -57, -55, -52, -52, -59 ...”
New sEddyProc class for site 'MY-LHP'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -52, -53, -63, -57, -55, -52, -52, -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for MY-LHP-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 5909 data points (33.73%) set to NA
LE: 11801 data points (67.36%) set to NA
NEE: 11906 data points (67.96%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9977 additional data points (56.95%) excluded by precipitation filter (9977
 data points = 56.95 % in total)
9977 data points (56.95%) excluded in total
7543 valid data points (43.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5909 data points (33.73%) set to NA
LE: 11801 data points (67.36%) set to NA
NEE: 11906 data points (67.96%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -63 ...”
New sEddyProc class for site 'MY-LHP'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -63 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for MY-LHP-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 114 data points (0.65%) set to NA
H: 9576 data points (54.66%) set to NA
LE: 12259 data points (69.97%) set to NA
NEE: 12208 data points (69.68%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9115 additional data points (52.03%) excluded by precipitation filter (9115
 data points = 52.03 % in total)
9115 data points (52.03%) excluded in total
8405 valid data points (47.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 114 data points (0.65%) set to NA
H: 9576 data points (54.66%) set to NA
LE: 12259 data points (69.97%) set to NA
NEE: 12208 data points (69.68%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -51 ...”
New sEddyProc class for site 'MY-LHP'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for MY-LHP-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[171/329] Processing: NL-Loo

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: NL-Loo | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 67 data points (0.38%) set to NA
H: 15 data points (0.09%) set to NA
LE: 231 data points (1.32%) set to NA
NEE: 426 data points (2.43%) set to NA
-------------------------------------------------------------------
Data filtering:
6432 data points (36.71%) excluded by growing season filter
7775 additional data points (44.38%) excluded by precipitation filter (12936
 data points = 73.84 % in total)
14207 data points (81.09%) excluded in total
3313 valid data points (18.91%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 67 data points (0.38%) set to NA
H: 15 data points (0.09%) set to NA
LE: 231 data points (1.32%) set to NA
NEE: 426 data points (2.43%) set to NA
-------------------------------------------------------------------
Data filtering:
6432 data points (36.71%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6432 data points (36.71%) excluded in total
11088 valid data points (63.29%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -54, -50, -51, -56, -54 ...”
New sEddyProc class for site 'NL-Loo'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -54, -50, -51, -56, -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for NL-Loo-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 111 data points (0.63%) set to NA
H: 521 data points (2.97%) set to NA
LE: 800 data points (4.57%) set to NA
NEE: 991 data points (5.66%) set to NA
-------------------------------------------------------------------
Data filtering:
6816 data points (38.9%) excluded by growing season filter
5819 additional data points (33.21%) excluded by precipitation filter (10122
 data points = 57.77 % in total)
12635 data points (72.12%) excluded in total
4885 valid data points (27.88%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 111 data points (0.63%) set to NA
H: 521 data points (2.97%) set to NA
LE: 800 data points (4.57%) set to NA
NEE: 991 data points (5.66%) set to NA
-------------------------------------------------------------------
Data filtering:
6816 data points (38.9%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6816 data points (38.9%) excluded in total
10704 valid data points (61.1%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
New sEddyProc class for site 'NL-Loo'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for NL-Loo-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 7610 data points (43.44%) set to NA
H: 863 data points (4.93%) set to NA
LE: 3882 data points (22.16%) set to NA
NEE: 6417 data points (36.63%) set to NA
-------------------------------------------------------------------
Data filtering:
4800 data points (27.4%) excluded by growing season filter
8457 additional data points (48.27%) excluded by precipitation filter (11364
 data points = 64.86 % in total)
13257 data points (75.67%) excluded in total
4263 valid data points (24.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7610 data points (43.44%) set to NA
H: 863 data points (4.93%) set to NA
LE: 3882 data points (22.16%) set to NA
NEE: 6417 data points (36.63%) set to NA
-------------------------------------------------------------------
Data filtering:
4800 data points (27.4%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4800 data points (27.4%) excluded in total
12720 valid data points (72.6%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -70, -60, -63, -54 ...”
New sEddyProc class for site 'NL-Loo'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -70, -60, -63, -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 204.66.

Regression of reference temperature R_ref for 34 periods.

Quality control:
TA: 150 data points (0.85%) set to NA
H: 1209 data points (6.88%) set to NA
LE: 1234 data points (7.02%) set to NA
NEE: 1401 data points (7.97%) set to NA
-------------------------------------------------------------------
Data filtering:
6288 data points (35.79%) excluded by growing season filter
6682 additional data points (38.04%) excluded by precipitation filter (11875
 data points = 67.59 % in total)
12970 data points (73.83%) excluded in total
4598 valid data points (26.17%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 150 data points (0.85%) set to NA
H: 1209 data points (6.88%) set to NA
LE: 1234 data points (7.02%) set to NA
NEE: 1401 data points (7.97%) set to NA
-------------------------------------------------------------------
Data filtering:
6288 data points (35.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6288 data points (35.79%) excluded in total
11280 valid data points (64.21%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 10 cases! Invalid values with 'NEE < -50': -74, -59, -54, -55, -55, -61, -54, -63, -52, -50 ...”
New sEddyProc class for site 'NL-Loo'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 10 cases! Invalid values with 'NEE < -50': -74, -59, -54, -55, -55, -61, -54, -63, -52, -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for NL-Loo-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3329 data points (19%) set to NA
H: 2336 data points (13.33%) set to NA
LE: 2266 data points (12.93%) set to NA
NEE: 2784 data points (15.89%) set to NA
-------------------------------------------------------------------
Data filtering:
6096 data points (34.79%) excluded by growing season filter
7863 additional data points (44.88%) excluded by precipitation filter (12066
 data points = 68.87 % in total)
13959 data points (79.67%) excluded in total
3561 valid data points (20.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3329 data points (19%) set to NA
H: 2336 data points (13.33%) set to NA
LE: 2266 data points (12.93%) set to NA
NEE: 2784 data points (15.89%) set to NA
-------------------------------------------------------------------
Data filtering:
6096 data points (34.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6096 data points (34.79%) excluded in total
11424 valid data points (65.21%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -54, -52, -55, -55, -54, -61, -61, -59 ...”
New sEddyProc class for site 'NL-Loo'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -54, -52, -55, -55, -54, -61, -61, -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 109.8.

Regression of reference temperature R_ref for 30 periods.

Quality control:
TA: 2134 data points (12.18%) set to NA
H: 211 data points (1.2%) set to NA
LE: 204 data points (1.16%) set to NA
NEE: 987 data points (5.63%) set to NA
-------------------------------------------------------------------
Data filtering:
6528 data points (37.26%) excluded by growing season filter
6389 additional data points (36.47%) excluded by precipitation filter (10462
 data points = 59.71 % in total)
12917 data points (73.73%) excluded in total
4603 valid data points (26.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2134 data points (12.18%) set to NA
H: 211 data points (1.2%) set to NA
LE: 204 data points (1.16%) set to NA
NEE: 987 data points (5.63%) set to NA
-------------------------------------------------------------------
Data filtering:
6528 data points (37.26%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6528 data points (37.26%) excluded in total
10992 valid data points (62.74%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 13 cases! Invalid values with 'NEE < -50': -75, -62, -55, -54, -54, -59, -59, -62, -53, -58, -67, -54, -70 ...”
New sEddyProc class for site 'NL-Loo'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 13 cases! Invalid values with 'NEE < -50': -75, -62, -55, -54, -54, -59, -59, -62, -53, -58, -67, -54, -70 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for NL-Loo-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2292 data points (13.08%) set to NA
H: 659 data points (3.76%) set to NA
LE: 645 data points (3.68%) set to NA
NEE: 671 data points (3.83%) set to NA
-------------------------------------------------------------------
Data filtering:
7248 data points (41.37%) excluded by growing season filter
5049 additional data points (28.82%) excluded by precipitation filter (10255
 data points = 58.53 % in total)
12297 data points (70.19%) excluded in total
5223 valid data points (29.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2292 data points (13.08%) set to NA
H: 659 data points (3.76%) set to NA
LE: 645 data points (3.68%) set to NA
NEE: 671 data points (3.83%) set to NA
-------------------------------------------------------------------
Data filtering:
7248 data points (41.37%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7248 data points (41.37%) excluded in total
10272 valid data points (58.63%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -70, -59, -66, -55, -51, -74, -66, -58, -55 ...”
New sEddyProc class for site 'NL-Loo'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -70, -59, -66, -55, -51, -74, -66, -58, -55 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 99.69.

Regression of reference temperature R_ref for 5 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 72 data points (0.41%) set to NA
LE: 54 data points (0.31%) set to NA
NEE: 91 data points (0.52%) set to NA
-------------------------------------------------------------------
Data filtering:
7008 data points (39.89%) excluded by growing season filter
5655 additional data points (32.19%) excluded by precipitation filter (9838
 data points = 56 % in total)
12663 data points (72.08%) excluded in total
4905 valid data points (27.92%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 72 data points (0.41%) set to NA
LE: 54 data points (0.31%) set to NA
NEE: 91 data points (0.52%) set to NA
-------------------------------------------------------------------
Data filtering:
7008 data points (39.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7008 data points (39.89%) excluded in total
10560 valid data points (60.11%) remaining.

New sEddyProc class for site 'NL-Loo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for NL-Loo-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[172/329] Processing: NO-Hur

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: NO-Hur | Years: 2023, 2024
Quality control:
TA: 14242 data points (81.29%) set to NA
H: 13884 data points (79.25%) set to NA
LE: 13925 data points (79.48%) set to NA
NEE: 14506 data points (82.8%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7982 additional data points (45.56%) excluded by precipitation filter (7982
 data points = 45.56 % in total)
7982 data points (45.56%) excluded in total
9538 valid data points (54.44%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (27) for NO-Hur-2023”

Quality control:
TA: 953 data points (5.42%) set to NA
H: 444 data points (2.53%) set to NA
LE: 306 data points (1.74%) set to NA
NEE: 1452 data points (8.27%) set to NA
-------------------------------------------------------------------
Data filtering:
10320 data points (58.74%) excluded by growing season filter
3400 additional data points (19.35%) excluded by precipitation filter (8124
 data points = 46.24 % in total)
13720 data points (78.1%) excluded in total
3848 valid data points (21.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 953 data points (5.42%) set to NA
H: 444 data points (2.53%) set to NA
LE: 306 data points (1.74%) set to NA
NEE: 1452 data points (8.27%) set to NA
-------------------------------------------------------------------
Data filtering:
10320 data points (58.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10320 data points (58.74%) excluded in total
7248 valid data points (41.26%) remaining.

New sEddyProc class for site 'NO-Hur'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for NO-Hur-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[173/329] Processing: NO-Ikr

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: NO-Ikr | Years: 2019, 2020, 2021, 2022
Quality control:
TA: 4232 data points (24.16%) set to NA
H: 5947 data points (33.94%) set to NA
LE: 6426 data points (36.68%) set to NA
NEE: 6536 data points (37.31%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 75”

-------------------------------------------------------------------
Data filtering:
12912 data points (73.7%) excluded by growing season filter
3172 additional data points (18.11%) excluded by precipitation filter (11226
 data points = 64.08 % in total)
16084 data points (91.8%) excluded in total
1436 valid data points (8.2%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4232 data points (24.16%) set to NA
H: 5947 data points (33.94%) set to NA
LE: 6426 data points (36.68%) set to NA
NEE: 6536 data points (37.31%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 75”

-------------------------------------------------------------------
Data filtering:
12912 data points (73.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12912 data points (73.7%) excluded in total
4608 valid data points (26.3%) remaining.

New sEddyProc class for site 'NO-Ikr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 10 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for NO-Ikr-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 247 data points (1.41%) set to NA
H: 1924 data points (10.95%) set to NA
LE: 2271 data points (12.93%) set to NA
NEE: 2541 data points (14.46%) set to NA
-------------------------------------------------------------------
Data filtering:
13344 data points (75.96%) excluded by growing season filter
3026 additional data points (17.22%) excluded by precipitation filter (12168
 data points = 69.26 % in total)
16370 data points (93.18%) excluded in total
1198 valid data points (6.82%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 247 data points (1.41%) set to NA
H: 1924 data points (10.95%) set to NA
LE: 2271 data points (12.93%) set to NA
NEE: 2541 data points (14.46%) set to NA
-------------------------------------------------------------------
Data filtering:
13344 data points (75.96%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13344 data points (75.96%) excluded in total
4224 valid data points (24.04%) remaining.

New sEddyProc class for site 'NO-Ikr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for NO-Ikr-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 5211 data points (29.74%) set to NA
LE: 5192 data points (29.63%) set to NA
NEE: 5689 data points (32.47%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 19”

-------------------------------------------------------------------
Data filtering:
8976 data points (51.23%) excluded by growing season filter
5692 additional data points (32.49%) excluded by precipitation filter (11246
 data points = 64.19 % in total)
14668 data points (83.72%) excluded in total
2852 valid data points (16.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5211 data points (29.74%) set to NA
LE: 5192 data points (29.63%) set to NA
NEE: 5689 data points (32.47%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 19”

-------------------------------------------------------------------
Data filtering:
8976 data points (51.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8976 data points (51.23%) excluded in total
8544 valid data points (48.77%) remaining.

New sEddyProc class for site 'NO-Ikr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for NO-Ikr-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 13399 data points (76.48%) set to NA
H: 16113 data points (91.97%) set to NA
LE: 16427 data points (93.76%) set to NA
NEE: 16442 data points (93.85%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
11684 additional data points (66.69%) excluded by precipitation filter (11684
 data points = 66.69 % in total)
11684 data points (66.69%) excluded in total
5836 valid data points (33.31%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for NO-Ikr-2022”
[174/329] Processing: PE-QFR

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: PE-QFR | Years: 2018, 2019, 2020, 2021, 2022
Quality control:
TA: 910 data points (5.19%) set to NA
H: 3831 data points (21.87%) set to NA
LE: 3670 data points (20.95%) set to NA
NEE: 3717 data points (21.22%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
17126 additional data points (97.75%) excluded by precipitation filter (17126
 data points = 97.75 % in total)
17126 data points (97.75%) excluded in total
394 valid data points (2.25%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 910 data points (5.19%) set to NA
H: 3831 data points (21.87%) set to NA
LE: 3670 data points (20.95%) set to NA
NEE: 3717 data points (21.22%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -62, -64, -54, -51 ...”
New sEddyProc class for site 'PE-QFR'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -62, -64, -54, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for PE-QFR-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 18 data points (0.1%) set to NA
H: 740 data points (4.22%) set to NA
LE: 568 data points (3.24%) set to NA
NEE: 450 data points (2.57%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
17080 additional data points (97.49%) excluded by precipitation filter (17080
 data points = 97.49 % in total)
17080 data points (97.49%) excluded in total
440 valid data points (2.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 18 data points (0.1%) set to NA
H: 740 data points (4.22%) set to NA
LE: 568 data points (3.24%) set to NA
NEE: 450 data points (2.57%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -54, -64, -50 ...”
New sEddyProc class for site 'PE-QFR'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -54, -64, -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for PE-QFR-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 17567 data points (99.99%) set to NA
H: 17568 data points (100%) set to NA
LE: 17568 data points (100%) set to NA
NEE: 17568 data points (100%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
16572 additional data points (94.33%) excluded by precipitation filter (16572
 data points = 94.33 % in total)
16572 data points (94.33%) excluded in total
996 valid data points (5.67%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for PE-QFR-2020”

Quality control:
TA: 17519 data points (99.99%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 17520 data points (100%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
16958 additional data points (96.79%) excluded by precipitation filter (16958
 data points = 96.79 % in total)
16958 data points (96.79%) excluded in total
562 valid data points (3.21%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for PE-QFR-2021”

Quality control:
TA: 2993 data points (17.08%) set to NA
H: 1057 data points (6.03%) set to NA
LE: 864 data points (4.93%) set to NA
NEE: 807 data points (4.61%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
16172 additional data points (92.31%) excluded by precipitation filter (16172
 data points = 92.31 % in total)
16172 data points (92.31%) excluded in total
1348 valid data points (7.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2993 data points (17.08%) set to NA
H: 1057 data points (6.03%) set to NA
LE: 864 data points (4.93%) set to NA
NEE: 807 data points (4.61%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 6 cases! Invalid values with 'NEE < -50': -58, -51, -53, -57, -57, -63 ...”
New sEddyProc class for site 'PE-QFR'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 6 cases! Invalid values with 'NEE < -50': -58, -51, -53, -57, -57, -63 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for PE-QFR-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[175/329] Processing: RU-Ch2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: RU-Ch2 | Years: 2017, 2018, 2019, 2020, 2021
Quality control:
TA: 0 data points (0%) set to NA
H: 5299 data points (30.25%) set to NA
LE: 5342 data points (30.49%) set to NA
NEE: 8801 data points (50.23%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 148”

-------------------------------------------------------------------
Data filtering:
6096 data points (34.79%) excluded by growing season filter
1670 additional data points (9.53%) excluded by precipitation filter (3086
 data points = 17.61 % in total)
7766 data points (44.33%) excluded in total
9754 valid data points (55.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5299 data points (30.25%) set to NA
LE: 5342 data points (30.49%) set to NA
NEE: 8801 data points (50.23%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 148”

-------------------------------------------------------------------
Data filtering:
6096 data points (34.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6096 data points (34.79%) excluded in total
11424 valid data points (65.21%) remaining.

New sEddyProc class for site 'RU-Ch2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Ch2-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6226 data points (35.54%) set to NA
H: 4245 data points (24.23%) set to NA
LE: 4840 data points (27.63%) set to NA
NEE: 6565 data points (37.47%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 12”

-------------------------------------------------------------------
Data filtering:
13776 data points (78.63%) excluded by growing season filter
1362 additional data points (7.77%) excluded by precipitation filter (4188
 data points = 23.9 % in total)
15138 data points (86.4%) excluded in total
2382 valid data points (13.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6226 data points (35.54%) set to NA
H: 4245 data points (24.23%) set to NA
LE: 4840 data points (27.63%) set to NA
NEE: 6565 data points (37.47%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 12”

-------------------------------------------------------------------
Data filtering:
13776 data points (78.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13776 data points (78.63%) excluded in total
3744 valid data points (21.37%) remaining.

New sEddyProc class for site 'RU-Ch2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 19 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Ch2-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 311 data points (1.78%) set to NA
H: 1907 data points (10.88%) set to NA
LE: 2559 data points (14.61%) set to NA
NEE: 2386 data points (13.62%) set to NA
-------------------------------------------------------------------
Data filtering:
14064 data points (80.27%) excluded by growing season filter
748 additional data points (4.27%) excluded by precipitation filter (1289
 data points = 7.36 % in total)
14812 data points (84.54%) excluded in total
2708 valid data points (15.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 311 data points (1.78%) set to NA
H: 1907 data points (10.88%) set to NA
LE: 2559 data points (14.61%) set to NA
NEE: 2386 data points (13.62%) set to NA
-------------------------------------------------------------------
Data filtering:
14064 data points (80.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14064 data points (80.27%) excluded in total
3456 valid data points (19.73%) remaining.

New sEddyProc class for site 'RU-Ch2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Ch2-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 113 data points (0.64%) set to NA
H: 1812 data points (10.31%) set to NA
LE: 3028 data points (17.24%) set to NA
NEE: 3663 data points (20.85%) set to NA
-------------------------------------------------------------------
Data filtering:
13728 data points (78.14%) excluded by growing season filter
1431 additional data points (8.15%) excluded by precipitation filter (2096
 data points = 11.93 % in total)
15159 data points (86.29%) excluded in total
2409 valid data points (13.71%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 113 data points (0.64%) set to NA
H: 1812 data points (10.31%) set to NA
LE: 3028 data points (17.24%) set to NA
NEE: 3663 data points (20.85%) set to NA
-------------------------------------------------------------------
Data filtering:
13728 data points (78.14%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13728 data points (78.14%) excluded in total
3840 valid data points (21.86%) remaining.

New sEddyProc class for site 'RU-Ch2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Ch2-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1846 data points (10.54%) set to NA
H: 2037 data points (11.63%) set to NA
LE: 3719 data points (21.23%) set to NA
NEE: 3812 data points (21.76%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 28”

-------------------------------------------------------------------
Data filtering:
13824 data points (78.9%) excluded by growing season filter
49 additional data points (0.28%) excluded by precipitation filter (825
 data points = 4.71 % in total)
13873 data points (79.18%) excluded in total
3647 valid data points (20.82%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1846 data points (10.54%) set to NA
H: 2037 data points (11.63%) set to NA
LE: 3719 data points (21.23%) set to NA
NEE: 3812 data points (21.76%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 28”

-------------------------------------------------------------------
Data filtering:
13824 data points (78.9%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13824 data points (78.9%) excluded in total
3696 valid data points (21.1%) remaining.

New sEddyProc class for site 'RU-Ch2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Ch2-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[176/329] Processing: RU-Che

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: RU-Che | Years: 2017, 2018, 2019, 2020, 2021
Quality control:
TA: 0 data points (0%) set to NA
H: 55 data points (0.31%) set to NA
LE: 66 data points (0.38%) set to NA
NEE: 12559 data points (71.68%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2740 additional data points (15.64%) excluded by precipitation filter (2740
 data points = 15.64 % in total)
2740 data points (15.64%) excluded in total
14780 valid data points (84.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 55 data points (0.31%) set to NA
LE: 66 data points (0.38%) set to NA
NEE: 12559 data points (71.68%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'RU-Che'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Che-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2452 data points (14%) set to NA
H: 10131 data points (57.83%) set to NA
LE: 10123 data points (57.78%) set to NA
NEE: 15392 data points (87.85%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1941 additional data points (11.08%) excluded by precipitation filter (1941
 data points = 11.08 % in total)
1941 data points (11.08%) excluded in total
15579 valid data points (88.92%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2452 data points (14%) set to NA
H: 10131 data points (57.83%) set to NA
LE: 10123 data points (57.78%) set to NA
NEE: 15392 data points (87.85%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'RU-Che'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Che-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 27 data points (0.15%) set to NA
H: 8616 data points (49.18%) set to NA
LE: 8651 data points (49.38%) set to NA
NEE: 8826 data points (50.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1757 additional data points (10.03%) excluded by precipitation filter (1757
 data points = 10.03 % in total)
1757 data points (10.03%) excluded in total
15763 valid data points (89.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 27 data points (0.15%) set to NA
H: 8616 data points (49.18%) set to NA
LE: 8651 data points (49.38%) set to NA
NEE: 8826 data points (50.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'RU-Che'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Che-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2698 data points (15.36%) set to NA
LE: 2960 data points (16.85%) set to NA
NEE: 4056 data points (23.09%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2999 additional data points (17.07%) excluded by precipitation filter (2999
 data points = 17.07 % in total)
2999 data points (17.07%) excluded in total
14569 valid data points (82.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2698 data points (15.36%) set to NA
LE: 2960 data points (16.85%) set to NA
NEE: 4056 data points (23.09%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'RU-Che'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Che-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 5783 data points (33.01%) set to NA
H: 6672 data points (38.08%) set to NA
LE: 7035 data points (40.15%) set to NA
NEE: 15599 data points (89.04%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2429 additional data points (13.86%) excluded by precipitation filter (2429
 data points = 13.86 % in total)
2429 data points (13.86%) excluded in total
15091 valid data points (86.14%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5783 data points (33.01%) set to NA
H: 6672 data points (38.08%) set to NA
LE: 7035 data points (40.15%) set to NA
NEE: 15599 data points (89.04%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'RU-Che'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Che-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[177/329] Processing: RU-Ege

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: RU-Ege | Years: 2017, 2018
Quality control:
TA: 198 data points (1.13%) set to NA
H: 9110 data points (52%) set to NA
LE: 9112 data points (52.01%) set to NA
NEE: 9172 data points (52.35%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 129”

-------------------------------------------------------------------
Data filtering:
5856 data points (33.42%) excluded by growing season filter
4412 additional data points (25.18%) excluded by precipitation filter (7686
 data points = 43.87 % in total)
10268 data points (58.61%) excluded in total
7252 valid data points (41.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 198 data points (1.13%) set to NA
H: 9110 data points (52%) set to NA
LE: 9112 data points (52.01%) set to NA
NEE: 9172 data points (52.35%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 129”

-------------------------------------------------------------------
Data filtering:
5856 data points (33.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5856 data points (33.42%) excluded in total
11664 valid data points (66.58%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 13 cases! Invalid values with 'NEE < -50': -55, -60, -69, -62, -65, -64, -53, -54, -58, -54, -52, -62, -57 ...”
New sEddyProc class for site 'RU-Ege'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 13 cases! Invalid values with 'NEE < -50': -55, -60, -69, -62, -65, -64, -53, -54, -58, -54, -52, -62, -57 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Ege-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4415 data points (25.2%) set to NA
H: 9574 data points (54.65%) set to NA
LE: 9600 data points (54.79%) set to NA
NEE: 9631 data points (54.97%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 147”

-------------------------------------------------------------------
Data filtering:
4848 data points (27.67%) excluded by growing season filter
5296 additional data points (30.23%) excluded by precipitation filter (7298
 data points = 41.66 % in total)
10144 data points (57.9%) excluded in total
7376 valid data points (42.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4415 data points (25.2%) set to NA
H: 9574 data points (54.65%) set to NA
LE: 9600 data points (54.79%) set to NA
NEE: 9631 data points (54.97%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 147”

-------------------------------------------------------------------
Data filtering:
4848 data points (27.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4848 data points (27.67%) excluded in total
12672 valid data points (72.33%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -53, -51, -56, -68, -63, -64, -60, -70, -54 ...”
New sEddyProc class for site 'RU-Ege'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -53, -51, -56, -68, -63, -64, -60, -70, -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 10 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Ege-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[178/329] Processing: RU-Fy2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: RU-Fy2 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 213 data points (1.22%) set to NA
H: 276 data points (1.58%) set to NA
LE: 231 data points (1.32%) set to NA
NEE: 546 data points (3.12%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.84%) excluded by growing season filter
3135 additional data points (17.89%) excluded by precipitation filter (7173
 data points = 40.94 % in total)
14319 data points (81.73%) excluded in total
3201 valid data points (18.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 213 data points (1.22%) set to NA
H: 276 data points (1.58%) set to NA
LE: 231 data points (1.32%) set to NA
NEE: 546 data points (3.12%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11184 data points (63.84%) excluded in total
6336 valid data points (36.16%) remaining.

New sEddyProc class for site 'RU-Fy2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Fy2-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 290 data points (1.66%) set to NA
LE: 262 data points (1.5%) set to NA
NEE: 667 data points (3.81%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.73%) excluded by growing season filter
2594 additional data points (14.81%) excluded by precipitation filter (4899
 data points = 27.96 % in total)
13058 data points (74.53%) excluded in total
4462 valid data points (25.47%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 290 data points (1.66%) set to NA
LE: 262 data points (1.5%) set to NA
NEE: 667 data points (3.81%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10464 data points (59.73%) excluded in total
7056 valid data points (40.27%) remaining.

New sEddyProc class for site 'RU-Fy2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Fy2-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 524 data points (2.99%) set to NA
H: 585 data points (3.34%) set to NA
LE: 535 data points (3.05%) set to NA
NEE: 1096 data points (6.26%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.73%) excluded by growing season filter
3099 additional data points (17.69%) excluded by precipitation filter (7341
 data points = 41.9 % in total)
13563 data points (77.41%) excluded in total
3957 valid data points (22.59%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 524 data points (2.99%) set to NA
H: 585 data points (3.34%) set to NA
LE: 535 data points (3.05%) set to NA
NEE: 1096 data points (6.26%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10464 data points (59.73%) excluded in total
7056 valid data points (40.27%) remaining.

New sEddyProc class for site 'RU-Fy2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 245.14.

Regression of reference temperature R_ref for 4 periods.

Quality control:
TA: 395 data points (2.25%) set to NA
H: 416 data points (2.37%) set to NA
LE: 403 data points (2.29%) set to NA
NEE: 835 data points (4.75%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.3%) excluded by growing season filter
2969 additional data points (16.9%) excluded by precipitation filter (7398
 data points = 42.11 % in total)
13913 data points (79.2%) excluded in total
3655 valid data points (20.8%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 395 data points (2.25%) set to NA
H: 416 data points (2.37%) set to NA
LE: 403 data points (2.29%) set to NA
NEE: 835 data points (4.75%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10944 data points (62.3%) excluded in total
6624 valid data points (37.7%) remaining.

New sEddyProc class for site 'RU-Fy2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 113.26.

Regression of reference temperature R_ref for 4 periods.

Quality control:
TA: 338 data points (1.93%) set to NA
H: 648 data points (3.7%) set to NA
LE: 451 data points (2.57%) set to NA
NEE: 1507 data points (8.6%) set to NA
-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
2598 additional data points (14.83%) excluded by precipitation filter (7417
 data points = 42.33 % in total)
13830 data points (78.94%) excluded in total
3690 valid data points (21.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 338 data points (1.93%) set to NA
H: 648 data points (3.7%) set to NA
LE: 451 data points (2.57%) set to NA
NEE: 1507 data points (8.6%) set to NA
-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11232 data points (64.11%) excluded in total
6288 valid data points (35.89%) remaining.

New sEddyProc class for site 'RU-Fy2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Fy2-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1780 data points (10.16%) set to NA
H: 184 data points (1.05%) set to NA
LE: 367 data points (2.09%) set to NA
NEE: 1740 data points (9.93%) set to NA
-------------------------------------------------------------------
Data filtering:
11616 data points (66.3%) excluded by growing season filter
1323 additional data points (7.55%) excluded by precipitation filter (3670
 data points = 20.95 % in total)
12939 data points (73.85%) excluded in total
4581 valid data points (26.15%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1780 data points (10.16%) set to NA
H: 184 data points (1.05%) set to NA
LE: 367 data points (2.09%) set to NA
NEE: 1740 data points (9.93%) set to NA
-------------------------------------------------------------------
Data filtering:
11616 data points (66.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11616 data points (66.3%) excluded in total
5904 valid data points (33.7%) remaining.

New sEddyProc class for site 'RU-Fy2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 122.64.

Regression of reference temperature R_ref for 11 periods.

Quality control:
TA: 7622 data points (43.5%) set to NA
H: 9537 data points (54.43%) set to NA
LE: 9584 data points (54.7%) set to NA
NEE: 10576 data points (60.37%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 31”

-------------------------------------------------------------------
Data filtering:
9696 data points (55.34%) excluded by growing season filter
3126 additional data points (17.84%) excluded by precipitation filter (8071
 data points = 46.07 % in total)
12822 data points (73.18%) excluded in total
4698 valid data points (26.82%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7622 data points (43.5%) set to NA
H: 9537 data points (54.43%) set to NA
LE: 9584 data points (54.7%) set to NA
NEE: 10576 data points (60.37%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 31”

-------------------------------------------------------------------
Data filtering:
9696 data points (55.34%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9696 data points (55.34%) excluded in total
7824 valid data points (44.66%) remaining.

New sEddyProc class for site 'RU-Fy2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 49.34.

Regression of reference temperature R_ref for 44 periods.

Quality control:
TA: 1163 data points (6.62%) set to NA
H: 3935 data points (22.4%) set to NA
LE: 6302 data points (35.87%) set to NA
NEE: 7151 data points (40.7%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.2%) excluded by growing season filter
2826 additional data points (16.09%) excluded by precipitation filter (4965
 data points = 28.26 % in total)
13050 data points (74.28%) excluded in total
4518 valid data points (25.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1163 data points (6.62%) set to NA
H: 3935 data points (22.4%) set to NA
LE: 6302 data points (35.87%) set to NA
NEE: 7151 data points (40.7%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.2%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10224 data points (58.2%) excluded in total
7344 valid data points (41.8%) remaining.

New sEddyProc class for site 'RU-Fy2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 58.01.

Regression of reference temperature R_ref for 12 periods.

[179/329] Processing: RU-Fy3

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: RU-Fy3 | Years: 2017, 2018
Quality control:
TA: 8901 data points (50.8%) set to NA
H: 8792 data points (50.18%) set to NA
LE: 8813 data points (50.3%) set to NA
NEE: 8991 data points (51.32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 153”

-------------------------------------------------------------------
Data filtering:
3840 data points (21.92%) excluded by growing season filter
6320 additional data points (36.07%) excluded by precipitation filter (7847
 data points = 44.79 % in total)
10160 data points (57.99%) excluded in total
7360 valid data points (42.01%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8901 data points (50.8%) set to NA
H: 8792 data points (50.18%) set to NA
LE: 8813 data points (50.3%) set to NA
NEE: 8991 data points (51.32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 153”

-------------------------------------------------------------------
Data filtering:
3840 data points (21.92%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3840 data points (21.92%) excluded in total
13680 valid data points (78.08%) remaining.

New sEddyProc class for site 'RU-Fy3'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 133.76.

Regression of reference temperature R_ref for 15 periods.

Quality control:
TA: 6450 data points (36.82%) set to NA
H: 6410 data points (36.59%) set to NA
LE: 6506 data points (37.13%) set to NA
NEE: 6765 data points (38.61%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 77”

-------------------------------------------------------------------
Data filtering:
12288 data points (70.14%) excluded by growing season filter
2371 additional data points (13.53%) excluded by precipitation filter (6250
 data points = 35.67 % in total)
14659 data points (83.67%) excluded in total
2861 valid data points (16.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6450 data points (36.82%) set to NA
H: 6410 data points (36.59%) set to NA
LE: 6506 data points (37.13%) set to NA
NEE: 6765 data points (38.61%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 77”

-------------------------------------------------------------------
Data filtering:
12288 data points (70.14%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12288 data points (70.14%) excluded in total
5232 valid data points (29.86%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -50, -51 ...”
New sEddyProc class for site 'RU-Fy3'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -50, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 104.3.

Regression of reference temperature R_ref for 27 periods.

[180/329] Processing: RU-Fy4

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: RU-Fy4 | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 5119 data points (29.22%) set to NA
H: 11808 data points (67.4%) set to NA
LE: 11970 data points (68.32%) set to NA
NEE: 11983 data points (68.4%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 133”

-------------------------------------------------------------------
Data filtering:
3792 data points (21.64%) excluded by growing season filter
5626 additional data points (32.11%) excluded by precipitation filter (7089
 data points = 40.46 % in total)
9418 data points (53.76%) excluded in total
8102 valid data points (46.24%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5119 data points (29.22%) set to NA
H: 11808 data points (67.4%) set to NA
LE: 11970 data points (68.32%) set to NA
NEE: 11983 data points (68.4%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 133”

-------------------------------------------------------------------
Data filtering:
3792 data points (21.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3792 data points (21.64%) excluded in total
13728 valid data points (78.36%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -61, -69, -53, -60, -54 ...”
New sEddyProc class for site 'RU-Fy4'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -61, -69, -53, -60, -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 21 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Fy4-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 5045 data points (28.8%) set to NA
H: 8256 data points (47.12%) set to NA
LE: 8281 data points (47.27%) set to NA
NEE: 8704 data points (49.68%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 112”

-------------------------------------------------------------------
Data filtering:
4848 data points (27.67%) excluded by growing season filter
5024 additional data points (28.68%) excluded by precipitation filter (6279
 data points = 35.84 % in total)
9872 data points (56.35%) excluded in total
7648 valid data points (43.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5045 data points (28.8%) set to NA
H: 8256 data points (47.12%) set to NA
LE: 8281 data points (47.27%) set to NA
NEE: 8704 data points (49.68%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 112”

-------------------------------------------------------------------
Data filtering:
4848 data points (27.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4848 data points (27.67%) excluded in total
12672 valid data points (72.33%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 6 cases! Invalid values with 'NEE < -50': -56, -78, -60, -58, -60, -66 ...”
New sEddyProc class for site 'RU-Fy4'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 6 cases! Invalid values with 'NEE < -50': -56, -78, -60, -58, -60, -66 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Fy4-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6870 data points (39.21%) set to NA
H: 4247 data points (24.24%) set to NA
LE: 4412 data points (25.18%) set to NA
NEE: 5237 data points (29.89%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
3051 additional data points (17.41%) excluded by precipitation filter (7545
 data points = 43.07 % in total)
13323 data points (76.04%) excluded in total
4197 valid data points (23.96%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6870 data points (39.21%) set to NA
H: 4247 data points (24.24%) set to NA
LE: 4412 data points (25.18%) set to NA
NEE: 5237 data points (29.89%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10272 data points (58.63%) excluded in total
7248 valid data points (41.37%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 14 cases! Invalid values with 'NEE < -50': -66, -65, -50, -70, -56, -54, -59, -67, -55, -67, -53, -51, -73, -69 ...”
New sEddyProc class for site 'RU-Fy4'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 14 cases! Invalid values with 'NEE < -50': -66, -65, -50, -70, -56, -54, -59, -67, -55, -67, -53, -51, -73, -69 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 84.93.

Regression of reference temperature R_ref for 33 periods.

Quality control:
TA: 848 data points (4.83%) set to NA
H: 853 data points (4.86%) set to NA
LE: 858 data points (4.88%) set to NA
NEE: 981 data points (5.58%) set to NA
-------------------------------------------------------------------
Data filtering:
10704 data points (60.93%) excluded by growing season filter
1954 additional data points (11.12%) excluded by precipitation filter (5599
 data points = 31.87 % in total)
12658 data points (72.05%) excluded in total
4910 valid data points (27.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 848 data points (4.83%) set to NA
H: 853 data points (4.86%) set to NA
LE: 858 data points (4.88%) set to NA
NEE: 981 data points (5.58%) set to NA
-------------------------------------------------------------------
Data filtering:
10704 data points (60.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10704 data points (60.93%) excluded in total
6864 valid data points (39.07%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 13 cases! Invalid values with 'NEE < -50': -52, -51, -70, -51, -53, -58, -55, -51, -68, -53, -51, -57, -78 ...”
New sEddyProc class for site 'RU-Fy4'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 13 cases! Invalid values with 'NEE < -50': -52, -51, -70, -51, -53, -58, -55, -51, -68, -53, -51, -57, -78 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 8 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Fy4-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[181/329] Processing: RU-Fyo

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: RU-Fyo | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 213 data points (1.22%) set to NA
H: 1864 data points (10.64%) set to NA
LE: 1859 data points (10.61%) set to NA
NEE: 2682 data points (15.31%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
2350 additional data points (13.41%) excluded by precipitation filter (6635
 data points = 37.87 % in total)
12286 data points (70.13%) excluded in total
5234 valid data points (29.87%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 213 data points (1.22%) set to NA
H: 1864 data points (10.64%) set to NA
LE: 1859 data points (10.61%) set to NA
NEE: 2682 data points (15.31%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9936 data points (56.71%) excluded in total
7584 valid data points (43.29%) remaining.

New sEddyProc class for site 'RU-Fyo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Fyo-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 19 data points (0.11%) set to NA
LE: 17 data points (0.1%) set to NA
NEE: 244 data points (1.39%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.4%) excluded by growing season filter
3258 additional data points (18.6%) excluded by precipitation filter (4762
 data points = 27.18 % in total)
11562 data points (65.99%) excluded in total
5958 valid data points (34.01%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 19 data points (0.11%) set to NA
LE: 17 data points (0.1%) set to NA
NEE: 244 data points (1.39%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.4%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8304 data points (47.4%) excluded in total
9216 valid data points (52.6%) remaining.

New sEddyProc class for site 'RU-Fyo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Fyo-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 735 data points (4.2%) set to NA
H: 814 data points (4.65%) set to NA
LE: 772 data points (4.41%) set to NA
NEE: 1037 data points (5.92%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
2715 additional data points (15.5%) excluded by precipitation filter (6321
 data points = 36.08 % in total)
12651 data points (72.21%) excluded in total
4869 valid data points (27.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 735 data points (4.2%) set to NA
H: 814 data points (4.65%) set to NA
LE: 772 data points (4.41%) set to NA
NEE: 1037 data points (5.92%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9936 data points (56.71%) excluded in total
7584 valid data points (43.29%) remaining.

New sEddyProc class for site 'RU-Fyo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Fyo-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 194 data points (1.1%) set to NA
H: 629 data points (3.58%) set to NA
LE: 914 data points (5.2%) set to NA
NEE: 1156 data points (6.58%) set to NA
-------------------------------------------------------------------
Data filtering:
8832 data points (50.27%) excluded by growing season filter
3773 additional data points (21.48%) excluded by precipitation filter (6829
 data points = 38.87 % in total)
12605 data points (71.75%) excluded in total
4963 valid data points (28.25%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 194 data points (1.1%) set to NA
H: 629 data points (3.58%) set to NA
LE: 914 data points (5.2%) set to NA
NEE: 1156 data points (6.58%) set to NA
-------------------------------------------------------------------
Data filtering:
8832 data points (50.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8832 data points (50.27%) excluded in total
8736 valid data points (49.73%) remaining.

New sEddyProc class for site 'RU-Fyo'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 312.89.

Regression of reference temperature R_ref for 4 periods.

Quality control:
TA: 58 data points (0.33%) set to NA
H: 110 data points (0.63%) set to NA
LE: 63 data points (0.36%) set to NA
NEE: 400 data points (2.28%) set to NA
-------------------------------------------------------------------
Data filtering:
8544 data points (48.77%) excluded by growing season filter
4099 additional data points (23.4%) excluded by precipitation filter (7625
 data points = 43.52 % in total)
12643 data points (72.16%) excluded in total
4877 valid data points (27.84%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.

Warning message in nlrob(Gs ~ g0 + DwDc * (1 + g1/sqrt(VPD)) * GPP/Ca, data = df, :
“failed to converge in 20 steps”

Quality control:
TA: 58 data points (0.33%) set to NA
H: 110 data points (0.63%) set to NA
LE: 63 data points (0.36%) set to NA
NEE: 400 data points (2.28%) set to NA
-------------------------------------------------------------------
Data filtering:
8544 data points (48.77%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8544 data points (48.77%) excluded in total
8976 valid data points (51.23%) remaining.

New sEddyProc class for site 'RU-Fyo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Fyo-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 477 data points (2.72%) set to NA
LE: 474 data points (2.71%) set to NA
NEE: 738 data points (4.21%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
2219 additional data points (12.67%) excluded by precipitation filter (6200
 data points = 35.39 % in total)
12875 data points (73.49%) excluded in total
4645 valid data points (26.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 477 data points (2.72%) set to NA
LE: 474 data points (2.71%) set to NA
NEE: 738 data points (4.21%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10656 data points (60.82%) excluded in total
6864 valid data points (39.18%) remaining.

New sEddyProc class for site 'RU-Fyo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Fyo-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1057 data points (6.03%) set to NA
H: 1186 data points (6.77%) set to NA
LE: 1125 data points (6.42%) set to NA
NEE: 1595 data points (9.1%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
2897 additional data points (16.54%) excluded by precipitation filter (7337
 data points = 41.88 % in total)
12113 data points (69.14%) excluded in total
5407 valid data points (30.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1057 data points (6.03%) set to NA
H: 1186 data points (6.77%) set to NA
LE: 1125 data points (6.42%) set to NA
NEE: 1595 data points (9.1%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9216 data points (52.6%) excluded in total
8304 valid data points (47.4%) remaining.

New sEddyProc class for site 'RU-Fyo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 8 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for RU-Fyo-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1163 data points (6.62%) set to NA
H: 1322 data points (7.53%) set to NA
LE: 1420 data points (8.08%) set to NA
NEE: 2128 data points (12.11%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.11%) excluded by growing season filter
2815 additional data points (16.02%) excluded by precipitation filter (6211
 data points = 35.35 % in total)
13375 data points (76.13%) excluded in total
4193 valid data points (23.87%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1163 data points (6.62%) set to NA
H: 1322 data points (7.53%) set to NA
LE: 1420 data points (8.08%) set to NA
NEE: 2128 data points (12.11%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10560 data points (60.11%) excluded in total
7008 valid data points (39.89%) remaining.

New sEddyProc class for site 'RU-Fyo'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 130.74.

Regression of reference temperature R_ref for 12 periods.

[182/329] Processing: SE-Deg

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: SE-Deg | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 14384 data points (82.1%) set to NA
H: 14410 data points (82.25%) set to NA
LE: 14399 data points (82.19%) set to NA
NEE: 14422 data points (82.32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7124 additional data points (40.66%) excluded by precipitation filter (7124
 data points = 40.66 % in total)
7124 data points (40.66%) excluded in total
10396 valid data points (59.34%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for SE-Deg-2019”

Quality control:
TA: 0 data points (0%) set to NA
H: 100 data points (0.57%) set to NA
LE: 53 data points (0.3%) set to NA
NEE: 433 data points (2.46%) set to NA
-------------------------------------------------------------------
Data filtering:
12048 data points (68.58%) excluded by growing season filter
2546 additional data points (14.49%) excluded by precipitation filter (7777
 data points = 44.27 % in total)
14594 data points (83.07%) excluded in total
2974 valid data points (16.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 100 data points (0.57%) set to NA
LE: 53 data points (0.3%) set to NA
NEE: 433 data points (2.46%) set to NA
-------------------------------------------------------------------
Data filtering:
12048 data points (68.58%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12048 data points (68.58%) excluded in total
5520 valid data points (31.42%) remaining.

New sEddyProc class for site 'SE-Deg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Deg-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 226 data points (1.29%) set to NA
LE: 395 data points (2.25%) set to NA
NEE: 549 data points (3.13%) set to NA
-------------------------------------------------------------------
Data filtering:
12192 data points (69.59%) excluded by growing season filter
2221 additional data points (12.68%) excluded by precipitation filter (6423
 data points = 36.66 % in total)
14413 data points (82.27%) excluded in total
3107 valid data points (17.73%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 226 data points (1.29%) set to NA
LE: 395 data points (2.25%) set to NA
NEE: 549 data points (3.13%) set to NA
-------------------------------------------------------------------
Data filtering:
12192 data points (69.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12192 data points (69.59%) excluded in total
5328 valid data points (30.41%) remaining.

New sEddyProc class for site 'SE-Deg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Deg-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 283 data points (1.62%) set to NA
H: 249 data points (1.42%) set to NA
LE: 126 data points (0.72%) set to NA
NEE: 524 data points (2.99%) set to NA
-------------------------------------------------------------------
Data filtering:
12000 data points (68.49%) excluded by growing season filter
2215 additional data points (12.64%) excluded by precipitation filter (6422
 data points = 36.66 % in total)
14215 data points (81.14%) excluded in total
3305 valid data points (18.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 283 data points (1.62%) set to NA
H: 249 data points (1.42%) set to NA
LE: 126 data points (0.72%) set to NA
NEE: 524 data points (2.99%) set to NA
-------------------------------------------------------------------
Data filtering:
12000 data points (68.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12000 data points (68.49%) excluded in total
5520 valid data points (31.51%) remaining.

New sEddyProc class for site 'SE-Deg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Deg-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 330 data points (1.88%) set to NA
H: 359 data points (2.05%) set to NA
LE: 261 data points (1.49%) set to NA
NEE: 552 data points (3.15%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.84%) excluded by growing season filter
2793 additional data points (15.94%) excluded by precipitation filter (5772
 data points = 32.95 % in total)
13977 data points (79.78%) excluded in total
3543 valid data points (20.22%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 330 data points (1.88%) set to NA
H: 359 data points (2.05%) set to NA
LE: 261 data points (1.49%) set to NA
NEE: 552 data points (3.15%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11184 data points (63.84%) excluded in total
6336 valid data points (36.16%) remaining.

New sEddyProc class for site 'SE-Deg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Deg-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 7 data points (0.04%) set to NA
H: 100 data points (0.57%) set to NA
LE: 96 data points (0.55%) set to NA
NEE: 264 data points (1.5%) set to NA
-------------------------------------------------------------------
Data filtering:
11376 data points (64.75%) excluded by growing season filter
2707 additional data points (15.41%) excluded by precipitation filter (6103
 data points = 34.74 % in total)
14083 data points (80.16%) excluded in total
3485 valid data points (19.84%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7 data points (0.04%) set to NA
H: 100 data points (0.57%) set to NA
LE: 96 data points (0.55%) set to NA
NEE: 264 data points (1.5%) set to NA
-------------------------------------------------------------------
Data filtering:
11376 data points (64.75%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11376 data points (64.75%) excluded in total
6192 valid data points (35.25%) remaining.

New sEddyProc class for site 'SE-Deg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Deg-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[183/329] Processing: SE-HfM

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: SE-HfM | Years: 2020, 2021, 2022, 2023
Quality control:
TA: 4357 data points (24.8%) set to NA
H: 7716 data points (43.92%) set to NA
LE: 7716 data points (43.92%) set to NA
NEE: 7962 data points (45.32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 134”

-------------------------------------------------------------------
Data filtering:
5040 data points (28.69%) excluded by growing season filter
4826 additional data points (27.47%) excluded by precipitation filter (7823
 data points = 44.53 % in total)
9866 data points (56.16%) excluded in total
7702 valid data points (43.84%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4357 data points (24.8%) set to NA
H: 7716 data points (43.92%) set to NA
LE: 7716 data points (43.92%) set to NA
NEE: 7962 data points (45.32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 134”

-------------------------------------------------------------------
Data filtering:
5040 data points (28.69%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5040 data points (28.69%) excluded in total
12528 valid data points (71.31%) remaining.

New sEddyProc class for site 'SE-HfM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-HfM-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 11 data points (0.06%) set to NA
LE: 12 data points (0.07%) set to NA
NEE: 112 data points (0.64%) set to NA
-------------------------------------------------------------------
Data filtering:
12336 data points (70.41%) excluded by growing season filter
2110 additional data points (12.04%) excluded by precipitation filter (5046
 data points = 28.8 % in total)
14446 data points (82.45%) excluded in total
3074 valid data points (17.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 11 data points (0.06%) set to NA
LE: 12 data points (0.07%) set to NA
NEE: 112 data points (0.64%) set to NA
-------------------------------------------------------------------
Data filtering:
12336 data points (70.41%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12336 data points (70.41%) excluded in total
5184 valid data points (29.59%) remaining.

New sEddyProc class for site 'SE-HfM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-HfM-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 152 data points (0.87%) set to NA
LE: 153 data points (0.87%) set to NA
NEE: 212 data points (1.21%) set to NA
-------------------------------------------------------------------
Data filtering:
12288 data points (70.14%) excluded by growing season filter
2292 additional data points (13.08%) excluded by precipitation filter (4473
 data points = 25.53 % in total)
14580 data points (83.22%) excluded in total
2940 valid data points (16.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 152 data points (0.87%) set to NA
LE: 153 data points (0.87%) set to NA
NEE: 212 data points (1.21%) set to NA
-------------------------------------------------------------------
Data filtering:
12288 data points (70.14%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12288 data points (70.14%) excluded in total
5232 valid data points (29.86%) remaining.

New sEddyProc class for site 'SE-HfM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-HfM-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 4657 data points (26.58%) set to NA
LE: 4653 data points (26.56%) set to NA
NEE: 4697 data points (26.81%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.53%) excluded by growing season filter
3742 additional data points (21.36%) excluded by precipitation filter (4460
 data points = 25.46 % in total)
13822 data points (78.89%) excluded in total
3698 valid data points (21.11%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 4657 data points (26.58%) set to NA
LE: 4653 data points (26.56%) set to NA
NEE: 4697 data points (26.81%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.53%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10080 data points (57.53%) excluded in total
7440 valid data points (42.47%) remaining.

New sEddyProc class for site 'SE-HfM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-HfM-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[184/329] Processing: SE-Hmr

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: SE-Hmr | Years: 2020, 2021, 2022, 2023
Quality control:
TA: 4357 data points (24.8%) set to NA
H: 4929 data points (28.06%) set to NA
LE: 4923 data points (28.02%) set to NA
NEE: 5065 data points (28.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 81”

-------------------------------------------------------------------
Data filtering:
12336 data points (70.22%) excluded by growing season filter
2471 additional data points (14.07%) excluded by precipitation filter (8241
 data points = 46.91 % in total)
14807 data points (84.28%) excluded in total
2761 valid data points (15.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4357 data points (24.8%) set to NA
H: 4929 data points (28.06%) set to NA
LE: 4923 data points (28.02%) set to NA
NEE: 5065 data points (28.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 81”

-------------------------------------------------------------------
Data filtering:
12336 data points (70.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12336 data points (70.22%) excluded in total
5232 valid data points (29.78%) remaining.

New sEddyProc class for site 'SE-Hmr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Hmr-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1116 data points (6.37%) set to NA
LE: 1118 data points (6.38%) set to NA
NEE: 1467 data points (8.37%) set to NA
-------------------------------------------------------------------
Data filtering:
12432 data points (70.96%) excluded by growing season filter
2439 additional data points (13.92%) excluded by precipitation filter (6051
 data points = 34.54 % in total)
14871 data points (84.88%) excluded in total
2649 valid data points (15.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1116 data points (6.37%) set to NA
LE: 1118 data points (6.38%) set to NA
NEE: 1467 data points (8.37%) set to NA
-------------------------------------------------------------------
Data filtering:
12432 data points (70.96%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12432 data points (70.96%) excluded in total
5088 valid data points (29.04%) remaining.

New sEddyProc class for site 'SE-Hmr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Hmr-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 443 data points (2.53%) set to NA
LE: 441 data points (2.52%) set to NA
NEE: 601 data points (3.43%) set to NA
-------------------------------------------------------------------
Data filtering:
12192 data points (69.59%) excluded by growing season filter
2657 additional data points (15.17%) excluded by precipitation filter (5193
 data points = 29.64 % in total)
14849 data points (84.75%) excluded in total
2671 valid data points (15.25%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 443 data points (2.53%) set to NA
LE: 441 data points (2.52%) set to NA
NEE: 601 data points (3.43%) set to NA
-------------------------------------------------------------------
Data filtering:
12192 data points (69.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12192 data points (69.59%) excluded in total
5328 valid data points (30.41%) remaining.

New sEddyProc class for site 'SE-Hmr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Hmr-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2408 data points (13.74%) set to NA
LE: 2406 data points (13.73%) set to NA
NEE: 2692 data points (15.37%) set to NA
-------------------------------------------------------------------
Data filtering:
10848 data points (61.92%) excluded by growing season filter
3104 additional data points (17.72%) excluded by precipitation filter (5269
 data points = 30.07 % in total)
13952 data points (79.63%) excluded in total
3568 valid data points (20.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2408 data points (13.74%) set to NA
LE: 2406 data points (13.73%) set to NA
NEE: 2692 data points (15.37%) set to NA
-------------------------------------------------------------------
Data filtering:
10848 data points (61.92%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10848 data points (61.92%) excluded in total
6672 valid data points (38.08%) remaining.

New sEddyProc class for site 'SE-Hmr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Hmr-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[185/329] Processing: SE-Htm

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: SE-Htm | Years: 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 5256 data points (30%) set to NA
H: 5246 data points (29.94%) set to NA
LE: 5231 data points (29.86%) set to NA
NEE: 5563 data points (31.75%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 98”

-------------------------------------------------------------------
Data filtering:
3456 data points (19.73%) excluded by growing season filter
5076 additional data points (28.97%) excluded by precipitation filter (6967
 data points = 39.77 % in total)
8532 data points (48.7%) excluded in total
8988 valid data points (51.3%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5256 data points (30%) set to NA
H: 5246 data points (29.94%) set to NA
LE: 5231 data points (29.86%) set to NA
NEE: 5563 data points (31.75%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 98”

-------------------------------------------------------------------
Data filtering:
3456 data points (19.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3456 data points (19.73%) excluded in total
14064 valid data points (80.27%) remaining.

New sEddyProc class for site 'SE-Htm'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 159.31.

Regression of reference temperature R_ref for 6 periods.

Quality control:
TA: 6 data points (0.03%) set to NA
H: 55 data points (0.31%) set to NA
LE: 32 data points (0.18%) set to NA
NEE: 177 data points (1.01%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.85%) excluded by growing season filter
4395 additional data points (25.09%) excluded by precipitation filter (9751
 data points = 55.66 % in total)
12603 data points (71.93%) excluded in total
4917 valid data points (28.07%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6 data points (0.03%) set to NA
H: 55 data points (0.31%) set to NA
LE: 32 data points (0.18%) set to NA
NEE: 177 data points (1.01%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8208 data points (46.85%) excluded in total
9312 valid data points (53.15%) remaining.

New sEddyProc class for site 'SE-Htm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Htm-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 67 data points (0.38%) set to NA
H: 110 data points (0.63%) set to NA
LE: 79 data points (0.45%) set to NA
NEE: 378 data points (2.15%) set to NA
-------------------------------------------------------------------
Data filtering:
7488 data points (42.62%) excluded by growing season filter
4227 additional data points (24.06%) excluded by precipitation filter (9472
 data points = 53.92 % in total)
11715 data points (66.68%) excluded in total
5853 valid data points (33.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 67 data points (0.38%) set to NA
H: 110 data points (0.63%) set to NA
LE: 79 data points (0.45%) set to NA
NEE: 378 data points (2.15%) set to NA
-------------------------------------------------------------------
Data filtering:
7488 data points (42.62%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7488 data points (42.62%) excluded in total
10080 valid data points (57.38%) remaining.

New sEddyProc class for site 'SE-Htm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Htm-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1370 data points (7.82%) set to NA
H: 86 data points (0.49%) set to NA
LE: 56 data points (0.32%) set to NA
NEE: 505 data points (2.88%) set to NA
-------------------------------------------------------------------
Data filtering:
8640 data points (49.32%) excluded by growing season filter
3532 additional data points (20.16%) excluded by precipitation filter (7964
 data points = 45.46 % in total)
12172 data points (69.47%) excluded in total
5348 valid data points (30.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1370 data points (7.82%) set to NA
H: 86 data points (0.49%) set to NA
LE: 56 data points (0.32%) set to NA
NEE: 505 data points (2.88%) set to NA
-------------------------------------------------------------------
Data filtering:
8640 data points (49.32%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8640 data points (49.32%) excluded in total
8880 valid data points (50.68%) remaining.

New sEddyProc class for site 'SE-Htm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Htm-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 33 data points (0.19%) set to NA
H: 169 data points (0.96%) set to NA
LE: 132 data points (0.75%) set to NA
NEE: 975 data points (5.57%) set to NA
-------------------------------------------------------------------
Data filtering:
7776 data points (44.38%) excluded by growing season filter
4104 additional data points (23.42%) excluded by precipitation filter (8196
 data points = 46.78 % in total)
11880 data points (67.81%) excluded in total
5640 valid data points (32.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 33 data points (0.19%) set to NA
H: 169 data points (0.96%) set to NA
LE: 132 data points (0.75%) set to NA
NEE: 975 data points (5.57%) set to NA
-------------------------------------------------------------------
Data filtering:
7776 data points (44.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7776 data points (44.38%) excluded in total
9744 valid data points (55.62%) remaining.

New sEddyProc class for site 'SE-Htm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Htm-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 973 data points (5.55%) set to NA
H: 122 data points (0.7%) set to NA
LE: 75 data points (0.43%) set to NA
NEE: 1070 data points (6.11%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.67%) excluded by growing season filter
3988 additional data points (22.76%) excluded by precipitation filter (9038
 data points = 51.59 % in total)
12340 data points (70.43%) excluded in total
5180 valid data points (29.57%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 973 data points (5.55%) set to NA
H: 122 data points (0.7%) set to NA
LE: 75 data points (0.43%) set to NA
NEE: 1070 data points (6.11%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8352 data points (47.67%) excluded in total
9168 valid data points (52.33%) remaining.

New sEddyProc class for site 'SE-Htm'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 168.62.

Regression of reference temperature R_ref for 6 periods.

Quality control:
TA: 131 data points (0.75%) set to NA
H: 71 data points (0.4%) set to NA
LE: 44 data points (0.25%) set to NA
NEE: 772 data points (4.39%) set to NA
-------------------------------------------------------------------
Data filtering:
8016 data points (45.63%) excluded by growing season filter
4402 additional data points (25.06%) excluded by precipitation filter (8937
 data points = 50.87 % in total)
12418 data points (70.69%) excluded in total
5150 valid data points (29.31%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 131 data points (0.75%) set to NA
H: 71 data points (0.4%) set to NA
LE: 44 data points (0.25%) set to NA
NEE: 772 data points (4.39%) set to NA
-------------------------------------------------------------------
Data filtering:
8016 data points (45.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8016 data points (45.63%) excluded in total
9552 valid data points (54.37%) remaining.

New sEddyProc class for site 'SE-Htm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Htm-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[186/329] Processing: SE-Nor

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: SE-Nor | Years: 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 14816 data points (84.57%) set to NA
H: 14816 data points (84.57%) set to NA
LE: 14816 data points (84.57%) set to NA
NEE: 14875 data points (84.9%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5022 additional data points (28.66%) excluded by precipitation filter (5022
 data points = 28.66 % in total)
5022 data points (28.66%) excluded in total
12498 valid data points (71.34%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for SE-Nor-2018”

Quality control:
TA: 20 data points (0.11%) set to NA
H: 84 data points (0.48%) set to NA
LE: 78 data points (0.45%) set to NA
NEE: 438 data points (2.5%) set to NA
-------------------------------------------------------------------
Data filtering:
8544 data points (48.77%) excluded by growing season filter
3575 additional data points (20.41%) excluded by precipitation filter (7657
 data points = 43.7 % in total)
12119 data points (69.17%) excluded in total
5401 valid data points (30.83%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 20 data points (0.11%) set to NA
H: 84 data points (0.48%) set to NA
LE: 78 data points (0.45%) set to NA
NEE: 438 data points (2.5%) set to NA
-------------------------------------------------------------------
Data filtering:
8544 data points (48.77%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8544 data points (48.77%) excluded in total
8976 valid data points (51.23%) remaining.

New sEddyProc class for site 'SE-Nor'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Nor-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 148 data points (0.84%) set to NA
H: 86 data points (0.49%) set to NA
LE: 63 data points (0.36%) set to NA
NEE: 546 data points (3.11%) set to NA
-------------------------------------------------------------------
Data filtering:
9168 data points (52.19%) excluded by growing season filter
2905 additional data points (16.54%) excluded by precipitation filter (6660
 data points = 37.91 % in total)
12073 data points (68.72%) excluded in total
5495 valid data points (31.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 148 data points (0.84%) set to NA
H: 86 data points (0.49%) set to NA
LE: 63 data points (0.36%) set to NA
NEE: 546 data points (3.11%) set to NA
-------------------------------------------------------------------
Data filtering:
9168 data points (52.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9168 data points (52.19%) excluded in total
8400 valid data points (47.81%) remaining.

New sEddyProc class for site 'SE-Nor'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Nor-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 47 data points (0.27%) set to NA
H: 84 data points (0.48%) set to NA
LE: 103 data points (0.59%) set to NA
NEE: 607 data points (3.46%) set to NA
-------------------------------------------------------------------
Data filtering:
8448 data points (48.22%) excluded by growing season filter
3317 additional data points (18.93%) excluded by precipitation filter (5763
 data points = 32.89 % in total)
11765 data points (67.15%) excluded in total
5755 valid data points (32.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 47 data points (0.27%) set to NA
H: 84 data points (0.48%) set to NA
LE: 103 data points (0.59%) set to NA
NEE: 607 data points (3.46%) set to NA
-------------------------------------------------------------------
Data filtering:
8448 data points (48.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8448 data points (48.22%) excluded in total
9072 valid data points (51.78%) remaining.

New sEddyProc class for site 'SE-Nor'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Nor-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1 data points (0.01%) set to NA
H: 68 data points (0.39%) set to NA
LE: 35 data points (0.2%) set to NA
NEE: 226 data points (1.29%) set to NA
-------------------------------------------------------------------
Data filtering:
8976 data points (51.23%) excluded by growing season filter
3375 additional data points (19.26%) excluded by precipitation filter (6646
 data points = 37.93 % in total)
12351 data points (70.5%) excluded in total
5169 valid data points (29.5%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1 data points (0.01%) set to NA
H: 68 data points (0.39%) set to NA
LE: 35 data points (0.2%) set to NA
NEE: 226 data points (1.29%) set to NA
-------------------------------------------------------------------
Data filtering:
8976 data points (51.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8976 data points (51.23%) excluded in total
8544 valid data points (48.77%) remaining.

New sEddyProc class for site 'SE-Nor'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Nor-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 948 data points (5.41%) set to NA
H: 178 data points (1.02%) set to NA
LE: 139 data points (0.79%) set to NA
NEE: 937 data points (5.35%) set to NA
-------------------------------------------------------------------
Data filtering:
10368 data points (59.18%) excluded by growing season filter
1704 additional data points (9.73%) excluded by precipitation filter (6244
 data points = 35.64 % in total)
12072 data points (68.9%) excluded in total
5448 valid data points (31.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 948 data points (5.41%) set to NA
H: 178 data points (1.02%) set to NA
LE: 139 data points (0.79%) set to NA
NEE: 937 data points (5.35%) set to NA
-------------------------------------------------------------------
Data filtering:
10368 data points (59.18%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10368 data points (59.18%) excluded in total
7152 valid data points (40.82%) remaining.

New sEddyProc class for site 'SE-Nor'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 77.04.

Regression of reference temperature R_ref for 4 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 77 data points (0.44%) set to NA
LE: 51 data points (0.29%) set to NA
NEE: 376 data points (2.14%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.38%) excluded by growing season filter
2981 additional data points (16.97%) excluded by precipitation filter (6361
 data points = 36.21 % in total)
13061 data points (74.35%) excluded in total
4507 valid data points (25.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 77 data points (0.44%) set to NA
LE: 51 data points (0.29%) set to NA
NEE: 376 data points (2.14%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10080 data points (57.38%) excluded in total
7488 valid data points (42.62%) remaining.

New sEddyProc class for site 'SE-Nor'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Nor-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[187/329] Processing: SE-Ros

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: SE-Ros | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 0 data points (0%) set to NA
H: 35 data points (0.2%) set to NA
LE: 31 data points (0.18%) set to NA
NEE: 491 data points (2.8%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.84%) excluded by growing season filter
2972 additional data points (16.96%) excluded by precipitation filter (8009
 data points = 45.71 % in total)
14156 data points (80.8%) excluded in total
3364 valid data points (19.2%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 35 data points (0.2%) set to NA
LE: 31 data points (0.18%) set to NA
NEE: 491 data points (2.8%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11184 data points (63.84%) excluded in total
6336 valid data points (36.16%) remaining.

New sEddyProc class for site 'SE-Ros'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Ros-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 17 data points (0.1%) set to NA
LE: 2 data points (0.01%) set to NA
NEE: 365 data points (2.08%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.15%) excluded by growing season filter
3961 additional data points (22.61%) excluded by precipitation filter (9138
 data points = 52.16 % in total)
13273 data points (75.76%) excluded in total
4247 valid data points (24.24%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 17 data points (0.1%) set to NA
LE: 2 data points (0.01%) set to NA
NEE: 365 data points (2.08%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9312 data points (53.15%) excluded in total
8208 valid data points (46.85%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -61 ...”
New sEddyProc class for site 'SE-Ros'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -61 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Ros-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 950 data points (5.42%) set to NA
LE: 990 data points (5.65%) set to NA
NEE: 1564 data points (8.93%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.78%) excluded by growing season filter
3981 additional data points (22.72%) excluded by precipitation filter (9072
 data points = 51.78 % in total)
13053 data points (74.5%) excluded in total
4467 valid data points (25.5%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 950 data points (5.42%) set to NA
LE: 990 data points (5.65%) set to NA
NEE: 1564 data points (8.93%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.78%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9072 data points (51.78%) excluded in total
8448 valid data points (48.22%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 11 cases! Invalid values with 'NEE < -50': -62, -58, -58, -65, -79, -79, -70, -65, -76, -75, -59 ...”
New sEddyProc class for site 'SE-Ros'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 11 cases! Invalid values with 'NEE < -50': -62, -58, -58, -65, -79, -79, -70, -65, -76, -75, -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Ros-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 132 data points (0.75%) set to NA
NEE: 433 data points (2.46%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.3%) excluded by growing season filter
3040 additional data points (17.3%) excluded by precipitation filter (10042
 data points = 57.16 % in total)
13984 data points (79.6%) excluded in total
3584 valid data points (20.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 132 data points (0.75%) set to NA
NEE: 433 data points (2.46%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10944 data points (62.3%) excluded in total
6624 valid data points (37.7%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -62, -61, -53 ...”
New sEddyProc class for site 'SE-Ros'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -62, -61, -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Ros-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[188/329] Processing: SE-Srj

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: SE-Srj | Years: 2020, 2021, 2022, 2023
Quality control:
TA: 4357 data points (24.8%) set to NA
H: 4360 data points (24.82%) set to NA
LE: 4360 data points (24.82%) set to NA
NEE: 4517 data points (25.71%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 81”

-------------------------------------------------------------------
Data filtering:
12384 data points (70.49%) excluded by growing season filter
2628 additional data points (14.96%) excluded by precipitation filter (8633
 data points = 49.14 % in total)
15012 data points (85.45%) excluded in total
2556 valid data points (14.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4357 data points (24.8%) set to NA
H: 4360 data points (24.82%) set to NA
LE: 4360 data points (24.82%) set to NA
NEE: 4517 data points (25.71%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 81”

-------------------------------------------------------------------
Data filtering:
12384 data points (70.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12384 data points (70.49%) excluded in total
5184 valid data points (29.51%) remaining.

New sEddyProc class for site 'SE-Srj'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Srj-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 47 data points (0.27%) set to NA
LE: 59 data points (0.34%) set to NA
NEE: 187 data points (1.07%) set to NA
-------------------------------------------------------------------
Data filtering:
12000 data points (68.49%) excluded by growing season filter
2508 additional data points (14.32%) excluded by precipitation filter (6237
 data points = 35.6 % in total)
14508 data points (82.81%) excluded in total
3012 valid data points (17.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 47 data points (0.27%) set to NA
LE: 59 data points (0.34%) set to NA
NEE: 187 data points (1.07%) set to NA
-------------------------------------------------------------------
Data filtering:
12000 data points (68.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12000 data points (68.49%) excluded in total
5520 valid data points (31.51%) remaining.

New sEddyProc class for site 'SE-Srj'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Srj-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 4284 data points (24.45%) set to NA
LE: 4283 data points (24.45%) set to NA
NEE: 4346 data points (24.81%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 24”

-------------------------------------------------------------------
Data filtering:
11856 data points (67.67%) excluded by growing season filter
2678 additional data points (15.29%) excluded by precipitation filter (5531
 data points = 31.57 % in total)
14534 data points (82.96%) excluded in total
2986 valid data points (17.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 4284 data points (24.45%) set to NA
LE: 4283 data points (24.45%) set to NA
NEE: 4346 data points (24.81%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 24”

-------------------------------------------------------------------
Data filtering:
11856 data points (67.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11856 data points (67.67%) excluded in total
5664 valid data points (32.33%) remaining.

New sEddyProc class for site 'SE-Srj'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Srj-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 8901 data points (50.8%) set to NA
LE: 8905 data points (50.83%) set to NA
NEE: 9123 data points (52.07%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 142”

-------------------------------------------------------------------
Data filtering:
6624 data points (37.81%) excluded by growing season filter
4263 additional data points (24.33%) excluded by precipitation filter (5281
 data points = 30.14 % in total)
10887 data points (62.14%) excluded in total
6633 valid data points (37.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 8901 data points (50.8%) set to NA
LE: 8905 data points (50.83%) set to NA
NEE: 9123 data points (52.07%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 142”

-------------------------------------------------------------------
Data filtering:
6624 data points (37.81%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6624 data points (37.81%) excluded in total
10896 valid data points (62.19%) remaining.

New sEddyProc class for site 'SE-Srj'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Srj-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[189/329] Processing: SE-Sto

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: SE-Sto | Years: 2022, 2023, 2024
Quality control:
TA: 6640 data points (37.9%) set to NA
H: 6662 data points (38.03%) set to NA
LE: 6652 data points (37.97%) set to NA
NEE: 6703 data points (38.26%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 127”

-------------------------------------------------------------------
Data filtering:
13056 data points (74.52%) excluded by growing season filter
2308 additional data points (13.17%) excluded by precipitation filter (6549
 data points = 37.38 % in total)
15364 data points (87.69%) excluded in total
2156 valid data points (12.31%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6640 data points (37.9%) set to NA
H: 6662 data points (38.03%) set to NA
LE: 6652 data points (37.97%) set to NA
NEE: 6703 data points (38.26%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 127”

-------------------------------------------------------------------
Data filtering:
13056 data points (74.52%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13056 data points (74.52%) excluded in total
4464 valid data points (25.48%) remaining.

New sEddyProc class for site 'SE-Sto'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Sto-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1 data points (0.01%) set to NA
H: 238 data points (1.36%) set to NA
LE: 717 data points (4.09%) set to NA
NEE: 1004 data points (5.73%) set to NA
-------------------------------------------------------------------
Data filtering:
12912 data points (73.7%) excluded by growing season filter
1898 additional data points (10.83%) excluded by precipitation filter (5361
 data points = 30.6 % in total)
14810 data points (84.53%) excluded in total
2710 valid data points (15.47%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1 data points (0.01%) set to NA
H: 238 data points (1.36%) set to NA
LE: 717 data points (4.09%) set to NA
NEE: 1004 data points (5.73%) set to NA
-------------------------------------------------------------------
Data filtering:
12912 data points (73.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12912 data points (73.7%) excluded in total
4608 valid data points (26.3%) remaining.

New sEddyProc class for site 'SE-Sto'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Sto-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 374 data points (2.13%) set to NA
H: 460 data points (2.62%) set to NA
LE: 428 data points (2.44%) set to NA
NEE: 758 data points (4.31%) set to NA
-------------------------------------------------------------------
Data filtering:
12384 data points (70.49%) excluded by growing season filter
2480 additional data points (14.12%) excluded by precipitation filter (5905
 data points = 33.61 % in total)
14864 data points (84.61%) excluded in total
2704 valid data points (15.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 374 data points (2.13%) set to NA
H: 460 data points (2.62%) set to NA
LE: 428 data points (2.44%) set to NA
NEE: 758 data points (4.31%) set to NA
-------------------------------------------------------------------
Data filtering:
12384 data points (70.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12384 data points (70.49%) excluded in total
5184 valid data points (29.51%) remaining.

New sEddyProc class for site 'SE-Sto'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Sto-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[190/329] Processing: SE-Svb

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: SE-Svb | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 3 data points (0.02%) set to NA
H: 9497 data points (54.21%) set to NA
LE: 9795 data points (55.91%) set to NA
NEE: 10523 data points (60.06%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 130”

-------------------------------------------------------------------
Data filtering:
7680 data points (43.84%) excluded by growing season filter
4437 additional data points (25.33%) excluded by precipitation filter (8009
 data points = 45.71 % in total)
12117 data points (69.16%) excluded in total
5403 valid data points (30.84%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (20) for SE-Svb-2017”

Quality control:
TA: 41 data points (0.23%) set to NA
H: 796 data points (4.54%) set to NA
LE: 838 data points (4.78%) set to NA
NEE: 1856 data points (10.59%) set to NA
-------------------------------------------------------------------
Data filtering:
9552 data points (54.52%) excluded by growing season filter
3885 additional data points (22.17%) excluded by precipitation filter (9206
 data points = 52.55 % in total)
13437 data points (76.7%) excluded in total
4083 valid data points (23.3%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 41 data points (0.23%) set to NA
H: 796 data points (4.54%) set to NA
LE: 838 data points (4.78%) set to NA
NEE: 1856 data points (10.59%) set to NA
-------------------------------------------------------------------
Data filtering:
9552 data points (54.52%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9552 data points (54.52%) excluded in total
7968 valid data points (45.48%) remaining.

New sEddyProc class for site 'SE-Svb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Svb-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 159 data points (0.91%) set to NA
H: 93 data points (0.53%) set to NA
LE: 85 data points (0.49%) set to NA
NEE: 796 data points (4.54%) set to NA
-------------------------------------------------------------------
Data filtering:
9696 data points (55.34%) excluded by growing season filter
3641 additional data points (20.78%) excluded by precipitation filter (8197
 data points = 46.79 % in total)
13337 data points (76.12%) excluded in total
4183 valid data points (23.88%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 159 data points (0.91%) set to NA
H: 93 data points (0.53%) set to NA
LE: 85 data points (0.49%) set to NA
NEE: 796 data points (4.54%) set to NA
-------------------------------------------------------------------
Data filtering:
9696 data points (55.34%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9696 data points (55.34%) excluded in total
7824 valid data points (44.66%) remaining.

New sEddyProc class for site 'SE-Svb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Svb-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 535 data points (3.05%) set to NA
LE: 502 data points (2.86%) set to NA
NEE: 1044 data points (5.94%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.56%) excluded by growing season filter
3798 additional data points (21.62%) excluded by precipitation filter (7974
 data points = 45.39 % in total)
14262 data points (81.18%) excluded in total
3306 valid data points (18.82%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 535 data points (3.05%) set to NA
LE: 502 data points (2.86%) set to NA
NEE: 1044 data points (5.94%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10464 data points (59.56%) excluded in total
7104 valid data points (40.44%) remaining.

New sEddyProc class for site 'SE-Svb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Svb-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 15 data points (0.09%) set to NA
H: 119 data points (0.68%) set to NA
LE: 2790 data points (15.92%) set to NA
NEE: 3259 data points (18.6%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.84%) excluded by growing season filter
2462 additional data points (14.05%) excluded by precipitation filter (6209
 data points = 35.44 % in total)
13646 data points (77.89%) excluded in total
3874 valid data points (22.11%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 15 data points (0.09%) set to NA
H: 119 data points (0.68%) set to NA
LE: 2790 data points (15.92%) set to NA
NEE: 3259 data points (18.6%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11184 data points (63.84%) excluded in total
6336 valid data points (36.16%) remaining.

New sEddyProc class for site 'SE-Svb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Svb-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 14 data points (0.08%) set to NA
H: 109 data points (0.62%) set to NA
LE: 71 data points (0.41%) set to NA
NEE: 439 data points (2.51%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
2945 additional data points (16.81%) excluded by precipitation filter (6734
 data points = 38.44 % in total)
13169 data points (75.17%) excluded in total
4351 valid data points (24.83%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 14 data points (0.08%) set to NA
H: 109 data points (0.62%) set to NA
LE: 71 data points (0.41%) set to NA
NEE: 439 data points (2.51%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10224 data points (58.36%) excluded in total
7296 valid data points (41.64%) remaining.

New sEddyProc class for site 'SE-Svb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Svb-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 165 data points (0.94%) set to NA
H: 339 data points (1.93%) set to NA
LE: 250 data points (1.43%) set to NA
NEE: 878 data points (5.01%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (60%) excluded by growing season filter
3031 additional data points (17.3%) excluded by precipitation filter (6829
 data points = 38.98 % in total)
13543 data points (77.3%) excluded in total
3977 valid data points (22.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 165 data points (0.94%) set to NA
H: 339 data points (1.93%) set to NA
LE: 250 data points (1.43%) set to NA
NEE: 878 data points (5.01%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (60%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10512 data points (60%) excluded in total
7008 valid data points (40%) remaining.

New sEddyProc class for site 'SE-Svb'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 91.06.

Regression of reference temperature R_ref for 2 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 104 data points (0.59%) set to NA
LE: 224 data points (1.28%) set to NA
NEE: 819 data points (4.66%) set to NA
-------------------------------------------------------------------
Data filtering:
10368 data points (59.02%) excluded by growing season filter
3462 additional data points (19.71%) excluded by precipitation filter (7247
 data points = 41.25 % in total)
13830 data points (78.72%) excluded in total
3738 valid data points (21.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 104 data points (0.59%) set to NA
LE: 224 data points (1.28%) set to NA
NEE: 819 data points (4.66%) set to NA
-------------------------------------------------------------------
Data filtering:
10368 data points (59.02%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10368 data points (59.02%) excluded in total
7200 valid data points (40.98%) remaining.

New sEddyProc class for site 'SE-Svb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Svb-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[191/329] Processing: SE-Trb

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: SE-Trb | Years: 2021, 2022, 2023
Quality control:
TA: 0 data points (0%) set to NA
H: 1497 data points (8.54%) set to NA
LE: 1495 data points (8.53%) set to NA
NEE: 1685 data points (9.62%) set to NA
-------------------------------------------------------------------
Data filtering:
11952 data points (68.22%) excluded by growing season filter
2950 additional data points (16.84%) excluded by precipitation filter (10390
 data points = 59.3 % in total)
14902 data points (85.06%) excluded in total
2618 valid data points (14.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1497 data points (8.54%) set to NA
LE: 1495 data points (8.53%) set to NA
NEE: 1685 data points (9.62%) set to NA
-------------------------------------------------------------------
Data filtering:
11952 data points (68.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11952 data points (68.22%) excluded in total
5568 valid data points (31.78%) remaining.

New sEddyProc class for site 'SE-Trb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Trb-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 580 data points (3.31%) set to NA
H: 977 data points (5.58%) set to NA
LE: 586 data points (3.34%) set to NA
NEE: 1072 data points (6.12%) set to NA
-------------------------------------------------------------------
Data filtering:
12048 data points (68.77%) excluded by growing season filter
3658 additional data points (20.88%) excluded by precipitation filter (10600
 data points = 60.5 % in total)
15706 data points (89.65%) excluded in total
1814 valid data points (10.35%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 580 data points (3.31%) set to NA
H: 977 data points (5.58%) set to NA
LE: 586 data points (3.34%) set to NA
NEE: 1072 data points (6.12%) set to NA
-------------------------------------------------------------------
Data filtering:
12048 data points (68.77%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12048 data points (68.77%) excluded in total
5472 valid data points (31.23%) remaining.

New sEddyProc class for site 'SE-Trb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Trb-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4019 data points (22.94%) set to NA
H: 9242 data points (52.75%) set to NA
LE: 9240 data points (52.74%) set to NA
NEE: 9472 data points (54.06%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 119”

-------------------------------------------------------------------
Data filtering:
5856 data points (33.42%) excluded by growing season filter
6918 additional data points (39.49%) excluded by precipitation filter (9960
 data points = 56.85 % in total)
12774 data points (72.91%) excluded in total
4746 valid data points (27.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4019 data points (22.94%) set to NA
H: 9242 data points (52.75%) set to NA
LE: 9240 data points (52.74%) set to NA
NEE: 9472 data points (54.06%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 119”

-------------------------------------------------------------------
Data filtering:
5856 data points (33.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5856 data points (33.42%) excluded in total
11664 valid data points (66.58%) remaining.

New sEddyProc class for site 'SE-Trb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 13 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for SE-Trb-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[192/329] Processing: UK-AMo

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: UK-AMo | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 61 data points (0.35%) set to NA
LE: 68 data points (0.39%) set to NA
NEE: 300 data points (1.71%) set to NA
-------------------------------------------------------------------
Data filtering:
9600 data points (54.79%) excluded by growing season filter
5998 additional data points (34.24%) excluded by precipitation filter (12943
 data points = 73.88 % in total)
15598 data points (89.03%) excluded in total
1922 valid data points (10.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 61 data points (0.35%) set to NA
LE: 68 data points (0.39%) set to NA
NEE: 300 data points (1.71%) set to NA
-------------------------------------------------------------------
Data filtering:
9600 data points (54.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9600 data points (54.79%) excluded in total
7920 valid data points (45.21%) remaining.

New sEddyProc class for site 'UK-AMo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for UK-AMo-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 213 data points (1.22%) set to NA
LE: 214 data points (1.22%) set to NA
NEE: 425 data points (2.43%) set to NA
-------------------------------------------------------------------
Data filtering:
12720 data points (72.6%) excluded by growing season filter
2695 additional data points (15.38%) excluded by precipitation filter (12699
 data points = 72.48 % in total)
15415 data points (87.99%) excluded in total
2105 valid data points (12.01%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 213 data points (1.22%) set to NA
LE: 214 data points (1.22%) set to NA
NEE: 425 data points (2.43%) set to NA
-------------------------------------------------------------------
Data filtering:
12720 data points (72.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12720 data points (72.6%) excluded in total
4800 valid data points (27.4%) remaining.

New sEddyProc class for site 'UK-AMo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for UK-AMo-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 62 data points (0.35%) set to NA
LE: 71 data points (0.41%) set to NA
NEE: 362 data points (2.07%) set to NA
-------------------------------------------------------------------
Data filtering:
9456 data points (53.97%) excluded by growing season filter
5799 additional data points (33.1%) excluded by precipitation filter (12739
 data points = 72.71 % in total)
15255 data points (87.07%) excluded in total
2265 valid data points (12.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 62 data points (0.35%) set to NA
LE: 71 data points (0.41%) set to NA
NEE: 362 data points (2.07%) set to NA
-------------------------------------------------------------------
Data filtering:
9456 data points (53.97%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9456 data points (53.97%) excluded in total
8064 valid data points (46.03%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
New sEddyProc class for site 'UK-AMo'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for UK-AMo-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 179 data points (1.02%) set to NA
LE: 211 data points (1.2%) set to NA
NEE: 1473 data points (8.38%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.01%) excluded by growing season filter
5884 additional data points (33.49%) excluded by precipitation filter (13542
 data points = 77.08 % in total)
15196 data points (86.5%) excluded in total
2372 valid data points (13.5%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 179 data points (1.02%) set to NA
LE: 211 data points (1.2%) set to NA
NEE: 1473 data points (8.38%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.01%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9312 data points (53.01%) excluded in total
8256 valid data points (46.99%) remaining.

New sEddyProc class for site 'UK-AMo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for UK-AMo-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 85 data points (0.49%) set to NA
H: 21 data points (0.12%) set to NA
LE: 17 data points (0.1%) set to NA
NEE: 383 data points (2.19%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
3180 additional data points (18.15%) excluded by precipitation filter (10737
 data points = 61.28 % in total)
13404 data points (76.51%) excluded in total
4116 valid data points (23.49%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 85 data points (0.49%) set to NA
H: 21 data points (0.12%) set to NA
LE: 17 data points (0.1%) set to NA
NEE: 383 data points (2.19%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10224 data points (58.36%) excluded in total
7296 valid data points (41.64%) remaining.

New sEddyProc class for site 'UK-AMo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for UK-AMo-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 24 data points (0.14%) set to NA
H: 96 data points (0.55%) set to NA
LE: 21 data points (0.12%) set to NA
NEE: 7040 data points (40.18%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 55”

-------------------------------------------------------------------
Data filtering:
7584 data points (43.29%) excluded by growing season filter
6719 additional data points (38.35%) excluded by precipitation filter (13033
 data points = 74.39 % in total)
14303 data points (81.64%) excluded in total
3217 valid data points (18.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 24 data points (0.14%) set to NA
H: 96 data points (0.55%) set to NA
LE: 21 data points (0.12%) set to NA
NEE: 7040 data points (40.18%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 55”

-------------------------------------------------------------------
Data filtering:
7584 data points (43.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7584 data points (43.29%) excluded in total
9936 valid data points (56.71%) remaining.

New sEddyProc class for site 'UK-AMo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for UK-AMo-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 31 data points (0.18%) set to NA
LE: 35 data points (0.2%) set to NA
NEE: 241 data points (1.38%) set to NA
-------------------------------------------------------------------
Data filtering:
10176 data points (58.08%) excluded by growing season filter
5760 additional data points (32.88%) excluded by precipitation filter (13564
 data points = 77.42 % in total)
15936 data points (90.96%) excluded in total
1584 valid data points (9.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 31 data points (0.18%) set to NA
LE: 35 data points (0.2%) set to NA
NEE: 241 data points (1.38%) set to NA
-------------------------------------------------------------------
Data filtering:
10176 data points (58.08%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10176 data points (58.08%) excluded in total
7344 valid data points (41.92%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -65 ...”
New sEddyProc class for site 'UK-AMo'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -65 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for UK-AMo-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 9 data points (0.05%) set to NA
LE: 8 data points (0.05%) set to NA
NEE: 644 data points (3.67%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.11%) excluded by growing season filter
3973 additional data points (22.61%) excluded by precipitation filter (10907
 data points = 62.08 % in total)
14533 data points (82.72%) excluded in total
3035 valid data points (17.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 9 data points (0.05%) set to NA
LE: 8 data points (0.05%) set to NA
NEE: 644 data points (3.67%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10560 data points (60.11%) excluded in total
7008 valid data points (39.89%) remaining.

New sEddyProc class for site 'UK-AMo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for UK-AMo-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[193/329] Processing: US-ALQ

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-ALQ | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 17520 data points (100%) set to NA
H: 14290 data points (81.56%) set to NA
LE: 14347 data points (81.89%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9886 additional data points (56.43%) excluded by precipitation filter (9886
 data points = 56.43 % in total)
9886 data points (56.43%) excluded in total
7634 valid data points (43.57%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 17520 data points (100%) set to NA
H: 14290 data points (81.56%) set to NA
LE: 14347 data points (81.89%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-ALQ'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ALQ-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 13476 data points (76.92%) set to NA
H: 13528 data points (77.21%) set to NA
LE: 13814 data points (78.85%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7712 additional data points (44.02%) excluded by precipitation filter (7712
 data points = 44.02 % in total)
7712 data points (44.02%) excluded in total
9808 valid data points (55.98%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 13476 data points (76.92%) set to NA
H: 13528 data points (77.21%) set to NA
LE: 13814 data points (78.85%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-ALQ'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ALQ-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1281 data points (7.31%) set to NA
H: 1314 data points (7.5%) set to NA
LE: 1367 data points (7.8%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9039 additional data points (51.59%) excluded by precipitation filter (9039
 data points = 51.59 % in total)
9039 data points (51.59%) excluded in total
8481 valid data points (48.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 1281 data points (7.31%) set to NA
H: 1314 data points (7.5%) set to NA
LE: 1367 data points (7.8%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-ALQ'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ALQ-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 184 data points (1.05%) set to NA
H: 219 data points (1.25%) set to NA
LE: 250 data points (1.42%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8124 additional data points (46.24%) excluded by precipitation filter (8124
 data points = 46.24 % in total)
8124 data points (46.24%) excluded in total
9444 valid data points (53.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 184 data points (1.05%) set to NA
H: 219 data points (1.25%) set to NA
LE: 250 data points (1.42%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-ALQ'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ALQ-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 184 data points (1.05%) set to NA
H: 211 data points (1.2%) set to NA
LE: 635 data points (3.62%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8306 additional data points (47.41%) excluded by precipitation filter (8306
 data points = 47.41 % in total)
8306 data points (47.41%) excluded in total
9214 valid data points (52.59%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 184 data points (1.05%) set to NA
H: 211 data points (1.2%) set to NA
LE: 635 data points (3.62%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-ALQ'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ALQ-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 304 data points (1.74%) set to NA
H: 364 data points (2.08%) set to NA
LE: 426 data points (2.43%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8098 additional data points (46.22%) excluded by precipitation filter (8098
 data points = 46.22 % in total)
8098 data points (46.22%) excluded in total
9422 valid data points (53.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 304 data points (1.74%) set to NA
H: 364 data points (2.08%) set to NA
LE: 426 data points (2.43%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-ALQ'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ALQ-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1648 data points (9.41%) set to NA
H: 1793 data points (10.23%) set to NA
LE: 1882 data points (10.74%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7161 additional data points (40.87%) excluded by precipitation filter (7161
 data points = 40.87 % in total)
7161 data points (40.87%) excluded in total
10359 valid data points (59.13%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 1648 data points (9.41%) set to NA
H: 1793 data points (10.23%) set to NA
LE: 1882 data points (10.74%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-ALQ'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ALQ-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1282 data points (7.3%) set to NA
H: 1569 data points (8.93%) set to NA
LE: 1647 data points (9.38%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6904 additional data points (39.3%) excluded by precipitation filter (6904
 data points = 39.3 % in total)
6904 data points (39.3%) excluded in total
10664 valid data points (60.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 1282 data points (7.3%) set to NA
H: 1569 data points (8.93%) set to NA
LE: 1647 data points (9.38%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-ALQ'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ALQ-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3382 data points (19.3%) set to NA
H: 3456 data points (19.73%) set to NA
LE: 3550 data points (20.26%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6198 additional data points (35.38%) excluded by precipitation filter (6198
 data points = 35.38 % in total)
6198 data points (35.38%) excluded in total
11322 valid data points (64.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 3382 data points (19.3%) set to NA
H: 3456 data points (19.73%) set to NA
LE: 3550 data points (20.26%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-ALQ'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ALQ-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[194/329] Processing: US-Akn

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Akn | Years: 2017, 2018, 2019, 2020, 2021, 2022
Quality control:
TA: 1219 data points (6.96%) set to NA
H: 1223 data points (6.98%) set to NA
LE: 1383 data points (7.89%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2273 additional data points (12.97%) excluded by precipitation filter (2273
 data points = 12.97 % in total)
2273 data points (12.97%) excluded in total
15247 valid data points (87.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1219 data points (6.96%) set to NA
H: 1223 data points (6.98%) set to NA
LE: 1383 data points (7.89%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Akn'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Akn-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 15 data points (0.09%) set to NA
H: 18 data points (0.1%) set to NA
LE: 173 data points (0.99%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2855 additional data points (16.3%) excluded by precipitation filter (2855
 data points = 16.3 % in total)
2855 data points (16.3%) excluded in total
14665 valid data points (83.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 15 data points (0.09%) set to NA
H: 18 data points (0.1%) set to NA
LE: 173 data points (0.99%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Akn'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Akn-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 5103 data points (29.13%) set to NA
H: 5108 data points (29.16%) set to NA
LE: 5202 data points (29.69%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2031 additional data points (11.59%) excluded by precipitation filter (2031
 data points = 11.59 % in total)
2031 data points (11.59%) excluded in total
15489 valid data points (88.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5103 data points (29.13%) set to NA
H: 5108 data points (29.16%) set to NA
LE: 5202 data points (29.69%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Akn'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Akn-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3045 data points (17.33%) set to NA
H: 3046 data points (17.34%) set to NA
LE: 3149 data points (17.92%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2578 additional data points (14.67%) excluded by precipitation filter (2578
 data points = 14.67 % in total)
2578 data points (14.67%) excluded in total
14990 valid data points (85.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3045 data points (17.33%) set to NA
H: 3046 data points (17.34%) set to NA
LE: 3149 data points (17.92%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-Akn'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Akn-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1240 data points (7.08%) set to NA
H: 1245 data points (7.11%) set to NA
LE: 1291 data points (7.37%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2879 additional data points (16.43%) excluded by precipitation filter (2879
 data points = 16.43 % in total)
2879 data points (16.43%) excluded in total
14641 valid data points (83.57%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1240 data points (7.08%) set to NA
H: 1245 data points (7.11%) set to NA
LE: 1291 data points (7.37%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Akn'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Akn-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 11943 data points (68.17%) set to NA
H: 11947 data points (68.19%) set to NA
LE: 11952 data points (68.22%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1001 additional data points (5.71%) excluded by precipitation filter (1001
 data points = 5.71 % in total)
1001 data points (5.71%) excluded in total
16519 valid data points (94.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11943 data points (68.17%) set to NA
H: 11947 data points (68.19%) set to NA
LE: 11952 data points (68.22%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Akn'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Akn-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[195/329] Processing: US-BZB

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-BZB | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 892 data points (5.09%) set to NA
H: 2423 data points (13.83%) set to NA
LE: 2515 data points (14.36%) set to NA
NEE: 5038 data points (28.76%) set to NA
-------------------------------------------------------------------
Data filtering:
11040 data points (63.01%) excluded by growing season filter
2100 additional data points (11.99%) excluded by precipitation filter (3653
 data points = 20.85 % in total)
13140 data points (75%) excluded in total
4380 valid data points (25%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 892 data points (5.09%) set to NA
H: 2423 data points (13.83%) set to NA
LE: 2515 data points (14.36%) set to NA
NEE: 5038 data points (28.76%) set to NA
-------------------------------------------------------------------
Data filtering:
11040 data points (63.01%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11040 data points (63.01%) excluded in total
6480 valid data points (36.99%) remaining.

New sEddyProc class for site 'US-BZB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 11 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-BZB-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1586 data points (9.05%) set to NA
H: 2284 data points (13.04%) set to NA
LE: 2301 data points (13.13%) set to NA
NEE: 2802 data points (15.99%) set to NA
-------------------------------------------------------------------
Data filtering:
11568 data points (66.03%) excluded by growing season filter
2508 additional data points (14.32%) excluded by precipitation filter (4231
 data points = 24.15 % in total)
14076 data points (80.34%) excluded in total
3444 valid data points (19.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1586 data points (9.05%) set to NA
H: 2284 data points (13.04%) set to NA
LE: 2301 data points (13.13%) set to NA
NEE: 2802 data points (15.99%) set to NA
-------------------------------------------------------------------
Data filtering:
11568 data points (66.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11568 data points (66.03%) excluded in total
5952 valid data points (33.97%) remaining.

New sEddyProc class for site 'US-BZB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 10 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-BZB-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 25 data points (0.14%) set to NA
H: 882 data points (5.03%) set to NA
LE: 893 data points (5.1%) set to NA
NEE: 1743 data points (9.95%) set to NA
-------------------------------------------------------------------
Data filtering:
10752 data points (61.37%) excluded by growing season filter
2141 additional data points (12.22%) excluded by precipitation filter (4090
 data points = 23.34 % in total)
12893 data points (73.59%) excluded in total
4627 valid data points (26.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 25 data points (0.14%) set to NA
H: 882 data points (5.03%) set to NA
LE: 893 data points (5.1%) set to NA
NEE: 1743 data points (9.95%) set to NA
-------------------------------------------------------------------
Data filtering:
10752 data points (61.37%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10752 data points (61.37%) excluded in total
6768 valid data points (38.63%) remaining.

New sEddyProc class for site 'US-BZB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-BZB-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 260 data points (1.48%) set to NA
H: 1538 data points (8.75%) set to NA
LE: 1441 data points (8.2%) set to NA
NEE: 1855 data points (10.56%) set to NA
-------------------------------------------------------------------
Data filtering:
10704 data points (60.93%) excluded by growing season filter
2891 additional data points (16.46%) excluded by precipitation filter (4474
 data points = 25.47 % in total)
13595 data points (77.39%) excluded in total
3973 valid data points (22.61%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 260 data points (1.48%) set to NA
H: 1538 data points (8.75%) set to NA
LE: 1441 data points (8.2%) set to NA
NEE: 1855 data points (10.56%) set to NA
-------------------------------------------------------------------
Data filtering:
10704 data points (60.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10704 data points (60.93%) excluded in total
6864 valid data points (39.07%) remaining.

New sEddyProc class for site 'US-BZB'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 87.11.

Regression of reference temperature R_ref for 6 periods.

Quality control:
TA: 67 data points (0.38%) set to NA
H: 629 data points (3.59%) set to NA
LE: 712 data points (4.06%) set to NA
NEE: 1307 data points (7.46%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.19%) excluded by growing season filter
2190 additional data points (12.5%) excluded by precipitation filter (3339
 data points = 19.06 % in total)
13086 data points (74.69%) excluded in total
4434 valid data points (25.31%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 67 data points (0.38%) set to NA
H: 629 data points (3.59%) set to NA
LE: 712 data points (4.06%) set to NA
NEE: 1307 data points (7.46%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10896 data points (62.19%) excluded in total
6624 valid data points (37.81%) remaining.

New sEddyProc class for site 'US-BZB'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 238.14.

Regression of reference temperature R_ref for 2 periods.

Quality control:
TA: 4 data points (0.02%) set to NA
H: 751 data points (4.29%) set to NA
LE: 888 data points (5.07%) set to NA
NEE: 1116 data points (6.37%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
2057 additional data points (11.74%) excluded by precipitation filter (3354
 data points = 19.14 % in total)
13193 data points (75.3%) excluded in total
4327 valid data points (24.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4 data points (0.02%) set to NA
H: 751 data points (4.29%) set to NA
LE: 888 data points (5.07%) set to NA
NEE: 1116 data points (6.37%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11136 data points (63.56%) excluded in total
6384 valid data points (36.44%) remaining.

New sEddyProc class for site 'US-BZB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-BZB-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 421 data points (2.4%) set to NA
LE: 497 data points (2.84%) set to NA
NEE: 754 data points (4.3%) set to NA
-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
2439 additional data points (13.92%) excluded by precipitation filter (3601
 data points = 20.55 % in total)
13527 data points (77.21%) excluded in total
3993 valid data points (22.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 421 data points (2.4%) set to NA
LE: 497 data points (2.84%) set to NA
NEE: 754 data points (4.3%) set to NA
-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11088 data points (63.29%) excluded in total
6432 valid data points (36.71%) remaining.

New sEddyProc class for site 'US-BZB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-BZB-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 66 data points (0.38%) set to NA
H: 2605 data points (14.83%) set to NA
LE: 2732 data points (15.55%) set to NA
NEE: 2974 data points (16.93%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.48%) excluded by growing season filter
2822 additional data points (16.06%) excluded by precipitation filter (3986
 data points = 22.69 % in total)
13622 data points (77.54%) excluded in total
3946 valid data points (22.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 66 data points (0.38%) set to NA
H: 2605 data points (14.83%) set to NA
LE: 2732 data points (15.55%) set to NA
NEE: 2974 data points (16.93%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.48%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10800 data points (61.48%) excluded in total
6768 valid data points (38.52%) remaining.

New sEddyProc class for site 'US-BZB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-BZB-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6528 data points (37.26%) set to NA
H: 6642 data points (37.91%) set to NA
LE: 6642 data points (37.91%) set to NA
NEE: 6715 data points (38.33%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 112”

-------------------------------------------------------------------
Data filtering:
6096 data points (34.79%) excluded by growing season filter
3725 additional data points (21.26%) excluded by precipitation filter (4610
 data points = 26.31 % in total)
9821 data points (56.06%) excluded in total
7699 valid data points (43.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6528 data points (37.26%) set to NA
H: 6642 data points (37.91%) set to NA
LE: 6642 data points (37.91%) set to NA
NEE: 6715 data points (38.33%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 112”

-------------------------------------------------------------------
Data filtering:
6096 data points (34.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6096 data points (34.79%) excluded in total
11424 valid data points (65.21%) remaining.

New sEddyProc class for site 'US-BZB'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 283.16.

Regression of reference temperature R_ref for 10 periods.

[196/329] Processing: US-BZo

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-BZo | Years: 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 5415 data points (30.91%) set to NA
H: 5424 data points (30.96%) set to NA
LE: 5441 data points (31.06%) set to NA
NEE: 5652 data points (32.26%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 86”

-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
2178 additional data points (12.43%) excluded by precipitation filter (3439
 data points = 19.63 % in total)
13266 data points (75.72%) excluded in total
4254 valid data points (24.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5415 data points (30.91%) set to NA
H: 5424 data points (30.96%) set to NA
LE: 5441 data points (31.06%) set to NA
NEE: 5652 data points (32.26%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 86”

-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11088 data points (63.29%) excluded in total
6432 valid data points (36.71%) remaining.

New sEddyProc class for site 'US-BZo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 11 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-BZo-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 580 data points (3.31%) set to NA
H: 691 data points (3.94%) set to NA
LE: 777 data points (4.43%) set to NA
NEE: 1128 data points (6.44%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.47%) excluded by growing season filter
2287 additional data points (13.05%) excluded by precipitation filter (4083
 data points = 23.3 % in total)
13231 data points (75.52%) excluded in total
4289 valid data points (24.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 580 data points (3.31%) set to NA
H: 691 data points (3.94%) set to NA
LE: 777 data points (4.43%) set to NA
NEE: 1128 data points (6.44%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10944 data points (62.47%) excluded in total
6576 valid data points (37.53%) remaining.

New sEddyProc class for site 'US-BZo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 10 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-BZo-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 376 data points (2.14%) set to NA
H: 1628 data points (9.27%) set to NA
LE: 1643 data points (9.35%) set to NA
NEE: 2041 data points (11.62%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.66%) excluded by growing season filter
3024 additional data points (17.21%) excluded by precipitation filter (3938
 data points = 22.42 % in total)
13680 data points (77.87%) excluded in total
3888 valid data points (22.13%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 376 data points (2.14%) set to NA
H: 1628 data points (9.27%) set to NA
LE: 1643 data points (9.35%) set to NA
NEE: 2041 data points (11.62%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.66%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10656 data points (60.66%) excluded in total
6912 valid data points (39.34%) remaining.

New sEddyProc class for site 'US-BZo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-BZo-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1378 data points (7.87%) set to NA
H: 1651 data points (9.42%) set to NA
LE: 1669 data points (9.53%) set to NA
NEE: 1955 data points (11.16%) set to NA
-------------------------------------------------------------------
Data filtering:
12048 data points (68.77%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (468
 data points = 2.67 % in total)
12048 data points (68.77%) excluded in total
5472 valid data points (31.23%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1378 data points (7.87%) set to NA
H: 1651 data points (9.42%) set to NA
LE: 1669 data points (9.53%) set to NA
NEE: 1955 data points (11.16%) set to NA
-------------------------------------------------------------------
Data filtering:
12048 data points (68.77%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12048 data points (68.77%) excluded in total
5472 valid data points (31.23%) remaining.

New sEddyProc class for site 'US-BZo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-BZo-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1999 data points (11.41%) set to NA
H: 2020 data points (11.53%) set to NA
LE: 2030 data points (11.59%) set to NA
NEE: 2313 data points (13.2%) set to NA
-------------------------------------------------------------------
Data filtering:
12192 data points (69.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (635
 data points = 3.62 % in total)
12192 data points (69.59%) excluded in total
5328 valid data points (30.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1999 data points (11.41%) set to NA
H: 2020 data points (11.53%) set to NA
LE: 2030 data points (11.59%) set to NA
NEE: 2313 data points (13.2%) set to NA
-------------------------------------------------------------------
Data filtering:
12192 data points (69.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12192 data points (69.59%) excluded in total
5328 valid data points (30.41%) remaining.

New sEddyProc class for site 'US-BZo'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 115.72.

Regression of reference temperature R_ref for 20 periods.

Quality control:
TA: 1927 data points (11%) set to NA
H: 1936 data points (11.05%) set to NA
LE: 1941 data points (11.08%) set to NA
NEE: 2241 data points (12.79%) set to NA
-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
339 additional data points (1.93%) excluded by precipitation filter (874
 data points = 4.99 % in total)
11427 data points (65.22%) excluded in total
6093 valid data points (34.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1927 data points (11%) set to NA
H: 1936 data points (11.05%) set to NA
LE: 1941 data points (11.08%) set to NA
NEE: 2241 data points (12.79%) set to NA
-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11088 data points (63.29%) excluded in total
6432 valid data points (36.71%) remaining.

New sEddyProc class for site 'US-BZo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 24 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-BZo-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 998 data points (5.68%) set to NA
H: 1269 data points (7.22%) set to NA
LE: 1221 data points (6.95%) set to NA
NEE: 1578 data points (8.98%) set to NA
-------------------------------------------------------------------
Data filtering:
10704 data points (60.93%) excluded by growing season filter
119 additional data points (0.68%) excluded by precipitation filter (960
 data points = 5.46 % in total)
10823 data points (61.61%) excluded in total
6745 valid data points (38.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 998 data points (5.68%) set to NA
H: 1269 data points (7.22%) set to NA
LE: 1221 data points (6.95%) set to NA
NEE: 1578 data points (8.98%) set to NA
-------------------------------------------------------------------
Data filtering:
10704 data points (60.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10704 data points (60.93%) excluded in total
6864 valid data points (39.07%) remaining.

New sEddyProc class for site 'US-BZo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 10 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-BZo-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 5845 data points (33.36%) set to NA
H: 6053 data points (34.55%) set to NA
LE: 6053 data points (34.55%) set to NA
NEE: 6312 data points (36.03%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 113”

-------------------------------------------------------------------
Data filtering:
7296 data points (41.64%) excluded by growing season filter
3058 additional data points (17.45%) excluded by precipitation filter (4333
 data points = 24.73 % in total)
10354 data points (59.1%) excluded in total
7166 valid data points (40.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5845 data points (33.36%) set to NA
H: 6053 data points (34.55%) set to NA
LE: 6053 data points (34.55%) set to NA
NEE: 6312 data points (36.03%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 113”

-------------------------------------------------------------------
Data filtering:
7296 data points (41.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7296 data points (41.64%) excluded in total
10224 valid data points (58.36%) remaining.

New sEddyProc class for site 'US-BZo'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 79.89.

Regression of reference temperature R_ref for 6 periods.

[197/329] Processing: US-Bar

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Bar | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023
Quality control:
TA: 9 data points (0.05%) set to NA
H: 438 data points (2.5%) set to NA
LE: 701 data points (4%) set to NA
NEE: 2236 data points (12.76%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (60%) excluded by growing season filter
2828 additional data points (16.14%) excluded by precipitation filter (6874
 data points = 39.24 % in total)
13340 data points (76.14%) excluded in total
4180 valid data points (23.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9 data points (0.05%) set to NA
H: 438 data points (2.5%) set to NA
LE: 701 data points (4%) set to NA
NEE: 2236 data points (12.76%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (60%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10512 data points (60%) excluded in total
7008 valid data points (40%) remaining.

New sEddyProc class for site 'US-Bar'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Bar-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 369 data points (2.11%) set to NA
LE: 8171 data points (46.64%) set to NA
NEE: 9107 data points (51.98%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 110”

-------------------------------------------------------------------
Data filtering:
5280 data points (30.14%) excluded by growing season filter
4955 additional data points (28.28%) excluded by precipitation filter (7013
 data points = 40.03 % in total)
10235 data points (58.42%) excluded in total
7285 valid data points (41.58%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 369 data points (2.11%) set to NA
LE: 8171 data points (46.64%) set to NA
NEE: 9107 data points (51.98%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 110”

-------------------------------------------------------------------
Data filtering:
5280 data points (30.14%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5280 data points (30.14%) excluded in total
12240 valid data points (69.86%) remaining.

New sEddyProc class for site 'US-Bar'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Bar-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 490 data points (2.8%) set to NA
LE: 1046 data points (5.97%) set to NA
NEE: 2472 data points (14.11%) set to NA
-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
2220 additional data points (12.67%) excluded by precipitation filter (6955
 data points = 39.7 % in total)
13308 data points (75.96%) excluded in total
4212 valid data points (24.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 490 data points (2.8%) set to NA
LE: 1046 data points (5.97%) set to NA
NEE: 2472 data points (14.11%) set to NA
-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11088 data points (63.29%) excluded in total
6432 valid data points (36.71%) remaining.

New sEddyProc class for site 'US-Bar'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Bar-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 494 data points (2.81%) set to NA
LE: 503 data points (2.86%) set to NA
NEE: 1488 data points (8.47%) set to NA
-------------------------------------------------------------------
Data filtering:
10752 data points (61.2%) excluded by growing season filter
1875 additional data points (10.67%) excluded by precipitation filter (6350
 data points = 36.15 % in total)
12627 data points (71.88%) excluded in total
4941 valid data points (28.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 494 data points (2.81%) set to NA
LE: 503 data points (2.86%) set to NA
NEE: 1488 data points (8.47%) set to NA
-------------------------------------------------------------------
Data filtering:
10752 data points (61.2%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10752 data points (61.2%) excluded in total
6816 valid data points (38.8%) remaining.

New sEddyProc class for site 'US-Bar'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Bar-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 151 data points (0.86%) set to NA
LE: 4028 data points (22.99%) set to NA
NEE: 4818 data points (27.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 52”

-------------------------------------------------------------------
Data filtering:
10032 data points (57.26%) excluded by growing season filter
3126 additional data points (17.84%) excluded by precipitation filter (6576
 data points = 37.53 % in total)
13158 data points (75.1%) excluded in total
4362 valid data points (24.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 151 data points (0.86%) set to NA
LE: 4028 data points (22.99%) set to NA
NEE: 4818 data points (27.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 52”

-------------------------------------------------------------------
Data filtering:
10032 data points (57.26%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10032 data points (57.26%) excluded in total
7488 valid data points (42.74%) remaining.

New sEddyProc class for site 'US-Bar'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Bar-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 196 data points (1.12%) set to NA
LE: 9738 data points (55.58%) set to NA
NEE: 10027 data points (57.23%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 140”

-------------------------------------------------------------------
Data filtering:
2448 data points (13.97%) excluded by growing season filter
5823 additional data points (33.24%) excluded by precipitation filter (6908
 data points = 39.43 % in total)
8271 data points (47.21%) excluded in total
9249 valid data points (52.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 196 data points (1.12%) set to NA
LE: 9738 data points (55.58%) set to NA
NEE: 10027 data points (57.23%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 140”

-------------------------------------------------------------------
Data filtering:
2448 data points (13.97%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2448 data points (13.97%) excluded in total
15072 valid data points (86.03%) remaining.

New sEddyProc class for site 'US-Bar'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Bar-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 123 data points (0.7%) set to NA
LE: 4117 data points (23.5%) set to NA
NEE: 5012 data points (28.61%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 51”

-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
3340 additional data points (19.06%) excluded by precipitation filter (7200
 data points = 41.1 % in total)
13612 data points (77.69%) excluded in total
3908 valid data points (22.31%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 123 data points (0.7%) set to NA
LE: 4117 data points (23.5%) set to NA
NEE: 5012 data points (28.61%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 51”

-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10272 data points (58.63%) excluded in total
7248 valid data points (41.37%) remaining.

New sEddyProc class for site 'US-Bar'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Bar-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[198/329] Processing: US-CMW

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-CMW | Years: 2017, 2018, 2019, 2020, 2021
Quality control:
TA: 0 data points (0%) set to NA
H: 6 data points (0.03%) set to NA
LE: 15 data points (0.09%) set to NA
NEE: 1669 data points (9.53%) set to NA
-------------------------------------------------------------------
Data filtering:
8016 data points (45.75%) excluded by growing season filter
2018 additional data points (11.52%) excluded by precipitation filter (2615
 data points = 14.93 % in total)
10034 data points (57.27%) excluded in total
7486 valid data points (42.73%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 6 data points (0.03%) set to NA
LE: 15 data points (0.09%) set to NA
NEE: 1669 data points (9.53%) set to NA
-------------------------------------------------------------------
Data filtering:
8016 data points (45.75%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8016 data points (45.75%) excluded in total
9504 valid data points (54.25%) remaining.

New sEddyProc class for site 'US-CMW'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-CMW-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 86 data points (0.49%) set to NA
H: 183 data points (1.04%) set to NA
LE: 200 data points (1.14%) set to NA
NEE: 1988 data points (11.35%) set to NA
-------------------------------------------------------------------
Data filtering:
8832 data points (50.41%) excluded by growing season filter
2253 additional data points (12.86%) excluded by precipitation filter (3004
 data points = 17.15 % in total)
11085 data points (63.27%) excluded in total
6435 valid data points (36.73%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 86 data points (0.49%) set to NA
H: 183 data points (1.04%) set to NA
LE: 200 data points (1.14%) set to NA
NEE: 1988 data points (11.35%) set to NA
-------------------------------------------------------------------
Data filtering:
8832 data points (50.41%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8832 data points (50.41%) excluded in total
8688 valid data points (49.59%) remaining.

New sEddyProc class for site 'US-CMW'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-CMW-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 10 data points (0.06%) set to NA
LE: 25 data points (0.14%) set to NA
NEE: 1412 data points (8.06%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.59%) excluded by growing season filter
1406 additional data points (8.03%) excluded by precipitation filter (2787
 data points = 15.91 % in total)
10094 data points (57.61%) excluded in total
7426 valid data points (42.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 10 data points (0.06%) set to NA
LE: 25 data points (0.14%) set to NA
NEE: 1412 data points (8.06%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8688 data points (49.59%) excluded in total
8832 valid data points (50.41%) remaining.

New sEddyProc class for site 'US-CMW'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-CMW-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 7 data points (0.04%) set to NA
LE: 36 data points (0.2%) set to NA
NEE: 1459 data points (8.3%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.64%) excluded by growing season filter
1396 additional data points (7.95%) excluded by precipitation filter (2355
 data points = 13.41 % in total)
10468 data points (59.59%) excluded in total
7100 valid data points (40.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 7 data points (0.04%) set to NA
LE: 36 data points (0.2%) set to NA
NEE: 1459 data points (8.3%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9072 data points (51.64%) excluded in total
8496 valid data points (48.36%) remaining.

New sEddyProc class for site 'US-CMW'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-CMW-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 10 data points (0.06%) set to NA
NEE: 1394 data points (7.96%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.16%) excluded by growing season filter
2203 additional data points (12.57%) excluded by precipitation filter (2669
 data points = 15.23 % in total)
12043 data points (68.74%) excluded in total
5477 valid data points (31.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 10 data points (0.06%) set to NA
NEE: 1394 data points (7.96%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9840 data points (56.16%) excluded in total
7680 valid data points (43.84%) remaining.

New sEddyProc class for site 'US-CMW'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-CMW-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[199/329] Processing: US-CRK

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-CRK | Years: 2022, 2023, 2024, 2025
Quality control:
TA: 1231 data points (7.03%) set to NA
H: 1249 data points (7.13%) set to NA
LE: 1263 data points (7.21%) set to NA
NEE: 2447 data points (13.97%) set to NA
-------------------------------------------------------------------
Data filtering:
4608 data points (26.3%) excluded by growing season filter
2458 additional data points (14.03%) excluded by precipitation filter (3215
 data points = 18.35 % in total)
7066 data points (40.33%) excluded in total
10454 valid data points (59.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1231 data points (7.03%) set to NA
H: 1249 data points (7.13%) set to NA
LE: 1263 data points (7.21%) set to NA
NEE: 2447 data points (13.97%) set to NA
-------------------------------------------------------------------
Data filtering:
4608 data points (26.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4608 data points (26.3%) excluded in total
12912 valid data points (73.7%) remaining.

New sEddyProc class for site 'US-CRK'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 64.4.

Regression of reference temperature R_ref for 9 periods.

Quality control:
TA: 2846 data points (16.24%) set to NA
H: 4973 data points (28.38%) set to NA
LE: 4708 data points (26.87%) set to NA
NEE: 5270 data points (30.08%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 52”

-------------------------------------------------------------------
Data filtering:
7200 data points (41.1%) excluded by growing season filter
2294 additional data points (13.09%) excluded by precipitation filter (4096
 data points = 23.38 % in total)
9494 data points (54.19%) excluded in total
8026 valid data points (45.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2846 data points (16.24%) set to NA
H: 4973 data points (28.38%) set to NA
LE: 4708 data points (26.87%) set to NA
NEE: 5270 data points (30.08%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 52”

-------------------------------------------------------------------
Data filtering:
7200 data points (41.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7200 data points (41.1%) excluded in total
10320 valid data points (58.9%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -63 ...”
New sEddyProc class for site 'US-CRK'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -63 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 12 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-CRK-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1436 data points (8.17%) set to NA
H: 3616 data points (20.58%) set to NA
LE: 2109 data points (12%) set to NA
NEE: 2590 data points (14.74%) set to NA
-------------------------------------------------------------------
Data filtering:
2304 data points (13.11%) excluded by growing season filter
4470 additional data points (25.44%) excluded by precipitation filter (5257
 data points = 29.92 % in total)
6774 data points (38.56%) excluded in total
10794 valid data points (61.44%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1436 data points (8.17%) set to NA
H: 3616 data points (20.58%) set to NA
LE: 2109 data points (12%) set to NA
NEE: 2590 data points (14.74%) set to NA
-------------------------------------------------------------------
Data filtering:
2304 data points (13.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2304 data points (13.11%) excluded in total
15264 valid data points (86.89%) remaining.

New sEddyProc class for site 'US-CRK'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 121.91.

Regression of reference temperature R_ref for 16 periods.

Quality control:
TA: 9062 data points (51.72%) set to NA
H: 9085 data points (51.86%) set to NA
LE: 9105 data points (51.97%) set to NA
NEE: 9378 data points (53.53%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 174”

-------------------------------------------------------------------
Data filtering:
2736 data points (15.62%) excluded by growing season filter
4162 additional data points (23.76%) excluded by precipitation filter (5006
 data points = 28.57 % in total)
6898 data points (39.37%) excluded in total
10622 valid data points (60.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9062 data points (51.72%) set to NA
H: 9085 data points (51.86%) set to NA
LE: 9105 data points (51.97%) set to NA
NEE: 9378 data points (53.53%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 174”

-------------------------------------------------------------------
Data filtering:
2736 data points (15.62%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2736 data points (15.62%) excluded in total
14784 valid data points (84.38%) remaining.

New sEddyProc class for site 'US-CRK'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-CRK-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[200/329] Processing: US-CS2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-CS2 | Years: 2018, 2019, 2020, 2021, 2022
Quality control:
TA: 15790 data points (90.13%) set to NA
H: 15896 data points (90.73%) set to NA
LE: 16380 data points (93.49%) set to NA
NEE: 15980 data points (91.21%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9188 additional data points (52.44%) excluded by precipitation filter (9188
 data points = 52.44 % in total)
9188 data points (52.44%) excluded in total
8332 valid data points (47.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 15790 data points (90.13%) set to NA
H: 15896 data points (90.73%) set to NA
LE: 16380 data points (93.49%) set to NA
NEE: 15980 data points (91.21%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-CS2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 21 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-CS2-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4541 data points (25.92%) set to NA
H: 4611 data points (26.32%) set to NA
LE: 4739 data points (27.05%) set to NA
NEE: 5252 data points (29.98%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 40”

-------------------------------------------------------------------
Data filtering:
8304 data points (47.4%) excluded by growing season filter
5852 additional data points (33.4%) excluded by precipitation filter (9952
 data points = 56.8 % in total)
14156 data points (80.8%) excluded in total
3364 valid data points (19.2%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4541 data points (25.92%) set to NA
H: 4611 data points (26.32%) set to NA
LE: 4739 data points (27.05%) set to NA
NEE: 5252 data points (29.98%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 40”

-------------------------------------------------------------------
Data filtering:
8304 data points (47.4%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8304 data points (47.4%) excluded in total
9216 valid data points (52.6%) remaining.

New sEddyProc class for site 'US-CS2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 36 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-CS2-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3084 data points (17.55%) set to NA
H: 3352 data points (19.08%) set to NA
LE: 3334 data points (18.98%) set to NA
NEE: 3966 data points (22.58%) set to NA
-------------------------------------------------------------------
Data filtering:
8112 data points (46.17%) excluded by growing season filter
5216 additional data points (29.69%) excluded by precipitation filter (8600
 data points = 48.95 % in total)
13328 data points (75.87%) excluded in total
4240 valid data points (24.13%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3084 data points (17.55%) set to NA
H: 3352 data points (19.08%) set to NA
LE: 3334 data points (18.98%) set to NA
NEE: 3966 data points (22.58%) set to NA
-------------------------------------------------------------------
Data filtering:
8112 data points (46.17%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8112 data points (46.17%) excluded in total
9456 valid data points (53.83%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -52, -55 ...”
New sEddyProc class for site 'US-CS2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -52, -55 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 124.17.

Regression of reference temperature R_ref for 28 periods.

Quality control:
TA: 7858 data points (44.85%) set to NA
H: 8318 data points (47.48%) set to NA
LE: 8232 data points (46.99%) set to NA
NEE: 8966 data points (51.18%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 89”

-------------------------------------------------------------------
Data filtering:
3888 data points (22.19%) excluded by growing season filter
7636 additional data points (43.58%) excluded by precipitation filter (9002
 data points = 51.38 % in total)
11524 data points (65.78%) excluded in total
5996 valid data points (34.22%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7858 data points (44.85%) set to NA
H: 8318 data points (47.48%) set to NA
LE: 8232 data points (46.99%) set to NA
NEE: 8966 data points (51.18%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 89”

-------------------------------------------------------------------
Data filtering:
3888 data points (22.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3888 data points (22.19%) excluded in total
13632 valid data points (77.81%) remaining.

New sEddyProc class for site 'US-CS2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 92.04.

Regression of reference temperature R_ref for 39 periods.

Quality control:
TA: 16331 data points (93.21%) set to NA
H: 16331 data points (93.21%) set to NA
LE: 16331 data points (93.21%) set to NA
NEE: 16567 data points (94.56%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8750 additional data points (49.94%) excluded by precipitation filter (8750
 data points = 49.94 % in total)
8750 data points (49.94%) excluded in total
8770 valid data points (50.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 16331 data points (93.21%) set to NA
H: 16331 data points (93.21%) set to NA
LE: 16331 data points (93.21%) set to NA
NEE: 16567 data points (94.56%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-CS2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 120.39.

Regression of reference temperature R_ref for 14 periods.

[201/329] Processing: US-CdM

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-CdM | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 7914 data points (45.17%) set to NA
H: 7935 data points (45.29%) set to NA
LE: 7936 data points (45.3%) set to NA
NEE: 8517 data points (48.61%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 155”

-------------------------------------------------------------------
Data filtering:
3696 data points (21.1%) excluded by growing season filter
3411 additional data points (19.47%) excluded by precipitation filter (4440
 data points = 25.34 % in total)
7107 data points (40.57%) excluded in total
10413 valid data points (59.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7914 data points (45.17%) set to NA
H: 7935 data points (45.29%) set to NA
LE: 7936 data points (45.3%) set to NA
NEE: 8517 data points (48.61%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 155”

-------------------------------------------------------------------
Data filtering:
3696 data points (21.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3696 data points (21.1%) excluded in total
13824 valid data points (78.9%) remaining.

New sEddyProc class for site 'US-CdM'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 65.42.

Regression of reference temperature R_ref for 5 periods.

Quality control:
TA: 884 data points (5.03%) set to NA
H: 929 data points (5.29%) set to NA
LE: 937 data points (5.33%) set to NA
NEE: 1761 data points (10.02%) set to NA
-------------------------------------------------------------------
Data filtering:
7392 data points (42.08%) excluded by growing season filter
1085 additional data points (6.18%) excluded by precipitation filter (2033
 data points = 11.57 % in total)
8477 data points (48.25%) excluded in total
9091 valid data points (51.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 884 data points (5.03%) set to NA
H: 929 data points (5.29%) set to NA
LE: 937 data points (5.33%) set to NA
NEE: 1761 data points (10.02%) set to NA
-------------------------------------------------------------------
Data filtering:
7392 data points (42.08%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7392 data points (42.08%) excluded in total
10176 valid data points (57.92%) remaining.

New sEddyProc class for site 'US-CdM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-CdM-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1133 data points (6.47%) set to NA
H: 1205 data points (6.88%) set to NA
LE: 1214 data points (6.93%) set to NA
NEE: 1983 data points (11.32%) set to NA
-------------------------------------------------------------------
Data filtering:
5808 data points (33.15%) excluded by growing season filter
1717 additional data points (9.8%) excluded by precipitation filter (3322
 data points = 18.96 % in total)
7525 data points (42.95%) excluded in total
9995 valid data points (57.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1133 data points (6.47%) set to NA
H: 1205 data points (6.88%) set to NA
LE: 1214 data points (6.93%) set to NA
NEE: 1983 data points (11.32%) set to NA
-------------------------------------------------------------------
Data filtering:
5808 data points (33.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5808 data points (33.15%) excluded in total
11712 valid data points (66.85%) remaining.

New sEddyProc class for site 'US-CdM'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 126.09.

Regression of reference temperature R_ref for 7 periods.

Quality control:
TA: 1967 data points (11.23%) set to NA
H: 2013 data points (11.49%) set to NA
LE: 2048 data points (11.69%) set to NA
NEE: 4196 data points (23.95%) set to NA
-------------------------------------------------------------------
Data filtering:
3312 data points (18.9%) excluded by growing season filter
2345 additional data points (13.38%) excluded by precipitation filter (3058
 data points = 17.45 % in total)
5657 data points (32.29%) excluded in total
11863 valid data points (67.71%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1967 data points (11.23%) set to NA
H: 2013 data points (11.49%) set to NA
LE: 2048 data points (11.69%) set to NA
NEE: 4196 data points (23.95%) set to NA
-------------------------------------------------------------------
Data filtering:
3312 data points (18.9%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3312 data points (18.9%) excluded in total
14208 valid data points (81.1%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -60 ...”
New sEddyProc class for site 'US-CdM'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -60 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 27 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-CdM-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 644 data points (3.68%) set to NA
H: 808 data points (4.61%) set to NA
LE: 818 data points (4.67%) set to NA
NEE: 2604 data points (14.86%) set to NA
-------------------------------------------------------------------
Data filtering:
7200 data points (41.1%) excluded by growing season filter
1208 additional data points (6.89%) excluded by precipitation filter (3437
 data points = 19.62 % in total)
8408 data points (47.99%) excluded in total
9112 valid data points (52.01%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 644 data points (3.68%) set to NA
H: 808 data points (4.61%) set to NA
LE: 818 data points (4.67%) set to NA
NEE: 2604 data points (14.86%) set to NA
-------------------------------------------------------------------
Data filtering:
7200 data points (41.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7200 data points (41.1%) excluded in total
10320 valid data points (58.9%) remaining.

New sEddyProc class for site 'US-CdM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-CdM-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1802 data points (10.26%) set to NA
H: 1804 data points (10.27%) set to NA
LE: 1812 data points (10.31%) set to NA
NEE: 1913 data points (10.89%) set to NA
-------------------------------------------------------------------
Data filtering:
9696 data points (55.19%) excluded by growing season filter
1002 additional data points (5.7%) excluded by precipitation filter (2031
 data points = 11.56 % in total)
10698 data points (60.89%) excluded in total
6870 valid data points (39.11%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1802 data points (10.26%) set to NA
H: 1804 data points (10.27%) set to NA
LE: 1812 data points (10.31%) set to NA
NEE: 1913 data points (10.89%) set to NA
-------------------------------------------------------------------
Data filtering:
9696 data points (55.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9696 data points (55.19%) excluded in total
7872 valid data points (44.81%) remaining.

New sEddyProc class for site 'US-CdM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 15 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-CdM-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[202/329] Processing: US-ChR

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-ChR | Years: 2017, 2018, 2019
Quality control:
TA: 0 data points (0%) set to NA
H: 3147 data points (17.96%) set to NA
LE: 8632 data points (49.27%) set to NA
NEE: 8674 data points (49.51%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7893 additional data points (45.05%) excluded by precipitation filter (7893
 data points = 45.05 % in total)
7893 data points (45.05%) excluded in total
9627 valid data points (54.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 3147 data points (17.96%) set to NA
LE: 8632 data points (49.27%) set to NA
NEE: 8674 data points (49.51%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 36 cases! Invalid values with 'NEE < -50': -73, -59, -77, -76, -61, -55, -70, -73, -70, -59, -64, -75, -50, -64, -63, -60, -64, -69, -79, -54, -50, -73, -59, -53, -69, -75, -54, -67, -60, -65, -60, -54, -53, -62, -65, -51 ...”
New sEddyProc class for site 'US-ChR'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 36 cases! Invalid values with 'NEE < -50': -73, -59, -77, -76, -61, -55, -70, -73, -70, -59, -64, -75, -50, -64, -63, -60, -64, -69, -79, -54, -50, -73, -59, -53, -69, -75, -54, -67, -60, -65, -60, -54, -53, -62, -65, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ChR-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2053 data points (11.72%) set to NA
LE: 9054 data points (51.68%) set to NA
NEE: 9070 data points (51.77%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 173”

-------------------------------------------------------------------
Data filtering:
3936 data points (22.47%) excluded by growing season filter
5649 additional data points (32.24%) excluded by precipitation filter (7559
 data points = 43.14 % in total)
9585 data points (54.71%) excluded in total
7935 valid data points (45.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2053 data points (11.72%) set to NA
LE: 9054 data points (51.68%) set to NA
NEE: 9070 data points (51.77%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 173”

-------------------------------------------------------------------
Data filtering:
3936 data points (22.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3936 data points (22.47%) excluded in total
13584 valid data points (77.53%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 34 cases! Invalid values with 'NEE < -50': -60, -59, -67, -62, -55, -59, -66, -56, -66, -74, -77, -52, -57, -50, -69, -58, -60, -63, -74, -70, -56, -77, -63, -68, -53, -55, -53, -57, -55, -54, -50, -58, -60, -71 ...”
New sEddyProc class for site 'US-ChR'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 34 cases! Invalid values with 'NEE < -50': -60, -59, -67, -62, -55, -59, -66, -56, -66, -74, -77, -52, -57, -50, -69, -58, -60, -63, -74, -70, -56, -77, -63, -68, -53, -55, -53, -57, -55, -54, -50, -58, -60, -71 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ChR-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 70 data points (0.4%) set to NA
LE: 54 data points (0.31%) set to NA
NEE: 166 data points (0.95%) set to NA
-------------------------------------------------------------------
Data filtering:
8112 data points (46.3%) excluded by growing season filter
3460 additional data points (19.75%) excluded by precipitation filter (7129
 data points = 40.69 % in total)
11572 data points (66.05%) excluded in total
5948 valid data points (33.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 70 data points (0.4%) set to NA
LE: 54 data points (0.31%) set to NA
NEE: 166 data points (0.95%) set to NA
-------------------------------------------------------------------
Data filtering:
8112 data points (46.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8112 data points (46.3%) excluded in total
9408 valid data points (53.7%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 47 cases! Invalid values with 'NEE < -50': -56, -73, -55, -69, -57, -56, -69, -77, -75, -52, -61, -64, -52, -51, -55, -50, -62, -54, -57, -60, -71, -76, -57, -70, -69, -57, -51, -75, -63, -52, -77, -58, -55, -50, -52, -53, -79, -58, -51, -54, -52, -53, -67, -56, -53, -54, -54 ...”
New sEddyProc class for site 'US-ChR'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 47 cases! Invalid values with 'NEE < -50': -56, -73, -55, -69, -57, -56, -69, -77, -75, -52, -61, -64, -52, -51, -55, -50, -62, -54, -57, -60, -71, -76, -57, -70, -69, -57, -51, -75, -63, -52, -77, -58, -55, -50, -52, -53, -79, -58, -51, -54, -52, -53, -67, -56, -53, -54, -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ChR-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[203/329] Processing: US-Cst

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Cst | Years: 2017
Quality control:
TA: 882 data points (5.03%) set to NA
H: 950 data points (5.42%) set to NA
LE: 963 data points (5.5%) set to NA
NEE: 1148 data points (6.55%) set to NA
-------------------------------------------------------------------
Data filtering:
3552 data points (20.27%) excluded by growing season filter
5268 additional data points (30.07%) excluded by precipitation filter (6304
 data points = 35.98 % in total)
8820 data points (50.34%) excluded in total
8700 valid data points (49.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 882 data points (5.03%) set to NA
H: 950 data points (5.42%) set to NA
LE: 963 data points (5.5%) set to NA
NEE: 1148 data points (6.55%) set to NA
-------------------------------------------------------------------
Data filtering:
3552 data points (20.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3552 data points (20.27%) excluded in total
13968 valid data points (79.73%) remaining.

New sEddyProc class for site 'US-Cst'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 84.75.

Regression of reference temperature R_ref for 7 periods.

[204/329] Processing: US-Dmg

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Dmg | Years: 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 11826 data points (67.5%) set to NA
H: 11828 data points (67.51%) set to NA
LE: 11835 data points (67.55%) set to NA
NEE: 12056 data points (68.81%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2074 additional data points (11.84%) excluded by precipitation filter (2074
 data points = 11.84 % in total)
2074 data points (11.84%) excluded in total
15446 valid data points (88.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11826 data points (67.5%) set to NA
H: 11828 data points (67.51%) set to NA
LE: 11835 data points (67.55%) set to NA
NEE: 12056 data points (68.81%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Dmg'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 134.31.

Regression of reference temperature R_ref for 8 periods.

Quality control:
TA: 571 data points (3.26%) set to NA
H: 1 data points (0.01%) set to NA
LE: 21 data points (0.12%) set to NA
NEE: 586 data points (3.34%) set to NA
-------------------------------------------------------------------
Data filtering:
8256 data points (47.12%) excluded by growing season filter
369 additional data points (2.11%) excluded by precipitation filter (1558
 data points = 8.89 % in total)
8625 data points (49.23%) excluded in total
8895 valid data points (50.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 571 data points (3.26%) set to NA
H: 1 data points (0.01%) set to NA
LE: 21 data points (0.12%) set to NA
NEE: 586 data points (3.34%) set to NA
-------------------------------------------------------------------
Data filtering:
8256 data points (47.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8256 data points (47.12%) excluded in total
9264 valid data points (52.88%) remaining.

New sEddyProc class for site 'US-Dmg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Dmg-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 102 data points (0.58%) set to NA
H: 166 data points (0.95%) set to NA
LE: 197 data points (1.12%) set to NA
NEE: 903 data points (5.15%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.67%) excluded by growing season filter
269 additional data points (1.54%) excluded by precipitation filter (3054
 data points = 17.43 % in total)
8621 data points (49.21%) excluded in total
8899 valid data points (50.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 102 data points (0.58%) set to NA
H: 166 data points (0.95%) set to NA
LE: 197 data points (1.12%) set to NA
NEE: 903 data points (5.15%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8352 data points (47.67%) excluded in total
9168 valid data points (52.33%) remaining.

New sEddyProc class for site 'US-Dmg'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 1 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Dmg-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 628 data points (3.57%) set to NA
H: 28 data points (0.16%) set to NA
LE: 223 data points (1.27%) set to NA
NEE: 857 data points (4.88%) set to NA
-------------------------------------------------------------------
Data filtering:
7872 data points (44.81%) excluded by growing season filter
178 additional data points (1.01%) excluded by precipitation filter (2893
 data points = 16.47 % in total)
8050 data points (45.82%) excluded in total
9518 valid data points (54.18%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 628 data points (3.57%) set to NA
H: 28 data points (0.16%) set to NA
LE: 223 data points (1.27%) set to NA
NEE: 857 data points (4.88%) set to NA
-------------------------------------------------------------------
Data filtering:
7872 data points (44.81%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7872 data points (44.81%) excluded in total
9696 valid data points (55.19%) remaining.

New sEddyProc class for site 'US-Dmg'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 174.69.

Regression of reference temperature R_ref for 4 periods.

Quality control:
TA: 1456 data points (8.31%) set to NA
H: 1591 data points (9.08%) set to NA
LE: 1612 data points (9.2%) set to NA
NEE: 2122 data points (12.11%) set to NA
-------------------------------------------------------------------
Data filtering:
8064 data points (46.03%) excluded by growing season filter
451 additional data points (2.57%) excluded by precipitation filter (2175
 data points = 12.41 % in total)
8515 data points (48.6%) excluded in total
9005 valid data points (51.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1456 data points (8.31%) set to NA
H: 1591 data points (9.08%) set to NA
LE: 1612 data points (9.2%) set to NA
NEE: 2122 data points (12.11%) set to NA
-------------------------------------------------------------------
Data filtering:
8064 data points (46.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8064 data points (46.03%) excluded in total
9456 valid data points (53.97%) remaining.

New sEddyProc class for site 'US-Dmg'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 142.87.

Regression of reference temperature R_ref for 13 periods.

[205/329] Processing: US-EA4

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-EA4 | Years: 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 3026 data points (17.27%) set to NA
H: 6887 data points (39.31%) set to NA
LE: 7276 data points (41.53%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5030 additional data points (28.71%) excluded by precipitation filter (5030
 data points = 28.71 % in total)
5030 data points (28.71%) excluded in total
12490 valid data points (71.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3026 data points (17.27%) set to NA
H: 6887 data points (39.31%) set to NA
LE: 7276 data points (41.53%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-EA4'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EA4-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2454 data points (14.01%) set to NA
H: 6564 data points (37.47%) set to NA
LE: 6972 data points (39.79%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3810 additional data points (21.75%) excluded by precipitation filter (3810
 data points = 21.75 % in total)
3810 data points (21.75%) excluded in total
13710 valid data points (78.25%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2454 data points (14.01%) set to NA
H: 6564 data points (37.47%) set to NA
LE: 6972 data points (39.79%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-EA4'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EA4-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4 data points (0.02%) set to NA
H: 769 data points (4.39%) set to NA
LE: 821 data points (4.69%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4067 additional data points (23.21%) excluded by precipitation filter (4067
 data points = 23.21 % in total)
4067 data points (23.21%) excluded in total
13453 valid data points (76.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4 data points (0.02%) set to NA
H: 769 data points (4.39%) set to NA
LE: 821 data points (4.69%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-EA4'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EA4-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1898 data points (10.8%) set to NA
H: 2843 data points (16.18%) set to NA
LE: 2908 data points (16.55%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3930 additional data points (22.37%) excluded by precipitation filter (3930
 data points = 22.37 % in total)
3930 data points (22.37%) excluded in total
13638 valid data points (77.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1898 data points (10.8%) set to NA
H: 2843 data points (16.18%) set to NA
LE: 2908 data points (16.55%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-EA4'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EA4-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 12529 data points (71.51%) set to NA
H: 12660 data points (72.26%) set to NA
LE: 12692 data points (72.44%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6106 additional data points (34.85%) excluded by precipitation filter (6106
 data points = 34.85 % in total)
6106 data points (34.85%) excluded in total
11414 valid data points (65.15%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12529 data points (71.51%) set to NA
H: 12660 data points (72.26%) set to NA
LE: 12692 data points (72.44%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-EA4'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EA4-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[206/329] Processing: US-EA5

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-EA5 | Years: 2021, 2022
Quality control:
TA: 5032 data points (28.72%) set to NA
H: 5967 data points (34.06%) set to NA
LE: 6065 data points (34.62%) set to NA
NEE: 6876 data points (39.25%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 94”

-------------------------------------------------------------------
Data filtering:
3072 data points (17.53%) excluded by growing season filter
3752 additional data points (21.42%) excluded by precipitation filter (4182
 data points = 23.87 % in total)
6824 data points (38.95%) excluded in total
10696 valid data points (61.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5032 data points (28.72%) set to NA
H: 5967 data points (34.06%) set to NA
LE: 6065 data points (34.62%) set to NA
NEE: 6876 data points (39.25%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 94”

-------------------------------------------------------------------
Data filtering:
3072 data points (17.53%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3072 data points (17.53%) excluded in total
14448 valid data points (82.47%) remaining.

New sEddyProc class for site 'US-EA5'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EA5-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 5 data points (0.03%) set to NA
H: 393 data points (2.24%) set to NA
LE: 463 data points (2.64%) set to NA
NEE: 987 data points (5.63%) set to NA
-------------------------------------------------------------------
Data filtering:
7920 data points (45.21%) excluded by growing season filter
1378 additional data points (7.87%) excluded by precipitation filter (2352
 data points = 13.42 % in total)
9298 data points (53.07%) excluded in total
8222 valid data points (46.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5 data points (0.03%) set to NA
H: 393 data points (2.24%) set to NA
LE: 463 data points (2.64%) set to NA
NEE: 987 data points (5.63%) set to NA
-------------------------------------------------------------------
Data filtering:
7920 data points (45.21%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7920 data points (45.21%) excluded in total
9600 valid data points (54.79%) remaining.

New sEddyProc class for site 'US-EA5'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EA5-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[207/329] Processing: US-EA6

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-EA6 | Years: 2023
Quality control:
TA: 9928 data points (56.67%) set to NA
H: 10110 data points (57.71%) set to NA
LE: 10109 data points (57.7%) set to NA
NEE: 10164 data points (58.01%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6431 additional data points (36.71%) excluded by precipitation filter (6431
 data points = 36.71 % in total)
6431 data points (36.71%) excluded in total
11089 valid data points (63.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9928 data points (56.67%) set to NA
H: 10110 data points (57.71%) set to NA
LE: 10109 data points (57.7%) set to NA
NEE: 10164 data points (58.01%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-EA6'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 344.02.

Regression of reference temperature R_ref for 6 periods.

[208/329] Processing: US-EDN

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-EDN | Years: 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 2233 data points (12.75%) set to NA
H: 7600 data points (43.38%) set to NA
LE: 7608 data points (43.42%) set to NA
NEE: 7816 data points (44.61%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 56”

-------------------------------------------------------------------
Data filtering:
4368 data points (24.93%) excluded by growing season filter
599 additional data points (3.42%) excluded by precipitation filter (1288
 data points = 7.35 % in total)
4967 data points (28.35%) excluded in total
12553 valid data points (71.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 2233 data points (12.75%) set to NA
H: 7600 data points (43.38%) set to NA
LE: 7608 data points (43.42%) set to NA
NEE: 7816 data points (44.61%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 56”

-------------------------------------------------------------------
Data filtering:
4368 data points (24.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4368 data points (24.93%) excluded in total
13152 valid data points (75.07%) remaining.

New sEddyProc class for site 'US-EDN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EDN-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 62 data points (0.35%) set to NA
H: 70 data points (0.4%) set to NA
LE: 1456 data points (8.31%) set to NA
NEE: 1634 data points (9.33%) set to NA
-------------------------------------------------------------------
Data filtering:
4992 data points (28.49%) excluded by growing season filter
1406 additional data points (8.03%) excluded by precipitation filter (2816
 data points = 16.07 % in total)
6398 data points (36.52%) excluded in total
11122 valid data points (63.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 62 data points (0.35%) set to NA
H: 70 data points (0.4%) set to NA
LE: 1456 data points (8.31%) set to NA
NEE: 1634 data points (9.33%) set to NA
-------------------------------------------------------------------
Data filtering:
4992 data points (28.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4992 data points (28.49%) excluded in total
12528 valid data points (71.51%) remaining.

New sEddyProc class for site 'US-EDN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EDN-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 368 data points (2.09%) set to NA
H: 2061 data points (11.73%) set to NA
LE: 2703 data points (15.39%) set to NA
NEE: 3414 data points (19.43%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 14”

-------------------------------------------------------------------
Data filtering:
5232 data points (29.78%) excluded by growing season filter
957 additional data points (5.45%) excluded by precipitation filter (1810
 data points = 10.3 % in total)
6189 data points (35.23%) excluded in total
11379 valid data points (64.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 368 data points (2.09%) set to NA
H: 2061 data points (11.73%) set to NA
LE: 2703 data points (15.39%) set to NA
NEE: 3414 data points (19.43%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 14”

-------------------------------------------------------------------
Data filtering:
5232 data points (29.78%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5232 data points (29.78%) excluded in total
12336 valid data points (70.22%) remaining.

New sEddyProc class for site 'US-EDN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EDN-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1056 data points (6.03%) set to NA
H: 1784 data points (10.18%) set to NA
LE: 1782 data points (10.17%) set to NA
NEE: 2020 data points (11.53%) set to NA
-------------------------------------------------------------------
Data filtering:
7248 data points (41.37%) excluded by growing season filter
269 additional data points (1.54%) excluded by precipitation filter (1619
 data points = 9.24 % in total)
7517 data points (42.91%) excluded in total
10003 valid data points (57.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 1056 data points (6.03%) set to NA
H: 1784 data points (10.18%) set to NA
LE: 1782 data points (10.17%) set to NA
NEE: 2020 data points (11.53%) set to NA
-------------------------------------------------------------------
Data filtering:
7248 data points (41.37%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7248 data points (41.37%) excluded in total
10272 valid data points (58.63%) remaining.

New sEddyProc class for site 'US-EDN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EDN-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3160 data points (18.04%) set to NA
H: 3715 data points (21.2%) set to NA
LE: 4048 data points (23.11%) set to NA
NEE: 4757 data points (27.15%) set to NA
-------------------------------------------------------------------
Data filtering:
6288 data points (35.89%) excluded by growing season filter
887 additional data points (5.06%) excluded by precipitation filter (2120
 data points = 12.1 % in total)
7175 data points (40.95%) excluded in total
10345 valid data points (59.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 3160 data points (18.04%) set to NA
H: 3715 data points (21.2%) set to NA
LE: 4048 data points (23.11%) set to NA
NEE: 4757 data points (27.15%) set to NA
-------------------------------------------------------------------
Data filtering:
6288 data points (35.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6288 data points (35.89%) excluded in total
11232 valid data points (64.11%) remaining.

New sEddyProc class for site 'US-EDN'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 137.38.

Regression of reference temperature R_ref for 22 periods.

Quality control:
TA: 1747 data points (9.97%) set to NA
H: 2492 data points (14.22%) set to NA
LE: 2988 data points (17.05%) set to NA
NEE: 3358 data points (19.17%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 20”

-------------------------------------------------------------------
Data filtering:
8352 data points (47.67%) excluded by growing season filter
730 additional data points (4.17%) excluded by precipitation filter (3357
 data points = 19.16 % in total)
9082 data points (51.84%) excluded in total
8438 valid data points (48.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 1747 data points (9.97%) set to NA
H: 2492 data points (14.22%) set to NA
LE: 2988 data points (17.05%) set to NA
NEE: 3358 data points (19.17%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 20”

-------------------------------------------------------------------
Data filtering:
8352 data points (47.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8352 data points (47.67%) excluded in total
9168 valid data points (52.33%) remaining.

New sEddyProc class for site 'US-EDN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EDN-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 911 data points (5.19%) set to NA
H: 1519 data points (8.65%) set to NA
LE: 1515 data points (8.62%) set to NA
NEE: 2113 data points (12.03%) set to NA
-------------------------------------------------------------------
Data filtering:
6336 data points (36.07%) excluded by growing season filter
1098 additional data points (6.25%) excluded by precipitation filter (3216
 data points = 18.31 % in total)
7434 data points (42.32%) excluded in total
10134 valid data points (57.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 911 data points (5.19%) set to NA
H: 1519 data points (8.65%) set to NA
LE: 1515 data points (8.62%) set to NA
NEE: 2113 data points (12.03%) set to NA
-------------------------------------------------------------------
Data filtering:
6336 data points (36.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6336 data points (36.07%) excluded in total
11232 valid data points (63.93%) remaining.

New sEddyProc class for site 'US-EDN'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 244.04.

Regression of reference temperature R_ref for 8 periods.

[209/329] Processing: US-EKH

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-EKH | Years: 2022, 2023, 2024
Quality control:
TA: 9176 data points (52.37%) set to NA
H: 12682 data points (72.39%) set to NA
LE: 12701 data points (72.49%) set to NA
NEE: 12826 data points (73.21%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
430 additional data points (2.45%) excluded by precipitation filter (430
 data points = 2.45 % in total)
430 data points (2.45%) excluded in total
17090 valid data points (97.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9176 data points (52.37%) set to NA
H: 12682 data points (72.39%) set to NA
LE: 12701 data points (72.49%) set to NA
NEE: 12826 data points (73.21%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-EKH'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EKH-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2132 data points (12.17%) set to NA
H: 3135 data points (17.89%) set to NA
LE: 3148 data points (17.97%) set to NA
NEE: 3219 data points (18.37%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
574 additional data points (3.28%) excluded by precipitation filter (574
 data points = 3.28 % in total)
574 data points (3.28%) excluded in total
16946 valid data points (96.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2132 data points (12.17%) set to NA
H: 3135 data points (17.89%) set to NA
LE: 3148 data points (17.97%) set to NA
NEE: 3219 data points (18.37%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-EKH'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 131.94.

Regression of reference temperature R_ref for 14 periods.

Quality control:
TA: 1434 data points (8.16%) set to NA
H: 20 data points (0.11%) set to NA
LE: 43 data points (0.24%) set to NA
NEE: 463 data points (2.64%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
996 additional data points (5.67%) excluded by precipitation filter (996
 data points = 5.67 % in total)
996 data points (5.67%) excluded in total
16572 valid data points (94.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1434 data points (8.16%) set to NA
H: 20 data points (0.11%) set to NA
LE: 43 data points (0.24%) set to NA
NEE: 463 data points (2.64%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-EKH'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EKH-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[210/329] Processing: US-EKN

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-EKN | Years: 2023, 2024
Quality control:
TA: 8845 data points (50.49%) set to NA
H: 9088 data points (51.87%) set to NA
LE: 9060 data points (51.71%) set to NA
NEE: 9200 data points (52.51%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
305 additional data points (1.74%) excluded by precipitation filter (305
 data points = 1.74 % in total)
305 data points (1.74%) excluded in total
17215 valid data points (98.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8845 data points (50.49%) set to NA
H: 9088 data points (51.87%) set to NA
LE: 9060 data points (51.71%) set to NA
NEE: 9200 data points (52.51%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-EKN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EKN-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1677 data points (9.55%) set to NA
LE: 1644 data points (9.36%) set to NA
NEE: 2065 data points (11.75%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
731 additional data points (4.16%) excluded by precipitation filter (731
 data points = 4.16 % in total)
731 data points (4.16%) excluded in total
16837 valid data points (95.84%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1677 data points (9.55%) set to NA
LE: 1644 data points (9.36%) set to NA
NEE: 2065 data points (11.75%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-EKN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EKN-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[211/329] Processing: US-EKP

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-EKP | Years: 2022, 2023, 2024
Quality control:
TA: 9390 data points (53.6%) set to NA
H: 10804 data points (61.67%) set to NA
LE: 10836 data points (61.85%) set to NA
NEE: 10950 data points (62.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 159”

-------------------------------------------------------------------
Data filtering:
2016 data points (11.51%) excluded by growing season filter
190 additional data points (1.08%) excluded by precipitation filter (190
 data points = 1.08 % in total)
2206 data points (12.59%) excluded in total
15314 valid data points (87.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9390 data points (53.6%) set to NA
H: 10804 data points (61.67%) set to NA
LE: 10836 data points (61.85%) set to NA
NEE: 10950 data points (62.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 159”

-------------------------------------------------------------------
Data filtering:
2016 data points (11.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2016 data points (11.51%) excluded in total
15504 valid data points (88.49%) remaining.

New sEddyProc class for site 'US-EKP'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 144.84.

Regression of reference temperature R_ref for 16 periods.

Quality control:
TA: 3227 data points (18.42%) set to NA
H: 5999 data points (34.24%) set to NA
LE: 6016 data points (34.34%) set to NA
NEE: 6113 data points (34.89%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 85”

-------------------------------------------------------------------
Data filtering:
2640 data points (15.07%) excluded by growing season filter
49 additional data points (0.28%) excluded by precipitation filter (103
 data points = 0.59 % in total)
2689 data points (15.35%) excluded in total
14831 valid data points (84.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3227 data points (18.42%) set to NA
H: 5999 data points (34.24%) set to NA
LE: 6016 data points (34.34%) set to NA
NEE: 6113 data points (34.89%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 85”

-------------------------------------------------------------------
Data filtering:
2640 data points (15.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2640 data points (15.07%) excluded in total
14880 valid data points (84.93%) remaining.

New sEddyProc class for site 'US-EKP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EKP-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 49 data points (0.28%) set to NA
LE: 52 data points (0.3%) set to NA
NEE: 328 data points (1.87%) set to NA
-------------------------------------------------------------------
Data filtering:
5712 data points (32.51%) excluded by growing season filter
149 additional data points (0.85%) excluded by precipitation filter (399
 data points = 2.27 % in total)
5861 data points (33.36%) excluded in total
11707 valid data points (66.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 49 data points (0.28%) set to NA
LE: 52 data points (0.3%) set to NA
NEE: 328 data points (1.87%) set to NA
-------------------------------------------------------------------
Data filtering:
5712 data points (32.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5712 data points (32.51%) excluded in total
11856 valid data points (67.49%) remaining.

New sEddyProc class for site 'US-EKP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EKP-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[212/329] Processing: US-EML

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-EML | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023
Quality control:
TA: 3366 data points (19.21%) set to NA
H: 3416 data points (19.5%) set to NA
LE: 3830 data points (21.86%) set to NA
NEE: 4329 data points (24.71%) set to NA
-------------------------------------------------------------------
Data filtering:
11424 data points (65.21%) excluded by growing season filter
4734 additional data points (27.02%) excluded by precipitation filter (10280
 data points = 58.68 % in total)
16158 data points (92.23%) excluded in total
1362 valid data points (7.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3366 data points (19.21%) set to NA
H: 3416 data points (19.5%) set to NA
LE: 3830 data points (21.86%) set to NA
NEE: 4329 data points (24.71%) set to NA
-------------------------------------------------------------------
Data filtering:
11424 data points (65.21%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11424 data points (65.21%) excluded in total
6096 valid data points (34.79%) remaining.

New sEddyProc class for site 'US-EML'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 206.12.

Regression of reference temperature R_ref for 49 periods.

Quality control:
TA: 4079 data points (23.28%) set to NA
H: 4130 data points (23.57%) set to NA
LE: 4548 data points (25.96%) set to NA
NEE: 4667 data points (26.64%) set to NA
-------------------------------------------------------------------
Data filtering:
12432 data points (70.96%) excluded by growing season filter
3596 additional data points (20.53%) excluded by precipitation filter (9520
 data points = 54.34 % in total)
16028 data points (91.48%) excluded in total
1492 valid data points (8.52%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4079 data points (23.28%) set to NA
H: 4130 data points (23.57%) set to NA
LE: 4548 data points (25.96%) set to NA
NEE: 4667 data points (26.64%) set to NA
-------------------------------------------------------------------
Data filtering:
12432 data points (70.96%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12432 data points (70.96%) excluded in total
5088 valid data points (29.04%) remaining.

New sEddyProc class for site 'US-EML'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 136.13.

Regression of reference temperature R_ref for 40 periods.

Quality control:
TA: 3299 data points (18.83%) set to NA
H: 3521 data points (20.1%) set to NA
LE: 5001 data points (28.54%) set to NA
NEE: 5259 data points (30.02%) set to NA
-------------------------------------------------------------------
Data filtering:
12144 data points (69.32%) excluded by growing season filter
4044 additional data points (23.08%) excluded by precipitation filter (10610
 data points = 60.56 % in total)
16188 data points (92.4%) excluded in total
1332 valid data points (7.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3299 data points (18.83%) set to NA
H: 3521 data points (20.1%) set to NA
LE: 5001 data points (28.54%) set to NA
NEE: 5259 data points (30.02%) set to NA
-------------------------------------------------------------------
Data filtering:
12144 data points (69.32%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12144 data points (69.32%) excluded in total
5376 valid data points (30.68%) remaining.

New sEddyProc class for site 'US-EML'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 98.54.

Regression of reference temperature R_ref for 38 periods.

Quality control:
TA: 2607 data points (14.84%) set to NA
H: 10317 data points (58.73%) set to NA
LE: 10561 data points (60.11%) set to NA
NEE: 10665 data points (60.71%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 148”

-------------------------------------------------------------------
Data filtering:
6528 data points (37.16%) excluded by growing season filter
7588 additional data points (43.19%) excluded by precipitation filter (11066
 data points = 62.99 % in total)
14116 data points (80.35%) excluded in total
3452 valid data points (19.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2607 data points (14.84%) set to NA
H: 10317 data points (58.73%) set to NA
LE: 10561 data points (60.11%) set to NA
NEE: 10665 data points (60.71%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 148”

-------------------------------------------------------------------
Data filtering:
6528 data points (37.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6528 data points (37.16%) excluded in total
11040 valid data points (62.84%) remaining.

New sEddyProc class for site 'US-EML'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 11 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EML-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2880 data points (16.44%) set to NA
H: 3002 data points (17.13%) set to NA
LE: 3024 data points (17.26%) set to NA
NEE: 3272 data points (18.68%) set to NA
-------------------------------------------------------------------
Data filtering:
13152 data points (75.07%) excluded by growing season filter
3358 additional data points (19.17%) excluded by precipitation filter (10430
 data points = 59.53 % in total)
16510 data points (94.24%) excluded in total
1010 valid data points (5.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2880 data points (16.44%) set to NA
H: 3002 data points (17.13%) set to NA
LE: 3024 data points (17.26%) set to NA
NEE: 3272 data points (18.68%) set to NA
-------------------------------------------------------------------
Data filtering:
13152 data points (75.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13152 data points (75.07%) excluded in total
4368 valid data points (24.93%) remaining.

New sEddyProc class for site 'US-EML'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 271.58.

Regression of reference temperature R_ref for 29 periods.

Quality control:
TA: 6095 data points (34.79%) set to NA
H: 4765 data points (27.2%) set to NA
LE: 4822 data points (27.52%) set to NA
NEE: 5256 data points (30%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 24”

-------------------------------------------------------------------
Data filtering:
12768 data points (72.88%) excluded by growing season filter
3504 additional data points (20%) excluded by precipitation filter (9996
 data points = 57.05 % in total)
16272 data points (92.88%) excluded in total
1248 valid data points (7.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6095 data points (34.79%) set to NA
H: 4765 data points (27.2%) set to NA
LE: 4822 data points (27.52%) set to NA
NEE: 5256 data points (30%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 24”

-------------------------------------------------------------------
Data filtering:
12768 data points (72.88%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12768 data points (72.88%) excluded in total
4752 valid data points (27.12%) remaining.

New sEddyProc class for site 'US-EML'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 204.98.

Regression of reference temperature R_ref for 44 periods.

Quality control:
TA: 13896 data points (79.32%) set to NA
H: 13918 data points (79.44%) set to NA
LE: 13924 data points (79.47%) set to NA
NEE: 14151 data points (80.77%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10500 additional data points (59.93%) excluded by precipitation filter (10500
 data points = 59.93 % in total)
10500 data points (59.93%) excluded in total
7020 valid data points (40.07%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 13896 data points (79.32%) set to NA
H: 13918 data points (79.44%) set to NA
LE: 13924 data points (79.47%) set to NA
NEE: 14151 data points (80.77%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-EML'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 43.64.

Regression of reference temperature R_ref for 22 periods.

[213/329] Processing: US-Elm

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Elm | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 2515 data points (14.36%) set to NA
H: 2680 data points (15.3%) set to NA
LE: 2678 data points (15.29%) set to NA
NEE: 2599 data points (14.83%) set to NA
-------------------------------------------------------------------
Data filtering:
1488 data points (8.49%) excluded by growing season filter
5161 additional data points (29.46%) excluded by precipitation filter (5749
 data points = 32.81 % in total)
6649 data points (37.95%) excluded in total
10871 valid data points (62.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2515 data points (14.36%) set to NA
H: 2680 data points (15.3%) set to NA
LE: 2678 data points (15.29%) set to NA
NEE: 2599 data points (14.83%) set to NA
-------------------------------------------------------------------
Data filtering:
1488 data points (8.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1488 data points (8.49%) excluded in total
16032 valid data points (91.51%) remaining.

New sEddyProc class for site 'US-Elm'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 93.03.

Regression of reference temperature R_ref for 14 periods.

Quality control:
TA: 918 data points (5.24%) set to NA
H: 1208 data points (6.89%) set to NA
LE: 1208 data points (6.89%) set to NA
NEE: 1200 data points (6.85%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5860 additional data points (33.45%) excluded by precipitation filter (5860
 data points = 33.45 % in total)
5860 data points (33.45%) excluded in total
11660 valid data points (66.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 918 data points (5.24%) set to NA
H: 1208 data points (6.89%) set to NA
LE: 1208 data points (6.89%) set to NA
NEE: 1200 data points (6.85%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Elm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 1 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Elm-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 142 data points (0.81%) set to NA
H: 244 data points (1.39%) set to NA
LE: 243 data points (1.39%) set to NA
NEE: 216 data points (1.23%) set to NA
-------------------------------------------------------------------
Data filtering:
2400 data points (13.7%) excluded by growing season filter
4340 additional data points (24.77%) excluded by precipitation filter (5370
 data points = 30.65 % in total)
6740 data points (38.47%) excluded in total
10780 valid data points (61.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 142 data points (0.81%) set to NA
H: 244 data points (1.39%) set to NA
LE: 243 data points (1.39%) set to NA
NEE: 216 data points (1.23%) set to NA
-------------------------------------------------------------------
Data filtering:
2400 data points (13.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2400 data points (13.7%) excluded in total
15120 valid data points (86.3%) remaining.

New sEddyProc class for site 'US-Elm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Elm-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 5140 data points (29.26%) set to NA
H: 5261 data points (29.95%) set to NA
LE: 5261 data points (29.95%) set to NA
NEE: 5203 data points (29.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 75”

-------------------------------------------------------------------
Data filtering:
6864 data points (39.07%) excluded by growing season filter
3414 additional data points (19.43%) excluded by precipitation filter (6282
 data points = 35.76 % in total)
10278 data points (58.5%) excluded in total
7290 valid data points (41.5%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5140 data points (29.26%) set to NA
H: 5261 data points (29.95%) set to NA
LE: 5261 data points (29.95%) set to NA
NEE: 5203 data points (29.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 75”

-------------------------------------------------------------------
Data filtering:
6864 data points (39.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6864 data points (39.07%) excluded in total
10704 valid data points (60.93%) remaining.

New sEddyProc class for site 'US-Elm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 13 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Elm-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4 data points (0.02%) set to NA
H: 106 data points (0.61%) set to NA
LE: 106 data points (0.61%) set to NA
NEE: 64 data points (0.37%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5420 additional data points (30.94%) excluded by precipitation filter (5420
 data points = 30.94 % in total)
5420 data points (30.94%) excluded in total
12100 valid data points (69.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4 data points (0.02%) set to NA
H: 106 data points (0.61%) set to NA
LE: 106 data points (0.61%) set to NA
NEE: 64 data points (0.37%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Elm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Elm-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1 data points (0.01%) set to NA
H: 59 data points (0.34%) set to NA
LE: 57 data points (0.33%) set to NA
NEE: 44 data points (0.25%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6186 additional data points (35.31%) excluded by precipitation filter (6186
 data points = 35.31 % in total)
6186 data points (35.31%) excluded in total
11334 valid data points (64.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1 data points (0.01%) set to NA
H: 59 data points (0.34%) set to NA
LE: 57 data points (0.33%) set to NA
NEE: 44 data points (0.25%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Elm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Elm-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2339 data points (13.35%) set to NA
H: 8985 data points (51.28%) set to NA
LE: 8984 data points (51.28%) set to NA
NEE: 8971 data points (51.2%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5713 additional data points (32.61%) excluded by precipitation filter (5713
 data points = 32.61 % in total)
5713 data points (32.61%) excluded in total
11807 valid data points (67.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2339 data points (13.35%) set to NA
H: 8985 data points (51.28%) set to NA
LE: 8984 data points (51.28%) set to NA
NEE: 8971 data points (51.2%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Elm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Elm-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3838 data points (21.85%) set to NA
H: 7278 data points (41.43%) set to NA
LE: 7276 data points (41.42%) set to NA
NEE: 7144 data points (40.66%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 70”

-------------------------------------------------------------------
Data filtering:
5040 data points (28.69%) excluded by growing season filter
1825 additional data points (10.39%) excluded by precipitation filter (2062
 data points = 11.74 % in total)
6865 data points (39.08%) excluded in total
10703 valid data points (60.92%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3838 data points (21.85%) set to NA
H: 7278 data points (41.43%) set to NA
LE: 7276 data points (41.42%) set to NA
NEE: 7144 data points (40.66%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 70”

-------------------------------------------------------------------
Data filtering:
5040 data points (28.69%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5040 data points (28.69%) excluded in total
12528 valid data points (71.31%) remaining.

New sEddyProc class for site 'US-Elm'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 82.44.

Regression of reference temperature R_ref for 8 periods.

[214/329] Processing: US-Esm

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Esm | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 2116 data points (12.08%) set to NA
H: 2523 data points (14.4%) set to NA
LE: 2525 data points (14.41%) set to NA
NEE: 2421 data points (13.82%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7439 additional data points (42.46%) excluded by precipitation filter (7439
 data points = 42.46 % in total)
7439 data points (42.46%) excluded in total
10081 valid data points (57.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2116 data points (12.08%) set to NA
H: 2523 data points (14.4%) set to NA
LE: 2525 data points (14.41%) set to NA
NEE: 2421 data points (13.82%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Esm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 11 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Esm-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 316 data points (1.8%) set to NA
LE: 316 data points (1.8%) set to NA
NEE: 240 data points (1.37%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6753 additional data points (38.54%) excluded by precipitation filter (6753
 data points = 38.54 % in total)
6753 data points (38.54%) excluded in total
10767 valid data points (61.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 316 data points (1.8%) set to NA
LE: 316 data points (1.8%) set to NA
NEE: 240 data points (1.37%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
New sEddyProc class for site 'US-Esm'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Esm-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 661 data points (3.77%) set to NA
H: 934 data points (5.33%) set to NA
LE: 934 data points (5.33%) set to NA
NEE: 883 data points (5.04%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6818 additional data points (38.92%) excluded by precipitation filter (6818
 data points = 38.92 % in total)
6818 data points (38.92%) excluded in total
10702 valid data points (61.08%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 661 data points (3.77%) set to NA
H: 934 data points (5.33%) set to NA
LE: 934 data points (5.33%) set to NA
NEE: 883 data points (5.04%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
New sEddyProc class for site 'US-Esm'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Esm-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2 data points (0.01%) set to NA
H: 210 data points (1.2%) set to NA
LE: 210 data points (1.2%) set to NA
NEE: 175 data points (1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8091 additional data points (46.06%) excluded by precipitation filter (8091
 data points = 46.06 % in total)
8091 data points (46.06%) excluded in total
9477 valid data points (53.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2 data points (0.01%) set to NA
H: 210 data points (1.2%) set to NA
LE: 210 data points (1.2%) set to NA
NEE: 175 data points (1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-Esm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Esm-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2 data points (0.01%) set to NA
H: 874 data points (4.99%) set to NA
LE: 875 data points (4.99%) set to NA
NEE: 866 data points (4.94%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6074 additional data points (34.67%) excluded by precipitation filter (6074
 data points = 34.67 % in total)
6074 data points (34.67%) excluded in total
11446 valid data points (65.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2 data points (0.01%) set to NA
H: 874 data points (4.99%) set to NA
LE: 875 data points (4.99%) set to NA
NEE: 866 data points (4.94%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Esm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Esm-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 555 data points (3.17%) set to NA
H: 724 data points (4.13%) set to NA
LE: 725 data points (4.14%) set to NA
NEE: 686 data points (3.92%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3208 additional data points (18.31%) excluded by precipitation filter (3208
 data points = 18.31 % in total)
3208 data points (18.31%) excluded in total
14312 valid data points (81.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 555 data points (3.17%) set to NA
H: 724 data points (4.13%) set to NA
LE: 725 data points (4.14%) set to NA
NEE: 686 data points (3.92%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Esm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Esm-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3271 data points (18.67%) set to NA
H: 4639 data points (26.48%) set to NA
LE: 4632 data points (26.44%) set to NA
NEE: 4193 data points (23.93%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2370 additional data points (13.53%) excluded by precipitation filter (2370
 data points = 13.53 % in total)
2370 data points (13.53%) excluded in total
15150 valid data points (86.47%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3271 data points (18.67%) set to NA
H: 4639 data points (26.48%) set to NA
LE: 4632 data points (26.44%) set to NA
NEE: 4193 data points (23.93%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Esm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 14 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Esm-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3308 data points (18.83%) set to NA
H: 3527 data points (20.08%) set to NA
LE: 3527 data points (20.08%) set to NA
NEE: 3826 data points (21.78%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3308 data points (18.83%) set to NA
H: 3527 data points (20.08%) set to NA
LE: 3527 data points (20.08%) set to NA
NEE: 3826 data points (21.78%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-Esm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 16 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Esm-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[215/329] Processing: US-EvM

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-EvM | Years: 2020, 2021, 2022, 2023
Quality control:
TA: 6275 data points (35.72%) set to NA
H: 5910 data points (33.64%) set to NA
LE: 5907 data points (33.62%) set to NA
NEE: 5930 data points (33.75%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8124 additional data points (46.24%) excluded by precipitation filter (8124
 data points = 46.24 % in total)
8124 data points (46.24%) excluded in total
9444 valid data points (53.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6275 data points (35.72%) set to NA
H: 5910 data points (33.64%) set to NA
LE: 5907 data points (33.62%) set to NA
NEE: 5930 data points (33.75%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-EvM'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 242.19.

Regression of reference temperature R_ref for 5 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 631 data points (3.6%) set to NA
LE: 632 data points (3.61%) set to NA
NEE: 685 data points (3.91%) set to NA
-------------------------------------------------------------------
Data filtering:
4560 data points (26.03%) excluded by growing season filter
4635 additional data points (26.46%) excluded by precipitation filter (6058
 data points = 34.58 % in total)
9195 data points (52.48%) excluded in total
8325 valid data points (47.52%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 631 data points (3.6%) set to NA
LE: 632 data points (3.61%) set to NA
NEE: 685 data points (3.91%) set to NA
-------------------------------------------------------------------
Data filtering:
4560 data points (26.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4560 data points (26.03%) excluded in total
12960 valid data points (73.97%) remaining.

New sEddyProc class for site 'US-EvM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EvM-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 392 data points (2.24%) set to NA
H: 620 data points (3.54%) set to NA
LE: 618 data points (3.53%) set to NA
NEE: 621 data points (3.54%) set to NA
-------------------------------------------------------------------
Data filtering:
3072 data points (17.53%) excluded by growing season filter
5194 additional data points (29.65%) excluded by precipitation filter (6370
 data points = 36.36 % in total)
8266 data points (47.18%) excluded in total
9254 valid data points (52.82%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 392 data points (2.24%) set to NA
H: 620 data points (3.54%) set to NA
LE: 618 data points (3.53%) set to NA
NEE: 621 data points (3.54%) set to NA
-------------------------------------------------------------------
Data filtering:
3072 data points (17.53%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3072 data points (17.53%) excluded in total
14448 valid data points (82.47%) remaining.

New sEddyProc class for site 'US-EvM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EvM-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1075 data points (6.14%) set to NA
H: 10347 data points (59.06%) set to NA
LE: 10350 data points (59.08%) set to NA
NEE: 10383 data points (59.26%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 186”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6274 additional data points (35.81%) excluded by precipitation filter (6274
 data points = 35.81 % in total)
6274 data points (35.81%) excluded in total
11246 valid data points (64.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1075 data points (6.14%) set to NA
H: 10347 data points (59.06%) set to NA
LE: 10350 data points (59.08%) set to NA
NEE: 10383 data points (59.26%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 186”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-EvM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-EvM-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[216/329] Processing: US-Fo1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Fo1 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 17520 data points (100%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1502 additional data points (8.57%) excluded by precipitation filter (1502
 data points = 8.57 % in total)
1502 data points (8.57%) excluded in total
16018 valid data points (91.43%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-Fo1-2017”

Quality control:
TA: 17520 data points (100%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1613 additional data points (9.21%) excluded by precipitation filter (1613
 data points = 9.21 % in total)
1613 data points (9.21%) excluded in total
15907 valid data points (90.79%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-Fo1-2018”

Quality control:
TA: 17520 data points (100%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1723 additional data points (9.83%) excluded by precipitation filter (1723
 data points = 9.83 % in total)
1723 data points (9.83%) excluded in total
15797 valid data points (90.17%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-Fo1-2019”

Quality control:
TA: 17568 data points (100%) set to NA
H: 17568 data points (100%) set to NA
LE: 17568 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1116 additional data points (6.35%) excluded by precipitation filter (1116
 data points = 6.35 % in total)
1116 data points (6.35%) excluded in total
16452 valid data points (93.65%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-Fo1-2020”

Quality control:
TA: 17520 data points (100%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1312 additional data points (7.49%) excluded by precipitation filter (1312
 data points = 7.49 % in total)
1312 data points (7.49%) excluded in total
16208 valid data points (92.51%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-Fo1-2021”

Quality control:
TA: 14025 data points (80.05%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2380 additional data points (13.58%) excluded by precipitation filter (2380
 data points = 13.58 % in total)
2380 data points (13.58%) excluded in total
15140 valid data points (86.42%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-Fo1-2022”

Quality control:
TA: 4017 data points (22.93%) set to NA
H: 11800 data points (67.35%) set to NA
LE: 12147 data points (69.33%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3610 additional data points (20.61%) excluded by precipitation filter (3610
 data points = 20.61 % in total)
3610 data points (20.61%) excluded in total
13910 valid data points (79.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4017 data points (22.93%) set to NA
H: 11800 data points (67.35%) set to NA
LE: 12147 data points (69.33%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Fo1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Fo1-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 7085 data points (40.33%) set to NA
H: 13300 data points (75.71%) set to NA
LE: 13312 data points (75.77%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1428 additional data points (8.13%) excluded by precipitation filter (1428
 data points = 8.13 % in total)
1428 data points (8.13%) excluded in total
16140 valid data points (91.87%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7085 data points (40.33%) set to NA
H: 13300 data points (75.71%) set to NA
LE: 13312 data points (75.77%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-Fo1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Fo1-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[217/329] Processing: US-GLE

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-GLE | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 168 data points (0.96%) set to NA
H: 213 data points (1.22%) set to NA
LE: 346 data points (1.97%) set to NA
NEE: 933 data points (5.33%) set to NA
-------------------------------------------------------------------
Data filtering:
11760 data points (67.12%) excluded by growing season filter
2602 additional data points (14.85%) excluded by precipitation filter (9463
 data points = 54.01 % in total)
14362 data points (81.97%) excluded in total
3158 valid data points (18.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 168 data points (0.96%) set to NA
H: 213 data points (1.22%) set to NA
LE: 346 data points (1.97%) set to NA
NEE: 933 data points (5.33%) set to NA
-------------------------------------------------------------------
Data filtering:
11760 data points (67.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11760 data points (67.12%) excluded in total
5760 valid data points (32.88%) remaining.

New sEddyProc class for site 'US-GLE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-GLE-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 6 data points (0.03%) set to NA
LE: 121 data points (0.69%) set to NA
NEE: 660 data points (3.77%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
2455 additional data points (14.01%) excluded by precipitation filter (9567
 data points = 54.61 % in total)
13111 data points (74.83%) excluded in total
4409 valid data points (25.17%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 6 data points (0.03%) set to NA
LE: 121 data points (0.69%) set to NA
NEE: 660 data points (3.77%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10656 data points (60.82%) excluded in total
6864 valid data points (39.18%) remaining.

New sEddyProc class for site 'US-GLE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-GLE-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 37 data points (0.21%) set to NA
LE: 115 data points (0.66%) set to NA
NEE: 368 data points (2.1%) set to NA
-------------------------------------------------------------------
Data filtering:
11376 data points (64.93%) excluded by growing season filter
2625 additional data points (14.98%) excluded by precipitation filter (9459
 data points = 53.99 % in total)
14001 data points (79.91%) excluded in total
3519 valid data points (20.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 37 data points (0.21%) set to NA
LE: 115 data points (0.66%) set to NA
NEE: 368 data points (2.1%) set to NA
-------------------------------------------------------------------
Data filtering:
11376 data points (64.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11376 data points (64.93%) excluded in total
6144 valid data points (35.07%) remaining.

New sEddyProc class for site 'US-GLE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-GLE-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4404 data points (25.07%) set to NA
H: 4416 data points (25.14%) set to NA
LE: 4456 data points (25.36%) set to NA
NEE: 4574 data points (26.04%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 82”

-------------------------------------------------------------------
Data filtering:
6528 data points (37.16%) excluded by growing season filter
3136 additional data points (17.85%) excluded by precipitation filter (7917
 data points = 45.06 % in total)
9664 data points (55.01%) excluded in total
7904 valid data points (44.99%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4404 data points (25.07%) set to NA
H: 4416 data points (25.14%) set to NA
LE: 4456 data points (25.36%) set to NA
NEE: 4574 data points (26.04%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 82”

-------------------------------------------------------------------
Data filtering:
6528 data points (37.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6528 data points (37.16%) excluded in total
11040 valid data points (62.84%) remaining.

New sEddyProc class for site 'US-GLE'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 95.7.

Regression of reference temperature R_ref for 6 periods.

[218/329] Processing: US-HB1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-HB1 | Years: 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 46 data points (0.26%) set to NA
H: 1301 data points (7.43%) set to NA
LE: 1298 data points (7.41%) set to NA
NEE: 1343 data points (7.67%) set to NA
-------------------------------------------------------------------
Data filtering:
6240 data points (35.62%) excluded by growing season filter
3920 additional data points (22.37%) excluded by precipitation filter (6540
 data points = 37.33 % in total)
10160 data points (57.99%) excluded in total
7360 valid data points (42.01%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 46 data points (0.26%) set to NA
H: 1301 data points (7.43%) set to NA
LE: 1298 data points (7.41%) set to NA
NEE: 1343 data points (7.67%) set to NA
-------------------------------------------------------------------
Data filtering:
6240 data points (35.62%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6240 data points (35.62%) excluded in total
11280 valid data points (64.38%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -55 ...”
New sEddyProc class for site 'US-HB1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -55 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB1-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4166 data points (23.78%) set to NA
H: 4156 data points (23.72%) set to NA
LE: 4155 data points (23.72%) set to NA
NEE: 4262 data points (24.33%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 51”

-------------------------------------------------------------------
Data filtering:
5328 data points (30.41%) excluded by growing season filter
3580 additional data points (20.43%) excluded by precipitation filter (5127
 data points = 29.26 % in total)
8908 data points (50.84%) excluded in total
8612 valid data points (49.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4166 data points (23.78%) set to NA
H: 4156 data points (23.72%) set to NA
LE: 4155 data points (23.72%) set to NA
NEE: 4262 data points (24.33%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 51”

-------------------------------------------------------------------
Data filtering:
5328 data points (30.41%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5328 data points (30.41%) excluded in total
12192 valid data points (69.59%) remaining.

New sEddyProc class for site 'US-HB1'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 171.39.

Regression of reference temperature R_ref for 14 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 2 data points (0.01%) set to NA
LE: 6 data points (0.03%) set to NA
NEE: 58 data points (0.33%) set to NA
-------------------------------------------------------------------
Data filtering:
5664 data points (32.24%) excluded by growing season filter
4681 additional data points (26.65%) excluded by precipitation filter (6502
 data points = 37.01 % in total)
10345 data points (58.89%) excluded in total
7223 valid data points (41.11%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2 data points (0.01%) set to NA
LE: 6 data points (0.03%) set to NA
NEE: 58 data points (0.33%) set to NA
-------------------------------------------------------------------
Data filtering:
5664 data points (32.24%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5664 data points (32.24%) excluded in total
11904 valid data points (67.76%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -69, -57, -63, -65, -56 ...”
New sEddyProc class for site 'US-HB1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -69, -57, -63, -65, -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB1-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 37 data points (0.21%) set to NA
LE: 50 data points (0.29%) set to NA
NEE: 99 data points (0.57%) set to NA
-------------------------------------------------------------------
Data filtering:
5520 data points (31.51%) excluded by growing season filter
3437 additional data points (19.62%) excluded by precipitation filter (5260
 data points = 30.02 % in total)
8957 data points (51.12%) excluded in total
8563 valid data points (48.88%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 37 data points (0.21%) set to NA
LE: 50 data points (0.29%) set to NA
NEE: 99 data points (0.57%) set to NA
-------------------------------------------------------------------
Data filtering:
5520 data points (31.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5520 data points (31.51%) excluded in total
12000 valid data points (68.49%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -54, -57, -57 ...”
New sEddyProc class for site 'US-HB1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -54, -57, -57 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB1-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 21 data points (0.12%) set to NA
LE: 41 data points (0.23%) set to NA
NEE: 65 data points (0.37%) set to NA
-------------------------------------------------------------------
Data filtering:
6960 data points (39.73%) excluded by growing season filter
3554 additional data points (20.29%) excluded by precipitation filter (5462
 data points = 31.18 % in total)
10514 data points (60.01%) excluded in total
7006 valid data points (39.99%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 21 data points (0.12%) set to NA
LE: 41 data points (0.23%) set to NA
NEE: 65 data points (0.37%) set to NA
-------------------------------------------------------------------
Data filtering:
6960 data points (39.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6960 data points (39.73%) excluded in total
10560 valid data points (60.27%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -65, -51, -57, -51, -51 ...”
New sEddyProc class for site 'US-HB1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -65, -51, -57, -51, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB1-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1884 data points (10.75%) set to NA
LE: 1896 data points (10.82%) set to NA
NEE: 2004 data points (11.44%) set to NA
-------------------------------------------------------------------
Data filtering:
8160 data points (46.58%) excluded by growing season filter
3348 additional data points (19.11%) excluded by precipitation filter (5586
 data points = 31.88 % in total)
11508 data points (65.68%) excluded in total
6012 valid data points (34.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1884 data points (10.75%) set to NA
LE: 1896 data points (10.82%) set to NA
NEE: 2004 data points (11.44%) set to NA
-------------------------------------------------------------------
Data filtering:
8160 data points (46.58%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8160 data points (46.58%) excluded in total
9360 valid data points (53.42%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -55, -52 ...”
New sEddyProc class for site 'US-HB1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -55, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB1-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 11 data points (0.06%) set to NA
H: 13 data points (0.07%) set to NA
LE: 22 data points (0.13%) set to NA
NEE: 50 data points (0.28%) set to NA
-------------------------------------------------------------------
Data filtering:
6528 data points (37.16%) excluded by growing season filter
3286 additional data points (18.7%) excluded by precipitation filter (4696
 data points = 26.73 % in total)
9814 data points (55.86%) excluded in total
7754 valid data points (44.14%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11 data points (0.06%) set to NA
H: 13 data points (0.07%) set to NA
LE: 22 data points (0.13%) set to NA
NEE: 50 data points (0.28%) set to NA
-------------------------------------------------------------------
Data filtering:
6528 data points (37.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6528 data points (37.16%) excluded in total
11040 valid data points (62.84%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -52, -62, -59, -67, -51 ...”
New sEddyProc class for site 'US-HB1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -52, -62, -59, -67, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB1-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[219/329] Processing: US-HB2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-HB2 | Years: 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 11314 data points (64.58%) set to NA
H: 11320 data points (64.61%) set to NA
LE: 11320 data points (64.61%) set to NA
NEE: 11451 data points (65.36%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6394 additional data points (36.5%) excluded by precipitation filter (6394
 data points = 36.5 % in total)
6394 data points (36.5%) excluded in total
11126 valid data points (63.5%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11314 data points (64.58%) set to NA
H: 11320 data points (64.61%) set to NA
LE: 11320 data points (64.61%) set to NA
NEE: 11451 data points (65.36%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -56, -58, -64, -50, -61, -70, -64, -66, -52 ...”
New sEddyProc class for site 'US-HB2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -56, -58, -64, -50, -61, -70, -64, -66, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 1 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB2-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 645 data points (3.68%) set to NA
H: 612 data points (3.49%) set to NA
LE: 662 data points (3.78%) set to NA
NEE: 889 data points (5.07%) set to NA
-------------------------------------------------------------------
Data filtering:
624 data points (3.56%) excluded by growing season filter
4947 additional data points (28.24%) excluded by precipitation filter (5142
 data points = 29.35 % in total)
5571 data points (31.8%) excluded in total
11949 valid data points (68.2%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 645 data points (3.68%) set to NA
H: 612 data points (3.49%) set to NA
LE: 662 data points (3.78%) set to NA
NEE: 889 data points (5.07%) set to NA
-------------------------------------------------------------------
Data filtering:
624 data points (3.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
624 data points (3.56%) excluded in total
16896 valid data points (96.44%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 23 cases! Invalid values with 'NEE < -50': -78, -53, -66, -53, -80, -63, -62, -62, -67, -56, -54, -57, -71, -64, -53, -60, -54, -53, -52, -72, -52, -64, -55 ...”
New sEddyProc class for site 'US-HB2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 23 cases! Invalid values with 'NEE < -50': -78, -53, -66, -53, -80, -63, -62, -62, -67, -56, -54, -57, -71, -64, -53, -60, -54, -53, -52, -72, -52, -64, -55 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB2-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 26 data points (0.15%) set to NA
H: 111 data points (0.63%) set to NA
LE: 158 data points (0.9%) set to NA
NEE: 646 data points (3.68%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6269 additional data points (35.68%) excluded by precipitation filter (6269
 data points = 35.68 % in total)
6269 data points (35.68%) excluded in total
11299 valid data points (64.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 26 data points (0.15%) set to NA
H: 111 data points (0.63%) set to NA
LE: 158 data points (0.9%) set to NA
NEE: 646 data points (3.68%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 44 cases! Invalid values with 'NEE < -50': -60, -74, -59, -79, -63, -52, -65, -56, -62, -59, -72, -58, -71, -50, -62, -63, -71, -52, -63, -52, -55, -55, -64, -55, -55, -66, -73, -53, -56, -79, -58, -59, -54, -76, -51, -54, -67, -62, -65, -62, -62, -65, -62, -68 ...”
New sEddyProc class for site 'US-HB2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 44 cases! Invalid values with 'NEE < -50': -60, -74, -59, -79, -63, -52, -65, -56, -62, -59, -72, -58, -71, -50, -62, -63, -71, -52, -63, -52, -55, -55, -64, -55, -55, -66, -73, -53, -56, -79, -58, -59, -54, -76, -51, -54, -67, -62, -65, -62, -62, -65, -62, -68 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB2-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 0 data points (0%) set to NA
LE: 37 data points (0.21%) set to NA
NEE: 364 data points (2.08%) set to NA
-------------------------------------------------------------------
Data filtering:
768 data points (4.38%) excluded by growing season filter
5165 additional data points (29.48%) excluded by precipitation filter (5406
 data points = 30.86 % in total)
5933 data points (33.86%) excluded in total
11587 valid data points (66.14%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 0 data points (0%) set to NA
LE: 37 data points (0.21%) set to NA
NEE: 364 data points (2.08%) set to NA
-------------------------------------------------------------------
Data filtering:
768 data points (4.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
768 data points (4.38%) excluded in total
16752 valid data points (95.62%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 32 cases! Invalid values with 'NEE < -50': -75, -64, -53, -51, -78, -69, -50, -71, -65, -74, -66, -51, -53, -53, -77, -64, -80, -66, -72, -61, -59, -53, -61, -61, -66, -55, -55, -69, -56, -70, -71, -55 ...”
New sEddyProc class for site 'US-HB2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 32 cases! Invalid values with 'NEE < -50': -75, -64, -53, -51, -78, -69, -50, -71, -65, -74, -66, -51, -53, -53, -77, -64, -80, -66, -72, -61, -59, -53, -61, -61, -66, -55, -55, -69, -56, -70, -71, -55 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB2-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 345 data points (1.97%) set to NA
H: 225 data points (1.28%) set to NA
LE: 797 data points (4.55%) set to NA
NEE: 1363 data points (7.78%) set to NA
-------------------------------------------------------------------
Data filtering:
2640 data points (15.07%) excluded by growing season filter
4764 additional data points (27.19%) excluded by precipitation filter (5556
 data points = 31.71 % in total)
7404 data points (42.26%) excluded in total
10116 valid data points (57.74%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 345 data points (1.97%) set to NA
H: 225 data points (1.28%) set to NA
LE: 797 data points (4.55%) set to NA
NEE: 1363 data points (7.78%) set to NA
-------------------------------------------------------------------
Data filtering:
2640 data points (15.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2640 data points (15.07%) excluded in total
14880 valid data points (84.93%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 10 cases! Invalid values with 'NEE < -50': -63, -58, -63, -68, -54, -57, -69, -67, -59, -70 ...”
New sEddyProc class for site 'US-HB2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 10 cases! Invalid values with 'NEE < -50': -63, -58, -63, -68, -54, -57, -69, -67, -59, -70 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB2-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2 data points (0.01%) set to NA
H: 10 data points (0.06%) set to NA
LE: 28 data points (0.16%) set to NA
NEE: 859 data points (4.9%) set to NA
-------------------------------------------------------------------
Data filtering:
1392 data points (7.95%) excluded by growing season filter
5236 additional data points (29.89%) excluded by precipitation filter (5742
 data points = 32.77 % in total)
6628 data points (37.83%) excluded in total
10892 valid data points (62.17%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2 data points (0.01%) set to NA
H: 10 data points (0.06%) set to NA
LE: 28 data points (0.16%) set to NA
NEE: 859 data points (4.9%) set to NA
-------------------------------------------------------------------
Data filtering:
1392 data points (7.95%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1392 data points (7.95%) excluded in total
16128 valid data points (92.05%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -50, -53, -58, -59, -56, -51, -51, -67 ...”
New sEddyProc class for site 'US-HB2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -50, -53, -58, -59, -56, -51, -51, -67 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB2-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3 data points (0.02%) set to NA
H: 9 data points (0.05%) set to NA
LE: 24 data points (0.14%) set to NA
NEE: 672 data points (3.83%) set to NA
-------------------------------------------------------------------
Data filtering:
384 data points (2.19%) excluded by growing season filter
4635 additional data points (26.38%) excluded by precipitation filter (4846
 data points = 27.58 % in total)
5019 data points (28.57%) excluded in total
12549 valid data points (71.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3 data points (0.02%) set to NA
H: 9 data points (0.05%) set to NA
LE: 24 data points (0.14%) set to NA
NEE: 672 data points (3.83%) set to NA
-------------------------------------------------------------------
Data filtering:
384 data points (2.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
384 data points (2.19%) excluded in total
17184 valid data points (97.81%) remaining.

New sEddyProc class for site 'US-HB2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB2-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[220/329] Processing: US-HB3

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-HB3 | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 204 data points (1.16%) set to NA
H: 192 data points (1.1%) set to NA
LE: 285 data points (1.63%) set to NA
NEE: 578 data points (3.3%) set to NA
-------------------------------------------------------------------
Data filtering:
5520 data points (31.51%) excluded by growing season filter
3525 additional data points (20.12%) excluded by precipitation filter (5097
 data points = 29.09 % in total)
9045 data points (51.63%) excluded in total
8475 valid data points (48.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 204 data points (1.16%) set to NA
H: 192 data points (1.1%) set to NA
LE: 285 data points (1.63%) set to NA
NEE: 578 data points (3.3%) set to NA
-------------------------------------------------------------------
Data filtering:
5520 data points (31.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5520 data points (31.51%) excluded in total
12000 valid data points (68.49%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -67, -55 ...”
New sEddyProc class for site 'US-HB3'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -67, -55 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 1 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB3-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 19 data points (0.11%) set to NA
LE: 27 data points (0.15%) set to NA
NEE: 326 data points (1.86%) set to NA
-------------------------------------------------------------------
Data filtering:
6192 data points (35.25%) excluded by growing season filter
4414 additional data points (25.13%) excluded by precipitation filter (6430
 data points = 36.6 % in total)
10606 data points (60.37%) excluded in total
6962 valid data points (39.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 19 data points (0.11%) set to NA
LE: 27 data points (0.15%) set to NA
NEE: 326 data points (1.86%) set to NA
-------------------------------------------------------------------
Data filtering:
6192 data points (35.25%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6192 data points (35.25%) excluded in total
11376 valid data points (64.75%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 10 cases! Invalid values with 'NEE < -50': -52, -61, -60, -73, -63, -55, -57, -55, -51, -52 ...”
New sEddyProc class for site 'US-HB3'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 10 cases! Invalid values with 'NEE < -50': -52, -61, -60, -73, -63, -55, -57, -55, -51, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB3-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 10 data points (0.06%) set to NA
H: 33 data points (0.19%) set to NA
LE: 64 data points (0.37%) set to NA
NEE: 543 data points (3.1%) set to NA
-------------------------------------------------------------------
Data filtering:
6240 data points (35.62%) excluded by growing season filter
3347 additional data points (19.1%) excluded by precipitation filter (5288
 data points = 30.18 % in total)
9587 data points (54.72%) excluded in total
7933 valid data points (45.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10 data points (0.06%) set to NA
H: 33 data points (0.19%) set to NA
LE: 64 data points (0.37%) set to NA
NEE: 543 data points (3.1%) set to NA
-------------------------------------------------------------------
Data filtering:
6240 data points (35.62%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6240 data points (35.62%) excluded in total
11280 valid data points (64.38%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -55, -55, -59, -68, -57, -58, -63, -51, -54 ...”
New sEddyProc class for site 'US-HB3'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 9 cases! Invalid values with 'NEE < -50': -55, -55, -59, -68, -57, -58, -63, -51, -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB3-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 29 data points (0.17%) set to NA
NEE: 399 data points (2.28%) set to NA
-------------------------------------------------------------------
Data filtering:
3504 data points (20%) excluded by growing season filter
4411 additional data points (25.18%) excluded by precipitation filter (5452
 data points = 31.12 % in total)
7915 data points (45.18%) excluded in total
9605 valid data points (54.82%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 29 data points (0.17%) set to NA
NEE: 399 data points (2.28%) set to NA
-------------------------------------------------------------------
Data filtering:
3504 data points (20%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3504 data points (20%) excluded in total
14016 valid data points (80%) remaining.

New sEddyProc class for site 'US-HB3'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB3-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2 data points (0.01%) set to NA
H: 30 data points (0.17%) set to NA
LE: 45 data points (0.26%) set to NA
NEE: 454 data points (2.59%) set to NA
-------------------------------------------------------------------
Data filtering:
2256 data points (12.88%) excluded by growing season filter
5057 additional data points (28.86%) excluded by precipitation filter (5772
 data points = 32.95 % in total)
7313 data points (41.74%) excluded in total
10207 valid data points (58.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2 data points (0.01%) set to NA
H: 30 data points (0.17%) set to NA
LE: 45 data points (0.26%) set to NA
NEE: 454 data points (2.59%) set to NA
-------------------------------------------------------------------
Data filtering:
2256 data points (12.88%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2256 data points (12.88%) excluded in total
15264 valid data points (87.12%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -51, -56 ...”
New sEddyProc class for site 'US-HB3'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -51, -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB3-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 158 data points (0.9%) set to NA
H: 60 data points (0.34%) set to NA
LE: 177 data points (1.01%) set to NA
NEE: 322 data points (1.83%) set to NA
-------------------------------------------------------------------
Data filtering:
1248 data points (7.1%) excluded by growing season filter
5076 additional data points (28.89%) excluded by precipitation filter (5449
 data points = 31.02 % in total)
6324 data points (36%) excluded in total
11244 valid data points (64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 158 data points (0.9%) set to NA
H: 60 data points (0.34%) set to NA
LE: 177 data points (1.01%) set to NA
NEE: 322 data points (1.83%) set to NA
-------------------------------------------------------------------
Data filtering:
1248 data points (7.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1248 data points (7.1%) excluded in total
16320 valid data points (92.9%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
New sEddyProc class for site 'US-HB3'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB3-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[221/329] Processing: US-HB4

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-HB4 | Years: 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 3823 data points (21.76%) set to NA
H: 3639 data points (20.71%) set to NA
LE: 3645 data points (20.75%) set to NA
NEE: 3676 data points (20.92%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 66”

-------------------------------------------------------------------
Data filtering:
8592 data points (48.91%) excluded by growing season filter
3173 additional data points (18.06%) excluded by precipitation filter (4757
 data points = 27.08 % in total)
11765 data points (66.97%) excluded in total
5803 valid data points (33.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3823 data points (21.76%) set to NA
H: 3639 data points (20.71%) set to NA
LE: 3645 data points (20.75%) set to NA
NEE: 3676 data points (20.92%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 66”

-------------------------------------------------------------------
Data filtering:
8592 data points (48.91%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8592 data points (48.91%) excluded in total
8976 valid data points (51.09%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -52, -64, -56 ...”
New sEddyProc class for site 'US-HB4'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -52, -64, -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 94.38.

Regression of reference temperature R_ref for 8 periods.

Quality control:
TA: 250 data points (1.43%) set to NA
H: 349 data points (1.99%) set to NA
LE: 354 data points (2.02%) set to NA
NEE: 389 data points (2.22%) set to NA
-------------------------------------------------------------------
Data filtering:
8736 data points (49.86%) excluded by growing season filter
2604 additional data points (14.86%) excluded by precipitation filter (5371
 data points = 30.66 % in total)
11340 data points (64.73%) excluded in total
6180 valid data points (35.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 250 data points (1.43%) set to NA
H: 349 data points (1.99%) set to NA
LE: 354 data points (2.02%) set to NA
NEE: 389 data points (2.22%) set to NA
-------------------------------------------------------------------
Data filtering:
8736 data points (49.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8736 data points (49.86%) excluded in total
8784 valid data points (50.14%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -58, -57 ...”
New sEddyProc class for site 'US-HB4'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -58, -57 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB4-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 102 data points (0.58%) set to NA
H: 112 data points (0.64%) set to NA
LE: 123 data points (0.7%) set to NA
NEE: 128 data points (0.73%) set to NA
-------------------------------------------------------------------
Data filtering:
8784 data points (50.14%) excluded by growing season filter
2903 additional data points (16.57%) excluded by precipitation filter (4950
 data points = 28.25 % in total)
11687 data points (66.71%) excluded in total
5833 valid data points (33.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 102 data points (0.58%) set to NA
H: 112 data points (0.64%) set to NA
LE: 123 data points (0.7%) set to NA
NEE: 128 data points (0.73%) set to NA
-------------------------------------------------------------------
Data filtering:
8784 data points (50.14%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8784 data points (50.14%) excluded in total
8736 valid data points (49.86%) remaining.

New sEddyProc class for site 'US-HB4'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB4-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 345 data points (1.97%) set to NA
H: 359 data points (2.05%) set to NA
LE: 379 data points (2.16%) set to NA
NEE: 417 data points (2.38%) set to NA
-------------------------------------------------------------------
Data filtering:
8064 data points (46.03%) excluded by growing season filter
3089 additional data points (17.63%) excluded by precipitation filter (5041
 data points = 28.77 % in total)
11153 data points (63.66%) excluded in total
6367 valid data points (36.34%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 345 data points (1.97%) set to NA
H: 359 data points (2.05%) set to NA
LE: 379 data points (2.16%) set to NA
NEE: 417 data points (2.38%) set to NA
-------------------------------------------------------------------
Data filtering:
8064 data points (46.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8064 data points (46.03%) excluded in total
9456 valid data points (53.97%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 6 cases! Invalid values with 'NEE < -50': -53, -69, -53, -54, -53, -52 ...”
New sEddyProc class for site 'US-HB4'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 6 cases! Invalid values with 'NEE < -50': -53, -69, -53, -54, -53, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB4-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4 data points (0.02%) set to NA
H: 18 data points (0.1%) set to NA
LE: 26 data points (0.15%) set to NA
NEE: 45 data points (0.26%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.01%) excluded by growing season filter
3156 additional data points (17.96%) excluded by precipitation filter (5528
 data points = 31.47 % in total)
12468 data points (70.97%) excluded in total
5100 valid data points (29.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4 data points (0.02%) set to NA
H: 18 data points (0.1%) set to NA
LE: 26 data points (0.15%) set to NA
NEE: 45 data points (0.26%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.01%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9312 data points (53.01%) excluded in total
8256 valid data points (46.99%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -53, -57 ...”
New sEddyProc class for site 'US-HB4'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -53, -57 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HB4-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[222/329] Processing: US-HBK

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-HBK | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 3352 data points (19.13%) set to NA
H: 5295 data points (30.22%) set to NA
LE: 5359 data points (30.59%) set to NA
NEE: 5916 data points (33.77%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 33”

-------------------------------------------------------------------
Data filtering:
10080 data points (57.53%) excluded by growing season filter
4728 additional data points (26.99%) excluded by precipitation filter (11474
 data points = 65.49 % in total)
14808 data points (84.52%) excluded in total
2712 valid data points (15.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3352 data points (19.13%) set to NA
H: 5295 data points (30.22%) set to NA
LE: 5359 data points (30.59%) set to NA
NEE: 5916 data points (33.77%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 33”

-------------------------------------------------------------------
Data filtering:
10080 data points (57.53%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10080 data points (57.53%) excluded in total
7440 valid data points (42.47%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -52, -59, -70, -77, -60, -68, -55 ...”
New sEddyProc class for site 'US-HBK'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -52, -59, -70, -77, -60, -68, -55 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 22 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HBK-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1242 data points (7.09%) set to NA
H: 3840 data points (21.92%) set to NA
LE: 3851 data points (21.98%) set to NA
NEE: 4239 data points (24.2%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.73%) excluded by growing season filter
4218 additional data points (24.08%) excluded by precipitation filter (11244
 data points = 64.18 % in total)
14682 data points (83.8%) excluded in total
2838 valid data points (16.2%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1242 data points (7.09%) set to NA
H: 3840 data points (21.92%) set to NA
LE: 3851 data points (21.98%) set to NA
NEE: 4239 data points (24.2%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10464 data points (59.73%) excluded in total
7056 valid data points (40.27%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 6 cases! Invalid values with 'NEE < -50': -62, -62, -53, -75, -63, -63 ...”
New sEddyProc class for site 'US-HBK'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 6 cases! Invalid values with 'NEE < -50': -62, -62, -53, -75, -63, -63 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HBK-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 121 data points (0.69%) set to NA
H: 229 data points (1.31%) set to NA
LE: 233 data points (1.33%) set to NA
NEE: 639 data points (3.65%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
4414 additional data points (25.19%) excluded by precipitation filter (10988
 data points = 62.72 % in total)
14638 data points (83.55%) excluded in total
2882 valid data points (16.45%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 121 data points (0.69%) set to NA
H: 229 data points (1.31%) set to NA
LE: 233 data points (1.33%) set to NA
NEE: 639 data points (3.65%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10224 data points (58.36%) excluded in total
7296 valid data points (41.64%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 40 cases! Invalid values with 'NEE < -50': -52, -53, -64, -64, -63, -63, -54, -57, -64, -76, -65, -65, -72, -69, -67, -73, -62, -62, -62, -62, -62, -62, -62, -62, -62, -76, -62, -62, -62, -79, -51, -62, -62, -62, -62, -62, -62, -62, -54, -62 ...”
New sEddyProc class for site 'US-HBK'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 40 cases! Invalid values with 'NEE < -50': -52, -53, -64, -64, -63, -63, -54, -57, -64, -76, -65, -65, -72, -69, -67, -73, -62, -62, -62, -62, -62, -62, -62, -62, -62, -76, -62, -62, -62, -79, -51, -62, -62, -62, -62, -62, -62, -62, -54, -62 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HBK-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 3541 data points (20.16%) set to NA
LE: 3555 data points (20.24%) set to NA
NEE: 3946 data points (22.46%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 42”

-------------------------------------------------------------------
Data filtering:
10752 data points (61.2%) excluded by growing season filter
3710 additional data points (21.12%) excluded by precipitation filter (10300
 data points = 58.63 % in total)
14462 data points (82.32%) excluded in total
3106 valid data points (17.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 3541 data points (20.16%) set to NA
LE: 3555 data points (20.24%) set to NA
NEE: 3946 data points (22.46%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 42”

-------------------------------------------------------------------
Data filtering:
10752 data points (61.2%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10752 data points (61.2%) excluded in total
6816 valid data points (38.8%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 15 cases! Invalid values with 'NEE < -50': -67, -70, -61, -64, -53, -51, -65, -61, -57, -63, -57, -56, -61, -52, -80 ...”
New sEddyProc class for site 'US-HBK'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 15 cases! Invalid values with 'NEE < -50': -67, -70, -61, -64, -53, -51, -65, -61, -57, -63, -57, -56, -61, -52, -80 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HBK-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 20 data points (0.11%) set to NA
H: 3210 data points (18.32%) set to NA
LE: 3213 data points (18.34%) set to NA
NEE: 3659 data points (20.88%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 35”

-------------------------------------------------------------------
Data filtering:
10176 data points (58.08%) excluded by growing season filter
5028 additional data points (28.7%) excluded by precipitation filter (11406
 data points = 65.1 % in total)
15204 data points (86.78%) excluded in total
2316 valid data points (13.22%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 20 data points (0.11%) set to NA
H: 3210 data points (18.32%) set to NA
LE: 3213 data points (18.34%) set to NA
NEE: 3659 data points (20.88%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 35”

-------------------------------------------------------------------
Data filtering:
10176 data points (58.08%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10176 data points (58.08%) excluded in total
7344 valid data points (41.92%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -65, -54, -68, -51, -74, -74, -78, -70 ...”
New sEddyProc class for site 'US-HBK'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -65, -54, -68, -51, -74, -74, -78, -70 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HBK-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 29 data points (0.17%) set to NA
H: 299 data points (1.71%) set to NA
LE: 324 data points (1.85%) set to NA
NEE: 896 data points (5.11%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (60%) excluded by growing season filter
4414 additional data points (25.19%) excluded by precipitation filter (10548
 data points = 60.21 % in total)
14926 data points (85.19%) excluded in total
2594 valid data points (14.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 29 data points (0.17%) set to NA
H: 299 data points (1.71%) set to NA
LE: 324 data points (1.85%) set to NA
NEE: 896 data points (5.11%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (60%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10512 data points (60%) excluded in total
7008 valid data points (40%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -50, -60, -77, -51, -53, -62, -54 ...”
New sEddyProc class for site 'US-HBK'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -50, -60, -77, -51, -53, -62, -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HBK-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 844 data points (4.82%) set to NA
LE: 7014 data points (40.03%) set to NA
NEE: 7355 data points (41.98%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 90”

-------------------------------------------------------------------
Data filtering:
10896 data points (62.19%) excluded by growing season filter
4752 additional data points (27.12%) excluded by precipitation filter (11582
 data points = 66.11 % in total)
15648 data points (89.32%) excluded in total
1872 valid data points (10.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 844 data points (4.82%) set to NA
LE: 7014 data points (40.03%) set to NA
NEE: 7355 data points (41.98%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 90”

-------------------------------------------------------------------
Data filtering:
10896 data points (62.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10896 data points (62.19%) excluded in total
6624 valid data points (37.81%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 14 cases! Invalid values with 'NEE < -50': -62, -78, -59, -60, -57, -57, -57, -54, -59, -53, -67, -72, -60, -65 ...”
New sEddyProc class for site 'US-HBK'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 14 cases! Invalid values with 'NEE < -50': -62, -78, -59, -60, -57, -57, -57, -54, -59, -53, -67, -72, -60, -65 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HBK-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6855 data points (39.02%) set to NA
H: 6899 data points (39.27%) set to NA
LE: 8533 data points (48.57%) set to NA
NEE: 8782 data points (49.99%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 133”

-------------------------------------------------------------------
Data filtering:
6240 data points (35.52%) excluded by growing season filter
7110 additional data points (40.47%) excluded by precipitation filter (10990
 data points = 62.56 % in total)
13350 data points (75.99%) excluded in total
4218 valid data points (24.01%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6855 data points (39.02%) set to NA
H: 6899 data points (39.27%) set to NA
LE: 8533 data points (48.57%) set to NA
NEE: 8782 data points (49.99%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 133”

-------------------------------------------------------------------
Data filtering:
6240 data points (35.52%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6240 data points (35.52%) excluded in total
11328 valid data points (64.48%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 12 cases! Invalid values with 'NEE < -50': -74, -78, -55, -68, -67, -62, -65, -76, -72, -59, -69, -60 ...”
New sEddyProc class for site 'US-HBK'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 12 cases! Invalid values with 'NEE < -50': -74, -78, -55, -68, -67, -62, -65, -76, -72, -59, -69, -60 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-HBK-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[223/329] Processing: US-Hn3

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Hn3 | Years: 2017, 2018
Quality control:
TA: 16209 data points (92.52%) set to NA
H: 15344 data points (87.58%) set to NA
LE: 15349 data points (87.61%) set to NA
NEE: 15347 data points (87.6%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
151 additional data points (0.86%) excluded by precipitation filter (151
 data points = 0.86 % in total)
151 data points (0.86%) excluded in total
17369 valid data points (99.14%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 16209 data points (92.52%) set to NA
H: 15344 data points (87.58%) set to NA
LE: 15349 data points (87.61%) set to NA
NEE: 15347 data points (87.6%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Hn3'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 179.09.

Regression of reference temperature R_ref for 6 periods.

Quality control:
TA: 5322 data points (30.38%) set to NA
H: 5333 data points (30.44%) set to NA
LE: 5370 data points (30.65%) set to NA
NEE: 5568 data points (31.78%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 33”

-------------------------------------------------------------------
Data filtering:
5472 data points (31.23%) excluded by growing season filter
200 additional data points (1.14%) excluded by precipitation filter (874
 data points = 4.99 % in total)
5672 data points (32.37%) excluded in total
11848 valid data points (67.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5322 data points (30.38%) set to NA
H: 5333 data points (30.44%) set to NA
LE: 5370 data points (30.65%) set to NA
NEE: 5568 data points (31.78%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 33”

-------------------------------------------------------------------
Data filtering:
5472 data points (31.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5472 data points (31.23%) excluded in total
12048 valid data points (68.77%) remaining.

New sEddyProc class for site 'US-Hn3'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 208.7.

Regression of reference temperature R_ref for 23 periods.

[224/329] Processing: US-Ho2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Ho2 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 439 data points (2.51%) set to NA
H: 538 data points (3.07%) set to NA
LE: 533 data points (3.04%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5843 additional data points (33.35%) excluded by precipitation filter (5843
 data points = 33.35 % in total)
5843 data points (33.35%) excluded in total
11677 valid data points (66.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 439 data points (2.51%) set to NA
H: 538 data points (3.07%) set to NA
LE: 533 data points (3.04%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Ho2'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ho2-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 106 data points (0.61%) set to NA
H: 810 data points (4.62%) set to NA
LE: 2227 data points (12.71%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5498 additional data points (31.38%) excluded by precipitation filter (5498
 data points = 31.38 % in total)
5498 data points (31.38%) excluded in total
12022 valid data points (68.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 106 data points (0.61%) set to NA
H: 810 data points (4.62%) set to NA
LE: 2227 data points (12.71%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Ho2'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ho2-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1634 data points (9.33%) set to NA
H: 7891 data points (45.04%) set to NA
LE: 7893 data points (45.05%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6211 additional data points (35.45%) excluded by precipitation filter (6211
 data points = 35.45 % in total)
6211 data points (35.45%) excluded in total
11309 valid data points (64.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1634 data points (9.33%) set to NA
H: 7891 data points (45.04%) set to NA
LE: 7893 data points (45.05%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Ho2'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ho2-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 271 data points (1.54%) set to NA
H: 517 data points (2.94%) set to NA
LE: 527 data points (3%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5671 additional data points (32.28%) excluded by precipitation filter (5671
 data points = 32.28 % in total)
5671 data points (32.28%) excluded in total
11897 valid data points (67.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 271 data points (1.54%) set to NA
H: 517 data points (2.94%) set to NA
LE: 527 data points (3%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-Ho2'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ho2-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 83 data points (0.47%) set to NA
LE: 88 data points (0.5%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5025 additional data points (28.68%) excluded by precipitation filter (5025
 data points = 28.68 % in total)
5025 data points (28.68%) excluded in total
12495 valid data points (71.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 83 data points (0.47%) set to NA
LE: 88 data points (0.5%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Ho2'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ho2-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 60 data points (0.34%) set to NA
LE: 64 data points (0.37%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5794 additional data points (33.07%) excluded by precipitation filter (5794
 data points = 33.07 % in total)
5794 data points (33.07%) excluded in total
11726 valid data points (66.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 60 data points (0.34%) set to NA
LE: 64 data points (0.37%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Ho2'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ho2-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3667 data points (20.93%) set to NA
H: 1064 data points (6.07%) set to NA
LE: 2305 data points (13.16%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6474 additional data points (36.95%) excluded by precipitation filter (6474
 data points = 36.95 % in total)
6474 data points (36.95%) excluded in total
11046 valid data points (63.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3667 data points (20.93%) set to NA
H: 1064 data points (6.07%) set to NA
LE: 2305 data points (13.16%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Ho2'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ho2-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 342 data points (1.95%) set to NA
H: 237 data points (1.35%) set to NA
LE: 753 data points (4.29%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5689 additional data points (32.38%) excluded by precipitation filter (5689
 data points = 32.38 % in total)
5689 data points (32.38%) excluded in total
11879 valid data points (67.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 342 data points (1.95%) set to NA
H: 237 data points (1.35%) set to NA
LE: 753 data points (4.29%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-Ho2'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ho2-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 7662 data points (43.73%) set to NA
H: 8076 data points (46.1%) set to NA
LE: 8196 data points (46.78%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5396 additional data points (30.8%) excluded by precipitation filter (5396
 data points = 30.8 % in total)
5396 data points (30.8%) excluded in total
12124 valid data points (69.2%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7662 data points (43.73%) set to NA
H: 8076 data points (46.1%) set to NA
LE: 8196 data points (46.78%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Ho2'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ho2-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[225/329] Processing: US-Hsm

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Hsm | Years: 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 3339 data points (19.06%) set to NA
H: 3344 data points (19.09%) set to NA
LE: 3360 data points (19.18%) set to NA
NEE: 5365 data points (30.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 61”

-------------------------------------------------------------------
Data filtering:
9408 data points (53.7%) excluded by growing season filter
50 additional data points (0.29%) excluded by precipitation filter (2523
 data points = 14.4 % in total)
9458 data points (53.98%) excluded in total
8062 valid data points (46.02%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3339 data points (19.06%) set to NA
H: 3344 data points (19.09%) set to NA
LE: 3360 data points (19.18%) set to NA
NEE: 5365 data points (30.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 61”

-------------------------------------------------------------------
Data filtering:
9408 data points (53.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9408 data points (53.7%) excluded in total
8112 valid data points (46.3%) remaining.

New sEddyProc class for site 'US-Hsm'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 183.22.

Regression of reference temperature R_ref for 6 periods.

Quality control:
TA: 48 data points (0.27%) set to NA
H: 76 data points (0.43%) set to NA
LE: 86 data points (0.49%) set to NA
NEE: 2373 data points (13.54%) set to NA
-------------------------------------------------------------------
Data filtering:
8928 data points (50.96%) excluded by growing season filter
680 additional data points (3.88%) excluded by precipitation filter (1950
 data points = 11.13 % in total)
9608 data points (54.84%) excluded in total
7912 valid data points (45.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 48 data points (0.27%) set to NA
H: 76 data points (0.43%) set to NA
LE: 86 data points (0.49%) set to NA
NEE: 2373 data points (13.54%) set to NA
-------------------------------------------------------------------
Data filtering:
8928 data points (50.96%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8928 data points (50.96%) excluded in total
8592 valid data points (49.04%) remaining.

New sEddyProc class for site 'US-Hsm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Hsm-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 72 data points (0.41%) set to NA
H: 80 data points (0.46%) set to NA
LE: 94 data points (0.54%) set to NA
NEE: 1365 data points (7.79%) set to NA
-------------------------------------------------------------------
Data filtering:
6768 data points (38.63%) excluded by growing season filter
516 additional data points (2.95%) excluded by precipitation filter (3215
 data points = 18.35 % in total)
7284 data points (41.58%) excluded in total
10236 valid data points (58.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 72 data points (0.41%) set to NA
H: 80 data points (0.46%) set to NA
LE: 94 data points (0.54%) set to NA
NEE: 1365 data points (7.79%) set to NA
-------------------------------------------------------------------
Data filtering:
6768 data points (38.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6768 data points (38.63%) excluded in total
10752 valid data points (61.37%) remaining.

New sEddyProc class for site 'US-Hsm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Hsm-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 30 data points (0.17%) set to NA
H: 48 data points (0.27%) set to NA
LE: 86 data points (0.49%) set to NA
NEE: 1707 data points (9.72%) set to NA
-------------------------------------------------------------------
Data filtering:
7680 data points (43.72%) excluded by growing season filter
807 additional data points (4.59%) excluded by precipitation filter (3482
 data points = 19.82 % in total)
8487 data points (48.31%) excluded in total
9081 valid data points (51.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 30 data points (0.17%) set to NA
H: 48 data points (0.27%) set to NA
LE: 86 data points (0.49%) set to NA
NEE: 1707 data points (9.72%) set to NA
-------------------------------------------------------------------
Data filtering:
7680 data points (43.72%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7680 data points (43.72%) excluded in total
9888 valid data points (56.28%) remaining.

New sEddyProc class for site 'US-Hsm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Hsm-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 150 data points (0.86%) set to NA
H: 326 data points (1.86%) set to NA
LE: 346 data points (1.97%) set to NA
NEE: 1697 data points (9.69%) set to NA
-------------------------------------------------------------------
Data filtering:
6384 data points (36.44%) excluded by growing season filter
1020 additional data points (5.82%) excluded by precipitation filter (2317
 data points = 13.22 % in total)
7404 data points (42.26%) excluded in total
10116 valid data points (57.74%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 150 data points (0.86%) set to NA
H: 326 data points (1.86%) set to NA
LE: 346 data points (1.97%) set to NA
NEE: 1697 data points (9.69%) set to NA
-------------------------------------------------------------------
Data filtering:
6384 data points (36.44%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6384 data points (36.44%) excluded in total
11136 valid data points (63.56%) remaining.

New sEddyProc class for site 'US-Hsm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Hsm-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[226/329] Processing: US-ICh

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-ICh | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 121 data points (0.69%) set to NA
H: 1860 data points (10.62%) set to NA
LE: 1840 data points (10.5%) set to NA
NEE: 3997 data points (22.81%) set to NA
-------------------------------------------------------------------
Data filtering:
13872 data points (79.18%) excluded by growing season filter
2158 additional data points (12.32%) excluded by precipitation filter (3390
 data points = 19.35 % in total)
16030 data points (91.5%) excluded in total
1490 valid data points (8.5%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 121 data points (0.69%) set to NA
H: 1860 data points (10.62%) set to NA
LE: 1840 data points (10.5%) set to NA
NEE: 3997 data points (22.81%) set to NA
-------------------------------------------------------------------
Data filtering:
13872 data points (79.18%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13872 data points (79.18%) excluded in total
3648 valid data points (20.82%) remaining.

New sEddyProc class for site 'US-ICh'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICh-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 184 data points (1.05%) set to NA
H: 1023 data points (5.84%) set to NA
LE: 995 data points (5.68%) set to NA
NEE: 2692 data points (15.37%) set to NA
-------------------------------------------------------------------
Data filtering:
13968 data points (79.73%) excluded by growing season filter
2273 additional data points (12.97%) excluded by precipitation filter (4134
 data points = 23.6 % in total)
16241 data points (92.7%) excluded in total
1279 valid data points (7.3%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 184 data points (1.05%) set to NA
H: 1023 data points (5.84%) set to NA
LE: 995 data points (5.68%) set to NA
NEE: 2692 data points (15.37%) set to NA
-------------------------------------------------------------------
Data filtering:
13968 data points (79.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13968 data points (79.73%) excluded in total
3552 valid data points (20.27%) remaining.

New sEddyProc class for site 'US-ICh'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICh-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 184 data points (1.05%) set to NA
H: 2310 data points (13.18%) set to NA
LE: 2276 data points (12.99%) set to NA
NEE: 3801 data points (21.7%) set to NA
-------------------------------------------------------------------
Data filtering:
12864 data points (73.42%) excluded by growing season filter
2276 additional data points (12.99%) excluded by precipitation filter (4210
 data points = 24.03 % in total)
15140 data points (86.42%) excluded in total
2380 valid data points (13.58%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 184 data points (1.05%) set to NA
H: 2310 data points (13.18%) set to NA
LE: 2276 data points (12.99%) set to NA
NEE: 3801 data points (21.7%) set to NA
-------------------------------------------------------------------
Data filtering:
12864 data points (73.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12864 data points (73.42%) excluded in total
4656 valid data points (26.58%) remaining.

New sEddyProc class for site 'US-ICh'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICh-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2024 data points (11.52%) set to NA
LE: 1733 data points (9.86%) set to NA
NEE: 3586 data points (20.41%) set to NA
-------------------------------------------------------------------
Data filtering:
14208 data points (80.87%) excluded by growing season filter
1491 additional data points (8.49%) excluded by precipitation filter (3157
 data points = 17.97 % in total)
15699 data points (89.36%) excluded in total
1869 valid data points (10.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2024 data points (11.52%) set to NA
LE: 1733 data points (9.86%) set to NA
NEE: 3586 data points (20.41%) set to NA
-------------------------------------------------------------------
Data filtering:
14208 data points (80.87%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14208 data points (80.87%) excluded in total
3360 valid data points (19.13%) remaining.

New sEddyProc class for site 'US-ICh'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICh-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 33 data points (0.19%) set to NA
H: 1706 data points (9.74%) set to NA
LE: 1819 data points (10.38%) set to NA
NEE: 3378 data points (19.28%) set to NA
-------------------------------------------------------------------
Data filtering:
14544 data points (83.01%) excluded by growing season filter
1837 additional data points (10.49%) excluded by precipitation filter (3749
 data points = 21.4 % in total)
16381 data points (93.5%) excluded in total
1139 valid data points (6.5%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 33 data points (0.19%) set to NA
H: 1706 data points (9.74%) set to NA
LE: 1819 data points (10.38%) set to NA
NEE: 3378 data points (19.28%) set to NA
-------------------------------------------------------------------
Data filtering:
14544 data points (83.01%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14544 data points (83.01%) excluded in total
2976 valid data points (16.99%) remaining.

New sEddyProc class for site 'US-ICh'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICh-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1925 data points (10.99%) set to NA
LE: 1937 data points (11.06%) set to NA
NEE: 2883 data points (16.46%) set to NA
-------------------------------------------------------------------
Data filtering:
12912 data points (73.7%) excluded by growing season filter
2049 additional data points (11.7%) excluded by precipitation filter (2685
 data points = 15.33 % in total)
14961 data points (85.39%) excluded in total
2559 valid data points (14.61%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1925 data points (10.99%) set to NA
LE: 1937 data points (11.06%) set to NA
NEE: 2883 data points (16.46%) set to NA
-------------------------------------------------------------------
Data filtering:
12912 data points (73.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12912 data points (73.7%) excluded in total
4608 valid data points (26.3%) remaining.

New sEddyProc class for site 'US-ICh'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICh-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 7 data points (0.04%) set to NA
H: 1649 data points (9.41%) set to NA
LE: 1643 data points (9.38%) set to NA
NEE: 2767 data points (15.79%) set to NA
-------------------------------------------------------------------
Data filtering:
12816 data points (73.15%) excluded by growing season filter
2479 additional data points (14.15%) excluded by precipitation filter (3067
 data points = 17.51 % in total)
15295 data points (87.3%) excluded in total
2225 valid data points (12.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7 data points (0.04%) set to NA
H: 1649 data points (9.41%) set to NA
LE: 1643 data points (9.38%) set to NA
NEE: 2767 data points (15.79%) set to NA
-------------------------------------------------------------------
Data filtering:
12816 data points (73.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12816 data points (73.15%) excluded in total
4704 valid data points (26.85%) remaining.

New sEddyProc class for site 'US-ICh'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICh-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 779 data points (4.43%) set to NA
LE: 849 data points (4.83%) set to NA
NEE: 2428 data points (13.82%) set to NA
-------------------------------------------------------------------
Data filtering:
13632 data points (77.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13632 data points (77.6%) excluded in total
3936 valid data points (22.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 779 data points (4.43%) set to NA
LE: 849 data points (4.83%) set to NA
NEE: 2428 data points (13.82%) set to NA
-------------------------------------------------------------------
Data filtering:
13632 data points (77.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13632 data points (77.6%) excluded in total
3936 valid data points (22.4%) remaining.

New sEddyProc class for site 'US-ICh'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICh-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 680 data points (3.88%) set to NA
H: 2186 data points (12.48%) set to NA
LE: 2216 data points (12.65%) set to NA
NEE: 5274 data points (30.1%) set to NA
-------------------------------------------------------------------
Data filtering:
13968 data points (79.73%) excluded by growing season filter
1558 additional data points (8.89%) excluded by precipitation filter (3405
 data points = 19.43 % in total)
15526 data points (88.62%) excluded in total
1994 valid data points (11.38%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 680 data points (3.88%) set to NA
H: 2186 data points (12.48%) set to NA
LE: 2216 data points (12.65%) set to NA
NEE: 5274 data points (30.1%) set to NA
-------------------------------------------------------------------
Data filtering:
13968 data points (79.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13968 data points (79.73%) excluded in total
3552 valid data points (20.27%) remaining.

New sEddyProc class for site 'US-ICh'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 135.29.

Regression of reference temperature R_ref for 7 periods.

[227/329] Processing: US-ICs

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-ICs | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 1035 data points (5.91%) set to NA
H: 960 data points (5.48%) set to NA
LE: 959 data points (5.47%) set to NA
NEE: 2249 data points (12.84%) set to NA
-------------------------------------------------------------------
Data filtering:
13488 data points (76.99%) excluded by growing season filter
1879 additional data points (10.72%) excluded by precipitation filter (3235
 data points = 18.46 % in total)
15367 data points (87.71%) excluded in total
2153 valid data points (12.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1035 data points (5.91%) set to NA
H: 960 data points (5.48%) set to NA
LE: 959 data points (5.47%) set to NA
NEE: 2249 data points (12.84%) set to NA
-------------------------------------------------------------------
Data filtering:
13488 data points (76.99%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13488 data points (76.99%) excluded in total
4032 valid data points (23.01%) remaining.

New sEddyProc class for site 'US-ICs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICs-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 485 data points (2.77%) set to NA
H: 902 data points (5.15%) set to NA
LE: 942 data points (5.38%) set to NA
NEE: 1830 data points (10.45%) set to NA
-------------------------------------------------------------------
Data filtering:
13488 data points (76.99%) excluded by growing season filter
2160 additional data points (12.33%) excluded by precipitation filter (3784
 data points = 21.6 % in total)
15648 data points (89.32%) excluded in total
1872 valid data points (10.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 485 data points (2.77%) set to NA
H: 902 data points (5.15%) set to NA
LE: 942 data points (5.38%) set to NA
NEE: 1830 data points (10.45%) set to NA
-------------------------------------------------------------------
Data filtering:
13488 data points (76.99%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13488 data points (76.99%) excluded in total
4032 valid data points (23.01%) remaining.

New sEddyProc class for site 'US-ICs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICs-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 13 data points (0.07%) set to NA
H: 552 data points (3.15%) set to NA
LE: 523 data points (2.99%) set to NA
NEE: 1617 data points (9.23%) set to NA
-------------------------------------------------------------------
Data filtering:
13824 data points (78.9%) excluded by growing season filter
2225 additional data points (12.7%) excluded by precipitation filter (4096
 data points = 23.38 % in total)
16049 data points (91.6%) excluded in total
1471 valid data points (8.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 13 data points (0.07%) set to NA
H: 552 data points (3.15%) set to NA
LE: 523 data points (2.99%) set to NA
NEE: 1617 data points (9.23%) set to NA
-------------------------------------------------------------------
Data filtering:
13824 data points (78.9%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13824 data points (78.9%) excluded in total
3696 valid data points (21.1%) remaining.

New sEddyProc class for site 'US-ICs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICs-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 108 data points (0.61%) set to NA
H: 2697 data points (15.35%) set to NA
LE: 2725 data points (15.51%) set to NA
NEE: 4498 data points (25.6%) set to NA
-------------------------------------------------------------------
Data filtering:
14160 data points (80.6%) excluded by growing season filter
1497 additional data points (8.52%) excluded by precipitation filter (3414
 data points = 19.43 % in total)
15657 data points (89.12%) excluded in total
1911 valid data points (10.88%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 108 data points (0.61%) set to NA
H: 2697 data points (15.35%) set to NA
LE: 2725 data points (15.51%) set to NA
NEE: 4498 data points (25.6%) set to NA
-------------------------------------------------------------------
Data filtering:
14160 data points (80.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14160 data points (80.6%) excluded in total
3408 valid data points (19.4%) remaining.

New sEddyProc class for site 'US-ICs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICs-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 137 data points (0.78%) set to NA
H: 3718 data points (21.22%) set to NA
LE: 4227 data points (24.13%) set to NA
NEE: 5334 data points (30.45%) set to NA
-------------------------------------------------------------------
Data filtering:
14448 data points (82.47%) excluded by growing season filter
1794 additional data points (10.24%) excluded by precipitation filter (3895
 data points = 22.23 % in total)
16242 data points (92.71%) excluded in total
1278 valid data points (7.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 137 data points (0.78%) set to NA
H: 3718 data points (21.22%) set to NA
LE: 4227 data points (24.13%) set to NA
NEE: 5334 data points (30.45%) set to NA
-------------------------------------------------------------------
Data filtering:
14448 data points (82.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14448 data points (82.47%) excluded in total
3072 valid data points (17.53%) remaining.

New sEddyProc class for site 'US-ICs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICs-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2231 data points (12.73%) set to NA
LE: 2230 data points (12.73%) set to NA
NEE: 3769 data points (21.51%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.47%) excluded by growing season filter
2486 additional data points (14.19%) excluded by precipitation filter (2700
 data points = 15.41 % in total)
13430 data points (76.66%) excluded in total
4090 valid data points (23.34%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2231 data points (12.73%) set to NA
LE: 2230 data points (12.73%) set to NA
NEE: 3769 data points (21.51%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10944 data points (62.47%) excluded in total
6576 valid data points (37.53%) remaining.

New sEddyProc class for site 'US-ICs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICs-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4 data points (0.02%) set to NA
H: 2036 data points (11.62%) set to NA
LE: 2041 data points (11.65%) set to NA
NEE: 4259 data points (24.31%) set to NA
-------------------------------------------------------------------
Data filtering:
12912 data points (73.7%) excluded by growing season filter
2975 additional data points (16.98%) excluded by precipitation filter (3531
 data points = 20.15 % in total)
15887 data points (90.68%) excluded in total
1633 valid data points (9.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4 data points (0.02%) set to NA
H: 2036 data points (11.62%) set to NA
LE: 2041 data points (11.65%) set to NA
NEE: 4259 data points (24.31%) set to NA
-------------------------------------------------------------------
Data filtering:
12912 data points (73.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12912 data points (73.7%) excluded in total
4608 valid data points (26.3%) remaining.

New sEddyProc class for site 'US-ICs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICs-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1056 data points (6.01%) set to NA
LE: 2121 data points (12.07%) set to NA
NEE: 4070 data points (23.17%) set to NA
-------------------------------------------------------------------
Data filtering:
12864 data points (73.22%) excluded by growing season filter
2155 additional data points (12.27%) excluded by precipitation filter (2978
 data points = 16.95 % in total)
15019 data points (85.49%) excluded in total
2549 valid data points (14.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1056 data points (6.01%) set to NA
LE: 2121 data points (12.07%) set to NA
NEE: 4070 data points (23.17%) set to NA
-------------------------------------------------------------------
Data filtering:
12864 data points (73.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12864 data points (73.22%) excluded in total
4704 valid data points (26.78%) remaining.

New sEddyProc class for site 'US-ICs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICs-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 193 data points (1.1%) set to NA
H: 2410 data points (13.76%) set to NA
LE: 2344 data points (13.38%) set to NA
NEE: 4695 data points (26.8%) set to NA
-------------------------------------------------------------------
Data filtering:
14064 data points (80.27%) excluded by growing season filter
1653 additional data points (9.43%) excluded by precipitation filter (4081
 data points = 23.29 % in total)
15717 data points (89.71%) excluded in total
1803 valid data points (10.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 193 data points (1.1%) set to NA
H: 2410 data points (13.76%) set to NA
LE: 2344 data points (13.38%) set to NA
NEE: 4695 data points (26.8%) set to NA
-------------------------------------------------------------------
Data filtering:
14064 data points (80.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14064 data points (80.27%) excluded in total
3456 valid data points (19.73%) remaining.

New sEddyProc class for site 'US-ICs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICs-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[228/329] Processing: US-ICt

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-ICt | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 186 data points (1.06%) set to NA
H: 1089 data points (6.22%) set to NA
LE: 1095 data points (6.25%) set to NA
NEE: 2685 data points (15.33%) set to NA
-------------------------------------------------------------------
Data filtering:
14064 data points (80.27%) excluded by growing season filter
1564 additional data points (8.93%) excluded by precipitation filter (2795
 data points = 15.95 % in total)
15628 data points (89.2%) excluded in total
1892 valid data points (10.8%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 186 data points (1.06%) set to NA
H: 1089 data points (6.22%) set to NA
LE: 1095 data points (6.25%) set to NA
NEE: 2685 data points (15.33%) set to NA
-------------------------------------------------------------------
Data filtering:
14064 data points (80.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14064 data points (80.27%) excluded in total
3456 valid data points (19.73%) remaining.

New sEddyProc class for site 'US-ICt'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICt-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 5643 data points (32.21%) set to NA
LE: 667 data points (3.81%) set to NA
NEE: 2449 data points (13.98%) set to NA
-------------------------------------------------------------------
Data filtering:
13968 data points (79.73%) excluded by growing season filter
2356 additional data points (13.45%) excluded by precipitation filter (4065
 data points = 23.2 % in total)
16324 data points (93.17%) excluded in total
1196 valid data points (6.83%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5643 data points (32.21%) set to NA
LE: 667 data points (3.81%) set to NA
NEE: 2449 data points (13.98%) set to NA
-------------------------------------------------------------------
Data filtering:
13968 data points (79.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13968 data points (79.73%) excluded in total
3552 valid data points (20.27%) remaining.

New sEddyProc class for site 'US-ICt'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICt-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 181 data points (1.03%) set to NA
H: 726 data points (4.14%) set to NA
LE: 731 data points (4.17%) set to NA
NEE: 2776 data points (15.84%) set to NA
-------------------------------------------------------------------
Data filtering:
13632 data points (77.81%) excluded by growing season filter
2312 additional data points (13.2%) excluded by precipitation filter (3957
 data points = 22.59 % in total)
15944 data points (91%) excluded in total
1576 valid data points (9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 181 data points (1.03%) set to NA
H: 726 data points (4.14%) set to NA
LE: 731 data points (4.17%) set to NA
NEE: 2776 data points (15.84%) set to NA
-------------------------------------------------------------------
Data filtering:
13632 data points (77.81%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13632 data points (77.81%) excluded in total
3888 valid data points (22.19%) remaining.

New sEddyProc class for site 'US-ICt'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICt-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 3875 data points (22.06%) set to NA
LE: 3887 data points (22.13%) set to NA
NEE: 4845 data points (27.58%) set to NA
-------------------------------------------------------------------
Data filtering:
13728 data points (78.14%) excluded by growing season filter
1679 additional data points (9.56%) excluded by precipitation filter (3442
 data points = 19.59 % in total)
15407 data points (87.7%) excluded in total
2161 valid data points (12.3%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 3875 data points (22.06%) set to NA
LE: 3887 data points (22.13%) set to NA
NEE: 4845 data points (27.58%) set to NA
-------------------------------------------------------------------
Data filtering:
13728 data points (78.14%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13728 data points (78.14%) excluded in total
3840 valid data points (21.86%) remaining.

New sEddyProc class for site 'US-ICt'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICt-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 9 data points (0.05%) set to NA
H: 1629 data points (9.3%) set to NA
LE: 1617 data points (9.23%) set to NA
NEE: 3172 data points (18.11%) set to NA
-------------------------------------------------------------------
Data filtering:
14448 data points (82.47%) excluded by growing season filter
1586 additional data points (9.05%) excluded by precipitation filter (3783
 data points = 21.59 % in total)
16034 data points (91.52%) excluded in total
1486 valid data points (8.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9 data points (0.05%) set to NA
H: 1629 data points (9.3%) set to NA
LE: 1617 data points (9.23%) set to NA
NEE: 3172 data points (18.11%) set to NA
-------------------------------------------------------------------
Data filtering:
14448 data points (82.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14448 data points (82.47%) excluded in total
3072 valid data points (17.53%) remaining.

New sEddyProc class for site 'US-ICt'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICt-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 419 data points (2.39%) set to NA
H: 6612 data points (37.74%) set to NA
LE: 6565 data points (37.47%) set to NA
NEE: 7162 data points (40.88%) set to NA
-------------------------------------------------------------------
Data filtering:
12432 data points (70.96%) excluded by growing season filter
2276 additional data points (12.99%) excluded by precipitation filter (2835
 data points = 16.18 % in total)
14708 data points (83.95%) excluded in total
2812 valid data points (16.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 419 data points (2.39%) set to NA
H: 6612 data points (37.74%) set to NA
LE: 6565 data points (37.47%) set to NA
NEE: 7162 data points (40.88%) set to NA
-------------------------------------------------------------------
Data filtering:
12432 data points (70.96%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12432 data points (70.96%) excluded in total
5088 valid data points (29.04%) remaining.

New sEddyProc class for site 'US-ICt'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICt-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2942 data points (16.79%) set to NA
H: 3976 data points (22.69%) set to NA
LE: 3994 data points (22.8%) set to NA
NEE: 7239 data points (41.32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 45”

-------------------------------------------------------------------
Data filtering:
12576 data points (71.78%) excluded by growing season filter
2896 additional data points (16.53%) excluded by precipitation filter (3807
 data points = 21.73 % in total)
15472 data points (88.31%) excluded in total
2048 valid data points (11.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2942 data points (16.79%) set to NA
H: 3976 data points (22.69%) set to NA
LE: 3994 data points (22.8%) set to NA
NEE: 7239 data points (41.32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 45”

-------------------------------------------------------------------
Data filtering:
12576 data points (71.78%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12576 data points (71.78%) excluded in total
4944 valid data points (28.22%) remaining.

New sEddyProc class for site 'US-ICt'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICt-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 3947 data points (22.47%) set to NA
LE: 3927 data points (22.35%) set to NA
NEE: 6280 data points (35.75%) set to NA
-------------------------------------------------------------------
Data filtering:
12624 data points (71.86%) excluded by growing season filter
2497 additional data points (14.21%) excluded by precipitation filter (2897
 data points = 16.49 % in total)
15121 data points (86.07%) excluded in total
2447 valid data points (13.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 3947 data points (22.47%) set to NA
LE: 3927 data points (22.35%) set to NA
NEE: 6280 data points (35.75%) set to NA
-------------------------------------------------------------------
Data filtering:
12624 data points (71.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12624 data points (71.86%) excluded in total
4944 valid data points (28.14%) remaining.

New sEddyProc class for site 'US-ICt'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICt-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 13 data points (0.07%) set to NA
H: 2595 data points (14.81%) set to NA
LE: 2608 data points (14.89%) set to NA
NEE: 7888 data points (45.02%) set to NA
-------------------------------------------------------------------
Data filtering:
13968 data points (79.73%) excluded by growing season filter
1596 additional data points (9.11%) excluded by precipitation filter (3439
 data points = 19.63 % in total)
15564 data points (88.84%) excluded in total
1956 valid data points (11.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 13 data points (0.07%) set to NA
H: 2595 data points (14.81%) set to NA
LE: 2608 data points (14.89%) set to NA
NEE: 7888 data points (45.02%) set to NA
-------------------------------------------------------------------
Data filtering:
13968 data points (79.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13968 data points (79.73%) excluded in total
3552 valid data points (20.27%) remaining.

New sEddyProc class for site 'US-ICt'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-ICt-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[229/329] Processing: US-Jo1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Jo1 | Years: 2017, 2018, 2019, 2020, 2021, 2022
Quality control:
TA: 10667 data points (60.88%) set to NA
H: 7976 data points (45.53%) set to NA
LE: 8029 data points (45.83%) set to NA
NEE: 9144 data points (52.19%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 144”

-------------------------------------------------------------------
Data filtering:
7200 data points (41.1%) excluded by growing season filter
3088 additional data points (17.63%) excluded by precipitation filter (3969
 data points = 22.65 % in total)
10288 data points (58.72%) excluded in total
7232 valid data points (41.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10667 data points (60.88%) set to NA
H: 7976 data points (45.53%) set to NA
LE: 8029 data points (45.83%) set to NA
NEE: 9144 data points (52.19%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 144”

-------------------------------------------------------------------
Data filtering:
7200 data points (41.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7200 data points (41.1%) excluded in total
10320 valid data points (58.9%) remaining.

New sEddyProc class for site 'US-Jo1'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 292.65.

Regression of reference temperature R_ref for 27 periods.

Quality control:
TA: 5956 data points (34%) set to NA
H: 1677 data points (9.57%) set to NA
LE: 1802 data points (10.29%) set to NA
NEE: 3090 data points (17.64%) set to NA
-------------------------------------------------------------------
Data filtering:
2496 data points (14.25%) excluded by growing season filter
2381 additional data points (13.59%) excluded by precipitation filter (3188
 data points = 18.2 % in total)
4877 data points (27.84%) excluded in total
12643 valid data points (72.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5956 data points (34%) set to NA
H: 1677 data points (9.57%) set to NA
LE: 1802 data points (10.29%) set to NA
NEE: 3090 data points (17.64%) set to NA
-------------------------------------------------------------------
Data filtering:
2496 data points (14.25%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2496 data points (14.25%) excluded in total
15024 valid data points (85.75%) remaining.

New sEddyProc class for site 'US-Jo1'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 144.84.

Regression of reference temperature R_ref for 33 periods.

Quality control:
TA: 406 data points (2.32%) set to NA
H: 473 data points (2.7%) set to NA
LE: 531 data points (3.03%) set to NA
NEE: 861 data points (4.91%) set to NA
-------------------------------------------------------------------
Data filtering:
4608 data points (26.3%) excluded by growing season filter
2104 additional data points (12.01%) excluded by precipitation filter (2729
 data points = 15.58 % in total)
6712 data points (38.31%) excluded in total
10808 valid data points (61.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 406 data points (2.32%) set to NA
H: 473 data points (2.7%) set to NA
LE: 531 data points (3.03%) set to NA
NEE: 861 data points (4.91%) set to NA
-------------------------------------------------------------------
Data filtering:
4608 data points (26.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4608 data points (26.3%) excluded in total
12912 valid data points (73.7%) remaining.

New sEddyProc class for site 'US-Jo1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 8 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Jo1-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 25 data points (0.14%) set to NA
LE: 73 data points (0.42%) set to NA
NEE: 516 data points (2.94%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.2%) excluded by growing season filter
684 additional data points (3.89%) excluded by precipitation filter (1733
 data points = 9.86 % in total)
10908 data points (62.09%) excluded in total
6660 valid data points (37.91%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 25 data points (0.14%) set to NA
LE: 73 data points (0.42%) set to NA
NEE: 516 data points (2.94%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.2%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10224 data points (58.2%) excluded in total
7344 valid data points (41.8%) remaining.

New sEddyProc class for site 'US-Jo1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Jo1-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 387 data points (2.21%) set to NA
H: 4819 data points (27.51%) set to NA
LE: 4899 data points (27.96%) set to NA
NEE: 5299 data points (30.25%) set to NA
-------------------------------------------------------------------
Data filtering:
13248 data points (75.62%) excluded by growing season filter
802 additional data points (4.58%) excluded by precipitation filter (1988
 data points = 11.35 % in total)
14050 data points (80.19%) excluded in total
3470 valid data points (19.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 387 data points (2.21%) set to NA
H: 4819 data points (27.51%) set to NA
LE: 4899 data points (27.96%) set to NA
NEE: 5299 data points (30.25%) set to NA
-------------------------------------------------------------------
Data filtering:
13248 data points (75.62%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13248 data points (75.62%) excluded in total
4272 valid data points (24.38%) remaining.

New sEddyProc class for site 'US-Jo1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Jo1-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4404 data points (25.14%) set to NA
H: 4525 data points (25.83%) set to NA
LE: 4571 data points (26.09%) set to NA
NEE: 4679 data points (26.71%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 82”

-------------------------------------------------------------------
Data filtering:
6336 data points (36.16%) excluded by growing season filter
1898 additional data points (10.83%) excluded by precipitation filter (2907
 data points = 16.59 % in total)
8234 data points (47%) excluded in total
9286 valid data points (53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4404 data points (25.14%) set to NA
H: 4525 data points (25.83%) set to NA
LE: 4571 data points (26.09%) set to NA
NEE: 4679 data points (26.71%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 82”

-------------------------------------------------------------------
Data filtering:
6336 data points (36.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6336 data points (36.16%) excluded in total
11184 valid data points (63.84%) remaining.

New sEddyProc class for site 'US-Jo1'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 131.88.

Regression of reference temperature R_ref for 6 periods.

[230/329] Processing: US-KPL

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-KPL | Years: 2021, 2022, 2023, 2024
Quality control:
TA: 3735 data points (21.32%) set to NA
H: 5204 data points (29.7%) set to NA
LE: 5205 data points (29.71%) set to NA
NEE: 5328 data points (30.41%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 68”

-------------------------------------------------------------------
Data filtering:
12480 data points (71.23%) excluded by growing season filter
2206 additional data points (12.59%) excluded by precipitation filter (6654
 data points = 37.98 % in total)
14686 data points (83.82%) excluded in total
2834 valid data points (16.18%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3735 data points (21.32%) set to NA
H: 5204 data points (29.7%) set to NA
LE: 5205 data points (29.71%) set to NA
NEE: 5328 data points (30.41%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 68”

-------------------------------------------------------------------
Data filtering:
12480 data points (71.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12480 data points (71.23%) excluded in total
5040 valid data points (28.77%) remaining.

New sEddyProc class for site 'US-KPL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-KPL-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1989 data points (11.35%) set to NA
LE: 1988 data points (11.35%) set to NA
NEE: 2060 data points (11.76%) set to NA
-------------------------------------------------------------------
Data filtering:
12000 data points (68.49%) excluded by growing season filter
2826 additional data points (16.13%) excluded by precipitation filter (7434
 data points = 42.43 % in total)
14826 data points (84.62%) excluded in total
2694 valid data points (15.38%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1989 data points (11.35%) set to NA
LE: 1988 data points (11.35%) set to NA
NEE: 2060 data points (11.76%) set to NA
-------------------------------------------------------------------
Data filtering:
12000 data points (68.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12000 data points (68.49%) excluded in total
5520 valid data points (31.51%) remaining.

New sEddyProc class for site 'US-KPL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-KPL-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 377 data points (2.15%) set to NA
LE: 370 data points (2.11%) set to NA
NEE: 682 data points (3.89%) set to NA
-------------------------------------------------------------------
Data filtering:
12240 data points (69.86%) excluded by growing season filter
2397 additional data points (13.68%) excluded by precipitation filter (6899
 data points = 39.38 % in total)
14637 data points (83.54%) excluded in total
2883 valid data points (16.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 377 data points (2.15%) set to NA
LE: 370 data points (2.11%) set to NA
NEE: 682 data points (3.89%) set to NA
-------------------------------------------------------------------
Data filtering:
12240 data points (69.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12240 data points (69.86%) excluded in total
5280 valid data points (30.14%) remaining.

New sEddyProc class for site 'US-KPL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-KPL-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1068 data points (6.08%) set to NA
LE: 1058 data points (6.02%) set to NA
NEE: 1099 data points (6.26%) set to NA
-------------------------------------------------------------------
Data filtering:
12624 data points (71.86%) excluded by growing season filter
1969 additional data points (11.21%) excluded by precipitation filter (6430
 data points = 36.6 % in total)
14593 data points (83.07%) excluded in total
2975 valid data points (16.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1068 data points (6.08%) set to NA
LE: 1058 data points (6.02%) set to NA
NEE: 1099 data points (6.26%) set to NA
-------------------------------------------------------------------
Data filtering:
12624 data points (71.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12624 data points (71.86%) excluded in total
4944 valid data points (28.14%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
New sEddyProc class for site 'US-KPL'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-KPL-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[231/329] Processing: US-KS3

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-KS3 | Years: 2018
Quality control:
TA: 4790 data points (27.34%) set to NA
H: 4801 data points (27.4%) set to NA
LE: 4800 data points (27.4%) set to NA
NEE: 4847 data points (27.67%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 91”

-------------------------------------------------------------------
Data filtering:
1440 data points (8.22%) excluded by growing season filter
2151 additional data points (12.28%) excluded by precipitation filter (2151
 data points = 12.28 % in total)
3591 data points (20.5%) excluded in total
13929 valid data points (79.5%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4790 data points (27.34%) set to NA
H: 4801 data points (27.4%) set to NA
LE: 4800 data points (27.4%) set to NA
NEE: 4847 data points (27.67%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 91”

-------------------------------------------------------------------
Data filtering:
1440 data points (8.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1440 data points (8.22%) excluded in total
16080 valid data points (91.78%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -77, -50 ...”
New sEddyProc class for site 'US-KS3'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -77, -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-KS3-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[232/329] Processing: US-LA2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-LA2 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023
Quality control:
TA: 17520 data points (100%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9701 additional data points (55.37%) excluded by precipitation filter (9701
 data points = 55.37 % in total)
9701 data points (55.37%) excluded in total
7819 valid data points (44.63%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-LA2-2017”

Quality control:
TA: 17520 data points (100%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
11025 additional data points (62.93%) excluded by precipitation filter (11025
 data points = 62.93 % in total)
11025 data points (62.93%) excluded in total
6495 valid data points (37.07%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-LA2-2018”

Quality control:
TA: 17520 data points (100%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9496 additional data points (54.2%) excluded by precipitation filter (9496
 data points = 54.2 % in total)
9496 data points (54.2%) excluded in total
8024 valid data points (45.8%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-LA2-2019”

Quality control:
TA: 17568 data points (100%) set to NA
H: 17568 data points (100%) set to NA
LE: 17568 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
9677 additional data points (55.08%) excluded by precipitation filter (9677
 data points = 55.08 % in total)
9677 data points (55.08%) excluded in total
7891 valid data points (44.92%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-LA2-2020”

Quality control:
TA: 10212 data points (58.29%) set to NA
H: 8925 data points (50.94%) set to NA
LE: 8925 data points (50.94%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7612 additional data points (43.45%) excluded by precipitation filter (7612
 data points = 43.45 % in total)
7612 data points (43.45%) excluded in total
9908 valid data points (56.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10212 data points (58.29%) set to NA
H: 8925 data points (50.94%) set to NA
LE: 8925 data points (50.94%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-LA2'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-LA2-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 10824 data points (61.78%) set to NA
H: 4126 data points (23.55%) set to NA
LE: 4169 data points (23.8%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6387 additional data points (36.46%) excluded by precipitation filter (6387
 data points = 36.46 % in total)
6387 data points (36.46%) excluded in total
11133 valid data points (63.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10824 data points (61.78%) set to NA
H: 4126 data points (23.55%) set to NA
LE: 4169 data points (23.8%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-LA2'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-LA2-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 11387 data points (64.99%) set to NA
H: 11319 data points (64.61%) set to NA
LE: 11316 data points (64.59%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6748 additional data points (38.52%) excluded by precipitation filter (6748
 data points = 38.52 % in total)
6748 data points (38.52%) excluded in total
10772 valid data points (61.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11387 data points (64.99%) set to NA
H: 11319 data points (64.61%) set to NA
LE: 11316 data points (64.59%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-LA2'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-LA2-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[233/329] Processing: US-LA3

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-LA3 | Years: 2019, 2020, 2021, 2022, 2023
Quality control:
TA: 16847 data points (96.16%) set to NA
H: 16849 data points (96.17%) set to NA
LE: 16849 data points (96.17%) set to NA
NEE: 16850 data points (96.18%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7487 additional data points (42.73%) excluded by precipitation filter (7487
 data points = 42.73 % in total)
7487 data points (42.73%) excluded in total
10033 valid data points (57.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 16847 data points (96.16%) set to NA
H: 16849 data points (96.17%) set to NA
LE: 16849 data points (96.17%) set to NA
NEE: 16850 data points (96.18%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-LA3'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 116.3.

Regression of reference temperature R_ref for 6 periods.

Quality control:
TA: 10509 data points (59.82%) set to NA
H: 9433 data points (53.69%) set to NA
LE: 9466 data points (53.88%) set to NA
NEE: 9778 data points (55.66%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6641 additional data points (37.8%) excluded by precipitation filter (6641
 data points = 37.8 % in total)
6641 data points (37.8%) excluded in total
10927 valid data points (62.2%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10509 data points (59.82%) set to NA
H: 9433 data points (53.69%) set to NA
LE: 9466 data points (53.88%) set to NA
NEE: 9778 data points (55.66%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
New sEddyProc class for site 'US-LA3'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 159.85.

Regression of reference temperature R_ref for 24 periods.

Quality control:
TA: 12790 data points (73%) set to NA
H: 10420 data points (59.47%) set to NA
LE: 10432 data points (59.54%) set to NA
NEE: 10990 data points (62.73%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7645 additional data points (43.64%) excluded by precipitation filter (7645
 data points = 43.64 % in total)
7645 data points (43.64%) excluded in total
9875 valid data points (56.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12790 data points (73%) set to NA
H: 10420 data points (59.47%) set to NA
LE: 10432 data points (59.54%) set to NA
NEE: 10990 data points (62.73%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
New sEddyProc class for site 'US-LA3'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 115.17.

Regression of reference temperature R_ref for 28 periods.

Quality control:
TA: 7367 data points (42.05%) set to NA
H: 4000 data points (22.83%) set to NA
LE: 4014 data points (22.91%) set to NA
NEE: 5085 data points (29.02%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7628 additional data points (43.54%) excluded by precipitation filter (7628
 data points = 43.54 % in total)
7628 data points (43.54%) excluded in total
9892 valid data points (56.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7367 data points (42.05%) set to NA
H: 4000 data points (22.83%) set to NA
LE: 4014 data points (22.91%) set to NA
NEE: 5085 data points (29.02%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
New sEddyProc class for site 'US-LA3'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -50 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 116.68.

Regression of reference temperature R_ref for 50 periods.

Quality control:
TA: 1516 data points (8.65%) set to NA
H: 1194 data points (6.82%) set to NA
LE: 1207 data points (6.89%) set to NA
NEE: 1472 data points (8.4%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3223 additional data points (18.4%) excluded by precipitation filter (3223
 data points = 18.4 % in total)
3223 data points (18.4%) excluded in total
14297 valid data points (81.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1516 data points (8.65%) set to NA
H: 1194 data points (6.82%) set to NA
LE: 1207 data points (6.89%) set to NA
NEE: 1472 data points (8.4%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-LA3'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 11 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-LA3-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[234/329] Processing: US-Los

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Los | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 270 data points (1.54%) set to NA
H: 286 data points (1.63%) set to NA
LE: 394 data points (2.25%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7029 additional data points (40.12%) excluded by precipitation filter (7029
 data points = 40.12 % in total)
7029 data points (40.12%) excluded in total
10491 valid data points (59.88%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 270 data points (1.54%) set to NA
H: 286 data points (1.63%) set to NA
LE: 394 data points (2.25%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Los'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Los-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 528 data points (3.01%) set to NA
H: 575 data points (3.28%) set to NA
LE: 587 data points (3.35%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5749 additional data points (32.81%) excluded by precipitation filter (5749
 data points = 32.81 % in total)
5749 data points (32.81%) excluded in total
11771 valid data points (67.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 528 data points (3.01%) set to NA
H: 575 data points (3.28%) set to NA
LE: 587 data points (3.35%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Los'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Los-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 654 data points (3.73%) set to NA
H: 701 data points (4%) set to NA
LE: 1619 data points (9.24%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6743 additional data points (38.49%) excluded by precipitation filter (6743
 data points = 38.49 % in total)
6743 data points (38.49%) excluded in total
10777 valid data points (61.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 654 data points (3.73%) set to NA
H: 701 data points (4%) set to NA
LE: 1619 data points (9.24%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Los'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Los-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 499 data points (2.84%) set to NA
H: 520 data points (2.96%) set to NA
LE: 522 data points (2.97%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5937 additional data points (33.79%) excluded by precipitation filter (5937
 data points = 33.79 % in total)
5937 data points (33.79%) excluded in total
11631 valid data points (66.21%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 499 data points (2.84%) set to NA
H: 520 data points (2.96%) set to NA
LE: 522 data points (2.97%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-Los'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Los-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 261 data points (1.49%) set to NA
H: 279 data points (1.59%) set to NA
LE: 1790 data points (10.22%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5714 additional data points (32.61%) excluded by precipitation filter (5714
 data points = 32.61 % in total)
5714 data points (32.61%) excluded in total
11806 valid data points (67.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 261 data points (1.49%) set to NA
H: 279 data points (1.59%) set to NA
LE: 1790 data points (10.22%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Los'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Los-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1314 data points (7.5%) set to NA
H: 1421 data points (8.11%) set to NA
LE: 4991 data points (28.49%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6361 additional data points (36.31%) excluded by precipitation filter (6361
 data points = 36.31 % in total)
6361 data points (36.31%) excluded in total
11159 valid data points (63.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1314 data points (7.5%) set to NA
H: 1421 data points (8.11%) set to NA
LE: 4991 data points (28.49%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Los'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Los-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1863 data points (10.63%) set to NA
H: 1859 data points (10.61%) set to NA
LE: 1928 data points (11%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6420 additional data points (36.64%) excluded by precipitation filter (6420
 data points = 36.64 % in total)
6420 data points (36.64%) excluded in total
11100 valid data points (63.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1863 data points (10.63%) set to NA
H: 1859 data points (10.61%) set to NA
LE: 1928 data points (11%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Los'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Los-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1144 data points (6.51%) set to NA
H: 1150 data points (6.55%) set to NA
LE: 1244 data points (7.08%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6271 additional data points (35.7%) excluded by precipitation filter (6271
 data points = 35.7 % in total)
6271 data points (35.7%) excluded in total
11297 valid data points (64.3%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1144 data points (6.51%) set to NA
H: 1150 data points (6.55%) set to NA
LE: 1244 data points (7.08%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-Los'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Los-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2317 data points (13.22%) set to NA
H: 2332 data points (13.31%) set to NA
LE: 2727 data points (15.57%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6351 additional data points (36.25%) excluded by precipitation filter (6351
 data points = 36.25 % in total)
6351 data points (36.25%) excluded in total
11169 valid data points (63.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2317 data points (13.22%) set to NA
H: 2332 data points (13.31%) set to NA
LE: 2727 data points (15.57%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Los'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Los-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[235/329] Processing: US-MBP

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-MBP | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 552 data points (3.15%) set to NA
LE: 656 data points (3.74%) set to NA
NEE: 960 data points (5.48%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
4824 additional data points (27.53%) excluded by precipitation filter (10252
 data points = 58.52 % in total)
15480 data points (88.36%) excluded in total
2040 valid data points (11.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 552 data points (3.15%) set to NA
LE: 656 data points (3.74%) set to NA
NEE: 960 data points (5.48%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10656 data points (60.82%) excluded in total
6864 valid data points (39.18%) remaining.

New sEddyProc class for site 'US-MBP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MBP-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 572 data points (3.26%) set to NA
LE: 771 data points (4.4%) set to NA
NEE: 1215 data points (6.93%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.27%) excluded by growing season filter
4480 additional data points (25.57%) excluded by precipitation filter (8844
 data points = 50.48 % in total)
15040 data points (85.84%) excluded in total
2480 valid data points (14.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 572 data points (3.26%) set to NA
LE: 771 data points (4.4%) set to NA
NEE: 1215 data points (6.93%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10560 data points (60.27%) excluded in total
6960 valid data points (39.73%) remaining.

New sEddyProc class for site 'US-MBP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MBP-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 797 data points (4.55%) set to NA
LE: 939 data points (5.36%) set to NA
NEE: 1371 data points (7.83%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.89%) excluded by growing season filter
5298 additional data points (30.24%) excluded by precipitation filter (10004
 data points = 57.1 % in total)
15090 data points (86.13%) excluded in total
2430 valid data points (13.87%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 797 data points (4.55%) set to NA
LE: 939 data points (5.36%) set to NA
NEE: 1371 data points (7.83%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9792 data points (55.89%) excluded in total
7728 valid data points (44.11%) remaining.

New sEddyProc class for site 'US-MBP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MBP-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1493 data points (8.5%) set to NA
LE: 1717 data points (9.77%) set to NA
NEE: 2207 data points (12.56%) set to NA
-------------------------------------------------------------------
Data filtering:
10416 data points (59.29%) excluded by growing season filter
3866 additional data points (22.01%) excluded by precipitation filter (8412
 data points = 47.88 % in total)
14282 data points (81.3%) excluded in total
3286 valid data points (18.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1493 data points (8.5%) set to NA
LE: 1717 data points (9.77%) set to NA
NEE: 2207 data points (12.56%) set to NA
-------------------------------------------------------------------
Data filtering:
10416 data points (59.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10416 data points (59.29%) excluded in total
7152 valid data points (40.71%) remaining.

New sEddyProc class for site 'US-MBP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MBP-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 646 data points (3.69%) set to NA
LE: 791 data points (4.51%) set to NA
NEE: 1245 data points (7.11%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.15%) excluded by growing season filter
4250 additional data points (24.26%) excluded by precipitation filter (8448
 data points = 48.22 % in total)
13562 data points (77.41%) excluded in total
3958 valid data points (22.59%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 646 data points (3.69%) set to NA
LE: 791 data points (4.51%) set to NA
NEE: 1245 data points (7.11%) set to NA
-------------------------------------------------------------------
Data filtering:
9312 data points (53.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9312 data points (53.15%) excluded in total
8208 valid data points (46.85%) remaining.

New sEddyProc class for site 'US-MBP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MBP-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 480 data points (2.74%) set to NA
LE: 435 data points (2.48%) set to NA
NEE: 820 data points (4.68%) set to NA
-------------------------------------------------------------------
Data filtering:
10368 data points (59.18%) excluded by growing season filter
4230 additional data points (24.14%) excluded by precipitation filter (9940
 data points = 56.74 % in total)
14598 data points (83.32%) excluded in total
2922 valid data points (16.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 480 data points (2.74%) set to NA
LE: 435 data points (2.48%) set to NA
NEE: 820 data points (4.68%) set to NA
-------------------------------------------------------------------
Data filtering:
10368 data points (59.18%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10368 data points (59.18%) excluded in total
7152 valid data points (40.82%) remaining.

New sEddyProc class for site 'US-MBP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MBP-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 384 data points (2.19%) set to NA
LE: 333 data points (1.9%) set to NA
NEE: 828 data points (4.73%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
4426 additional data points (25.26%) excluded by precipitation filter (9772
 data points = 55.78 % in total)
15082 data points (86.08%) excluded in total
2438 valid data points (13.92%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 384 data points (2.19%) set to NA
LE: 333 data points (1.9%) set to NA
NEE: 828 data points (4.73%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10656 data points (60.82%) excluded in total
6864 valid data points (39.18%) remaining.

New sEddyProc class for site 'US-MBP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MBP-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3 data points (0.02%) set to NA
H: 407 data points (2.32%) set to NA
LE: 361 data points (2.05%) set to NA
NEE: 891 data points (5.07%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (59.84%) excluded by growing season filter
4500 additional data points (25.61%) excluded by precipitation filter (9268
 data points = 52.76 % in total)
15012 data points (85.45%) excluded in total
2556 valid data points (14.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3 data points (0.02%) set to NA
H: 407 data points (2.32%) set to NA
LE: 361 data points (2.05%) set to NA
NEE: 891 data points (5.07%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (59.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10512 data points (59.84%) excluded in total
7056 valid data points (40.16%) remaining.

New sEddyProc class for site 'US-MBP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MBP-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[236/329] Processing: US-MEF

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-MEF | Years: 2024, 2025
Quality control:
TA: 12 data points (0.07%) set to NA
H: 19 data points (0.11%) set to NA
LE: 22 data points (0.13%) set to NA
NEE: 633 data points (3.6%) set to NA
-------------------------------------------------------------------
Data filtering:
7584 data points (43.17%) excluded by growing season filter
2470 additional data points (14.06%) excluded by precipitation filter (4066
 data points = 23.14 % in total)
10054 data points (57.23%) excluded in total
7514 valid data points (42.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12 data points (0.07%) set to NA
H: 19 data points (0.11%) set to NA
LE: 22 data points (0.13%) set to NA
NEE: 633 data points (3.6%) set to NA
-------------------------------------------------------------------
Data filtering:
7584 data points (43.17%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7584 data points (43.17%) excluded in total
9984 valid data points (56.83%) remaining.

New sEddyProc class for site 'US-MEF'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MEF-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 513 data points (2.93%) set to NA
H: 577 data points (3.29%) set to NA
LE: 580 data points (3.31%) set to NA
NEE: 1148 data points (6.55%) set to NA
-------------------------------------------------------------------
Data filtering:
6192 data points (35.34%) excluded by growing season filter
3285 additional data points (18.75%) excluded by precipitation filter (4510
 data points = 25.74 % in total)
9477 data points (54.09%) excluded in total
8043 valid data points (45.91%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 513 data points (2.93%) set to NA
H: 577 data points (3.29%) set to NA
LE: 580 data points (3.31%) set to NA
NEE: 1148 data points (6.55%) set to NA
-------------------------------------------------------------------
Data filtering:
6192 data points (35.34%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6192 data points (35.34%) excluded in total
11328 valid data points (64.66%) remaining.

New sEddyProc class for site 'US-MEF'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 381.1.

Regression of reference temperature R_ref for 4 periods.

[237/329] Processing: US-MOz

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-MOz | Years: 2017, 2018, 2019, 2020, 2021
Quality control:
TA: 0 data points (0%) set to NA
H: 8 data points (0.05%) set to NA
LE: 20 data points (0.11%) set to NA
NEE: 532 data points (3.04%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.78%) excluded by growing season filter
2184 additional data points (12.47%) excluded by precipitation filter (3911
 data points = 22.32 % in total)
11256 data points (64.25%) excluded in total
6264 valid data points (35.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 8 data points (0.05%) set to NA
LE: 20 data points (0.11%) set to NA
NEE: 532 data points (3.04%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.78%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9072 data points (51.78%) excluded in total
8448 valid data points (48.22%) remaining.

New sEddyProc class for site 'US-MOz'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MOz-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 40 data points (0.23%) set to NA
LE: 46 data points (0.26%) set to NA
NEE: 332 data points (1.89%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.53%) excluded by growing season filter
2046 additional data points (11.68%) excluded by precipitation filter (4859
 data points = 27.73 % in total)
12126 data points (69.21%) excluded in total
5394 valid data points (30.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 40 data points (0.23%) set to NA
LE: 46 data points (0.26%) set to NA
NEE: 332 data points (1.89%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.53%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10080 data points (57.53%) excluded in total
7440 valid data points (42.47%) remaining.

New sEddyProc class for site 'US-MOz'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MOz-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 10 data points (0.06%) set to NA
H: 1264 data points (7.21%) set to NA
LE: 1289 data points (7.36%) set to NA
NEE: 1661 data points (9.48%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
2761 additional data points (15.76%) excluded by precipitation filter (5366
 data points = 30.63 % in total)
11977 data points (68.36%) excluded in total
5543 valid data points (31.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10 data points (0.06%) set to NA
H: 1264 data points (7.21%) set to NA
LE: 1289 data points (7.36%) set to NA
NEE: 1661 data points (9.48%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9216 data points (52.6%) excluded in total
8304 valid data points (47.4%) remaining.

New sEddyProc class for site 'US-MOz'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MOz-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 322 data points (1.83%) set to NA
LE: 411 data points (2.34%) set to NA
NEE: 932 data points (5.31%) set to NA
-------------------------------------------------------------------
Data filtering:
10032 data points (57.1%) excluded by growing season filter
2079 additional data points (11.83%) excluded by precipitation filter (4857
 data points = 27.65 % in total)
12111 data points (68.94%) excluded in total
5457 valid data points (31.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 322 data points (1.83%) set to NA
LE: 411 data points (2.34%) set to NA
NEE: 932 data points (5.31%) set to NA
-------------------------------------------------------------------
Data filtering:
10032 data points (57.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10032 data points (57.1%) excluded in total
7536 valid data points (42.9%) remaining.

New sEddyProc class for site 'US-MOz'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MOz-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1769 data points (10.1%) set to NA
H: 39 data points (0.22%) set to NA
LE: 54 data points (0.31%) set to NA
NEE: 405 data points (2.31%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
2834 additional data points (16.18%) excluded by precipitation filter (5035
 data points = 28.74 % in total)
12194 data points (69.6%) excluded in total
5326 valid data points (30.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1769 data points (10.1%) set to NA
H: 39 data points (0.22%) set to NA
LE: 54 data points (0.31%) set to NA
NEE: 405 data points (2.31%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9360 data points (53.42%) excluded in total
8160 valid data points (46.58%) remaining.

New sEddyProc class for site 'US-MOz'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MOz-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[238/329] Processing: US-MZA

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-MZA | Years: 2024, 2025
Quality control:
TA: 13804 data points (78.57%) set to NA
H: 13802 data points (78.56%) set to NA
LE: 13802 data points (78.56%) set to NA
NEE: 13868 data points (78.94%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7579 additional data points (43.14%) excluded by precipitation filter (7579
 data points = 43.14 % in total)
7579 data points (43.14%) excluded in total
9989 valid data points (56.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 13804 data points (78.57%) set to NA
H: 13802 data points (78.56%) set to NA
LE: 13802 data points (78.56%) set to NA
NEE: 13868 data points (78.94%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-MZA'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 10 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MZA-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 11274 data points (64.35%) set to NA
H: 11311 data points (64.56%) set to NA
LE: 11325 data points (64.64%) set to NA
NEE: 11386 data points (64.99%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7089 additional data points (40.46%) excluded by precipitation filter (7089
 data points = 40.46 % in total)
7089 data points (40.46%) excluded in total
10431 valid data points (59.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11274 data points (64.35%) set to NA
H: 11311 data points (64.56%) set to NA
LE: 11325 data points (64.64%) set to NA
NEE: 11386 data points (64.99%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-MZA'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 132.11.

Regression of reference temperature R_ref for 20 periods.

[239/329] Processing: US-Me6

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Me6 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 6 data points (0.03%) set to NA
H: 112 data points (0.64%) set to NA
LE: 112 data points (0.64%) set to NA
NEE: 497 data points (2.84%) set to NA
-------------------------------------------------------------------
Data filtering:
7584 data points (43.29%) excluded by growing season filter
2796 additional data points (15.96%) excluded by precipitation filter (5530
 data points = 31.56 % in total)
10380 data points (59.25%) excluded in total
7140 valid data points (40.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6 data points (0.03%) set to NA
H: 112 data points (0.64%) set to NA
LE: 112 data points (0.64%) set to NA
NEE: 497 data points (2.84%) set to NA
-------------------------------------------------------------------
Data filtering:
7584 data points (43.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7584 data points (43.29%) excluded in total
9936 valid data points (56.71%) remaining.

New sEddyProc class for site 'US-Me6'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Me6-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 438 data points (2.5%) set to NA
H: 404 data points (2.31%) set to NA
LE: 410 data points (2.34%) set to NA
NEE: 841 data points (4.8%) set to NA
-------------------------------------------------------------------
Data filtering:
6576 data points (37.53%) excluded by growing season filter
1790 additional data points (10.22%) excluded by precipitation filter (4352
 data points = 24.84 % in total)
8366 data points (47.75%) excluded in total
9154 valid data points (52.25%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 438 data points (2.5%) set to NA
H: 404 data points (2.31%) set to NA
LE: 410 data points (2.34%) set to NA
NEE: 841 data points (4.8%) set to NA
-------------------------------------------------------------------
Data filtering:
6576 data points (37.53%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6576 data points (37.53%) excluded in total
10944 valid data points (62.47%) remaining.

New sEddyProc class for site 'US-Me6'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 15 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Me6-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1259 data points (7.19%) set to NA
H: 1334 data points (7.61%) set to NA
LE: 1340 data points (7.65%) set to NA
NEE: 1701 data points (9.71%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.67%) excluded by growing season filter
2298 additional data points (13.12%) excluded by precipitation filter (5621
 data points = 32.08 % in total)
10650 data points (60.79%) excluded in total
6870 valid data points (39.21%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1259 data points (7.19%) set to NA
H: 1334 data points (7.61%) set to NA
LE: 1340 data points (7.65%) set to NA
NEE: 1701 data points (9.71%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8352 data points (47.67%) excluded in total
9168 valid data points (52.33%) remaining.

New sEddyProc class for site 'US-Me6'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 12 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Me6-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1367 data points (7.78%) set to NA
H: 1791 data points (10.19%) set to NA
LE: 1805 data points (10.27%) set to NA
NEE: 2310 data points (13.15%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 13”

-------------------------------------------------------------------
Data filtering:
11088 data points (63.11%) excluded by growing season filter
1204 additional data points (6.85%) excluded by precipitation filter (4113
 data points = 23.41 % in total)
12292 data points (69.97%) excluded in total
5276 valid data points (30.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1367 data points (7.78%) set to NA
H: 1791 data points (10.19%) set to NA
LE: 1805 data points (10.27%) set to NA
NEE: 2310 data points (13.15%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 13”

-------------------------------------------------------------------
Data filtering:
11088 data points (63.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11088 data points (63.11%) excluded in total
6480 valid data points (36.89%) remaining.

New sEddyProc class for site 'US-Me6'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Me6-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 566 data points (3.23%) set to NA
H: 585 data points (3.34%) set to NA
LE: 610 data points (3.48%) set to NA
NEE: 1042 data points (5.95%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.16%) excluded by growing season filter
1016 additional data points (5.8%) excluded by precipitation filter (4444
 data points = 25.37 % in total)
10856 data points (61.96%) excluded in total
6664 valid data points (38.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 566 data points (3.23%) set to NA
H: 585 data points (3.34%) set to NA
LE: 610 data points (3.48%) set to NA
NEE: 1042 data points (5.95%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9840 data points (56.16%) excluded in total
7680 valid data points (43.84%) remaining.

New sEddyProc class for site 'US-Me6'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 13 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Me6-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 62 data points (0.35%) set to NA
H: 1960 data points (11.19%) set to NA
LE: 1808 data points (10.32%) set to NA
NEE: 2794 data points (15.95%) set to NA
-------------------------------------------------------------------
Data filtering:
9264 data points (52.88%) excluded by growing season filter
2038 additional data points (11.63%) excluded by precipitation filter (5046
 data points = 28.8 % in total)
11302 data points (64.51%) excluded in total
6218 valid data points (35.49%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 62 data points (0.35%) set to NA
H: 1960 data points (11.19%) set to NA
LE: 1808 data points (10.32%) set to NA
NEE: 2794 data points (15.95%) set to NA
-------------------------------------------------------------------
Data filtering:
9264 data points (52.88%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9264 data points (52.88%) excluded in total
8256 valid data points (47.12%) remaining.

New sEddyProc class for site 'US-Me6'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Me6-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 366 data points (2.09%) set to NA
H: 565 data points (3.22%) set to NA
LE: 597 data points (3.41%) set to NA
NEE: 905 data points (5.17%) set to NA
-------------------------------------------------------------------
Data filtering:
9696 data points (55.34%) excluded by growing season filter
1417 additional data points (8.09%) excluded by precipitation filter (5595
 data points = 31.93 % in total)
11113 data points (63.43%) excluded in total
6407 valid data points (36.57%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 366 data points (2.09%) set to NA
H: 565 data points (3.22%) set to NA
LE: 597 data points (3.41%) set to NA
NEE: 905 data points (5.17%) set to NA
-------------------------------------------------------------------
Data filtering:
9696 data points (55.34%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9696 data points (55.34%) excluded in total
7824 valid data points (44.66%) remaining.

New sEddyProc class for site 'US-Me6'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Me6-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 456 data points (2.6%) set to NA
H: 686 data points (3.9%) set to NA
LE: 709 data points (4.04%) set to NA
NEE: 1021 data points (5.81%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.27%) excluded by growing season filter
1518 additional data points (8.64%) excluded by precipitation filter (5413
 data points = 30.81 % in total)
9822 data points (55.91%) excluded in total
7746 valid data points (44.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 456 data points (2.6%) set to NA
H: 686 data points (3.9%) set to NA
LE: 709 data points (4.04%) set to NA
NEE: 1021 data points (5.81%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8304 data points (47.27%) excluded in total
9264 valid data points (52.73%) remaining.

New sEddyProc class for site 'US-Me6'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 64.64.

Regression of reference temperature R_ref for 9 periods.

Quality control:
TA: 214 data points (1.22%) set to NA
H: 231 data points (1.32%) set to NA
LE: 235 data points (1.34%) set to NA
NEE: 583 data points (3.33%) set to NA
-------------------------------------------------------------------
Data filtering:
8736 data points (49.86%) excluded by growing season filter
1278 additional data points (7.29%) excluded by precipitation filter (4929
 data points = 28.13 % in total)
10014 data points (57.16%) excluded in total
7506 valid data points (42.84%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 214 data points (1.22%) set to NA
H: 231 data points (1.32%) set to NA
LE: 235 data points (1.34%) set to NA
NEE: 583 data points (3.33%) set to NA
-------------------------------------------------------------------
Data filtering:
8736 data points (49.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8736 data points (49.86%) excluded in total
8784 valid data points (50.14%) remaining.

New sEddyProc class for site 'US-Me6'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Me6-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[240/329] Processing: US-Me7

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Me7 | Years: 2022, 2023
Quality control:
TA: 8012 data points (45.73%) set to NA
H: 8015 data points (45.75%) set to NA
LE: 8014 data points (45.74%) set to NA
NEE: 8146 data points (46.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 156”

-------------------------------------------------------------------
Data filtering:
8592 data points (49.04%) excluded by growing season filter
4744 additional data points (27.08%) excluded by precipitation filter (7856
 data points = 44.84 % in total)
13336 data points (76.12%) excluded in total
4184 valid data points (23.88%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (10) for US-Me7-2022”

Quality control:
TA: 573 data points (3.27%) set to NA
H: 571 data points (3.26%) set to NA
LE: 568 data points (3.24%) set to NA
NEE: 748 data points (4.27%) set to NA
-------------------------------------------------------------------
Data filtering:
16560 data points (94.52%) excluded by growing season filter
334 additional data points (1.91%) excluded by precipitation filter (9144
 data points = 52.19 % in total)
16894 data points (96.43%) excluded in total
626 valid data points (3.57%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (24) for US-Me7-2023”
[241/329] Processing: US-Mpj

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Mpj | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 0 data points (0%) set to NA
H: 110 data points (0.63%) set to NA
LE: 129 data points (0.74%) set to NA
NEE: 402 data points (2.29%) set to NA
-------------------------------------------------------------------
Data filtering:
2016 data points (11.51%) excluded by growing season filter
3400 additional data points (19.41%) excluded by precipitation filter (4082
 data points = 23.3 % in total)
5416 data points (30.91%) excluded in total
12104 valid data points (69.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 110 data points (0.63%) set to NA
LE: 129 data points (0.74%) set to NA
NEE: 402 data points (2.29%) set to NA
-------------------------------------------------------------------
Data filtering:
2016 data points (11.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2016 data points (11.51%) excluded in total
15504 valid data points (88.49%) remaining.

New sEddyProc class for site 'US-Mpj'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Mpj-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 541 data points (3.09%) set to NA
H: 661 data points (3.77%) set to NA
LE: 683 data points (3.9%) set to NA
NEE: 1030 data points (5.88%) set to NA
-------------------------------------------------------------------
Data filtering:
5184 data points (29.59%) excluded by growing season filter
2601 additional data points (14.85%) excluded by precipitation filter (3420
 data points = 19.52 % in total)
7785 data points (44.43%) excluded in total
9735 valid data points (55.57%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 541 data points (3.09%) set to NA
H: 661 data points (3.77%) set to NA
LE: 683 data points (3.9%) set to NA
NEE: 1030 data points (5.88%) set to NA
-------------------------------------------------------------------
Data filtering:
5184 data points (29.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5184 data points (29.59%) excluded in total
12336 valid data points (70.41%) remaining.

New sEddyProc class for site 'US-Mpj'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 108.17.

Regression of reference temperature R_ref for 5 periods.

Quality control:
TA: 16 data points (0.09%) set to NA
H: 125 data points (0.71%) set to NA
LE: 145 data points (0.83%) set to NA
NEE: 341 data points (1.95%) set to NA
-------------------------------------------------------------------
Data filtering:
7008 data points (40%) excluded by growing season filter
2469 additional data points (14.09%) excluded by precipitation filter (4174
 data points = 23.82 % in total)
9477 data points (54.09%) excluded in total
8043 valid data points (45.91%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 16 data points (0.09%) set to NA
H: 125 data points (0.71%) set to NA
LE: 145 data points (0.83%) set to NA
NEE: 341 data points (1.95%) set to NA
-------------------------------------------------------------------
Data filtering:
7008 data points (40%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7008 data points (40%) excluded in total
10512 valid data points (60%) remaining.

New sEddyProc class for site 'US-Mpj'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Mpj-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 7 data points (0.04%) set to NA
H: 78 data points (0.44%) set to NA
LE: 93 data points (0.53%) set to NA
NEE: 412 data points (2.35%) set to NA
-------------------------------------------------------------------
Data filtering:
5424 data points (30.87%) excluded by growing season filter
2076 additional data points (11.82%) excluded by precipitation filter (3017
 data points = 17.17 % in total)
7500 data points (42.69%) excluded in total
10068 valid data points (57.31%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7 data points (0.04%) set to NA
H: 78 data points (0.44%) set to NA
LE: 93 data points (0.53%) set to NA
NEE: 412 data points (2.35%) set to NA
-------------------------------------------------------------------
Data filtering:
5424 data points (30.87%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5424 data points (30.87%) excluded in total
12144 valid data points (69.13%) remaining.

New sEddyProc class for site 'US-Mpj'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Mpj-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 30 data points (0.17%) set to NA
H: 134 data points (0.76%) set to NA
LE: 162 data points (0.92%) set to NA
NEE: 340 data points (1.94%) set to NA
-------------------------------------------------------------------
Data filtering:
7488 data points (42.74%) excluded by growing season filter
2383 additional data points (13.6%) excluded by precipitation filter (3094
 data points = 17.66 % in total)
9871 data points (56.34%) excluded in total
7649 valid data points (43.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 30 data points (0.17%) set to NA
H: 134 data points (0.76%) set to NA
LE: 162 data points (0.92%) set to NA
NEE: 340 data points (1.94%) set to NA
-------------------------------------------------------------------
Data filtering:
7488 data points (42.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7488 data points (42.74%) excluded in total
10032 valid data points (57.26%) remaining.

New sEddyProc class for site 'US-Mpj'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Mpj-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1 data points (0.01%) set to NA
H: 144 data points (0.82%) set to NA
LE: 169 data points (0.96%) set to NA
NEE: 352 data points (2.01%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.4%) excluded by growing season filter
2739 additional data points (15.63%) excluded by precipitation filter (3699
 data points = 21.11 % in total)
11043 data points (63.03%) excluded in total
6477 valid data points (36.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1 data points (0.01%) set to NA
H: 144 data points (0.82%) set to NA
LE: 169 data points (0.96%) set to NA
NEE: 352 data points (2.01%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.4%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8304 data points (47.4%) excluded in total
9216 valid data points (52.6%) remaining.

New sEddyProc class for site 'US-Mpj'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Mpj-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 33 data points (0.19%) set to NA
H: 144 data points (0.82%) set to NA
LE: 165 data points (0.94%) set to NA
NEE: 487 data points (2.78%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (60%) excluded by growing season filter
1266 additional data points (7.23%) excluded by precipitation filter (3759
 data points = 21.46 % in total)
11778 data points (67.23%) excluded in total
5742 valid data points (32.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 33 data points (0.19%) set to NA
H: 144 data points (0.82%) set to NA
LE: 165 data points (0.94%) set to NA
NEE: 487 data points (2.78%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (60%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10512 data points (60%) excluded in total
7008 valid data points (40%) remaining.

New sEddyProc class for site 'US-Mpj'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Mpj-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 34 data points (0.19%) set to NA
H: 160 data points (0.91%) set to NA
LE: 176 data points (1%) set to NA
NEE: 464 data points (2.64%) set to NA
-------------------------------------------------------------------
Data filtering:
3744 data points (21.31%) excluded by growing season filter
2875 additional data points (16.36%) excluded by precipitation filter (3699
 data points = 21.06 % in total)
6619 data points (37.68%) excluded in total
10949 valid data points (62.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 34 data points (0.19%) set to NA
H: 160 data points (0.91%) set to NA
LE: 176 data points (1%) set to NA
NEE: 464 data points (2.64%) set to NA
-------------------------------------------------------------------
Data filtering:
3744 data points (21.31%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3744 data points (21.31%) excluded in total
13824 valid data points (78.69%) remaining.

New sEddyProc class for site 'US-Mpj'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Mpj-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 34 data points (0.19%) set to NA
H: 127 data points (0.72%) set to NA
LE: 137 data points (0.78%) set to NA
NEE: 383 data points (2.19%) set to NA
-------------------------------------------------------------------
Data filtering:
1536 data points (8.77%) excluded by growing season filter
3469 additional data points (19.8%) excluded by precipitation filter (3627
 data points = 20.7 % in total)
5005 data points (28.57%) excluded in total
12515 valid data points (71.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 34 data points (0.19%) set to NA
H: 127 data points (0.72%) set to NA
LE: 137 data points (0.78%) set to NA
NEE: 383 data points (2.19%) set to NA
-------------------------------------------------------------------
Data filtering:
1536 data points (8.77%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
1536 data points (8.77%) excluded in total
15984 valid data points (91.23%) remaining.

New sEddyProc class for site 'US-Mpj'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Mpj-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[242/329] Processing: US-MtB

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-MtB | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 389 data points (2.22%) set to NA
LE: 421 data points (2.4%) set to NA
NEE: 2849 data points (16.26%) set to NA
-------------------------------------------------------------------
Data filtering:
2016 data points (11.51%) excluded by growing season filter
2356 additional data points (13.45%) excluded by precipitation filter (3242
 data points = 18.5 % in total)
4372 data points (24.95%) excluded in total
13148 valid data points (75.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 389 data points (2.22%) set to NA
LE: 421 data points (2.4%) set to NA
NEE: 2849 data points (16.26%) set to NA
-------------------------------------------------------------------
Data filtering:
2016 data points (11.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2016 data points (11.51%) excluded in total
15504 valid data points (88.49%) remaining.

New sEddyProc class for site 'US-MtB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MtB-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 772 data points (4.41%) set to NA
H: 1099 data points (6.27%) set to NA
LE: 1111 data points (6.34%) set to NA
NEE: 2478 data points (14.14%) set to NA
-------------------------------------------------------------------
Data filtering:
2976 data points (16.99%) excluded by growing season filter
2615 additional data points (14.93%) excluded by precipitation filter (3268
 data points = 18.65 % in total)
5591 data points (31.91%) excluded in total
11929 valid data points (68.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 772 data points (4.41%) set to NA
H: 1099 data points (6.27%) set to NA
LE: 1111 data points (6.34%) set to NA
NEE: 2478 data points (14.14%) set to NA
-------------------------------------------------------------------
Data filtering:
2976 data points (16.99%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2976 data points (16.99%) excluded in total
14544 valid data points (83.01%) remaining.

New sEddyProc class for site 'US-MtB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MtB-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2475 data points (14.13%) set to NA
H: 3268 data points (18.65%) set to NA
LE: 3294 data points (18.8%) set to NA
NEE: 8307 data points (47.41%) set to NA
-------------------------------------------------------------------
Data filtering:
3360 data points (19.18%) excluded by growing season filter
3065 additional data points (17.49%) excluded by precipitation filter (4162
 data points = 23.76 % in total)
6425 data points (36.67%) excluded in total
11095 valid data points (63.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2475 data points (14.13%) set to NA
H: 3268 data points (18.65%) set to NA
LE: 3294 data points (18.8%) set to NA
NEE: 8307 data points (47.41%) set to NA
-------------------------------------------------------------------
Data filtering:
3360 data points (19.18%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3360 data points (19.18%) excluded in total
14160 valid data points (80.82%) remaining.

New sEddyProc class for site 'US-MtB'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 77.1.

Regression of reference temperature R_ref for 23 periods.

Quality control:
TA: 866 data points (4.93%) set to NA
H: 744 data points (4.23%) set to NA
LE: 759 data points (4.32%) set to NA
NEE: 4084 data points (23.25%) set to NA
-------------------------------------------------------------------
Data filtering:
4080 data points (23.22%) excluded by growing season filter
2152 additional data points (12.25%) excluded by precipitation filter (2678
 data points = 15.24 % in total)
6232 data points (35.47%) excluded in total
11336 valid data points (64.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 866 data points (4.93%) set to NA
H: 744 data points (4.23%) set to NA
LE: 759 data points (4.32%) set to NA
NEE: 4084 data points (23.25%) set to NA
-------------------------------------------------------------------
Data filtering:
4080 data points (23.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4080 data points (23.22%) excluded in total
13488 valid data points (76.78%) remaining.

New sEddyProc class for site 'US-MtB'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 249.88.

Regression of reference temperature R_ref for 9 periods.

Quality control:
TA: 31 data points (0.18%) set to NA
H: 144 data points (0.82%) set to NA
LE: 157 data points (0.9%) set to NA
NEE: 6680 data points (38.13%) set to NA
-------------------------------------------------------------------
Data filtering:
4944 data points (28.22%) excluded by growing season filter
3001 additional data points (17.13%) excluded by precipitation filter (3896
 data points = 22.24 % in total)
7945 data points (45.35%) excluded in total
9575 valid data points (54.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 31 data points (0.18%) set to NA
H: 144 data points (0.82%) set to NA
LE: 157 data points (0.9%) set to NA
NEE: 6680 data points (38.13%) set to NA
-------------------------------------------------------------------
Data filtering:
4944 data points (28.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4944 data points (28.22%) excluded in total
12576 valid data points (71.78%) remaining.

New sEddyProc class for site 'US-MtB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MtB-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 12 data points (0.07%) set to NA
H: 79 data points (0.45%) set to NA
LE: 85 data points (0.49%) set to NA
NEE: 4498 data points (25.67%) set to NA
-------------------------------------------------------------------
Data filtering:
4560 data points (26.03%) excluded by growing season filter
2643 additional data points (15.09%) excluded by precipitation filter (3994
 data points = 22.8 % in total)
7203 data points (41.11%) excluded in total
10317 valid data points (58.89%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12 data points (0.07%) set to NA
H: 79 data points (0.45%) set to NA
LE: 85 data points (0.49%) set to NA
NEE: 4498 data points (25.67%) set to NA
-------------------------------------------------------------------
Data filtering:
4560 data points (26.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4560 data points (26.03%) excluded in total
12960 valid data points (73.97%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
New sEddyProc class for site 'US-MtB'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MtB-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1046 data points (5.97%) set to NA
H: 1108 data points (6.32%) set to NA
LE: 1111 data points (6.34%) set to NA
NEE: 3868 data points (22.08%) set to NA
-------------------------------------------------------------------
Data filtering:
4608 data points (26.3%) excluded by growing season filter
2190 additional data points (12.5%) excluded by precipitation filter (3525
 data points = 20.12 % in total)
6798 data points (38.8%) excluded in total
10722 valid data points (61.2%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1046 data points (5.97%) set to NA
H: 1108 data points (6.32%) set to NA
LE: 1111 data points (6.34%) set to NA
NEE: 3868 data points (22.08%) set to NA
-------------------------------------------------------------------
Data filtering:
4608 data points (26.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4608 data points (26.3%) excluded in total
12912 valid data points (73.7%) remaining.

New sEddyProc class for site 'US-MtB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 8 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-MtB-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 334 data points (1.9%) set to NA
H: 352 data points (2%) set to NA
LE: 683 data points (3.89%) set to NA
NEE: 6002 data points (34.16%) set to NA
-------------------------------------------------------------------
Data filtering:
2544 data points (14.48%) excluded by growing season filter
2982 additional data points (16.97%) excluded by precipitation filter (4017
 data points = 22.87 % in total)
5526 data points (31.45%) excluded in total
12042 valid data points (68.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 334 data points (1.9%) set to NA
H: 352 data points (2%) set to NA
LE: 683 data points (3.89%) set to NA
NEE: 6002 data points (34.16%) set to NA
-------------------------------------------------------------------
Data filtering:
2544 data points (14.48%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2544 data points (14.48%) excluded in total
15024 valid data points (85.52%) remaining.

New sEddyProc class for site 'US-MtB'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 192.87.

Regression of reference temperature R_ref for 5 periods.

[243/329] Processing: US-Myb

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Myb | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 39 data points (0.22%) set to NA
H: 286 data points (1.63%) set to NA
LE: 388 data points (2.21%) set to NA
NEE: 1296 data points (7.4%) set to NA
-------------------------------------------------------------------
Data filtering:
6432 data points (36.71%) excluded by growing season filter
997 additional data points (5.69%) excluded by precipitation filter (3724
 data points = 21.26 % in total)
7429 data points (42.4%) excluded in total
10091 valid data points (57.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 39 data points (0.22%) set to NA
H: 286 data points (1.63%) set to NA
LE: 388 data points (2.21%) set to NA
NEE: 1296 data points (7.4%) set to NA
-------------------------------------------------------------------
Data filtering:
6432 data points (36.71%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6432 data points (36.71%) excluded in total
11088 valid data points (63.29%) remaining.

New sEddyProc class for site 'US-Myb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Myb-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 409 data points (2.33%) set to NA
H: 117 data points (0.67%) set to NA
LE: 184 data points (1.05%) set to NA
NEE: 1065 data points (6.08%) set to NA
-------------------------------------------------------------------
Data filtering:
8016 data points (45.75%) excluded by growing season filter
63 additional data points (0.36%) excluded by precipitation filter (2787
 data points = 15.91 % in total)
8079 data points (46.11%) excluded in total
9441 valid data points (53.89%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 409 data points (2.33%) set to NA
H: 117 data points (0.67%) set to NA
LE: 184 data points (1.05%) set to NA
NEE: 1065 data points (6.08%) set to NA
-------------------------------------------------------------------
Data filtering:
8016 data points (45.75%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8016 data points (45.75%) excluded in total
9504 valid data points (54.25%) remaining.

New sEddyProc class for site 'US-Myb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Myb-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 981 data points (5.6%) set to NA
H: 7 data points (0.04%) set to NA
LE: 318 data points (1.82%) set to NA
NEE: 1373 data points (7.84%) set to NA
-------------------------------------------------------------------
Data filtering:
8160 data points (46.58%) excluded by growing season filter
677 additional data points (3.86%) excluded by precipitation filter (4087
 data points = 23.33 % in total)
8837 data points (50.44%) excluded in total
8683 valid data points (49.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 981 data points (5.6%) set to NA
H: 7 data points (0.04%) set to NA
LE: 318 data points (1.82%) set to NA
NEE: 1373 data points (7.84%) set to NA
-------------------------------------------------------------------
Data filtering:
8160 data points (46.58%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8160 data points (46.58%) excluded in total
9360 valid data points (53.42%) remaining.

New sEddyProc class for site 'US-Myb'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 197.62.

Regression of reference temperature R_ref for 8 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 77 data points (0.44%) set to NA
NEE: 696 data points (3.96%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.27%) excluded by growing season filter
360 additional data points (2.05%) excluded by precipitation filter (2047
 data points = 11.65 % in total)
8664 data points (49.32%) excluded in total
8904 valid data points (50.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 77 data points (0.44%) set to NA
NEE: 696 data points (3.96%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8304 data points (47.27%) excluded in total
9264 valid data points (52.73%) remaining.

New sEddyProc class for site 'US-Myb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Myb-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 226 data points (1.29%) set to NA
H: 1063 data points (6.07%) set to NA
LE: 1351 data points (7.71%) set to NA
NEE: 2090 data points (11.93%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
98 additional data points (0.56%) excluded by precipitation filter (2623
 data points = 14.97 % in total)
10370 data points (59.19%) excluded in total
7150 valid data points (40.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 226 data points (1.29%) set to NA
H: 1063 data points (6.07%) set to NA
LE: 1351 data points (7.71%) set to NA
NEE: 2090 data points (11.93%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10272 data points (58.63%) excluded in total
7248 valid data points (41.37%) remaining.

New sEddyProc class for site 'US-Myb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Myb-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1726 data points (9.85%) set to NA
LE: 1781 data points (10.17%) set to NA
NEE: 3471 data points (19.81%) set to NA
-------------------------------------------------------------------
Data filtering:
8928 data points (50.96%) excluded by growing season filter
302 additional data points (1.72%) excluded by precipitation filter (1837
 data points = 10.49 % in total)
9230 data points (52.68%) excluded in total
8290 valid data points (47.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1726 data points (9.85%) set to NA
LE: 1781 data points (10.17%) set to NA
NEE: 3471 data points (19.81%) set to NA
-------------------------------------------------------------------
Data filtering:
8928 data points (50.96%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8928 data points (50.96%) excluded in total
8592 valid data points (49.04%) remaining.

New sEddyProc class for site 'US-Myb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Myb-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 111 data points (0.63%) set to NA
H: 7 data points (0.04%) set to NA
LE: 46 data points (0.26%) set to NA
NEE: 1089 data points (6.22%) set to NA
-------------------------------------------------------------------
Data filtering:
9408 data points (53.7%) excluded by growing season filter
107 additional data points (0.61%) excluded by precipitation filter (2768
 data points = 15.8 % in total)
9515 data points (54.31%) excluded in total
8005 valid data points (45.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 111 data points (0.63%) set to NA
H: 7 data points (0.04%) set to NA
LE: 46 data points (0.26%) set to NA
NEE: 1089 data points (6.22%) set to NA
-------------------------------------------------------------------
Data filtering:
9408 data points (53.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9408 data points (53.7%) excluded in total
8112 valid data points (46.3%) remaining.

New sEddyProc class for site 'US-Myb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Myb-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 48 data points (0.27%) set to NA
LE: 97 data points (0.55%) set to NA
NEE: 1576 data points (8.97%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.54%) excluded by growing season filter
186 additional data points (1.06%) excluded by precipitation filter (3584
 data points = 20.4 % in total)
8538 data points (48.6%) excluded in total
9030 valid data points (51.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 48 data points (0.27%) set to NA
LE: 97 data points (0.55%) set to NA
NEE: 1576 data points (8.97%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.54%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8352 data points (47.54%) excluded in total
9216 valid data points (52.46%) remaining.

New sEddyProc class for site 'US-Myb'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Myb-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4404 data points (25.14%) set to NA
H: 4407 data points (25.15%) set to NA
LE: 4454 data points (25.42%) set to NA
NEE: 5094 data points (29.08%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 82”

-------------------------------------------------------------------
Data filtering:
6768 data points (38.63%) excluded by growing season filter
1319 additional data points (7.53%) excluded by precipitation filter (2294
 data points = 13.09 % in total)
8087 data points (46.16%) excluded in total
9433 valid data points (53.84%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4404 data points (25.14%) set to NA
H: 4407 data points (25.15%) set to NA
LE: 4454 data points (25.42%) set to NA
NEE: 5094 data points (29.08%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 82”

-------------------------------------------------------------------
Data filtering:
6768 data points (38.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6768 data points (38.63%) excluded in total
10752 valid data points (61.37%) remaining.

New sEddyProc class for site 'US-Myb'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 86.82.

Regression of reference temperature R_ref for 6 periods.

[244/329] Processing: US-NC2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-NC2 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 21 data points (0.12%) set to NA
H: 457 data points (2.61%) set to NA
LE: 523 data points (2.99%) set to NA
NEE: 781 data points (4.46%) set to NA
-------------------------------------------------------------------
Data filtering:
2976 data points (16.99%) excluded by growing season filter
5207 additional data points (29.72%) excluded by precipitation filter (6640
 data points = 37.9 % in total)
8183 data points (46.71%) excluded in total
9337 valid data points (53.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 21 data points (0.12%) set to NA
H: 457 data points (2.61%) set to NA
LE: 523 data points (2.99%) set to NA
NEE: 781 data points (4.46%) set to NA
-------------------------------------------------------------------
Data filtering:
2976 data points (16.99%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2976 data points (16.99%) excluded in total
14544 valid data points (83.01%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 11 cases! Invalid values with 'NEE < -50': -69, -68, -59, -64, -64, -68, -61, -79, -51, -70, -51 ...”
New sEddyProc class for site 'US-NC2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 11 cases! Invalid values with 'NEE < -50': -69, -68, -59, -64, -64, -68, -61, -79, -51, -70, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC2-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 246 data points (1.4%) set to NA
H: 1741 data points (9.94%) set to NA
LE: 5679 data points (32.41%) set to NA
NEE: 4282 data points (24.44%) set to NA
-------------------------------------------------------------------
Data filtering:
3936 data points (22.47%) excluded by growing season filter
5410 additional data points (30.88%) excluded by precipitation filter (6876
 data points = 39.25 % in total)
9346 data points (53.34%) excluded in total
8174 valid data points (46.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 246 data points (1.4%) set to NA
H: 1741 data points (9.94%) set to NA
LE: 5679 data points (32.41%) set to NA
NEE: 4282 data points (24.44%) set to NA
-------------------------------------------------------------------
Data filtering:
3936 data points (22.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3936 data points (22.47%) excluded in total
13584 valid data points (77.53%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -74, -71, -68, -73, -70, -63, -58, -54 ...”
New sEddyProc class for site 'US-NC2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -74, -71, -68, -73, -70, -63, -58, -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC2-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 497 data points (2.84%) set to NA
H: 788 data points (4.5%) set to NA
LE: 2590 data points (14.78%) set to NA
NEE: 1691 data points (9.65%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.59%) excluded by growing season filter
2798 additional data points (15.97%) excluded by precipitation filter (5789
 data points = 33.04 % in total)
11486 data points (65.56%) excluded in total
6034 valid data points (34.44%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 497 data points (2.84%) set to NA
H: 788 data points (4.5%) set to NA
LE: 2590 data points (14.78%) set to NA
NEE: 1691 data points (9.65%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8688 data points (49.59%) excluded in total
8832 valid data points (50.41%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 11 cases! Invalid values with 'NEE < -50': -66, -68, -56, -57, -62, -66, -53, -58, -61, -54, -67 ...”
New sEddyProc class for site 'US-NC2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 11 cases! Invalid values with 'NEE < -50': -66, -68, -56, -57, -62, -66, -53, -58, -61, -54, -67 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC2-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1301 data points (7.41%) set to NA
H: 2572 data points (14.64%) set to NA
LE: 2693 data points (15.33%) set to NA
NEE: 3319 data points (18.89%) set to NA
-------------------------------------------------------------------
Data filtering:
8640 data points (49.18%) excluded by growing season filter
3236 additional data points (18.42%) excluded by precipitation filter (6549
 data points = 37.28 % in total)
11876 data points (67.6%) excluded in total
5692 valid data points (32.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1301 data points (7.41%) set to NA
H: 2572 data points (14.64%) set to NA
LE: 2693 data points (15.33%) set to NA
NEE: 3319 data points (18.89%) set to NA
-------------------------------------------------------------------
Data filtering:
8640 data points (49.18%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8640 data points (49.18%) excluded in total
8928 valid data points (50.82%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 18 cases! Invalid values with 'NEE < -50': -64, -71, -52, -51, -67, -62, -59, -51, -75, -73, -62, -53, -52, -54, -57, -52, -63, -52 ...”
New sEddyProc class for site 'US-NC2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 18 cases! Invalid values with 'NEE < -50': -64, -71, -52, -51, -67, -62, -59, -51, -75, -73, -62, -53, -52, -54, -57, -52, -63, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC2-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 648 data points (3.7%) set to NA
H: 1981 data points (11.31%) set to NA
LE: 2047 data points (11.68%) set to NA
NEE: 2885 data points (16.47%) set to NA
-------------------------------------------------------------------
Data filtering:
7728 data points (44.11%) excluded by growing season filter
4664 additional data points (26.62%) excluded by precipitation filter (7660
 data points = 43.72 % in total)
12392 data points (70.73%) excluded in total
5128 valid data points (29.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 648 data points (3.7%) set to NA
H: 1981 data points (11.31%) set to NA
LE: 2047 data points (11.68%) set to NA
NEE: 2885 data points (16.47%) set to NA
-------------------------------------------------------------------
Data filtering:
7728 data points (44.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7728 data points (44.11%) excluded in total
9792 valid data points (55.89%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 6 cases! Invalid values with 'NEE < -50': -64, -70, -74, -53, -78, -64 ...”
New sEddyProc class for site 'US-NC2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 6 cases! Invalid values with 'NEE < -50': -64, -70, -74, -53, -78, -64 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 95.13.

Regression of reference temperature R_ref for 35 periods.

Quality control:
TA: 1714 data points (9.78%) set to NA
H: 3479 data points (19.86%) set to NA
LE: 3475 data points (19.83%) set to NA
NEE: 4165 data points (23.77%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.59%) excluded by growing season filter
1440 additional data points (8.22%) excluded by precipitation filter (2788
 data points = 15.91 % in total)
10128 data points (57.81%) excluded in total
7392 valid data points (42.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1714 data points (9.78%) set to NA
H: 3479 data points (19.86%) set to NA
LE: 3475 data points (19.83%) set to NA
NEE: 4165 data points (23.77%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8688 data points (49.59%) excluded in total
8832 valid data points (50.41%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -56, -71, -75, -59, -59 ...”
New sEddyProc class for site 'US-NC2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -56, -71, -75, -59, -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 97.57.

Regression of reference temperature R_ref for 11 periods.

Quality control:
TA: 8 data points (0.05%) set to NA
H: 357 data points (2.04%) set to NA
LE: 404 data points (2.31%) set to NA
NEE: 1671 data points (9.54%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.67%) excluded by growing season filter
3384 additional data points (19.32%) excluded by precipitation filter (6327
 data points = 36.11 % in total)
11736 data points (66.99%) excluded in total
5784 valid data points (33.01%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8 data points (0.05%) set to NA
H: 357 data points (2.04%) set to NA
LE: 404 data points (2.31%) set to NA
NEE: 1671 data points (9.54%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8352 data points (47.67%) excluded in total
9168 valid data points (52.33%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -52, -74, -51, -69 ...”
New sEddyProc class for site 'US-NC2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -52, -74, -51, -69 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC2-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 7466 data points (42.5%) set to NA
H: 7684 data points (43.74%) set to NA
LE: 7719 data points (43.94%) set to NA
NEE: 8376 data points (47.68%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 88”

-------------------------------------------------------------------
Data filtering:
4560 data points (25.96%) excluded by growing season filter
4637 additional data points (26.39%) excluded by precipitation filter (6059
 data points = 34.49 % in total)
9197 data points (52.35%) excluded in total
8371 valid data points (47.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7466 data points (42.5%) set to NA
H: 7684 data points (43.74%) set to NA
LE: 7719 data points (43.94%) set to NA
NEE: 8376 data points (47.68%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 88”

-------------------------------------------------------------------
Data filtering:
4560 data points (25.96%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4560 data points (25.96%) excluded in total
13008 valid data points (74.04%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
New sEddyProc class for site 'US-NC2'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 155.41.

Regression of reference temperature R_ref for 27 periods.

Quality control:
TA: 54 data points (0.31%) set to NA
H: 3427 data points (19.56%) set to NA
LE: 16398 data points (93.6%) set to NA
NEE: 16451 data points (93.9%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5326 additional data points (30.4%) excluded by precipitation filter (5326
 data points = 30.4 % in total)
5326 data points (30.4%) excluded in total
12194 valid data points (69.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 54 data points (0.31%) set to NA
H: 3427 data points (19.56%) set to NA
LE: 16398 data points (93.6%) set to NA
NEE: 16451 data points (93.9%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-NC2'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC2-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[245/329] Processing: US-NC3

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-NC3 | Years: 2017, 2018, 2019, 2020, 2021
Quality control:
TA: 0 data points (0%) set to NA
H: 338 data points (1.93%) set to NA
LE: 522 data points (2.98%) set to NA
NEE: 792 data points (4.52%) set to NA
-------------------------------------------------------------------
Data filtering:
7344 data points (41.92%) excluded by growing season filter
3579 additional data points (20.43%) excluded by precipitation filter (5829
 data points = 33.27 % in total)
10923 data points (62.35%) excluded in total
6597 valid data points (37.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 338 data points (1.93%) set to NA
LE: 522 data points (2.98%) set to NA
NEE: 792 data points (4.52%) set to NA
-------------------------------------------------------------------
Data filtering:
7344 data points (41.92%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7344 data points (41.92%) excluded in total
10176 valid data points (58.08%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
New sEddyProc class for site 'US-NC3'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC3-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 103 data points (0.59%) set to NA
LE: 171 data points (0.98%) set to NA
NEE: 476 data points (2.72%) set to NA
-------------------------------------------------------------------
Data filtering:
7632 data points (43.56%) excluded by growing season filter
1910 additional data points (10.9%) excluded by precipitation filter (4273
 data points = 24.39 % in total)
9542 data points (54.46%) excluded in total
7978 valid data points (45.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 103 data points (0.59%) set to NA
LE: 171 data points (0.98%) set to NA
NEE: 476 data points (2.72%) set to NA
-------------------------------------------------------------------
Data filtering:
7632 data points (43.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7632 data points (43.56%) excluded in total
9888 valid data points (56.44%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -51 ...”
New sEddyProc class for site 'US-NC3'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC3-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 787 data points (4.49%) set to NA
H: 531 data points (3.03%) set to NA
LE: 936 data points (5.34%) set to NA
NEE: 1358 data points (7.75%) set to NA
-------------------------------------------------------------------
Data filtering:
6144 data points (35.07%) excluded by growing season filter
3408 additional data points (19.45%) excluded by precipitation filter (5468
 data points = 31.21 % in total)
9552 data points (54.52%) excluded in total
7968 valid data points (45.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.

Warning message in nlrob(Gs ~ g0 + DwDc * (1 + g1/sqrt(VPD)) * GPP/Ca, data = df, :
“failed to converge in 20 steps”

Quality control:
TA: 787 data points (4.49%) set to NA
H: 531 data points (3.03%) set to NA
LE: 936 data points (5.34%) set to NA
NEE: 1358 data points (7.75%) set to NA
-------------------------------------------------------------------
Data filtering:
6144 data points (35.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6144 data points (35.07%) excluded in total
11376 valid data points (64.93%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -63, -53, -55, -76, -64 ...”
New sEddyProc class for site 'US-NC3'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 5 cases! Invalid values with 'NEE < -50': -63, -53, -55, -76, -64 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC3-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1508 data points (8.58%) set to NA
H: 7488 data points (42.62%) set to NA
LE: 13016 data points (74.09%) set to NA
NEE: 13409 data points (76.33%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 139”

-------------------------------------------------------------------
Data filtering:
5040 data points (28.69%) excluded by growing season filter
4529 additional data points (25.78%) excluded by precipitation filter (6510
 data points = 37.06 % in total)
9569 data points (54.47%) excluded in total
7999 valid data points (45.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1508 data points (8.58%) set to NA
H: 7488 data points (42.62%) set to NA
LE: 13016 data points (74.09%) set to NA
NEE: 13409 data points (76.33%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 139”

-------------------------------------------------------------------
Data filtering:
5040 data points (28.69%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5040 data points (28.69%) excluded in total
12528 valid data points (71.31%) remaining.

New sEddyProc class for site 'US-NC3'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 168.12.

Regression of reference temperature R_ref for 10 periods.

Quality control:
TA: 4864 data points (27.76%) set to NA
H: 15223 data points (86.89%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 17391 data points (99.26%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5295 additional data points (30.22%) excluded by precipitation filter (5295
 data points = 30.22 % in total)
5295 data points (30.22%) excluded in total
12225 valid data points (69.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 4864 data points (27.76%) set to NA
H: 15223 data points (86.89%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 17391 data points (99.26%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-NC3'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC3-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[246/329] Processing: US-NC4

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-NC4 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 0 data points (0%) set to NA
H: 3499 data points (19.97%) set to NA
LE: 2885 data points (16.47%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6026 additional data points (34.39%) excluded by precipitation filter (6026
 data points = 34.39 % in total)
6026 data points (34.39%) excluded in total
11494 valid data points (65.61%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 3499 data points (19.97%) set to NA
LE: 2885 data points (16.47%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-NC4'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC4-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 947 data points (5.41%) set to NA
H: 1193 data points (6.81%) set to NA
LE: 1435 data points (8.19%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6351 additional data points (36.25%) excluded by precipitation filter (6351
 data points = 36.25 % in total)
6351 data points (36.25%) excluded in total
11169 valid data points (63.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 947 data points (5.41%) set to NA
H: 1193 data points (6.81%) set to NA
LE: 1435 data points (8.19%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-NC4'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC4-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 738 data points (4.21%) set to NA
H: 1142 data points (6.52%) set to NA
LE: 1455 data points (8.3%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5495 additional data points (31.36%) excluded by precipitation filter (5495
 data points = 31.36 % in total)
5495 data points (31.36%) excluded in total
12025 valid data points (68.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 738 data points (4.21%) set to NA
H: 1142 data points (6.52%) set to NA
LE: 1455 data points (8.3%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-NC4'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC4-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 7089 data points (40.35%) set to NA
H: 11487 data points (65.39%) set to NA
LE: 11591 data points (65.98%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6861 additional data points (39.05%) excluded by precipitation filter (6861
 data points = 39.05 % in total)
6861 data points (39.05%) excluded in total
10707 valid data points (60.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7089 data points (40.35%) set to NA
H: 11487 data points (65.39%) set to NA
LE: 11591 data points (65.98%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-NC4'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC4-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 5077 data points (28.98%) set to NA
H: 5566 data points (31.77%) set to NA
LE: 5574 data points (31.82%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5904 additional data points (33.7%) excluded by precipitation filter (5904
 data points = 33.7 % in total)
5904 data points (33.7%) excluded in total
11616 valid data points (66.3%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5077 data points (28.98%) set to NA
H: 5566 data points (31.77%) set to NA
LE: 5574 data points (31.82%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-NC4'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC4-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 17519 data points (99.99%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6822 additional data points (38.94%) excluded by precipitation filter (6822
 data points = 38.94 % in total)
6822 data points (38.94%) excluded in total
10698 valid data points (61.06%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-NC4-2022”

Quality control:
TA: 17520 data points (100%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7064 additional data points (40.32%) excluded by precipitation filter (7064
 data points = 40.32 % in total)
7064 data points (40.32%) excluded in total
10456 valid data points (59.68%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-NC4-2023”

Quality control:
TA: 15122 data points (86.08%) set to NA
H: 15035 data points (85.58%) set to NA
LE: 15093 data points (85.91%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6195 additional data points (35.26%) excluded by precipitation filter (6195
 data points = 35.26 % in total)
6195 data points (35.26%) excluded in total
11373 valid data points (64.74%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 15122 data points (86.08%) set to NA
H: 15035 data points (85.58%) set to NA
LE: 15093 data points (85.91%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-NC4'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC4-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1471 data points (8.4%) set to NA
H: 7463 data points (42.6%) set to NA
LE: 7473 data points (42.65%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3960 additional data points (22.6%) excluded by precipitation filter (3960
 data points = 22.6 % in total)
3960 data points (22.6%) excluded in total
13560 valid data points (77.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1471 data points (8.4%) set to NA
H: 7463 data points (42.6%) set to NA
LE: 7473 data points (42.65%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-NC4'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NC4-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[247/329] Processing: US-NR1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-NR1 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 0 data points (0%) set to NA
H: 9 data points (0.05%) set to NA
LE: 2043 data points (11.66%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8714 additional data points (49.74%) excluded by precipitation filter (8714
 data points = 49.74 % in total)
8714 data points (49.74%) excluded in total
8806 valid data points (50.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 9 data points (0.05%) set to NA
LE: 2043 data points (11.66%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-NR1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NR1-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 13 data points (0.07%) set to NA
LE: 1967 data points (11.23%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7604 additional data points (43.4%) excluded by precipitation filter (7604
 data points = 43.4 % in total)
7604 data points (43.4%) excluded in total
9916 valid data points (56.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 13 data points (0.07%) set to NA
LE: 1967 data points (11.23%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-NR1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NR1-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 20 data points (0.11%) set to NA
LE: 1982 data points (11.31%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8118 additional data points (46.34%) excluded by precipitation filter (8118
 data points = 46.34 % in total)
8118 data points (46.34%) excluded in total
9402 valid data points (53.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 20 data points (0.11%) set to NA
LE: 1982 data points (11.31%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-NR1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NR1-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 3 data points (0.02%) set to NA
LE: 48 data points (0.27%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7022 additional data points (39.97%) excluded by precipitation filter (7022
 data points = 39.97 % in total)
7022 data points (39.97%) excluded in total
10546 valid data points (60.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 3 data points (0.02%) set to NA
LE: 48 data points (0.27%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-NR1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NR1-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 3 data points (0.02%) set to NA
LE: 3497 data points (19.96%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8076 additional data points (46.1%) excluded by precipitation filter (8076
 data points = 46.1 % in total)
8076 data points (46.1%) excluded in total
9444 valid data points (53.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 3 data points (0.02%) set to NA
LE: 3497 data points (19.96%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-NR1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NR1-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 22 data points (0.13%) set to NA
LE: 2824 data points (16.12%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8248 additional data points (47.08%) excluded by precipitation filter (8248
 data points = 47.08 % in total)
8248 data points (47.08%) excluded in total
9272 valid data points (52.92%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 22 data points (0.13%) set to NA
LE: 2824 data points (16.12%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-NR1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NR1-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2 data points (0.01%) set to NA
LE: 16 data points (0.09%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7820 additional data points (44.63%) excluded by precipitation filter (7820
 data points = 44.63 % in total)
7820 data points (44.63%) excluded in total
9700 valid data points (55.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2 data points (0.01%) set to NA
LE: 16 data points (0.09%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-NR1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NR1-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2 data points (0.01%) set to NA
H: 38 data points (0.22%) set to NA
LE: 87 data points (0.5%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7796 additional data points (44.38%) excluded by precipitation filter (7796
 data points = 44.38 % in total)
7796 data points (44.38%) excluded in total
9772 valid data points (55.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2 data points (0.01%) set to NA
H: 38 data points (0.22%) set to NA
LE: 87 data points (0.5%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-NR1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NR1-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2965 data points (16.92%) set to NA
H: 2999 data points (17.12%) set to NA
LE: 3167 data points (18.08%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8245 additional data points (47.06%) excluded by precipitation filter (8245
 data points = 47.06 % in total)
8245 data points (47.06%) excluded in total
9275 valid data points (52.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2965 data points (16.92%) set to NA
H: 2999 data points (17.12%) set to NA
LE: 3167 data points (18.08%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-NR1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-NR1-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[248/329] Processing: US-OWC

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-OWC | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 17520 data points (100%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8235 additional data points (47%) excluded by precipitation filter (8235
 data points = 47 % in total)
8235 data points (47%) excluded in total
9285 valid data points (53%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-OWC-2017”

Quality control:
TA: 17520 data points (100%) set to NA
H: 17520 data points (100%) set to NA
LE: 17520 data points (100%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8584 additional data points (49%) excluded by precipitation filter (8584
 data points = 49 % in total)
8584 data points (49%) excluded in total
8936 valid data points (51%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-OWC-2018”

Quality control:
TA: 6934 data points (39.58%) set to NA
H: 11454 data points (65.38%) set to NA
LE: 11431 data points (65.25%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8007 additional data points (45.7%) excluded by precipitation filter (8007
 data points = 45.7 % in total)
8007 data points (45.7%) excluded in total
9513 valid data points (54.3%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6934 data points (39.58%) set to NA
H: 11454 data points (65.38%) set to NA
LE: 11431 data points (65.25%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-OWC'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-OWC-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1761 data points (10.02%) set to NA
H: 4881 data points (27.78%) set to NA
LE: 2465 data points (14.03%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7832 additional data points (44.58%) excluded by precipitation filter (7832
 data points = 44.58 % in total)
7832 data points (44.58%) excluded in total
9736 valid data points (55.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1761 data points (10.02%) set to NA
H: 4881 data points (27.78%) set to NA
LE: 2465 data points (14.03%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-OWC'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-OWC-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6378 data points (36.4%) set to NA
H: 6897 data points (39.37%) set to NA
LE: 6888 data points (39.32%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5490 additional data points (31.34%) excluded by precipitation filter (5490
 data points = 31.34 % in total)
5490 data points (31.34%) excluded in total
12030 valid data points (68.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6378 data points (36.4%) set to NA
H: 6897 data points (39.37%) set to NA
LE: 6888 data points (39.32%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-OWC'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-OWC-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 11829 data points (67.52%) set to NA
H: 11860 data points (67.69%) set to NA
LE: 11870 data points (67.75%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7540 additional data points (43.04%) excluded by precipitation filter (7540
 data points = 43.04 % in total)
7540 data points (43.04%) excluded in total
9980 valid data points (56.96%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11829 data points (67.52%) set to NA
H: 11860 data points (67.69%) set to NA
LE: 11870 data points (67.75%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-OWC'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-OWC-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 11 data points (0.06%) set to NA
H: 1101 data points (6.28%) set to NA
LE: 1127 data points (6.43%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7547 additional data points (43.08%) excluded by precipitation filter (7547
 data points = 43.08 % in total)
7547 data points (43.08%) excluded in total
9973 valid data points (56.92%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11 data points (0.06%) set to NA
H: 1101 data points (6.28%) set to NA
LE: 1127 data points (6.43%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-OWC'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-OWC-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 4993 data points (28.42%) set to NA
LE: 5411 data points (30.8%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7683 additional data points (43.73%) excluded by precipitation filter (7683
 data points = 43.73 % in total)
7683 data points (43.73%) excluded in total
9885 valid data points (56.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 4993 data points (28.42%) set to NA
LE: 5411 data points (30.8%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-OWC'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-OWC-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4452 data points (25.41%) set to NA
H: 4514 data points (25.76%) set to NA
LE: 4517 data points (25.78%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7844 additional data points (44.77%) excluded by precipitation filter (7844
 data points = 44.77 % in total)
7844 data points (44.77%) excluded in total
9676 valid data points (55.23%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4452 data points (25.41%) set to NA
H: 4514 data points (25.76%) set to NA
LE: 4517 data points (25.78%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-OWC'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-OWC-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[249/329] Processing: US-PFL

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-PFL | Years: 2019
Quality control:
TA: 12529 data points (71.51%) set to NA
H: 12652 data points (72.21%) set to NA
LE: 12685 data points (72.4%) set to NA
NEE: 13448 data points (76.76%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10290 additional data points (58.73%) excluded by precipitation filter (10290
 data points = 58.73 % in total)
10290 data points (58.73%) excluded in total
7230 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12529 data points (71.51%) set to NA
H: 12652 data points (72.21%) set to NA
LE: 12685 data points (72.4%) set to NA
NEE: 13448 data points (76.76%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-PFL'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 116.03.

Regression of reference temperature R_ref for 17 periods.

[250/329] Processing: US-PFb

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-PFb | Years: 2019
Quality control:
TA: 13289 data points (75.85%) set to NA
H: 12871 data points (73.46%) set to NA
LE: 13120 data points (74.89%) set to NA
NEE: 13308 data points (75.96%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10290 additional data points (58.73%) excluded by precipitation filter (10290
 data points = 58.73 % in total)
10290 data points (58.73%) excluded in total
7230 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 13289 data points (75.85%) set to NA
H: 12871 data points (73.46%) set to NA
LE: 13120 data points (74.89%) set to NA
NEE: 13308 data points (75.96%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -64, -54 ...”
New sEddyProc class for site 'US-PFb'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -64, -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 95.01.

Regression of reference temperature R_ref for 19 periods.

[251/329] Processing: US-PFc

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-PFc | Years: 2019
Quality control:
TA: 12555 data points (71.66%) set to NA
H: 12731 data points (72.67%) set to NA
LE: 12835 data points (73.26%) set to NA
NEE: 13042 data points (74.44%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10290 additional data points (58.73%) excluded by precipitation filter (10290
 data points = 58.73 % in total)
10290 data points (58.73%) excluded in total
7230 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12555 data points (71.66%) set to NA
H: 12731 data points (72.67%) set to NA
LE: 12835 data points (73.26%) set to NA
NEE: 13042 data points (74.44%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-PFc'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 151.73.

Regression of reference temperature R_ref for 12 periods.

[252/329] Processing: US-PFd

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-PFd | Years: 2019
Quality control:
TA: 11920 data points (68.04%) set to NA
H: 12406 data points (70.81%) set to NA
LE: 12442 data points (71.02%) set to NA
NEE: 12736 data points (72.69%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10290 additional data points (58.73%) excluded by precipitation filter (10290
 data points = 58.73 % in total)
10290 data points (58.73%) excluded in total
7230 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11920 data points (68.04%) set to NA
H: 12406 data points (70.81%) set to NA
LE: 12442 data points (71.02%) set to NA
NEE: 12736 data points (72.69%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -60, -62 ...”
New sEddyProc class for site 'US-PFd'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -60, -62 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 237.09.

Regression of reference temperature R_ref for 12 periods.

[253/329] Processing: US-PFg

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-PFg | Years: 2019
Quality control:
TA: 13492 data points (77.01%) set to NA
H: 13609 data points (77.68%) set to NA
LE: 13644 data points (77.88%) set to NA
NEE: 13723 data points (78.33%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10290 additional data points (58.73%) excluded by precipitation filter (10290
 data points = 58.73 % in total)
10290 data points (58.73%) excluded in total
7230 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 13492 data points (77.01%) set to NA
H: 13609 data points (77.68%) set to NA
LE: 13644 data points (77.88%) set to NA
NEE: 13723 data points (78.33%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-PFg'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 81.17.

Regression of reference temperature R_ref for 11 periods.

[254/329] Processing: US-PFh

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-PFh | Years: 2019
Quality control:
TA: 12861 data points (73.41%) set to NA
H: 13014 data points (74.28%) set to NA
LE: 13029 data points (74.37%) set to NA
NEE: 13516 data points (77.15%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10290 additional data points (58.73%) excluded by precipitation filter (10290
 data points = 58.73 % in total)
10290 data points (58.73%) excluded in total
7230 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12861 data points (73.41%) set to NA
H: 13014 data points (74.28%) set to NA
LE: 13029 data points (74.37%) set to NA
NEE: 13516 data points (77.15%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-PFh'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 101.93.

Regression of reference temperature R_ref for 12 periods.

[255/329] Processing: US-PFi

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-PFi | Years: 2019
Quality control:
TA: 12540 data points (71.58%) set to NA
H: 13598 data points (77.61%) set to NA
LE: 13693 data points (78.16%) set to NA
NEE: 13942 data points (79.58%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10290 additional data points (58.73%) excluded by precipitation filter (10290
 data points = 58.73 % in total)
10290 data points (58.73%) excluded in total
7230 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12540 data points (71.58%) set to NA
H: 13598 data points (77.61%) set to NA
LE: 13693 data points (78.16%) set to NA
NEE: 13942 data points (79.58%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-PFi'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-PFi-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[256/329] Processing: US-PFj

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-PFj | Years: 2019
Quality control:
TA: 12766 data points (72.87%) set to NA
H: 12805 data points (73.09%) set to NA
LE: 12813 data points (73.13%) set to NA
NEE: 13075 data points (74.63%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10290 additional data points (58.73%) excluded by precipitation filter (10290
 data points = 58.73 % in total)
10290 data points (58.73%) excluded in total
7230 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12766 data points (72.87%) set to NA
H: 12805 data points (73.09%) set to NA
LE: 12813 data points (73.13%) set to NA
NEE: 13075 data points (74.63%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
New sEddyProc class for site 'US-PFj'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 11 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-PFj-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[257/329] Processing: US-PFk

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-PFk | Years: 2019
Quality control:
TA: 12793 data points (73.02%) set to NA
H: 12942 data points (73.87%) set to NA
LE: 12960 data points (73.97%) set to NA
NEE: 13287 data points (75.84%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10290 additional data points (58.73%) excluded by precipitation filter (10290
 data points = 58.73 % in total)
10290 data points (58.73%) excluded in total
7230 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12793 data points (73.02%) set to NA
H: 12942 data points (73.87%) set to NA
LE: 12960 data points (73.97%) set to NA
NEE: 13287 data points (75.84%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-PFk'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 10 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-PFk-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[258/329] Processing: US-PFm

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-PFm | Years: 2019
Quality control:
TA: 12395 data points (70.75%) set to NA
H: 12486 data points (71.27%) set to NA
LE: 12506 data points (71.38%) set to NA
NEE: 12718 data points (72.59%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10290 additional data points (58.73%) excluded by precipitation filter (10290
 data points = 58.73 % in total)
10290 data points (58.73%) excluded in total
7230 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12395 data points (70.75%) set to NA
H: 12486 data points (71.27%) set to NA
LE: 12506 data points (71.38%) set to NA
NEE: 12718 data points (72.59%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -53, -51, -66 ...”
New sEddyProc class for site 'US-PFm'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -53, -51, -66 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 70.62.

Regression of reference temperature R_ref for 12 periods.

[259/329] Processing: US-PFn

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-PFn | Years: 2019
Quality control:
TA: 13127 data points (74.93%) set to NA
H: 12623 data points (72.05%) set to NA
LE: 12659 data points (72.25%) set to NA
NEE: 13015 data points (74.29%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10290 additional data points (58.73%) excluded by precipitation filter (10290
 data points = 58.73 % in total)
10290 data points (58.73%) excluded in total
7230 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 13127 data points (74.93%) set to NA
H: 12623 data points (72.05%) set to NA
LE: 12659 data points (72.25%) set to NA
NEE: 13015 data points (74.29%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 10 cases! Invalid values with 'NEE < -50': -61, -70, -72, -67, -55, -55, -55, -55, -55, -55 ...”
New sEddyProc class for site 'US-PFn'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 10 cases! Invalid values with 'NEE < -50': -61, -70, -72, -67, -55, -55, -55, -55, -55, -55 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 63.91.

Regression of reference temperature R_ref for 19 periods.

[260/329] Processing: US-PFp

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-PFp | Years: 2019
Quality control:
TA: 14917 data points (85.14%) set to NA
H: 12516 data points (71.44%) set to NA
LE: 12546 data points (71.61%) set to NA
NEE: 12772 data points (72.9%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10290 additional data points (58.73%) excluded by precipitation filter (10290
 data points = 58.73 % in total)
10290 data points (58.73%) excluded in total
7230 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 14917 data points (85.14%) set to NA
H: 12516 data points (71.44%) set to NA
LE: 12546 data points (71.61%) set to NA
NEE: 12772 data points (72.9%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-PFp'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 72.8.

Regression of reference temperature R_ref for 31 periods.

[261/329] Processing: US-PFq

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-PFq | Years: 2019
Quality control:
TA: 12707 data points (72.53%) set to NA
H: 12700 data points (72.49%) set to NA
LE: 12714 data points (72.57%) set to NA
NEE: 13157 data points (75.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10290 additional data points (58.73%) excluded by precipitation filter (10290
 data points = 58.73 % in total)
10290 data points (58.73%) excluded in total
7230 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12707 data points (72.53%) set to NA
H: 12700 data points (72.49%) set to NA
LE: 12714 data points (72.57%) set to NA
NEE: 13157 data points (75.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -69 ...”
New sEddyProc class for site 'US-PFq'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -69 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 83.99.

Regression of reference temperature R_ref for 13 periods.

[262/329] Processing: US-PFr

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-PFr | Years: 2019
Quality control:
TA: 12213 data points (69.71%) set to NA
H: 12730 data points (72.66%) set to NA
LE: 12780 data points (72.95%) set to NA
NEE: 13285 data points (75.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10290 additional data points (58.73%) excluded by precipitation filter (10290
 data points = 58.73 % in total)
10290 data points (58.73%) excluded in total
7230 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12213 data points (69.71%) set to NA
H: 12730 data points (72.66%) set to NA
LE: 12780 data points (72.95%) set to NA
NEE: 13285 data points (75.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-PFr'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 93.08.

Regression of reference temperature R_ref for 17 periods.

[263/329] Processing: US-PFt

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-PFt | Years: 2019
Quality control:
TA: 12454 data points (71.08%) set to NA
H: 12633 data points (72.11%) set to NA
LE: 12673 data points (72.33%) set to NA
NEE: 12941 data points (73.86%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
10290 additional data points (58.73%) excluded by precipitation filter (10290
 data points = 58.73 % in total)
10290 data points (58.73%) excluded in total
7230 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12454 data points (71.08%) set to NA
H: 12633 data points (72.11%) set to NA
LE: 12673 data points (72.33%) set to NA
NEE: 12941 data points (73.86%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -67 ...”
New sEddyProc class for site 'US-PFt'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -67 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 101.42.

Regression of reference temperature R_ref for 14 periods.

[264/329] Processing: US-PLo

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-PLo | Years: 2022, 2023
Quality control:
TA: 7804 data points (44.54%) set to NA
H: 6689 data points (38.18%) set to NA
LE: 6698 data points (38.23%) set to NA
NEE: 7224 data points (41.23%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 127”

-------------------------------------------------------------------
Data filtering:
13104 data points (74.79%) excluded by growing season filter
2270 additional data points (12.96%) excluded by precipitation filter (8570
 data points = 48.92 % in total)
15374 data points (87.75%) excluded in total
2146 valid data points (12.25%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7804 data points (44.54%) set to NA
H: 6689 data points (38.18%) set to NA
LE: 6698 data points (38.23%) set to NA
NEE: 7224 data points (41.23%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 127”

-------------------------------------------------------------------
Data filtering:
13104 data points (74.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13104 data points (74.79%) excluded in total
4416 valid data points (25.21%) remaining.

New sEddyProc class for site 'US-PLo'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 244.59.

Regression of reference temperature R_ref for 13 periods.

Quality control:
TA: 101 data points (0.58%) set to NA
H: 154 data points (0.88%) set to NA
LE: 156 data points (0.89%) set to NA
NEE: 901 data points (5.14%) set to NA
-------------------------------------------------------------------
Data filtering:
12240 data points (69.86%) excluded by growing season filter
3688 additional data points (21.05%) excluded by precipitation filter (9682
 data points = 55.26 % in total)
15928 data points (90.91%) excluded in total
1592 valid data points (9.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 101 data points (0.58%) set to NA
H: 154 data points (0.88%) set to NA
LE: 156 data points (0.89%) set to NA
NEE: 901 data points (5.14%) set to NA
-------------------------------------------------------------------
Data filtering:
12240 data points (69.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12240 data points (69.86%) excluded in total
5280 valid data points (30.14%) remaining.

New sEddyProc class for site 'US-PLo'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-PLo-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[265/329] Processing: US-Prr

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Prr | Years: 2017, 2018, 2019, 2020, 2021, 2022
Quality control:
TA: 2 data points (0.01%) set to NA
H: 2309 data points (13.18%) set to NA
LE: 3399 data points (19.4%) set to NA
NEE: 3750 data points (21.4%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 33”

-------------------------------------------------------------------
Data filtering:
11280 data points (64.38%) excluded by growing season filter
3080 additional data points (17.58%) excluded by precipitation filter (6307
 data points = 36 % in total)
14360 data points (81.96%) excluded in total
3160 valid data points (18.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2 data points (0.01%) set to NA
H: 2309 data points (13.18%) set to NA
LE: 3399 data points (19.4%) set to NA
NEE: 3750 data points (21.4%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 33”

-------------------------------------------------------------------
Data filtering:
11280 data points (64.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11280 data points (64.38%) excluded in total
6240 valid data points (35.62%) remaining.

New sEddyProc class for site 'US-Prr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Prr-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 7 data points (0.04%) set to NA
H: 62 data points (0.35%) set to NA
LE: 3813 data points (21.76%) set to NA
NEE: 4701 data points (26.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 47”

-------------------------------------------------------------------
Data filtering:
12048 data points (68.77%) excluded by growing season filter
2341 additional data points (13.36%) excluded by precipitation filter (4982
 data points = 28.44 % in total)
14389 data points (82.13%) excluded in total
3131 valid data points (17.87%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7 data points (0.04%) set to NA
H: 62 data points (0.35%) set to NA
LE: 3813 data points (21.76%) set to NA
NEE: 4701 data points (26.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 47”

-------------------------------------------------------------------
Data filtering:
12048 data points (68.77%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12048 data points (68.77%) excluded in total
5472 valid data points (31.23%) remaining.

New sEddyProc class for site 'US-Prr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Prr-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 15 data points (0.09%) set to NA
H: 4564 data points (26.05%) set to NA
LE: 6713 data points (38.32%) set to NA
NEE: 7526 data points (42.96%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 54”

-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
2178 additional data points (12.43%) excluded by precipitation filter (4680
 data points = 26.71 % in total)
13410 data points (76.54%) excluded in total
4110 valid data points (23.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 15 data points (0.09%) set to NA
H: 4564 data points (26.05%) set to NA
LE: 6713 data points (38.32%) set to NA
NEE: 7526 data points (42.96%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 54”

-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11232 data points (64.11%) excluded in total
6288 valid data points (35.89%) remaining.

New sEddyProc class for site 'US-Prr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Prr-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1 data points (0.01%) set to NA
H: 2910 data points (16.56%) set to NA
LE: 4662 data points (26.54%) set to NA
NEE: 5338 data points (30.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 11”

-------------------------------------------------------------------
Data filtering:
11424 data points (65.03%) excluded by growing season filter
2405 additional data points (13.69%) excluded by precipitation filter (5678
 data points = 32.32 % in total)
13829 data points (78.72%) excluded in total
3739 valid data points (21.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1 data points (0.01%) set to NA
H: 2910 data points (16.56%) set to NA
LE: 4662 data points (26.54%) set to NA
NEE: 5338 data points (30.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 11”

-------------------------------------------------------------------
Data filtering:
11424 data points (65.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11424 data points (65.03%) excluded in total
6144 valid data points (34.97%) remaining.

New sEddyProc class for site 'US-Prr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Prr-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 278 data points (1.59%) set to NA
H: 4111 data points (23.46%) set to NA
LE: 4146 data points (23.66%) set to NA
NEE: 4918 data points (28.07%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 50”

-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
2718 additional data points (15.51%) excluded by precipitation filter (5526
 data points = 31.54 % in total)
13518 data points (77.16%) excluded in total
4002 valid data points (22.84%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 278 data points (1.59%) set to NA
H: 4111 data points (23.46%) set to NA
LE: 4146 data points (23.66%) set to NA
NEE: 4918 data points (28.07%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 50”

-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10800 data points (61.64%) excluded in total
6720 valid data points (38.36%) remaining.

New sEddyProc class for site 'US-Prr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Prr-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 425 data points (2.43%) set to NA
H: 2948 data points (16.83%) set to NA
LE: 2989 data points (17.06%) set to NA
NEE: 3570 data points (20.38%) set to NA
-------------------------------------------------------------------
Data filtering:
11568 data points (66.03%) excluded by growing season filter
1929 additional data points (11.01%) excluded by precipitation filter (5212
 data points = 29.75 % in total)
13497 data points (77.04%) excluded in total
4023 valid data points (22.96%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 425 data points (2.43%) set to NA
H: 2948 data points (16.83%) set to NA
LE: 2989 data points (17.06%) set to NA
NEE: 3570 data points (20.38%) set to NA
-------------------------------------------------------------------
Data filtering:
11568 data points (66.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11568 data points (66.03%) excluded in total
5952 valid data points (33.97%) remaining.

New sEddyProc class for site 'US-Prr'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Prr-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[266/329] Processing: US-RRC

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-RRC | Years: 2022, 2023, 2024
Quality control:
TA: 8403 data points (47.96%) set to NA
H: 7958 data points (45.42%) set to NA
LE: 7974 data points (45.51%) set to NA
NEE: 8569 data points (48.91%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 144”

-------------------------------------------------------------------
Data filtering:
3840 data points (21.92%) excluded by growing season filter
4501 additional data points (25.69%) excluded by precipitation filter (5519
 data points = 31.5 % in total)
8341 data points (47.61%) excluded in total
9179 valid data points (52.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8403 data points (47.96%) set to NA
H: 7958 data points (45.42%) set to NA
LE: 7974 data points (45.51%) set to NA
NEE: 8569 data points (48.91%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 144”

-------------------------------------------------------------------
Data filtering:
3840 data points (21.92%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3840 data points (21.92%) excluded in total
13680 valid data points (78.08%) remaining.

New sEddyProc class for site 'US-RRC'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 113.42.

Regression of reference temperature R_ref for 15 periods.

Quality control:
TA: 202 data points (1.15%) set to NA
H: 676 data points (3.86%) set to NA
LE: 970 data points (5.54%) set to NA
NEE: 2246 data points (12.82%) set to NA
-------------------------------------------------------------------
Data filtering:
9648 data points (55.07%) excluded by growing season filter
2348 additional data points (13.4%) excluded by precipitation filter (4969
 data points = 28.36 % in total)
11996 data points (68.47%) excluded in total
5524 valid data points (31.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 202 data points (1.15%) set to NA
H: 676 data points (3.86%) set to NA
LE: 970 data points (5.54%) set to NA
NEE: 2246 data points (12.82%) set to NA
-------------------------------------------------------------------
Data filtering:
9648 data points (55.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9648 data points (55.07%) excluded in total
7872 valid data points (44.93%) remaining.

New sEddyProc class for site 'US-RRC'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-RRC-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3777 data points (21.5%) set to NA
H: 4017 data points (22.87%) set to NA
LE: 4540 data points (25.84%) set to NA
NEE: 5237 data points (29.81%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 49”

-------------------------------------------------------------------
Data filtering:
11040 data points (62.84%) excluded by growing season filter
2118 additional data points (12.06%) excluded by precipitation filter (5483
 data points = 31.21 % in total)
13158 data points (74.9%) excluded in total
4410 valid data points (25.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3777 data points (21.5%) set to NA
H: 4017 data points (22.87%) set to NA
LE: 4540 data points (25.84%) set to NA
NEE: 5237 data points (29.81%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 49”

-------------------------------------------------------------------
Data filtering:
11040 data points (62.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11040 data points (62.84%) excluded in total
6528 valid data points (37.16%) remaining.

New sEddyProc class for site 'US-RRC'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 18 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-RRC-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[267/329] Processing: US-Rls

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Rls | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023
Quality control:
TA: 0 data points (0%) set to NA
H: 107 data points (0.61%) set to NA
LE: 118 data points (0.67%) set to NA
NEE: 1856 data points (10.59%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
2670 additional data points (15.24%) excluded by precipitation filter (8124
 data points = 46.37 % in total)
13470 data points (76.88%) excluded in total
4050 valid data points (23.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 107 data points (0.61%) set to NA
LE: 118 data points (0.67%) set to NA
NEE: 1856 data points (10.59%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10800 data points (61.64%) excluded in total
6720 valid data points (38.36%) remaining.

New sEddyProc class for site 'US-Rls'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rls-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 6 data points (0.03%) set to NA
LE: 13 data points (0.07%) set to NA
NEE: 1208 data points (6.89%) set to NA
-------------------------------------------------------------------
Data filtering:
12816 data points (73.15%) excluded by growing season filter
2186 additional data points (12.48%) excluded by precipitation filter (7428
 data points = 42.4 % in total)
15002 data points (85.63%) excluded in total
2518 valid data points (14.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 6 data points (0.03%) set to NA
LE: 13 data points (0.07%) set to NA
NEE: 1208 data points (6.89%) set to NA
-------------------------------------------------------------------
Data filtering:
12816 data points (73.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12816 data points (73.15%) excluded in total
4704 valid data points (26.85%) remaining.

New sEddyProc class for site 'US-Rls'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rls-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4 data points (0.02%) set to NA
H: 26 data points (0.15%) set to NA
LE: 42 data points (0.24%) set to NA
NEE: 1402 data points (8%) set to NA
-------------------------------------------------------------------
Data filtering:
10416 data points (59.45%) excluded by growing season filter
2898 additional data points (16.54%) excluded by precipitation filter (7820
 data points = 44.63 % in total)
13314 data points (75.99%) excluded in total
4206 valid data points (24.01%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4 data points (0.02%) set to NA
H: 26 data points (0.15%) set to NA
LE: 42 data points (0.24%) set to NA
NEE: 1402 data points (8%) set to NA
-------------------------------------------------------------------
Data filtering:
10416 data points (59.45%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10416 data points (59.45%) excluded in total
7104 valid data points (40.55%) remaining.

New sEddyProc class for site 'US-Rls'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rls-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 84 data points (0.48%) set to NA
H: 94 data points (0.54%) set to NA
LE: 97 data points (0.55%) set to NA
NEE: 2571 data points (14.63%) set to NA
-------------------------------------------------------------------
Data filtering:
8448 data points (48.09%) excluded by growing season filter
3134 additional data points (17.84%) excluded by precipitation filter (7014
 data points = 39.92 % in total)
11582 data points (65.93%) excluded in total
5986 valid data points (34.07%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 84 data points (0.48%) set to NA
H: 94 data points (0.54%) set to NA
LE: 97 data points (0.55%) set to NA
NEE: 2571 data points (14.63%) set to NA
-------------------------------------------------------------------
Data filtering:
8448 data points (48.09%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8448 data points (48.09%) excluded in total
9120 valid data points (51.91%) remaining.

New sEddyProc class for site 'US-Rls'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rls-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 208 data points (1.19%) set to NA
H: 225 data points (1.28%) set to NA
LE: 236 data points (1.35%) set to NA
NEE: 3132 data points (17.88%) set to NA
-------------------------------------------------------------------
Data filtering:
8256 data points (47.12%) excluded by growing season filter
2630 additional data points (15.01%) excluded by precipitation filter (7070
 data points = 40.35 % in total)
10886 data points (62.13%) excluded in total
6634 valid data points (37.87%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 208 data points (1.19%) set to NA
H: 225 data points (1.28%) set to NA
LE: 236 data points (1.35%) set to NA
NEE: 3132 data points (17.88%) set to NA
-------------------------------------------------------------------
Data filtering:
8256 data points (47.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8256 data points (47.12%) excluded in total
9264 valid data points (52.88%) remaining.

New sEddyProc class for site 'US-Rls'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 211.12.

Regression of reference temperature R_ref for 4 periods.

Quality control:
TA: 60 data points (0.34%) set to NA
H: 74 data points (0.42%) set to NA
LE: 80 data points (0.46%) set to NA
NEE: 2609 data points (14.89%) set to NA
-------------------------------------------------------------------
Data filtering:
8064 data points (46.03%) excluded by growing season filter
3990 additional data points (22.77%) excluded by precipitation filter (7148
 data points = 40.8 % in total)
12054 data points (68.8%) excluded in total
5466 valid data points (31.2%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 60 data points (0.34%) set to NA
H: 74 data points (0.42%) set to NA
LE: 80 data points (0.46%) set to NA
NEE: 2609 data points (14.89%) set to NA
-------------------------------------------------------------------
Data filtering:
8064 data points (46.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8064 data points (46.03%) excluded in total
9456 valid data points (53.97%) remaining.

New sEddyProc class for site 'US-Rls'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rls-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4434 data points (25.31%) set to NA
H: 4439 data points (25.34%) set to NA
LE: 4437 data points (25.33%) set to NA
NEE: 5449 data points (31.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 83”

-------------------------------------------------------------------
Data filtering:
11472 data points (65.48%) excluded by growing season filter
2402 additional data points (13.71%) excluded by precipitation filter (7650
 data points = 43.66 % in total)
13874 data points (79.19%) excluded in total
3646 valid data points (20.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4434 data points (25.31%) set to NA
H: 4439 data points (25.34%) set to NA
LE: 4437 data points (25.33%) set to NA
NEE: 5449 data points (31.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 83”

-------------------------------------------------------------------
Data filtering:
11472 data points (65.48%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11472 data points (65.48%) excluded in total
6048 valid data points (34.52%) remaining.

New sEddyProc class for site 'US-Rls'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 64.13.

Regression of reference temperature R_ref for 7 periods.

[268/329] Processing: US-Rms

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Rms | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023
Quality control:
TA: 273 data points (1.56%) set to NA
H: 326 data points (1.86%) set to NA
LE: 341 data points (1.95%) set to NA
NEE: 1719 data points (9.81%) set to NA
-------------------------------------------------------------------
Data filtering:
13392 data points (76.44%) excluded by growing season filter
1262 additional data points (7.2%) excluded by precipitation filter (8514
 data points = 48.6 % in total)
14654 data points (83.64%) excluded in total
2866 valid data points (16.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 273 data points (1.56%) set to NA
H: 326 data points (1.86%) set to NA
LE: 341 data points (1.95%) set to NA
NEE: 1719 data points (9.81%) set to NA
-------------------------------------------------------------------
Data filtering:
13392 data points (76.44%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13392 data points (76.44%) excluded in total
4128 valid data points (23.56%) remaining.

New sEddyProc class for site 'US-Rms'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rms-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 119 data points (0.68%) set to NA
LE: 138 data points (0.79%) set to NA
NEE: 1008 data points (5.75%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
2176 additional data points (12.42%) excluded by precipitation filter (7906
 data points = 45.13 % in total)
13312 data points (75.98%) excluded in total
4208 valid data points (24.02%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 119 data points (0.68%) set to NA
LE: 138 data points (0.79%) set to NA
NEE: 1008 data points (5.75%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11136 data points (63.56%) excluded in total
6384 valid data points (36.44%) remaining.

New sEddyProc class for site 'US-Rms'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rms-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 11 data points (0.06%) set to NA
H: 138 data points (0.79%) set to NA
LE: 161 data points (0.92%) set to NA
NEE: 1399 data points (7.99%) set to NA
-------------------------------------------------------------------
Data filtering:
10320 data points (58.9%) excluded by growing season filter
3192 additional data points (18.22%) excluded by precipitation filter (8790
 data points = 50.17 % in total)
13512 data points (77.12%) excluded in total
4008 valid data points (22.88%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 11 data points (0.06%) set to NA
H: 138 data points (0.79%) set to NA
LE: 161 data points (0.92%) set to NA
NEE: 1399 data points (7.99%) set to NA
-------------------------------------------------------------------
Data filtering:
10320 data points (58.9%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10320 data points (58.9%) excluded in total
7200 valid data points (41.1%) remaining.

New sEddyProc class for site 'US-Rms'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rms-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 39 data points (0.22%) set to NA
LE: 44 data points (0.25%) set to NA
NEE: 1176 data points (6.69%) set to NA
-------------------------------------------------------------------
Data filtering:
10608 data points (60.38%) excluded by growing season filter
2422 additional data points (13.79%) excluded by precipitation filter (7542
 data points = 42.93 % in total)
13030 data points (74.17%) excluded in total
4538 valid data points (25.83%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 39 data points (0.22%) set to NA
LE: 44 data points (0.25%) set to NA
NEE: 1176 data points (6.69%) set to NA
-------------------------------------------------------------------
Data filtering:
10608 data points (60.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10608 data points (60.38%) excluded in total
6960 valid data points (39.62%) remaining.

New sEddyProc class for site 'US-Rms'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rms-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 74 data points (0.42%) set to NA
LE: 100 data points (0.57%) set to NA
NEE: 1638 data points (9.35%) set to NA
-------------------------------------------------------------------
Data filtering:
11040 data points (63.01%) excluded by growing season filter
2006 additional data points (11.45%) excluded by precipitation filter (7416
 data points = 42.33 % in total)
13046 data points (74.46%) excluded in total
4474 valid data points (25.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 74 data points (0.42%) set to NA
LE: 100 data points (0.57%) set to NA
NEE: 1638 data points (9.35%) set to NA
-------------------------------------------------------------------
Data filtering:
11040 data points (63.01%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11040 data points (63.01%) excluded in total
6480 valid data points (36.99%) remaining.

New sEddyProc class for site 'US-Rms'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rms-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 76 data points (0.43%) set to NA
LE: 149 data points (0.85%) set to NA
NEE: 1228 data points (7.01%) set to NA
-------------------------------------------------------------------
Data filtering:
11616 data points (66.3%) excluded by growing season filter
2070 additional data points (11.82%) excluded by precipitation filter (7508
 data points = 42.85 % in total)
13686 data points (78.12%) excluded in total
3834 valid data points (21.88%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 76 data points (0.43%) set to NA
LE: 149 data points (0.85%) set to NA
NEE: 1228 data points (7.01%) set to NA
-------------------------------------------------------------------
Data filtering:
11616 data points (66.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11616 data points (66.3%) excluded in total
5904 valid data points (33.7%) remaining.

New sEddyProc class for site 'US-Rms'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rms-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4403 data points (25.13%) set to NA
H: 4440 data points (25.34%) set to NA
LE: 4453 data points (25.42%) set to NA
NEE: 5231 data points (29.86%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 83”

-------------------------------------------------------------------
Data filtering:
11280 data points (64.38%) excluded by growing season filter
2626 additional data points (14.99%) excluded by precipitation filter (8308
 data points = 47.42 % in total)
13906 data points (79.37%) excluded in total
3614 valid data points (20.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4403 data points (25.13%) set to NA
H: 4440 data points (25.34%) set to NA
LE: 4453 data points (25.42%) set to NA
NEE: 5231 data points (29.86%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 83”

-------------------------------------------------------------------
Data filtering:
11280 data points (64.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11280 data points (64.38%) excluded in total
6240 valid data points (35.62%) remaining.

New sEddyProc class for site 'US-Rms'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 91.9.

Regression of reference temperature R_ref for 5 periods.

[269/329] Processing: US-Rpf

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Rpf | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 38 data points (0.22%) set to NA
H: 628 data points (3.58%) set to NA
LE: 2959 data points (16.89%) set to NA
NEE: 4495 data points (25.66%) set to NA
-------------------------------------------------------------------
Data filtering:
12288 data points (70.14%) excluded by growing season filter
2647 additional data points (15.11%) excluded by precipitation filter (4191
 data points = 23.92 % in total)
14935 data points (85.25%) excluded in total
2585 valid data points (14.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 38 data points (0.22%) set to NA
H: 628 data points (3.58%) set to NA
LE: 2959 data points (16.89%) set to NA
NEE: 4495 data points (25.66%) set to NA
-------------------------------------------------------------------
Data filtering:
12288 data points (70.14%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12288 data points (70.14%) excluded in total
5232 valid data points (29.86%) remaining.

New sEddyProc class for site 'US-Rpf'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rpf-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 503 data points (2.87%) set to NA
H: 554 data points (3.16%) set to NA
LE: 1647 data points (9.4%) set to NA
NEE: 4716 data points (26.92%) set to NA
-------------------------------------------------------------------
Data filtering:
12576 data points (71.78%) excluded by growing season filter
2285 additional data points (13.04%) excluded by precipitation filter (3879
 data points = 22.14 % in total)
14861 data points (84.82%) excluded in total
2659 valid data points (15.18%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 503 data points (2.87%) set to NA
H: 554 data points (3.16%) set to NA
LE: 1647 data points (9.4%) set to NA
NEE: 4716 data points (26.92%) set to NA
-------------------------------------------------------------------
Data filtering:
12576 data points (71.78%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12576 data points (71.78%) excluded in total
4944 valid data points (28.22%) remaining.

New sEddyProc class for site 'US-Rpf'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rpf-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2045 data points (11.67%) set to NA
H: 19 data points (0.11%) set to NA
LE: 581 data points (3.32%) set to NA
NEE: 2277 data points (13%) set to NA
-------------------------------------------------------------------
Data filtering:
12048 data points (68.77%) excluded by growing season filter
2067 additional data points (11.8%) excluded by precipitation filter (4075
 data points = 23.26 % in total)
14115 data points (80.57%) excluded in total
3405 valid data points (19.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2045 data points (11.67%) set to NA
H: 19 data points (0.11%) set to NA
LE: 581 data points (3.32%) set to NA
NEE: 2277 data points (13%) set to NA
-------------------------------------------------------------------
Data filtering:
12048 data points (68.77%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12048 data points (68.77%) excluded in total
5472 valid data points (31.23%) remaining.

New sEddyProc class for site 'US-Rpf'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 81.24.

Regression of reference temperature R_ref for 12 periods.

Quality control:
TA: 3373 data points (19.2%) set to NA
H: 3479 data points (19.8%) set to NA
LE: 3743 data points (21.31%) set to NA
NEE: 5640 data points (32.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 25”

-------------------------------------------------------------------
Data filtering:
11952 data points (68.03%) excluded by growing season filter
2998 additional data points (17.07%) excluded by precipitation filter (4320
 data points = 24.59 % in total)
14950 data points (85.1%) excluded in total
2618 valid data points (14.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3373 data points (19.2%) set to NA
H: 3479 data points (19.8%) set to NA
LE: 3743 data points (21.31%) set to NA
NEE: 5640 data points (32.1%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 25”

-------------------------------------------------------------------
Data filtering:
11952 data points (68.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11952 data points (68.03%) excluded in total
5616 valid data points (31.97%) remaining.

New sEddyProc class for site 'US-Rpf'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 126.59.

Regression of reference temperature R_ref for 20 periods.

Quality control:
TA: 6276 data points (35.82%) set to NA
H: 5825 data points (33.25%) set to NA
LE: 6579 data points (37.55%) set to NA
NEE: 8099 data points (46.23%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 57”

-------------------------------------------------------------------
Data filtering:
13296 data points (75.89%) excluded by growing season filter
1357 additional data points (7.75%) excluded by precipitation filter (3653
 data points = 20.85 % in total)
14653 data points (83.64%) excluded in total
2867 valid data points (16.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6276 data points (35.82%) set to NA
H: 5825 data points (33.25%) set to NA
LE: 6579 data points (37.55%) set to NA
NEE: 8099 data points (46.23%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 57”

-------------------------------------------------------------------
Data filtering:
13296 data points (75.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13296 data points (75.89%) excluded in total
4224 valid data points (24.11%) remaining.

New sEddyProc class for site 'US-Rpf'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 92.64.

Regression of reference temperature R_ref for 27 periods.

Quality control:
TA: 706 data points (4.03%) set to NA
H: 731 data points (4.17%) set to NA
LE: 1467 data points (8.37%) set to NA
NEE: 3094 data points (17.66%) set to NA
-------------------------------------------------------------------
Data filtering:
12432 data points (70.96%) excluded by growing season filter
1846 additional data points (10.54%) excluded by precipitation filter (3555
 data points = 20.29 % in total)
14278 data points (81.5%) excluded in total
3242 valid data points (18.5%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 706 data points (4.03%) set to NA
H: 731 data points (4.17%) set to NA
LE: 1467 data points (8.37%) set to NA
NEE: 3094 data points (17.66%) set to NA
-------------------------------------------------------------------
Data filtering:
12432 data points (70.96%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12432 data points (70.96%) excluded in total
5088 valid data points (29.04%) remaining.

New sEddyProc class for site 'US-Rpf'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rpf-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4473 data points (25.53%) set to NA
H: 2234 data points (12.75%) set to NA
LE: 2346 data points (13.39%) set to NA
NEE: 4249 data points (24.25%) set to NA
-------------------------------------------------------------------
Data filtering:
12720 data points (72.6%) excluded by growing season filter
2341 additional data points (13.36%) excluded by precipitation filter (4069
 data points = 23.22 % in total)
15061 data points (85.96%) excluded in total
2459 valid data points (14.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4473 data points (25.53%) set to NA
H: 2234 data points (12.75%) set to NA
LE: 2346 data points (13.39%) set to NA
NEE: 4249 data points (24.25%) set to NA
-------------------------------------------------------------------
Data filtering:
12720 data points (72.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12720 data points (72.6%) excluded in total
4800 valid data points (27.4%) remaining.

New sEddyProc class for site 'US-Rpf'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 16 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rpf-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 7599 data points (43.25%) set to NA
H: 30 data points (0.17%) set to NA
LE: 3744 data points (21.31%) set to NA
NEE: 2710 data points (15.43%) set to NA
-------------------------------------------------------------------
Data filtering:
12336 data points (70.22%) excluded by growing season filter
2447 additional data points (13.93%) excluded by precipitation filter (5675
 data points = 32.3 % in total)
14783 data points (84.15%) excluded in total
2785 valid data points (15.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7599 data points (43.25%) set to NA
H: 30 data points (0.17%) set to NA
LE: 3744 data points (21.31%) set to NA
NEE: 2710 data points (15.43%) set to NA
-------------------------------------------------------------------
Data filtering:
12336 data points (70.22%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12336 data points (70.22%) excluded in total
5232 valid data points (29.78%) remaining.

New sEddyProc class for site 'US-Rpf'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rpf-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[270/329] Processing: US-Rwf

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Rwf | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023
Quality control:
TA: 3199 data points (18.26%) set to NA
H: 2637 data points (15.05%) set to NA
LE: 2683 data points (15.31%) set to NA
NEE: 4389 data points (25.05%) set to NA
-------------------------------------------------------------------
Data filtering:
13056 data points (74.52%) excluded by growing season filter
1580 additional data points (9.02%) excluded by precipitation filter (8514
 data points = 48.6 % in total)
14636 data points (83.54%) excluded in total
2884 valid data points (16.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3199 data points (18.26%) set to NA
H: 2637 data points (15.05%) set to NA
LE: 2683 data points (15.31%) set to NA
NEE: 4389 data points (25.05%) set to NA
-------------------------------------------------------------------
Data filtering:
13056 data points (74.52%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13056 data points (74.52%) excluded in total
4464 valid data points (25.48%) remaining.

New sEddyProc class for site 'US-Rwf'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 110.75.

Regression of reference temperature R_ref for 20 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 269 data points (1.54%) set to NA
LE: 272 data points (1.55%) set to NA
NEE: 1922 data points (10.97%) set to NA
-------------------------------------------------------------------
Data filtering:
11616 data points (66.3%) excluded by growing season filter
2274 additional data points (12.98%) excluded by precipitation filter (7906
 data points = 45.13 % in total)
13890 data points (79.28%) excluded in total
3630 valid data points (20.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 269 data points (1.54%) set to NA
LE: 272 data points (1.55%) set to NA
NEE: 1922 data points (10.97%) set to NA
-------------------------------------------------------------------
Data filtering:
11616 data points (66.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11616 data points (66.3%) excluded in total
5904 valid data points (33.7%) remaining.

New sEddyProc class for site 'US-Rwf'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rwf-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 633 data points (3.61%) set to NA
LE: 675 data points (3.85%) set to NA
NEE: 2665 data points (15.21%) set to NA
-------------------------------------------------------------------
Data filtering:
11760 data points (67.12%) excluded by growing season filter
2490 additional data points (14.21%) excluded by precipitation filter (8790
 data points = 50.17 % in total)
14250 data points (81.34%) excluded in total
3270 valid data points (18.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 633 data points (3.61%) set to NA
LE: 675 data points (3.85%) set to NA
NEE: 2665 data points (15.21%) set to NA
-------------------------------------------------------------------
Data filtering:
11760 data points (67.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11760 data points (67.12%) excluded in total
5760 valid data points (32.88%) remaining.

New sEddyProc class for site 'US-Rwf'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rwf-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3 data points (0.02%) set to NA
H: 62 data points (0.35%) set to NA
LE: 76 data points (0.43%) set to NA
NEE: 1618 data points (9.21%) set to NA
-------------------------------------------------------------------
Data filtering:
11232 data points (63.93%) excluded by growing season filter
2388 additional data points (13.59%) excluded by precipitation filter (7542
 data points = 42.93 % in total)
13620 data points (77.53%) excluded in total
3948 valid data points (22.47%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3 data points (0.02%) set to NA
H: 62 data points (0.35%) set to NA
LE: 76 data points (0.43%) set to NA
NEE: 1618 data points (9.21%) set to NA
-------------------------------------------------------------------
Data filtering:
11232 data points (63.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11232 data points (63.93%) excluded in total
6336 valid data points (36.07%) remaining.

New sEddyProc class for site 'US-Rwf'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rwf-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 12 data points (0.07%) set to NA
H: 26 data points (0.15%) set to NA
LE: 27 data points (0.15%) set to NA
NEE: 2008 data points (11.46%) set to NA
-------------------------------------------------------------------
Data filtering:
11568 data points (66.03%) excluded by growing season filter
1960 additional data points (11.19%) excluded by precipitation filter (7416
 data points = 42.33 % in total)
13528 data points (77.21%) excluded in total
3992 valid data points (22.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12 data points (0.07%) set to NA
H: 26 data points (0.15%) set to NA
LE: 27 data points (0.15%) set to NA
NEE: 2008 data points (11.46%) set to NA
-------------------------------------------------------------------
Data filtering:
11568 data points (66.03%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11568 data points (66.03%) excluded in total
5952 valid data points (33.97%) remaining.

New sEddyProc class for site 'US-Rwf'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rwf-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3 data points (0.02%) set to NA
H: 30 data points (0.17%) set to NA
LE: 33 data points (0.19%) set to NA
NEE: 1285 data points (7.33%) set to NA
-------------------------------------------------------------------
Data filtering:
11616 data points (66.3%) excluded by growing season filter
2112 additional data points (12.05%) excluded by precipitation filter (7508
 data points = 42.85 % in total)
13728 data points (78.36%) excluded in total
3792 valid data points (21.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3 data points (0.02%) set to NA
H: 30 data points (0.17%) set to NA
LE: 33 data points (0.19%) set to NA
NEE: 1285 data points (7.33%) set to NA
-------------------------------------------------------------------
Data filtering:
11616 data points (66.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11616 data points (66.3%) excluded in total
5904 valid data points (33.7%) remaining.

New sEddyProc class for site 'US-Rwf'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rwf-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4412 data points (25.18%) set to NA
H: 4422 data points (25.24%) set to NA
LE: 4420 data points (25.23%) set to NA
NEE: 5014 data points (28.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 83”

-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
2854 additional data points (16.29%) excluded by precipitation filter (8308
 data points = 47.42 % in total)
14086 data points (80.4%) excluded in total
3434 valid data points (19.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4412 data points (25.18%) set to NA
H: 4422 data points (25.24%) set to NA
LE: 4420 data points (25.23%) set to NA
NEE: 5014 data points (28.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 83”

-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11232 data points (64.11%) excluded in total
6288 valid data points (35.89%) remaining.

New sEddyProc class for site 'US-Rwf'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 85.86.

Regression of reference temperature R_ref for 7 periods.

[271/329] Processing: US-Rws

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Rws | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023
Quality control:
TA: 3 data points (0.02%) set to NA
H: 30 data points (0.17%) set to NA
LE: 62 data points (0.35%) set to NA
NEE: 213 data points (1.22%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.19%) excluded by growing season filter
2852 additional data points (16.28%) excluded by precipitation filter (8124
 data points = 46.37 % in total)
13748 data points (78.47%) excluded in total
3772 valid data points (21.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3 data points (0.02%) set to NA
H: 30 data points (0.17%) set to NA
LE: 62 data points (0.35%) set to NA
NEE: 213 data points (1.22%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10896 data points (62.19%) excluded in total
6624 valid data points (37.81%) remaining.

New sEddyProc class for site 'US-Rws'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rws-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 17 data points (0.1%) set to NA
LE: 63 data points (0.36%) set to NA
NEE: 182 data points (1.04%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
3428 additional data points (19.57%) excluded by precipitation filter (7428
 data points = 42.4 % in total)
14228 data points (81.21%) excluded in total
3292 valid data points (18.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 17 data points (0.1%) set to NA
LE: 63 data points (0.36%) set to NA
NEE: 182 data points (1.04%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10800 data points (61.64%) excluded in total
6720 valid data points (38.36%) remaining.

New sEddyProc class for site 'US-Rws'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rws-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 64 data points (0.37%) set to NA
H: 81 data points (0.46%) set to NA
LE: 328 data points (1.87%) set to NA
NEE: 445 data points (2.54%) set to NA
-------------------------------------------------------------------
Data filtering:
12384 data points (70.68%) excluded by growing season filter
2722 additional data points (15.54%) excluded by precipitation filter (7820
 data points = 44.63 % in total)
15106 data points (86.22%) excluded in total
2414 valid data points (13.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 64 data points (0.37%) set to NA
H: 81 data points (0.46%) set to NA
LE: 328 data points (1.87%) set to NA
NEE: 445 data points (2.54%) set to NA
-------------------------------------------------------------------
Data filtering:
12384 data points (70.68%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12384 data points (70.68%) excluded in total
5136 valid data points (29.32%) remaining.

New sEddyProc class for site 'US-Rws'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rws-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6 data points (0.03%) set to NA
H: 36 data points (0.2%) set to NA
LE: 129 data points (0.73%) set to NA
NEE: 326 data points (1.86%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.72%) excluded by growing season filter
3640 additional data points (20.72%) excluded by precipitation filter (7014
 data points = 39.92 % in total)
11848 data points (67.44%) excluded in total
5720 valid data points (32.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6 data points (0.03%) set to NA
H: 36 data points (0.2%) set to NA
LE: 129 data points (0.73%) set to NA
NEE: 326 data points (1.86%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.72%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8208 data points (46.72%) excluded in total
9360 valid data points (53.28%) remaining.

New sEddyProc class for site 'US-Rws'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rws-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 17 data points (0.1%) set to NA
H: 25 data points (0.14%) set to NA
LE: 54 data points (0.31%) set to NA
NEE: 94 data points (0.54%) set to NA
-------------------------------------------------------------------
Data filtering:
7200 data points (41.1%) excluded by growing season filter
3042 additional data points (17.36%) excluded by precipitation filter (7070
 data points = 40.35 % in total)
10242 data points (58.46%) excluded in total
7278 valid data points (41.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 17 data points (0.1%) set to NA
H: 25 data points (0.14%) set to NA
LE: 54 data points (0.31%) set to NA
NEE: 94 data points (0.54%) set to NA
-------------------------------------------------------------------
Data filtering:
7200 data points (41.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7200 data points (41.1%) excluded in total
10320 valid data points (58.9%) remaining.

New sEddyProc class for site 'US-Rws'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rws-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 38 data points (0.22%) set to NA
H: 68 data points (0.39%) set to NA
LE: 75 data points (0.43%) set to NA
NEE: 145 data points (0.83%) set to NA
-------------------------------------------------------------------
Data filtering:
6336 data points (36.16%) excluded by growing season filter
4418 additional data points (25.22%) excluded by precipitation filter (7148
 data points = 40.8 % in total)
10754 data points (61.38%) excluded in total
6766 valid data points (38.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 38 data points (0.22%) set to NA
H: 68 data points (0.39%) set to NA
LE: 75 data points (0.43%) set to NA
NEE: 145 data points (0.83%) set to NA
-------------------------------------------------------------------
Data filtering:
6336 data points (36.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6336 data points (36.16%) excluded in total
11184 valid data points (63.84%) remaining.

New sEddyProc class for site 'US-Rws'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Rws-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4406 data points (25.15%) set to NA
H: 4416 data points (25.21%) set to NA
LE: 4418 data points (25.22%) set to NA
NEE: 4446 data points (25.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 82”

-------------------------------------------------------------------
Data filtering:
9312 data points (53.15%) excluded by growing season filter
3282 additional data points (18.73%) excluded by precipitation filter (7650
 data points = 43.66 % in total)
12594 data points (71.88%) excluded in total
4926 valid data points (28.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4406 data points (25.15%) set to NA
H: 4416 data points (25.21%) set to NA
LE: 4418 data points (25.22%) set to NA
NEE: 4446 data points (25.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 82”

-------------------------------------------------------------------
Data filtering:
9312 data points (53.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9312 data points (53.15%) excluded in total
8208 valid data points (46.85%) remaining.

New sEddyProc class for site 'US-Rws'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 61.14.

Regression of reference temperature R_ref for 6 periods.

[272/329] Processing: US-SHC

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-SHC | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 8199 data points (46.8%) set to NA
H: 8230 data points (46.97%) set to NA
LE: 8240 data points (47.03%) set to NA
NEE: 8587 data points (49.01%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 161”

-------------------------------------------------------------------
Data filtering:
3168 data points (18.08%) excluded by growing season filter
4487 additional data points (25.61%) excluded by precipitation filter (5659
 data points = 32.3 % in total)
7655 data points (43.69%) excluded in total
9865 valid data points (56.31%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8199 data points (46.8%) set to NA
H: 8230 data points (46.97%) set to NA
LE: 8240 data points (47.03%) set to NA
NEE: 8587 data points (49.01%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 161”

-------------------------------------------------------------------
Data filtering:
3168 data points (18.08%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3168 data points (18.08%) excluded in total
14352 valid data points (81.92%) remaining.

New sEddyProc class for site 'US-SHC'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SHC-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 100 data points (0.57%) set to NA
H: 352 data points (2.01%) set to NA
LE: 399 data points (2.28%) set to NA
NEE: 1454 data points (8.3%) set to NA
-------------------------------------------------------------------
Data filtering:
7104 data points (40.55%) excluded by growing season filter
1517 additional data points (8.66%) excluded by precipitation filter (4802
 data points = 27.41 % in total)
8621 data points (49.21%) excluded in total
8899 valid data points (50.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 100 data points (0.57%) set to NA
H: 352 data points (2.01%) set to NA
LE: 399 data points (2.28%) set to NA
NEE: 1454 data points (8.3%) set to NA
-------------------------------------------------------------------
Data filtering:
7104 data points (40.55%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7104 data points (40.55%) excluded in total
10416 valid data points (59.45%) remaining.

New sEddyProc class for site 'US-SHC'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SHC-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 129 data points (0.74%) set to NA
LE: 133 data points (0.76%) set to NA
NEE: 1445 data points (8.25%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.4%) excluded by growing season filter
1906 additional data points (10.88%) excluded by precipitation filter (6131
 data points = 34.99 % in total)
10210 data points (58.28%) excluded in total
7310 valid data points (41.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 129 data points (0.74%) set to NA
LE: 133 data points (0.76%) set to NA
NEE: 1445 data points (8.25%) set to NA
-------------------------------------------------------------------
Data filtering:
8304 data points (47.4%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8304 data points (47.4%) excluded in total
9216 valid data points (52.6%) remaining.

New sEddyProc class for site 'US-SHC'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SHC-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4404 data points (25.07%) set to NA
H: 4464 data points (25.41%) set to NA
LE: 4466 data points (25.42%) set to NA
NEE: 5240 data points (29.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 82”

-------------------------------------------------------------------
Data filtering:
4896 data points (27.87%) excluded by growing season filter
1789 additional data points (10.18%) excluded by precipitation filter (3602
 data points = 20.5 % in total)
6685 data points (38.05%) excluded in total
10883 valid data points (61.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4404 data points (25.07%) set to NA
H: 4464 data points (25.41%) set to NA
LE: 4466 data points (25.42%) set to NA
NEE: 5240 data points (29.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 82”

-------------------------------------------------------------------
Data filtering:
4896 data points (27.87%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4896 data points (27.87%) excluded in total
12672 valid data points (72.13%) remaining.

New sEddyProc class for site 'US-SHC'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 157.28.

Regression of reference temperature R_ref for 6 periods.

[273/329] Processing: US-SP1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-SP1 | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 1325 data points (7.56%) set to NA
H: 1139 data points (6.5%) set to NA
LE: 1153 data points (6.58%) set to NA
NEE: 1851 data points (10.57%) set to NA
-------------------------------------------------------------------
Data filtering:
384 data points (2.19%) excluded by growing season filter
5696 additional data points (32.51%) excluded by precipitation filter (5863
 data points = 33.46 % in total)
6080 data points (34.7%) excluded in total
11440 valid data points (65.3%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.

Warning message in nlrob(Gs ~ g0 + DwDc * (1 + g1/sqrt(VPD)) * GPP/Ca, data = df, :
“failed to converge in 20 steps”

Quality control:
TA: 1325 data points (7.56%) set to NA
H: 1139 data points (6.5%) set to NA
LE: 1153 data points (6.58%) set to NA
NEE: 1851 data points (10.57%) set to NA
-------------------------------------------------------------------
Data filtering:
384 data points (2.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
384 data points (2.19%) excluded in total
17136 valid data points (97.81%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -76, -52, -64, -54, -77, -61, -70, -66 ...”
New sEddyProc class for site 'US-SP1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 8 cases! Invalid values with 'NEE < -50': -76, -52, -64, -54, -77, -61, -70, -66 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 12 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SP1-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 233 data points (1.33%) set to NA
H: 2 data points (0.01%) set to NA
LE: 65 data points (0.37%) set to NA
NEE: 552 data points (3.15%) set to NA
-------------------------------------------------------------------
Data filtering:
2400 data points (13.7%) excluded by growing season filter
5164 additional data points (29.47%) excluded by precipitation filter (6666
 data points = 38.05 % in total)
7564 data points (43.17%) excluded in total
9956 valid data points (56.83%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 233 data points (1.33%) set to NA
H: 2 data points (0.01%) set to NA
LE: 65 data points (0.37%) set to NA
NEE: 552 data points (3.15%) set to NA
-------------------------------------------------------------------
Data filtering:
2400 data points (13.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
2400 data points (13.7%) excluded in total
15120 valid data points (86.3%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 22 cases! Invalid values with 'NEE < -50': -58, -58, -74, -52, -58, -71, -50, -55, -61, -71, -56, -70, -56, -53, -53, -70, -51, -51, -50, -74, -60, -51 ...”
New sEddyProc class for site 'US-SP1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 22 cases! Invalid values with 'NEE < -50': -58, -58, -74, -52, -58, -71, -50, -55, -61, -71, -56, -70, -56, -53, -53, -70, -51, -51, -50, -74, -60, -51 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SP1-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 948 data points (5.41%) set to NA
H: 1530 data points (8.73%) set to NA
LE: 1823 data points (10.41%) set to NA
NEE: 1911 data points (10.91%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6283 additional data points (35.86%) excluded by precipitation filter (6283
 data points = 35.86 % in total)
6283 data points (35.86%) excluded in total
11237 valid data points (64.14%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 948 data points (5.41%) set to NA
H: 1530 data points (8.73%) set to NA
LE: 1823 data points (10.41%) set to NA
NEE: 1911 data points (10.91%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 14 cases! Invalid values with 'NEE < -50': -51, -63, -55, -51, -63, -59, -59, -64, -55, -61, -63, -60, -54, -52 ...”
New sEddyProc class for site 'US-SP1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 14 cases! Invalid values with 'NEE < -50': -51, -63, -55, -51, -63, -59, -59, -64, -55, -61, -63, -60, -54, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SP1-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 39 data points (0.22%) set to NA
H: 44 data points (0.25%) set to NA
LE: 165 data points (0.94%) set to NA
NEE: 7513 data points (42.77%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 61”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6154 additional data points (35.03%) excluded by precipitation filter (6154
 data points = 35.03 % in total)
6154 data points (35.03%) excluded in total
11414 valid data points (64.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 39 data points (0.22%) set to NA
H: 44 data points (0.25%) set to NA
LE: 165 data points (0.94%) set to NA
NEE: 7513 data points (42.77%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 61”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -60, -66, -71, -57, -64, -73, -73 ...”
New sEddyProc class for site 'US-SP1'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 7 cases! Invalid values with 'NEE < -50': -60, -66, -71, -57, -64, -73, -73 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SP1-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[274/329] Processing: US-SRM

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-SRM | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 28 data points (0.16%) set to NA
H: 36 data points (0.21%) set to NA
LE: 50 data points (0.29%) set to NA
NEE: 534 data points (3.05%) set to NA
-------------------------------------------------------------------
Data filtering:
14880 data points (84.93%) excluded by growing season filter
906 additional data points (5.17%) excluded by precipitation filter (2596
 data points = 14.82 % in total)
15786 data points (90.1%) excluded in total
1734 valid data points (9.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 28 data points (0.16%) set to NA
H: 36 data points (0.21%) set to NA
LE: 50 data points (0.29%) set to NA
NEE: 534 data points (3.05%) set to NA
-------------------------------------------------------------------
Data filtering:
14880 data points (84.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14880 data points (84.93%) excluded in total
2640 valid data points (15.07%) remaining.

New sEddyProc class for site 'US-SRM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SRM-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 12 data points (0.07%) set to NA
LE: 19 data points (0.11%) set to NA
NEE: 586 data points (3.34%) set to NA
-------------------------------------------------------------------
Data filtering:
11040 data points (63.01%) excluded by growing season filter
1983 additional data points (11.32%) excluded by precipitation filter (3068
 data points = 17.51 % in total)
13023 data points (74.33%) excluded in total
4497 valid data points (25.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 12 data points (0.07%) set to NA
LE: 19 data points (0.11%) set to NA
NEE: 586 data points (3.34%) set to NA
-------------------------------------------------------------------
Data filtering:
11040 data points (63.01%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11040 data points (63.01%) excluded in total
6480 valid data points (36.99%) remaining.

New sEddyProc class for site 'US-SRM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SRM-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 28 data points (0.16%) set to NA
H: 35 data points (0.2%) set to NA
LE: 59 data points (0.34%) set to NA
NEE: 1072 data points (6.12%) set to NA
-------------------------------------------------------------------
Data filtering:
8784 data points (50.14%) excluded by growing season filter
1411 additional data points (8.05%) excluded by precipitation filter (3424
 data points = 19.54 % in total)
10195 data points (58.19%) excluded in total
7325 valid data points (41.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 28 data points (0.16%) set to NA
H: 35 data points (0.2%) set to NA
LE: 59 data points (0.34%) set to NA
NEE: 1072 data points (6.12%) set to NA
-------------------------------------------------------------------
Data filtering:
8784 data points (50.14%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8784 data points (50.14%) excluded in total
8736 valid data points (49.86%) remaining.

New sEddyProc class for site 'US-SRM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SRM-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 57 data points (0.32%) set to NA
H: 26 data points (0.15%) set to NA
LE: 107 data points (0.61%) set to NA
NEE: 854 data points (4.86%) set to NA
-------------------------------------------------------------------
Data filtering:
7872 data points (44.81%) excluded by growing season filter
1226 additional data points (6.98%) excluded by precipitation filter (2024
 data points = 11.52 % in total)
9098 data points (51.79%) excluded in total
8470 valid data points (48.21%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 57 data points (0.32%) set to NA
H: 26 data points (0.15%) set to NA
LE: 107 data points (0.61%) set to NA
NEE: 854 data points (4.86%) set to NA
-------------------------------------------------------------------
Data filtering:
7872 data points (44.81%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7872 data points (44.81%) excluded in total
9696 valid data points (55.19%) remaining.

New sEddyProc class for site 'US-SRM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SRM-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 9 data points (0.05%) set to NA
NEE: 890 data points (5.08%) set to NA
-------------------------------------------------------------------
Data filtering:
13824 data points (78.9%) excluded by growing season filter
1184 additional data points (6.76%) excluded by precipitation filter (2815
 data points = 16.07 % in total)
15008 data points (85.66%) excluded in total
2512 valid data points (14.34%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 9 data points (0.05%) set to NA
NEE: 890 data points (5.08%) set to NA
-------------------------------------------------------------------
Data filtering:
13824 data points (78.9%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13824 data points (78.9%) excluded in total
3696 valid data points (21.1%) remaining.

New sEddyProc class for site 'US-SRM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SRM-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 30 data points (0.17%) set to NA
LE: 36 data points (0.21%) set to NA
NEE: 634 data points (3.62%) set to NA
-------------------------------------------------------------------
Data filtering:
13104 data points (74.79%) excluded by growing season filter
1847 additional data points (10.54%) excluded by precipitation filter (3511
 data points = 20.04 % in total)
14951 data points (85.34%) excluded in total
2569 valid data points (14.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 30 data points (0.17%) set to NA
LE: 36 data points (0.21%) set to NA
NEE: 634 data points (3.62%) set to NA
-------------------------------------------------------------------
Data filtering:
13104 data points (74.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13104 data points (74.79%) excluded in total
4416 valid data points (25.21%) remaining.

New sEddyProc class for site 'US-SRM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SRM-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1633 data points (9.32%) set to NA
H: 1636 data points (9.34%) set to NA
LE: 1644 data points (9.38%) set to NA
NEE: 2047 data points (11.68%) set to NA
-------------------------------------------------------------------
Data filtering:
13392 data points (76.44%) excluded by growing season filter
1364 additional data points (7.79%) excluded by precipitation filter (2657
 data points = 15.17 % in total)
14756 data points (84.22%) excluded in total
2764 valid data points (15.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1633 data points (9.32%) set to NA
H: 1636 data points (9.34%) set to NA
LE: 1644 data points (9.38%) set to NA
NEE: 2047 data points (11.68%) set to NA
-------------------------------------------------------------------
Data filtering:
13392 data points (76.44%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13392 data points (76.44%) excluded in total
4128 valid data points (23.56%) remaining.

New sEddyProc class for site 'US-SRM'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 57.98.

Regression of reference temperature R_ref for 10 periods.

Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 22 data points (0.13%) set to NA
NEE: 336 data points (1.91%) set to NA
-------------------------------------------------------------------
Data filtering:
10320 data points (58.74%) excluded by growing season filter
2213 additional data points (12.6%) excluded by precipitation filter (3032
 data points = 17.26 % in total)
12533 data points (71.34%) excluded in total
5035 valid data points (28.66%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 22 data points (0.13%) set to NA
NEE: 336 data points (1.91%) set to NA
-------------------------------------------------------------------
Data filtering:
10320 data points (58.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10320 data points (58.74%) excluded in total
7248 valid data points (41.26%) remaining.

New sEddyProc class for site 'US-SRM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SRM-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 27 data points (0.15%) set to NA
LE: 41 data points (0.23%) set to NA
NEE: 255 data points (1.46%) set to NA
-------------------------------------------------------------------
Data filtering:
12144 data points (69.32%) excluded by growing season filter
1046 additional data points (5.97%) excluded by precipitation filter (2088
 data points = 11.92 % in total)
13190 data points (75.29%) excluded in total
4330 valid data points (24.71%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 27 data points (0.15%) set to NA
LE: 41 data points (0.23%) set to NA
NEE: 255 data points (1.46%) set to NA
-------------------------------------------------------------------
Data filtering:
12144 data points (69.32%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12144 data points (69.32%) excluded in total
5376 valid data points (30.68%) remaining.

New sEddyProc class for site 'US-SRM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SRM-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[275/329] Processing: US-SRS

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-SRS | Years: 2017, 2018
Quality control:
TA: 0 data points (0%) set to NA
H: 1521 data points (8.68%) set to NA
LE: 1533 data points (8.75%) set to NA
NEE: 2714 data points (15.49%) set to NA
-------------------------------------------------------------------
Data filtering:
6720 data points (38.36%) excluded by growing season filter
2122 additional data points (12.11%) excluded by precipitation filter (3165
 data points = 18.07 % in total)
8842 data points (50.47%) excluded in total
8678 valid data points (49.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1521 data points (8.68%) set to NA
LE: 1533 data points (8.75%) set to NA
NEE: 2714 data points (15.49%) set to NA
-------------------------------------------------------------------
Data filtering:
6720 data points (38.36%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6720 data points (38.36%) excluded in total
10800 valid data points (61.64%) remaining.

New sEddyProc class for site 'US-SRS'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SRS-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1604 data points (9.16%) set to NA
LE: 1604 data points (9.16%) set to NA
NEE: 3284 data points (18.74%) set to NA
-------------------------------------------------------------------
Data filtering:
6480 data points (36.99%) excluded by growing season filter
2250 additional data points (12.84%) excluded by precipitation filter (3551
 data points = 20.27 % in total)
8730 data points (49.83%) excluded in total
8790 valid data points (50.17%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1604 data points (9.16%) set to NA
LE: 1604 data points (9.16%) set to NA
NEE: 3284 data points (18.74%) set to NA
-------------------------------------------------------------------
Data filtering:
6480 data points (36.99%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6480 data points (36.99%) excluded in total
11040 valid data points (63.01%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
New sEddyProc class for site 'US-SRS'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SRS-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[276/329] Processing: US-SSH

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-SSH | Years: 2017, 2018, 2019, 2020, 2021
Quality control:
TA: 250 data points (1.43%) set to NA
H: 6061 data points (34.59%) set to NA
LE: 6428 data points (36.69%) set to NA
NEE: 6894 data points (39.35%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 87”

-------------------------------------------------------------------
Data filtering:
6288 data points (35.89%) excluded by growing season filter
3989 additional data points (22.77%) excluded by precipitation filter (7188
 data points = 41.03 % in total)
10277 data points (58.66%) excluded in total
7243 valid data points (41.34%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 250 data points (1.43%) set to NA
H: 6061 data points (34.59%) set to NA
LE: 6428 data points (36.69%) set to NA
NEE: 6894 data points (39.35%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 87”

-------------------------------------------------------------------
Data filtering:
6288 data points (35.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6288 data points (35.89%) excluded in total
11232 valid data points (64.11%) remaining.

New sEddyProc class for site 'US-SSH'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SSH-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 60 data points (0.34%) set to NA
H: 15296 data points (87.31%) set to NA
LE: 15338 data points (87.55%) set to NA
NEE: 15442 data points (88.14%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8103 additional data points (46.25%) excluded by precipitation filter (8103
 data points = 46.25 % in total)
8103 data points (46.25%) excluded in total
9417 valid data points (53.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 60 data points (0.34%) set to NA
H: 15296 data points (87.31%) set to NA
LE: 15338 data points (87.55%) set to NA
NEE: 15442 data points (88.14%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-SSH'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SSH-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 197 data points (1.12%) set to NA
H: 334 data points (1.91%) set to NA
LE: 628 data points (3.58%) set to NA
NEE: 1869 data points (10.67%) set to NA
-------------------------------------------------------------------
Data filtering:
10416 data points (59.45%) excluded by growing season filter
2887 additional data points (16.48%) excluded by precipitation filter (6975
 data points = 39.81 % in total)
13303 data points (75.93%) excluded in total
4217 valid data points (24.07%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 197 data points (1.12%) set to NA
H: 334 data points (1.91%) set to NA
LE: 628 data points (3.58%) set to NA
NEE: 1869 data points (10.67%) set to NA
-------------------------------------------------------------------
Data filtering:
10416 data points (59.45%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10416 data points (59.45%) excluded in total
7104 valid data points (40.55%) remaining.

New sEddyProc class for site 'US-SSH'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SSH-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 125 data points (0.71%) set to NA
H: 1012 data points (5.76%) set to NA
LE: 1106 data points (6.3%) set to NA
NEE: 1955 data points (11.13%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.48%) excluded by growing season filter
2128 additional data points (12.11%) excluded by precipitation filter (6924
 data points = 39.41 % in total)
12928 data points (73.59%) excluded in total
4640 valid data points (26.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 125 data points (0.71%) set to NA
H: 1012 data points (5.76%) set to NA
LE: 1106 data points (6.3%) set to NA
NEE: 1955 data points (11.13%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.48%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10800 data points (61.48%) excluded in total
6768 valid data points (38.52%) remaining.

New sEddyProc class for site 'US-SSH'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SSH-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 3185 data points (18.18%) set to NA
H: 3905 data points (22.29%) set to NA
LE: 4053 data points (23.13%) set to NA
NEE: 4641 data points (26.49%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 51”

-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
2458 additional data points (14.03%) excluded by precipitation filter (5896
 data points = 33.65 % in total)
12394 data points (70.74%) excluded in total
5126 valid data points (29.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3185 data points (18.18%) set to NA
H: 3905 data points (22.29%) set to NA
LE: 4053 data points (23.13%) set to NA
NEE: 4641 data points (26.49%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 51”

-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9936 data points (56.71%) excluded in total
7584 valid data points (43.29%) remaining.

New sEddyProc class for site 'US-SSH'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 10 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-SSH-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[277/329] Processing: US-Ses

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Ses | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 2 data points (0.01%) set to NA
H: 13 data points (0.07%) set to NA
LE: 34 data points (0.19%) set to NA
NEE: 1576 data points (9%) set to NA
-------------------------------------------------------------------
Data filtering:
6720 data points (38.36%) excluded by growing season filter
1942 additional data points (11.08%) excluded by precipitation filter (2623
 data points = 14.97 % in total)
8662 data points (49.44%) excluded in total
8858 valid data points (50.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2 data points (0.01%) set to NA
H: 13 data points (0.07%) set to NA
LE: 34 data points (0.19%) set to NA
NEE: 1576 data points (9%) set to NA
-------------------------------------------------------------------
Data filtering:
6720 data points (38.36%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6720 data points (38.36%) excluded in total
10800 valid data points (61.64%) remaining.

New sEddyProc class for site 'US-Ses'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ses-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 206 data points (1.18%) set to NA
H: 227 data points (1.3%) set to NA
LE: 1502 data points (8.57%) set to NA
NEE: 2961 data points (16.9%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.16%) excluded by growing season filter
1246 additional data points (7.11%) excluded by precipitation filter (2430
 data points = 13.87 % in total)
11086 data points (63.28%) excluded in total
6434 valid data points (36.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 206 data points (1.18%) set to NA
H: 227 data points (1.3%) set to NA
LE: 1502 data points (8.57%) set to NA
NEE: 2961 data points (16.9%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9840 data points (56.16%) excluded in total
7680 valid data points (43.84%) remaining.

New sEddyProc class for site 'US-Ses'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ses-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 17 data points (0.1%) set to NA
LE: 59 data points (0.34%) set to NA
NEE: 1634 data points (9.33%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
968 additional data points (5.53%) excluded by precipitation filter (2839
 data points = 16.2 % in total)
12104 data points (69.09%) excluded in total
5416 valid data points (30.91%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 17 data points (0.1%) set to NA
LE: 59 data points (0.34%) set to NA
NEE: 1634 data points (9.33%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11136 data points (63.56%) excluded in total
6384 valid data points (36.44%) remaining.

New sEddyProc class for site 'US-Ses'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ses-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 105 data points (0.6%) set to NA
H: 120 data points (0.68%) set to NA
LE: 159 data points (0.91%) set to NA
NEE: 1705 data points (9.71%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.2%) excluded by growing season filter
654 additional data points (3.72%) excluded by precipitation filter (1971
 data points = 11.22 % in total)
10878 data points (61.92%) excluded in total
6690 valid data points (38.08%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 105 data points (0.6%) set to NA
H: 120 data points (0.68%) set to NA
LE: 159 data points (0.91%) set to NA
NEE: 1705 data points (9.71%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.2%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10224 data points (58.2%) excluded in total
7344 valid data points (41.8%) remaining.

New sEddyProc class for site 'US-Ses'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ses-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 7 data points (0.04%) set to NA
LE: 55 data points (0.31%) set to NA
NEE: 1167 data points (6.66%) set to NA
-------------------------------------------------------------------
Data filtering:
14928 data points (85.21%) excluded by growing season filter
715 additional data points (4.08%) excluded by precipitation filter (2086
 data points = 11.91 % in total)
15643 data points (89.29%) excluded in total
1877 valid data points (10.71%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 7 data points (0.04%) set to NA
LE: 55 data points (0.31%) set to NA
NEE: 1167 data points (6.66%) set to NA
-------------------------------------------------------------------
Data filtering:
14928 data points (85.21%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14928 data points (85.21%) excluded in total
2592 valid data points (14.79%) remaining.

New sEddyProc class for site 'US-Ses'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ses-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 18 data points (0.1%) set to NA
H: 19 data points (0.11%) set to NA
LE: 17079 data points (97.48%) set to NA
NEE: 17520 data points (100%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2741 additional data points (15.64%) excluded by precipitation filter (2741
 data points = 15.64 % in total)
2741 data points (15.64%) excluded in total
14779 valid data points (84.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 18 data points (0.1%) set to NA
H: 19 data points (0.11%) set to NA
LE: 17079 data points (97.48%) set to NA
NEE: 17520 data points (100%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Ses'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

  REddyProc error for US-Ses-2022: sMRFluxPartition:::sRegrE0fromShortTerm:::fCheckColNum::: Detected following columns in dataset to be non numeric: FP_VARnight! First occurence of non-numeric value at column 'FP_VARnight' at row NA is 'NA'.

Quality control:
TA: 100 data points (0.57%) set to NA
H: 113 data points (0.64%) set to NA
LE: 134 data points (0.76%) set to NA
NEE: 1339 data points (7.64%) set to NA
-------------------------------------------------------------------
Data filtering:
13296 data points (75.89%) excluded by growing season filter
842 additional data points (4.81%) excluded by precipitation filter (2503
 data points = 14.29 % in total)
14138 data points (80.7%) excluded in total
3382 valid data points (19.3%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 100 data points (0.57%) set to NA
H: 113 data points (0.64%) set to NA
LE: 134 data points (0.76%) set to NA
NEE: 1339 data points (7.64%) set to NA
-------------------------------------------------------------------
Data filtering:
13296 data points (75.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13296 data points (75.89%) excluded in total
4224 valid data points (24.11%) remaining.

New sEddyProc class for site 'US-Ses'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ses-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 316 data points (1.8%) set to NA
H: 332 data points (1.89%) set to NA
LE: 357 data points (2.03%) set to NA
NEE: 1182 data points (6.73%) set to NA
-------------------------------------------------------------------
Data filtering:
12096 data points (68.85%) excluded by growing season filter
1113 additional data points (6.34%) excluded by precipitation filter (2521
 data points = 14.35 % in total)
13209 data points (75.19%) excluded in total
4359 valid data points (24.81%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 316 data points (1.8%) set to NA
H: 332 data points (1.89%) set to NA
LE: 357 data points (2.03%) set to NA
NEE: 1182 data points (6.73%) set to NA
-------------------------------------------------------------------
Data filtering:
12096 data points (68.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12096 data points (68.85%) excluded in total
5472 valid data points (31.15%) remaining.

New sEddyProc class for site 'US-Ses'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ses-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 558 data points (3.18%) set to NA
H: 572 data points (3.26%) set to NA
LE: 592 data points (3.38%) set to NA
NEE: 1677 data points (9.57%) set to NA
-------------------------------------------------------------------
Data filtering:
12528 data points (71.51%) excluded by growing season filter
1141 additional data points (6.51%) excluded by precipitation filter (2670
 data points = 15.24 % in total)
13669 data points (78.02%) excluded in total
3851 valid data points (21.98%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 558 data points (3.18%) set to NA
H: 572 data points (3.26%) set to NA
LE: 592 data points (3.38%) set to NA
NEE: 1677 data points (9.57%) set to NA
-------------------------------------------------------------------
Data filtering:
12528 data points (71.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12528 data points (71.51%) excluded in total
4992 valid data points (28.49%) remaining.

New sEddyProc class for site 'US-Ses'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 139.82.

Regression of reference temperature R_ref for 6 periods.

[278/329] Processing: US-Srr

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Srr | Years: 2017
Quality control:
TA: 4308 data points (24.59%) set to NA
H: 4560 data points (26.03%) set to NA
LE: 4627 data points (26.41%) set to NA
NEE: 5673 data points (32.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 81”

-------------------------------------------------------------------
Data filtering:
4032 data points (23.01%) excluded by growing season filter
1926 additional data points (10.99%) excluded by precipitation filter (4288
 data points = 24.47 % in total)
5958 data points (34.01%) excluded in total
11562 valid data points (65.99%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4308 data points (24.59%) set to NA
H: 4560 data points (26.03%) set to NA
LE: 4627 data points (26.41%) set to NA
NEE: 5673 data points (32.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 81”

-------------------------------------------------------------------
Data filtering:
4032 data points (23.01%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4032 data points (23.01%) excluded in total
13488 valid data points (76.99%) remaining.

New sEddyProc class for site 'US-Srr'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 130.25.

Regression of reference temperature R_ref for 6 periods.

[279/329] Processing: US-StJ

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-StJ | Years: 2017, 2018, 2019, 2020
Quality control:
TA: 502 data points (2.87%) set to NA
H: 51 data points (0.29%) set to NA
LE: 72 data points (0.41%) set to NA
NEE: 457 data points (2.61%) set to NA
-------------------------------------------------------------------
Data filtering:
9984 data points (56.99%) excluded by growing season filter
3163 additional data points (18.05%) excluded by precipitation filter (7075
 data points = 40.38 % in total)
13147 data points (75.04%) excluded in total
4373 valid data points (24.96%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 502 data points (2.87%) set to NA
H: 51 data points (0.29%) set to NA
LE: 72 data points (0.41%) set to NA
NEE: 457 data points (2.61%) set to NA
-------------------------------------------------------------------
Data filtering:
9984 data points (56.99%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9984 data points (56.99%) excluded in total
7536 valid data points (43.01%) remaining.

New sEddyProc class for site 'US-StJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-StJ-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 322 data points (1.84%) set to NA
H: 335 data points (1.91%) set to NA
LE: 403 data points (2.3%) set to NA
NEE: 562 data points (3.21%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
2911 additional data points (16.62%) excluded by precipitation filter (6883
 data points = 39.29 % in total)
13567 data points (77.44%) excluded in total
3953 valid data points (22.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 322 data points (1.84%) set to NA
H: 335 data points (1.91%) set to NA
LE: 403 data points (2.3%) set to NA
NEE: 562 data points (3.21%) set to NA
-------------------------------------------------------------------
Data filtering:
10656 data points (60.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10656 data points (60.82%) excluded in total
6864 valid data points (39.18%) remaining.

New sEddyProc class for site 'US-StJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-StJ-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 10 data points (0.06%) set to NA
LE: 32 data points (0.18%) set to NA
NEE: 164 data points (0.94%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
2391 additional data points (13.65%) excluded by precipitation filter (6669
 data points = 38.07 % in total)
12663 data points (72.28%) excluded in total
4857 valid data points (27.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 10 data points (0.06%) set to NA
LE: 32 data points (0.18%) set to NA
NEE: 164 data points (0.94%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10272 data points (58.63%) excluded in total
7248 valid data points (41.37%) remaining.

New sEddyProc class for site 'US-StJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-StJ-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 10 data points (0.06%) set to NA
LE: 23 data points (0.13%) set to NA
NEE: 204 data points (1.16%) set to NA
-------------------------------------------------------------------
Data filtering:
10608 data points (60.38%) excluded by growing season filter
2640 additional data points (15.03%) excluded by precipitation filter (7325
 data points = 41.7 % in total)
13248 data points (75.41%) excluded in total
4320 valid data points (24.59%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 10 data points (0.06%) set to NA
LE: 23 data points (0.13%) set to NA
NEE: 204 data points (1.16%) set to NA
-------------------------------------------------------------------
Data filtering:
10608 data points (60.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10608 data points (60.38%) excluded in total
6960 valid data points (39.62%) remaining.

New sEddyProc class for site 'US-StJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-StJ-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[280/329] Processing: US-TKs

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-TKs | Years: 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 4033 data points (23.02%) set to NA
H: 4790 data points (27.34%) set to NA
LE: 4804 data points (27.42%) set to NA
NEE: 5102 data points (29.12%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 42”

-------------------------------------------------------------------
Data filtering:
14304 data points (81.64%) excluded by growing season filter
1852 additional data points (10.57%) excluded by precipitation filter (3705
 data points = 21.15 % in total)
16156 data points (92.21%) excluded in total
1364 valid data points (7.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4033 data points (23.02%) set to NA
H: 4790 data points (27.34%) set to NA
LE: 4804 data points (27.42%) set to NA
NEE: 5102 data points (29.12%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 42”

-------------------------------------------------------------------
Data filtering:
14304 data points (81.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14304 data points (81.64%) excluded in total
3216 valid data points (18.36%) remaining.

New sEddyProc class for site 'US-TKs'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 117.51.

Regression of reference temperature R_ref for 18 periods.

Quality control:
TA: 415 data points (2.37%) set to NA
H: 2762 data points (15.76%) set to NA
LE: 2981 data points (17.01%) set to NA
NEE: 3489 data points (19.91%) set to NA
-------------------------------------------------------------------
Data filtering:
12864 data points (73.42%) excluded by growing season filter
2580 additional data points (14.73%) excluded by precipitation filter (3686
 data points = 21.04 % in total)
15444 data points (88.15%) excluded in total
2076 valid data points (11.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 415 data points (2.37%) set to NA
H: 2762 data points (15.76%) set to NA
LE: 2981 data points (17.01%) set to NA
NEE: 3489 data points (19.91%) set to NA
-------------------------------------------------------------------
Data filtering:
12864 data points (73.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12864 data points (73.42%) excluded in total
4656 valid data points (26.58%) remaining.

New sEddyProc class for site 'US-TKs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-TKs-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 634 data points (3.61%) set to NA
H: 4619 data points (26.29%) set to NA
LE: 4659 data points (26.52%) set to NA
NEE: 5261 data points (29.95%) set to NA
-------------------------------------------------------------------
Data filtering:
14256 data points (81.15%) excluded by growing season filter
1532 additional data points (8.72%) excluded by precipitation filter (3539
 data points = 20.14 % in total)
15788 data points (89.87%) excluded in total
1780 valid data points (10.13%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 634 data points (3.61%) set to NA
H: 4619 data points (26.29%) set to NA
LE: 4659 data points (26.52%) set to NA
NEE: 5261 data points (29.95%) set to NA
-------------------------------------------------------------------
Data filtering:
14256 data points (81.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14256 data points (81.15%) excluded in total
3312 valid data points (18.85%) remaining.

New sEddyProc class for site 'US-TKs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-TKs-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1142 data points (6.52%) set to NA
H: 4528 data points (25.84%) set to NA
LE: 4611 data points (26.32%) set to NA
NEE: 5005 data points (28.57%) set to NA
-------------------------------------------------------------------
Data filtering:
14352 data points (81.92%) excluded by growing season filter
1672 additional data points (9.54%) excluded by precipitation filter (3312
 data points = 18.9 % in total)
16024 data points (91.46%) excluded in total
1496 valid data points (8.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1142 data points (6.52%) set to NA
H: 4528 data points (25.84%) set to NA
LE: 4611 data points (26.32%) set to NA
NEE: 5005 data points (28.57%) set to NA
-------------------------------------------------------------------
Data filtering:
14352 data points (81.92%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14352 data points (81.92%) excluded in total
3168 valid data points (18.08%) remaining.

New sEddyProc class for site 'US-TKs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 12 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-TKs-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1050 data points (5.99%) set to NA
H: 2705 data points (15.44%) set to NA
LE: 2744 data points (15.66%) set to NA
NEE: 3110 data points (17.75%) set to NA
-------------------------------------------------------------------
Data filtering:
14400 data points (82.19%) excluded by growing season filter
1702 additional data points (9.71%) excluded by precipitation filter (2884
 data points = 16.46 % in total)
16102 data points (91.91%) excluded in total
1418 valid data points (8.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1050 data points (5.99%) set to NA
H: 2705 data points (15.44%) set to NA
LE: 2744 data points (15.66%) set to NA
NEE: 3110 data points (17.75%) set to NA
-------------------------------------------------------------------
Data filtering:
14400 data points (82.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14400 data points (82.19%) excluded in total
3120 valid data points (17.81%) remaining.

New sEddyProc class for site 'US-TKs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-TKs-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 986 data points (5.63%) set to NA
H: 984 data points (5.62%) set to NA
LE: 1125 data points (6.42%) set to NA
NEE: 1604 data points (9.16%) set to NA
-------------------------------------------------------------------
Data filtering:
14112 data points (80.55%) excluded by growing season filter
1914 additional data points (10.92%) excluded by precipitation filter (3510
 data points = 20.03 % in total)
16026 data points (91.47%) excluded in total
1494 valid data points (8.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 986 data points (5.63%) set to NA
H: 984 data points (5.62%) set to NA
LE: 1125 data points (6.42%) set to NA
NEE: 1604 data points (9.16%) set to NA
-------------------------------------------------------------------
Data filtering:
14112 data points (80.55%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14112 data points (80.55%) excluded in total
3408 valid data points (19.45%) remaining.

New sEddyProc class for site 'US-TKs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-TKs-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 73 data points (0.42%) set to NA
H: 5922 data points (33.71%) set to NA
LE: 5980 data points (34.04%) set to NA
NEE: 6344 data points (36.11%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 35”

-------------------------------------------------------------------
Data filtering:
14112 data points (80.33%) excluded by growing season filter
1842 additional data points (10.48%) excluded by precipitation filter (3578
 data points = 20.37 % in total)
15954 data points (90.81%) excluded in total
1614 valid data points (9.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 73 data points (0.42%) set to NA
H: 5922 data points (33.71%) set to NA
LE: 5980 data points (34.04%) set to NA
NEE: 6344 data points (36.11%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 35”

-------------------------------------------------------------------
Data filtering:
14112 data points (80.33%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14112 data points (80.33%) excluded in total
3456 valid data points (19.67%) remaining.

New sEddyProc class for site 'US-TKs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-TKs-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 5846 data points (33.37%) set to NA
H: 7627 data points (43.53%) set to NA
LE: 7680 data points (43.84%) set to NA
NEE: 8101 data points (46.24%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 112”

-------------------------------------------------------------------
Data filtering:
14160 data points (80.82%) excluded by growing season filter
1722 additional data points (9.83%) excluded by precipitation filter (4143
 data points = 23.65 % in total)
15882 data points (90.65%) excluded in total
1638 valid data points (9.35%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5846 data points (33.37%) set to NA
H: 7627 data points (43.53%) set to NA
LE: 7680 data points (43.84%) set to NA
NEE: 8101 data points (46.24%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 112”

-------------------------------------------------------------------
Data filtering:
14160 data points (80.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14160 data points (80.82%) excluded in total
3360 valid data points (19.18%) remaining.

New sEddyProc class for site 'US-TKs'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 143.14.

Regression of reference temperature R_ref for 6 periods.

[281/329] Processing: US-TLR

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-TLR | Years: 2024
Quality control:
TA: 3677 data points (20.93%) set to NA
H: 3776 data points (21.49%) set to NA
LE: 3774 data points (21.48%) set to NA
NEE: 4498 data points (25.6%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 31”

-------------------------------------------------------------------
Data filtering:
6624 data points (37.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6624 data points (37.7%) excluded in total
10944 valid data points (62.3%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3677 data points (20.93%) set to NA
H: 3776 data points (21.49%) set to NA
LE: 3774 data points (21.48%) set to NA
NEE: 4498 data points (25.6%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 31”

-------------------------------------------------------------------
Data filtering:
6624 data points (37.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6624 data points (37.7%) excluded in total
10944 valid data points (62.3%) remaining.

New sEddyProc class for site 'US-TLR'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 260.52.

Regression of reference temperature R_ref for 40 periods.

[282/329] Processing: US-Ton

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Ton | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 77 data points (0.44%) set to NA
H: 324 data points (1.85%) set to NA
LE: 377 data points (2.15%) set to NA
NEE: 1319 data points (7.53%) set to NA
-------------------------------------------------------------------
Data filtering:
9456 data points (53.97%) excluded by growing season filter
2340 additional data points (13.36%) excluded by precipitation filter (3806
 data points = 21.72 % in total)
11796 data points (67.33%) excluded in total
5724 valid data points (32.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 77 data points (0.44%) set to NA
H: 324 data points (1.85%) set to NA
LE: 377 data points (2.15%) set to NA
NEE: 1319 data points (7.53%) set to NA
-------------------------------------------------------------------
Data filtering:
9456 data points (53.97%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9456 data points (53.97%) excluded in total
8064 valid data points (46.03%) remaining.

New sEddyProc class for site 'US-Ton'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ton-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1 data points (0.01%) set to NA
LE: 19 data points (0.11%) set to NA
NEE: 620 data points (3.54%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.78%) excluded by growing season filter
1672 additional data points (9.54%) excluded by precipitation filter (2892
 data points = 16.51 % in total)
10744 data points (61.32%) excluded in total
6776 valid data points (38.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1 data points (0.01%) set to NA
LE: 19 data points (0.11%) set to NA
NEE: 620 data points (3.54%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.78%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9072 data points (51.78%) excluded in total
8448 valid data points (48.22%) remaining.

New sEddyProc class for site 'US-Ton'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ton-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 306 data points (1.75%) set to NA
H: 316 data points (1.8%) set to NA
LE: 318 data points (1.82%) set to NA
NEE: 929 data points (5.3%) set to NA
-------------------------------------------------------------------
Data filtering:
6288 data points (35.89%) excluded by growing season filter
2550 additional data points (14.55%) excluded by precipitation filter (4250
 data points = 24.26 % in total)
8838 data points (50.45%) excluded in total
8682 valid data points (49.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 306 data points (1.75%) set to NA
H: 316 data points (1.8%) set to NA
LE: 318 data points (1.82%) set to NA
NEE: 929 data points (5.3%) set to NA
-------------------------------------------------------------------
Data filtering:
6288 data points (35.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6288 data points (35.89%) excluded in total
11232 valid data points (64.11%) remaining.

New sEddyProc class for site 'US-Ton'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ton-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6 data points (0.03%) set to NA
H: 16 data points (0.09%) set to NA
LE: 29 data points (0.17%) set to NA
NEE: 783 data points (4.46%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.45%) excluded by growing season filter
1446 additional data points (8.23%) excluded by precipitation filter (2516
 data points = 14.32 % in total)
10134 data points (57.68%) excluded in total
7434 valid data points (42.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6 data points (0.03%) set to NA
H: 16 data points (0.09%) set to NA
LE: 29 data points (0.17%) set to NA
NEE: 783 data points (4.46%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.45%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8688 data points (49.45%) excluded in total
8880 valid data points (50.55%) remaining.

New sEddyProc class for site 'US-Ton'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ton-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6 data points (0.03%) set to NA
H: 22 data points (0.13%) set to NA
LE: 94 data points (0.54%) set to NA
NEE: 968 data points (5.53%) set to NA
-------------------------------------------------------------------
Data filtering:
7392 data points (42.19%) excluded by growing season filter
1432 additional data points (8.17%) excluded by precipitation filter (2577
 data points = 14.71 % in total)
8824 data points (50.37%) excluded in total
8696 valid data points (49.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6 data points (0.03%) set to NA
H: 22 data points (0.13%) set to NA
LE: 94 data points (0.54%) set to NA
NEE: 968 data points (5.53%) set to NA
-------------------------------------------------------------------
Data filtering:
7392 data points (42.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7392 data points (42.19%) excluded in total
10128 valid data points (57.81%) remaining.

New sEddyProc class for site 'US-Ton'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ton-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 262 data points (1.5%) set to NA
H: 305 data points (1.74%) set to NA
LE: 402 data points (2.29%) set to NA
NEE: 1539 data points (8.78%) set to NA
-------------------------------------------------------------------
Data filtering:
7728 data points (44.11%) excluded by growing season filter
879 additional data points (5.02%) excluded by precipitation filter (2146
 data points = 12.25 % in total)
8607 data points (49.13%) excluded in total
8913 valid data points (50.87%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 262 data points (1.5%) set to NA
H: 305 data points (1.74%) set to NA
LE: 402 data points (2.29%) set to NA
NEE: 1539 data points (8.78%) set to NA
-------------------------------------------------------------------
Data filtering:
7728 data points (44.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7728 data points (44.11%) excluded in total
9792 valid data points (55.89%) remaining.

New sEddyProc class for site 'US-Ton'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ton-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 11 data points (0.06%) set to NA
LE: 375 data points (2.14%) set to NA
NEE: 1386 data points (7.91%) set to NA
-------------------------------------------------------------------
Data filtering:
11808 data points (67.4%) excluded by growing season filter
717 additional data points (4.09%) excluded by precipitation filter (3557
 data points = 20.3 % in total)
12525 data points (71.49%) excluded in total
4995 valid data points (28.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 11 data points (0.06%) set to NA
LE: 375 data points (2.14%) set to NA
NEE: 1386 data points (7.91%) set to NA
-------------------------------------------------------------------
Data filtering:
11808 data points (67.4%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11808 data points (67.4%) excluded in total
5712 valid data points (32.6%) remaining.

New sEddyProc class for site 'US-Ton'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ton-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 476 data points (2.71%) set to NA
H: 2030 data points (11.56%) set to NA
LE: 2057 data points (11.71%) set to NA
NEE: 2920 data points (16.62%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.56%) excluded by growing season filter
1545 additional data points (8.79%) excluded by precipitation filter (3507
 data points = 19.96 % in total)
11481 data points (65.35%) excluded in total
6087 valid data points (34.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 476 data points (2.71%) set to NA
H: 2030 data points (11.56%) set to NA
LE: 2057 data points (11.71%) set to NA
NEE: 2920 data points (16.62%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9936 data points (56.56%) excluded in total
7632 valid data points (43.44%) remaining.

New sEddyProc class for site 'US-Ton'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 148.01.

Regression of reference temperature R_ref for 6 periods.

Quality control:
TA: 646 data points (3.69%) set to NA
H: 1102 data points (6.29%) set to NA
LE: 1155 data points (6.59%) set to NA
NEE: 2089 data points (11.92%) set to NA
-------------------------------------------------------------------
Data filtering:
9168 data points (52.33%) excluded by growing season filter
1047 additional data points (5.98%) excluded by precipitation filter (3094
 data points = 17.66 % in total)
10215 data points (58.3%) excluded in total
7305 valid data points (41.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 646 data points (3.69%) set to NA
H: 1102 data points (6.29%) set to NA
LE: 1155 data points (6.59%) set to NA
NEE: 2089 data points (11.92%) set to NA
-------------------------------------------------------------------
Data filtering:
9168 data points (52.33%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9168 data points (52.33%) excluded in total
8352 valid data points (47.67%) remaining.

New sEddyProc class for site 'US-Ton'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Ton-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[283/329] Processing: US-Tw1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Tw1 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023
Quality control:
TA: 110 data points (0.63%) set to NA
H: 1137 data points (6.49%) set to NA
LE: 1487 data points (8.49%) set to NA
NEE: 5939 data points (33.9%) set to NA
-------------------------------------------------------------------
Data filtering:
8736 data points (49.86%) excluded by growing season filter
626 additional data points (3.57%) excluded by precipitation filter (4296
 data points = 24.52 % in total)
9362 data points (53.44%) excluded in total
8158 valid data points (46.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 110 data points (0.63%) set to NA
H: 1137 data points (6.49%) set to NA
LE: 1487 data points (8.49%) set to NA
NEE: 5939 data points (33.9%) set to NA
-------------------------------------------------------------------
Data filtering:
8736 data points (49.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8736 data points (49.86%) excluded in total
8784 valid data points (50.14%) remaining.

New sEddyProc class for site 'US-Tw1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Tw1-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1070 data points (6.11%) set to NA
LE: 2437 data points (13.91%) set to NA
NEE: 5226 data points (29.83%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
318 additional data points (1.82%) excluded by precipitation filter (3444
 data points = 19.66 % in total)
9534 data points (54.42%) excluded in total
7986 valid data points (45.58%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1070 data points (6.11%) set to NA
LE: 2437 data points (13.91%) set to NA
NEE: 5226 data points (29.83%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9216 data points (52.6%) excluded in total
8304 valid data points (47.4%) remaining.

New sEddyProc class for site 'US-Tw1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Tw1-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 798 data points (4.55%) set to NA
LE: 1086 data points (6.2%) set to NA
NEE: 4653 data points (26.56%) set to NA
-------------------------------------------------------------------
Data filtering:
9888 data points (56.44%) excluded by growing season filter
496 additional data points (2.83%) excluded by precipitation filter (4954
 data points = 28.28 % in total)
10384 data points (59.27%) excluded in total
7136 valid data points (40.73%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 798 data points (4.55%) set to NA
LE: 1086 data points (6.2%) set to NA
NEE: 4653 data points (26.56%) set to NA
-------------------------------------------------------------------
Data filtering:
9888 data points (56.44%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9888 data points (56.44%) excluded in total
7632 valid data points (43.56%) remaining.

New sEddyProc class for site 'US-Tw1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Tw1-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 783 data points (4.46%) set to NA
LE: 1167 data points (6.64%) set to NA
NEE: 4693 data points (26.71%) set to NA
-------------------------------------------------------------------
Data filtering:
9600 data points (54.64%) excluded by growing season filter
150 additional data points (0.85%) excluded by precipitation filter (2856
 data points = 16.26 % in total)
9750 data points (55.5%) excluded in total
7818 valid data points (44.5%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 783 data points (4.46%) set to NA
LE: 1167 data points (6.64%) set to NA
NEE: 4693 data points (26.71%) set to NA
-------------------------------------------------------------------
Data filtering:
9600 data points (54.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9600 data points (54.64%) excluded in total
7968 valid data points (45.36%) remaining.

New sEddyProc class for site 'US-Tw1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Tw1-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 813 data points (4.64%) set to NA
LE: 1265 data points (7.22%) set to NA
NEE: 5647 data points (32.23%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.27%) excluded by growing season filter
156 additional data points (0.89%) excluded by precipitation filter (3392
 data points = 19.36 % in total)
10716 data points (61.16%) excluded in total
6804 valid data points (38.84%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 813 data points (4.64%) set to NA
LE: 1265 data points (7.22%) set to NA
NEE: 5647 data points (32.23%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10560 data points (60.27%) excluded in total
6960 valid data points (39.73%) remaining.

New sEddyProc class for site 'US-Tw1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Tw1-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 83 data points (0.47%) set to NA
H: 800 data points (4.57%) set to NA
LE: 1195 data points (6.82%) set to NA
NEE: 4910 data points (28.03%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
568 additional data points (3.24%) excluded by precipitation filter (2838
 data points = 16.2 % in total)
10504 data points (59.95%) excluded in total
7016 valid data points (40.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 83 data points (0.47%) set to NA
H: 800 data points (4.57%) set to NA
LE: 1195 data points (6.82%) set to NA
NEE: 4910 data points (28.03%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9936 data points (56.71%) excluded in total
7584 valid data points (43.29%) remaining.

New sEddyProc class for site 'US-Tw1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Tw1-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 611 data points (3.49%) set to NA
H: 1509 data points (8.61%) set to NA
LE: 1875 data points (10.7%) set to NA
NEE: 4451 data points (25.41%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
718 additional data points (4.1%) excluded by precipitation filter (4566
 data points = 26.06 % in total)
10654 data points (60.81%) excluded in total
6866 valid data points (39.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 611 data points (3.49%) set to NA
H: 1509 data points (8.61%) set to NA
LE: 1875 data points (10.7%) set to NA
NEE: 4451 data points (25.41%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9936 data points (56.71%) excluded in total
7584 valid data points (43.29%) remaining.

New sEddyProc class for site 'US-Tw1'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Tw1-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[284/329] Processing: US-Tw4

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Tw4 | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 0 data points (0%) set to NA
H: 55 data points (0.31%) set to NA
LE: 274 data points (1.56%) set to NA
NEE: 1074 data points (6.13%) set to NA
-------------------------------------------------------------------
Data filtering:
8736 data points (49.86%) excluded by growing season filter
154 additional data points (0.88%) excluded by precipitation filter (2760
 data points = 15.75 % in total)
8890 data points (50.74%) excluded in total
8630 valid data points (49.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 55 data points (0.31%) set to NA
LE: 274 data points (1.56%) set to NA
NEE: 1074 data points (6.13%) set to NA
-------------------------------------------------------------------
Data filtering:
8736 data points (49.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8736 data points (49.86%) excluded in total
8784 valid data points (50.14%) remaining.

New sEddyProc class for site 'US-Tw4'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Tw4-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 19 data points (0.11%) set to NA
LE: 66 data points (0.38%) set to NA
NEE: 879 data points (5.02%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.59%) excluded by growing season filter
51 additional data points (0.29%) excluded by precipitation filter (1996
 data points = 11.39 % in total)
8739 data points (49.88%) excluded in total
8781 valid data points (50.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 19 data points (0.11%) set to NA
LE: 66 data points (0.38%) set to NA
NEE: 879 data points (5.02%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8688 data points (49.59%) excluded in total
8832 valid data points (50.41%) remaining.

New sEddyProc class for site 'US-Tw4'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Tw4-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 58 data points (0.33%) set to NA
H: 65 data points (0.37%) set to NA
LE: 265 data points (1.51%) set to NA
NEE: 1001 data points (5.71%) set to NA
-------------------------------------------------------------------
Data filtering:
8400 data points (47.95%) excluded by growing season filter
352 additional data points (2.01%) excluded by precipitation filter (3124
 data points = 17.83 % in total)
8752 data points (49.95%) excluded in total
8768 valid data points (50.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 58 data points (0.33%) set to NA
H: 65 data points (0.37%) set to NA
LE: 265 data points (1.51%) set to NA
NEE: 1001 data points (5.71%) set to NA
-------------------------------------------------------------------
Data filtering:
8400 data points (47.95%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8400 data points (47.95%) excluded in total
9120 valid data points (52.05%) remaining.

New sEddyProc class for site 'US-Tw4'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Tw4-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 17 data points (0.1%) set to NA
H: 54 data points (0.31%) set to NA
LE: 150 data points (0.85%) set to NA
NEE: 993 data points (5.65%) set to NA
-------------------------------------------------------------------
Data filtering:
10176 data points (57.92%) excluded by growing season filter
142 additional data points (0.81%) excluded by precipitation filter (1437
 data points = 8.18 % in total)
10318 data points (58.73%) excluded in total
7250 valid data points (41.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 17 data points (0.1%) set to NA
H: 54 data points (0.31%) set to NA
LE: 150 data points (0.85%) set to NA
NEE: 993 data points (5.65%) set to NA
-------------------------------------------------------------------
Data filtering:
10176 data points (57.92%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10176 data points (57.92%) excluded in total
7392 valid data points (42.08%) remaining.

New sEddyProc class for site 'US-Tw4'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Tw4-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 108 data points (0.62%) set to NA
H: 95 data points (0.54%) set to NA
LE: 199 data points (1.14%) set to NA
NEE: 876 data points (5%) set to NA
-------------------------------------------------------------------
Data filtering:
8928 data points (50.96%) excluded by growing season filter
114 additional data points (0.65%) excluded by precipitation filter (1708
 data points = 9.75 % in total)
9042 data points (51.61%) excluded in total
8478 valid data points (48.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 108 data points (0.62%) set to NA
H: 95 data points (0.54%) set to NA
LE: 199 data points (1.14%) set to NA
NEE: 876 data points (5%) set to NA
-------------------------------------------------------------------
Data filtering:
8928 data points (50.96%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8928 data points (50.96%) excluded in total
8592 valid data points (49.04%) remaining.

New sEddyProc class for site 'US-Tw4'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Tw4-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 459 data points (2.62%) set to NA
H: 488 data points (2.79%) set to NA
LE: 876 data points (5%) set to NA
NEE: 1794 data points (10.24%) set to NA
-------------------------------------------------------------------
Data filtering:
9744 data points (55.62%) excluded by growing season filter
166 additional data points (0.95%) excluded by precipitation filter (1695
 data points = 9.67 % in total)
9910 data points (56.56%) excluded in total
7610 valid data points (43.44%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 459 data points (2.62%) set to NA
H: 488 data points (2.79%) set to NA
LE: 876 data points (5%) set to NA
NEE: 1794 data points (10.24%) set to NA
-------------------------------------------------------------------
Data filtering:
9744 data points (55.62%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9744 data points (55.62%) excluded in total
7776 valid data points (44.38%) remaining.

New sEddyProc class for site 'US-Tw4'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 62.43.

Regression of reference temperature R_ref for 8 periods.

Quality control:
TA: 144 data points (0.82%) set to NA
H: 281 data points (1.6%) set to NA
LE: 331 data points (1.89%) set to NA
NEE: 1142 data points (6.52%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
190 additional data points (1.08%) excluded by precipitation filter (3061
 data points = 17.47 % in total)
9550 data points (54.51%) excluded in total
7970 valid data points (45.49%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 144 data points (0.82%) set to NA
H: 281 data points (1.6%) set to NA
LE: 331 data points (1.89%) set to NA
NEE: 1142 data points (6.52%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9360 data points (53.42%) excluded in total
8160 valid data points (46.58%) remaining.

New sEddyProc class for site 'US-Tw4'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 1 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Tw4-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 65 data points (0.37%) set to NA
H: 214 data points (1.22%) set to NA
LE: 427 data points (2.43%) set to NA
NEE: 1510 data points (8.6%) set to NA
-------------------------------------------------------------------
Data filtering:
9264 data points (52.73%) excluded by growing season filter
66 additional data points (0.38%) excluded by precipitation filter (2989
 data points = 17.01 % in total)
9330 data points (53.11%) excluded in total
8238 valid data points (46.89%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 65 data points (0.37%) set to NA
H: 214 data points (1.22%) set to NA
LE: 427 data points (2.43%) set to NA
NEE: 1510 data points (8.6%) set to NA
-------------------------------------------------------------------
Data filtering:
9264 data points (52.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9264 data points (52.73%) excluded in total
8304 valid data points (47.27%) remaining.

New sEddyProc class for site 'US-Tw4'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Tw4-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[285/329] Processing: US-Tw5

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Tw5 | Years: 2018, 2019
Quality control:
TA: 5728 data points (32.69%) set to NA
H: 5721 data points (32.65%) set to NA
LE: 6051 data points (34.54%) set to NA
NEE: 7577 data points (43.25%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 98”

-------------------------------------------------------------------
Data filtering:
8400 data points (47.95%) excluded by growing season filter
318 additional data points (1.82%) excluded by precipitation filter (3444
 data points = 19.66 % in total)
8718 data points (49.76%) excluded in total
8802 valid data points (50.24%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5728 data points (32.69%) set to NA
H: 5721 data points (32.65%) set to NA
LE: 6051 data points (34.54%) set to NA
NEE: 7577 data points (43.25%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 98”

-------------------------------------------------------------------
Data filtering:
8400 data points (47.95%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8400 data points (47.95%) excluded in total
9120 valid data points (52.05%) remaining.

New sEddyProc class for site 'US-Tw5'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 332.68.

Regression of reference temperature R_ref for 11 periods.

Quality control:
TA: 60 data points (0.34%) set to NA
H: 730 data points (4.17%) set to NA
LE: 1480 data points (8.45%) set to NA
NEE: 3544 data points (20.23%) set to NA
-------------------------------------------------------------------
Data filtering:
7296 data points (41.64%) excluded by growing season filter
948 additional data points (5.41%) excluded by precipitation filter (4954
 data points = 28.28 % in total)
8244 data points (47.05%) excluded in total
9276 valid data points (52.95%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 60 data points (0.34%) set to NA
H: 730 data points (4.17%) set to NA
LE: 1480 data points (8.45%) set to NA
NEE: 3544 data points (20.23%) set to NA
-------------------------------------------------------------------
Data filtering:
7296 data points (41.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7296 data points (41.64%) excluded in total
10224 valid data points (58.36%) remaining.

New sEddyProc class for site 'US-Tw5'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Tw5-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[286/329] Processing: US-UMd

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-UMd | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 142 data points (0.81%) set to NA
H: 147 data points (0.84%) set to NA
LE: 154 data points (0.88%) set to NA
NEE: 336 data points (1.92%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (60%) excluded by growing season filter
4536 additional data points (25.89%) excluded by precipitation filter (11922
 data points = 68.05 % in total)
15048 data points (85.89%) excluded in total
2472 valid data points (14.11%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 142 data points (0.81%) set to NA
H: 147 data points (0.84%) set to NA
LE: 154 data points (0.88%) set to NA
NEE: 336 data points (1.92%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (60%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10512 data points (60%) excluded in total
7008 valid data points (40%) remaining.

New sEddyProc class for site 'US-UMd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-UMd-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 21 data points (0.12%) set to NA
H: 34 data points (0.19%) set to NA
LE: 38 data points (0.22%) set to NA
NEE: 223 data points (1.27%) set to NA
-------------------------------------------------------------------
Data filtering:
10608 data points (60.55%) excluded by growing season filter
3540 additional data points (20.21%) excluded by precipitation filter (10160
 data points = 57.99 % in total)
14148 data points (80.75%) excluded in total
3372 valid data points (19.25%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 21 data points (0.12%) set to NA
H: 34 data points (0.19%) set to NA
LE: 38 data points (0.22%) set to NA
NEE: 223 data points (1.27%) set to NA
-------------------------------------------------------------------
Data filtering:
10608 data points (60.55%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10608 data points (60.55%) excluded in total
6912 valid data points (39.45%) remaining.

New sEddyProc class for site 'US-UMd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-UMd-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 191 data points (1.09%) set to NA
H: 212 data points (1.21%) set to NA
LE: 221 data points (1.26%) set to NA
NEE: 506 data points (2.89%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
4072 additional data points (23.24%) excluded by precipitation filter (11396
 data points = 65.05 % in total)
14872 data points (84.89%) excluded in total
2648 valid data points (15.11%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 191 data points (1.09%) set to NA
H: 212 data points (1.21%) set to NA
LE: 221 data points (1.26%) set to NA
NEE: 506 data points (2.89%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10800 data points (61.64%) excluded in total
6720 valid data points (38.36%) remaining.

New sEddyProc class for site 'US-UMd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-UMd-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 252 data points (1.43%) set to NA
H: 293 data points (1.67%) set to NA
LE: 99 data points (0.56%) set to NA
NEE: 562 data points (3.2%) set to NA
-------------------------------------------------------------------
Data filtering:
10992 data points (62.57%) excluded by growing season filter
3600 additional data points (20.49%) excluded by precipitation filter (10432
 data points = 59.38 % in total)
14592 data points (83.06%) excluded in total
2976 valid data points (16.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 252 data points (1.43%) set to NA
H: 293 data points (1.67%) set to NA
LE: 99 data points (0.56%) set to NA
NEE: 562 data points (3.2%) set to NA
-------------------------------------------------------------------
Data filtering:
10992 data points (62.57%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10992 data points (62.57%) excluded in total
6576 valid data points (37.43%) remaining.

New sEddyProc class for site 'US-UMd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-UMd-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 260 data points (1.48%) set to NA
H: 274 data points (1.56%) set to NA
LE: 106 data points (0.61%) set to NA
NEE: 683 data points (3.9%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
4224 additional data points (24.11%) excluded by precipitation filter (10750
 data points = 61.36 % in total)
14496 data points (82.74%) excluded in total
3024 valid data points (17.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 260 data points (1.48%) set to NA
H: 274 data points (1.56%) set to NA
LE: 106 data points (0.61%) set to NA
NEE: 683 data points (3.9%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10272 data points (58.63%) excluded in total
7248 valid data points (41.37%) remaining.

New sEddyProc class for site 'US-UMd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-UMd-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 334 data points (1.91%) set to NA
H: 389 data points (2.22%) set to NA
LE: 115 data points (0.66%) set to NA
NEE: 427 data points (2.44%) set to NA
-------------------------------------------------------------------
Data filtering:
10416 data points (59.45%) excluded by growing season filter
3438 additional data points (19.62%) excluded by precipitation filter (10390
 data points = 59.3 % in total)
13854 data points (79.08%) excluded in total
3666 valid data points (20.92%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 334 data points (1.91%) set to NA
H: 389 data points (2.22%) set to NA
LE: 115 data points (0.66%) set to NA
NEE: 427 data points (2.44%) set to NA
-------------------------------------------------------------------
Data filtering:
10416 data points (59.45%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10416 data points (59.45%) excluded in total
7104 valid data points (40.55%) remaining.

New sEddyProc class for site 'US-UMd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-UMd-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 169 data points (0.96%) set to NA
H: 4083 data points (23.3%) set to NA
LE: 106 data points (0.61%) set to NA
NEE: 303 data points (1.73%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
3524 additional data points (20.11%) excluded by precipitation filter (9838
 data points = 56.15 % in total)
13748 data points (78.47%) excluded in total
3772 valid data points (21.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 169 data points (0.96%) set to NA
H: 4083 data points (23.3%) set to NA
LE: 106 data points (0.61%) set to NA
NEE: 303 data points (1.73%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10224 data points (58.36%) excluded in total
7296 valid data points (41.64%) remaining.

New sEddyProc class for site 'US-UMd'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 217.29.

Regression of reference temperature R_ref for 3 periods.

Quality control:
TA: 2809 data points (15.99%) set to NA
H: 14491 data points (82.49%) set to NA
LE: 2662 data points (15.15%) set to NA
NEE: 2857 data points (16.26%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.39%) excluded by growing season filter
3826 additional data points (21.78%) excluded by precipitation filter (10642
 data points = 60.58 % in total)
14962 data points (85.17%) excluded in total
2606 valid data points (14.83%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2809 data points (15.99%) set to NA
H: 14491 data points (82.49%) set to NA
LE: 2662 data points (15.15%) set to NA
NEE: 2857 data points (16.26%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.39%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11136 data points (63.39%) excluded in total
6432 valid data points (36.61%) remaining.

New sEddyProc class for site 'US-UMd'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 57.9.

Regression of reference temperature R_ref for 20 periods.

Quality control:
TA: 4054 data points (23.14%) set to NA
H: 9729 data points (55.53%) set to NA
LE: 4244 data points (24.22%) set to NA
NEE: 4360 data points (24.89%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 69”

-------------------------------------------------------------------
Data filtering:
10896 data points (62.19%) excluded by growing season filter
3546 additional data points (20.24%) excluded by precipitation filter (11364
 data points = 64.86 % in total)
14442 data points (82.43%) excluded in total
3078 valid data points (17.57%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4054 data points (23.14%) set to NA
H: 9729 data points (55.53%) set to NA
LE: 4244 data points (24.22%) set to NA
NEE: 4360 data points (24.89%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 69”

-------------------------------------------------------------------
Data filtering:
10896 data points (62.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10896 data points (62.19%) excluded in total
6624 valid data points (37.81%) remaining.

New sEddyProc class for site 'US-UMd'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 10 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-UMd-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[287/329] Processing: US-Uaf

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Uaf | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 0 data points (0%) set to NA
H: 2256 data points (12.88%) set to NA
LE: 2349 data points (13.41%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2442 additional data points (13.94%) excluded by precipitation filter (2442
 data points = 13.94 % in total)
2442 data points (13.94%) excluded in total
15078 valid data points (86.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2256 data points (12.88%) set to NA
LE: 2349 data points (13.41%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Uaf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Uaf-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1800 data points (10.27%) set to NA
H: 2805 data points (16.01%) set to NA
LE: 3053 data points (17.43%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3471 additional data points (19.81%) excluded by precipitation filter (3471
 data points = 19.81 % in total)
3471 data points (19.81%) excluded in total
14049 valid data points (80.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1800 data points (10.27%) set to NA
H: 2805 data points (16.01%) set to NA
LE: 3053 data points (17.43%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Uaf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Uaf-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 458 data points (2.61%) set to NA
H: 6093 data points (34.78%) set to NA
LE: 6681 data points (38.13%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3645 additional data points (20.8%) excluded by precipitation filter (3645
 data points = 20.8 % in total)
3645 data points (20.8%) excluded in total
13875 valid data points (79.2%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 458 data points (2.61%) set to NA
H: 6093 data points (34.78%) set to NA
LE: 6681 data points (38.13%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Uaf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Uaf-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4 data points (0.02%) set to NA
H: 1591 data points (9.06%) set to NA
LE: 1662 data points (9.46%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4443 additional data points (25.29%) excluded by precipitation filter (4443
 data points = 25.29 % in total)
4443 data points (25.29%) excluded in total
13125 valid data points (74.71%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4 data points (0.02%) set to NA
H: 1591 data points (9.06%) set to NA
LE: 1662 data points (9.46%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-Uaf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Uaf-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4 data points (0.02%) set to NA
H: 121 data points (0.69%) set to NA
LE: 3840 data points (21.92%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2521 additional data points (14.39%) excluded by precipitation filter (2521
 data points = 14.39 % in total)
2521 data points (14.39%) excluded in total
14999 valid data points (85.61%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4 data points (0.02%) set to NA
H: 121 data points (0.69%) set to NA
LE: 3840 data points (21.92%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Uaf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Uaf-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 712 data points (4.06%) set to NA
LE: 5551 data points (31.68%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3138 additional data points (17.91%) excluded by precipitation filter (3138
 data points = 17.91 % in total)
3138 data points (17.91%) excluded in total
14382 valid data points (82.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 712 data points (4.06%) set to NA
LE: 5551 data points (31.68%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Uaf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Uaf-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 1163 data points (6.64%) set to NA
LE: 2305 data points (13.16%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3599 additional data points (20.54%) excluded by precipitation filter (3599
 data points = 20.54 % in total)
3599 data points (20.54%) excluded in total
13921 valid data points (79.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 1163 data points (6.64%) set to NA
LE: 2305 data points (13.16%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Uaf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Uaf-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 881 data points (5.01%) set to NA
LE: 967 data points (5.5%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4985 additional data points (28.38%) excluded by precipitation filter (4985
 data points = 28.38 % in total)
4985 data points (28.38%) excluded in total
12583 valid data points (71.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 881 data points (5.01%) set to NA
LE: 967 data points (5.5%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-Uaf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Uaf-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 126 data points (0.72%) set to NA
LE: 1174 data points (6.7%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5053 additional data points (28.84%) excluded by precipitation filter (5053
 data points = 28.84 % in total)
5053 data points (28.84%) excluded in total
12467 valid data points (71.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 126 data points (0.72%) set to NA
LE: 1174 data points (6.7%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Uaf'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Uaf-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[288/329] Processing: US-Vcm

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Vcm | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 1468 data points (8.38%) set to NA
H: 1576 data points (9%) set to NA
LE: 1612 data points (9.2%) set to NA
NEE: 2948 data points (16.83%) set to NA
-------------------------------------------------------------------
Data filtering:
9168 data points (52.33%) excluded by growing season filter
3308 additional data points (18.88%) excluded by precipitation filter (4900
 data points = 27.97 % in total)
12476 data points (71.21%) excluded in total
5044 valid data points (28.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1468 data points (8.38%) set to NA
H: 1576 data points (9%) set to NA
LE: 1612 data points (9.2%) set to NA
NEE: 2948 data points (16.83%) set to NA
-------------------------------------------------------------------
Data filtering:
9168 data points (52.33%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9168 data points (52.33%) excluded in total
8352 valid data points (47.67%) remaining.

New sEddyProc class for site 'US-Vcm'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 72.18.

Regression of reference temperature R_ref for 12 periods.

Quality control:
TA: 10 data points (0.06%) set to NA
H: 121 data points (0.69%) set to NA
LE: 132 data points (0.75%) set to NA
NEE: 1745 data points (9.96%) set to NA
-------------------------------------------------------------------
Data filtering:
8640 data points (49.32%) excluded by growing season filter
3587 additional data points (20.47%) excluded by precipitation filter (6345
 data points = 36.22 % in total)
12227 data points (69.79%) excluded in total
5293 valid data points (30.21%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10 data points (0.06%) set to NA
H: 121 data points (0.69%) set to NA
LE: 132 data points (0.75%) set to NA
NEE: 1745 data points (9.96%) set to NA
-------------------------------------------------------------------
Data filtering:
8640 data points (49.32%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8640 data points (49.32%) excluded in total
8880 valid data points (50.68%) remaining.

New sEddyProc class for site 'US-Vcm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Vcm-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 309 data points (1.76%) set to NA
H: 444 data points (2.53%) set to NA
LE: 476 data points (2.72%) set to NA
NEE: 2231 data points (12.73%) set to NA
-------------------------------------------------------------------
Data filtering:
9984 data points (56.99%) excluded by growing season filter
3103 additional data points (17.71%) excluded by precipitation filter (8653
 data points = 49.39 % in total)
13087 data points (74.7%) excluded in total
4433 valid data points (25.3%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 309 data points (1.76%) set to NA
H: 444 data points (2.53%) set to NA
LE: 476 data points (2.72%) set to NA
NEE: 2231 data points (12.73%) set to NA
-------------------------------------------------------------------
Data filtering:
9984 data points (56.99%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9984 data points (56.99%) excluded in total
7536 valid data points (43.01%) remaining.

New sEddyProc class for site 'US-Vcm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Vcm-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 18 data points (0.1%) set to NA
H: 66 data points (0.38%) set to NA
LE: 86 data points (0.49%) set to NA
NEE: 1690 data points (9.62%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.72%) excluded by growing season filter
2842 additional data points (16.18%) excluded by precipitation filter (5691
 data points = 32.39 % in total)
11050 data points (62.9%) excluded in total
6518 valid data points (37.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 18 data points (0.1%) set to NA
H: 66 data points (0.38%) set to NA
LE: 86 data points (0.49%) set to NA
NEE: 1690 data points (9.62%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.72%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8208 data points (46.72%) excluded in total
9360 valid data points (53.28%) remaining.

New sEddyProc class for site 'US-Vcm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Vcm-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 245 data points (1.4%) set to NA
H: 321 data points (1.83%) set to NA
LE: 344 data points (1.96%) set to NA
NEE: 3331 data points (19.01%) set to NA
-------------------------------------------------------------------
Data filtering:
9456 data points (53.97%) excluded by growing season filter
4198 additional data points (23.96%) excluded by precipitation filter (6946
 data points = 39.65 % in total)
13654 data points (77.93%) excluded in total
3866 valid data points (22.07%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 245 data points (1.4%) set to NA
H: 321 data points (1.83%) set to NA
LE: 344 data points (1.96%) set to NA
NEE: 3331 data points (19.01%) set to NA
-------------------------------------------------------------------
Data filtering:
9456 data points (53.97%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9456 data points (53.97%) excluded in total
8064 valid data points (46.03%) remaining.

New sEddyProc class for site 'US-Vcm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Vcm-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 24 data points (0.14%) set to NA
H: 102 data points (0.58%) set to NA
LE: 124 data points (0.71%) set to NA
NEE: 3797 data points (21.67%) set to NA
-------------------------------------------------------------------
Data filtering:
8496 data points (48.49%) excluded by growing season filter
4629 additional data points (26.42%) excluded by precipitation filter (7309
 data points = 41.72 % in total)
13125 data points (74.91%) excluded in total
4395 valid data points (25.09%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 24 data points (0.14%) set to NA
H: 102 data points (0.58%) set to NA
LE: 124 data points (0.71%) set to NA
NEE: 3797 data points (21.67%) set to NA
-------------------------------------------------------------------
Data filtering:
8496 data points (48.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8496 data points (48.49%) excluded in total
9024 valid data points (51.51%) remaining.

New sEddyProc class for site 'US-Vcm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Vcm-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 54 data points (0.31%) set to NA
H: 204 data points (1.16%) set to NA
LE: 215 data points (1.23%) set to NA
NEE: 2922 data points (16.68%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
3226 additional data points (18.41%) excluded by precipitation filter (7192
 data points = 41.05 % in total)
13450 data points (76.77%) excluded in total
4070 valid data points (23.23%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 54 data points (0.31%) set to NA
H: 204 data points (1.16%) set to NA
LE: 215 data points (1.23%) set to NA
NEE: 2922 data points (16.68%) set to NA
-------------------------------------------------------------------
Data filtering:
10224 data points (58.36%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10224 data points (58.36%) excluded in total
7296 valid data points (41.64%) remaining.

New sEddyProc class for site 'US-Vcm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Vcm-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 102 data points (0.58%) set to NA
H: 359 data points (2.04%) set to NA
LE: 391 data points (2.23%) set to NA
NEE: 4416 data points (25.14%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.56%) excluded by growing season filter
3756 additional data points (21.38%) excluded by precipitation filter (7506
 data points = 42.73 % in total)
14220 data points (80.94%) excluded in total
3348 valid data points (19.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 102 data points (0.58%) set to NA
H: 359 data points (2.04%) set to NA
LE: 391 data points (2.23%) set to NA
NEE: 4416 data points (25.14%) set to NA
-------------------------------------------------------------------
Data filtering:
10464 data points (59.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10464 data points (59.56%) excluded in total
7104 valid data points (40.44%) remaining.

New sEddyProc class for site 'US-Vcm'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Vcm-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 192 data points (1.1%) set to NA
H: 348 data points (1.99%) set to NA
LE: 374 data points (2.13%) set to NA
NEE: 3232 data points (18.45%) set to NA
-------------------------------------------------------------------
Data filtering:
9888 data points (56.44%) excluded by growing season filter
4175 additional data points (23.83%) excluded by precipitation filter (6908
 data points = 39.43 % in total)
14063 data points (80.27%) excluded in total
3457 valid data points (19.73%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 192 data points (1.1%) set to NA
H: 348 data points (1.99%) set to NA
LE: 374 data points (2.13%) set to NA
NEE: 3232 data points (18.45%) set to NA
-------------------------------------------------------------------
Data filtering:
9888 data points (56.44%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9888 data points (56.44%) excluded in total
7632 valid data points (43.56%) remaining.

New sEddyProc class for site 'US-Vcm'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 188.18.

Regression of reference temperature R_ref for 3 periods.

[289/329] Processing: US-Vcp

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Vcp | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 753 data points (4.3%) set to NA
H: 845 data points (4.82%) set to NA
LE: 876 data points (5%) set to NA
NEE: 1555 data points (8.88%) set to NA
-------------------------------------------------------------------
Data filtering:
3984 data points (22.74%) excluded by growing season filter
4239 additional data points (24.2%) excluded by precipitation filter (5275
 data points = 30.11 % in total)
8223 data points (46.93%) excluded in total
9297 valid data points (53.07%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 753 data points (4.3%) set to NA
H: 845 data points (4.82%) set to NA
LE: 876 data points (5%) set to NA
NEE: 1555 data points (8.88%) set to NA
-------------------------------------------------------------------
Data filtering:
3984 data points (22.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3984 data points (22.74%) excluded in total
13536 valid data points (77.26%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
New sEddyProc class for site 'US-Vcp'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 85.06.

Regression of reference temperature R_ref for 6 periods.

Quality control:
TA: 444 data points (2.53%) set to NA
H: 550 data points (3.14%) set to NA
LE: 594 data points (3.39%) set to NA
NEE: 1343 data points (7.67%) set to NA
-------------------------------------------------------------------
Data filtering:
7584 data points (43.29%) excluded by growing season filter
2708 additional data points (15.46%) excluded by precipitation filter (4660
 data points = 26.6 % in total)
10292 data points (58.74%) excluded in total
7228 valid data points (41.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 444 data points (2.53%) set to NA
H: 550 data points (3.14%) set to NA
LE: 594 data points (3.39%) set to NA
NEE: 1343 data points (7.67%) set to NA
-------------------------------------------------------------------
Data filtering:
7584 data points (43.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7584 data points (43.29%) excluded in total
9936 valid data points (56.71%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
New sEddyProc class for site 'US-Vcp'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 184.59.

Regression of reference temperature R_ref for 7 periods.

Quality control:
TA: 1998 data points (11.4%) set to NA
H: 2149 data points (12.27%) set to NA
LE: 2206 data points (12.59%) set to NA
NEE: 2970 data points (16.95%) set to NA
-------------------------------------------------------------------
Data filtering:
5232 data points (29.86%) excluded by growing season filter
4109 additional data points (23.45%) excluded by precipitation filter (6490
 data points = 37.04 % in total)
9341 data points (53.32%) excluded in total
8179 valid data points (46.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1998 data points (11.4%) set to NA
H: 2149 data points (12.27%) set to NA
LE: 2206 data points (12.59%) set to NA
NEE: 2970 data points (16.95%) set to NA
-------------------------------------------------------------------
Data filtering:
5232 data points (29.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5232 data points (29.86%) excluded in total
12288 valid data points (70.14%) remaining.

New sEddyProc class for site 'US-Vcp'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 16 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Vcp-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 828 data points (4.71%) set to NA
H: 948 data points (5.4%) set to NA
LE: 979 data points (5.57%) set to NA
NEE: 1570 data points (8.94%) set to NA
-------------------------------------------------------------------
Data filtering:
5808 data points (33.06%) excluded by growing season filter
2807 additional data points (15.98%) excluded by precipitation filter (3944
 data points = 22.45 % in total)
8615 data points (49.04%) excluded in total
8953 valid data points (50.96%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 828 data points (4.71%) set to NA
H: 948 data points (5.4%) set to NA
LE: 979 data points (5.57%) set to NA
NEE: 1570 data points (8.94%) set to NA
-------------------------------------------------------------------
Data filtering:
5808 data points (33.06%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5808 data points (33.06%) excluded in total
11760 valid data points (66.94%) remaining.

New sEddyProc class for site 'US-Vcp'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 111.15.

Regression of reference temperature R_ref for 6 periods.

Quality control:
TA: 938 data points (5.35%) set to NA
H: 1012 data points (5.78%) set to NA
LE: 1058 data points (6.04%) set to NA
NEE: 1560 data points (8.9%) set to NA
-------------------------------------------------------------------
Data filtering:
5184 data points (29.59%) excluded by growing season filter
3384 additional data points (19.32%) excluded by precipitation filter (4524
 data points = 25.82 % in total)
8568 data points (48.9%) excluded in total
8952 valid data points (51.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 938 data points (5.35%) set to NA
H: 1012 data points (5.78%) set to NA
LE: 1058 data points (6.04%) set to NA
NEE: 1560 data points (8.9%) set to NA
-------------------------------------------------------------------
Data filtering:
5184 data points (29.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5184 data points (29.59%) excluded in total
12336 valid data points (70.41%) remaining.

New sEddyProc class for site 'US-Vcp'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Vcp-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 34 data points (0.19%) set to NA
H: 127 data points (0.72%) set to NA
LE: 164 data points (0.94%) set to NA
NEE: 770 data points (4.39%) set to NA
-------------------------------------------------------------------
Data filtering:
6000 data points (34.25%) excluded by growing season filter
3897 additional data points (22.24%) excluded by precipitation filter (5063
 data points = 28.9 % in total)
9897 data points (56.49%) excluded in total
7623 valid data points (43.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 34 data points (0.19%) set to NA
H: 127 data points (0.72%) set to NA
LE: 164 data points (0.94%) set to NA
NEE: 770 data points (4.39%) set to NA
-------------------------------------------------------------------
Data filtering:
6000 data points (34.25%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6000 data points (34.25%) excluded in total
11520 valid data points (65.75%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
New sEddyProc class for site 'US-Vcp'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Vcp-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 56 data points (0.32%) set to NA
H: 191 data points (1.09%) set to NA
LE: 217 data points (1.24%) set to NA
NEE: 741 data points (4.23%) set to NA
-------------------------------------------------------------------
Data filtering:
6048 data points (34.52%) excluded by growing season filter
2978 additional data points (17%) excluded by precipitation filter (5491
 data points = 31.34 % in total)
9026 data points (51.52%) excluded in total
8494 valid data points (48.48%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 56 data points (0.32%) set to NA
H: 191 data points (1.09%) set to NA
LE: 217 data points (1.24%) set to NA
NEE: 741 data points (4.23%) set to NA
-------------------------------------------------------------------
Data filtering:
6048 data points (34.52%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6048 data points (34.52%) excluded in total
11472 valid data points (65.48%) remaining.

New sEddyProc class for site 'US-Vcp'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Vcp-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 104 data points (0.59%) set to NA
H: 278 data points (1.58%) set to NA
LE: 339 data points (1.93%) set to NA
NEE: 839 data points (4.78%) set to NA
-------------------------------------------------------------------
Data filtering:
5520 data points (31.42%) excluded by growing season filter
3587 additional data points (20.42%) excluded by precipitation filter (5208
 data points = 29.64 % in total)
9107 data points (51.84%) excluded in total
8461 valid data points (48.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 104 data points (0.59%) set to NA
H: 278 data points (1.58%) set to NA
LE: 339 data points (1.93%) set to NA
NEE: 839 data points (4.78%) set to NA
-------------------------------------------------------------------
Data filtering:
5520 data points (31.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5520 data points (31.42%) excluded in total
12048 valid data points (68.58%) remaining.

New sEddyProc class for site 'US-Vcp'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Vcp-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 157 data points (0.9%) set to NA
H: 337 data points (1.92%) set to NA
LE: 373 data points (2.13%) set to NA
NEE: 1006 data points (5.74%) set to NA
-------------------------------------------------------------------
Data filtering:
3408 data points (19.45%) excluded by growing season filter
1075 additional data points (6.14%) excluded by precipitation filter (1434
 data points = 8.18 % in total)
4483 data points (25.59%) excluded in total
13037 valid data points (74.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 157 data points (0.9%) set to NA
H: 337 data points (1.92%) set to NA
LE: 373 data points (2.13%) set to NA
NEE: 1006 data points (5.74%) set to NA
-------------------------------------------------------------------
Data filtering:
3408 data points (19.45%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3408 data points (19.45%) excluded in total
14112 valid data points (80.55%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
New sEddyProc class for site 'US-Vcp'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Vcp-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[290/329] Processing: US-WCr

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-WCr | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 1099 data points (6.27%) set to NA
H: 1125 data points (6.42%) set to NA
LE: 1120 data points (6.39%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7532 additional data points (42.99%) excluded by precipitation filter (7532
 data points = 42.99 % in total)
7532 data points (42.99%) excluded in total
9988 valid data points (57.01%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1099 data points (6.27%) set to NA
H: 1125 data points (6.42%) set to NA
LE: 1120 data points (6.39%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-WCr'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-WCr-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 167 data points (0.95%) set to NA
H: 261 data points (1.49%) set to NA
LE: 2501 data points (14.28%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4854 additional data points (27.71%) excluded by precipitation filter (4854
 data points = 27.71 % in total)
4854 data points (27.71%) excluded in total
12666 valid data points (72.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 167 data points (0.95%) set to NA
H: 261 data points (1.49%) set to NA
LE: 2501 data points (14.28%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-WCr'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-WCr-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 353 data points (2.01%) set to NA
H: 510 data points (2.91%) set to NA
LE: 516 data points (2.95%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6900 additional data points (39.38%) excluded by precipitation filter (6900
 data points = 39.38 % in total)
6900 data points (39.38%) excluded in total
10620 valid data points (60.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 353 data points (2.01%) set to NA
H: 510 data points (2.91%) set to NA
LE: 516 data points (2.95%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-WCr'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-WCr-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 80 data points (0.46%) set to NA
H: 100 data points (0.57%) set to NA
LE: 3228 data points (18.37%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6078 additional data points (34.6%) excluded by precipitation filter (6078
 data points = 34.6 % in total)
6078 data points (34.6%) excluded in total
11490 valid data points (65.4%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 80 data points (0.46%) set to NA
H: 100 data points (0.57%) set to NA
LE: 3228 data points (18.37%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-WCr'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-WCr-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2779 data points (15.86%) set to NA
H: 2016 data points (11.51%) set to NA
LE: 2329 data points (13.29%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5818 additional data points (33.21%) excluded by precipitation filter (5818
 data points = 33.21 % in total)
5818 data points (33.21%) excluded in total
11702 valid data points (66.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2779 data points (15.86%) set to NA
H: 2016 data points (11.51%) set to NA
LE: 2329 data points (13.29%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-WCr'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-WCr-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 710 data points (4.05%) set to NA
H: 749 data points (4.28%) set to NA
LE: 748 data points (4.27%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6304 additional data points (35.98%) excluded by precipitation filter (6304
 data points = 35.98 % in total)
6304 data points (35.98%) excluded in total
11216 valid data points (64.02%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 710 data points (4.05%) set to NA
H: 749 data points (4.28%) set to NA
LE: 748 data points (4.27%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-WCr'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-WCr-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1779 data points (10.15%) set to NA
H: 1803 data points (10.29%) set to NA
LE: 1811 data points (10.34%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6284 additional data points (35.87%) excluded by precipitation filter (6284
 data points = 35.87 % in total)
6284 data points (35.87%) excluded in total
11236 valid data points (64.13%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1779 data points (10.15%) set to NA
H: 1803 data points (10.29%) set to NA
LE: 1811 data points (10.34%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-WCr'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-WCr-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4983 data points (28.36%) set to NA
H: 4954 data points (28.2%) set to NA
LE: 6387 data points (36.36%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6572 additional data points (37.41%) excluded by precipitation filter (6572
 data points = 37.41 % in total)
6572 data points (37.41%) excluded in total
10996 valid data points (62.59%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4983 data points (28.36%) set to NA
H: 4954 data points (28.2%) set to NA
LE: 6387 data points (36.36%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-WCr'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-WCr-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1954 data points (11.15%) set to NA
H: 1982 data points (11.31%) set to NA
LE: 1983 data points (11.32%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6197 additional data points (35.37%) excluded by precipitation filter (6197
 data points = 35.37 % in total)
6197 data points (35.37%) excluded in total
11323 valid data points (64.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1954 data points (11.15%) set to NA
H: 1982 data points (11.31%) set to NA
LE: 1983 data points (11.32%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-WCr'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-WCr-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[291/329] Processing: US-Whs

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Whs | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 0 data points (0%) set to NA
H: 10 data points (0.06%) set to NA
LE: 28 data points (0.16%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1967 additional data points (11.23%) excluded by precipitation filter (1967
 data points = 11.23 % in total)
1967 data points (11.23%) excluded in total
15553 valid data points (88.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 10 data points (0.06%) set to NA
LE: 28 data points (0.16%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Whs'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Whs-2017: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 2 data points (0.01%) set to NA
LE: 5 data points (0.03%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2520 additional data points (14.38%) excluded by precipitation filter (2520
 data points = 14.38 % in total)
2520 data points (14.38%) excluded in total
15000 valid data points (85.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 2 data points (0.01%) set to NA
LE: 5 data points (0.03%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Whs'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Whs-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 17 data points (0.1%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2692 additional data points (15.37%) excluded by precipitation filter (2692
 data points = 15.37 % in total)
2692 data points (15.37%) excluded in total
14828 valid data points (84.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 4 data points (0.02%) set to NA
LE: 17 data points (0.1%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Whs'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Whs-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 6 data points (0.03%) set to NA
LE: 17 data points (0.1%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1998 additional data points (11.37%) excluded by precipitation filter (1998
 data points = 11.37 % in total)
1998 data points (11.37%) excluded in total
15570 valid data points (88.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 6 data points (0.03%) set to NA
LE: 17 data points (0.1%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-Whs'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Whs-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 16 data points (0.09%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2487 additional data points (14.2%) excluded by precipitation filter (2487
 data points = 14.2 % in total)
2487 data points (14.2%) excluded in total
15033 valid data points (85.8%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 16 data points (0.09%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Whs'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Whs-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 20 data points (0.11%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3410 additional data points (19.46%) excluded by precipitation filter (3410
 data points = 19.46 % in total)
3410 data points (19.46%) excluded in total
14110 valid data points (80.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 5 data points (0.03%) set to NA
LE: 20 data points (0.11%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Whs'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Whs-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6 data points (0.03%) set to NA
H: 32 data points (0.18%) set to NA
LE: 45 data points (0.26%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2106 additional data points (12.02%) excluded by precipitation filter (2106
 data points = 12.02 % in total)
2106 data points (12.02%) excluded in total
15414 valid data points (87.98%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6 data points (0.03%) set to NA
H: 32 data points (0.18%) set to NA
LE: 45 data points (0.26%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Whs'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Whs-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 0 data points (0%) set to NA
LE: 8 data points (0.05%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2624 additional data points (14.94%) excluded by precipitation filter (2624
 data points = 14.94 % in total)
2624 data points (14.94%) excluded in total
14944 valid data points (85.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 0 data points (0%) set to NA
LE: 8 data points (0.05%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-Whs'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Whs-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 0 data points (0%) set to NA
H: 7 data points (0.04%) set to NA
LE: 16 data points (0.09%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2214 additional data points (12.64%) excluded by precipitation filter (2214
 data points = 12.64 % in total)
2214 data points (12.64%) excluded in total
15306 valid data points (87.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 0 data points (0%) set to NA
H: 7 data points (0.04%) set to NA
LE: 16 data points (0.09%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-Whs'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fSetQF(sDT, TempVar, QFTempVar, QFTempValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'TA' contains no data after applying quality flag 'TA_QC_OK' with value 0!”
Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Whs-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[292/329] Processing: US-Wjs

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-Wjs | Years: 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 1572 data points (8.97%) set to NA
H: 1596 data points (9.11%) set to NA
LE: 1618 data points (9.24%) set to NA
NEE: 2116 data points (12.08%) set to NA
-------------------------------------------------------------------
Data filtering:
4224 data points (24.11%) excluded by growing season filter
2904 additional data points (16.58%) excluded by precipitation filter (3137
 data points = 17.91 % in total)
7128 data points (40.68%) excluded in total
10392 valid data points (59.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1572 data points (8.97%) set to NA
H: 1596 data points (9.11%) set to NA
LE: 1618 data points (9.24%) set to NA
NEE: 2116 data points (12.08%) set to NA
-------------------------------------------------------------------
Data filtering:
4224 data points (24.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4224 data points (24.11%) excluded in total
13296 valid data points (75.89%) remaining.

New sEddyProc class for site 'US-Wjs'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 310.76.

Regression of reference temperature R_ref for 10 periods.

Quality control:
TA: 2 data points (0.01%) set to NA
H: 29 data points (0.17%) set to NA
LE: 87 data points (0.5%) set to NA
NEE: 427 data points (2.44%) set to NA
-------------------------------------------------------------------
Data filtering:
5904 data points (33.7%) excluded by growing season filter
1912 additional data points (10.91%) excluded by precipitation filter (2456
 data points = 14.02 % in total)
7816 data points (44.61%) excluded in total
9704 valid data points (55.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2 data points (0.01%) set to NA
H: 29 data points (0.17%) set to NA
LE: 87 data points (0.5%) set to NA
NEE: 427 data points (2.44%) set to NA
-------------------------------------------------------------------
Data filtering:
5904 data points (33.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5904 data points (33.7%) excluded in total
11616 valid data points (66.3%) remaining.

New sEddyProc class for site 'US-Wjs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Wjs-2018: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1 data points (0.01%) set to NA
H: 40 data points (0.23%) set to NA
LE: 79 data points (0.45%) set to NA
NEE: 479 data points (2.73%) set to NA
-------------------------------------------------------------------
Data filtering:
5856 data points (33.42%) excluded by growing season filter
2850 additional data points (16.27%) excluded by precipitation filter (3988
 data points = 22.76 % in total)
8706 data points (49.69%) excluded in total
8814 valid data points (50.31%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1 data points (0.01%) set to NA
H: 40 data points (0.23%) set to NA
LE: 79 data points (0.45%) set to NA
NEE: 479 data points (2.73%) set to NA
-------------------------------------------------------------------
Data filtering:
5856 data points (33.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5856 data points (33.42%) excluded in total
11664 valid data points (66.58%) remaining.

New sEddyProc class for site 'US-Wjs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Wjs-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 5 data points (0.03%) set to NA
H: 28 data points (0.16%) set to NA
LE: 59 data points (0.34%) set to NA
NEE: 527 data points (3%) set to NA
-------------------------------------------------------------------
Data filtering:
4992 data points (28.42%) excluded by growing season filter
1765 additional data points (10.05%) excluded by precipitation filter (2446
 data points = 13.92 % in total)
6757 data points (38.46%) excluded in total
10811 valid data points (61.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5 data points (0.03%) set to NA
H: 28 data points (0.16%) set to NA
LE: 59 data points (0.34%) set to NA
NEE: 527 data points (3%) set to NA
-------------------------------------------------------------------
Data filtering:
4992 data points (28.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4992 data points (28.42%) excluded in total
12576 valid data points (71.58%) remaining.

New sEddyProc class for site 'US-Wjs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Wjs-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4 data points (0.02%) set to NA
H: 42 data points (0.24%) set to NA
LE: 113 data points (0.64%) set to NA
NEE: 373 data points (2.13%) set to NA
-------------------------------------------------------------------
Data filtering:
12288 data points (70.14%) excluded by growing season filter
1564 additional data points (8.93%) excluded by precipitation filter (3046
 data points = 17.39 % in total)
13852 data points (79.06%) excluded in total
3668 valid data points (20.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4 data points (0.02%) set to NA
H: 42 data points (0.24%) set to NA
LE: 113 data points (0.64%) set to NA
NEE: 373 data points (2.13%) set to NA
-------------------------------------------------------------------
Data filtering:
12288 data points (70.14%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12288 data points (70.14%) excluded in total
5232 valid data points (29.86%) remaining.

New sEddyProc class for site 'US-Wjs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Wjs-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1 data points (0.01%) set to NA
H: 28 data points (0.16%) set to NA
LE: 71 data points (0.41%) set to NA
NEE: 447 data points (2.55%) set to NA
-------------------------------------------------------------------
Data filtering:
12432 data points (70.96%) excluded by growing season filter
1642 additional data points (9.37%) excluded by precipitation filter (3675
 data points = 20.98 % in total)
14074 data points (80.33%) excluded in total
3446 valid data points (19.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1 data points (0.01%) set to NA
H: 28 data points (0.16%) set to NA
LE: 71 data points (0.41%) set to NA
NEE: 447 data points (2.55%) set to NA
-------------------------------------------------------------------
Data filtering:
12432 data points (70.96%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12432 data points (70.96%) excluded in total
5088 valid data points (29.04%) remaining.

New sEddyProc class for site 'US-Wjs'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-Wjs-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1219 data points (6.96%) set to NA
H: 1242 data points (7.09%) set to NA
LE: 1269 data points (7.24%) set to NA
NEE: 1428 data points (8.15%) set to NA
-------------------------------------------------------------------
Data filtering:
5184 data points (29.59%) excluded by growing season filter
2737 additional data points (15.62%) excluded by precipitation filter (3887
 data points = 22.19 % in total)
7921 data points (45.21%) excluded in total
9599 valid data points (54.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1219 data points (6.96%) set to NA
H: 1242 data points (7.09%) set to NA
LE: 1269 data points (7.24%) set to NA
NEE: 1428 data points (8.15%) set to NA
-------------------------------------------------------------------
Data filtering:
5184 data points (29.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5184 data points (29.59%) excluded in total
12336 valid data points (70.41%) remaining.

New sEddyProc class for site 'US-Wjs'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 180.7.

Regression of reference temperature R_ref for 12 periods.

Quality control:
TA: 675 data points (3.84%) set to NA
H: 741 data points (4.22%) set to NA
LE: 772 data points (4.39%) set to NA
NEE: 1488 data points (8.47%) set to NA
-------------------------------------------------------------------
Data filtering:
6480 data points (36.89%) excluded by growing season filter
2598 additional data points (14.79%) excluded by precipitation filter (3670
 data points = 20.89 % in total)
9078 data points (51.67%) excluded in total
8490 valid data points (48.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 675 data points (3.84%) set to NA
H: 741 data points (4.22%) set to NA
LE: 772 data points (4.39%) set to NA
NEE: 1488 data points (8.47%) set to NA
-------------------------------------------------------------------
Data filtering:
6480 data points (36.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6480 data points (36.89%) excluded in total
11088 valid data points (63.11%) remaining.

New sEddyProc class for site 'US-Wjs'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 226.85.

Regression of reference temperature R_ref for 9 periods.

Quality control:
TA: 4405 data points (25.14%) set to NA
H: 4430 data points (25.29%) set to NA
LE: 4449 data points (25.39%) set to NA
NEE: 4599 data points (26.25%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 82”

-------------------------------------------------------------------
Data filtering:
3024 data points (17.26%) excluded by growing season filter
3295 additional data points (18.81%) excluded by precipitation filter (3445
 data points = 19.66 % in total)
6319 data points (36.07%) excluded in total
11201 valid data points (63.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Ground heat flux G is not provided and set to 0.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4405 data points (25.14%) set to NA
H: 4430 data points (25.29%) set to NA
LE: 4449 data points (25.39%) set to NA
NEE: 4599 data points (26.25%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 82”

-------------------------------------------------------------------
Data filtering:
3024 data points (17.26%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3024 data points (17.26%) excluded in total
14496 valid data points (82.74%) remaining.

New sEddyProc class for site 'US-Wjs'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 126.47.

Regression of reference temperature R_ref for 6 periods.

[293/329] Processing: US-YK1

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-YK1 | Years: 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 17233 data points (98.36%) set to NA
H: 15355 data points (87.64%) set to NA
LE: 15384 data points (87.81%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6870 additional data points (39.21%) excluded by precipitation filter (6870
 data points = 39.21 % in total)
6870 data points (39.21%) excluded in total
10650 valid data points (60.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Quality control:
TA: 17233 data points (98.36%) set to NA
H: 15355 data points (87.64%) set to NA
LE: 15384 data points (87.81%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-YK1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-YK1-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 12940 data points (73.66%) set to NA
H: 9262 data points (52.72%) set to NA
LE: 9458 data points (53.84%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5351 additional data points (30.46%) excluded by precipitation filter (5351
 data points = 30.46 % in total)
5351 data points (30.46%) excluded in total
12217 valid data points (69.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12940 data points (73.66%) set to NA
H: 9262 data points (52.72%) set to NA
LE: 9458 data points (53.84%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-YK1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-YK1-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 7682 data points (43.85%) set to NA
H: 9343 data points (53.33%) set to NA
LE: 9644 data points (55.05%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4975 additional data points (28.4%) excluded by precipitation filter (4975
 data points = 28.4 % in total)
4975 data points (28.4%) excluded in total
12545 valid data points (71.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7682 data points (43.85%) set to NA
H: 9343 data points (53.33%) set to NA
LE: 9644 data points (55.05%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-YK1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-YK1-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2220 data points (12.67%) set to NA
H: 4358 data points (24.87%) set to NA
LE: 3705 data points (21.15%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5085 additional data points (29.02%) excluded by precipitation filter (5085
 data points = 29.02 % in total)
5085 data points (29.02%) excluded in total
12435 valid data points (70.98%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2220 data points (12.67%) set to NA
H: 4358 data points (24.87%) set to NA
LE: 3705 data points (21.15%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-YK1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-YK1-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 7687 data points (43.88%) set to NA
H: 7782 data points (44.42%) set to NA
LE: 7779 data points (44.4%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5092 additional data points (29.06%) excluded by precipitation filter (5092
 data points = 29.06 % in total)
5092 data points (29.06%) excluded in total
12428 valid data points (70.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7687 data points (43.88%) set to NA
H: 7782 data points (44.42%) set to NA
LE: 7779 data points (44.4%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-YK1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-YK1-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 8399 data points (47.81%) set to NA
H: 7868 data points (44.79%) set to NA
LE: 7883 data points (44.87%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5230 additional data points (29.77%) excluded by precipitation filter (5230
 data points = 29.77 % in total)
5230 data points (29.77%) excluded in total
12338 valid data points (70.23%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8399 data points (47.81%) set to NA
H: 7868 data points (44.79%) set to NA
LE: 7883 data points (44.87%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-YK1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-YK1-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 9441 data points (53.89%) set to NA
H: 10089 data points (57.59%) set to NA
LE: 13778 data points (78.64%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5124 additional data points (29.25%) excluded by precipitation filter (5124
 data points = 29.25 % in total)
5124 data points (29.25%) excluded in total
12396 valid data points (70.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9441 data points (53.89%) set to NA
H: 10089 data points (57.59%) set to NA
LE: 13778 data points (78.64%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-YK1'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-YK1-2025: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[294/329] Processing: US-YK2

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-YK2 | Years: 2019, 2020, 2021, 2022, 2023, 2024, 2025
Quality control:
TA: 10572 data points (60.34%) set to NA
H: 10611 data points (60.57%) set to NA
LE: 10615 data points (60.59%) set to NA
NEE: 10669 data points (60.9%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 186”

-------------------------------------------------------------------
Data filtering:
4704 data points (26.85%) excluded by growing season filter
5751 additional data points (32.83%) excluded by precipitation filter (7134
 data points = 40.72 % in total)
10455 data points (59.67%) excluded in total
7065 valid data points (40.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10572 data points (60.34%) set to NA
H: 10611 data points (60.57%) set to NA
LE: 10615 data points (60.59%) set to NA
NEE: 10669 data points (60.9%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 186”

-------------------------------------------------------------------
Data filtering:
4704 data points (26.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4704 data points (26.85%) excluded in total
12816 valid data points (73.15%) remaining.

New sEddyProc class for site 'US-YK2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 159.53.

Regression of reference temperature R_ref for 14 periods.

Quality control:
TA: 4278 data points (24.35%) set to NA
H: 4346 data points (24.74%) set to NA
LE: 4434 data points (25.24%) set to NA
NEE: 4574 data points (26.04%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.02%) excluded by growing season filter
2586 additional data points (14.72%) excluded by precipitation filter (5598
 data points = 31.86 % in total)
13482 data points (76.74%) excluded in total
4086 valid data points (23.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4278 data points (24.35%) set to NA
H: 4346 data points (24.74%) set to NA
LE: 4434 data points (25.24%) set to NA
NEE: 4574 data points (26.04%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.02%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10896 data points (62.02%) excluded in total
6672 valid data points (37.98%) remaining.

New sEddyProc class for site 'US-YK2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 126.5.

Regression of reference temperature R_ref for 28 periods.

Quality control:
TA: 10426 data points (59.51%) set to NA
H: 12203 data points (69.65%) set to NA
LE: 12219 data points (69.74%) set to NA
NEE: 12329 data points (70.37%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 121”

-------------------------------------------------------------------
Data filtering:
9168 data points (52.33%) excluded by growing season filter
3214 additional data points (18.34%) excluded by precipitation filter (5631
 data points = 32.14 % in total)
12382 data points (70.67%) excluded in total
5138 valid data points (29.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10426 data points (59.51%) set to NA
H: 12203 data points (69.65%) set to NA
LE: 12219 data points (69.74%) set to NA
NEE: 12329 data points (70.37%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 121”

-------------------------------------------------------------------
Data filtering:
9168 data points (52.33%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9168 data points (52.33%) excluded in total
8352 valid data points (47.67%) remaining.

New sEddyProc class for site 'US-YK2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 106.9.

Regression of reference temperature R_ref for 43 periods.

Quality control:
TA: 4233 data points (24.16%) set to NA
H: 2715 data points (15.5%) set to NA
LE: 2681 data points (15.3%) set to NA
NEE: 3316 data points (18.93%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.47%) excluded by growing season filter
2518 additional data points (14.37%) excluded by precipitation filter (5195
 data points = 29.65 % in total)
13462 data points (76.84%) excluded in total
4058 valid data points (23.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4233 data points (24.16%) set to NA
H: 2715 data points (15.5%) set to NA
LE: 2681 data points (15.3%) set to NA
NEE: 3316 data points (18.93%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.47%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10944 data points (62.47%) excluded in total
6576 valid data points (37.53%) remaining.

New sEddyProc class for site 'US-YK2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 45.57.

Regression of reference temperature R_ref for 39 periods.

Quality control:
TA: 5784 data points (33.01%) set to NA
H: 5616 data points (32.05%) set to NA
LE: 5606 data points (32%) set to NA
NEE: 5732 data points (32.72%) set to NA
-------------------------------------------------------------------
Data filtering:
11760 data points (67.12%) excluded by growing season filter
3034 additional data points (17.32%) excluded by precipitation filter (4881
 data points = 27.86 % in total)
14794 data points (84.44%) excluded in total
2726 valid data points (15.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 5784 data points (33.01%) set to NA
H: 5616 data points (32.05%) set to NA
LE: 5606 data points (32%) set to NA
NEE: 5732 data points (32.72%) set to NA
-------------------------------------------------------------------
Data filtering:
11760 data points (67.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11760 data points (67.12%) excluded in total
5760 valid data points (32.88%) remaining.

New sEddyProc class for site 'US-YK2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 62.48.

Regression of reference temperature R_ref for 39 periods.

Quality control:
TA: 10304 data points (58.65%) set to NA
H: 11458 data points (65.22%) set to NA
LE: 11375 data points (64.75%) set to NA
NEE: 11586 data points (65.95%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 136”

-------------------------------------------------------------------
Data filtering:
4608 data points (26.23%) excluded by growing season filter
4585 additional data points (26.1%) excluded by precipitation filter (6014
 data points = 34.23 % in total)
9193 data points (52.33%) excluded in total
8375 valid data points (47.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 10304 data points (58.65%) set to NA
H: 11458 data points (65.22%) set to NA
LE: 11375 data points (64.75%) set to NA
NEE: 11586 data points (65.95%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 136”

-------------------------------------------------------------------
Data filtering:
4608 data points (26.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4608 data points (26.23%) excluded in total
12960 valid data points (73.77%) remaining.

New sEddyProc class for site 'US-YK2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 90.34.

Regression of reference temperature R_ref for 35 periods.

Quality control:
TA: 12373 data points (70.62%) set to NA
H: 13180 data points (75.23%) set to NA
LE: 13017 data points (74.3%) set to NA
NEE: 13414 data points (76.56%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5869 additional data points (33.5%) excluded by precipitation filter (5869
 data points = 33.5 % in total)
5869 data points (33.5%) excluded in total
11651 valid data points (66.5%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12373 data points (70.62%) set to NA
H: 13180 data points (75.23%) set to NA
LE: 13017 data points (74.3%) set to NA
NEE: 13414 data points (76.56%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-YK2'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 99.58.

Regression of reference temperature R_ref for 20 periods.

[295/329] Processing: US-xAB

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xAB | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 286 data points (1.63%) set to NA
H: 4603 data points (26.27%) set to NA
LE: 4613 data points (26.33%) set to NA
NEE: 9937 data points (56.72%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 76”

-------------------------------------------------------------------
Data filtering:
5904 data points (33.7%) excluded by growing season filter
4089 additional data points (23.34%) excluded by precipitation filter (7423
 data points = 42.37 % in total)
9993 data points (57.04%) excluded in total
7527 valid data points (42.96%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 286 data points (1.63%) set to NA
H: 4603 data points (26.27%) set to NA
LE: 4613 data points (26.33%) set to NA
NEE: 9937 data points (56.72%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 76”

-------------------------------------------------------------------
Data filtering:
5904 data points (33.7%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5904 data points (33.7%) excluded in total
11616 valid data points (66.3%) remaining.

New sEddyProc class for site 'US-xAB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xAB-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 41 data points (0.23%) set to NA
H: 3738 data points (21.28%) set to NA
LE: 3732 data points (21.24%) set to NA
NEE: 9725 data points (55.36%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 123”

-------------------------------------------------------------------
Data filtering:
4176 data points (23.77%) excluded by growing season filter
4963 additional data points (28.25%) excluded by precipitation filter (8532
 data points = 48.57 % in total)
9139 data points (52.02%) excluded in total
8429 valid data points (47.98%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 41 data points (0.23%) set to NA
H: 3738 data points (21.28%) set to NA
LE: 3732 data points (21.24%) set to NA
NEE: 9725 data points (55.36%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 123”

-------------------------------------------------------------------
Data filtering:
4176 data points (23.77%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4176 data points (23.77%) excluded in total
13392 valid data points (76.23%) remaining.

New sEddyProc class for site 'US-xAB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xAB-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 75 data points (0.43%) set to NA
H: 170 data points (0.97%) set to NA
LE: 167 data points (0.95%) set to NA
NEE: 1585 data points (9.05%) set to NA
-------------------------------------------------------------------
Data filtering:
7776 data points (44.38%) excluded by growing season filter
2726 additional data points (15.56%) excluded by precipitation filter (8828
 data points = 50.39 % in total)
10502 data points (59.94%) excluded in total
7018 valid data points (40.06%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 75 data points (0.43%) set to NA
H: 170 data points (0.97%) set to NA
LE: 167 data points (0.95%) set to NA
NEE: 1585 data points (9.05%) set to NA
-------------------------------------------------------------------
Data filtering:
7776 data points (44.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7776 data points (44.38%) excluded in total
9744 valid data points (55.62%) remaining.

New sEddyProc class for site 'US-xAB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xAB-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 155 data points (0.88%) set to NA
H: 306 data points (1.75%) set to NA
LE: 299 data points (1.71%) set to NA
NEE: 1821 data points (10.39%) set to NA
-------------------------------------------------------------------
Data filtering:
6144 data points (35.07%) excluded by growing season filter
4302 additional data points (24.55%) excluded by precipitation filter (7963
 data points = 45.45 % in total)
10446 data points (59.62%) excluded in total
7074 valid data points (40.38%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 155 data points (0.88%) set to NA
H: 306 data points (1.75%) set to NA
LE: 299 data points (1.71%) set to NA
NEE: 1821 data points (10.39%) set to NA
-------------------------------------------------------------------
Data filtering:
6144 data points (35.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6144 data points (35.07%) excluded in total
11376 valid data points (64.93%) remaining.

New sEddyProc class for site 'US-xAB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xAB-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 168 data points (0.96%) set to NA
H: 2674 data points (15.26%) set to NA
LE: 2805 data points (16.01%) set to NA
NEE: 5286 data points (30.17%) set to NA
-------------------------------------------------------------------
Data filtering:
8592 data points (49.04%) excluded by growing season filter
3188 additional data points (18.2%) excluded by precipitation filter (8076
 data points = 46.1 % in total)
11780 data points (67.24%) excluded in total
5740 valid data points (32.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 168 data points (0.96%) set to NA
H: 2674 data points (15.26%) set to NA
LE: 2805 data points (16.01%) set to NA
NEE: 5286 data points (30.17%) set to NA
-------------------------------------------------------------------
Data filtering:
8592 data points (49.04%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8592 data points (49.04%) excluded in total
8928 valid data points (50.96%) remaining.

New sEddyProc class for site 'US-xAB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xAB-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2051 data points (11.67%) set to NA
H: 3071 data points (17.48%) set to NA
LE: 3259 data points (18.55%) set to NA
NEE: 8600 data points (48.95%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 83”

-------------------------------------------------------------------
Data filtering:
3600 data points (20.49%) excluded by growing season filter
5818 additional data points (33.12%) excluded by precipitation filter (7690
 data points = 43.77 % in total)
9418 data points (53.61%) excluded in total
8150 valid data points (46.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2051 data points (11.67%) set to NA
H: 3071 data points (17.48%) set to NA
LE: 3259 data points (18.55%) set to NA
NEE: 8600 data points (48.95%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 83”

-------------------------------------------------------------------
Data filtering:
3600 data points (20.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3600 data points (20.49%) excluded in total
13968 valid data points (79.51%) remaining.

New sEddyProc class for site 'US-xAB'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 40.08.

Regression of reference temperature R_ref for 11 periods.

[296/329] Processing: US-xBA

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xBA | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 921 data points (5.26%) set to NA
H: 4278 data points (24.42%) set to NA
LE: 4300 data points (24.54%) set to NA
NEE: 7705 data points (43.98%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
671 additional data points (3.83%) excluded by precipitation filter (671
 data points = 3.83 % in total)
671 data points (3.83%) excluded in total
16849 valid data points (96.17%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 921 data points (5.26%) set to NA
H: 4278 data points (24.42%) set to NA
LE: 4300 data points (24.54%) set to NA
NEE: 7705 data points (43.98%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xBA'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 8 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBA-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 81 data points (0.46%) set to NA
H: 2916 data points (16.6%) set to NA
LE: 3038 data points (17.29%) set to NA
NEE: 5689 data points (32.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1502 additional data points (8.55%) excluded by precipitation filter (1502
 data points = 8.55 % in total)
1502 data points (8.55%) excluded in total
16066 valid data points (91.45%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 81 data points (0.46%) set to NA
H: 2916 data points (16.6%) set to NA
LE: 3038 data points (17.29%) set to NA
NEE: 5689 data points (32.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-xBA'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBA-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1618 data points (9.24%) set to NA
H: 5502 data points (31.4%) set to NA
LE: 5580 data points (31.85%) set to NA
NEE: 8730 data points (49.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1597 additional data points (9.12%) excluded by precipitation filter (1597
 data points = 9.12 % in total)
1597 data points (9.12%) excluded in total
15923 valid data points (90.88%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1618 data points (9.24%) set to NA
H: 5502 data points (31.4%) set to NA
LE: 5580 data points (31.85%) set to NA
NEE: 8730 data points (49.83%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xBA'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBA-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 160 data points (0.91%) set to NA
H: 10802 data points (61.66%) set to NA
LE: 10760 data points (61.42%) set to NA
NEE: 11805 data points (67.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1968 additional data points (11.23%) excluded by precipitation filter (1968
 data points = 11.23 % in total)
1968 data points (11.23%) excluded in total
15552 valid data points (88.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 160 data points (0.91%) set to NA
H: 10802 data points (61.66%) set to NA
LE: 10760 data points (61.42%) set to NA
NEE: 11805 data points (67.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xBA'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBA-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 603 data points (3.44%) set to NA
H: 3742 data points (21.36%) set to NA
LE: 3783 data points (21.59%) set to NA
NEE: 4022 data points (22.96%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2744 additional data points (15.66%) excluded by precipitation filter (2744
 data points = 15.66 % in total)
2744 data points (15.66%) excluded in total
14776 valid data points (84.34%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 603 data points (3.44%) set to NA
H: 3742 data points (21.36%) set to NA
LE: 3783 data points (21.59%) set to NA
NEE: 4022 data points (22.96%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xBA'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBA-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1752 data points (9.97%) set to NA
H: 7313 data points (41.63%) set to NA
LE: 7309 data points (41.6%) set to NA
NEE: 8305 data points (47.27%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2232 additional data points (12.7%) excluded by precipitation filter (2232
 data points = 12.7 % in total)
2232 data points (12.7%) excluded in total
15336 valid data points (87.3%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1752 data points (9.97%) set to NA
H: 7313 data points (41.63%) set to NA
LE: 7309 data points (41.6%) set to NA
NEE: 8305 data points (47.27%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-xBA'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBA-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[297/329] Processing: US-xBL

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xBL | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 281 data points (1.6%) set to NA
H: 11028 data points (62.95%) set to NA
LE: 10843 data points (61.89%) set to NA
NEE: 14448 data points (82.47%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6269 additional data points (35.78%) excluded by precipitation filter (6269
 data points = 35.78 % in total)
6269 data points (35.78%) excluded in total
11251 valid data points (64.22%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 281 data points (1.6%) set to NA
H: 11028 data points (62.95%) set to NA
LE: 10843 data points (61.89%) set to NA
NEE: 14448 data points (82.47%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xBL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBL-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 228 data points (1.3%) set to NA
H: 4891 data points (27.84%) set to NA
LE: 4898 data points (27.88%) set to NA
NEE: 7917 data points (45.06%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 71”

-------------------------------------------------------------------
Data filtering:
8928 data points (50.82%) excluded by growing season filter
2504 additional data points (14.25%) excluded by precipitation filter (5076
 data points = 28.89 % in total)
11432 data points (65.07%) excluded in total
6136 valid data points (34.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 228 data points (1.3%) set to NA
H: 4891 data points (27.84%) set to NA
LE: 4898 data points (27.88%) set to NA
NEE: 7917 data points (45.06%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 71”

-------------------------------------------------------------------
Data filtering:
8928 data points (50.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8928 data points (50.82%) excluded in total
8640 valid data points (49.18%) remaining.

New sEddyProc class for site 'US-xBL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBL-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 28 data points (0.16%) set to NA
H: 349 data points (1.99%) set to NA
LE: 343 data points (1.96%) set to NA
NEE: 1722 data points (9.83%) set to NA
-------------------------------------------------------------------
Data filtering:
7488 data points (42.74%) excluded by growing season filter
3677 additional data points (20.99%) excluded by precipitation filter (5875
 data points = 33.53 % in total)
11165 data points (63.73%) excluded in total
6355 valid data points (36.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 28 data points (0.16%) set to NA
H: 349 data points (1.99%) set to NA
LE: 343 data points (1.96%) set to NA
NEE: 1722 data points (9.83%) set to NA
-------------------------------------------------------------------
Data filtering:
7488 data points (42.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7488 data points (42.74%) excluded in total
10032 valid data points (57.26%) remaining.

New sEddyProc class for site 'US-xBL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBL-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 21 data points (0.12%) set to NA
H: 420 data points (2.4%) set to NA
LE: 397 data points (2.27%) set to NA
NEE: 1416 data points (8.08%) set to NA
-------------------------------------------------------------------
Data filtering:
8160 data points (46.58%) excluded by growing season filter
3528 additional data points (20.14%) excluded by precipitation filter (5824
 data points = 33.24 % in total)
11688 data points (66.71%) excluded in total
5832 valid data points (33.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 21 data points (0.12%) set to NA
H: 420 data points (2.4%) set to NA
LE: 397 data points (2.27%) set to NA
NEE: 1416 data points (8.08%) set to NA
-------------------------------------------------------------------
Data filtering:
8160 data points (46.58%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8160 data points (46.58%) excluded in total
9360 valid data points (53.42%) remaining.

New sEddyProc class for site 'US-xBL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBL-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 15 data points (0.09%) set to NA
H: 1166 data points (6.66%) set to NA
LE: 1145 data points (6.54%) set to NA
NEE: 2095 data points (11.96%) set to NA
-------------------------------------------------------------------
Data filtering:
7344 data points (41.92%) excluded by growing season filter
2902 additional data points (16.56%) excluded by precipitation filter (4988
 data points = 28.47 % in total)
10246 data points (58.48%) excluded in total
7274 valid data points (41.52%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 15 data points (0.09%) set to NA
H: 1166 data points (6.66%) set to NA
LE: 1145 data points (6.54%) set to NA
NEE: 2095 data points (11.96%) set to NA
-------------------------------------------------------------------
Data filtering:
7344 data points (41.92%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7344 data points (41.92%) excluded in total
10176 valid data points (58.08%) remaining.

New sEddyProc class for site 'US-xBL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBL-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 48 data points (0.27%) set to NA
H: 871 data points (4.96%) set to NA
LE: 887 data points (5.05%) set to NA
NEE: 3636 data points (20.7%) set to NA
-------------------------------------------------------------------
Data filtering:
7824 data points (44.54%) excluded by growing season filter
3190 additional data points (18.16%) excluded by precipitation filter (5700
 data points = 32.45 % in total)
11014 data points (62.69%) excluded in total
6554 valid data points (37.31%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 48 data points (0.27%) set to NA
H: 871 data points (4.96%) set to NA
LE: 887 data points (5.05%) set to NA
NEE: 3636 data points (20.7%) set to NA
-------------------------------------------------------------------
Data filtering:
7824 data points (44.54%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7824 data points (44.54%) excluded in total
9744 valid data points (55.46%) remaining.

New sEddyProc class for site 'US-xBL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBL-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[298/329] Processing: US-xBN

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xBN | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 49 data points (0.28%) set to NA
H: 2157 data points (12.31%) set to NA
LE: 2165 data points (12.36%) set to NA
NEE: 3620 data points (20.66%) set to NA
-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
1964 additional data points (11.21%) excluded by precipitation filter (4504
 data points = 25.71 % in total)
13052 data points (74.5%) excluded in total
4468 valid data points (25.5%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 49 data points (0.28%) set to NA
H: 2157 data points (12.31%) set to NA
LE: 2165 data points (12.36%) set to NA
NEE: 3620 data points (20.66%) set to NA
-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11088 data points (63.29%) excluded in total
6432 valid data points (36.71%) remaining.

New sEddyProc class for site 'US-xBN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBN-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 47 data points (0.27%) set to NA
H: 5515 data points (31.39%) set to NA
LE: 5526 data points (31.45%) set to NA
NEE: 6079 data points (34.6%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 53”

-------------------------------------------------------------------
Data filtering:
7776 data points (44.26%) excluded by growing season filter
4366 additional data points (24.85%) excluded by precipitation filter (5580
 data points = 31.76 % in total)
12142 data points (69.11%) excluded in total
5426 valid data points (30.89%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 47 data points (0.27%) set to NA
H: 5515 data points (31.39%) set to NA
LE: 5526 data points (31.45%) set to NA
NEE: 6079 data points (34.6%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 53”

-------------------------------------------------------------------
Data filtering:
7776 data points (44.26%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7776 data points (44.26%) excluded in total
9792 valid data points (55.74%) remaining.

New sEddyProc class for site 'US-xBN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBN-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 93 data points (0.53%) set to NA
H: 162 data points (0.92%) set to NA
LE: 164 data points (0.94%) set to NA
NEE: 458 data points (2.61%) set to NA
-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
2140 additional data points (12.21%) excluded by precipitation filter (4968
 data points = 28.36 % in total)
13372 data points (76.32%) excluded in total
4148 valid data points (23.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 93 data points (0.53%) set to NA
H: 162 data points (0.92%) set to NA
LE: 164 data points (0.94%) set to NA
NEE: 458 data points (2.61%) set to NA
-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11232 data points (64.11%) excluded in total
6288 valid data points (35.89%) remaining.

New sEddyProc class for site 'US-xBN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBN-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 191 data points (1.09%) set to NA
H: 2519 data points (14.38%) set to NA
LE: 2504 data points (14.29%) set to NA
NEE: 3184 data points (18.17%) set to NA
-------------------------------------------------------------------
Data filtering:
10992 data points (62.74%) excluded by growing season filter
2250 additional data points (12.84%) excluded by precipitation filter (5664
 data points = 32.33 % in total)
13242 data points (75.58%) excluded in total
4278 valid data points (24.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 191 data points (1.09%) set to NA
H: 2519 data points (14.38%) set to NA
LE: 2504 data points (14.29%) set to NA
NEE: 3184 data points (18.17%) set to NA
-------------------------------------------------------------------
Data filtering:
10992 data points (62.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10992 data points (62.74%) excluded in total
6528 valid data points (37.26%) remaining.

New sEddyProc class for site 'US-xBN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBN-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 61 data points (0.35%) set to NA
H: 3021 data points (17.24%) set to NA
LE: 3014 data points (17.2%) set to NA
NEE: 3160 data points (18.04%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
2870 additional data points (16.38%) excluded by precipitation filter (7678
 data points = 43.82 % in total)
13670 data points (78.03%) excluded in total
3850 valid data points (21.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 61 data points (0.35%) set to NA
H: 3021 data points (17.24%) set to NA
LE: 3014 data points (17.2%) set to NA
NEE: 3160 data points (18.04%) set to NA
-------------------------------------------------------------------
Data filtering:
10800 data points (61.64%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10800 data points (61.64%) excluded in total
6720 valid data points (38.36%) remaining.

New sEddyProc class for site 'US-xBN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBN-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 775 data points (4.41%) set to NA
H: 1465 data points (8.34%) set to NA
LE: 1461 data points (8.32%) set to NA
NEE: 2227 data points (12.68%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (59.84%) excluded by growing season filter
3126 additional data points (17.79%) excluded by precipitation filter (6784
 data points = 38.62 % in total)
13638 data points (77.63%) excluded in total
3930 valid data points (22.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 775 data points (4.41%) set to NA
H: 1465 data points (8.34%) set to NA
LE: 1461 data points (8.32%) set to NA
NEE: 2227 data points (12.68%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (59.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10512 data points (59.84%) excluded in total
7056 valid data points (40.16%) remaining.

New sEddyProc class for site 'US-xBN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBN-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[299/329] Processing: US-xBR

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xBR | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 610 data points (3.48%) set to NA
H: 1248 data points (7.12%) set to NA
LE: 1243 data points (7.09%) set to NA
NEE: 2797 data points (15.96%) set to NA
-------------------------------------------------------------------
Data filtering:
10752 data points (61.37%) excluded by growing season filter
2262 additional data points (12.91%) excluded by precipitation filter (6307
 data points = 36 % in total)
13014 data points (74.28%) excluded in total
4506 valid data points (25.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 610 data points (3.48%) set to NA
H: 1248 data points (7.12%) set to NA
LE: 1243 data points (7.09%) set to NA
NEE: 2797 data points (15.96%) set to NA
-------------------------------------------------------------------
Data filtering:
10752 data points (61.37%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10752 data points (61.37%) excluded in total
6768 valid data points (38.63%) remaining.

New sEddyProc class for site 'US-xBR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBR-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 196 data points (1.12%) set to NA
H: 4015 data points (22.85%) set to NA
LE: 3998 data points (22.76%) set to NA
NEE: 5855 data points (33.33%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 33”

-------------------------------------------------------------------
Data filtering:
10800 data points (61.48%) excluded by growing season filter
1698 additional data points (9.67%) excluded by precipitation filter (6092
 data points = 34.68 % in total)
12498 data points (71.14%) excluded in total
5070 valid data points (28.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 196 data points (1.12%) set to NA
H: 4015 data points (22.85%) set to NA
LE: 3998 data points (22.76%) set to NA
NEE: 5855 data points (33.33%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 33”

-------------------------------------------------------------------
Data filtering:
10800 data points (61.48%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10800 data points (61.48%) excluded in total
6768 valid data points (38.52%) remaining.

New sEddyProc class for site 'US-xBR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBR-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 39 data points (0.22%) set to NA
H: 168 data points (0.96%) set to NA
LE: 163 data points (0.93%) set to NA
NEE: 1766 data points (10.08%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.53%) excluded by growing season filter
2883 additional data points (16.46%) excluded by precipitation filter (6619
 data points = 37.78 % in total)
12963 data points (73.99%) excluded in total
4557 valid data points (26.01%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 39 data points (0.22%) set to NA
H: 168 data points (0.96%) set to NA
LE: 163 data points (0.93%) set to NA
NEE: 1766 data points (10.08%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.53%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10080 data points (57.53%) excluded in total
7440 valid data points (42.47%) remaining.

New sEddyProc class for site 'US-xBR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBR-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 14 data points (0.08%) set to NA
H: 167 data points (0.95%) set to NA
LE: 190 data points (1.08%) set to NA
NEE: 1433 data points (8.18%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
2693 additional data points (15.37%) excluded by precipitation filter (6173
 data points = 35.23 % in total)
12965 data points (74%) excluded in total
4555 valid data points (26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 14 data points (0.08%) set to NA
H: 167 data points (0.95%) set to NA
LE: 190 data points (1.08%) set to NA
NEE: 1433 data points (8.18%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10272 data points (58.63%) excluded in total
7248 valid data points (41.37%) remaining.

New sEddyProc class for site 'US-xBR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBR-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 8 data points (0.05%) set to NA
H: 97 data points (0.55%) set to NA
LE: 86 data points (0.49%) set to NA
NEE: 1099 data points (6.27%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
3243 additional data points (18.51%) excluded by precipitation filter (7211
 data points = 41.16 % in total)
13515 data points (77.14%) excluded in total
4005 valid data points (22.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8 data points (0.05%) set to NA
H: 97 data points (0.55%) set to NA
LE: 86 data points (0.49%) set to NA
NEE: 1099 data points (6.27%) set to NA
-------------------------------------------------------------------
Data filtering:
10272 data points (58.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10272 data points (58.63%) excluded in total
7248 valid data points (41.37%) remaining.

New sEddyProc class for site 'US-xBR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBR-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 70 data points (0.4%) set to NA
H: 1660 data points (9.45%) set to NA
LE: 1669 data points (9.5%) set to NA
NEE: 5681 data points (32.34%) set to NA
-------------------------------------------------------------------
Data filtering:
9168 data points (52.19%) excluded by growing season filter
3171 additional data points (18.05%) excluded by precipitation filter (6801
 data points = 38.71 % in total)
12339 data points (70.24%) excluded in total
5229 valid data points (29.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 70 data points (0.4%) set to NA
H: 1660 data points (9.45%) set to NA
LE: 1669 data points (9.5%) set to NA
NEE: 5681 data points (32.34%) set to NA
-------------------------------------------------------------------
Data filtering:
9168 data points (52.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9168 data points (52.19%) excluded in total
8400 valid data points (47.81%) remaining.

New sEddyProc class for site 'US-xBR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xBR-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[300/329] Processing: US-xDJ

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xDJ | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 111 data points (0.63%) set to NA
H: 5111 data points (29.17%) set to NA
LE: 5398 data points (30.81%) set to NA
NEE: 6187 data points (35.31%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 23”

-------------------------------------------------------------------
Data filtering:
9648 data points (55.07%) excluded by growing season filter
3928 additional data points (22.42%) excluded by precipitation filter (5345
 data points = 30.51 % in total)
13576 data points (77.49%) excluded in total
3944 valid data points (22.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 111 data points (0.63%) set to NA
H: 5111 data points (29.17%) set to NA
LE: 5398 data points (30.81%) set to NA
NEE: 6187 data points (35.31%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 23”

-------------------------------------------------------------------
Data filtering:
9648 data points (55.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9648 data points (55.07%) excluded in total
7872 valid data points (44.93%) remaining.

New sEddyProc class for site 'US-xDJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xDJ-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 58 data points (0.33%) set to NA
H: 1294 data points (7.37%) set to NA
LE: 1304 data points (7.42%) set to NA
NEE: 1652 data points (9.4%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.3%) excluded by growing season filter
2957 additional data points (16.83%) excluded by precipitation filter (4236
 data points = 24.11 % in total)
13901 data points (79.13%) excluded in total
3667 valid data points (20.87%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 58 data points (0.33%) set to NA
H: 1294 data points (7.37%) set to NA
LE: 1304 data points (7.42%) set to NA
NEE: 1652 data points (9.4%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10944 data points (62.3%) excluded in total
6624 valid data points (37.7%) remaining.

New sEddyProc class for site 'US-xDJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xDJ-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6 data points (0.03%) set to NA
H: 324 data points (1.85%) set to NA
LE: 304 data points (1.74%) set to NA
NEE: 704 data points (4.02%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (60%) excluded by growing season filter
3146 additional data points (17.96%) excluded by precipitation filter (4265
 data points = 24.34 % in total)
13658 data points (77.96%) excluded in total
3862 valid data points (22.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6 data points (0.03%) set to NA
H: 324 data points (1.85%) set to NA
LE: 304 data points (1.74%) set to NA
NEE: 704 data points (4.02%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (60%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10512 data points (60%) excluded in total
7008 valid data points (40%) remaining.

New sEddyProc class for site 'US-xDJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xDJ-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 61 data points (0.35%) set to NA
H: 528 data points (3.01%) set to NA
LE: 530 data points (3.03%) set to NA
NEE: 1586 data points (9.05%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (60%) excluded by growing season filter
1596 additional data points (9.11%) excluded by precipitation filter (2820
 data points = 16.1 % in total)
12108 data points (69.11%) excluded in total
5412 valid data points (30.89%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 61 data points (0.35%) set to NA
H: 528 data points (3.01%) set to NA
LE: 530 data points (3.03%) set to NA
NEE: 1586 data points (9.05%) set to NA
-------------------------------------------------------------------
Data filtering:
10512 data points (60%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10512 data points (60%) excluded in total
7008 valid data points (40%) remaining.

New sEddyProc class for site 'US-xDJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xDJ-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 152 data points (0.87%) set to NA
H: 711 data points (4.06%) set to NA
LE: 726 data points (4.14%) set to NA
NEE: 1383 data points (7.89%) set to NA
-------------------------------------------------------------------
Data filtering:
10992 data points (62.74%) excluded by growing season filter
1938 additional data points (11.06%) excluded by precipitation filter (3042
 data points = 17.36 % in total)
12930 data points (73.8%) excluded in total
4590 valid data points (26.2%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 152 data points (0.87%) set to NA
H: 711 data points (4.06%) set to NA
LE: 726 data points (4.14%) set to NA
NEE: 1383 data points (7.89%) set to NA
-------------------------------------------------------------------
Data filtering:
10992 data points (62.74%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10992 data points (62.74%) excluded in total
6528 valid data points (37.26%) remaining.

New sEddyProc class for site 'US-xDJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xDJ-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 14 data points (0.08%) set to NA
H: 1549 data points (8.82%) set to NA
LE: 1545 data points (8.79%) set to NA
NEE: 2187 data points (12.45%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.38%) excluded by growing season filter
3030 additional data points (17.25%) excluded by precipitation filter (3852
 data points = 21.93 % in total)
13110 data points (74.62%) excluded in total
4458 valid data points (25.38%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 14 data points (0.08%) set to NA
H: 1549 data points (8.82%) set to NA
LE: 1545 data points (8.79%) set to NA
NEE: 2187 data points (12.45%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10080 data points (57.38%) excluded in total
7488 valid data points (42.62%) remaining.

New sEddyProc class for site 'US-xDJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xDJ-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[301/329] Processing: US-xDL

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xDL | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 87 data points (0.5%) set to NA
H: 15793 data points (90.14%) set to NA
LE: 15809 data points (90.23%) set to NA
NEE: 15852 data points (90.48%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5535 additional data points (31.59%) excluded by precipitation filter (5535
 data points = 31.59 % in total)
5535 data points (31.59%) excluded in total
11985 valid data points (68.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 87 data points (0.5%) set to NA
H: 15793 data points (90.14%) set to NA
LE: 15809 data points (90.23%) set to NA
NEE: 15852 data points (90.48%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xDL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xDL-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1152 data points (6.56%) set to NA
H: 5081 data points (28.92%) set to NA
LE: 5094 data points (29%) set to NA
NEE: 12756 data points (72.61%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 114”

-------------------------------------------------------------------
Data filtering:
3600 data points (20.49%) excluded by growing season filter
4484 additional data points (25.52%) excluded by precipitation filter (5479
 data points = 31.19 % in total)
8084 data points (46.02%) excluded in total
9484 valid data points (53.98%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1152 data points (6.56%) set to NA
H: 5081 data points (28.92%) set to NA
LE: 5094 data points (29%) set to NA
NEE: 12756 data points (72.61%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 114”

-------------------------------------------------------------------
Data filtering:
3600 data points (20.49%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3600 data points (20.49%) excluded in total
13968 valid data points (79.51%) remaining.

New sEddyProc class for site 'US-xDL'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 222.85.

Regression of reference temperature R_ref for 5 periods.

Quality control:
TA: 17 data points (0.1%) set to NA
H: 1240 data points (7.08%) set to NA
LE: 1215 data points (6.93%) set to NA
NEE: 3370 data points (19.24%) set to NA
-------------------------------------------------------------------
Data filtering:
7632 data points (43.56%) excluded by growing season filter
3560 additional data points (20.32%) excluded by precipitation filter (6108
 data points = 34.86 % in total)
11192 data points (63.88%) excluded in total
6328 valid data points (36.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 17 data points (0.1%) set to NA
H: 1240 data points (7.08%) set to NA
LE: 1215 data points (6.93%) set to NA
NEE: 3370 data points (19.24%) set to NA
-------------------------------------------------------------------
Data filtering:
7632 data points (43.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7632 data points (43.56%) excluded in total
9888 valid data points (56.44%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -50, -52 ...”
New sEddyProc class for site 'US-xDL'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -50, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xDL-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 72 data points (0.41%) set to NA
H: 221 data points (1.26%) set to NA
LE: 224 data points (1.28%) set to NA
NEE: 1330 data points (7.59%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.67%) excluded by growing season filter
2794 additional data points (15.95%) excluded by precipitation filter (4968
 data points = 28.36 % in total)
11146 data points (63.62%) excluded in total
6374 valid data points (36.38%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 72 data points (0.41%) set to NA
H: 221 data points (1.26%) set to NA
LE: 224 data points (1.28%) set to NA
NEE: 1330 data points (7.59%) set to NA
-------------------------------------------------------------------
Data filtering:
8352 data points (47.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8352 data points (47.67%) excluded in total
9168 valid data points (52.33%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -61 ...”
New sEddyProc class for site 'US-xDL'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -61 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xDL-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 148 data points (0.84%) set to NA
H: 1321 data points (7.54%) set to NA
LE: 1335 data points (7.62%) set to NA
NEE: 1491 data points (8.51%) set to NA
-------------------------------------------------------------------
Data filtering:
7920 data points (45.21%) excluded by growing season filter
2535 additional data points (14.47%) excluded by precipitation filter (4848
 data points = 27.67 % in total)
10455 data points (59.67%) excluded in total
7065 valid data points (40.33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 148 data points (0.84%) set to NA
H: 1321 data points (7.54%) set to NA
LE: 1335 data points (7.62%) set to NA
NEE: 1491 data points (8.51%) set to NA
-------------------------------------------------------------------
Data filtering:
7920 data points (45.21%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7920 data points (45.21%) excluded in total
9600 valid data points (54.79%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -53, -53 ...”
New sEddyProc class for site 'US-xDL'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -53, -53 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xDL-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 24 data points (0.14%) set to NA
H: 141 data points (0.8%) set to NA
LE: 159 data points (0.91%) set to NA
NEE: 997 data points (5.68%) set to NA
-------------------------------------------------------------------
Data filtering:
8448 data points (48.09%) excluded by growing season filter
2617 additional data points (14.9%) excluded by precipitation filter (4825
 data points = 27.46 % in total)
11065 data points (62.98%) excluded in total
6503 valid data points (37.02%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 24 data points (0.14%) set to NA
H: 141 data points (0.8%) set to NA
LE: 159 data points (0.91%) set to NA
NEE: 997 data points (5.68%) set to NA
-------------------------------------------------------------------
Data filtering:
8448 data points (48.09%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8448 data points (48.09%) excluded in total
9120 valid data points (51.91%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
New sEddyProc class for site 'US-xDL'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xDL-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[302/329] Processing: US-xGR

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xGR | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 166 data points (0.95%) set to NA
H: 4537 data points (25.9%) set to NA
LE: 4312 data points (24.61%) set to NA
NEE: 5321 data points (30.37%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 64”

-------------------------------------------------------------------
Data filtering:
9168 data points (52.33%) excluded by growing season filter
3359 additional data points (19.17%) excluded by precipitation filter (7344
 data points = 41.92 % in total)
12527 data points (71.5%) excluded in total
4993 valid data points (28.5%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 166 data points (0.95%) set to NA
H: 4537 data points (25.9%) set to NA
LE: 4312 data points (24.61%) set to NA
NEE: 5321 data points (30.37%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 64”

-------------------------------------------------------------------
Data filtering:
9168 data points (52.33%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9168 data points (52.33%) excluded in total
8352 valid data points (47.67%) remaining.

New sEddyProc class for site 'US-xGR'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 202.94.

Regression of reference temperature R_ref for 2 periods.

Quality control:
TA: 100 data points (0.57%) set to NA
H: 3548 data points (20.2%) set to NA
LE: 8057 data points (45.86%) set to NA
NEE: 10508 data points (59.81%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 123”

-------------------------------------------------------------------
Data filtering:
3408 data points (19.4%) excluded by growing season filter
6159 additional data points (35.06%) excluded by precipitation filter (8000
 data points = 45.54 % in total)
9567 data points (54.46%) excluded in total
8001 valid data points (45.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 100 data points (0.57%) set to NA
H: 3548 data points (20.2%) set to NA
LE: 8057 data points (45.86%) set to NA
NEE: 10508 data points (59.81%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 123”

-------------------------------------------------------------------
Data filtering:
3408 data points (19.4%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
3408 data points (19.4%) excluded in total
14160 valid data points (80.6%) remaining.

New sEddyProc class for site 'US-xGR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xGR-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 24 data points (0.14%) set to NA
H: 1277 data points (7.29%) set to NA
LE: 2085 data points (11.9%) set to NA
NEE: 4355 data points (24.86%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.78%) excluded by growing season filter
3359 additional data points (19.17%) excluded by precipitation filter (6801
 data points = 38.82 % in total)
12431 data points (70.95%) excluded in total
5089 valid data points (29.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 24 data points (0.14%) set to NA
H: 1277 data points (7.29%) set to NA
LE: 2085 data points (11.9%) set to NA
NEE: 4355 data points (24.86%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.78%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9072 data points (51.78%) excluded in total
8448 valid data points (48.22%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -78 ...”
New sEddyProc class for site 'US-xGR'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -78 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xGR-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 179 data points (1.02%) set to NA
H: 712 data points (4.06%) set to NA
LE: 751 data points (4.29%) set to NA
NEE: 1860 data points (10.62%) set to NA
-------------------------------------------------------------------
Data filtering:
9504 data points (54.25%) excluded by growing season filter
3197 additional data points (18.25%) excluded by precipitation filter (6553
 data points = 37.4 % in total)
12701 data points (72.49%) excluded in total
4819 valid data points (27.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 179 data points (1.02%) set to NA
H: 712 data points (4.06%) set to NA
LE: 751 data points (4.29%) set to NA
NEE: 1860 data points (10.62%) set to NA
-------------------------------------------------------------------
Data filtering:
9504 data points (54.25%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9504 data points (54.25%) excluded in total
8016 valid data points (45.75%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -79 ...”
New sEddyProc class for site 'US-xGR'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -79 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xGR-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 55 data points (0.31%) set to NA
H: 2379 data points (13.58%) set to NA
LE: 2452 data points (14%) set to NA
NEE: 3613 data points (20.62%) set to NA
-------------------------------------------------------------------
Data filtering:
9744 data points (55.62%) excluded by growing season filter
3958 additional data points (22.59%) excluded by precipitation filter (7440
 data points = 42.47 % in total)
13702 data points (78.21%) excluded in total
3818 valid data points (21.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 55 data points (0.31%) set to NA
H: 2379 data points (13.58%) set to NA
LE: 2452 data points (14%) set to NA
NEE: 3613 data points (20.62%) set to NA
-------------------------------------------------------------------
Data filtering:
9744 data points (55.62%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9744 data points (55.62%) excluded in total
7776 valid data points (44.38%) remaining.

New sEddyProc class for site 'US-xGR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xGR-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 93 data points (0.53%) set to NA
H: 351 data points (2%) set to NA
LE: 358 data points (2.04%) set to NA
NEE: 1433 data points (8.16%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.28%) excluded by growing season filter
3281 additional data points (18.68%) excluded by precipitation filter (6911
 data points = 39.34 % in total)
12641 data points (71.95%) excluded in total
4927 valid data points (28.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 93 data points (0.53%) set to NA
H: 351 data points (2%) set to NA
LE: 358 data points (2.04%) set to NA
NEE: 1433 data points (8.16%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.28%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9360 data points (53.28%) excluded in total
8208 valid data points (46.72%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -51, -76, -57 ...”
New sEddyProc class for site 'US-xGR'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -51, -76, -57 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xGR-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[303/329] Processing: US-xHE

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xHE | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 50 data points (0.29%) set to NA
H: 6736 data points (38.45%) set to NA
LE: 6743 data points (38.49%) set to NA
NEE: 7242 data points (41.34%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 106”

-------------------------------------------------------------------
Data filtering:
6912 data points (39.45%) excluded by growing season filter
3941 additional data points (22.49%) excluded by precipitation filter (4750
 data points = 27.11 % in total)
10853 data points (61.95%) excluded in total
6667 valid data points (38.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 50 data points (0.29%) set to NA
H: 6736 data points (38.45%) set to NA
LE: 6743 data points (38.49%) set to NA
NEE: 7242 data points (41.34%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 106”

-------------------------------------------------------------------
Data filtering:
6912 data points (39.45%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6912 data points (39.45%) excluded in total
10608 valid data points (60.55%) remaining.

New sEddyProc class for site 'US-xHE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xHE-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 111 data points (0.63%) set to NA
H: 10087 data points (57.42%) set to NA
LE: 10094 data points (57.46%) set to NA
NEE: 11097 data points (63.17%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 176”

-------------------------------------------------------------------
Data filtering:
5520 data points (31.42%) excluded by growing season filter
3313 additional data points (18.86%) excluded by precipitation filter (4025
 data points = 22.91 % in total)
8833 data points (50.28%) excluded in total
8735 valid data points (49.72%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 111 data points (0.63%) set to NA
H: 10087 data points (57.42%) set to NA
LE: 10094 data points (57.46%) set to NA
NEE: 11097 data points (63.17%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 176”

-------------------------------------------------------------------
Data filtering:
5520 data points (31.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5520 data points (31.42%) excluded in total
12048 valid data points (68.58%) remaining.

New sEddyProc class for site 'US-xHE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xHE-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 20 data points (0.11%) set to NA
H: 507 data points (2.89%) set to NA
LE: 567 data points (3.24%) set to NA
NEE: 2369 data points (13.52%) set to NA
-------------------------------------------------------------------
Data filtering:
12720 data points (72.6%) excluded by growing season filter
1903 additional data points (10.86%) excluded by precipitation filter (3540
 data points = 20.21 % in total)
14623 data points (83.46%) excluded in total
2897 valid data points (16.54%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 20 data points (0.11%) set to NA
H: 507 data points (2.89%) set to NA
LE: 567 data points (3.24%) set to NA
NEE: 2369 data points (13.52%) set to NA
-------------------------------------------------------------------
Data filtering:
12720 data points (72.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12720 data points (72.6%) excluded in total
4800 valid data points (27.4%) remaining.

New sEddyProc class for site 'US-xHE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xHE-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 148 data points (0.84%) set to NA
H: 1991 data points (11.36%) set to NA
LE: 1992 data points (11.37%) set to NA
NEE: 3921 data points (22.38%) set to NA
-------------------------------------------------------------------
Data filtering:
12384 data points (70.68%) excluded by growing season filter
1789 additional data points (10.21%) excluded by precipitation filter (3337
 data points = 19.05 % in total)
14173 data points (80.9%) excluded in total
3347 valid data points (19.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 148 data points (0.84%) set to NA
H: 1991 data points (11.36%) set to NA
LE: 1992 data points (11.37%) set to NA
NEE: 3921 data points (22.38%) set to NA
-------------------------------------------------------------------
Data filtering:
12384 data points (70.68%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12384 data points (70.68%) excluded in total
5136 valid data points (29.32%) remaining.

New sEddyProc class for site 'US-xHE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xHE-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 28 data points (0.16%) set to NA
H: 676 data points (3.86%) set to NA
LE: 720 data points (4.11%) set to NA
NEE: 2325 data points (13.27%) set to NA
-------------------------------------------------------------------
Data filtering:
12672 data points (72.33%) excluded by growing season filter
1894 additional data points (10.81%) excluded by precipitation filter (3966
 data points = 22.64 % in total)
14566 data points (83.14%) excluded in total
2954 valid data points (16.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 28 data points (0.16%) set to NA
H: 676 data points (3.86%) set to NA
LE: 720 data points (4.11%) set to NA
NEE: 2325 data points (13.27%) set to NA
-------------------------------------------------------------------
Data filtering:
12672 data points (72.33%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12672 data points (72.33%) excluded in total
4848 valid data points (27.67%) remaining.

New sEddyProc class for site 'US-xHE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xHE-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 17 data points (0.1%) set to NA
H: 373 data points (2.12%) set to NA
LE: 388 data points (2.21%) set to NA
NEE: 2124 data points (12.09%) set to NA
-------------------------------------------------------------------
Data filtering:
12672 data points (72.13%) excluded by growing season filter
2290 additional data points (13.04%) excluded by precipitation filter (4649
 data points = 26.46 % in total)
14962 data points (85.17%) excluded in total
2606 valid data points (14.83%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 17 data points (0.1%) set to NA
H: 373 data points (2.12%) set to NA
LE: 388 data points (2.21%) set to NA
NEE: 2124 data points (12.09%) set to NA
-------------------------------------------------------------------
Data filtering:
12672 data points (72.13%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12672 data points (72.13%) excluded in total
4896 valid data points (27.87%) remaining.

New sEddyProc class for site 'US-xHE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xHE-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[304/329] Processing: US-xJE

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xJE | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 66 data points (0.38%) set to NA
H: 7127 data points (40.68%) set to NA
LE: 7130 data points (40.7%) set to NA
NEE: 12547 data points (71.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4883 additional data points (27.87%) excluded by precipitation filter (4883
 data points = 27.87 % in total)
4883 data points (27.87%) excluded in total
12637 valid data points (72.13%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 66 data points (0.38%) set to NA
H: 7127 data points (40.68%) set to NA
LE: 7130 data points (40.7%) set to NA
NEE: 12547 data points (71.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xJE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xJE-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 63 data points (0.36%) set to NA
H: 203 data points (1.16%) set to NA
LE: 193 data points (1.1%) set to NA
NEE: 896 data points (5.1%) set to NA
-------------------------------------------------------------------
Data filtering:
5280 data points (30.05%) excluded by growing season filter
3560 additional data points (20.26%) excluded by precipitation filter (5457
 data points = 31.06 % in total)
8840 data points (50.32%) excluded in total
8728 valid data points (49.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 63 data points (0.36%) set to NA
H: 203 data points (1.16%) set to NA
LE: 193 data points (1.1%) set to NA
NEE: 896 data points (5.1%) set to NA
-------------------------------------------------------------------
Data filtering:
5280 data points (30.05%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5280 data points (30.05%) excluded in total
12288 valid data points (69.95%) remaining.

New sEddyProc class for site 'US-xJE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xJE-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 59 data points (0.34%) set to NA
H: 879 data points (5.02%) set to NA
LE: 856 data points (4.89%) set to NA
NEE: 1434 data points (8.18%) set to NA
-------------------------------------------------------------------
Data filtering:
6768 data points (38.63%) excluded by growing season filter
3738 additional data points (21.34%) excluded by precipitation filter (5944
 data points = 33.93 % in total)
10506 data points (59.97%) excluded in total
7014 valid data points (40.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 59 data points (0.34%) set to NA
H: 879 data points (5.02%) set to NA
LE: 856 data points (4.89%) set to NA
NEE: 1434 data points (8.18%) set to NA
-------------------------------------------------------------------
Data filtering:
6768 data points (38.63%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6768 data points (38.63%) excluded in total
10752 valid data points (61.37%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -53, -60, -51, -59 ...”
New sEddyProc class for site 'US-xJE'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 4 cases! Invalid values with 'NEE < -50': -53, -60, -51, -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xJE-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 62 data points (0.35%) set to NA
H: 216 data points (1.23%) set to NA
LE: 185 data points (1.06%) set to NA
NEE: 858 data points (4.9%) set to NA
-------------------------------------------------------------------
Data filtering:
6576 data points (37.53%) excluded by growing season filter
2947 additional data points (16.82%) excluded by precipitation filter (4791
 data points = 27.35 % in total)
9523 data points (54.36%) excluded in total
7997 valid data points (45.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 62 data points (0.35%) set to NA
H: 216 data points (1.23%) set to NA
LE: 185 data points (1.06%) set to NA
NEE: 858 data points (4.9%) set to NA
-------------------------------------------------------------------
Data filtering:
6576 data points (37.53%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6576 data points (37.53%) excluded in total
10944 valid data points (62.47%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -56, -54 ...”
New sEddyProc class for site 'US-xJE'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -56, -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xJE-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 109 data points (0.62%) set to NA
H: 6710 data points (38.3%) set to NA
LE: 6723 data points (38.37%) set to NA
NEE: 7083 data points (40.43%) set to NA
-------------------------------------------------------------------
Data filtering:
6336 data points (36.16%) excluded by growing season filter
3050 additional data points (17.41%) excluded by precipitation filter (4121
 data points = 23.52 % in total)
9386 data points (53.57%) excluded in total
8134 valid data points (46.43%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 109 data points (0.62%) set to NA
H: 6710 data points (38.3%) set to NA
LE: 6723 data points (38.37%) set to NA
NEE: 7083 data points (40.43%) set to NA
-------------------------------------------------------------------
Data filtering:
6336 data points (36.16%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6336 data points (36.16%) excluded in total
11184 valid data points (63.84%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -57, -59 ...”
New sEddyProc class for site 'US-xJE'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -57, -59 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xJE-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 59 data points (0.34%) set to NA
H: 617 data points (3.51%) set to NA
LE: 591 data points (3.36%) set to NA
NEE: 3537 data points (20.13%) set to NA
-------------------------------------------------------------------
Data filtering:
4368 data points (24.86%) excluded by growing season filter
3645 additional data points (20.75%) excluded by precipitation filter (4891
 data points = 27.84 % in total)
8013 data points (45.61%) excluded in total
9555 valid data points (54.39%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 59 data points (0.34%) set to NA
H: 617 data points (3.51%) set to NA
LE: 591 data points (3.36%) set to NA
NEE: 3537 data points (20.13%) set to NA
-------------------------------------------------------------------
Data filtering:
4368 data points (24.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4368 data points (24.86%) excluded in total
13200 valid data points (75.14%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -56, -56 ...”
New sEddyProc class for site 'US-xJE'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -56, -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xJE-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[305/329] Processing: US-xJR

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xJR | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 74 data points (0.42%) set to NA
H: 1787 data points (10.2%) set to NA
LE: 1864 data points (10.64%) set to NA
NEE: 3083 data points (17.6%) set to NA
-------------------------------------------------------------------
Data filtering:
8880 data points (50.68%) excluded by growing season filter
1783 additional data points (10.18%) excluded by precipitation filter (3672
 data points = 20.96 % in total)
10663 data points (60.86%) excluded in total
6857 valid data points (39.14%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 74 data points (0.42%) set to NA
H: 1787 data points (10.2%) set to NA
LE: 1864 data points (10.64%) set to NA
NEE: 3083 data points (17.6%) set to NA
-------------------------------------------------------------------
Data filtering:
8880 data points (50.68%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8880 data points (50.68%) excluded in total
8640 valid data points (49.32%) remaining.

New sEddyProc class for site 'US-xJR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xJR-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 21 data points (0.12%) set to NA
H: 1355 data points (7.71%) set to NA
LE: 1347 data points (7.67%) set to NA
NEE: 2299 data points (13.09%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.01%) excluded by growing season filter
756 additional data points (4.3%) excluded by precipitation filter (1952
 data points = 11.11 % in total)
10596 data points (60.31%) excluded in total
6972 valid data points (39.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 21 data points (0.12%) set to NA
H: 1355 data points (7.71%) set to NA
LE: 1347 data points (7.67%) set to NA
NEE: 2299 data points (13.09%) set to NA
-------------------------------------------------------------------
Data filtering:
9840 data points (56.01%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9840 data points (56.01%) excluded in total
7728 valid data points (43.99%) remaining.

New sEddyProc class for site 'US-xJR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xJR-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 70 data points (0.4%) set to NA
H: 237 data points (1.35%) set to NA
LE: 354 data points (2.02%) set to NA
NEE: 2201 data points (12.56%) set to NA
-------------------------------------------------------------------
Data filtering:
14928 data points (85.21%) excluded by growing season filter
631 additional data points (3.6%) excluded by precipitation filter (2003
 data points = 11.43 % in total)
15559 data points (88.81%) excluded in total
1961 valid data points (11.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 70 data points (0.4%) set to NA
H: 237 data points (1.35%) set to NA
LE: 354 data points (2.02%) set to NA
NEE: 2201 data points (12.56%) set to NA
-------------------------------------------------------------------
Data filtering:
14928 data points (85.21%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14928 data points (85.21%) excluded in total
2592 valid data points (14.79%) remaining.

New sEddyProc class for site 'US-xJR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xJR-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 57 data points (0.33%) set to NA
H: 248 data points (1.42%) set to NA
LE: 315 data points (1.8%) set to NA
NEE: 1077 data points (6.15%) set to NA
-------------------------------------------------------------------
Data filtering:
12864 data points (73.42%) excluded by growing season filter
878 additional data points (5.01%) excluded by precipitation filter (2299
 data points = 13.12 % in total)
13742 data points (78.44%) excluded in total
3778 valid data points (21.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 57 data points (0.33%) set to NA
H: 248 data points (1.42%) set to NA
LE: 315 data points (1.8%) set to NA
NEE: 1077 data points (6.15%) set to NA
-------------------------------------------------------------------
Data filtering:
12864 data points (73.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12864 data points (73.42%) excluded in total
4656 valid data points (26.58%) remaining.

New sEddyProc class for site 'US-xJR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xJR-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 313 data points (1.79%) set to NA
H: 1881 data points (10.74%) set to NA
LE: 1977 data points (11.28%) set to NA
NEE: 3250 data points (18.55%) set to NA
-------------------------------------------------------------------
Data filtering:
12576 data points (71.78%) excluded by growing season filter
667 additional data points (3.81%) excluded by precipitation filter (2150
 data points = 12.27 % in total)
13243 data points (75.59%) excluded in total
4277 valid data points (24.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 313 data points (1.79%) set to NA
H: 1881 data points (10.74%) set to NA
LE: 1977 data points (11.28%) set to NA
NEE: 3250 data points (18.55%) set to NA
-------------------------------------------------------------------
Data filtering:
12576 data points (71.78%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12576 data points (71.78%) excluded in total
4944 valid data points (28.22%) remaining.

New sEddyProc class for site 'US-xJR'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 179.44.

Regression of reference temperature R_ref for 3 periods.

Quality control:
TA: 207 data points (1.18%) set to NA
H: 1845 data points (10.5%) set to NA
LE: 1898 data points (10.8%) set to NA
NEE: 2756 data points (15.69%) set to NA
-------------------------------------------------------------------
Data filtering:
14256 data points (81.15%) excluded by growing season filter
537 additional data points (3.06%) excluded by precipitation filter (1725
 data points = 9.82 % in total)
14793 data points (84.2%) excluded in total
2775 valid data points (15.8%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 207 data points (1.18%) set to NA
H: 1845 data points (10.5%) set to NA
LE: 1898 data points (10.8%) set to NA
NEE: 2756 data points (15.69%) set to NA
-------------------------------------------------------------------
Data filtering:
14256 data points (81.15%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14256 data points (81.15%) excluded in total
3312 valid data points (18.85%) remaining.

New sEddyProc class for site 'US-xJR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xJR-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[306/329] Processing: US-xLE

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xLE | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 528 data points (3.01%) set to NA
H: 12971 data points (74.04%) set to NA
LE: 12980 data points (74.09%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5300 additional data points (30.25%) excluded by precipitation filter (5300
 data points = 30.25 % in total)
5300 data points (30.25%) excluded in total
12220 valid data points (69.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 528 data points (3.01%) set to NA
H: 12971 data points (74.04%) set to NA
LE: 12980 data points (74.09%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xLE'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xLE-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 7481 data points (42.58%) set to NA
H: 9730 data points (55.38%) set to NA
LE: 9714 data points (55.29%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6877 additional data points (39.15%) excluded by precipitation filter (6877
 data points = 39.15 % in total)
6877 data points (39.15%) excluded in total
10691 valid data points (60.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7481 data points (42.58%) set to NA
H: 9730 data points (55.38%) set to NA
LE: 9714 data points (55.29%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-xLE'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xLE-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 92 data points (0.53%) set to NA
H: 5454 data points (31.13%) set to NA
LE: 5505 data points (31.42%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7352 additional data points (41.96%) excluded by precipitation filter (7352
 data points = 41.96 % in total)
7352 data points (41.96%) excluded in total
10168 valid data points (58.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 92 data points (0.53%) set to NA
H: 5454 data points (31.13%) set to NA
LE: 5505 data points (31.42%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xLE'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xLE-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 126 data points (0.72%) set to NA
H: 1444 data points (8.24%) set to NA
LE: 1713 data points (9.78%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5408 additional data points (30.87%) excluded by precipitation filter (5408
 data points = 30.87 % in total)
5408 data points (30.87%) excluded in total
12112 valid data points (69.13%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 126 data points (0.72%) set to NA
H: 1444 data points (8.24%) set to NA
LE: 1713 data points (9.78%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xLE'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xLE-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 111 data points (0.63%) set to NA
H: 5892 data points (33.63%) set to NA
LE: 5832 data points (33.29%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5270 additional data points (30.08%) excluded by precipitation filter (5270
 data points = 30.08 % in total)
5270 data points (30.08%) excluded in total
12250 valid data points (69.92%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 111 data points (0.63%) set to NA
H: 5892 data points (33.63%) set to NA
LE: 5832 data points (33.29%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xLE'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xLE-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 287 data points (1.63%) set to NA
H: 3104 data points (17.67%) set to NA
LE: 3117 data points (17.74%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4646 additional data points (26.45%) excluded by precipitation filter (4646
 data points = 26.45 % in total)
4646 data points (26.45%) excluded in total
12922 valid data points (73.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 287 data points (1.63%) set to NA
H: 3104 data points (17.67%) set to NA
LE: 3117 data points (17.74%) set to NA
NEE: 0 data points (0%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-xLE'

Warning message in fSetQF(sDT, FluxVar, QFFluxVar, QFFluxValue, "sMRFluxPartition"):
“sMRFluxPartition:::fSetQF::: Variable 'NEE' contains no data after applying quality flag 'NEE_QC_OK' with value 0!”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xLE-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[307/329] Processing: US-xMB

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xMB | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 224 data points (1.28%) set to NA
H: 13384 data points (76.39%) set to NA
LE: 13391 data points (76.43%) set to NA
NEE: 14887 data points (84.97%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3510 additional data points (20.03%) excluded by precipitation filter (3510
 data points = 20.03 % in total)
3510 data points (20.03%) excluded in total
14010 valid data points (79.97%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 224 data points (1.28%) set to NA
H: 13384 data points (76.39%) set to NA
LE: 13391 data points (76.43%) set to NA
NEE: 14887 data points (84.97%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xMB'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 193.37.

Regression of reference temperature R_ref for 3 periods.

Quality control:
TA: 21 data points (0.12%) set to NA
H: 4775 data points (27.18%) set to NA
LE: 4797 data points (27.31%) set to NA
NEE: 5155 data points (29.34%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 55”

-------------------------------------------------------------------
Data filtering:
12912 data points (73.5%) excluded by growing season filter
396 additional data points (2.25%) excluded by precipitation filter (2400
 data points = 13.66 % in total)
13308 data points (75.75%) excluded in total
4260 valid data points (24.25%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 21 data points (0.12%) set to NA
H: 4775 data points (27.18%) set to NA
LE: 4797 data points (27.31%) set to NA
NEE: 5155 data points (29.34%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 55”

-------------------------------------------------------------------
Data filtering:
12912 data points (73.5%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12912 data points (73.5%) excluded in total
4656 valid data points (26.5%) remaining.

New sEddyProc class for site 'US-xMB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xMB-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 52 data points (0.3%) set to NA
H: 818 data points (4.67%) set to NA
LE: 817 data points (4.66%) set to NA
NEE: 2415 data points (13.78%) set to NA
-------------------------------------------------------------------
Data filtering:
12720 data points (72.6%) excluded by growing season filter
800 additional data points (4.57%) excluded by precipitation filter (3971
 data points = 22.67 % in total)
13520 data points (77.17%) excluded in total
4000 valid data points (22.83%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 52 data points (0.3%) set to NA
H: 818 data points (4.67%) set to NA
LE: 817 data points (4.66%) set to NA
NEE: 2415 data points (13.78%) set to NA
-------------------------------------------------------------------
Data filtering:
12720 data points (72.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12720 data points (72.6%) excluded in total
4800 valid data points (27.4%) remaining.

New sEddyProc class for site 'US-xMB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xMB-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 21 data points (0.12%) set to NA
H: 1450 data points (8.28%) set to NA
LE: 1468 data points (8.38%) set to NA
NEE: 1936 data points (11.05%) set to NA
-------------------------------------------------------------------
Data filtering:
12720 data points (72.6%) excluded by growing season filter
281 additional data points (1.6%) excluded by precipitation filter (2370
 data points = 13.53 % in total)
13001 data points (74.21%) excluded in total
4519 valid data points (25.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 21 data points (0.12%) set to NA
H: 1450 data points (8.28%) set to NA
LE: 1468 data points (8.38%) set to NA
NEE: 1936 data points (11.05%) set to NA
-------------------------------------------------------------------
Data filtering:
12720 data points (72.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12720 data points (72.6%) excluded in total
4800 valid data points (27.4%) remaining.

New sEddyProc class for site 'US-xMB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xMB-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 36 data points (0.21%) set to NA
H: 171 data points (0.98%) set to NA
LE: 182 data points (1.04%) set to NA
NEE: 911 data points (5.2%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
392 additional data points (2.24%) excluded by precipitation filter (2409
 data points = 13.75 % in total)
11528 data points (65.8%) excluded in total
5992 valid data points (34.2%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 36 data points (0.21%) set to NA
H: 171 data points (0.98%) set to NA
LE: 182 data points (1.04%) set to NA
NEE: 911 data points (5.2%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11136 data points (63.56%) excluded in total
6384 valid data points (36.44%) remaining.

New sEddyProc class for site 'US-xMB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xMB-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 15 data points (0.09%) set to NA
H: 99 data points (0.56%) set to NA
LE: 97 data points (0.55%) set to NA
NEE: 1222 data points (6.96%) set to NA
-------------------------------------------------------------------
Data filtering:
12192 data points (69.4%) excluded by growing season filter
1184 additional data points (6.74%) excluded by precipitation filter (2772
 data points = 15.78 % in total)
13376 data points (76.14%) excluded in total
4192 valid data points (23.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 15 data points (0.09%) set to NA
H: 99 data points (0.56%) set to NA
LE: 97 data points (0.55%) set to NA
NEE: 1222 data points (6.96%) set to NA
-------------------------------------------------------------------
Data filtering:
12192 data points (69.4%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12192 data points (69.4%) excluded in total
5376 valid data points (30.6%) remaining.

New sEddyProc class for site 'US-xMB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xMB-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[308/329] Processing: US-xML

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xML | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 102 data points (0.58%) set to NA
H: 1735 data points (9.9%) set to NA
LE: 1755 data points (10.02%) set to NA
NEE: 7552 data points (43.11%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 100”

-------------------------------------------------------------------
Data filtering:
10704 data points (61.1%) excluded by growing season filter
3089 additional data points (17.63%) excluded by precipitation filter (8068
 data points = 46.05 % in total)
13793 data points (78.73%) excluded in total
3727 valid data points (21.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 102 data points (0.58%) set to NA
H: 1735 data points (9.9%) set to NA
LE: 1755 data points (10.02%) set to NA
NEE: 7552 data points (43.11%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 100”

-------------------------------------------------------------------
Data filtering:
10704 data points (61.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10704 data points (61.1%) excluded in total
6816 valid data points (38.9%) remaining.

New sEddyProc class for site 'US-xML'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xML-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 45 data points (0.26%) set to NA
H: 1525 data points (8.68%) set to NA
LE: 1531 data points (8.71%) set to NA
NEE: 3502 data points (19.93%) set to NA
-------------------------------------------------------------------
Data filtering:
11520 data points (65.57%) excluded by growing season filter
2452 additional data points (13.96%) excluded by precipitation filter (7948
 data points = 45.24 % in total)
13972 data points (79.53%) excluded in total
3596 valid data points (20.47%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 45 data points (0.26%) set to NA
H: 1525 data points (8.68%) set to NA
LE: 1531 data points (8.71%) set to NA
NEE: 3502 data points (19.93%) set to NA
-------------------------------------------------------------------
Data filtering:
11520 data points (65.57%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11520 data points (65.57%) excluded in total
6048 valid data points (34.43%) remaining.

New sEddyProc class for site 'US-xML'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xML-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 333 data points (1.9%) set to NA
H: 3775 data points (21.55%) set to NA
LE: 3791 data points (21.64%) set to NA
NEE: 16126 data points (92.04%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
7047 additional data points (40.22%) excluded by precipitation filter (7047
 data points = 40.22 % in total)
7047 data points (40.22%) excluded in total
10473 valid data points (59.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 333 data points (1.9%) set to NA
H: 3775 data points (21.55%) set to NA
LE: 3791 data points (21.64%) set to NA
NEE: 16126 data points (92.04%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xML'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xML-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 121 data points (0.69%) set to NA
H: 1172 data points (6.69%) set to NA
LE: 1211 data points (6.91%) set to NA
NEE: 3608 data points (20.59%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.84%) excluded by growing season filter
2389 additional data points (13.64%) excluded by precipitation filter (6626
 data points = 37.82 % in total)
13573 data points (77.47%) excluded in total
3947 valid data points (22.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 121 data points (0.69%) set to NA
H: 1172 data points (6.69%) set to NA
LE: 1211 data points (6.91%) set to NA
NEE: 3608 data points (20.59%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11184 data points (63.84%) excluded in total
6336 valid data points (36.16%) remaining.

New sEddyProc class for site 'US-xML'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xML-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 117 data points (0.67%) set to NA
H: 418 data points (2.39%) set to NA
LE: 447 data points (2.55%) set to NA
NEE: 2690 data points (15.35%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.19%) excluded by growing season filter
2612 additional data points (14.91%) excluded by precipitation filter (6246
 data points = 35.65 % in total)
13508 data points (77.1%) excluded in total
4012 valid data points (22.9%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 117 data points (0.67%) set to NA
H: 418 data points (2.39%) set to NA
LE: 447 data points (2.55%) set to NA
NEE: 2690 data points (15.35%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10896 data points (62.19%) excluded in total
6624 valid data points (37.81%) remaining.

New sEddyProc class for site 'US-xML'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xML-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 236 data points (1.34%) set to NA
H: 1441 data points (8.2%) set to NA
LE: 1478 data points (8.41%) set to NA
NEE: 3245 data points (18.47%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.02%) excluded by growing season filter
2452 additional data points (13.96%) excluded by precipitation filter (6247
 data points = 35.56 % in total)
13348 data points (75.98%) excluded in total
4220 valid data points (24.02%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 236 data points (1.34%) set to NA
H: 1441 data points (8.2%) set to NA
LE: 1478 data points (8.41%) set to NA
NEE: 3245 data points (18.47%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.02%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10896 data points (62.02%) excluded in total
6672 valid data points (37.98%) remaining.

New sEddyProc class for site 'US-xML'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xML-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[309/329] Processing: US-xNQ

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xNQ | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 202 data points (1.15%) set to NA
H: 4476 data points (25.55%) set to NA
LE: 4466 data points (25.49%) set to NA
NEE: 6865 data points (39.18%) set to NA
-------------------------------------------------------------------
Data filtering:
12720 data points (72.6%) excluded by growing season filter
1354 additional data points (7.73%) excluded by precipitation filter (4556
 data points = 26 % in total)
14074 data points (80.33%) excluded in total
3446 valid data points (19.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 202 data points (1.15%) set to NA
H: 4476 data points (25.55%) set to NA
LE: 4466 data points (25.49%) set to NA
NEE: 6865 data points (39.18%) set to NA
-------------------------------------------------------------------
Data filtering:
12720 data points (72.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12720 data points (72.6%) excluded in total
4800 valid data points (27.4%) remaining.

New sEddyProc class for site 'US-xNQ'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 140.12.

Regression of reference temperature R_ref for 4 periods.

Quality control:
TA: 61 data points (0.35%) set to NA
H: 5129 data points (29.2%) set to NA
LE: 5147 data points (29.3%) set to NA
NEE: 7682 data points (43.73%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 34”

-------------------------------------------------------------------
Data filtering:
10608 data points (60.38%) excluded by growing season filter
760 additional data points (4.33%) excluded by precipitation filter (1784
 data points = 10.15 % in total)
11368 data points (64.71%) excluded in total
6200 valid data points (35.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 61 data points (0.35%) set to NA
H: 5129 data points (29.2%) set to NA
LE: 5147 data points (29.3%) set to NA
NEE: 7682 data points (43.73%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 34”

-------------------------------------------------------------------
Data filtering:
10608 data points (60.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10608 data points (60.38%) excluded in total
6960 valid data points (39.62%) remaining.

New sEddyProc class for site 'US-xNQ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xNQ-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 74 data points (0.42%) set to NA
H: 387 data points (2.21%) set to NA
LE: 419 data points (2.39%) set to NA
NEE: 1022 data points (5.83%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.89%) excluded by growing season filter
1150 additional data points (6.56%) excluded by precipitation filter (3264
 data points = 18.63 % in total)
10942 data points (62.45%) excluded in total
6578 valid data points (37.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 74 data points (0.42%) set to NA
H: 387 data points (2.21%) set to NA
LE: 419 data points (2.39%) set to NA
NEE: 1022 data points (5.83%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9792 data points (55.89%) excluded in total
7728 valid data points (44.11%) remaining.

New sEddyProc class for site 'US-xNQ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xNQ-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 34 data points (0.19%) set to NA
H: 17147 data points (97.87%) set to NA
LE: 17149 data points (97.88%) set to NA
NEE: 17520 data points (100%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2826 additional data points (16.13%) excluded by precipitation filter (2826
 data points = 16.13 % in total)
2826 data points (16.13%) excluded in total
14694 valid data points (83.87%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-xNQ-2022”

Quality control:
TA: 26 data points (0.15%) set to NA
H: 270 data points (1.54%) set to NA
LE: 275 data points (1.57%) set to NA
NEE: 1784 data points (10.18%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.84%) excluded by growing season filter
1164 additional data points (6.64%) excluded by precipitation filter (4082
 data points = 23.3 % in total)
12348 data points (70.48%) excluded in total
5172 valid data points (29.52%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 26 data points (0.15%) set to NA
H: 270 data points (1.54%) set to NA
LE: 275 data points (1.57%) set to NA
NEE: 1784 data points (10.18%) set to NA
-------------------------------------------------------------------
Data filtering:
11184 data points (63.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11184 data points (63.84%) excluded in total
6336 valid data points (36.16%) remaining.

New sEddyProc class for site 'US-xNQ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xNQ-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 43 data points (0.24%) set to NA
H: 152 data points (0.87%) set to NA
LE: 169 data points (0.96%) set to NA
NEE: 1012 data points (5.76%) set to NA
-------------------------------------------------------------------
Data filtering:
13392 data points (76.23%) excluded by growing season filter
782 additional data points (4.45%) excluded by precipitation filter (3194
 data points = 18.18 % in total)
14174 data points (80.68%) excluded in total
3394 valid data points (19.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 43 data points (0.24%) set to NA
H: 152 data points (0.87%) set to NA
LE: 169 data points (0.96%) set to NA
NEE: 1012 data points (5.76%) set to NA
-------------------------------------------------------------------
Data filtering:
13392 data points (76.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13392 data points (76.23%) excluded in total
4176 valid data points (23.77%) remaining.

New sEddyProc class for site 'US-xNQ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xNQ-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[310/329] Processing: US-xNW

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xNW | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 235 data points (1.34%) set to NA
H: 6971 data points (39.79%) set to NA
LE: 6999 data points (39.95%) set to NA
NEE: 11496 data points (65.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 127”

-------------------------------------------------------------------
Data filtering:
15024 data points (85.75%) excluded by growing season filter
1088 additional data points (6.21%) excluded by precipitation filter (10058
 data points = 57.41 % in total)
16112 data points (91.96%) excluded in total
1408 valid data points (8.04%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 235 data points (1.34%) set to NA
H: 6971 data points (39.79%) set to NA
LE: 6999 data points (39.95%) set to NA
NEE: 11496 data points (65.62%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 127”

-------------------------------------------------------------------
Data filtering:
15024 data points (85.75%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
15024 data points (85.75%) excluded in total
2496 valid data points (14.25%) remaining.

New sEddyProc class for site 'US-xNW'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xNW-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 19 data points (0.11%) set to NA
H: 14154 data points (80.57%) set to NA
LE: 14163 data points (80.62%) set to NA
NEE: 14459 data points (82.3%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
8444 additional data points (48.06%) excluded by precipitation filter (8444
 data points = 48.06 % in total)
8444 data points (48.06%) excluded in total
9124 valid data points (51.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 19 data points (0.11%) set to NA
H: 14154 data points (80.57%) set to NA
LE: 14163 data points (80.62%) set to NA
NEE: 14459 data points (82.3%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-xNW'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xNW-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 422 data points (2.41%) set to NA
H: 6454 data points (36.84%) set to NA
LE: 6433 data points (36.72%) set to NA
NEE: 9352 data points (53.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 55”

-------------------------------------------------------------------
Data filtering:
12144 data points (69.32%) excluded by growing season filter
2404 additional data points (13.72%) excluded by precipitation filter (8160
 data points = 46.58 % in total)
14548 data points (83.04%) excluded in total
2972 valid data points (16.96%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 422 data points (2.41%) set to NA
H: 6454 data points (36.84%) set to NA
LE: 6433 data points (36.72%) set to NA
NEE: 9352 data points (53.38%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 55”

-------------------------------------------------------------------
Data filtering:
12144 data points (69.32%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12144 data points (69.32%) excluded in total
5376 valid data points (30.68%) remaining.

New sEddyProc class for site 'US-xNW'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 164.74.

Regression of reference temperature R_ref for 8 periods.

Quality control:
TA: 206 data points (1.18%) set to NA
H: 3667 data points (20.93%) set to NA
LE: 3615 data points (20.63%) set to NA
NEE: 4830 data points (27.57%) set to NA
-------------------------------------------------------------------
Data filtering:
12144 data points (69.32%) excluded by growing season filter
2736 additional data points (15.62%) excluded by precipitation filter (8748
 data points = 49.93 % in total)
14880 data points (84.93%) excluded in total
2640 valid data points (15.07%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 206 data points (1.18%) set to NA
H: 3667 data points (20.93%) set to NA
LE: 3615 data points (20.63%) set to NA
NEE: 4830 data points (27.57%) set to NA
-------------------------------------------------------------------
Data filtering:
12144 data points (69.32%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12144 data points (69.32%) excluded in total
5376 valid data points (30.68%) remaining.

New sEddyProc class for site 'US-xNW'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xNW-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 61 data points (0.35%) set to NA
H: 1522 data points (8.69%) set to NA
LE: 1519 data points (8.67%) set to NA
NEE: 3007 data points (17.16%) set to NA
-------------------------------------------------------------------
Data filtering:
13104 data points (74.79%) excluded by growing season filter
3308 additional data points (18.88%) excluded by precipitation filter (9840
 data points = 56.16 % in total)
16412 data points (93.68%) excluded in total
1108 valid data points (6.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 61 data points (0.35%) set to NA
H: 1522 data points (8.69%) set to NA
LE: 1519 data points (8.67%) set to NA
NEE: 3007 data points (17.16%) set to NA
-------------------------------------------------------------------
Data filtering:
13104 data points (74.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13104 data points (74.79%) excluded in total
4416 valid data points (25.21%) remaining.

New sEddyProc class for site 'US-xNW'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xNW-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 887 data points (5.05%) set to NA
H: 7020 data points (39.96%) set to NA
LE: 7054 data points (40.15%) set to NA
NEE: 11911 data points (67.8%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 38”

-------------------------------------------------------------------
Data filtering:
11616 data points (66.12%) excluded by growing season filter
4330 additional data points (24.65%) excluded by precipitation filter (9268
 data points = 52.76 % in total)
15946 data points (90.77%) excluded in total
1622 valid data points (9.23%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 887 data points (5.05%) set to NA
H: 7020 data points (39.96%) set to NA
LE: 7054 data points (40.15%) set to NA
NEE: 11911 data points (67.8%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 38”

-------------------------------------------------------------------
Data filtering:
11616 data points (66.12%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11616 data points (66.12%) excluded in total
5952 valid data points (33.88%) remaining.

New sEddyProc class for site 'US-xNW'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 165.4.

Regression of reference temperature R_ref for 10 periods.

[311/329] Processing: US-xPU

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xPU | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 7227 data points (41.25%) set to NA
H: 7527 data points (42.96%) set to NA
LE: 7567 data points (43.19%) set to NA
NEE: 8970 data points (51.2%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
13196 additional data points (75.32%) excluded by precipitation filter (13196
 data points = 75.32 % in total)
13196 data points (75.32%) excluded in total
4324 valid data points (24.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7227 data points (41.25%) set to NA
H: 7527 data points (42.96%) set to NA
LE: 7567 data points (43.19%) set to NA
NEE: 8970 data points (51.2%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xPU'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xPU-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 470 data points (2.68%) set to NA
H: 1662 data points (9.46%) set to NA
LE: 1675 data points (9.53%) set to NA
NEE: 2840 data points (16.17%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12880 additional data points (73.32%) excluded by precipitation filter (12880
 data points = 73.32 % in total)
12880 data points (73.32%) excluded in total
4688 valid data points (26.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 470 data points (2.68%) set to NA
H: 1662 data points (9.46%) set to NA
LE: 1675 data points (9.53%) set to NA
NEE: 2840 data points (16.17%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-xPU'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xPU-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1270 data points (7.25%) set to NA
H: 2300 data points (13.13%) set to NA
LE: 2319 data points (13.24%) set to NA
NEE: 3284 data points (18.74%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
13942 additional data points (79.58%) excluded by precipitation filter (13942
 data points = 79.58 % in total)
13942 data points (79.58%) excluded in total
3578 valid data points (20.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1270 data points (7.25%) set to NA
H: 2300 data points (13.13%) set to NA
LE: 2319 data points (13.24%) set to NA
NEE: 3284 data points (18.74%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xPU'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xPU-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 2272 data points (12.97%) set to NA
H: 2371 data points (13.53%) set to NA
LE: 2397 data points (13.68%) set to NA
NEE: 7470 data points (42.64%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12366 additional data points (70.58%) excluded by precipitation filter (12366
 data points = 70.58 % in total)
12366 data points (70.58%) excluded in total
5154 valid data points (29.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 2272 data points (12.97%) set to NA
H: 2371 data points (13.53%) set to NA
LE: 2397 data points (13.68%) set to NA
NEE: 7470 data points (42.64%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xPU'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xPU-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 69 data points (0.39%) set to NA
H: 1314 data points (7.5%) set to NA
LE: 1333 data points (7.61%) set to NA
NEE: 7669 data points (43.77%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12174 additional data points (69.49%) excluded by precipitation filter (12174
 data points = 69.49 % in total)
12174 data points (69.49%) excluded in total
5346 valid data points (30.51%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 69 data points (0.39%) set to NA
H: 1314 data points (7.5%) set to NA
LE: 1333 data points (7.61%) set to NA
NEE: 7669 data points (43.77%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xPU'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xPU-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 83 data points (0.47%) set to NA
H: 164 data points (0.93%) set to NA
LE: 165 data points (0.94%) set to NA
NEE: 1733 data points (9.86%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
12104 additional data points (68.9%) excluded by precipitation filter (12104
 data points = 68.9 % in total)
12104 data points (68.9%) excluded in total
5464 valid data points (31.1%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 83 data points (0.47%) set to NA
H: 164 data points (0.93%) set to NA
LE: 165 data points (0.94%) set to NA
NEE: 1733 data points (9.86%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-xPU'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xPU-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[312/329] Processing: US-xRM

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xRM | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 82 data points (0.47%) set to NA
H: 891 data points (5.09%) set to NA
LE: 931 data points (5.31%) set to NA
NEE: 2110 data points (12.04%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
3142 additional data points (17.93%) excluded by precipitation filter (5190
 data points = 29.62 % in total)
12358 data points (70.54%) excluded in total
5162 valid data points (29.46%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 82 data points (0.47%) set to NA
H: 891 data points (5.09%) set to NA
LE: 931 data points (5.31%) set to NA
NEE: 2110 data points (12.04%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9216 data points (52.6%) excluded in total
8304 valid data points (47.4%) remaining.

New sEddyProc class for site 'US-xRM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xRM-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1977 data points (11.25%) set to NA
H: 4722 data points (26.88%) set to NA
LE: 4731 data points (26.93%) set to NA
NEE: 6945 data points (39.53%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 86”

-------------------------------------------------------------------
Data filtering:
10704 data points (60.93%) excluded by growing season filter
1885 additional data points (10.73%) excluded by precipitation filter (3704
 data points = 21.08 % in total)
12589 data points (71.66%) excluded in total
4979 valid data points (28.34%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1977 data points (11.25%) set to NA
H: 4722 data points (26.88%) set to NA
LE: 4731 data points (26.93%) set to NA
NEE: 6945 data points (39.53%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 86”

-------------------------------------------------------------------
Data filtering:
10704 data points (60.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10704 data points (60.93%) excluded in total
6864 valid data points (39.07%) remaining.

New sEddyProc class for site 'US-xRM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xRM-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 815 data points (4.65%) set to NA
H: 2300 data points (13.13%) set to NA
LE: 2326 data points (13.28%) set to NA
NEE: 6919 data points (39.49%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 31”

-------------------------------------------------------------------
Data filtering:
8736 data points (49.86%) excluded by growing season filter
3044 additional data points (17.37%) excluded by precipitation filter (5404
 data points = 30.84 % in total)
11780 data points (67.24%) excluded in total
5740 valid data points (32.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 815 data points (4.65%) set to NA
H: 2300 data points (13.13%) set to NA
LE: 2326 data points (13.28%) set to NA
NEE: 6919 data points (39.49%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 31”

-------------------------------------------------------------------
Data filtering:
8736 data points (49.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8736 data points (49.86%) excluded in total
8784 valid data points (50.14%) remaining.

New sEddyProc class for site 'US-xRM'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 104.68.

Regression of reference temperature R_ref for 8 periods.

Quality control:
TA: 174 data points (0.99%) set to NA
H: 363 data points (2.07%) set to NA
LE: 367 data points (2.09%) set to NA
NEE: 1339 data points (7.64%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.59%) excluded by growing season filter
3616 additional data points (20.64%) excluded by precipitation filter (5858
 data points = 33.44 % in total)
12304 data points (70.23%) excluded in total
5216 valid data points (29.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 174 data points (0.99%) set to NA
H: 363 data points (2.07%) set to NA
LE: 367 data points (2.09%) set to NA
NEE: 1339 data points (7.64%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8688 data points (49.59%) excluded in total
8832 valid data points (50.41%) remaining.

New sEddyProc class for site 'US-xRM'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 133.86.

Regression of reference temperature R_ref for 3 periods.

Quality control:
TA: 9 data points (0.05%) set to NA
H: 148 data points (0.84%) set to NA
LE: 136 data points (0.78%) set to NA
NEE: 1644 data points (9.38%) set to NA
-------------------------------------------------------------------
Data filtering:
9168 data points (52.33%) excluded by growing season filter
3312 additional data points (18.9%) excluded by precipitation filter (4325
 data points = 24.69 % in total)
12480 data points (71.23%) excluded in total
5040 valid data points (28.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9 data points (0.05%) set to NA
H: 148 data points (0.84%) set to NA
LE: 136 data points (0.78%) set to NA
NEE: 1644 data points (9.38%) set to NA
-------------------------------------------------------------------
Data filtering:
9168 data points (52.33%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9168 data points (52.33%) excluded in total
8352 valid data points (47.67%) remaining.

New sEddyProc class for site 'US-xRM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xRM-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 30 data points (0.17%) set to NA
H: 74 data points (0.42%) set to NA
LE: 74 data points (0.42%) set to NA
NEE: 755 data points (4.3%) set to NA
-------------------------------------------------------------------
Data filtering:
8640 data points (49.18%) excluded by growing season filter
3260 additional data points (18.56%) excluded by precipitation filter (5030
 data points = 28.63 % in total)
11900 data points (67.74%) excluded in total
5668 valid data points (32.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 30 data points (0.17%) set to NA
H: 74 data points (0.42%) set to NA
LE: 74 data points (0.42%) set to NA
NEE: 755 data points (4.3%) set to NA
-------------------------------------------------------------------
Data filtering:
8640 data points (49.18%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8640 data points (49.18%) excluded in total
8928 valid data points (50.82%) remaining.

New sEddyProc class for site 'US-xRM'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xRM-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[313/329] Processing: US-xRN

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xRN | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 125 data points (0.71%) set to NA
H: 3795 data points (21.66%) set to NA
LE: 3991 data points (22.78%) set to NA
NEE: 16756 data points (95.64%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6524 additional data points (37.24%) excluded by precipitation filter (6524
 data points = 37.24 % in total)
6524 data points (37.24%) excluded in total
10996 valid data points (62.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 125 data points (0.71%) set to NA
H: 3795 data points (21.66%) set to NA
LE: 3991 data points (22.78%) set to NA
NEE: 16756 data points (95.64%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xRN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xRN-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 9 data points (0.05%) set to NA
H: 138 data points (0.79%) set to NA
LE: 124 data points (0.71%) set to NA
NEE: 1225 data points (6.97%) set to NA
-------------------------------------------------------------------
Data filtering:
8880 data points (50.55%) excluded by growing season filter
3630 additional data points (20.66%) excluded by precipitation filter (7240
 data points = 41.21 % in total)
12510 data points (71.21%) excluded in total
5058 valid data points (28.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 9 data points (0.05%) set to NA
H: 138 data points (0.79%) set to NA
LE: 124 data points (0.71%) set to NA
NEE: 1225 data points (6.97%) set to NA
-------------------------------------------------------------------
Data filtering:
8880 data points (50.55%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8880 data points (50.55%) excluded in total
8688 valid data points (49.45%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -53, -79 ...”
New sEddyProc class for site 'US-xRN'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -53, -79 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xRN-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 8 data points (0.05%) set to NA
H: 77 data points (0.44%) set to NA
LE: 85 data points (0.49%) set to NA
NEE: 2048 data points (11.69%) set to NA
-------------------------------------------------------------------
Data filtering:
8640 data points (49.32%) excluded by growing season filter
3050 additional data points (17.41%) excluded by precipitation filter (6054
 data points = 34.55 % in total)
11690 data points (66.72%) excluded in total
5830 valid data points (33.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8 data points (0.05%) set to NA
H: 77 data points (0.44%) set to NA
LE: 85 data points (0.49%) set to NA
NEE: 2048 data points (11.69%) set to NA
-------------------------------------------------------------------
Data filtering:
8640 data points (49.32%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8640 data points (49.32%) excluded in total
8880 valid data points (50.68%) remaining.

New sEddyProc class for site 'US-xRN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xRN-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1044 data points (5.96%) set to NA
H: 3446 data points (19.67%) set to NA
LE: 3448 data points (19.68%) set to NA
NEE: 4600 data points (26.26%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
2283 additional data points (13.03%) excluded by precipitation filter (5422
 data points = 30.95 % in total)
11499 data points (65.63%) excluded in total
6021 valid data points (34.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1044 data points (5.96%) set to NA
H: 3446 data points (19.67%) set to NA
LE: 3448 data points (19.68%) set to NA
NEE: 4600 data points (26.26%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9216 data points (52.6%) excluded in total
8304 valid data points (47.4%) remaining.

New sEddyProc class for site 'US-xRN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 16 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xRN-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 170 data points (0.97%) set to NA
H: 390 data points (2.23%) set to NA
LE: 434 data points (2.48%) set to NA
NEE: 2146 data points (12.25%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.78%) excluded by growing season filter
2196 additional data points (12.53%) excluded by precipitation filter (5500
 data points = 31.39 % in total)
11268 data points (64.32%) excluded in total
6252 valid data points (35.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 170 data points (0.97%) set to NA
H: 390 data points (2.23%) set to NA
LE: 434 data points (2.48%) set to NA
NEE: 2146 data points (12.25%) set to NA
-------------------------------------------------------------------
Data filtering:
9072 data points (51.78%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9072 data points (51.78%) excluded in total
8448 valid data points (48.22%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -55 ...”
New sEddyProc class for site 'US-xRN'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -55 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xRN-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 343 data points (1.95%) set to NA
H: 633 data points (3.6%) set to NA
LE: 638 data points (3.63%) set to NA
NEE: 1780 data points (10.13%) set to NA
-------------------------------------------------------------------
Data filtering:
10368 data points (59.02%) excluded by growing season filter
2311 additional data points (13.15%) excluded by precipitation filter (5837
 data points = 33.23 % in total)
12679 data points (72.17%) excluded in total
4889 valid data points (27.83%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 343 data points (1.95%) set to NA
H: 633 data points (3.6%) set to NA
LE: 638 data points (3.63%) set to NA
NEE: 1780 data points (10.13%) set to NA
-------------------------------------------------------------------
Data filtering:
10368 data points (59.02%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10368 data points (59.02%) excluded in total
7200 valid data points (40.98%) remaining.

New sEddyProc class for site 'US-xRN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xRN-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[314/329] Processing: US-xSB

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xSB | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 103 data points (0.59%) set to NA
H: 11415 data points (65.15%) set to NA
LE: 11385 data points (64.98%) set to NA
NEE: 12348 data points (70.48%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 139”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
4932 additional data points (28.15%) excluded by precipitation filter (4932
 data points = 28.15 % in total)
4932 data points (28.15%) excluded in total
12588 valid data points (71.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 103 data points (0.59%) set to NA
H: 11415 data points (65.15%) set to NA
LE: 11385 data points (64.98%) set to NA
NEE: 12348 data points (70.48%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 139”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xSB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSB-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 23 data points (0.13%) set to NA
H: 995 data points (5.66%) set to NA
LE: 1018 data points (5.79%) set to NA
NEE: 2448 data points (13.93%) set to NA
-------------------------------------------------------------------
Data filtering:
864 data points (4.92%) excluded by growing season filter
5572 additional data points (31.72%) excluded by precipitation filter (5798
 data points = 33 % in total)
6436 data points (36.63%) excluded in total
11132 valid data points (63.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 23 data points (0.13%) set to NA
H: 995 data points (5.66%) set to NA
LE: 1018 data points (5.79%) set to NA
NEE: 2448 data points (13.93%) set to NA
-------------------------------------------------------------------
Data filtering:
864 data points (4.92%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
864 data points (4.92%) excluded in total
16704 valid data points (95.08%) remaining.

New sEddyProc class for site 'US-xSB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSB-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 148 data points (0.84%) set to NA
H: 884 data points (5.05%) set to NA
LE: 896 data points (5.11%) set to NA
NEE: 1939 data points (11.07%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6012 additional data points (34.32%) excluded by precipitation filter (6012
 data points = 34.32 % in total)
6012 data points (34.32%) excluded in total
11508 valid data points (65.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 148 data points (0.84%) set to NA
H: 884 data points (5.05%) set to NA
LE: 896 data points (5.11%) set to NA
NEE: 1939 data points (11.07%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xSB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSB-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 546 data points (3.12%) set to NA
H: 6744 data points (38.49%) set to NA
LE: 6785 data points (38.73%) set to NA
NEE: 7390 data points (42.18%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 89”

-------------------------------------------------------------------
Data filtering:
672 data points (3.84%) excluded by growing season filter
4037 additional data points (23.04%) excluded by precipitation filter (4057
 data points = 23.16 % in total)
4709 data points (26.88%) excluded in total
12811 valid data points (73.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 546 data points (3.12%) set to NA
H: 6744 data points (38.49%) set to NA
LE: 6785 data points (38.73%) set to NA
NEE: 7390 data points (42.18%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 89”

-------------------------------------------------------------------
Data filtering:
672 data points (3.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
672 data points (3.84%) excluded in total
16848 valid data points (96.16%) remaining.

New sEddyProc class for site 'US-xSB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSB-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 66 data points (0.38%) set to NA
H: 2016 data points (11.51%) set to NA
LE: 2023 data points (11.55%) set to NA
NEE: 4683 data points (26.73%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5601 additional data points (31.97%) excluded by precipitation filter (5601
 data points = 31.97 % in total)
5601 data points (31.97%) excluded in total
11919 valid data points (68.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 66 data points (0.38%) set to NA
H: 2016 data points (11.51%) set to NA
LE: 2023 data points (11.55%) set to NA
NEE: 4683 data points (26.73%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xSB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSB-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 57 data points (0.32%) set to NA
H: 2282 data points (12.99%) set to NA
LE: 2293 data points (13.05%) set to NA
NEE: 2647 data points (15.07%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5928 additional data points (33.74%) excluded by precipitation filter (5928
 data points = 33.74 % in total)
5928 data points (33.74%) excluded in total
11640 valid data points (66.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 57 data points (0.32%) set to NA
H: 2282 data points (12.99%) set to NA
LE: 2293 data points (13.05%) set to NA
NEE: 2647 data points (15.07%) set to NA
-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-xSB'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSB-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[315/329] Processing: US-xSC

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xSC | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 64 data points (0.37%) set to NA
H: 8939 data points (51.02%) set to NA
LE: 8937 data points (51.01%) set to NA
NEE: 15330 data points (87.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6643 additional data points (37.92%) excluded by precipitation filter (6643
 data points = 37.92 % in total)
6643 data points (37.92%) excluded in total
10877 valid data points (62.08%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 64 data points (0.37%) set to NA
H: 8939 data points (51.02%) set to NA
LE: 8937 data points (51.01%) set to NA
NEE: 15330 data points (87.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xSC'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSC-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 154 data points (0.88%) set to NA
H: 8182 data points (46.57%) set to NA
LE: 8189 data points (46.61%) set to NA
NEE: 14137 data points (80.47%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5619 additional data points (31.98%) excluded by precipitation filter (5619
 data points = 31.98 % in total)
5619 data points (31.98%) excluded in total
11949 valid data points (68.02%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 154 data points (0.88%) set to NA
H: 8182 data points (46.57%) set to NA
LE: 8189 data points (46.61%) set to NA
NEE: 14137 data points (80.47%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-xSC'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSC-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 12 data points (0.07%) set to NA
H: 1898 data points (10.83%) set to NA
LE: 1932 data points (11.03%) set to NA
NEE: 7424 data points (42.37%) set to NA
-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
2866 additional data points (16.36%) excluded by precipitation filter (5669
 data points = 32.36 % in total)
11986 data points (68.41%) excluded in total
5534 valid data points (31.59%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12 data points (0.07%) set to NA
H: 1898 data points (10.83%) set to NA
LE: 1932 data points (11.03%) set to NA
NEE: 7424 data points (42.37%) set to NA
-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9120 data points (52.05%) excluded in total
8400 valid data points (47.95%) remaining.

New sEddyProc class for site 'US-xSC'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSC-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 91 data points (0.52%) set to NA
H: 1157 data points (6.6%) set to NA
LE: 1167 data points (6.66%) set to NA
NEE: 2738 data points (15.63%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
3193 additional data points (18.22%) excluded by precipitation filter (5699
 data points = 32.53 % in total)
12553 data points (71.65%) excluded in total
4967 valid data points (28.35%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 91 data points (0.52%) set to NA
H: 1157 data points (6.6%) set to NA
LE: 1167 data points (6.66%) set to NA
NEE: 2738 data points (15.63%) set to NA
-------------------------------------------------------------------
Data filtering:
9360 data points (53.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9360 data points (53.42%) excluded in total
8160 valid data points (46.58%) remaining.

New sEddyProc class for site 'US-xSC'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 162.23.

Regression of reference temperature R_ref for 3 periods.

Quality control:
TA: 42 data points (0.24%) set to NA
H: 324 data points (1.85%) set to NA
LE: 339 data points (1.93%) set to NA
NEE: 3051 data points (17.41%) set to NA
-------------------------------------------------------------------
Data filtering:
8736 data points (49.86%) excluded by growing season filter
3002 additional data points (17.13%) excluded by precipitation filter (5246
 data points = 29.94 % in total)
11738 data points (67%) excluded in total
5782 valid data points (33%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 42 data points (0.24%) set to NA
H: 324 data points (1.85%) set to NA
LE: 339 data points (1.93%) set to NA
NEE: 3051 data points (17.41%) set to NA
-------------------------------------------------------------------
Data filtering:
8736 data points (49.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8736 data points (49.86%) excluded in total
8784 valid data points (50.14%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
New sEddyProc class for site 'US-xSC'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSC-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 165 data points (0.94%) set to NA
H: 744 data points (4.23%) set to NA
LE: 749 data points (4.26%) set to NA
NEE: 2642 data points (15.04%) set to NA
-------------------------------------------------------------------
Data filtering:
8928 data points (50.82%) excluded by growing season filter
2997 additional data points (17.06%) excluded by precipitation filter (5862
 data points = 33.37 % in total)
11925 data points (67.88%) excluded in total
5643 valid data points (32.12%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 165 data points (0.94%) set to NA
H: 744 data points (4.23%) set to NA
LE: 749 data points (4.26%) set to NA
NEE: 2642 data points (15.04%) set to NA
-------------------------------------------------------------------
Data filtering:
8928 data points (50.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8928 data points (50.82%) excluded in total
8640 valid data points (49.18%) remaining.

New sEddyProc class for site 'US-xSC'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSC-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[316/329] Processing: US-xSE

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xSE | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 71 data points (0.41%) set to NA
H: 9144 data points (52.19%) set to NA
LE: 9149 data points (52.22%) set to NA
NEE: 12058 data points (68.82%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 127”

-------------------------------------------------------------------
Data filtering:
4032 data points (23.01%) excluded by growing season filter
6299 additional data points (35.95%) excluded by precipitation filter (7791
 data points = 44.47 % in total)
10331 data points (58.97%) excluded in total
7189 valid data points (41.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 71 data points (0.41%) set to NA
H: 9144 data points (52.19%) set to NA
LE: 9149 data points (52.22%) set to NA
NEE: 12058 data points (68.82%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 127”

-------------------------------------------------------------------
Data filtering:
4032 data points (23.01%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
4032 data points (23.01%) excluded in total
13488 valid data points (76.99%) remaining.

New sEddyProc class for site 'US-xSE'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 200.43.

Regression of reference temperature R_ref for 2 periods.

Quality control:
TA: 71 data points (0.4%) set to NA
H: 1262 data points (7.18%) set to NA
LE: 1265 data points (7.2%) set to NA
NEE: 1627 data points (9.26%) set to NA
-------------------------------------------------------------------
Data filtering:
9504 data points (54.1%) excluded by growing season filter
3039 additional data points (17.3%) excluded by precipitation filter (6801
 data points = 38.71 % in total)
12543 data points (71.4%) excluded in total
5025 valid data points (28.6%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 71 data points (0.4%) set to NA
H: 1262 data points (7.18%) set to NA
LE: 1265 data points (7.2%) set to NA
NEE: 1627 data points (9.26%) set to NA
-------------------------------------------------------------------
Data filtering:
9504 data points (54.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9504 data points (54.1%) excluded in total
8064 valid data points (45.9%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 25 cases! Invalid values with 'NEE < -50': -52, -53, -63, -51, -65, -63, -63, -52, -61, -52, -60, -66, -68, -61, -60, -53, -54, -57, -54, -60, -58, -53, -55, -51, -70 ...”
New sEddyProc class for site 'US-xSE'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 25 cases! Invalid values with 'NEE < -50': -52, -53, -63, -51, -65, -63, -63, -52, -61, -52, -60, -66, -68, -61, -60, -53, -54, -57, -54, -60, -58, -53, -55, -51, -70 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSE-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 175 data points (1%) set to NA
H: 312 data points (1.78%) set to NA
LE: 325 data points (1.86%) set to NA
NEE: 659 data points (3.76%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.59%) excluded by growing season filter
2653 additional data points (15.14%) excluded by precipitation filter (5636
 data points = 32.17 % in total)
11341 data points (64.73%) excluded in total
6179 valid data points (35.27%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 175 data points (1%) set to NA
H: 312 data points (1.78%) set to NA
LE: 325 data points (1.86%) set to NA
NEE: 659 data points (3.76%) set to NA
-------------------------------------------------------------------
Data filtering:
8688 data points (49.59%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8688 data points (49.59%) excluded in total
8832 valid data points (50.41%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -50, -52, -58 ...”
New sEddyProc class for site 'US-xSE'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 3 cases! Invalid values with 'NEE < -50': -50, -52, -58 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSE-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 103 data points (0.59%) set to NA
H: 185 data points (1.06%) set to NA
LE: 191 data points (1.09%) set to NA
NEE: 417 data points (2.38%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
2667 additional data points (15.22%) excluded by precipitation filter (5882
 data points = 33.57 % in total)
12603 data points (71.93%) excluded in total
4917 valid data points (28.07%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 103 data points (0.59%) set to NA
H: 185 data points (1.06%) set to NA
LE: 191 data points (1.09%) set to NA
NEE: 417 data points (2.38%) set to NA
-------------------------------------------------------------------
Data filtering:
9936 data points (56.71%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9936 data points (56.71%) excluded in total
7584 valid data points (43.29%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
New sEddyProc class for site 'US-xSE'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -54 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSE-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 84 data points (0.48%) set to NA
H: 454 data points (2.59%) set to NA
LE: 476 data points (2.72%) set to NA
NEE: 1192 data points (6.8%) set to NA
-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
2742 additional data points (15.65%) excluded by precipitation filter (4898
 data points = 27.96 % in total)
11862 data points (67.71%) excluded in total
5658 valid data points (32.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 84 data points (0.48%) set to NA
H: 454 data points (2.59%) set to NA
LE: 476 data points (2.72%) set to NA
NEE: 1192 data points (6.8%) set to NA
-------------------------------------------------------------------
Data filtering:
9120 data points (52.05%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9120 data points (52.05%) excluded in total
8400 valid data points (47.95%) remaining.

New sEddyProc class for site 'US-xSE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSE-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 37 data points (0.21%) set to NA
H: 1401 data points (7.97%) set to NA
LE: 1389 data points (7.91%) set to NA
NEE: 2297 data points (13.07%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.46%) excluded by growing season filter
2426 additional data points (13.81%) excluded by precipitation filter (5461
 data points = 31.08 % in total)
11642 data points (66.27%) excluded in total
5926 valid data points (33.73%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 37 data points (0.21%) set to NA
H: 1401 data points (7.97%) set to NA
LE: 1389 data points (7.91%) set to NA
NEE: 2297 data points (13.07%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.46%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9216 data points (52.46%) excluded in total
8352 valid data points (47.54%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -53, -58 ...”
New sEddyProc class for site 'US-xSE'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -53, -58 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSE-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[317/329] Processing: US-xSJ

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xSJ | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 585 data points (3.34%) set to NA
H: 8976 data points (51.23%) set to NA
LE: 9034 data points (51.56%) set to NA
NEE: 9405 data points (53.68%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3206 additional data points (18.3%) excluded by precipitation filter (3206
 data points = 18.3 % in total)
3206 data points (18.3%) excluded in total
14314 valid data points (81.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 585 data points (3.34%) set to NA
H: 8976 data points (51.23%) set to NA
LE: 9034 data points (51.56%) set to NA
NEE: 9405 data points (53.68%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xSJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 10 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSJ-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 124 data points (0.71%) set to NA
H: 4943 data points (28.14%) set to NA
LE: 5005 data points (28.49%) set to NA
NEE: 6332 data points (36.04%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 20”

-------------------------------------------------------------------
Data filtering:
11712 data points (66.67%) excluded by growing season filter
858 additional data points (4.88%) excluded by precipitation filter (1590
 data points = 9.05 % in total)
12570 data points (71.55%) excluded in total
4998 valid data points (28.45%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 124 data points (0.71%) set to NA
H: 4943 data points (28.14%) set to NA
LE: 5005 data points (28.49%) set to NA
NEE: 6332 data points (36.04%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 20”

-------------------------------------------------------------------
Data filtering:
11712 data points (66.67%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11712 data points (66.67%) excluded in total
5856 valid data points (33.33%) remaining.

New sEddyProc class for site 'US-xSJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSJ-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 39 data points (0.22%) set to NA
H: 356 data points (2.03%) set to NA
LE: 565 data points (3.22%) set to NA
NEE: 1564 data points (8.93%) set to NA
-------------------------------------------------------------------
Data filtering:
10128 data points (57.81%) excluded by growing season filter
1124 additional data points (6.42%) excluded by precipitation filter (1802
 data points = 10.29 % in total)
11252 data points (64.22%) excluded in total
6268 valid data points (35.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 39 data points (0.22%) set to NA
H: 356 data points (2.03%) set to NA
LE: 565 data points (3.22%) set to NA
NEE: 1564 data points (8.93%) set to NA
-------------------------------------------------------------------
Data filtering:
10128 data points (57.81%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10128 data points (57.81%) excluded in total
7392 valid data points (42.19%) remaining.

New sEddyProc class for site 'US-xSJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSJ-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 85 data points (0.49%) set to NA
H: 164 data points (0.94%) set to NA
LE: 272 data points (1.55%) set to NA
NEE: 1837 data points (10.49%) set to NA
-------------------------------------------------------------------
Data filtering:
8976 data points (51.23%) excluded by growing season filter
564 additional data points (3.22%) excluded by precipitation filter (1550
 data points = 8.85 % in total)
9540 data points (54.45%) excluded in total
7980 valid data points (45.55%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 85 data points (0.49%) set to NA
H: 164 data points (0.94%) set to NA
LE: 272 data points (1.55%) set to NA
NEE: 1837 data points (10.49%) set to NA
-------------------------------------------------------------------
Data filtering:
8976 data points (51.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8976 data points (51.23%) excluded in total
8544 valid data points (48.77%) remaining.

New sEddyProc class for site 'US-xSJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSJ-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 63 data points (0.36%) set to NA
H: 1212 data points (6.92%) set to NA
LE: 1291 data points (7.37%) set to NA
NEE: 2119 data points (12.09%) set to NA
-------------------------------------------------------------------
Data filtering:
9024 data points (51.51%) excluded by growing season filter
2380 additional data points (13.58%) excluded by precipitation filter (3898
 data points = 22.25 % in total)
11404 data points (65.09%) excluded in total
6116 valid data points (34.91%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 63 data points (0.36%) set to NA
H: 1212 data points (6.92%) set to NA
LE: 1291 data points (7.37%) set to NA
NEE: 2119 data points (12.09%) set to NA
-------------------------------------------------------------------
Data filtering:
9024 data points (51.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9024 data points (51.51%) excluded in total
8496 valid data points (48.49%) remaining.

New sEddyProc class for site 'US-xSJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSJ-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 52 data points (0.3%) set to NA
H: 1219 data points (6.94%) set to NA
LE: 1282 data points (7.3%) set to NA
NEE: 2614 data points (14.88%) set to NA
-------------------------------------------------------------------
Data filtering:
11568 data points (65.85%) excluded by growing season filter
1366 additional data points (7.78%) excluded by precipitation filter (3204
 data points = 18.24 % in total)
12934 data points (73.62%) excluded in total
4634 valid data points (26.38%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 52 data points (0.3%) set to NA
H: 1219 data points (6.94%) set to NA
LE: 1282 data points (7.3%) set to NA
NEE: 2614 data points (14.88%) set to NA
-------------------------------------------------------------------
Data filtering:
11568 data points (65.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11568 data points (65.85%) excluded in total
6000 valid data points (34.15%) remaining.

New sEddyProc class for site 'US-xSJ'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSJ-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[318/329] Processing: US-xSP

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xSP | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 1577 data points (9%) set to NA
H: 3760 data points (21.46%) set to NA
LE: 3734 data points (21.31%) set to NA
NEE: 6809 data points (38.86%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3406 additional data points (19.44%) excluded by precipitation filter (3406
 data points = 19.44 % in total)
3406 data points (19.44%) excluded in total
14114 valid data points (80.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1577 data points (9%) set to NA
H: 3760 data points (21.46%) set to NA
LE: 3734 data points (21.31%) set to NA
NEE: 6809 data points (38.86%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xSP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 19 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSP-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1380 data points (7.86%) set to NA
H: 2906 data points (16.54%) set to NA
LE: 2871 data points (16.34%) set to NA
NEE: 3123 data points (17.78%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1521 additional data points (8.66%) excluded by precipitation filter (1521
 data points = 8.66 % in total)
1521 data points (8.66%) excluded in total
16047 valid data points (91.34%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1380 data points (7.86%) set to NA
H: 2906 data points (16.54%) set to NA
LE: 2871 data points (16.34%) set to NA
NEE: 3123 data points (17.78%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-xSP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 11 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSP-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1256 data points (7.17%) set to NA
H: 2518 data points (14.37%) set to NA
LE: 2550 data points (14.55%) set to NA
NEE: 2894 data points (16.52%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2320 additional data points (13.24%) excluded by precipitation filter (2320
 data points = 13.24 % in total)
2320 data points (13.24%) excluded in total
15200 valid data points (86.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1256 data points (7.17%) set to NA
H: 2518 data points (14.37%) set to NA
LE: 2550 data points (14.55%) set to NA
NEE: 2894 data points (16.52%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xSP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 10 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSP-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 140 data points (0.8%) set to NA
H: 239 data points (1.36%) set to NA
LE: 243 data points (1.39%) set to NA
NEE: 649 data points (3.7%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
1118 additional data points (6.38%) excluded by precipitation filter (1118
 data points = 6.38 % in total)
1118 data points (6.38%) excluded in total
16402 valid data points (93.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 140 data points (0.8%) set to NA
H: 239 data points (1.36%) set to NA
LE: 243 data points (1.39%) set to NA
NEE: 649 data points (3.7%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xSP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSP-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 319 data points (1.82%) set to NA
H: 3746 data points (21.38%) set to NA
LE: 3725 data points (21.26%) set to NA
NEE: 4009 data points (22.88%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2814 additional data points (16.06%) excluded by precipitation filter (2814
 data points = 16.06 % in total)
2814 data points (16.06%) excluded in total
14706 valid data points (83.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 319 data points (1.82%) set to NA
H: 3746 data points (21.38%) set to NA
LE: 3725 data points (21.26%) set to NA
NEE: 4009 data points (22.88%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xSP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSP-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 161 data points (0.92%) set to NA
H: 421 data points (2.4%) set to NA
LE: 412 data points (2.35%) set to NA
NEE: 628 data points (3.57%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3277 additional data points (18.65%) excluded by precipitation filter (3277
 data points = 18.65 % in total)
3277 data points (18.65%) excluded in total
14291 valid data points (81.35%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 161 data points (0.92%) set to NA
H: 421 data points (2.4%) set to NA
LE: 412 data points (2.35%) set to NA
NEE: 628 data points (3.57%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-xSP'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSP-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[319/329] Processing: US-xSR

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xSR | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 41 data points (0.23%) set to NA
H: 3533 data points (20.17%) set to NA
LE: 3623 data points (20.68%) set to NA
NEE: 7922 data points (45.22%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 25”

-------------------------------------------------------------------
Data filtering:
7152 data points (40.82%) excluded by growing season filter
904 additional data points (5.16%) excluded by precipitation filter (2658
 data points = 15.17 % in total)
8056 data points (45.98%) excluded in total
9464 valid data points (54.02%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 41 data points (0.23%) set to NA
H: 3533 data points (20.17%) set to NA
LE: 3623 data points (20.68%) set to NA
NEE: 7922 data points (45.22%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 25”

-------------------------------------------------------------------
Data filtering:
7152 data points (40.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7152 data points (40.82%) excluded in total
10368 valid data points (59.18%) remaining.

New sEddyProc class for site 'US-xSR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSR-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 159 data points (0.91%) set to NA
H: 4061 data points (23.12%) set to NA
LE: 4142 data points (23.58%) set to NA
NEE: 8902 data points (50.67%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 45”

-------------------------------------------------------------------
Data filtering:
8784 data points (50%) excluded by growing season filter
876 additional data points (4.99%) excluded by precipitation filter (1938
 data points = 11.03 % in total)
9660 data points (54.99%) excluded in total
7908 valid data points (45.01%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 159 data points (0.91%) set to NA
H: 4061 data points (23.12%) set to NA
LE: 4142 data points (23.58%) set to NA
NEE: 8902 data points (50.67%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 45”

-------------------------------------------------------------------
Data filtering:
8784 data points (50%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8784 data points (50%) excluded in total
8784 valid data points (50%) remaining.

New sEddyProc class for site 'US-xSR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSR-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 41 data points (0.23%) set to NA
H: 2071 data points (11.82%) set to NA
LE: 2090 data points (11.93%) set to NA
NEE: 8696 data points (49.63%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 49”

-------------------------------------------------------------------
Data filtering:
13104 data points (74.79%) excluded by growing season filter
1456 additional data points (8.31%) excluded by precipitation filter (2332
 data points = 13.31 % in total)
14560 data points (83.11%) excluded in total
2960 valid data points (16.89%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 41 data points (0.23%) set to NA
H: 2071 data points (11.82%) set to NA
LE: 2090 data points (11.93%) set to NA
NEE: 8696 data points (49.63%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 49”

-------------------------------------------------------------------
Data filtering:
13104 data points (74.79%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13104 data points (74.79%) excluded in total
4416 valid data points (25.21%) remaining.

New sEddyProc class for site 'US-xSR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSR-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 221 data points (1.26%) set to NA
H: 1304 data points (7.44%) set to NA
LE: 1317 data points (7.52%) set to NA
NEE: 1769 data points (10.1%) set to NA
-------------------------------------------------------------------
Data filtering:
13584 data points (77.53%) excluded by growing season filter
892 additional data points (5.09%) excluded by precipitation filter (2422
 data points = 13.82 % in total)
14476 data points (82.63%) excluded in total
3044 valid data points (17.37%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 221 data points (1.26%) set to NA
H: 1304 data points (7.44%) set to NA
LE: 1317 data points (7.52%) set to NA
NEE: 1769 data points (10.1%) set to NA
-------------------------------------------------------------------
Data filtering:
13584 data points (77.53%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13584 data points (77.53%) excluded in total
3936 valid data points (22.47%) remaining.

New sEddyProc class for site 'US-xSR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSR-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 346 data points (1.97%) set to NA
H: 92 data points (0.53%) set to NA
LE: 154 data points (0.88%) set to NA
NEE: 1331 data points (7.6%) set to NA
-------------------------------------------------------------------
Data filtering:
8832 data points (50.41%) excluded by growing season filter
1680 additional data points (9.59%) excluded by precipitation filter (2296
 data points = 13.11 % in total)
10512 data points (60%) excluded in total
7008 valid data points (40%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 346 data points (1.97%) set to NA
H: 92 data points (0.53%) set to NA
LE: 154 data points (0.88%) set to NA
NEE: 1331 data points (7.6%) set to NA
-------------------------------------------------------------------
Data filtering:
8832 data points (50.41%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8832 data points (50.41%) excluded in total
8688 valid data points (49.59%) remaining.

New sEddyProc class for site 'US-xSR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSR-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 23 data points (0.13%) set to NA
H: 92 data points (0.52%) set to NA
LE: 116 data points (0.66%) set to NA
NEE: 2245 data points (12.78%) set to NA
-------------------------------------------------------------------
Data filtering:
9504 data points (54.1%) excluded by growing season filter
1536 additional data points (8.74%) excluded by precipitation filter (2308
 data points = 13.14 % in total)
11040 data points (62.84%) excluded in total
6528 valid data points (37.16%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 23 data points (0.13%) set to NA
H: 92 data points (0.52%) set to NA
LE: 116 data points (0.66%) set to NA
NEE: 2245 data points (12.78%) set to NA
-------------------------------------------------------------------
Data filtering:
9504 data points (54.1%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9504 data points (54.1%) excluded in total
8064 valid data points (45.9%) remaining.

New sEddyProc class for site 'US-xSR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xSR-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[320/329] Processing: US-xST

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xST | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 78 data points (0.45%) set to NA
H: 219 data points (1.25%) set to NA
LE: 230 data points (1.31%) set to NA
NEE: 786 data points (4.49%) set to NA
-------------------------------------------------------------------
Data filtering:
11712 data points (66.85%) excluded by growing season filter
2524 additional data points (14.41%) excluded by precipitation filter (6801
 data points = 38.82 % in total)
14236 data points (81.26%) excluded in total
3284 valid data points (18.74%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 78 data points (0.45%) set to NA
H: 219 data points (1.25%) set to NA
LE: 230 data points (1.31%) set to NA
NEE: 786 data points (4.49%) set to NA
-------------------------------------------------------------------
Data filtering:
11712 data points (66.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11712 data points (66.85%) excluded in total
5808 valid data points (33.15%) remaining.

New sEddyProc class for site 'US-xST'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xST-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 6 data points (0.03%) set to NA
H: 75 data points (0.43%) set to NA
LE: 65 data points (0.37%) set to NA
NEE: 889 data points (5.06%) set to NA
-------------------------------------------------------------------
Data filtering:
11472 data points (65.3%) excluded by growing season filter
2052 additional data points (11.68%) excluded by precipitation filter (5120
 data points = 29.14 % in total)
13524 data points (76.98%) excluded in total
4044 valid data points (23.02%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 6 data points (0.03%) set to NA
H: 75 data points (0.43%) set to NA
LE: 65 data points (0.37%) set to NA
NEE: 889 data points (5.06%) set to NA
-------------------------------------------------------------------
Data filtering:
11472 data points (65.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11472 data points (65.3%) excluded in total
6096 valid data points (34.7%) remaining.

New sEddyProc class for site 'US-xST'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xST-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 49 data points (0.28%) set to NA
H: 9061 data points (51.72%) set to NA
LE: 9083 data points (51.84%) set to NA
NEE: 9264 data points (52.88%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 127”

-------------------------------------------------------------------
Data filtering:
8736 data points (49.86%) excluded by growing season filter
2977 additional data points (16.99%) excluded by precipitation filter (5768
 data points = 32.92 % in total)
11713 data points (66.86%) excluded in total
5807 valid data points (33.14%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 49 data points (0.28%) set to NA
H: 9061 data points (51.72%) set to NA
LE: 9083 data points (51.84%) set to NA
NEE: 9264 data points (52.88%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 127”

-------------------------------------------------------------------
Data filtering:
8736 data points (49.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8736 data points (49.86%) excluded in total
8784 valid data points (50.14%) remaining.

New sEddyProc class for site 'US-xST'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xST-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 12 data points (0.07%) set to NA
H: 86 data points (0.49%) set to NA
LE: 85 data points (0.49%) set to NA
NEE: 523 data points (2.99%) set to NA
-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
2459 additional data points (14.04%) excluded by precipitation filter (5810
 data points = 33.16 % in total)
13547 data points (77.32%) excluded in total
3973 valid data points (22.68%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12 data points (0.07%) set to NA
H: 86 data points (0.49%) set to NA
LE: 85 data points (0.49%) set to NA
NEE: 523 data points (2.99%) set to NA
-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11088 data points (63.29%) excluded in total
6432 valid data points (36.71%) remaining.

New sEddyProc class for site 'US-xST'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xST-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 21 data points (0.12%) set to NA
H: 1956 data points (11.16%) set to NA
LE: 1985 data points (11.33%) set to NA
NEE: 2825 data points (16.12%) set to NA
-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
1868 additional data points (10.66%) excluded by precipitation filter (5652
 data points = 32.26 % in total)
12956 data points (73.95%) excluded in total
4564 valid data points (26.05%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 21 data points (0.12%) set to NA
H: 1956 data points (11.16%) set to NA
LE: 1985 data points (11.33%) set to NA
NEE: 2825 data points (16.12%) set to NA
-------------------------------------------------------------------
Data filtering:
11088 data points (63.29%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11088 data points (63.29%) excluded in total
6432 valid data points (36.71%) remaining.

New sEddyProc class for site 'US-xST'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xST-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 66 data points (0.38%) set to NA
H: 986 data points (5.61%) set to NA
LE: 997 data points (5.68%) set to NA
NEE: 1563 data points (8.9%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.3%) excluded by growing season filter
2817 additional data points (16.03%) excluded by precipitation filter (5804
 data points = 33.04 % in total)
13761 data points (78.33%) excluded in total
3807 valid data points (21.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 66 data points (0.38%) set to NA
H: 986 data points (5.61%) set to NA
LE: 997 data points (5.68%) set to NA
NEE: 1563 data points (8.9%) set to NA
-------------------------------------------------------------------
Data filtering:
10944 data points (62.3%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10944 data points (62.3%) excluded in total
6624 valid data points (37.7%) remaining.

New sEddyProc class for site 'US-xST'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 301.31.

Regression of reference temperature R_ref for 1 periods.

[321/329] Processing: US-xTE

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xTE | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 601 data points (3.43%) set to NA
H: 4132 data points (23.58%) set to NA
LE: 4145 data points (23.66%) set to NA
NEE: 8300 data points (47.37%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6018 additional data points (34.35%) excluded by precipitation filter (6018
 data points = 34.35 % in total)
6018 data points (34.35%) excluded in total
11502 valid data points (65.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 601 data points (3.43%) set to NA
H: 4132 data points (23.58%) set to NA
LE: 4145 data points (23.66%) set to NA
NEE: 8300 data points (47.37%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xTE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xTE-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 86 data points (0.49%) set to NA
H: 3756 data points (21.38%) set to NA
LE: 3766 data points (21.44%) set to NA
NEE: 4123 data points (23.47%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
2484 additional data points (14.14%) excluded by precipitation filter (2484
 data points = 14.14 % in total)
2484 data points (14.14%) excluded in total
15084 valid data points (85.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 86 data points (0.49%) set to NA
H: 3756 data points (21.38%) set to NA
LE: 3766 data points (21.44%) set to NA
NEE: 4123 data points (23.47%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-xTE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xTE-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 575 data points (3.28%) set to NA
H: 1829 data points (10.44%) set to NA
LE: 1887 data points (10.77%) set to NA
NEE: 2480 data points (14.16%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3165 additional data points (18.07%) excluded by precipitation filter (3165
 data points = 18.07 % in total)
3165 data points (18.07%) excluded in total
14355 valid data points (81.93%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 575 data points (3.28%) set to NA
H: 1829 data points (10.44%) set to NA
LE: 1887 data points (10.77%) set to NA
NEE: 2480 data points (14.16%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xTE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xTE-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1156 data points (6.6%) set to NA
H: 1313 data points (7.49%) set to NA
LE: 1373 data points (7.84%) set to NA
NEE: 3060 data points (17.47%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3228 additional data points (18.42%) excluded by precipitation filter (3228
 data points = 18.42 % in total)
3228 data points (18.42%) excluded in total
14292 valid data points (81.58%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1156 data points (6.6%) set to NA
H: 1313 data points (7.49%) set to NA
LE: 1373 data points (7.84%) set to NA
NEE: 3060 data points (17.47%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xTE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xTE-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 430 data points (2.45%) set to NA
H: 2934 data points (16.75%) set to NA
LE: 2964 data points (16.92%) set to NA
NEE: 6267 data points (35.77%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3907 additional data points (22.3%) excluded by precipitation filter (3907
 data points = 22.3 % in total)
3907 data points (22.3%) excluded in total
13613 valid data points (77.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 430 data points (2.45%) set to NA
H: 2934 data points (16.75%) set to NA
LE: 2964 data points (16.92%) set to NA
NEE: 6267 data points (35.77%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17520 valid data points (100%) remaining.

New sEddyProc class for site 'US-xTE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xTE-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 231 data points (1.31%) set to NA
H: 753 data points (4.29%) set to NA
LE: 765 data points (4.35%) set to NA
NEE: 937 data points (5.33%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
3918 additional data points (22.3%) excluded by precipitation filter (3918
 data points = 22.3 % in total)
3918 data points (22.3%) excluded in total
13650 valid data points (77.7%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 231 data points (1.31%) set to NA
H: 753 data points (4.29%) set to NA
LE: 765 data points (4.35%) set to NA
NEE: 937 data points (5.33%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-xTE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xTE-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[322/329] Processing: US-xTL

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xTL | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 451 data points (2.57%) set to NA
H: 1986 data points (11.34%) set to NA
LE: 1980 data points (11.3%) set to NA
NEE: 10425 data points (59.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 151”

-------------------------------------------------------------------
Data filtering:
7680 data points (43.84%) excluded by growing season filter
3770 additional data points (21.52%) excluded by precipitation filter (7090
 data points = 40.47 % in total)
11450 data points (65.35%) excluded in total
6070 valid data points (34.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 451 data points (2.57%) set to NA
H: 1986 data points (11.34%) set to NA
LE: 1980 data points (11.3%) set to NA
NEE: 10425 data points (59.5%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 151”

-------------------------------------------------------------------
Data filtering:
7680 data points (43.84%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7680 data points (43.84%) excluded in total
9840 valid data points (56.16%) remaining.

New sEddyProc class for site 'US-xTL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xTL-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 314 data points (1.79%) set to NA
H: 17392 data points (99%) set to NA
LE: 17391 data points (98.99%) set to NA
NEE: 17385 data points (98.96%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6090 additional data points (34.67%) excluded by precipitation filter (6090
 data points = 34.67 % in total)
6090 data points (34.67%) excluded in total
11478 valid data points (65.33%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-xTL-2020”

Quality control:
TA: 617 data points (3.52%) set to NA
H: 1633 data points (9.32%) set to NA
LE: 1671 data points (9.54%) set to NA
NEE: 2474 data points (14.12%) set to NA
-------------------------------------------------------------------
Data filtering:
14352 data points (81.92%) excluded by growing season filter
1492 additional data points (8.52%) excluded by precipitation filter (6830
 data points = 38.98 % in total)
15844 data points (90.43%) excluded in total
1676 valid data points (9.57%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 617 data points (3.52%) set to NA
H: 1633 data points (9.32%) set to NA
LE: 1671 data points (9.54%) set to NA
NEE: 2474 data points (14.12%) set to NA
-------------------------------------------------------------------
Data filtering:
14352 data points (81.92%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14352 data points (81.92%) excluded in total
3168 valid data points (18.08%) remaining.

New sEddyProc class for site 'US-xTL'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 120.15.

Regression of reference temperature R_ref for 7 periods.

Quality control:
TA: 722 data points (4.12%) set to NA
H: 2184 data points (12.47%) set to NA
LE: 2240 data points (12.79%) set to NA
NEE: 2782 data points (15.88%) set to NA
-------------------------------------------------------------------
Data filtering:
14064 data points (80.27%) excluded by growing season filter
1740 additional data points (9.93%) excluded by precipitation filter (6424
 data points = 36.67 % in total)
15804 data points (90.21%) excluded in total
1716 valid data points (9.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 722 data points (4.12%) set to NA
H: 2184 data points (12.47%) set to NA
LE: 2240 data points (12.79%) set to NA
NEE: 2782 data points (15.88%) set to NA
-------------------------------------------------------------------
Data filtering:
14064 data points (80.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
14064 data points (80.27%) excluded in total
3456 valid data points (19.73%) remaining.

New sEddyProc class for site 'US-xTL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xTL-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 223 data points (1.27%) set to NA
H: 1375 data points (7.85%) set to NA
LE: 1436 data points (8.2%) set to NA
NEE: 1977 data points (11.28%) set to NA
-------------------------------------------------------------------
Data filtering:
12864 data points (73.42%) excluded by growing season filter
2072 additional data points (11.83%) excluded by precipitation filter (6482
 data points = 37 % in total)
14936 data points (85.25%) excluded in total
2584 valid data points (14.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 223 data points (1.27%) set to NA
H: 1375 data points (7.85%) set to NA
LE: 1436 data points (8.2%) set to NA
NEE: 1977 data points (11.28%) set to NA
-------------------------------------------------------------------
Data filtering:
12864 data points (73.42%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12864 data points (73.42%) excluded in total
4656 valid data points (26.58%) remaining.

New sEddyProc class for site 'US-xTL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xTL-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 140 data points (0.8%) set to NA
H: 385 data points (2.19%) set to NA
LE: 399 data points (2.27%) set to NA
NEE: 1396 data points (7.95%) set to NA
-------------------------------------------------------------------
Data filtering:
13920 data points (79.23%) excluded by growing season filter
1670 additional data points (9.51%) excluded by precipitation filter (6596
 data points = 37.55 % in total)
15590 data points (88.74%) excluded in total
1978 valid data points (11.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 140 data points (0.8%) set to NA
H: 385 data points (2.19%) set to NA
LE: 399 data points (2.27%) set to NA
NEE: 1396 data points (7.95%) set to NA
-------------------------------------------------------------------
Data filtering:
13920 data points (79.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
13920 data points (79.23%) excluded in total
3648 valid data points (20.77%) remaining.

New sEddyProc class for site 'US-xTL'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xTL-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[323/329] Processing: US-xTR

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xTR | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 52 data points (0.3%) set to NA
H: 165 data points (0.94%) set to NA
LE: 167 data points (0.95%) set to NA
NEE: 465 data points (2.65%) set to NA
-------------------------------------------------------------------
Data filtering:
11328 data points (64.66%) excluded by growing season filter
3508 additional data points (20.02%) excluded by precipitation filter (7952
 data points = 45.39 % in total)
14836 data points (84.68%) excluded in total
2684 valid data points (15.32%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 52 data points (0.3%) set to NA
H: 165 data points (0.94%) set to NA
LE: 167 data points (0.95%) set to NA
NEE: 465 data points (2.65%) set to NA
-------------------------------------------------------------------
Data filtering:
11328 data points (64.66%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11328 data points (64.66%) excluded in total
6192 valid data points (35.34%) remaining.

New sEddyProc class for site 'US-xTR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xTR-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 37 data points (0.21%) set to NA
H: 3056 data points (17.4%) set to NA
LE: 3036 data points (17.28%) set to NA
NEE: 3365 data points (19.15%) set to NA
-------------------------------------------------------------------
Data filtering:
11664 data points (66.39%) excluded by growing season filter
1926 additional data points (10.96%) excluded by precipitation filter (4736
 data points = 26.96 % in total)
13590 data points (77.36%) excluded in total
3978 valid data points (22.64%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 37 data points (0.21%) set to NA
H: 3056 data points (17.4%) set to NA
LE: 3036 data points (17.28%) set to NA
NEE: 3365 data points (19.15%) set to NA
-------------------------------------------------------------------
Data filtering:
11664 data points (66.39%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11664 data points (66.39%) excluded in total
5904 valid data points (33.61%) remaining.

New sEddyProc class for site 'US-xTR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xTR-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 77 data points (0.44%) set to NA
H: 108 data points (0.62%) set to NA
LE: 112 data points (0.64%) set to NA
NEE: 490 data points (2.8%) set to NA
-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
2317 additional data points (13.22%) excluded by precipitation filter (5230
 data points = 29.85 % in total)
13549 data points (77.33%) excluded in total
3971 valid data points (22.67%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 77 data points (0.44%) set to NA
H: 108 data points (0.62%) set to NA
LE: 112 data points (0.64%) set to NA
NEE: 490 data points (2.8%) set to NA
-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11232 data points (64.11%) excluded in total
6288 valid data points (35.89%) remaining.

New sEddyProc class for site 'US-xTR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xTR-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 20 data points (0.11%) set to NA
H: 185 data points (1.06%) set to NA
LE: 188 data points (1.07%) set to NA
NEE: 669 data points (3.82%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
2291 additional data points (13.08%) excluded by precipitation filter (5242
 data points = 29.92 % in total)
13427 data points (76.64%) excluded in total
4093 valid data points (23.36%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 20 data points (0.11%) set to NA
H: 185 data points (1.06%) set to NA
LE: 188 data points (1.07%) set to NA
NEE: 669 data points (3.82%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.56%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11136 data points (63.56%) excluded in total
6384 valid data points (36.44%) remaining.

New sEddyProc class for site 'US-xTR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xTR-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 12 data points (0.07%) set to NA
H: 1475 data points (8.42%) set to NA
LE: 1476 data points (8.42%) set to NA
NEE: 2035 data points (11.62%) set to NA
-------------------------------------------------------------------
Data filtering:
11376 data points (64.93%) excluded by growing season filter
1660 additional data points (9.47%) excluded by precipitation filter (5072
 data points = 28.95 % in total)
13036 data points (74.41%) excluded in total
4484 valid data points (25.59%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 12 data points (0.07%) set to NA
H: 1475 data points (8.42%) set to NA
LE: 1476 data points (8.42%) set to NA
NEE: 2035 data points (11.62%) set to NA
-------------------------------------------------------------------
Data filtering:
11376 data points (64.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11376 data points (64.93%) excluded in total
6144 valid data points (35.07%) remaining.

New sEddyProc class for site 'US-xTR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xTR-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 17 data points (0.1%) set to NA
H: 1263 data points (7.19%) set to NA
LE: 1255 data points (7.14%) set to NA
NEE: 8311 data points (47.31%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 42”

-------------------------------------------------------------------
Data filtering:
6336 data points (36.07%) excluded by growing season filter
3963 additional data points (22.56%) excluded by precipitation filter (5553
 data points = 31.61 % in total)
10299 data points (58.62%) excluded in total
7269 valid data points (41.38%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 17 data points (0.1%) set to NA
H: 1263 data points (7.19%) set to NA
LE: 1255 data points (7.14%) set to NA
NEE: 8311 data points (47.31%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 42”

-------------------------------------------------------------------
Data filtering:
6336 data points (36.07%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
6336 data points (36.07%) excluded in total
11232 valid data points (63.93%) remaining.

New sEddyProc class for site 'US-xTR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xTR-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[324/329] Processing: US-xUK

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xUK | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 517 data points (2.95%) set to NA
H: 17383 data points (99.22%) set to NA
LE: 17383 data points (99.22%) set to NA
NEE: 17384 data points (99.22%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
5511 additional data points (31.46%) excluded by precipitation filter (5511
 data points = 31.46 % in total)
5511 data points (31.46%) excluded in total
12009 valid data points (68.54%) remaining.

Warning message in EFPcalc_year(dat_yr, site_id, yr, lat, lon, elevation, timezone):
“  Too few daytime records (0) for US-xUK-2019”

Quality control:
TA: 284 data points (1.62%) set to NA
H: 706 data points (4.02%) set to NA
LE: 743 data points (4.23%) set to NA
NEE: 3385 data points (19.27%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.39%) excluded by growing season filter
1792 additional data points (10.2%) excluded by precipitation filter (3923
 data points = 22.33 % in total)
12928 data points (73.59%) excluded in total
4640 valid data points (26.41%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 284 data points (1.62%) set to NA
H: 706 data points (4.02%) set to NA
LE: 743 data points (4.23%) set to NA
NEE: 3385 data points (19.27%) set to NA
-------------------------------------------------------------------
Data filtering:
11136 data points (63.39%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11136 data points (63.39%) excluded in total
6432 valid data points (36.61%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -54, -56 ...”
New sEddyProc class for site 'US-xUK'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -54, -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 1 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xUK-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 123 data points (0.7%) set to NA
H: 305 data points (1.74%) set to NA
LE: 346 data points (1.97%) set to NA
NEE: 1965 data points (11.22%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
2489 additional data points (14.21%) excluded by precipitation filter (4073
 data points = 23.25 % in total)
11705 data points (66.81%) excluded in total
5815 valid data points (33.19%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 123 data points (0.7%) set to NA
H: 305 data points (1.74%) set to NA
LE: 346 data points (1.97%) set to NA
NEE: 1965 data points (11.22%) set to NA
-------------------------------------------------------------------
Data filtering:
9216 data points (52.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9216 data points (52.6%) excluded in total
8304 valid data points (47.4%) remaining.

New sEddyProc class for site 'US-xUK'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xUK-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 208 data points (1.19%) set to NA
H: 335 data points (1.91%) set to NA
LE: 345 data points (1.97%) set to NA
NEE: 828 data points (4.73%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.27%) excluded by growing season filter
2009 additional data points (11.47%) excluded by precipitation filter (3865
 data points = 22.06 % in total)
12569 data points (71.74%) excluded in total
4951 valid data points (28.26%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 208 data points (1.19%) set to NA
H: 335 data points (1.91%) set to NA
LE: 345 data points (1.97%) set to NA
NEE: 828 data points (4.73%) set to NA
-------------------------------------------------------------------
Data filtering:
10560 data points (60.27%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10560 data points (60.27%) excluded in total
6960 valid data points (39.73%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -68 ...”
New sEddyProc class for site 'US-xUK'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -68 ...”
Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 132.26.

Regression of reference temperature R_ref for 2 periods.

Quality control:
TA: 28 data points (0.16%) set to NA
H: 419 data points (2.39%) set to NA
LE: 432 data points (2.47%) set to NA
NEE: 830 data points (4.74%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.89%) excluded by growing season filter
1723 additional data points (9.83%) excluded by precipitation filter (4235
 data points = 24.17 % in total)
11515 data points (65.72%) excluded in total
6005 valid data points (34.28%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 28 data points (0.16%) set to NA
H: 419 data points (2.39%) set to NA
LE: 432 data points (2.47%) set to NA
NEE: 830 data points (4.74%) set to NA
-------------------------------------------------------------------
Data filtering:
9792 data points (55.89%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9792 data points (55.89%) excluded in total
7728 valid data points (44.11%) remaining.

New sEddyProc class for site 'US-xUK'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xUK-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 32 data points (0.18%) set to NA
H: 135 data points (0.77%) set to NA
LE: 127 data points (0.72%) set to NA
NEE: 626 data points (3.56%) set to NA
-------------------------------------------------------------------
Data filtering:
9696 data points (55.19%) excluded by growing season filter
2451 additional data points (13.95%) excluded by precipitation filter (4052
 data points = 23.06 % in total)
12147 data points (69.14%) excluded in total
5421 valid data points (30.86%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 32 data points (0.18%) set to NA
H: 135 data points (0.77%) set to NA
LE: 127 data points (0.72%) set to NA
NEE: 626 data points (3.56%) set to NA
-------------------------------------------------------------------
Data filtering:
9696 data points (55.19%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9696 data points (55.19%) excluded in total
7872 valid data points (44.81%) remaining.

New sEddyProc class for site 'US-xUK'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xUK-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[325/329] Processing: US-xUN

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xUN | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 198 data points (1.13%) set to NA
H: 717 data points (4.09%) set to NA
LE: 749 data points (4.28%) set to NA
NEE: 1342 data points (7.66%) set to NA
-------------------------------------------------------------------
Data filtering:
11712 data points (66.85%) excluded by growing season filter
2253 additional data points (12.86%) excluded by precipitation filter (6264
 data points = 35.75 % in total)
13965 data points (79.71%) excluded in total
3555 valid data points (20.29%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 198 data points (1.13%) set to NA
H: 717 data points (4.09%) set to NA
LE: 749 data points (4.28%) set to NA
NEE: 1342 data points (7.66%) set to NA
-------------------------------------------------------------------
Data filtering:
11712 data points (66.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11712 data points (66.85%) excluded in total
5808 valid data points (33.15%) remaining.

New sEddyProc class for site 'US-xUN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 5 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xUN-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 25 data points (0.14%) set to NA
H: 179 data points (1.02%) set to NA
LE: 209 data points (1.19%) set to NA
NEE: 1350 data points (7.68%) set to NA
-------------------------------------------------------------------
Data filtering:
11520 data points (65.57%) excluded by growing season filter
2084 additional data points (11.86%) excluded by precipitation filter (5264
 data points = 29.96 % in total)
13604 data points (77.44%) excluded in total
3964 valid data points (22.56%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 25 data points (0.14%) set to NA
H: 179 data points (1.02%) set to NA
LE: 209 data points (1.19%) set to NA
NEE: 1350 data points (7.68%) set to NA
-------------------------------------------------------------------
Data filtering:
11520 data points (65.57%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11520 data points (65.57%) excluded in total
6048 valid data points (34.43%) remaining.

New sEddyProc class for site 'US-xUN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xUN-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1662 data points (9.49%) set to NA
H: 1787 data points (10.2%) set to NA
LE: 1816 data points (10.37%) set to NA
NEE: 2127 data points (12.14%) set to NA
-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
2471 additional data points (14.1%) excluded by precipitation filter (6058
 data points = 34.58 % in total)
13703 data points (78.21%) excluded in total
3817 valid data points (21.79%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1662 data points (9.49%) set to NA
H: 1787 data points (10.2%) set to NA
LE: 1816 data points (10.37%) set to NA
NEE: 2127 data points (12.14%) set to NA
-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11232 data points (64.11%) excluded in total
6288 valid data points (35.89%) remaining.

New sEddyProc class for site 'US-xUN'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 80.53.

Regression of reference temperature R_ref for 13 periods.

Quality control:
TA: 125 data points (0.71%) set to NA
H: 342 data points (1.95%) set to NA
LE: 377 data points (2.15%) set to NA
NEE: 739 data points (4.22%) set to NA
-------------------------------------------------------------------
Data filtering:
11280 data points (64.38%) excluded by growing season filter
2424 additional data points (13.84%) excluded by precipitation filter (5777
 data points = 32.97 % in total)
13704 data points (78.22%) excluded in total
3816 valid data points (21.78%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 125 data points (0.71%) set to NA
H: 342 data points (1.95%) set to NA
LE: 377 data points (2.15%) set to NA
NEE: 739 data points (4.22%) set to NA
-------------------------------------------------------------------
Data filtering:
11280 data points (64.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11280 data points (64.38%) excluded in total
6240 valid data points (35.62%) remaining.

New sEddyProc class for site 'US-xUN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 1 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xUN-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 180 data points (1.03%) set to NA
H: 378 data points (2.16%) set to NA
LE: 384 data points (2.19%) set to NA
NEE: 837 data points (4.78%) set to NA
-------------------------------------------------------------------
Data filtering:
11280 data points (64.38%) excluded by growing season filter
1871 additional data points (10.68%) excluded by precipitation filter (5206
 data points = 29.71 % in total)
13151 data points (75.06%) excluded in total
4369 valid data points (24.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 180 data points (1.03%) set to NA
H: 378 data points (2.16%) set to NA
LE: 384 data points (2.19%) set to NA
NEE: 837 data points (4.78%) set to NA
-------------------------------------------------------------------
Data filtering:
11280 data points (64.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11280 data points (64.38%) excluded in total
6240 valid data points (35.62%) remaining.

New sEddyProc class for site 'US-xUN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xUN-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 83 data points (0.47%) set to NA
H: 141 data points (0.8%) set to NA
LE: 144 data points (0.82%) set to NA
NEE: 504 data points (2.87%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.02%) excluded by growing season filter
2417 additional data points (13.76%) excluded by precipitation filter (5341
 data points = 30.4 % in total)
13313 data points (75.78%) excluded in total
4255 valid data points (24.22%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 83 data points (0.47%) set to NA
H: 141 data points (0.8%) set to NA
LE: 144 data points (0.82%) set to NA
NEE: 504 data points (2.87%) set to NA
-------------------------------------------------------------------
Data filtering:
10896 data points (62.02%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10896 data points (62.02%) excluded in total
6672 valid data points (37.98%) remaining.

New sEddyProc class for site 'US-xUN'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 3 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xUN-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[326/329] Processing: US-xWR

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xWR | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 22 data points (0.13%) set to NA
H: 395 data points (2.25%) set to NA
LE: 414 data points (2.36%) set to NA
NEE: 1248 data points (7.12%) set to NA
-------------------------------------------------------------------
Data filtering:
5232 data points (29.86%) excluded by growing season filter
3852 additional data points (21.99%) excluded by precipitation filter (6927
 data points = 39.54 % in total)
9084 data points (51.85%) excluded in total
8436 valid data points (48.15%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 22 data points (0.13%) set to NA
H: 395 data points (2.25%) set to NA
LE: 414 data points (2.36%) set to NA
NEE: 1248 data points (7.12%) set to NA
-------------------------------------------------------------------
Data filtering:
5232 data points (29.86%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5232 data points (29.86%) excluded in total
12288 valid data points (70.14%) remaining.

New sEddyProc class for site 'US-xWR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xWR-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 33 data points (0.19%) set to NA
H: 1844 data points (10.5%) set to NA
LE: 1815 data points (10.33%) set to NA
NEE: 2087 data points (11.88%) set to NA
-------------------------------------------------------------------
Data filtering:
5376 data points (30.6%) excluded by growing season filter
3586 additional data points (20.41%) excluded by precipitation filter (7556
 data points = 43.01 % in total)
8962 data points (51.01%) excluded in total
8606 valid data points (48.99%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 33 data points (0.19%) set to NA
H: 1844 data points (10.5%) set to NA
LE: 1815 data points (10.33%) set to NA
NEE: 2087 data points (11.88%) set to NA
-------------------------------------------------------------------
Data filtering:
5376 data points (30.6%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5376 data points (30.6%) excluded in total
12192 valid data points (69.4%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -53, -56 ...”
New sEddyProc class for site 'US-xWR'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -53, -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xWR-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 61 data points (0.35%) set to NA
H: 285 data points (1.63%) set to NA
LE: 286 data points (1.63%) set to NA
NEE: 583 data points (3.33%) set to NA
-------------------------------------------------------------------
Data filtering:
5472 data points (31.23%) excluded by growing season filter
3304 additional data points (18.86%) excluded by precipitation filter (7855
 data points = 44.83 % in total)
8776 data points (50.09%) excluded in total
8744 valid data points (49.91%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 61 data points (0.35%) set to NA
H: 285 data points (1.63%) set to NA
LE: 286 data points (1.63%) set to NA
NEE: 583 data points (3.33%) set to NA
-------------------------------------------------------------------
Data filtering:
5472 data points (31.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5472 data points (31.23%) excluded in total
12048 valid data points (68.77%) remaining.

New sEddyProc class for site 'US-xWR'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xWR-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 595 data points (3.4%) set to NA
H: 2168 data points (12.37%) set to NA
LE: 2208 data points (12.6%) set to NA
NEE: 2675 data points (15.27%) set to NA
-------------------------------------------------------------------
Data filtering:
5424 data points (30.96%) excluded by growing season filter
3929 additional data points (22.43%) excluded by precipitation filter (6733
 data points = 38.43 % in total)
9353 data points (53.38%) excluded in total
8167 valid data points (46.62%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 595 data points (3.4%) set to NA
H: 2168 data points (12.37%) set to NA
LE: 2208 data points (12.6%) set to NA
NEE: 2675 data points (15.27%) set to NA
-------------------------------------------------------------------
Data filtering:
5424 data points (30.96%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5424 data points (30.96%) excluded in total
12096 valid data points (69.04%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -79, -56 ...”
New sEddyProc class for site 'US-xWR'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -79, -56 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 9 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xWR-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 66 data points (0.38%) set to NA
H: 749 data points (4.28%) set to NA
LE: 718 data points (4.1%) set to NA
NEE: 4658 data points (26.59%) set to NA
-------------------------------------------------------------------
Data filtering:
7824 data points (44.66%) excluded by growing season filter
2013 additional data points (11.49%) excluded by precipitation filter (6736
 data points = 38.45 % in total)
9837 data points (56.15%) excluded in total
7683 valid data points (43.85%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 66 data points (0.38%) set to NA
H: 749 data points (4.28%) set to NA
LE: 718 data points (4.1%) set to NA
NEE: 4658 data points (26.59%) set to NA
-------------------------------------------------------------------
Data filtering:
7824 data points (44.66%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7824 data points (44.66%) excluded in total
9696 valid data points (55.34%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -51, -52 ...”
New sEddyProc class for site 'US-xWR'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 2 cases! Invalid values with 'NEE < -50': -51, -52 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xWR-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 24 data points (0.14%) set to NA
H: 289 data points (1.65%) set to NA
LE: 572 data points (3.26%) set to NA
NEE: 636 data points (3.62%) set to NA
-------------------------------------------------------------------
Data filtering:
5664 data points (32.24%) excluded by growing season filter
3378 additional data points (19.23%) excluded by precipitation filter (7826
 data points = 44.55 % in total)
9042 data points (51.47%) excluded in total
8526 valid data points (48.53%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 24 data points (0.14%) set to NA
H: 289 data points (1.65%) set to NA
LE: 572 data points (3.26%) set to NA
NEE: 636 data points (3.62%) set to NA
-------------------------------------------------------------------
Data filtering:
5664 data points (32.24%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
5664 data points (32.24%) excluded in total
11904 valid data points (67.76%) remaining.

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sEddyProc.initialize:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -61 ...”
New sEddyProc class for site 'US-xWR'

Warning message in fCheckOutsideRange(Data.F, VarName.V.s[v.i], c("<", -50), SubCallFunc.s):
“sMRFluxPartition:::fCheckColPlausibility:::fCheckOutsideRange::: Variable outside (plausible) range in 1 cases! Invalid values with 'NEE < -50': -61 ...”
Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xWR-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[327/329] Processing: US-xYE

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: US-xYE | Years: 2019, 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 344 data points (1.96%) set to NA
H: 2217 data points (12.65%) set to NA
LE: 2222 data points (12.68%) set to NA
NEE: 5357 data points (30.58%) set to NA
-------------------------------------------------------------------
Data filtering:
12048 data points (68.77%) excluded by growing season filter
2610 additional data points (14.9%) excluded by precipitation filter (7410
 data points = 42.29 % in total)
14658 data points (83.66%) excluded in total
2862 valid data points (16.34%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 344 data points (1.96%) set to NA
H: 2217 data points (12.65%) set to NA
LE: 2222 data points (12.68%) set to NA
NEE: 5357 data points (30.58%) set to NA
-------------------------------------------------------------------
Data filtering:
12048 data points (68.77%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12048 data points (68.77%) excluded in total
5472 valid data points (31.23%) remaining.

New sEddyProc class for site 'US-xYE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xYE-2019: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 74 data points (0.42%) set to NA
H: 11019 data points (62.72%) set to NA
LE: 11028 data points (62.77%) set to NA
NEE: 14608 data points (83.15%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
6730 additional data points (38.31%) excluded by precipitation filter (6730
 data points = 38.31 % in total)
6730 data points (38.31%) excluded in total
10838 valid data points (61.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 74 data points (0.42%) set to NA
H: 11019 data points (62.72%) set to NA
LE: 11028 data points (62.77%) set to NA
NEE: 14608 data points (83.15%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“number of available GPPd data is less than half the total number of days per year. Filter is not applied!”

-------------------------------------------------------------------
Data filtering:
0 data points (0%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
0 data points (0%) excluded in total
17568 valid data points (100%) remaining.

New sEddyProc class for site 'US-xYE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xYE-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 179 data points (1.02%) set to NA
H: 3965 data points (22.63%) set to NA
LE: 3969 data points (22.65%) set to NA
NEE: 5395 data points (30.79%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 22”

-------------------------------------------------------------------
Data filtering:
11712 data points (66.85%) excluded by growing season filter
1658 additional data points (9.46%) excluded by precipitation filter (5588
 data points = 31.89 % in total)
13370 data points (76.31%) excluded in total
4150 valid data points (23.69%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 179 data points (1.02%) set to NA
H: 3965 data points (22.63%) set to NA
LE: 3969 data points (22.65%) set to NA
NEE: 5395 data points (30.79%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 22”

-------------------------------------------------------------------
Data filtering:
11712 data points (66.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11712 data points (66.85%) excluded in total
5808 valid data points (33.15%) remaining.

New sEddyProc class for site 'US-xYE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 4 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xYE-2021: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 372 data points (2.12%) set to NA
H: 1094 data points (6.24%) set to NA
LE: 1110 data points (6.34%) set to NA
NEE: 2989 data points (17.06%) set to NA
-------------------------------------------------------------------
Data filtering:
12288 data points (70.14%) excluded by growing season filter
2404 additional data points (13.72%) excluded by precipitation filter (8214
 data points = 46.88 % in total)
14692 data points (83.86%) excluded in total
2828 valid data points (16.14%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 372 data points (2.12%) set to NA
H: 1094 data points (6.24%) set to NA
LE: 1110 data points (6.34%) set to NA
NEE: 2989 data points (17.06%) set to NA
-------------------------------------------------------------------
Data filtering:
12288 data points (70.14%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12288 data points (70.14%) excluded in total
5232 valid data points (29.86%) remaining.

New sEddyProc class for site 'US-xYE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 2 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xYE-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 84 data points (0.48%) set to NA
H: 6938 data points (39.6%) set to NA
LE: 6961 data points (39.73%) set to NA
NEE: 8176 data points (46.67%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 74”

-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
3176 additional data points (18.13%) excluded by precipitation filter (8116
 data points = 46.32 % in total)
14408 data points (82.24%) excluded in total
3112 valid data points (17.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 84 data points (0.48%) set to NA
H: 6938 data points (39.6%) set to NA
LE: 6961 data points (39.73%) set to NA
NEE: 8176 data points (46.67%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 74”

-------------------------------------------------------------------
Data filtering:
11232 data points (64.11%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11232 data points (64.11%) excluded in total
6288 valid data points (35.89%) remaining.

New sEddyProc class for site 'US-xYE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xYE-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 23 data points (0.13%) set to NA
H: 2471 data points (14.07%) set to NA
LE: 2486 data points (14.15%) set to NA
NEE: 3511 data points (19.99%) set to NA
-------------------------------------------------------------------
Data filtering:
11520 data points (65.57%) excluded by growing season filter
2448 additional data points (13.93%) excluded by precipitation filter (6536
 data points = 37.2 % in total)
13968 data points (79.51%) excluded in total
3600 valid data points (20.49%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 23 data points (0.13%) set to NA
H: 2471 data points (14.07%) set to NA
LE: 2486 data points (14.15%) set to NA
NEE: 3511 data points (19.99%) set to NA
-------------------------------------------------------------------
Data filtering:
11520 data points (65.57%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11520 data points (65.57%) excluded in total
6048 valid data points (34.43%) remaining.

New sEddyProc class for site 'US-xYE'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 0 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for US-xYE-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

[328/329] Processing: ZA-BfK

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ZA-BfK | Years: 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 7132 data points (40.6%) set to NA
H: 8099 data points (46.1%) set to NA
LE: 8202 data points (46.69%) set to NA
NEE: 8792 data points (50.05%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 117”

-------------------------------------------------------------------
Data filtering:
7104 data points (40.44%) excluded by growing season filter
3623 additional data points (20.62%) excluded by precipitation filter (4325
 data points = 24.62 % in total)
10727 data points (61.06%) excluded in total
6841 valid data points (38.94%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 7132 data points (40.6%) set to NA
H: 8099 data points (46.1%) set to NA
LE: 8202 data points (46.69%) set to NA
NEE: 8792 data points (50.05%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 117”

-------------------------------------------------------------------
Data filtering:
7104 data points (40.44%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7104 data points (40.44%) excluded in total
10464 valid data points (59.56%) remaining.

New sEddyProc class for site 'ZA-BfK'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 190.33.

Regression of reference temperature R_ref for 19 periods.

Quality control:
TA: 888 data points (5.07%) set to NA
H: 1327 data points (7.57%) set to NA
LE: 1372 data points (7.83%) set to NA
NEE: 2011 data points (11.48%) set to NA
-------------------------------------------------------------------
Data filtering:
8976 data points (51.23%) excluded by growing season filter
2339 additional data points (13.35%) excluded by precipitation filter (3287
 data points = 18.76 % in total)
11315 data points (64.58%) excluded in total
6205 valid data points (35.42%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 888 data points (5.07%) set to NA
H: 1327 data points (7.57%) set to NA
LE: 1372 data points (7.83%) set to NA
NEE: 2011 data points (11.48%) set to NA
-------------------------------------------------------------------
Data filtering:
8976 data points (51.23%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8976 data points (51.23%) excluded in total
8544 valid data points (48.77%) remaining.

New sEddyProc class for site 'ZA-BfK'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 312.77.

Regression of reference temperature R_ref for 6 periods.

Quality control:
TA: 1039 data points (5.93%) set to NA
H: 1660 data points (9.47%) set to NA
LE: 1731 data points (9.88%) set to NA
NEE: 3007 data points (17.16%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.85%) excluded by growing season filter
3570 additional data points (20.38%) excluded by precipitation filter (4564
 data points = 26.05 % in total)
11778 data points (67.23%) excluded in total
5742 valid data points (32.77%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1039 data points (5.93%) set to NA
H: 1660 data points (9.47%) set to NA
LE: 1731 data points (9.88%) set to NA
NEE: 3007 data points (17.16%) set to NA
-------------------------------------------------------------------
Data filtering:
8208 data points (46.85%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8208 data points (46.85%) excluded in total
9312 valid data points (53.15%) remaining.

New sEddyProc class for site 'ZA-BfK'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 7 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ZA-BfK-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 490 data points (2.8%) set to NA
H: 1167 data points (6.66%) set to NA
LE: 1274 data points (7.27%) set to NA
NEE: 2691 data points (15.36%) set to NA
-------------------------------------------------------------------
Data filtering:
11376 data points (64.93%) excluded by growing season filter
1828 additional data points (10.43%) excluded by precipitation filter (3460
 data points = 19.75 % in total)
13204 data points (75.37%) excluded in total
4316 valid data points (24.63%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 490 data points (2.8%) set to NA
H: 1167 data points (6.66%) set to NA
LE: 1274 data points (7.27%) set to NA
NEE: 2691 data points (15.36%) set to NA
-------------------------------------------------------------------
Data filtering:
11376 data points (64.93%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
11376 data points (64.93%) excluded in total
6144 valid data points (35.07%) remaining.

New sEddyProc class for site 'ZA-BfK'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 6 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ZA-BfK-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1168 data points (6.65%) set to NA
H: 1657 data points (9.43%) set to NA
LE: 1737 data points (9.89%) set to NA
NEE: 2791 data points (15.89%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.38%) excluded by growing season filter
1577 additional data points (8.98%) excluded by precipitation filter (2596
 data points = 14.78 % in total)
11657 data points (66.35%) excluded in total
5911 valid data points (33.65%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1168 data points (6.65%) set to NA
H: 1657 data points (9.43%) set to NA
LE: 1737 data points (9.89%) set to NA
NEE: 2791 data points (15.89%) set to NA
-------------------------------------------------------------------
Data filtering:
10080 data points (57.38%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10080 data points (57.38%) excluded in total
7488 valid data points (42.62%) remaining.

New sEddyProc class for site 'ZA-BfK'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 303.96.

Regression of reference temperature R_ref for 8 periods.

[329/329] Processing: ZA-BfS

Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message in CPL_crs_from_input(x):
“GDAL Error 1: PROJ: proj_create_from_database: /home/nk1125/miniconda3/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 2 whereas a number >= 4 is expected. It comes from another PROJ installation.”
Warning message:
“tz supplied is different from that in 'dt'. Overwriting with tz.”

  Site: ZA-BfS | Years: 2020, 2021, 2022, 2023, 2024
Quality control:
TA: 3763 data points (21.42%) set to NA
H: 3949 data points (22.48%) set to NA
LE: 3997 data points (22.75%) set to NA
NEE: 4653 data points (26.49%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 65”

-------------------------------------------------------------------
Data filtering:
8688 data points (49.45%) excluded by growing season filter
3604 additional data points (20.51%) excluded by precipitation filter (4315
 data points = 24.56 % in total)
12292 data points (69.97%) excluded in total
5276 valid data points (30.03%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 3763 data points (21.42%) set to NA
H: 3949 data points (22.48%) set to NA
LE: 3997 data points (22.75%) set to NA
NEE: 4653 data points (26.49%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 65”

-------------------------------------------------------------------
Data filtering:
8688 data points (49.45%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
8688 data points (49.45%) excluded in total
8880 valid data points (50.55%) remaining.

New sEddyProc class for site 'ZA-BfS'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 10 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ZA-BfS-2020: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 1439 data points (8.21%) set to NA
H: 1986 data points (11.34%) set to NA
LE: 2059 data points (11.75%) set to NA
NEE: 3091 data points (17.64%) set to NA
-------------------------------------------------------------------
Data filtering:
9024 data points (51.51%) excluded by growing season filter
2232 additional data points (12.74%) excluded by precipitation filter (2875
 data points = 16.41 % in total)
11256 data points (64.25%) excluded in total
6264 valid data points (35.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1439 data points (8.21%) set to NA
H: 1986 data points (11.34%) set to NA
LE: 2059 data points (11.75%) set to NA
NEE: 3091 data points (17.64%) set to NA
-------------------------------------------------------------------
Data filtering:
9024 data points (51.51%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
9024 data points (51.51%) excluded in total
8496 valid data points (48.49%) remaining.

New sEddyProc class for site 'ZA-BfS'

Start flux partitioning for variable NEE with temperature TA.

Estimate of the temperature sensitivity E_0 from short term data: 234.26.

Regression of reference temperature R_ref for 15 periods.

Quality control:
TA: 1490 data points (8.5%) set to NA
H: 1689 data points (9.64%) set to NA
LE: 1692 data points (9.66%) set to NA
NEE: 2185 data points (12.47%) set to NA
-------------------------------------------------------------------
Data filtering:
7152 data points (40.82%) excluded by growing season filter
2297 additional data points (13.11%) excluded by precipitation filter (2873
 data points = 16.4 % in total)
9449 data points (53.93%) excluded in total
8071 valid data points (46.07%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 1490 data points (8.5%) set to NA
H: 1689 data points (9.64%) set to NA
LE: 1692 data points (9.66%) set to NA
NEE: 2185 data points (12.47%) set to NA
-------------------------------------------------------------------
Data filtering:
7152 data points (40.82%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
7152 data points (40.82%) excluded in total
10368 valid data points (59.18%) remaining.

New sEddyProc class for site 'ZA-BfS'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 8 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ZA-BfS-2022: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 8144 data points (46.48%) set to NA
H: 8557 data points (48.84%) set to NA
LE: 8571 data points (48.92%) set to NA
NEE: 8853 data points (50.53%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 150”

-------------------------------------------------------------------
Data filtering:
10464 data points (59.73%) excluded by growing season filter
2193 additional data points (12.52%) excluded by precipitation filter (3667
 data points = 20.93 % in total)
12657 data points (72.24%) excluded in total
4863 valid data points (27.76%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 8144 data points (46.48%) set to NA
H: 8557 data points (48.84%) set to NA
LE: 8571 data points (48.92%) set to NA
NEE: 8853 data points (50.53%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 150”

-------------------------------------------------------------------
Data filtering:
10464 data points (59.73%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
10464 data points (59.73%) excluded in total
7056 valid data points (40.27%) remaining.

New sEddyProc class for site 'ZA-BfS'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 13 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ZA-BfS-2023: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Quality control:
TA: 4748 data points (27.03%) set to NA
H: 5113 data points (29.1%) set to NA
LE: 5202 data points (29.61%) set to NA
NEE: 5622 data points (32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 79”

-------------------------------------------------------------------
Data filtering:
12192 data points (69.4%) excluded by growing season filter
1028 additional data points (5.85%) excluded by precipitation filter (2872
 data points = 16.35 % in total)
13220 data points (75.25%) excluded in total
4348 valid data points (24.75%) remaining.
Note new column 'z0h' in the function output for 'bigleaf' versions > 0.7.5.
Energy storage fluxes S are not provided and set to 0.
Respiration from the leaves is ignored and set to 0.
Quality control:
TA: 4748 data points (27.03%) set to NA
H: 5113 data points (29.1%) set to NA
LE: 5202 data points (29.61%) set to NA
NEE: 5622 data points (32%) set to NA

Warning message in filter.growing.season(GPP_daily, tGPP = tGPP, ws = ws, min.int = min.int):
“Attention, there is a gap in 'GPPd' of length n = 79”

-------------------------------------------------------------------
Data filtering:
12192 data points (69.4%) excluded by growing season filter
0 additional data points (0%) excluded by precipitation filter (0 data points =
0 % in total)
12192 data points (69.4%) excluded in total
5376 valid data points (30.6%) remaining.

New sEddyProc class for site 'ZA-BfS'

Start flux partitioning for variable NEE with temperature TA.

Warning message in fRegrE0fromShortTerm(NightFlux, Temp, DayCounter, ..., MinE0 = MinE0, :
“sMRFluxPartition:::sRegrE0fromShortTerm:::fRegrE0fromShortTerm::: Less than 3 valid values for E_0 after regressing 12 periods! Aborting partitioning.
You may try relaxing the temperature range constraint by setting TempRange = 3 (instead of default 5C). See argument parsE0Regression in sMRFluxPartitioning.”
Estimate of the temperature sensitivity E_0 from short term data: -111.

  REddyProc error for ZA-BfS-2024: In argument: `mean_Rb = mean(Rb_hh, na.rm = TRUE)`.

Batch complete.
Failed sites this run: 0

## 10. Combine per-site outputs into master tables

In [11]:
# ============================================================
# 10. Combine saved outputs
# ============================================================

efp_files   <- list.files(efp_dir,   pattern = "_yearly_EFP\\.csv$",   full.names = TRUE)
meteo_files <- list.files(meteo_dir, pattern = "_monthly_meteo\\.csv$", full.names = TRUE)

all_efp_df   <- purrr::map_dfr(efp_files,   readr::read_csv, show_col_types = FALSE)
all_meteo_df <- purrr::map_dfr(meteo_files, readr::read_csv, show_col_types = FALSE)

readr::write_csv(all_efp_df,   file.path(out_dir, "ALL_SITES_YEARLY_EFP_corrected.csv"))
readr::write_csv(all_meteo_df, file.path(out_dir, "ALL_SITES_MONTHLY_METEO_corrected.csv"))

cat("Site-years in EFP table:    ", nrow(all_efp_df),   "\n")
cat("Monthly rows in meteo table:", nrow(all_meteo_df), "\n")
dplyr::glimpse(all_efp_df)

Site-years in EFP table:     1722
Monthly rows in meteo table: 20664
Rows: 1,722
Columns: 20
$ SITE_ID     <chr> "AR-TF1", "AR-TF1", "AR-TF2", "AR-TF2", "AT-Mmg", "AT-Mmg"…
$ YEAR        <dbl> 2017, 2018, 2017, 2018, 2021, 2022, 2023, 2024, 2018, 2019…
$ uWUE        <dbl> 1.3721711, 2.2942932, 0.6548226, 0.8353541, 2.4393007, 2.9…
$ WUE         <dbl> 1.8180265, 2.3813463, 0.7764370, 0.8397554, 2.8740877, 2.8…
$ ETmax       <dbl> 0.1828751, 0.1648241, 0.1664797, 0.1603725, 0.1989795, 0.2…
$ precipAvail <chr> "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "y…
$ Gavail      <chr> "no", "no", "no", "no", "no", "yes", "yes", "yes", "yes", …
$ GSmax       <dbl> 0.004534142, 0.005551693, 0.004988268, 0.009313015, 0.0079…
$ CO2avail    <chr> "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "y…
$ G1          <dbl> 2.1485846, 2.7675445, 7.9534008, 14.0036634, 2.3253668, 1.…
$ EF          <dbl> 0.5637964, 0.7910594, 0.4856848, 0.7153037, 0.4216831, 0.4…
$ EFampl      <dbl> 0.2728276, 0.2845304, 0.1322308, 0.2678948, 0.1904772, 0.1…
$ GPPsat      <dbl> 11.102377, 12.301597, 5.223131, 4.968874, 18.400181, 18.94…
$ NEPmax      <dbl> 8.869746, 9.187043, 4.059814, 4.356216, 19.263015, 17.2788…
$ Rb          <dbl> 1.149991, NA, NA, NA, 4.979469, NA, NA, NA, 2.670853, NA, …
$ Rbmax       <dbl> 1.262253, NA, NA, NA, 6.309289, NA, NA, NA, 2.679261, NA, …
$ aCUE        <dbl> 0.59977741, NA, NA, NA, -0.09542167, NA, NA, NA, 0.0557450…
$ TZ          <dbl> -3, -3, -3, -3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, …
$ nyears      <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ status      <chr> "ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok", "ok"…

## 11. Quality checks

FIX 8: Column names now match the actual output of `EFPcalc_year()`.

In [12]:
# ============================================================
# 11. Quality checks
# FIX 8: Column names updated to match EFPcalc_year() output
#         (GPPsat, NEPmax, aCUE — not NEP95, CUEeco90)
# ============================================================

# Count non-NA values per EFP
all_efp_df %>%
  summarise(
    n_sites      = n_distinct(SITE_ID),
    n_site_years = n(),
    n_ok         = sum(status == "ok", na.rm = TRUE),
    n_GPPsat     = sum(is.finite(GPPsat),  na.rm = TRUE),
    n_NEPmax     = sum(is.finite(NEPmax),  na.rm = TRUE),
    n_Rb         = sum(is.finite(Rb),      na.rm = TRUE),
    n_aCUE       = sum(is.finite(aCUE),    na.rm = TRUE),
    n_uWUE       = sum(is.finite(uWUE),    na.rm = TRUE),
    n_EF         = sum(is.finite(EF),      na.rm = TRUE),
    n_ETmax      = sum(is.finite(ETmax),   na.rm = TRUE),
    n_GSmax      = sum(is.finite(GSmax),   na.rm = TRUE)
  )

  n_sites n_site_years n_ok n_GPPsat n_NEPmax n_Rb n_aCUE n_uWUE n_EF n_ETmax
1 329     1722         1670 1357     1502     269  249    1356   1663 1667
  n_GSmax
1 1554

In [13]:
# Summary statistics by EFP
all_efp_df %>%
  filter(status == "ok") %>%
  summarise(
    across(
      c(GPPsat, NEPmax, Rb, Rbmax, aCUE, WUE, uWUE, EF, EFampl, ETmax, GSmax),
      list(
        median  = ~ median(.x, na.rm = TRUE),
        n_valid = ~ sum(is.finite(.x))
      ),
      .names = "{.col}_{.fn}"
    )
  ) %>%
  tidyr::pivot_longer(everything(),
                      names_to  = c("variable", "stat"),
                      names_sep = "_(?=[^_]+$)") %>%
  tidyr::pivot_wider(names_from = stat, values_from = value) %>%
  print(n = 30)

# A tibble: 22 × 3
   variable   median valid
   <chr>       <dbl> <dbl>
 1 GPPsat   19.5        NA
 2 GPPsat_n NA        1357
 3 NEPmax   17.7        NA
 4 NEPmax_n NA        1502
 5 Rb        2.94       NA
 6 Rb_n     NA         269
 7 Rbmax     4.23       NA
 8 Rbmax_n  NA         269
 9 aCUE      0.379      NA
10 aCUE_n   NA         249
11 WUE       2.65       NA
12 WUE_n    NA        1356
13 uWUE      2.92       NA
14 uWUE_n   NA        1356
15 EF        0.478      NA
16 EF_n     NA        1663
17 EFampl    0.204      NA
18 EFampl_n NA        1663
19 ETmax     0.194      NA
20 ETmax_n  NA        1667
21 GSmax     0.00806    NA
22 GSmax_n  NA        1554